### ISSUE TITLE
Question: Can ingress code check for parser error using v1model.p4?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1012]
Not a high priority issue, but if there is already a way to do it that works, I would be interested to know what it is.

Is there a way to write an 'if' statement in ingress control block code, in a P4_16 program using v1model.p4, that is true if there was a parser error during parsing, but false if there was no parser error?

Also, same question again, except can you write an 'if' statement where the condition is true/false depending upon whether the verifyCheckum() control found any checksum mismatches?

**Comment by mbudiu-vmw** [comment]
See https://github.com/p4lang/p4c/issues/808
There is now a way to do some of this in v1model.p4, but I am not sure whether bmv2 supports this feature yet.

**Comment by jafingerhut** [comment]
It seems I sometimes cannot remember well when I have asked similar questions before :-)

https://github.com/p4lang/behavioral-model/issues/446

**Comment by jafingerhut** [comment]
Closing this issue since I have asked it in another one.
