### ISSUE TITLE
feature: p4: initializing tables from p4 program

### ISSUE THREAD

**Issue by jrfastab** [p4lang/p4c#102]
I think this came up previously but would like to revisit.

In some architectures there are tables that can not be written to at run-time but can be programmed via firmware/ucode/etc at init time. Expressing this in P4 is not possible at the moment because the language expects all tables to be programmable at runtime.

To resolve this I have added an extension to an internal prototype compiler that accepts an initialization sequence similar to C style code. For example the following,

 table fixed_map() {
          key = {packet.parser_output : exact; }
          actions = {
                 act0;
          }
          default_action = act1(0xdeadbeef);
          size = 1024;
     } = { 1 : act0(1), 2 : act0(2), 3 : act0(3), 4 : act(4)};

Where the initialization is after the '='. Any thoughts/opinions about adding this to the language proper? The change had fairly minimal impact to both p4 programs and prototype compiler code.

Some example use cases for these fixed tables is to load balance across multiple packet pipelines in a device, provide a way for specified packets to skip certain pipeline components (encryption, etc). In many cases it is fairly difficult (impossible?) for the compiler to infer the fixed table contents from the p4 program itself.

Thanks.

**Comment by mbudiu-vmw** [comment]
This has been solved by PR #397
