### ISSUE TITLE
README cosmetic issue 

### ISSUE THREAD

**Issue by sksodhi** [p4lang/p4c#1039]
README states following as one of example commands to use 
"p4c -b bmv2-v1model-p4org simple_router.p4 -o simple_router.json"
but the target "bmv2-v1model-p4org" is no longer present in the available targets.

root@97b3a908c354:# p4c --target-help
Supported targets in "target-arch-vendor" triplet:
ebpf-v1model-p4org
bmv2-ss-p4org
bmv2-psa-p4org

root@97b3a908c354:# p4c -b bmv2-v1model-p4org simple_router.p4 -o simple_router.json
Unknown backend: bmv2-v1model-p4org          <<<<<<<<<<<<<<<<

root@97b3a908c354:# p4c --version
p4c 0.1

**Comment by mbudiu-vmw** [comment]
I have assigned @hanw , since I believe he wrote the original driver. But maybe someone else wants to pick this up.
