### ISSUE TITLE
How to use Resubmit in p4-16?

### ISSUE THREAD

**Issue by MaoJianwei** [p4lang/p4c#1043]
P4 - 16

How to use Resubmit ?
Is there any example in the tutorial or somewhere else ?

Can I put user-defined metadata into the _resubmit()_?
How can I read the put data from the pipeline of resubmitted packet?

When I use like:

`resubmit<Mao_metadata>(meta);`
or:
`resubmit(meta);`

The p4c-bm-ss will reports errors:

![qq 20171117155330](https://user-images.githubusercontent.com/12800168/32936738-6baa12a4-cbb0-11e7-9ed3-8b29776f9b7d.jpg)

**Comment by mbudiu-vmw** [comment]
This looks like a bug in the compiler, but this information is not sufficient to reproduce your error. Can you supply a small program that exhibits this symptom?

**Comment by MaoJianwei** [comment]
Could you please write an available P4-16 program as a resubmit tutorial for us?

Corresponding with this:
https://github.com/p4lang/tutorials/blob/master/examples/resubmit/p4src/resubmit.p4

**Comment by MaoJianwei** [comment]
eeee.....by the way,

This tutorial failed to resubmit too....

https://github.com/p4lang/tutorials/blob/master/examples/resubmit/p4src/resubmit.p4

**Comment by mbudiu-vmw** [comment]
This is not the right forum for example programs, you should use one of the P4 mailing lists for this purpose. Did you use this compiler to compile that program?

It would be nice if you could help us locate the bug in the compiler which caused the error message you posted last week. Can you attach a P4 program that produces the compiler error that you described above?

**Comment by MaoJianwei** [comment]
I aimed to the resubmit bug, but not the tutorial demo.

**Comment by mbudiu-vmw** [comment]
I will tag this issue as "invalid" because we don't have enough information to reproduce it.
I will leave it open for a while in the hope that we will get more information.

**Comment by JehandadKhan** [comment]
The tutorial mentioned above does not work, when debugged using the p4 debugging utility, the following is my diagnosis:

```
New event for packet 0.0
Entering action '_resubmit'
P4DBG:
New event for packet 0.0
Update for field mymeta.f1
New value is 01 (1)
P4DBG:
New event for packet 0.0
Update for field standard_metadata.resubmit_flag
New value is 00 (0)
P4DBG:
New event for packet 0.0
Exiting action '_resubmit'
P4DBG:
New event for packet 0.0
Exiting table 't_ingress_2'
P4DBG:
New event for packet 0.0
Exiting pipeline 'ingress'
```
The  ``mymeta.f1`` field is set as expected, however, the ``resubmit_flag`` metadata member is not set properly. Resulting in a resubmit failure.

Looks like a ``simple_switch`` bug. Any help would be much appreciated.

**Comment by mbudiu-vmw** [comment]
I have also filed an issue against simple_switch (bmv2).

**Comment by antoninbas** [comment]
I verified that the resubmit example in the tutorials repo now works
