### ISSUE TITLE
Usability: Displaying class name rather than pointer for Util::CompilationError exception

### ISSUE THREAD

**Issue by sksodhi** [p4lang/p4c#1048]
This small change will help folks who are writing their own backends.

root@97b3a908c354:~/p4c# git diff tools/ir-generator/irclass.cpp
diff --git a/tools/ir-generator/irclass.cpp b/tools/ir-generator/irclass.cpp
index 82c22eb..1a03712 100644
--- a/tools/ir-generator/irclass.cpp
+++ b/tools/ir-generator/irclass.cpp
@@ -45,7 +45,7 @@ IrNamespace *IrNamespace::get(IrNamespace *parent, cstring name) {
 void IrNamespace::add_class(IrClass *cl) {
     IrNamespace *ns = cl->containedIn ? cl->containedIn : &global;
     if (ns->classes[cl->name])
-        throw Util::CompilationError("%1%: Duplicate class name", cl);
+        throw Util::CompilationError("%1%: Duplicate class name", cl->name);
     else
         ns->classes[cl->name] = cl;
 }
root@97b3a908c354:~/p4c#

**Comment by mbudiu-vmw** [comment]
Why not submit a proper pull request?
You should quote code using backticks, your post has been reformatted by the markdown parser and it's hard to read.
