### ISSUE TITLE
p4c segfault when counter name and header name is the same.

### ISSUE THREAD

**Issue by rbooysen** [p4lang/p4c#1057]
p4c crashes with this error:

terminate called after throwing an instance of 'boost::exception_detail::clone_impl >'
  what():  boost::too_few_args: format-string referred to more arguments than were passed
Aborted (core dumped)

[name_clash_crash.p4.txt](https://github.com/p4lang/p4c/files/1501630/name_clash_crash.p4.txt)

**Comment by mbudiu-vmw** [comment]
I will assume that this issue can also be closed.
