### ISSUE TITLE
p4c segfault when header used in digest field list

### ISSUE THREAD

**Issue by rbooysen** [p4lang/p4c#1058]
p4c crashes with this error:

terminate called after throwing an instance of 'Util::CompilerBug'
  what():  In file: .../p4c/ir/id.h:38
[31mCompiler Bug[0m: Identifier with no name

Aborted (core dumped)

[header_in_fieldlist_crash.p4.txt](https://github.com/p4lang/p4c/files/1501635/header_in_fieldlist_crash.p4.txt)

**Comment by mbudiu-vmw** [comment]
I will assume that this issue can be closed.
