### ISSUE TITLE
Compiler Bug: Null right AFTER an error

### ISSUE THREAD

**Issue by qin-nz** [p4lang/p4c#1059]
Hi all,
I found a compiler bug again.
But this time, i use a wrong code.

I have a struct `map_meta_t` which doesn't have field `dst_psid`. And I try to use it in an action `encap_from_br` when call another action `generate_map_addr(meta.dst_psid, ... )`.
So I got an error and a compiler bug.

```
map.p4app/include/headers.p4(132): error: Structure struct map_meta_t does not have a field dst_psid
struct map_meta_t {
       ^^^^^^^^^^
map.p4app/control/mapcontrol.p4(55)
            generate_map_addr(meta.dst_ea, meta.dst_psid, p.ip6.dstAddr);
                                                ^^^^^^^^
In file: /home/dy/p4c/frontends/p4/typeChecking/typeConstraints.h:45
Compiler Bug: /home/dy/p4c/frontends/p4/typeChecking/typeConstraints.h:45: Null right
```

Maybe it's not a real bug and you won't fix it.

**Comment by jafingerhut** [comment]
It would be helpful if you could attach your complete program for which you got these errors, for us to better judge whether it is a compiler bug or not.  It isn't clear from your brief description of your program if this is the case.

**Comment by mbudiu-vmw** [comment]
I will assume that this issue can be closed.
