### ISSUE TITLE
Enhancement: Support bool, enum, error types as match key fields

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1067]
Perhaps the best approach to this is to wait until the work is done on making types like bool, enum, and error "serializable" in the P4_16 language work group, and then maybe this comes 'for free'.

**Comment by hanw** [comment]
Is this one supported in the current frontend?

**Comment by jafingerhut** [comment]
I believe the latest `p4test` does accept values of all of these types as match key fields.

P4Runtime API v1.0 has decided to limit search key fields to be `bit<W>` types for that version, although it does support more types in other places, e.g. the types of Digest extern messages.

**Comment by hesingh** [comment]
Regarding p4c p4runtime code, p4c/control-plane/typeSpecConverter.cpp does support boolean, error, and enum.  However, there is also the serializer code in the same path - this code only supports boolean with its bitwidth of 1.  The PR I have sent out to fix PSA1.1 issues in p4c and p4c p4runtime has added error and enum to the serializer.  Error has been shaken out with test P4 Programs.  I haven't bothered with enum yet.

**Comment by hesingh** [comment]
Note, p4c also has Type_SerEnum which is serializable.  p4c p4runtime does not support it in either of the two files mentioned in my prior note.  We should support Type_SerEnum.

We should find a wiki where p4runtime next release is being planned and see what we can add there.   I think, this enhancement and support for PSA 1.1 are two candidates.

**Comment by jafingerhut** [comment]
Closing this old issue.  The root issue is whether the P4Runtime API spec supports such types first.  Until it does, there is nothing p4c can do about it on its own.
