### ISSUE TITLE
Bug fix for P4_16 bmv2 JSON and P4Runtime control plane names?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1073]
As p4c-bm2-ss is now, when compiling P4_16 programs, controlPlaneName returns names like foo when foo is a table or extern or control instantiated directly inside of any top-level control block (and probably also parser, but I haven't checked that).

This leads to, in bmv2 JSON files and p4Runtime API files, conflicting names if foo is instantiated in both ingress and egress control blocks, for example.

If controlPlaneName instead returned a name like ingress.foo or egress.foo, then I think this would solve most or all of the name conflicts that currently occur between same-named things inside of different top-level controls, in both bmv2 JSON and p4Runtime API files generated by p4c-bm2-ss.

controlPlaneName already returns hierarchical names if there are one or more controls instantiated in a tree structure within ingress.  This is good, and should not change.  For example, if inside of ingress you instantiate another control with an instance name of c1, and inside c1 there is a table t1, then currently controlPlaneName returns c1.t1.  If that changed to ingress.c1.t1 (where by 'ingress' I mean whatever the instance name that the ingress control instance has in the top level package instantiation of V1Model), then that is the change I am suggesting.

I don't know how to make such a change, or whether it would break something else, but it seems worth a try.

**Comment by jafingerhut** [comment]
Even if someone could create a PR that had only the necessary changes for the names, but not tests and other things, I could run some experiments with it to investigate what else needs fixing, and perhaps update STF files, etc.

**Comment by mbudiu-vmw** [comment]
The compiler changes may not be very difficult, but we don't want to update all stf files. If we do the change in the most straightforward way all stf files for all P4-16 programs will need changes.

However, the spec says that shorter names can be used in the control plane as long as they are not ambiguous. So we need to update the program that interfaces between the stf files and the CLI to automatically convert the short names into the long forms. That program loads the entire JSON, so it knows the long names.

**Comment by jafingerhut** [comment]
I don't mind updating all stf files for P4_16 programs, if that is a clean long-term way to go.

**Comment by mbudiu-vmw** [comment]
How is this issue different from #486?

**Comment by jafingerhut** [comment]
With #486 the issue is names of fields need more global qualification.  This issue is names of tables, externs, control, parsers, etc.

**Comment by mbudiu-vmw** [comment]
I will mark this as fixed.
But the PR has not been merged yet, so we'll keep it around.

**Comment by jafingerhut** [comment]
Fix #1106 for this issue has been merged in.  Closing this issue.
