### ISSUE TITLE
Why does Deparser not support metadata?

### ISSUE THREAD

**Issue by MaoJianwei** [p4lang/p4c#1084]
![qq 20171208111704](https://user-images.githubusercontent.com/12800168/33749567-5b028756-dc09-11e7-8a1b-f63cdaecd776.jpg)

**Comment by mbudiu-vmw** [comment]
This is how the P4 v1model works (which is intended to model p4-14).
In the deparser you can only emit some headers.
The only statement you can have is a call to the emit method of the packet_out.

**Comment by jafingerhut** [comment]
The thinking here is that at the end, packets going out of the deparser to a switch port have no metadata.

If there is logic that you are thinking you would like to do in the deparser that requires the metadata, then typically you can put that code near the end of your egress control block, and get the same effect.

If you really, really want a way to pass some data in v1model to the deparser that doesn't go out on the wire, you can define one or more headers that you never emit, and put them inside the type H that goes to the deparser.

**Comment by jafingerhut** [comment]
The Portable Switch Architecture (PSA), which is unfortunately not yet implemented and available to try out (nor is the specification quite complete yet), does have metadata passed to the egress deparser.  We expect to be looking for volunteers to help implement PSA functionality in about a month or so, but realize that it is probably best done by incremental changes on top of the existing open source compiler and BMv2, so some familiarity with how one of those is implemented would be needed.

**Comment by MaoJianwei** [comment]
If we can just write packet.emit() here, why not cancel this deparser and emit packet by following the inner order of H hdr?

**Comment by mbudiu-vmw** [comment]
Maybe you don't want everything in hdr to be emitted.

**Comment by mbudiu-vmw** [comment]
Also, maybe you want them in a different order than they appear in hdr.
