### ISSUE TITLE
What is Type_ActionEnum in p4c typechecker?

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1088]
The p4c frontend IR has an IR::Type_ActionEnum, do we have a syntax for it in P4-16?

**Comment by mbudiu-vmw** [comment]
Not every ir node corresponds to syntax. This is the type of the value returned by the expression of a switch statement.

**Comment by mbudiu-vmw** [comment]
This issue is of narrow interest, so I will close it.
