### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#1093]
The compiler notifies about a syntax error,
```
bug.p4(8):syntax error, unexpected END
  if(0 == 1) { }
                ^
```
and then appears to go into an infinite loop on this P4_14 input program.
```
parser start {
  return ingress;
}    
control ingress {
  d();
}
control d {
  if(0 == 1) { }
```

**Comment by mbudiu-vmw** [comment]
@ChrisDodd @sethfowler  : I think this is a bison-related problem. The lexer reaches end of file but the parser gets into an infinite loop.

**Comment by mbudiu-vmw** [comment]
I think this has something to do with some bison rules that are supposed to handle errors, which @ChrisDodd  wrote.

**Comment by ChrisDodd** [comment]
The problem seems to be that the error recovery code tries to find the closing `}` to recover from the syntax error in the control block, but fails, getting stuck on the extra END symbol that got added at eof when the bison parser was switched to C++ mode.  I'll try to come up with a workaround.
