### ISSUE TITLE
Show sub-parsers in p4c-graphs output

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1101]
I have tried the latest p4c-graphs updates available with this recent commit, and they are very nice!  https://github.com/p4lang/p4c/commit/8357970c318ad1e65cf878b0956f6827bd9593b1

I don't see the exponential slowdown behavior that existed in the prior implementation for graphs with many paths.

The drawing of boxes for ingress and egress around sub-controls is also a very nice touch.

This issue is to request that a similar thing be done for sub-parsers.  Right now it appears that sub-parser calls are ignored in the graphs created for parsers.  Here is a test case that exhibits this behavior, and has a sub-parser that should make the parser graph significantly larger if it were included: https://github.com/jafingerhut/p4-guide/blob/master/tcp-options-parser/tcp-options-parser.p4

**Comment by mbudiu-vmw** [comment]
Each parser should be drawn in a separate file.
The call edges are not shown, however.

**Comment by jafingerhut** [comment]
Ah, you are right.  I didn't notice that.

If you don't mind a _low priority_ enhancement issue being open for a while as a suggested future nicety, we could leave this issue open.  If you'd prefer to tidy up open request to higher priority things, I don't mind closing this.

**Comment by mbudiu-vmw** [comment]
We could do something else, perhaps more useful: pass a flag -inline so that all inlining is done prior to dumping the graphs. This would work for both controls and parsers.

**Comment by mbudiu-vmw** [comment]
Since we moved inlining to the front-end this is no longer possible: the graph will be shown after inlining.
