### ISSUE TITLE
p4test --validate error

### ISSUE THREAD

**Issue by IfrahIdrees** [p4lang/p4c#1103]
Why does p4ctest --validate give the following error 

**" ../copy_to_cpu.p4(17):syntax error, unexpected IDENTIFIER "header_type" header_type ^^^^^^^^^^^ error: 1 errors encountered, aborting compilation"** 

When I run the following command **"./p4test --validate  ../copy_to_cpu.p4"**

**Comment by mbudiu-vmw** [comment]
You have to specify that this is a p4-14 program using --p4-14
