### ISSUE TITLE
Why does some table attribute requires a semicolon at the end, some does not?

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1115]
`key` and `actions` does not require semicolons at the end, but `psa_direct_counters` does. Even though all of them takes a list of things at the RHS. It seems inconsistent to me. Is there any particular reason why the table properties are designed this way?

```
DirectCounter<bit<12>>(CounterType_t.PACKETS) counter0;

table tbl {
     key = { headers.ip.ttl: exact; }
     actions = { Send_to_cpu; NoAction; }
     const default_action = NoAction;
     psa_direct_counters = { counter0; };
}
```

**Comment by jafingerhut** [comment]
Looks like key, actions, and entries have a special case in the P4_16 grammar that does not have a semicolon afterwards.

For all other table properties, they must have a semicolon at the end.

**Comment by hanw** [comment]
Trying to write down an example that uses `psa_direct_counters` table property annoyed me slightly because I need to put a semicolon at the end, but not for `key` or `action`. It is non-intuitive. I don't understand why `key` and `action` should be special-cased.

**Comment by hanw** [comment]
I am only speaking as a potential P4 programmer for p4-16, I am anticipating others will have a similar experience.

**Comment by mbudiu-vmw** [comment]
P4-14 legacy

**Comment by ChrisDodd** [comment]
Table attributes that require braces `{`..`}` can't have semicolons after them.  Table attributes that are just expressions require semicolons, even when the expression involved braces.

**Comment by ChrisDodd** [comment]
P4_14 was arguably cleaner, as it did not have the `=` before the `{` in the attributes that require `{` `}` and no semicolon, and there were no valid brace enclosed expressions, so the confusing case of having a `;` after a `}` never occurred.

**Comment by hanw** [comment]
Thanks, I understand from the frontend parser implementation perspective, these two are different. Just a comment on the end result. 
```
actions = { Send_to_cpu; NoAction; }
psa_direct_counters = { counter0; };
```
`action` and `psa_direct_counters` are very similar syntactically, yet, one of them requires a semicolon.

**Comment by ChrisDodd** [comment]
Both require semicolons, its just that `actions` requires it inside the braces and `psa_direct_counters` requires it outside (and the above code will give a syntax error due to the ';' inside the braces for the latter.)

**Comment by hanw** [comment]
Ah yes, my bad. psa_direct_counter should be 
```
psa_direct_counters = { counter0, counter1 };
```
Thanks, that's better.

**Comment by jnfoster** [comment]
This issue tripped me up yesterday. I had mistakenly written `keys` and then was confused when the parser complained about a missing semi-colon.

**Comment by hanw** [comment]
agreed, `keys` would be more consistent, I have run into the same issue before.

**Comment by hanw** [comment]
Ideally, I would hope all the table properties use the same convention, regardless of any legacy from p4-14. P4-16 is not backward compatible anyway.

**Comment by mbudiu-vmw** [comment]
It is too late to argue about that now. We can't break compatibility.
You have no idea how attached people grow to their languages, even if they only have a handful of users.
"keys" is not appropriate, that expression specifies how the key that is used to index in the table is computed. You index with a single key, which can be a tuple. The table contains a set of key-value pairs. But you lookup using a single key.

**Comment by jnfoster** [comment]
Perhaps we can provide a helpful error message ("did you mean 'key'"?)

**Comment by jnfoster** [comment]
@mbudiu-vmw's explanation makes sense. But just to record it here: part of what I find confusing is that P4_14 used `reads`, which is plural. So my brain often wants to write `keys` instead of `key`... But probably I an unusual -- I often flip back and forth between P4_14 and P4_16.

**Comment by ChrisDodd** [comment]
I just ran into another case that's odd -- extern object instantiations require a `;` after the `{`..`}` initializer.  This is the only place that allows a `;` after a `}`, so it is particularly confusing.

**Comment by mbudiu-vmw** [comment]
That's only when we are using the experimental syntax for defining the abstract methods.
This is similar to Java really, where you can implement an abstract class inline.

**Comment by jafingerhut** [comment]
At least for one of the original code samples motivating this issue `psa_direct_counters = { counter0; };`, PSA was simplified before v1.0 was published so that it is limited to a single direct counter per table, so now the example would be `psa_direct_counter = counter0;` instead, with no funky 'extra' semicolon.

Are there any remaining parts of this discussion that anyone is motivated to change in the language?  If not, perhaps time to close this issue?
