### ISSUE TITLE
type can be used uninitialized

### ISSUE THREAD

**Issue by teverman** [p4lang/p4c#1120]
https://github.com/p4lang/p4c/blob/cdb086252d422b16d3e5db7cc88dcaa44140237a/frontends/common/constantFolding.cpp#L72

Local variable type is uninitialized if the cc->type evaluates to neither Type_Bits or TypeInfInt in the preceding if-else, causing compiler error when options are set accordingly.

**Comment by mbudiu-vmw** [comment]
The type should never evaluate to something else.
I will add a BUG_CHECK.

**Comment by mbudiu-vmw** [comment]
I will assume that we can close this one.
