### ISSUE TITLE
Refers to Backend with no prior include of backend.h

### ISSUE THREAD

**Issue by teverman** [p4lang/p4c#1121]
https://github.com/p4lang/p4c/blob/cdb086252d422b16d3e5db7cc88dcaa44140237a/backends/bmv2/globals.h#L25

Problem hidden by unified builds?

**Comment by mbudiu-vmw** [comment]
I think it would take about as much effort to file a PR instead of filing an issue...
I will take care of this.

**Comment by mbudiu-vmw** [comment]
This seems good to be closed.
