### ISSUE TITLE
Internal bmv2 backend 'Duplicate label' error for legal P4_16 program

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1127]
[p4c-issue1127.p4.txt](https://github.com/p4lang/p4c/files/1608273/p4c-issue1127.p4.txt)

At least, I cannot see anything illegal about the P4_16 program I am attempting to compile that causes this error.  See the program in the attached file p4c-issue1127.p4.txt.  When I attempt to compile it with the following command line, using the latest version of p4c-bm2-ss as of 2018-Jan-05, it gives the following error:
```
% p4c-bm2-ss p4c-issue1127.p4.txt
terminate called after throwing an instance of 'std::logic_error'
  what():  Duplicate label in json object true_next
Aborted (core dumped)
```
There are 3 comments in the program showing small changes one can make to the program, either commenting out or uncommenting a few lines, that give a variant of the program for which no error message occurs from the compiler (I haven't verified whether the bmv2 JSON file is correct for those variations -- simply that the compiler gives no error message)

**Comment by mbudiu-vmw** [comment]
Seems to be a bug in the control-flow graph computation.

**Comment by jafingerhut** [comment]
With the latest p4c change, the compiler error is gone.  From a brief look, it appears that the generated BMv2 JSON file is correct, too.  Thanks for the fix.
