### ISSUE TITLE
Table V1Table t invoked from two different controls: Apply and Apply

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1135]
Following code causes an error in the P4-14 to 16 translation.
```
error: Table V1Table t invoked from two different controls: Apply and Apply
```

```
header_type h {
    fields {
        b : 1;
    }
}

metadata h m;

parser start {
    return ingress;
}

action x() {}

table t {
    actions { x; }
}

control c {
    apply(t);
}

control e {
    apply(t);
}

control ingress {
    c();
}
```

Question is: what is the right thing for the compiler to do? Should the compiler accept this program and eliminate the control block `e` that is not invoked anywhere? or should the compiler return an error to the programmer and ask programmer to delete `e` from source?

**Comment by hanw** [comment]
@mbudiu-vmw ?

**Comment by mbudiu-vmw** [comment]
I personally think that we should not invest too much in p4-14. The error looks good enough to me, although the Apply seems wrong.

We should not do more than the original Python compiler.
