### ISSUE TITLE
Global direct_meter regression

### ISSUE THREAD

**Issue by DGeorgeNetro** [p4lang/p4c#1137]
A recent commit https://github.com/p4lang/p4c/commit/da8ca81bd3b6d96195edb0cf9b8a7cf023fca3c8 caused globally declared direct meters to fail with the following message:

In file: /home/dgeorge/work/p4c/backends/bmv2/simpleSwitch.cpp:585
Compiler Bug: /home/dgeorge/work/p4c/backends/bmv2/simpleSwitch.cpp:585: Null info

I believe getMeterMap is not populated as convertExternInstances is being called from ConvertGlobals::preorder before the convertTable() call gets a chance to populate it.

This can be reproduced by applying this change to the existing direct_meter test:
 ```
--- a/testdata/p4_16_samples/named_meter_bmv2.p4
+++ b/testdata/p4_16_samples/named_meter_bmv2.p4
@@ -61,8 +61,9 @@ control egress(inout headers hdr, inout metadata meta, inout standard_metadata_t
     }
 }
 
+@name("namedmeter") direct_meter<bit<32>>(MeterType.packets) my_meter;
+
 control ingress(inout headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
-    @name("namedmeter") direct_meter<bit<32>>(MeterType.packets) my_meter;
     @name("_drop") action _drop() {
         mark_to_drop();
     }
```

**Comment by mbudiu-vmw** [comment]
I think we can close this issue.
