### ISSUE TITLE
Only registers with bit or int types are currently supported

### ISSUE THREAD

**Issue by thinkoco** [p4lang/p4c#1140]
When using a structure to define register  type, it gets error.
```
error: register: Only registers with bit or int types are currently supported
```
 the following is my code:
```
struct PortInfoCtrlReg_t {
  bit<3>   a;
  bit<3>   b;
  bit<3>   c;
}
register<PortInfoCtrlReg_t>(16) PortInfoCtrl_reg;
```
Sometimes, structure may be more convenient  than bit<> or int<>.
Is there any way that I can use a structure to define a register type ?

**Comment by mbudiu-vmw** [comment]
As far as I know this is not supported by the bmv2 simulator. The compiler support would probably be very easy. So you would have to file this issue with the bmv2 repository.
