### ISSUE TITLE
Update generated code for P4_14 push operation when behavioral-model 1.11 is released

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1143]
I believe the plan is that when behavioral-model 1.11 is released, the 'push' primitive in the BMv2 JSON file will change its behavior so that instead of push'ing new valid headers at the front of the header stack, it will push new invalid headers at the front of the stack.  This is to implement P4_16 push_front behavior.

I believe that also the plan is for P4_14 'push' to continue to push new valid headers at the front.

If both of those are true, then by the time behavioral-model 1.11 is released, one way to continue P4_14 'push' with its current behavior (which some extant programs may rely upon), is to change p4c-bm2-ss so that when it is compiling P4_14 source code, after generating a push primitive, it also generates N setValid() primitives, one for each of the newly pushed headers.  A similar thing should occur when using p4test to auto-translate P4_14 source code to P4_16 source code.

References:
+ Change in behavioral-model for 1.10, which is not the default yet, but requires a special command line option when compiling in order to get the new behavior - https://github.com/p4lang/behavioral-model/pull/515
+ Change in P4_14 language spec proposed for v1.0.5 - https://github.com/p4lang/p4-spec/pull/501

**Comment by mbudiu-vmw** [comment]
I will label this as a bug.
@jafingerhut : are you cooking a test case for this?
The fix will happen in the front-end when converting p4-14 to p4-16, so it will affect all back-ends equally.

**Comment by mbudiu-vmw** [comment]
One problem with this is that we will only be able to support push with a constant number of values.

**Comment by jafingerhut** [comment]
@mbudiu-vmw I don't have a test case handy right now, but could take some time to make one, with a few STF packets to include behavioral-model testing with it.

**Comment by jafingerhut** [comment]
It looks like the change to p4c has already been committed.  Nice.  That should be harmless to do even before behavioral-model 1.11 is released, because with behavioral-model 1.10 and earlier the extra setValid() operations in P4_14 are redundant but harmless from a functional perspective.  Later with behavioral-model 1.11 they will become necessary to preserve P4_14 program behavior of the push primitive.

I am assigning this issue to me, not to make further changes to p4c, but to remind me to create a test case that should exercise this new p4c behavior.  It will have to be a P4_14 test program, with STF tests, in order to automate catching incorrect behavior here.

**Comment by antoninbas** [comment]
@jafingerhut should this be closed?

**Comment by jafingerhut** [comment]
Yes, we can do that.  I have just created this separate issue to remind me to create a P4_14 test program and STF test cases: https://github.com/p4lang/p4c/issues/1207 and that was the only reason I had not closed this one already.
