### ISSUE TITLE
Possible bug in constant folding pass

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#1149]
I have the following non-sensical program:
```
#include <core.p4>
#include <v1model.p4>

struct H { };
struct M { }

parser ParserI(packet_in pk, out H hdr, inout M meta, inout standard_metadata_t smeta) {
    state start { transition accept; }
}

action empty() { }

control IngressI(inout H hdr, inout M meta, inout standard_metadata_t smeta) {
    apply {
        smeta.egress_spec = smeta.ingress_port + 32 - 16;
    }

};

control EgressI(inout H hdr, inout M meta, inout standard_metadata_t smeta) {
    apply { }
};

control DeparserI(packet_out pk, in H hdr) {
    apply { }
}

control VerifyChecksumI(inout H hdr, inout M meta) {
    apply { }
}

control ComputeChecksumI(inout H hdr, inout M meta) {
    apply { }
}

V1Switch(ParserI(), VerifyChecksumI(), IngressI(), EgressI(),
         ComputeChecksumI(), DeparserI()) main;
```
I noticed that the bmv2 JSON still had constants 32 and -16, even though I was expecting the compiler to do constant folding.
So I dumped the P4 program at the end of the bmv2 midend with `-top4 MidEndLast`:
```
control IngressI(inout H hdr, inout M meta, inout standard_metadata_t smeta) {
    apply {
        smeta.egress_spec = smeta.ingress_port + 9w32 + 9w496;
    }
}
```

I thought this might have been a small issue so I used gdb to walk through the constant folding pass. This is the IR AssignmentStatement:
```
(gdb) p dump(this)
[3029] AssignmentStatement
  left: [1138] Member member=egress_spec
    type: [123] Type_Unknown
    expr: [1137] PathExpression
      type: [123] Type_Unknown
      path: [1136] Path name=smeta absolute=0
  right: [1147] Sub
    type: [123] Type_Unknown
    left: [1144] Add
      type: [123] Type_Unknown
      left: [1141] Member member=ingress_port
        type: [123] Type_Unknown
        expr: [1139] PathExpression
          type: [123] Type_Unknown
          path: [1140] Path name=smeta absolute=0
      right: [1143] Constant value=32 base=10
        type: [1142] Type_InfInt declid=37
    right: [1146] Constant value=16 base=10
      type: [1145] Type_InfInt declid=38
$13 = void
```
I believe that `32 - 16` is never considered for constant folding because there are in different "subtrees". When I change my assignment to `smeta.egress_spec = 32 - 16 + smeta.ingress_port` then constant folding correctly transforms it to `smeta.egress_spec = 9w16 + smeta.ingress_port`. It looks like constant folding should be able to process my original assignment. Maybe one way of doing it is to move all the constants to the beginning of the expression?

**Comment by ChrisDodd** [comment]
We don't currently reassociate expressions to allow for additional constant folding.  Your expression is parsed as  `smeta.egress_spec = (smeta.ingress_port + 32) - 16;` per the normal precedence and associativity rules of the language.

**Comment by antoninbas** [comment]
This is fairly low-priority. I will try to take a stab at it if I find time.

**Comment by mbudiu-vmw** [comment]
We have few code quality passes at this point.

**Comment by mbudiu-vmw** [comment]
I believe that the reassociation pass has fixed this issue.
