### ISSUE TITLE
Support of arbitrary externs

### ISSUE THREAD

**Issue by holidayfun** [p4lang/p4c#1153]
Currently you have to manually make changes to the generated bmv2 JSON in order to use arbitrary externs. But this has to be done every time some changes were made to the p4 code, which is quite annoying after a while.
So i wanted to ask if p4c support for arbitrary externs is planned in the near future?

**Comment by mbudiu-vmw** [comment]
This is a complicated question. The p4c front-end does support arbitrary externs.
What you are asking is whether the p4c-bm2-ss back-end can be adapted to support externs that are not part of v1model.p4. To achieve that we have to define several things:
- a way to extend bmv2 to allow user-defined externs. I think that there is a spec for that
- a calling convention for user-defined externs. How are in/out/in-out arguments passed? What datatypes are supported?

**Comment by mbudiu-vmw** [comment]
I will close this issue, since I believe it has been addressed.
