### ISSUE TITLE
Enhance compiler to parse comments and attach to objects in the IR

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/p4c#1160]
Instead of discarding code comments, parse them and attach them to code objects in the IR. Intent is to allow Doxygen-style comments to be further parsed into e.g. brief and long desccriptions associated with e.g. entities, action params, match keys, structs, headers and their fields, as well as the top-level program. Initial motivation was to extract metadata to go into P4Info. See https://github.com/p4lang/p4-spec/issues/549 and https://github.com/p4lang/p4-spec/issues/580.

**Comment by mbudiu-vmw** [comment]
#1226 saves comments. Now we have to do something to them.
Perhaps we should open a new issue describing exactly how the comments should actually be used by the compiler.

**Comment by mbudiu-vmw** [comment]
We probably still need to make use of this information, but we should open new issues for that purpose.

**Comment by chrispsommers** [comment]
@mbudiu-vmw Thanks, I'll try to come  up witih a proposal.
