### ISSUE TITLE
P4Info doesn't contain Extern, ExternInstance

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/p4c#1164]
I can't seem to generate a P4Info file with Extern or ExternInstance messages in it. Am I missing something?

Given the P4_16 program `extern_test.p4`
```
#include <core.p4>
#include <v1model.p4>

typedef bit<48> mac_addr_t;
typedef bit<8> flavor_t;

header ethernet_t {
    mac_addr_t dstAddr;
    mac_addr_t srcAddr;
    bit<16> etherType;
}

struct headers {
    ethernet_t   ethernet;
}

struct metadata_t {
    flavor_t flavor;
}

parser ParserImpl(packet_in packet, out headers hdr, inout metadata_t meta, inout standard_metadata_t standard_metadata) {
    state start {
        transition parse_ethernet;
    }
    state parse_ethernet {
        packet.extract(hdr.ethernet);
        transition accept;
    }
}
  
// Define an extern to test P4info
extern Flavor<T> {
    Flavor(T flavor);
    void set_flavor(T flavor);
}

control egress(inout headers hdr, inout metadata_t meta, inout standard_metadata_t standard_metadata) {

    // Instantiate an extern
    @brief("Silly named extern")
    @description("Silly named extern longer description")
    @name("my_flavor")
    Flavor<flavor_t>(8w55) my_flavor;

    @name(".do_flavor")
    @brief("Action sets the global flavor")
    action do_flavor(
      @brief("Flavor to set") flavor_t the_flavor)
    {
      my_flavor.set_flavor(the_flavor);
    }
    
    @name(".flavor_tbl")
    table flavor_tbl {
        actions = {
            do_flavor;
        }
        default_action = do_flavor(8w0);
    }
    apply {
      flavor_tbl.apply();
    }
}

control ingress(inout headers hdr, inout metadata_t meta, inout standard_metadata_t standard_metadata) {
    apply {
    }
}

control DeparserImpl(packet_out packet, in headers hdr) {
    apply {
        packet.emit(hdr.ethernet);
    }
}

control verifyChecksum(inout headers hdr, inout metadata_t meta) {
    apply {
    }
}

control computeChecksum(inout headers hdr, inout metadata_t meta) {
    apply {
    }
}

V1Switch(ParserImpl(), verifyChecksum(), ingress(), egress(), computeChecksum(), DeparserImpl()) main;
```
Run the following:
```
p4c-bm2-ss --p4runtime-file extern_test.p4.p4info.txt --p4runtime-format text extern_test.p4
cat extern_test.p4.p4info.txt
```
Output:
```
tables {
  preamble {
    id: 33562925
    name: "flavor_tbl"
    alias: "flavor_tbl"
  }
  action_refs {
    id: 16819980
  }
  size: 1024
}
actions {
  preamble {
    id: 16819980
    name: "do_flavor"
    alias: "do_flavor"
    annotations: "@brief(\"Action sets the global flavor\")"
  }
  params {
    id: 1
    name: "the_flavor"
    annotations: "@brief(\"Flavor to set\")"
    bitwidth: 8
  }
}
```
I don't see any evidence of Extern or ExternInstance as declared in p4info.proto
```
// used to group all extern instances of the same type in one message
message Extern {
  // the extern_type_id is assigned during compilation. It is likely that this
  // id will in fact come from a P4 annotation to the extern declaration and
  // that each vendor will receive a prefix to avoid collisions.
  uint32 extern_type_id = 1;
  string extern_type_name = 2;
  repeated ExternInstance instances = 3;
}

message ExternInstance {
  Preamble preamble = 1;
  // specific to the extern type, declared in a separate vendor-specific proto
  // file
  google.protobuf.Any info = 2;
}
```
Thanks.

**Comment by antoninbas** [comment]
There is no magic. When a vendor introduces a new architecture with its own externs, they will have to do the following:
1. define a protobuf extension for P4Info with a message definition for each new extern that needs to be controlled at runtime
2. similarly define a protobuf extension for P4Runtime
3. support new P4Runtime messages in their P4Runtime server
4. extend the compiler to generate P4Info correctly for these externs (and make sure they can support the new architecture in their target-specific compiler backend of course)

As part of the P4Runtime specification, we need to make sure that 1 and 2 are well-documented, with an actual example (see https://github.com/p4lang/PI/issues/301).

As far as the compiler is concerned, we need to make sure that 4 can be done in a clean way.

**Comment by chrispsommers** [comment]
Thanks for explaining, sorry if I am playing catch-up. So my extern here didn't correrspond to any known architecture so the compiler couldn't do anything. For p4c-bm2-ss and the v1model, should the compiler emit Extern and ExternInstance for registers? I tried that in another example and didn't get any registers. I was also wondering why there are no registers as first-class Messages (liek we did for counters & meters) in p4info.proto since they are likely to be common. Is that a TODO?

**Comment by antoninbas** [comment]
Adding your own extern to an architecture essentially creates a new architecture.

The plan is to support all v1model / PSA externs with first-class Messages in P4Info / P4Runtime. We keep track of the missing ones here: https://github.com/p4lang/PI/issues/241

**Comment by chrispsommers** [comment]
Ahh, thanks, I was under-informed! Closing this.
