### ISSUE TITLE
Populate P4Info with content of @brief() and @description() annotations

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/p4c#1170]
See https://github.com/p4lang/PI/issues/275. Two new annotations have been defined which serve to populate new message fields in P4Info. Thus p4RuntimeSerializer.cpp should detect these special annotations and populate P4Info accordingly, similar to @name()

**Comment by mbudiu-vmw** [comment]
We should probably discuss these annotations in the language working group and add them to the P4-16 spec if we want them to be "official".

**Comment by chrispsommers** [comment]
@mbudiu-vmw OK, I'll bring up in the  next meeting. I should have also referenced https://github.com/p4lang/p4-spec/issues/549

**Comment by chrispsommers** [comment]
Can we revive this issue? It would go nicely with https://github.com/p4lang/p4c/pull/1614.

**Comment by mbudiu-vmw** [comment]
You should probably take this to the spec working group for the PI.

**Comment by mbudiu-vmw** [comment]
If there is a spec on how this should affect P4Runtime then you should probably assign @antoninbas to handle this issue, I believe he wrote most of the code for P4Runtime in the compiler.

**Comment by antoninbas** [comment]
@chrispsommers we should probably add mentions of `@brief`, `@description` and `@pkginfo` in the P4Runtime spec before we release the final 1.0 version. Do you think you could add some text to sections 6.1.1 and 6.2?
It will probably be quite straightforward for me to support these annotations in the P4Info generation code after that.

**Comment by chrispsommers** [comment]
@antoninbas I've no  problem adding to the P4Rt spec but it is this the right place to declare "reserved" annotations? I thought the language spec should declare them and then the compiler and P4-RT would follow. However in the interests of expediency I can take a stab at updating the P4-RT spec by mentioning @brief, @description nd @pkginfo.

**Comment by antoninbas** [comment]
I think the P4RT spec is the right place to talk about how these annotations are used to generate the P4Info message

**Comment by chrispsommers** [comment]
Move to P4Runtime https://github.com/p4lang/p4runtime/issues/102

**Comment by antoninbas** [comment]
I think this should stay open until after I had support in p4RuntimeSerializer
