### ISSUE TITLE
name shadowing in extern definition

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1172]
Following program triggers a warning in the frontend. However, there is no warning if we switched the declaration order of two externs.
```
shadow.p4(6): warning: max shadows max
    void write(in W max);
                    ^^^
shadow.p4(3)
extern T max<T>(T t1, T t2);
         ^^^
```

```
#include <core.p4>

extern T max<T>(T t1, T t2);

extern Register<W> {
    void write(in W max);
}

/// If move the definition of max here, compiler does not warn about shadowing.
/// extern T max<T>(T t1, T t2);

parser Parser<H>(packet_in pkt, out H hdr);
control Ingress<H>(inout H hdr);
control Deparser<H>(packet_out pkt, inout H hdr);
package Switch<H>(Parser<H> p, Ingress<H> ig, Deparser<H> dp);

header ethernet_t {
    bit<48> srcAddr;
    bit<48> dstAddr;
    bit<16> etherType;
}

parser myParser(
    packet_in pkt,
    out ethernet_t hdr) {
    state start {
          pkt.extract(hdr);
          transition accept;
    }
}

control myIngress(inout ethernet_t hdr) {
    apply {}
}

control myDeparser(
    packet_out pkt,
    inout ethernet_t hdr) {
    apply {
        pkt.emit(hdr);
    }
}

Switch(myParser(), myIngress(), myDeparser()) main;
```

**Comment by jnfoster** [comment]
I don't think this is surprising: as written, `max` is in scope when the second declaration is processed, but if we switch to the commented-out version, that's no longer true.

**Comment by mbudiu-vmw** [comment]
Indeed, in the second case there is no shadowing.
However, it is a good question whether we should report shadowing warnings for parameters of extern functions. Since an extern function cannot access anything but its parameters, maybe such a parameter is not really shadowing anything. So I will mark this as a bug/enhancement.

**Comment by hanw** [comment]
@mbudiu-vmw  This issue is closed, but the corresponding commit is on your fork, not merged to master. Can you open a PR?

**Comment by fruffy** [comment]
This has been merged, right?

**Comment by mbudiu-vmw** [comment]
It's not clear that there was a PR that solved this. If this is no longer an issue we should close it.

**Comment by fruffy** [comment]
It might be this PR? https://github.com/p4lang/p4c/pull/2014

**Comment by mbudiu-vmw** [comment]
That PR has been merged, the question is whether it indeed solved the issue.
