### ISSUE TITLE
core.p4 not found

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#1179]
This commit: https://github.com/p4lang/p4c/commit/94af1b909d4af0caadee1948c406191a037b2c89
seems to cause problems for people who do not install the compiler.

**Comment by Wasdns** [comment]
This problem occurs as I installing p4c today(180301). 

The command:
```
p4c-bm2-ss optimize.p4
```

The error log:
```
optimize.p4:2:19: error: no include path in which to search for core.p4
 #include <core.p4>
                   ^
optimize.p4:3:22: error: no include path in which to search for v1model.p4
 #include <v1model.p4>
                      ^
optimize.p4(50):syntax error, unexpected IDENTIFIER "packet_in"
parser MyParser(packet_in
                ^^^^^^^^^
error: Preprocessor returned exit code 256; aborting compilation
error: 2 errors encountered, aborting compilation
```

**Comment by antoninbas** [comment]
I have a similar issue. I get errors when I install the compiler but not when I use the locally built version:
```
antonin@ubuntu:~/Documents/p4lang/p4c/build$ p4c-bm2-ss ../testdata/p4_16_samples/action_profile-bmv2.p4 --p4-16
../testdata/p4_16_samples/action_profile-bmv2.p4:17:19: error: no include path in which to search for core.p4
../testdata/p4_16_samples/action_profile-bmv2.p4:18:22: error: no include path in which to search for v1model.p4
../testdata/p4_16_samples/action_profile-bmv2.p4(25):syntax error, unexpected IDENTIFIER "packet_in"
parser ParserI(packet_in
               ^^^^^^^^^
error: Preprocessor returned exit code 256; aborting compilation
error: 2 errors encountered, aborting compilation
antonin@ubuntu:~/Documents/p4lang/p4c/build$ ./p4c-bm2-ss ../testdata/p4_16_samples/action_profile-bmv2.p4 --p4-16
../testdata/p4_16_samples/action_profile-bmv2.p4(35): warning: Target does not support default_action for IngressI.indirect (due to action profiles)
    table indirect {
          ^^^^^^^^
../testdata/p4_16_samples/action_profile-bmv2.p4(42): warning: Target does not support default_action for IngressI.indirect_ws (due to action profiles)
    table indirect_ws {
          ^^^^^^^^^^^
```

**Comment by antoninbas** [comment]
Using the p4c driver instead of p4c-bm2-ss solves the issue.

**Comment by mbudiu-vmw** [comment]
Yes, however one should be able to also invoke the compilers directly.
Moreover, externally contributed compilers that do not make use of the driver should also work.

**Comment by antoninbas** [comment]
Agreed. This is actually a pretty annoying issue right now as the exercises in the tutorials repo invoke p4c-bm2-ss directly...

**Comment by paulsubrata55** [comment]
One workaround is putting an include path for the core.p4
p4c-bm2-ss --p4v 16 --p4runtime-file build/advanced_tunnel.p4info --p4runtime-format text -o build/advanced_tunnel.json advanced_tunnel.p4 -I /usr/local/share/p4c/p4include

But the tutorial P4D2_2017_Fall/exercises/p4runtime is failing because now the latest p4c-bm2-ss prepends the control block name along with the table name / action name in the p4info file and the p4runtime_lib is failing to build the table entry.
    
    tables {                                                                         
    preamble {                                                                     
       id: 33574068                                                                 
       name: "MyIngress.ipv4_lpm"                                                   
       alias: "ipv4_lpm"                                                            
    }

**Comment by mbudiu-vmw** [comment]
The second statement seems to be an issue with the tutorial.
If you think that it is a bug in the compiler you should probably file a separate issue with this repository.
Indeed, recently we changed the way control-plane names are generated, and we are now hopefully in sync with the specification. Previously we were not. Some applications that were using the old naming schemes may need to be updated. If you want to discuss issues with applications it is probably best to use a p4-related mailing list.

**Comment by mbudiu-vmw** [comment]
@cc10512 : it looks like the commit which changed the include paths broke several projects.

**Comment by wjf1993** [comment]
I have a similar issue. I Using the p4c driver instead of p4c-bm2-ss solves the issue.I want to know how to use p4c-bm2-ss compiled source code to make no mistake？

**Comment by edgarcosta92** [comment]
@wjf1993 do what they say in the thread: `p4c-bm2-ss -I /usr/local/share/p4c/p4include/ program.p4 -o program.json`
