### ISSUE TITLE
Recirculate does not work

### ISSUE THREAD

**Issue by paulsubrata55** [p4lang/p4c#1184]
I was trying out the recirculate mechanism and seems it does not work. Using simple switch grpc.

    control MyEgress(inout headers hdr,                                              
             inout metadata meta,                                            
             inout standard_metadata_t standard_metadata) {                                                                                  
    action ofpat_goto_table_(bit<7> table_id) {                                  
           meta.of_metadata.table_id = table_id;                                    
            recirculate(meta);                                                                                                              
     }                                                                            
    table ofpat_goto_table {                                                     
        key = {                                                                  
            meta.of_metadata.index : exact;                                      
        }                                                                        
                                                                             
        actions = {                                                              
            ofpat_goto_table_;                                                   
            NoAction;                                                            
        }                                                                        
        size = 1024;                                                             
        }                                                                            
        apply {                                                                      
            if ((meta.of_metadata.bmap & 4) == 4) {                                  
                ofpat_goto_table.apply();                                            
        }                                                                        
    }                                                                            
}

Seems like intrinsic_metadata.recirculate_flag metadata field in v1model.p4 is missing.

**Comment by mbudiu-vmw** [comment]
We just merged a fix for this. Are you using a new build?

**Comment by jafingerhut** [comment]
I see a recent commit with a fix for resubmit, but recirculate is controlled by a different metadata flag, according to this comment: https://github.com/p4lang/behavioral-model/issues/558#issuecomment-370564691

**Comment by mbudiu-vmw** [comment]
@paulsubrata55: Maybe you can run a quick experiment and just add that declaration to v1model.p4.
It that's enough to make it work you can then just submit a PR...

**Comment by paulsubrata55** [comment]
@mbudiu-vmw: I added recirculate flag in v1model.p4 and its started working as expected:
Changes done in v1model.p4
        @alias("intrinsic_metadata.recirculate_flag") bit<32> recirculate_flag; 

logs:
[05:11:09.711] [bmv2] [D] [thread 3940] [0.0] [cxt 0] Pipeline 'egress': end
[05:11:09.711] [bmv2] [D] [thread 3940] [0.0] [cxt 0] Deparser 'deparser': start
[05:11:09.711] [bmv2] [D] [thread 3940] [0.0] [cxt 0] Updating checksum 'cksum'
[05:11:09.711] [bmv2] [D] [thread 3940] [0.0] [cxt 0] Deparsing header 'ethernet'
[05:11:09.711] [bmv2] [D] [thread 3940] [0.0] [cxt 0] Deparsing header 'ipv4'
[05:11:09.712] [bmv2] [D] [thread 3940] [0.0] [cxt 0] Deparser 'deparser': end
[05:11:09.712] [bmv2] [D] [thread 3940] [0.0] [cxt 0] **Recirculating packet**
[05:11:09.712] [bmv2] [D] [thread 3939] [0.1] [cxt 0] Processing packet received on port 1
[05:11:09.712] [bmv2] [D] [thread 3939] [0.1] [cxt 0] Parser 'parser': start
[05:11:09.712] [bmv2] [D] [thread 3939] [0.1] [cxt 0] Extracting header 'ethernet'
[05:11:09.712] [bmv2] [D] [thread 3939] [0.1] [cxt 0] Parser state 'start': key is 0800
[05:11:09.712] [bmv2] [T] [thread 3939] [0.1] [cxt 0] Bytes parsed: 14
[05:11:09.712] [bmv2] [D] [thread 3939] [0.1] [cxt 0] Extracting header 'ipv4'
[05:11:09.712] [bmv2] [D] [thread 3939] [0.1] [cxt 0] Parser state 'parse_ipv4' has no switch, going to default next state
[05:11:09.712] [bmv2] [T] [thread 3939] [0.1] [cxt 0] Bytes parsed: 34
[05:11:09.712] [bmv2] [D] [thread 3939] [0.1] [cxt 0] Verifying checksum 'cksum': true
[05:11:09.712] [bmv2] [D] [thread 3939] [0.1] [cxt 0] Parser 'parser': end
[05:11:09.712] [bmv2] [D] [thread 3939] [0.1] [cxt 0] Pipeline 'ingress': start
[05:11:09.712] [bmv2] [T] [thread 3939] [0.1] [cxt 0] Applying table 'MyIngress.openflow_table'
[05:11:09.712] [bmv2] [D] [thread 3939] [0.1] [cxt 0] Looking up key:

Thanks

**Comment by edgarcosta92** [comment]
The recirculate_flag was not added to the `p4include/v1model.p4` yet. 

**A bit off topic:**
I have seen that in one of the latest commits you also added `egress_global_timestamp`. Is there a reason why `v1model.p4` is not complete? I mean, why aren't all the metadata fields supported by the behavioural model enabled?

For example another one missing is: `intrinsic_metadata.priority` for the strict priority queueing. 

Is there a file where I can find all the possible metadata fields that can be included to the `v1model.p4` ?

**Comment by mbudiu-vmw** [comment]
The recirculate flag will make it there as soon as the PR is merged; right now the Travis checks have failed, so I have submitted a new version.

What does "complete" mean?

v1model.p4 was created to emulate the features defined in P4-14, and not the behavioral model simple_switch.
In the meantime it has acquired a new life, where it evolves to track simple_switch. But that is a moving target.
The right solution would be to have some kind of versioning for both simple_switch and v1model, where versions match.
In principle you cannot change v1model.p4, it is published in concert with the architecture that it is modelling. You just use it as it is. It is as if you wanted to modify stdlib.h from the C library.

**Comment by alanamarzoev** [comment]
Sorry to comment on a closed issue, but I am experiencing the same problem (in the switch logs, it says that there is no source info for the recirculate primitive), even after adding the recirculate flag to p4include/v1model.p4. Does anyone have any ideas as to why this is happening?

Thanks.

**Comment by mbudiu-vmw** [comment]
I will mark this as closed. Please reopen if this is not true.
