### ISSUE TITLE
Cmake  cannot find googletest folder

### ISSUE THREAD

**Issue by KV6895** [p4lang/p4c#1189]
Cannot find source file :  

/home/MyTest/tutorials/p4c/test/frameworks/gtest/googletest/src/gtest-all.cc

**Comment by mbudiu-vmw** [comment]
This file comes form a git module, perhaps it will be installed if you do this:
`git submodule update --init --recursive`
(this is described in README.md)

**Comment by KV6895** [comment]
Thanks,  it works.
