### ISSUE TITLE
which branch can I checkout for compiling psa architecture code ?

### ISSUE THREAD

**Issue by thinkoco** [p4lang/p4c#1190]
Hi,all. I get stuck on compiling the psa code.I use the command:  

`p4c-bm2-ss  --p4v 16 --arch psa -o test.json psa-ether-wire.p4 `

It gives out:
```
In file: /opt/p4/p4c_psa/backends/bmv2/backend.cpp:98
Unimplemented compiler support: PSA architecture is not yet implemented
```
Any help would be  appreciated.

**Comment by antoninbas** [comment]
As indicated in the error message, PSA is not supported by the bmv2 compiler backend. This is a work-in-progress at the moment (very early stage) and there isn't even a branch with partial experimental support. I don't have a precise ETA for this but hopefully before the end of the year.

There may be a compiler backend somewhere that supports PSA, but not for bmv2 and not in the p4lang Github organization AFAIK.

Obviously if you just want to validate your P4 code (and not run it on any particular target), you can use the `p4test` backend which is architecture-independent.
