### ISSUE TITLE
Implement type checking for value of `size` table property

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1230]
https://github.com/p4lang/p4-spec/pull/603 is planned to be merged into the P4_16 language spec soon.

Creating this issue to remind us to implement type checking of the value assigned to the `size` table property (if present -- it is optional) to give an error if the value is not an integer.  I am not sure if size=0 should be an error or allowed for some reason.

size >= 1 should definitely be allowed.  size < 0 should definitely be an error.  There was a preference expressed that expressions should be allowed on the right-hand size of `=` here, e.g. ((5 + 7) / 2) should be compile-time evaluated to 6.  Other compile-time constant expressions should be allowed as well, e.g. symbols declared `const bit<16> FOO`.

**Comment by mbudiu-vmw** [comment]
I will close this issue.
