### ISSUE TITLE
/: could not evaluate at compilation time

### ISSUE THREAD

**Issue by Wannabeperfect** [p4lang/p4c#1232]
I need to calculate a number in my P4 program,the code is showing below:

`           temp = meta.ingress_metadata.packet_ipg;
            q = temp / 12; 
            pkt_num = q / 100000; 

`But when I compile it,`it occurs errors
![11](https://user-images.githubusercontent.com/38399275/38918815-4af0e240-42de-11e8-90f0-964be378c678.png)

How can I solve this problem?
Thank you:)

**Comment by jafingerhut** [comment]
P4 implementations need not support division, except for compile-time constant arguments (all arguments, not just one of them).

Shifting, adding, and subtracting are all supported, so multiplying or dividing by powers of 2 is straightforward via shifting.  You can multiply by 6 by doing (x << 2) + (x << 1), for example.

Division by a constant can be approximated to varying degrees by multiplying by a suitable constant K, then dividing by a power of 2 D, where you pick the constant and power of 2 such that multiplying by K/D is a close approximation to dividing by the constant you want.

**Comment by Wannabeperfect** [comment]
@jafingerhut  Thank U so much :)

When I compile my problem,I got a new issue
My code is like this,I want to write the queue length of different ports to the registers. 
   action get_queue_length() {
      qlength_1_reg.write(meta.queueing_metadata.deq_qdepth_5,0);  //port 5
      qlength_2_reg.write(meta.queueing_metadata.deq_qdepth_6,0); //port 6
      qlength_3_reg.write(meta.queueing_metadata.deq_qdepth_7,0); //port 7
      qlength_4_reg.write(meta.queueing_metadata.deq_qdepth_8,0);  //port 8
   }
      
   table get_port_queue_length {
       actions = { 
           get_queue_length;
           nop;
      }
   }
![22](https://user-images.githubusercontent.com/38399275/38924982-e0eb0a28-42ed-11e8-81ac-60227e01f051.png)
Could you tell me how to solve it?Thanks :)

**Comment by jafingerhut** [comment]
Neither of these issues are bugs in the p4c compiler.  For help or advice on writing P4 programs, I would recommend you use the p4-dev email list, which you can join here: http://lists.p4.org/mailman/listinfo/p4-dev_lists.p4.org or the P4 community on Slack: https://p4-lang.slack.com

**Comment by jnfoster** [comment]
+1

**Comment by ersuneetsingh** [comment]
@jafingerhut 
Hi, I found this discussion relevant to my current ongoing work. I am trying to calculate the weighted moving average using saved value in register and extracted value from the incoming packets.  Getting approximate moving average is not an issue for my current target P4 app. Therefore, as you suggested in previous post multiplying or dividing by powers of 2 via shifting, I am following the same, the steps are given below :  

Lets say 'A' is saved value in register and 'B' is current value extracted from the incoming packet,  
MA = (127 * A + 1* B )/128    // this is what i want to achieve

What I am trying in P4 is as follows:
MA = ((A << 7) - (A) + (B)) >> 7  ;   

However, I am not getting correct values of MA using shifting. May be, I am doing something wrong, could you please help me to suggest how I can achieve this type of calculation in P4 ?

 Thank you.

**Comment by jafingerhut** [comment]
@ersuneetsingh Do you have an example of values of A,B, and MA that look like they are incorrect to you with such an assignment in your program, and a complete P4 program that the assignment is part of?

One possibility to check: if the value of A is so large that (A << 7) overflows, then you will lose some of the most significant bits of the answer.  Casting A to a value that is 7 bits wider before doing the calculation should help avoid losing any of those most significant bits.

**Comment by ersuneetsingh** [comment]
Thank you so much Andy for your quick reply and suggestion. 
You are correct. In my case, due to the large 'A', I was loosing some most significant bits in (A << 7) case. That is why moving average was wrong. However, my application is memory sensitive so I do not want to add some extra bits, so now my final expression to calculate moving average is given below:

MA = (A - ( A >> 7))                           // Step 1 
MA = ((MA) + (B >> 7))                     //  Step 2

I checked with above expression, It seems to be working now. 
Thank you so much.

**Comment by jafingerhut** [comment]
You can also add more bits to the temporary values in the calculation, and then cast the final result back down to the smaller size after the calculation is done, which would not increase the storage size required in the P4 register array elements.

For example, you could use something like this:
```
bit<16> A_read_from_register;
bit<16> MA_to_write_back_to_register;
bit<23> A_temp;
bit<23> MA_temp;
bit<23> B_temp;

A_temp = (bit<23>) A_read_from_register;
MA_temp = ((A_temp << 7) - (A_temp) + (B_temp)) >> 7;
MA_to_write_back_to_register = (bit<16>) MA_temp;
```

**Comment by ersuneetsingh** [comment]
Yes, I was also looking for the same. This will also helped me in other part of my app.
Thank you so much, It will helped me lot.
