### ISSUE TITLE
Internal Compiler error

### ISSUE THREAD

**Issue by jw1park** [p4lang/p4c#1262]
How do I fix this??

[ 23%] Building CXX object frontends/CMakeFiles/frontend.dir/unified_frontend_sources_3.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
frontends/CMakeFiles/frontend.dir/build.make:265: recipe for target 'frontends/CMakeFiles/frontend.dir/unified_frontend_sources_3.cpp.o' failed
make[2]: *** [frontends/CMakeFiles/frontend.dir/unified_frontend_sources_3.cpp.o] Error 4
CMakeFiles/Makefile2:957: recipe for target 'frontends/CMakeFiles/frontend.dir/all' failed
make[1]: *** [frontends/CMakeFiles/frontend.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

I do run this process serveral times. But It didn't work.
What is the problem??

**Comment by jnfoster** [comment]
@jw1park 

> What is the problem??

That is hard to say without more information about your system. For example, perhaps you could say what C++ compiler you are using, and what steps you ran before typing `make`?

**Comment by ChrisDodd** [comment]
I've seen that error if you try to build the compiler in a VM with too little memory -- g++ fails if it runs out.  You may be able to make it work with  `cmake .. -DENABLE_UNIFIED_COMPILATION=OFF` (disable the unified build that tries build many files together to compile faster) and/or `make -j1` (disable parallel builds), but the simplest may be to just use more memory (4GB  is pretty much the absolute minimum -- more is better).

**Comment by mbudiu-vmw** [comment]
I will close this issue, since it is not really about p4c.
