### ISSUE TITLE
only 73% of tests passing

### ISSUE THREAD

**Issue by aneeshakella17** [p4lang/p4c#1263]
Hello, 
When I run the commands:

cmake .. -DCMAKE_BUILD_TYPE=RELEASE-DCMAKE_INSTALL_PREFIX=
make -j4 
make -j4 check 

only 73% of the tests are passing 

<img width="376" alt="screen shot 2018-04-30 at 5 13 06 pm" src="https://user-images.githubusercontent.com/25336480/39456221-d59e741a-4c99-11e8-8998-d8c14826c9a5.png">
[Temporary.zip](https://github.com/p4lang/p4c/files/1962559/Temporary.zip)
I have attached an image of the results and a zip file of the logs.

**Comment by arijeetsat** [comment]
I think it should work with only `cmake ..` , have you tried that?

**Comment by mbudiu-vmw** [comment]
I will close this issue.
