### ISSUE TITLE
Parser Bug

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#1267]
This bug was discovered by @Checkmate50.

The `parser3.p4` test contains the following declarations:
```
header_type data1_t {
    fields {
        f1 : 32;
        x1 : 2;
        x2 : 4;
        x3 : 4;
        x4 : 4;
        x5 : 2;
        x6 : 5;
        x7 : 2;
        x8 : 1;
    }
}
header data1_t data1;
```
And the parser starts like this:
```
parser start {
    extract(data1);
    return select(data1.x3, data1.x1, data1.x7) {
        0xe4: parse_data2;
        default: ingress;
    }
}
```
However, if we compile using the Bmv2 backend, we get the following JSON:
```
        {
          "name" : "start",
          "id" : 1,
          "parser_ops" : [
            {
              "parameters" : [
                {
                  "type" : "regular",
                  "value" : "data1"
                }
              ],
              "op" : "extract"
            }
          ],
          "transitions" : [
            {
              "type" : "hexstr",
              "value" : "0x0e0100",
              "mask" : null,
              "next_state" : "parse_data2"
            },
            {
              "value" : "default",
              "mask" : null,
              "next_state" : null
            }
          ],
          "transition_key" : [
            {
              "type" : "field",
              "value" : ["data1", "x3"]
            },
            {
              "type" : "field",
              "value" : ["data1", "x1"]
            },
            {
              "type" : "field",
              "value" : ["data1", "x7"]
            }
          ]
        }
```
Note that the constant mentioned in the `select` case `0xe4` has been translated to `0xe0100`, which is wrong! In particular, it looks like the compiler front-end is concatenating the hex representation of 14 (namely `0xe`) with the binary representation of 4 (namely `0b0100`), yielding the hex representation of 917760 (namely `0xe0110`) instead of 228 (namely `0xe4`). 

Even worse, the output is no longer type correct since the byte value has been expanded to a 20-bit value.

**Comment by antoninbas** [comment]
This actually looks correct to me. Did you check if packet forwarding was working?
According to the bmv2 JSON documentation for parser transition:

> For values and masks, make sure that you use the correct format. They need to be the concatenation (in the right order) of all byte padded fields (padded with 0 bits). For example, if the transition key consists of a 12-bit field and a 2-bit field, each value will need to have 3 bytes (2 for the first field, 1 for the second one). If the transition value is 0xaba, 0x3, the value attribute will be set to 0x0aba03.

This is also consistent with what the legacy P4_14 bmv2 compiler is generating.

**Comment by jnfoster** [comment]
I'm confused: the transition key is 1 byte (`data.x3`, `data.x1`, and `data.x7`) and the value is 1 byte (`0xe4`). There is no mask.

When parsing `0xe0100`, does Bmv2 somehow figure out that it should parse the first 4-bit chunk as hex and the second 4-bit chunk as binary?

**Comment by antoninbas** [comment]
When building the transition key, bmv2 will concatenate all the fields which are part of the key (data.x3, data.x1, and data.x7). These fields are byte-aligned. Rather than do expensive bit manipulations at runtime, bmv2 asks the compiler to add padding to the transition value, so that the byte-aligned fields can simply be concatenated for the lookup.

```
(data.x3, data.x1, and data.x7) == (0xe4) <=> data.x7 == 2w0 && data.x1 == 2w1 && data.x3 == 4we
```

Now all 3 fields are less than a byte, so bmv2 is going to expect a 1-byte value for each one:
- for data.x7 : `0x00`
- for data.x1 : `0x01`
- for data.x3 : `0x0e`
Then you concatenate all of them to obtain a 24-bit value (3 bytes): `0x0e0100`

There is no binary anywhere, it is 3 hexa byte values concatenated.

**Comment by jnfoster** [comment]
Got it. My mistake!
