### ISSUE TITLE
Use a struct type as T in value_set<T>

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1270]
Is the following P4 code correct syntax when the type T in PVS is a struct?

```
struct my_packet {
  bit<32> data;
}

struct value_set_t {
  bit<32> field;
}

parser MyParser(packet_in b, out my_packet p, inout my_metadata m, inout standard_metadata_t s) {

    value_set<value_set_t>(4) pvs;

    state start {
        b.extract(p.data);
        transition select({ p.data }) {
            pvs: accept;
            {0x810} : foo;
        }
    }

    state foo {
        transition accept;
    }
}
```

When I compile with p4test at commit d50facb5, type unification failed at the constant key expression {0x810}.

```
error: SelectExpression: Cannot unify tuple type Tuple(1) with non tuple-type int
        transition select({ p.data.da }) {
```

Complete test program below:
[pvs.p4.gz](https://github.com/p4lang/p4c/files/1975923/pvs.p4.gz)

**Comment by jafingerhut** [comment]
Do you get a similar error message if the struct contains 2 fields, and the transition select expression is a list of 2 expressions with type `bit<W>`?

Or does the error only occur for a struct with 1 field, and a list of 1 value?

**Comment by mbudiu-vmw** [comment]
We should support the second variant: the most natural one for the user, even if the compiler has to do a bit more work. I will tag these as enhancements, because they are in line with the current spec; we should update the spec to allow struct types for value sets.

**Comment by hanw** [comment]
Updated text and example in spec to allow struct type for the value set as part of https://github.com/p4lang/p4-spec/pull/602 https://github.com/p4lang/p4-spec/pull/602/commits/278afae9a3db7f495c474768ed9bf6575679e6e9
