### ISSUE TITLE
JSON to P4

### ISSUE THREAD

**Issue by aneeshakella17** [p4lang/p4c#1273]
Does the code handle JSON to P4 conversion? If not, how feasible do you think it would be to implement?

**Comment by mbudiu-vmw** [comment]
What is P4i?

**Comment by aneeshakella17** [comment]
Hi, 
Yes, I would really be interested in seeing the converter. P4i is an intermediate representation. When you convert P4 to JSON, a P4i file should be generated as well.

**Comment by aneeshakella17** [comment]
Just an update @debatgithub as to when and if you can share the converter

**Comment by TakeshiTseng** [comment]
Hi,
You mean `p4i` generated by `p4c`? (e.g. `p4c -b bmv2-v1model my-p4-code.p4`)

This `p4i` is not the `IR` between Frontend and Backend compiler. It's like the output from preprocessor such as `cc` or `gcc`

**Comment by TakeshiTseng** [comment]
By the way you can find how `p4c` generate `p4i` here:
https://github.com/p4lang/p4c/blob/master/tools/driver/p4c_src/p4c.bmv2.cfg#L40-L42

It actually execute this command:
`cc -E -x c -I /usr/local/share/p4c/p4include -o ./my-p4-code.p4i my-p4-code.p4`

**Comment by hanw** [comment]
The `-###` flag on `p4c` will print the commands executed by p4c.

**Comment by aneeshakella17** [comment]
Thank you, but I actually need something to convert JSON to some P4 format (p4-16, p4-14) or p4i.

**Comment by hanw** [comment]
In the case of bmv2, it runs the c preprocessor and the p4c-bm-ss backend.

**Comment by hanw** [comment]
If I understand correctly, p4i is just the preprocessed p4 source code, we could have named it my-p4-code.preprocessed.p4

**Comment by aneeshakella17** [comment]
I'm performing a project where JSON manipulation was a key element. I was hoping to  convert the manipulated JSON back into a p4 program.

**Comment by aneeshakella17** [comment]
I don't think --dumpJSON is a given option

**Comment by mbudiu-vmw** [comment]
It is `--toJSON`.
We should file an issue, because the documentation says:
`--toJSON file                           Dump IR to JSON in the specified file.`
But it does not say when the IR is generated.

**Comment by mbudiu-vmw** [comment]
By looking at the code the JSON seems to be generated just before the back-end is entered.

**Comment by hesingh** [comment]
There are not enough details on the project for what does it do to generate JSON.  For example, is the project designing switching asic hardware elements or does the project use switching code, or what have you.    See the MIT Domino compiler that generates P4 output.   

http://web.mit.edu/domino/#instructions

After p4c documentation is fixed, I don't see how p4c can help with this issue.  Similar to MIT domino, I would develop a backend for your project.

**Comment by TakeshiTseng** [comment]
As @hesingh said, there are not enough detail here.
JSON is just a format. Which spec you mentioned here?
bmv2 JSON? or JSON dump from Frontend+Midend compiler? Or something else?

**Comment by prakashdwy123** [comment]
hey @aneeshakella17  you got how to convert JSON to P4 ? is there any way ?

**Comment by aneeshakella17** [comment]
No, for right now, there is no trivial way I think.

**Comment by ChrisDodd** [comment]
Reading JSON from a file is pretty easy -- see the referenced change.  The tricky part is figuring out what to do with it afterwards.  What state of compilation is it in?  What passes still need to run?  skipping passas or running passes mulitple times may lead to unexpected errors.

There's also an issue that the SourceInfo is not properly loaded, so source line number positioning information will be lost.

**Comment by mbudiu-vmw** [comment]
Yes, a problem is that today we dump json after the mid-end, but the loading you implemented is before the front-end. Perhaps the --toJson and --fromJson should have an additional argument, something like "frontend", "midend", "backend", indicating where the dumping and loading should be done (before which stage). 

An alternative would be to save such information in the json file itself, and then the --fromJson does not need to have any arguments.

**Comment by drobinkent** [comment]
Is the JSON file an intermediate representation or a binary for the BMV2 backend?

**Comment by mbudiu-vmw** [comment]
Commenting on closed issues is not the best way to get answers, you can either reopen the issue or file a new one.
JSON is really a simple text-based language for representing simple tree data structures.
It is used a lot to represent *serialized* tree-like (or, with various conventions,) more complex data structures.
The compiler can serialize two different data structures as JSON: the intermediate representation it uses for the program, and the data structure that BMv2 uses to represent P4 programs. The latter was mostly defined before P4-16 existed, and has evolved. These are completely different data structures.
