### ISSUE TITLE
Compiler cannot read the IR dumped using --toJSON

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#1280]
There should be a flag to indicate to the compiler to read the program from a JSON file dumped previously instead of reading a P4 file. An important question is which passes should be run on this file; currently the compiler dumps JSON after the mid-end.

**Comment by lbanduka** [comment]
Hi,
I think that this is fixed in following commit
https://github.com/p4lang/p4c/commit/46609cd1c393ecf1741edd3f5209e16a70bafb8c

**Comment by mbudiu-vmw** [comment]
That fix only allows you to read the json before the mid-end.
But I will close this issue, because it looks like that's enough for now.
