### ISSUE TITLE
Varbit declaration in structs leading to compilation error

### ISSUE THREAD

**Issue by Mastertrap21** [p4lang/p4c#1291]
We are working on a compiler fuzzer for P4 and during our experiments we have found out that declaring varbit types inside structs and compiling for the BMv2 target leads to compilation error. In the language specification (https://p4.org/p4-spec/docs/P4-16-v1.0.0-spec.html) it is written under chapter 7.2.7 (Type nesting rules) that varbits are allowed in a struct container type.

Source file used:
[issue.p4.txt](https://github.com/p4lang/p4c/files/2025575/issue.p4.txt)

Compilation process:
`p4c-bm2-ss issue.p4 -o issue.json`

Error:
```
In file: /home/vagrant/p4c/backends/bmv2/header.cpp:107
Compiler Bug: issue.p4(8): varbit<8>: Unhandled type for @name("userMetadata.test") varbit<8> test
   varbit<8> test;
          ^
issue.p4(8)
   varbit<8> test;
             ^^^^
```

**Comment by mbudiu-vmw** [comment]
The spec allows specific back-ends to reject legal programs if they use features not supported by the target.
In this case the BMv2 back-end does not (yet) support structs containing varbits. 
Running `p4test --validate` will only execute the compiler front-end; something that passes successfully this validation should be legal across all targets.

**Comment by mbudiu-vmw** [comment]
On the other hand, the compiler should not crash for such an input, so I will tag this as a bug. We can fix the bug by either giving an error message, or by implementing support for varbits in bmv2.
