### ISSUE TITLE
Cannot infer type for type parameter H1

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1304]
The following example tries to exercise the optional argument feature in the `package` construct and it triggers an error in the frontend.

Command:
```
~/p4c/build/p4test --std p4-16 min.p4
```

Error message:
```
min.p4(64): error: main: cannot infer type for type parameter H1
Switch(p0) main;
           ^^^^
min.p4(5)
package Switch<H0, M0, H1, M1>(Pipeline<H0,M0> p0, @optional Pipeline<H1,M1> p1);
```

Source code:
[min.p4.txt](https://github.com/p4lang/p4c/files/2051232/min.p4.txt)

**Comment by mbudiu-vmw** [comment]
That makes sense. We'll have to figure out when it's fine to actually not infer a type for some type variables...

**Comment by mbudiu-vmw** [comment]
I think I have a solution: the compiler will bind such type variables to the Type_Dontcare type, and the task of offering a meaningful error will fall onto the back-end if that is unacceptable. Let me see if it works in practice.
