### ISSUE TITLE
Assignment from from tuple to header fails

### ISSUE THREAD

**Issue by ygottlieb-perspectalabs-com** [p4lang/p4c#1310]
In a simple test (attached), I try to assign a header from a tuple, but I get the following error:

/home/ygottlieb/examples/assign.p4(34): error: AssignmentStatement: Number of fields 1 in initializer different than number of fields in structure 2: Tuple(1) to header test
    headers.test = { 1 };
                 ^
/home/ygottlieb/examples/assign.p4(34)
    headers.test = { 1 };
                   ^^^^^
/home/ygottlieb/examples/assign.p4(4)
header test {
       ^^^^
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  In file: /home/ygottlieb/p4/p4c/control-plane/p4RuntimeSerializer.cpp:2044
Compiler Bug: Failed to transform the program into a P4Runtime-compatible form

Based on git bisect, the problem first appears in commit 9d836b33220571b1424c12e6864ff9cf275631e8, possibly due to control-plane/p4RuntimeSerializer.cpp calling P4::SynthesizeValidField.

/* -*- Mode:C; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */
#include <v1model.p4>

header test {
  bit<1> test;
}

struct headers_t {
  test test;
};

struct metadata_t {
};

parser EmptyParser(packet_in b, out headers_t headers, inout metadata_t meta,
                   inout standard_metadata_t standard_metadata)
{
  state start {
    /* No explicit reject */
    /* transition reject; */
    transition accept;
  }
}

control EmptyVerifyChecksum(inout headers_t hdr, inout metadata_t meta)
{
  apply {}
}

control EmptyIngress(inout headers_t headers, inout metadata_t meta,
                     inout standard_metadata_t standard_metadata)
{
  apply {
    headers.test = { 1 };
  }
}

control EmptyEgress(inout headers_t hdr,
                    inout metadata_t meta,
                    inout standard_metadata_t standard_metadata)
{
  apply {}
}

control EmptyComputeChecksum(inout headers_t hdr,
                             inout metadata_t meta)
{
  apply {}
}

control EmptyDeparser(packet_out b, in headers_t hdr)
{
  apply {}
}

V1Switch(EmptyParser(),
         EmptyVerifyChecksum(),
         EmptyIngress(),
         EmptyEgress(),
         EmptyComputeChecksum(),
         EmptyDeparser()) main;

**Comment by mbudiu-vmw** [comment]
I was hoping we worked around this bug. 
This is all due to the SynthesizeValidField pass. That pass changes the program IR in a way which makes it not pass type-checking. I think that pass should be removed and the API generation should handle headers in a special way rather than expecting a valid field to be present. @sethfowler : would you like to try to fix this long-standing problem? You wrote that pass.

**Comment by hanw** [comment]
Interestingly, if I remove that pass from p4RuntimeSerializer.cpp, none of the bmv2 tests fails. @antoninbas does this make sense to you?

**Comment by antoninbas** [comment]
Yes it makes sense. This test should fail though: https://github.com/p4lang/p4c/blob/master/test/gtest/p4runtime.cpp#L354
I've been talking to @mbudiu-vmw offline about fixing this. I was planning to take a look at it next week but you're welcome to fix it before then if you want :)

**Comment by antoninbas** [comment]
Basically my understanding is that because of changes to P4Runtime over time, the only transformation that is now required is:
```
<h>.isValid() : <match_type> -----> @name("<h>.$valid$") <h>.isValid() : <match_type>
```

**Comment by hanw** [comment]
I will leave it to you then, my plates are full.

**Comment by mbudiu-vmw** [comment]
Interestingly, the name generated in the front-end is already using `$valid`. So maybe we can just delete this pass. Let me try.

**Comment by antoninbas** [comment]
We need `$valid$`

**Comment by mbudiu-vmw** [comment]
Yes, it is `$valid$`. In fact all tests pass if I remove that Pass. I will submit a PR.
