### ISSUE TITLE
Error type in nested struct gives Compiler Bug error

### ISSUE THREAD

**Issue by Mastertrap21** [p4lang/p4c#1325]
We have found out that declaring error types inside nested structs and compiling for the BMv2 target leads to compilation error. In the language specification (https://p4.org/p4-spec/docs/P4-16-v1.0.0-spec.html) it is written under chapter 7.2.7 (Type nesting rules) that both structs and errors are allowed in struct container types. It works fine with p4test so this might be a BMv2 back-end issue

Source file used:
[issue.p4.txt](https://github.com/p4lang/p4c/files/2077203/issue.p4.txt)

Compilation process:
`p4c-bm2-ss issue.p4 -o issue.json`

Error:
```
In file: /home/vagrant/p4c/backends/bmv2/header.cpp:204
Compiler Bug: /usr/local/share/p4c/p4include/core.p4(23): error { NoError, PacketTooShort, NoMatch, StackOutOfBounds, HeaderTooShort, ParserTimeout }: unexpected type for struct test_struct {
  error { NoError, PacketTooShort, NoMatch, StackOutOfBounds, HeaderTooShort, ParserTimeout } test_error; }.test_error
error {
^
issue.p4(6)
struct test_struct {
       ^^^^^^^^^^^
issue.p4(7)
  error test_error;
        ^^^^^^^^^^
```

**Comment by mbudiu-vmw** [comment]
We can implement converting errors to integers quite easily, but we should implement a solution that allows us to also pass errors from the parser. In other words, we should give a solution that also solves #808. @antoninbas : we may need some support from BMv2 to do this properly. Do you have a suggestion?

**Comment by antoninbas** [comment]
bmv2 expects all errors to have been converted to integers and expects the `error` array in the JSON to have been populated appropriately (https://github.com/p4lang/behavioral-model/blob/master/docs/JSON_format.md#errors)
I'm not sure how it relates to #808 but I am definitely recommending replacing `bit<1> checksum_error` in the standard metadata header by a more general `error parser_error` if possible. Then people would be able to run the following code in bmv2:
```
// in ingress
if (std_metata.parser_error != error.NoError) drop();
```
which in the bmv2 JSON would have been replaced by:
```
if (std_metata.parser_error != 0) drop();
```

**Comment by mbudiu-vmw** [comment]
I will close this issue.
