### ISSUE TITLE
PSA examples fail compilation with p4c-bm2-psa: packet_path

### ISSUE THREAD

**Issue by rosstex** [p4lang/p4c#1329]
When compiling the example PSA programs from https://github.com/p4lang/p4-spec/tree/master/p4-16/psa/examples with the new p4c-bm2-psa implementation, I am getting the following error:

````
In file: /home/vagrant/p4c/backends/bmv2/psa_switch/psaSwitch.cpp:350
Compiler Bug: ../psa.p4(96): <Type_Enum>(244): Unhandled type for <Type_Enum>(244) packet_path
enum PSA_PacketPath_t {
^^^^
../psa.p4(110)
  PSA_PacketPath_t packet_path;
                   ^^^^^^^^^^^
````

**Comment by hanw** [comment]
Hi Ross, this is a known issue, we have not finished the implementation of psa backend yet.

**Comment by rosstex** [comment]
I see, thanks! Do you have an estimate for when the PSA implementation will be complete?

**Comment by hanw** [comment]
Working on it as we speak, but probably will get it done faster with more help from the community =).

**Comment by debmalyapan53** [comment]
[psa-example-bridged-metadata.p4.txt](https://github.com/p4lang/p4c/files/2525436/psa-example-bridged-metadata.p4.txt)
I am getting the following error: 
![virtualbox_p4compiler_29_10_2018_19_08_34](https://user-images.githubusercontent.com/35651463/47653430-96776680-dbae-11e8-9658-ef13060de28c.png)

**Comment by jafingerhut** [comment]
@debmalyapan53 I believe the psa back end is not complete yet, as Han commented above.  Interested in some compiler work?

**Comment by mbudiu-vmw** [comment]
Although the PSA backend is still not complete, I believe that this issue can be closed. At least I am not getting the same error.

**Comment by jafingerhut** [comment]
Agreed that the errors are different now than they were then, because the PSA implementation is definitely getting closer to complete.  Still errors on most of the examples in that directory of the p4lang/p4-spec repository, but hopefully we will get some more of them working within a month or three.

**Comment by machadoatz** [comment]
@jafingerhut Do you think the current state of PSA implementation is able to support firewall and policer programs (similar to tutorials) while targeting PSA_Switch?

**Comment by jafingerhut** [comment]
You are welcome to try, but the p4c compiler back end for PSA is currently in a state where some fairly simple programs compile correctly, but other fairly simple ones do not.  I don't have any quick summary of what works and what does not at the moment.
