### ISSUE TITLE
No Supported target-arch-vendor triplet found

### ISSUE THREAD

**Issue by arijeetsat** [p4lang/p4c#1341]
When I try to compile a .p4 file using the command 
`p4c -b bmv2-ss-p4org basic.p4 -o basic.bmv2.json`

its shows error : 
`usage: p4c [-h] [-V] [-v] [-###] [-Xpreprocessor <arg>] [-Xp4c <arg>]
           [-Xassembler <arg>] [-Xlinker <arg>] [-b BACKEND] [-c]
           [-D PREPROCESSOR_DEFINES] [-E] [-e] [-g] [-I SEARCH_PATH] [-o PATH]
           [--p4runtime-file P4RUNTIME_FILE]
           [--p4runtime-format {binary,json,text}] [--target-help] [-S]
           [-x {p4-14,p4-16}]
           [source_file]`

`p4c: error: Unknown backend: bmv2-ss-p4org`

**While checking the backend ,its shows nothing** 
`p4c --target-help bmv2`
`Supported targets in "target-arch-vendor" triplet:`

**How to install the backends?**

**Comment by cc10512** [comment]
the backends are installed in `$prefix/share/p4c` when you do `make install`, or in the build directory for a developer env (that is, when you just use the compiler from the build directory without a make install).
It is not clear which compiler are you using. Couple of suggestions:
`which p4c` to see which compiler you are using.

Here is how the output should look like if you configured your compiler correctly:
```
build> ./p4c --target-help
Supported targets in "target, arch" tuple:
bmv2-v1model
bmv2-psa
ebpf-v1model
```

**Comment by arijeetsat** [comment]
Yup I am getting the same output as yours,its resolved now, I think the problem was with using `bmv2 `.
Now, can you tell me , what command I should use to compile a p4 program?

**Comment by cc10512** [comment]
For bmv2 compilation I recommend:
`p4c --target bmv2 --arch v1model [--std=p4-14] -o <output_dir> program.p4`
The PSA support is still experimental, so YMMV.

**Comment by arijeetsat** [comment]
Thanks @cc10512 , I solved the problem , there was some problem while installing p4c, specially at the `cmake ..` part , which has to be run with DEBUG mode.

I removed the directory , and run it properly ,now everything is working fine, I have also referred : https://github.com/jafingerhut/p4-guide for installation.
