### ISSUE TITLE
Why is dot prefix handled differently in expressions and in prefixed types?

### ISSUE THREAD

**Issue by SantiagoBautista** [p4lang/p4c#1342]
According to the P4 semantics, the meaning of a dot prefix is always the same: it tells that the given name corresponds to the toplevel scope.

But in the implementation (and in the grammar), a dot prefix for prefixedType and prefixedNonTypeName rules uses the dotPrefix non-terminal (and triggers calls to `driver.structure->startAbsolutePath()` and `driver.structure->clearPath()` in the implementation) while a dot prefix in expressions doesn't.

Could someone tell me why this is so, please? :)

**Comment by mbudiu-vmw** [comment]
The lexer needs to distinguish TYPE_IDENTIFIER from IDENTIFIER. For this purpose it has a symbol table which is populated when new types are declared. The symbol table will distinguish between global types and local types. Although I don't think we can actually have local types, so perhaps that's unnecessary at this point. driver.structure only has to deal with this symbol table.

**Comment by SantiagoBautista** [comment]
It is possible to have local types: the type parameters of a control, for example, introduce type names that are local to the scope of the control.

So, if I understand correctly, `driver.structure->startAbsolutePath()` allows to take into account only the global type names, and not the local type names.

**Comment by SantiagoBautista** [comment]
Yes, I just checked, and that is what happens: `driver.structure->startAbsolutePath()` sets `lookupContext` to `rootNamespace` , which allows the path being read to be parsed according to the symbol table that corresponds to the toplevel.

And this means that, for expressions that are a dot prefixed name, _there is a bug in the current parser_ (file `frontend/parsers/p4/p4parser.ypp` , line 1047) because when using the dot prefix for a variable, `driver.structure->startAbsolutePath()` should be called, and it isn't.

I created pr #1343 solving this bug, and associated pr#649 in p4-spec that reflects this change into the grammar.

**Comment by SantiagoBautista** [comment]
I suggest leaving this issue open so that it reminds me of including the testcase when functions are supported.

**Comment by jafingerhut** [comment]
So I know that "hierarchical names" can be used as the values in @name annotations, used in controlling what names are exposed via the control plane API.

Is it really intended that hierarchical names, or names prefixed with a ".", are usable outside of annotations, too?  I had never seen such a thing used outside of a @name annotation before in a P4 program, but perhaps I haven't seen enough P4 programs to have encountered it before, e.g. like the example program below copied from this comment: https://github.com/p4lang/p4c/pull/1343#issuecomment-397084928
```
const bit X = 1; 

extern Virtual {
    Virtual();
    abstract bit f<X>();
}

Virtual() cntr = {
  bit f<X>(){
    return .X;
  }
}
```
Is it possible to write arbitrary hierarchical names in place of the ".X" in that example?  I would guess no, as that would seem to violate what values are accessible at a particular point in execution of the code.

**Comment by SantiagoBautista** [comment]
Hi @jafingerhut ,
It seems to be intended that names prefixed by a "." can be used in any expression to access the top-level namespace.
This is described in the section 6.8 of the spec. 
This feature is used by the programs struct.p4 and struct1.p4 in the p4c/testdata/p4_16_samples/ directory. But the program on #1343 comment is a crafted example, it is not a real-wolrd P4 program (and if fact it is not correct, as type parameters are not accepted in the instantiation of abstract methods [or at least that what it seems]).

**Comment by jafingerhut** [comment]
Thanks for the P4_16 spec section reference.  There it addresses my questions, too, where it says: "Declarations within a parser or control are private and cannot be referred to from outside of the enclosing parser or control."

**Comment by mbudiu-vmw** [comment]
The initial design or p4-16 had nested namespaces, but we gave these up because they were too complex. The dots are a vestige of that design, which may come back at some point. There's also an IR class called PathExpression, which was meant to represent namespace paths, which is not of much use, but appears everywhere.

**Comment by mbudiu-vmw** [comment]
Can we close this issue?

**Comment by SantiagoBautista** [comment]
Sure.
