### ISSUE TITLE
[Problem] In-band networking telemetry example code.

### ISSUE THREAD

**Issue by kevinbird61** [p4lang/p4c#1347]
I've encounter a problem of implementing the INT example code that mention in [p4.org - INT spec, Section 6: P4 Program specification for INT Transit](https://github.com/p4lang/p4-applications/blob/master/docs/INT.pdf), but there shown error message after running compile command （running `make` provided by [Makefile](https://github.com/kevinbird61/p4-researching/blob/master/INT/Makefile)）.

Here is the code I get from the INT spec - [int-transit.p4](https://github.com/kevinbird61/p4-researching/blob/master/INT/int-transit.p4)
And the error message I found: 
```sh
int-transit.p4(171): [--Wwarn=uninitialized_out_param] warning: out parameter normal_meta may be uninitialized when IngressDeparserImpl terminates
    out metadata normal_meta,
                 ^^^^^^^^^^^
int-transit.p4(167)
control IngressDeparserImpl(
        ^^^^^^^^^^^^^^^^^^^
int-transit.p4(767): error: package PSA_Switch: main package does not match the expected model
)main;
 ^^^^
error: Are you using an up-to-date v1model.p4?
int-transit.p4(767): error: package PSA_Switch: main package does not match the expected model
)main;
 ^^^^
error: Are you using an up-to-date v1model.p4?
Makefile:4: recipe for target 'int' failed
make: *** [int] Error 1
```

And checking out the [p4c/psa.p4 (L681)](https://github.com/p4lang/p4c/blob/master/p4include/psa.p4#L681) , still can't find why the error said can not match "main" package.

---
Another try: using `p4c-bm2-psa` to compile, still can't fix the problem, another error message: 
```sh
p4c-bm2-psa --std p4-16 -o int.json \
        --p4runtime-file int.p4info \
        --p4runtime-format text int-transit.p4
int-transit.p4(171): [--Wwarn=uninitialized_out_param] warning: out parameter normal_meta may be uninitialized when IngressDeparserImpl terminates
    out metadata normal_meta,
                 ^^^^^^^^^^^
int-transit.p4(167)
control IngressDeparserImpl(
        ^^^^^^^^^^^^^^^^^^^
make: *** [int] Segmentation fault: 11
```
---

Thank for any help !

**Comment by mbudiu-vmw** [comment]
The PSA implementation for the compiler and simulator is still under development.

**Comment by kevinbird61** [comment]
@mbudiu-vmw  Thanks for your reply! 
Maybe I can use `V1Switch` in v1model.p4 to adapt `INT` for current situation? 
Or there have another better solutions?

**Comment by mbudiu-vmw** [comment]
v1model works pretty well. I would expect there should exist a version of int for v1model somewhere.
