### ISSUE TITLE
v1model digest extern fails bmv2 assertion

### ISSUE THREAD

**Issue by rosstex** [p4lang/p4c#1352]
I am doing a simple digest test with bmv2-ss and the V1model, and calling the digest() extern causes the bmv2 switch to crash after the first packet it sees.

The issue is:
```
[21:15:00.182] [bmv2] [D] [thread 15611] [0.0] [cxt 0] Table 'tbl_act_1': miss
[21:15:00.182] [bmv2] [D] [thread 15611] [0.0] [cxt 0] Action entry is act_1 -
Assertion 'Default switch case should not be reachable' failed, file '../../include/bm/bm_sim/actions.h' line '318'.
```

My headers:
```
struct test_digest_t {
    macAddr_t in_mac_srcAddr;
}
struct metadata {
    bool                dfa_accept;
    dfa_accept_digest_t dfa_accept_digest;
    test_digest_t       test_digest;
}
```

In my Ingress control's apply func, I have:
```meta.test_digest.in_mac_srcAddr = hdr.ethernet.srcAddr;```

and in Egress, I have:
```digest(1, meta.test_digest);```

The generated .json is:
```
    {
      "name" : "act_1",
      "id" : 15,
      "runtime_data" : [],
      "primitives" : [
        {
          "op" : "assign",
          "parameters" : [
            {
              "type" : "header",
              "value" : "tmp_0"
            },
            {
              "type" : "header",
              "value" : "userMetadata.test_digest"
            }
          ],
          "source_info" : {
            "filename" : "ross_dfa_int.p4",
            "line" : 286,
            "column" : 18,
            "source_fragment" : "meta.test_digest"
          }
        },
        {
          "op" : "generate_digest",
          "parameters" : [
            {
              "type" : "hexstr",
              "value" : "0x00000001"
            },
            {
              "type" : "hexstr",
              "value" : "0x2"
            }
          ]
        }
      ]
    }
```

I'm not sure if this is a compiler issue or a bmv2 issue.

**Comment by antoninbas** [comment]
The "op" should be "assign_header" not "assign" for header assignments. This is indeed a bug in the bmv2 compiler backend.

**Comment by mbudiu-vmw** [comment]
The back-end code seems to generate "assign_header" for headers. Do you have a test programs we can use to reproduce this?

**Comment by rosstex** [comment]
Sure, here's a stripped-down p4 implementation that has this bug.

[ross_dfa_int.p4.txt](https://github.com/p4lang/p4c/files/2121270/ross_dfa_int.p4.txt)

**Comment by mbudiu-vmw** [comment]
@antoninbas: So tmp_0 is a test_digest_t, which is a struct, which compiles to a header_type instance which is actually metadata. Does that require an "assign" or an "assign_header"?

**Comment by antoninbas** [comment]
metadata header instance are still headers, so `assign_header`

**Comment by mbudiu-vmw** [comment]
I hope we can close this issue.
