### ISSUE TITLE
Function "truncate" problem

### ISSUE THREAD

**Issue by tomyhu1995** [p4lang/p4c#1354]
Hi all, 
I am trying to use `truncate` to eliminate payload of packet. The following is the code I use:

```
   action no_payload() {
        truncate(0);
    }
    apply {
            if (standard_metadata.enq_qdepth >= ECN_THRESHOLD){
                no_payload();
            }
    }
```

In my opinion, the packet's payload will be eliminate when queue length is larger than `ECN_THRESHOLD`. However, it doesn't work. Receiver can't receive any packet. And I change the parameter of truncate( change 0 to 34). Receiver can receive packet which only include mac+ipv4 header. 

My question is: what is the detail definition of truncate on bmv2? How to eliminate payload by using truncate?

**Comment by antoninbas** [comment]
What you are describing makes sense to me. The bmv2 truncate primitive applies to the deparsed packet I believe, not to the payload specifically. So if you truncate to 0, the packet is dropped.

**Comment by tomyhu1995** [comment]
@antoninbas  It is real make sense to me, too. 
I was confused by this issue #303. I do believe your explanation is correct and make sense. Thanks a lot
