### ISSUE TITLE
-bash: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by djshah19** [p4lang/p4c#1356]
When executing below command getting this error  "-bash: syntax error near unexpected token `('"

cmake .. [-DCMAKE_BUILD_TYPE=RELEASE|DEBUG] [-DCMAKE_INSTALL_PREFIX=<path>] [-DENABLE_DOCS=ON (default off)] [-DENABLE_P4RUNTIME_TO_PD=OFF (default on)] [-DENABLE_PROTOBUF_STATIC=OFF (default on)]

**Comment by ChrisDodd** [comment]
What arguments are you trying to use with cmake?  That's not an example command line, that's a description of the legal and optional arguments -- you need to choose which arguments are appropriate for your use.

As a minimal example, you could use just `cmake ..` -- arguments described in `[`...`]` are optinal.
