### ISSUE TITLE
LOG statements in header files are never executed

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#1367]
@ChrisDodd : I was hoping that these would be triggered by -TincludingFile, but that does not seem to happen. How can we add LOG statements to classes that use templates and are implemented fully in header files?

**Comment by ChrisDodd** [comment]
I thought we fixed this -- though you need the full name of the header.  So -Tsomeheader.h:3 will print log level 1/2/3 statements in someheader.h.  Or matches with `*` at the end (eg `-Ttype*:3` -- will get every file, source or header, that starts with `type`)

**Comment by mbudiu-vmw** [comment]
Yes, it works. I didn't realize that you have to type the whole file name.
I should document this.
