### ISSUE TITLE
STF Python Parser: Complete?

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#1371]
Hello,
I have a question about the stf python parser located in p4c/tools. I would like to use it to parse and process .stf files. For that purpose, `stf_parser.py` seems to be working fine. It provides me with a list of tuples which I can use to distinguish between add, packet, expect, etc operations.

However, it seems the parser is meant to do more than providing a list of tuples. Unfortunately, I cannot run `stf_test.py`, since the code is missing `STFNamedEntry` and `match2spec`. Are these code fragments missing? Or how is the parser meant to be used?

Best and thanks

**Comment by cc10512** [comment]
The intent of publishing the parser was to enable using the STF "language" with other test frameworks. There were several requests to enhance the testing infrastructure. See discussions on #899 and #961.

`STFNamedEntry` is defined in stf_runner.py.

`match2spec` was intended as an abstract function that needs to be implemented based on what your target is. Here is the prototype:
```
    def match2spec(self, table_name, match_name, match):
        """
            Turns a match into (escaped name, value, mask, hasMask)
            Returning a hasMask = False means there were no don't care symbols in the value
        """
```
Essentially has to deal with the conversion of names in STF to your test framework. For the purpose of stf_test.py you can simply compute the value and the mask (check whether there is a `*` in match parameter and set those to be masked) and set hasMask to true if there are any.

**Comment by fruffy** [comment]
Thank you for the quick reply! I will try that.
