### ISSUE TITLE
llvm dependencies in ebpf backend can cause cmake problems.

### ISSUE THREAD

**Issue by ChrisDodd** [p4lang/p4c#1376]
Pulling the latest p4c, when I run cmake I get some errors:

    CMake Warning at p4c/backends/ebpf/CMakeLists.txt:107 (MESSAGE):
      Kernel version 4.10.0 too small, expected 4.16.0.  Ignoring ebpf kernel
      tests...

    CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:178 (include):
      include could not find load file:

        /usr/share/llvm/cmake/LLVMExports.cmake
    Call Stack (most recent call first):
      p4c/backends/ebpf/CMakeLists.txt:114 (find_package)

    CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:181 (include):
      include could not find load file:

        /usr/share/llvm/cmake/LLVM-Config.cmake
    Call Stack (most recent call first):
      p4c/backends/ebpf/CMakeLists.txt:114 (find_package)

If I comment out the `find_package(LLVM)` line in that last cmake file, everything configures, but some stuff is disabled.

The README.md file just says that llvm 3.7.1 **or later** is required.  Is the problem llvm 3.8?

**Comment by antoninbas** [comment]
I had the same issue, I had to run `cmake` with `-DEENABLE_EBPF` to get rid of it.

**Comment by mbudiu-vmw** [comment]
This seems to be a bug in the llvm package for some ubuntu versions. The makefile has a link to a stackoverflow post describing a fix. It would be nice if the find-package would not crash and would just return false...

**Comment by mbudiu-vmw** [comment]
Here is the link describing the problem and the solution:
https://stackoverflow.com/questions/38171543/error-when-using-cmake-with-llvm
It is in a pending PR.
I am not sure what to do about it in the makefile.

**Comment by fruffy** [comment]
BCC seems to have a similar problem. This issue discusses several more workarounds:
https://github.com/iovisor/bcc/issues/492
