### ISSUE TITLE
Constant folding for select cases

### ISSUE THREAD

**Issue by theojepsen** [p4lang/p4c#1397]
I have a select that looks like this:

    return select(udp.length_) {
        SIZE0: ingress;
        SIZE1: parse_1bytes;
        SIZE2: parse_2bytes;
        ...

Where the `SIZE*` is defined as:

    #define SIZE0    (UDP_HDR_SIZE + MY_HDR_SIZE + 0)
    #define SIZE1    (UDP_HDR_SIZE + MY_HDR_SIZE + 1)

These are all constants, so I expect the compiler to fold the keys of the select cases. However, I get the following error:

    .../parser.p4(89): error: Expected constant or parser value set in +
        (8 + 5 + 0): ingress;
               ^

I think the solution is to accept other types of expressions (e.g. Add) here:
https://github.com/p4lang/p4c/blob/master/frontends/p4/fromv1.0/programStructure.cpp#L481

My program compiled after adding the following to that if/else block:

                } else if (auto first = v.first->to<IR::Add>()) {
                    auto sc = new IR::SelectCase(c->srcInfo, first, deststate);
                    cases.push_back(sc);
                } else {

After the constant folding pass, it seems like the expression becomes a constant.

I think this solution only works for + expressions. How can this be generalized to any constant expression?

**Comment by hanw** [comment]
Please submit a minimal but complete test program.

**Comment by theojepsen** [comment]
Hi @hanw,
Here's a minimal example that does not currently compile. With the change I showed above, it compiles.
[const_select.p4.txt](https://github.com/p4lang/p4c/files/2182180/const_select.p4.txt)

**Comment by hanw** [comment]
Attached example is a P4-14 program and appears to fail in P4-14 to 16 translation.

**Comment by hanw** [comment]
@theojepsen I checked P4-14 grammar, it seems the provided program is not a valid P4-14 program. P4-14 does not allow arbitrary expression in select case. P4-16, on the other hand, does.

**Comment by hanw** [comment]
If we really want to allow this, we should also modify the spec.

**Comment by hanw** [comment]
Changing the `else if` check to `else` would allow extern instance to be used as a select key, which makes little sense.

**Comment by mbudiu-vmw** [comment]
I would rather add a "-strict" flag to the compiler. If the flag is true we can reject such programs.
The type-checker will reject selects with extern cases later anyway. You don't need to do it now.

**Comment by cc10512** [comment]
At best this should be an experimental feature. But I thought we are not going to make such changes to P4_14.
