### ISSUE TITLE
P4_14 converter: "Wat" edition

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#1403]
@liujed and I were playing with some tiny examples in the P4 compiler today...

According to the [P4<sub>14</sub> specification, version 1.0.4](https://p4.org/p4-spec/p4-14/v1.0.4/tex/p4.pdf)

> If no width precedes the value, then the width is inferred. For positive values the inferred width is the smallest number of bits required to contain the value.

The specification does not describe the meaning of the plus operator, but elsewhere it says that for unsigned/unsaturating header fields:

> addition/subtraction causing overflow/underflow will wrap

Section 9.1.1 specifies that the value returned is modulo 2^width.

Now consider the following examples.

----

Compiling 
```p4
parser start { return ingress; }
table t { actions {} }        
control ingress {
  if (1+1 == 0) { apply(t); }
}
```
with the command
```
p4c --std p4-14 tiny.p4
```
yields
```
tiny.p4(2): warning: Table .t is not used; removing
table t { actions {} }
^^^^^^^^^^^^^^^^^^^^^^
```
That is, the compiler has statically determined (incorrectly, we believe) that the condition is false. The smallest width that can hold `1` is 1, and the addition overflows, which should yield `0` on the left hand side.

----

Compiling 
```p4
parser start { return ingress; }
table t { actions {} }        
control ingress {
  if (1w1+1 == 0) { apply(t); }
}
```
with the same command yields no warning. In this case, the compiler has statically determined (correctly, we believe) that the condition is true.

----

Compiling 
```p4
parser start { return ingress; }
table t { actions {} }        
control ingress {
  if (1 + 1 == 1w0) { apply(t); }
}
```
yields
```
tiny.p4(4): warning: 2: value does not fit in 1 bits
  if (1+1 == 1w0) { apply(t); }
tiny.p4(2): warning: Table .t is not used; removing
table t { actions {} }
^^^^^^^^^^^^^^^^^^^^^^
```
That is, the compiler has statically determined that the condition is false. Again, we think this is incorrect. And confusingly, the warning about 2 not fitting into 1 bits seems either irrelevant or ignored.

----

Compiling 
```p4
parser start { return ingress; }
table t { actions {} }        
control ingress {
  if (1 + 1w1== 1w0) { apply(t); }
}    
```
yields no warning. That is, the compiler has statically (and correctly we believe) determined that the condition is true. 

----

Compiling 
```p4
parser start { return ingress; }
table t { actions {} }        
control ingress {
  if (2 + 1w1== 1w0) { apply(t); }
}    
```
yields warnings:
```
tiny.p4(4): warning: 2: value does not fit in 1 bits
  if (2+1w1 == 1w0) { apply(t); }
      ^
tiny.p4(2): warning: Table .t is not used; removing
table t { actions {} }
^^^^^^^^^^^^^^^^^^^^^^
```
That is, the compiler has statically determined that the condition is false. We think the spec doesn't mandate what must happen here. It could be that the addition on the left is carried out using width 2 values and then truncated. Or it could be that the addition is all carried out in width 1. Either way, this behavior and the compiler messages are certainly confusing.

----

Finally, compiling 
```p4
parser start { return ingress; }
table t { actions {} }        
control ingress {
  if (3 + 1w1== 1w0) { apply(t); }
}    
```
yields warnings:
```
tiny.p4(4): warning: 3: value does not fit in 1 bits
  if (3+1w1 == 1w0) { apply(t); }
      ^
```
That is, the compiler has statically determined that the condition is true. Again, we think the spec doesn't mandate what must happen here, but that this behavior and the compiler messages are certainly confusing.

----

So, with apologies to Gary Bernhardt...

![Wat](https://www.i-programmer.info/images/stories/prof/iprogrammer/WAT/wat.jpg)

**Comment by liujed** [comment]
A couple more:
Compiling 
```p4
parser start { return ingress; }
table t { actions {} }        
control ingress {
  if (2w1-2w2 == -1) { apply(t); }
}
```
yields warnings:
```
tiny.p4(4): warning: -1: negative value with unsigned type
  if (2w1-2w2 == -1) { apply(t); }
                  ^
tiny.p4(2): warning: Table .t is not used; removing
table t { actions {} }
^^^^^^^^^^^^^^^^^^^^^^
```
The compiler has statically determined that the condition is false. But compiling
```p4
parser start { return ingress; }
table t { actions {} }        
control ingress {
  if (2w1-2w2 == -2w1) { apply(t); }
}
```
yields no warning, so the compiler has statically determined that the condition is true. We believe this second result is correct, but should give the `negative value with unsigned type` warning seen in the first result.

**Comment by jnfoster** [comment]
I'm convinced: we should fix the P4_14 spec. I'll bring it up with the LDWG.

I also believe this (reasonable) change is unlikely to break existing code since the `p4-hlir` front-end doesn't actually let programmers write down explicit widths (except in field list calculations).
