### ISSUE TITLE
A .pp file was accidentaly added to testdata/p4_16_samples

### ISSUE THREAD

**Issue by SantiagoBautista** [p4lang/p4c#1411]
I may be wrong, 
but I get the impression that the file
[v1model-newtype.pp]( https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples/v1model-newtype.pp ) in testdata/p4_16_samples has been added by accident.
It doesn't test the newtype feature as its name suggests, and it is nor a `.p4` nor a `.stf` file as all the other files in that directory.

@mbudiu-vmw

**Comment by mbudiu-vmw** [comment]
That file is included in psa-portid-using-newtype2.p4 which is tested.
There is comment explaining why the .pp suffix is being used.

**Comment by SantiagoBautista** [comment]
Oh ok. I hadn't seen it; my bad
