### ISSUE TITLE
Boolean expression not translated properly in bmv2 backend

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#1412]
The following P4 code:
```
    action set_true() {
        if (meta.field == 0) {
            meta.cond = true;
        }
    }
```
is not translated to valid bmv2 JSON.
More precisely, the use of a condition in the action leads to the use of the ternary (`?:`) operator in the JSON, which is expected, however **the 2 operands have different types** according to bmv2 (one is a boolean, while the other is a 1-bit values):
```
"value" : {
                      "op" : "?",
                      "left" : {
                        "type" : "bool",
                        "value" : true
                      },
                      "right" : {
                        "type" : "field",
                        "value" : ["scalars", "metadata.cond"]
                      },
                      "cond" : { ... }
```
This issue was originally created in the bmv2 repo (https://github.com/p4lang/behavioral-model/issues/629). A sample P4 program (along with the generated JSON) can be found here: https://gist.github.com/xenerizes/49a5a61a25c001aea1d6414d8ddcd8e6

**Comment by mbudiu-vmw** [comment]
in the conversion from IR to JSON some Boolean values are converted to 1-bit values.
it looks like the conversion of expressions is not systematic enough.
The right way to do this would be to do a separate pass to convert all expressions and insert casts. Today the casts are inserted only in the translation process. I am not sure I will have time to fix this too soon.
