### ISSUE TITLE
local_copyprop does not copyprop table key

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1426]
The attached program fails to compile with p4test

Command:
`./p4test --std p4-14 ~/vag6759.p4`

Diagnosis:
The problem seems to be in the DoLocalCopyPropagation pass, where the key saved in `key_remap` in line 524 does not match to the PathExpression that is used to do the lookup in line 125.

Program:
[vag6759.p4.txt](https://github.com/p4lang/p4c/files/2259138/vag6759.p4.txt)

Errror Message:
```
error: Could not find declaration for hdr_1_ethernet
error: Could not find declaration for hdr_1_ethernet
```

**Comment by ChrisDodd** [comment]
Fixed by #1427
