### ISSUE TITLE
Newbie:p4c make -j4 check ebpf fails

### ISSUE THREAD

**Issue by rdhillbb** [p4lang/p4c#1430]
ebpf tests 1 to 22 fail.
How to I check the reason for the failure? 
I installed p4c on ubuntu 18.04.

1/799 Test   #3: ebpf-bcc/testdata/p4_16_samples/action_call_table_ebpf.p4 .....................***Failed    0.01 sec
  2/799 Test   #2: ebpf-bcc/testdata/p4_16_samples/action_call_ebpf.p4 ...........................***Failed    0.01 sec
  3/799 Test   #4: ebpf-bcc/testdata/p4_16_samples/count_ebpf.p4 .................................***Failed    0.01 sec
  4/799 Test   #5: ebpf-bcc/testdata/p4_16_samples/hit_ebpf.p4 ...................................***Failed    0.01 sec
        Start   6: ebpf-bcc/testdata/p4_16_samples/issue870_ebpf.p4
        Start   7: ebpf-bcc/testdata/p4_16_samples/key-issue-1020_ebpf.p4
        Start   8: ebpf-bcc/testdata/p4_16_samples/key_ebpf.p4
        Start   9: ebpf-bcc/testdata/p4_16_samples/switch_ebpf.p4
  5/799 Test   #9: ebpf-bcc/testdata/p4_16_samples/switch_ebpf.p4 ................................***Failed    0.02 sec
  6/799 Test   #8: ebpf-bcc/testdata/p4_16_samples/key_ebpf.p4 ...................................***Failed    0.02 sec

**Comment by ChrisDodd** [comment]
Look in build/p4c/Testing/Temporary/LastTest.log -- this is the full log of the last test run, and will include the trace of the test runs, including what error were seen,

**Comment by rdhillbb** [comment]
Thank you Chris. I will test this tomorrow night. Late here in Singapore.
Cheers

**Comment by mbudiu-vmw** [comment]
Unless you provide more information we cannot help you debug the problem.

**Comment by rdhillbb** [comment]
I have revisited this issue I posted. I need to play closer attention to the instructions. Also, my linux skills are rusty after being away for 15+ years.
