### ISSUE TITLE
Makefile:138: recipe for target 'all' failed

### ISSUE THREAD

**Issue by fefer** [p4lang/p4c#1432]
I'm trying to install p4c and I'm getting the following error. I saw that someone had a similar problem running on a VM with low resources, I'm running my VM with 4 cores and 9.55GB of RAM and still getting similar output. I've tried to make -j1, make -j4 and cmake .. -DENABLE_UNIFIED_COMPILATION=OFF. However, I'm still getting this error:

root@ubuntu:~/p4c/build#  cmake ..
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   iostreams
--   regex
-- Could NOT find PY_tenjin (missing:  PY_TENJIN) 
-- Program 'simple_switch_CLI' (https://github.com/p4lang/behavioral-model.git) not found;
Searched /usr/local/bin;/root/p4c/../behavioral-model/build/targets/simple_switch;/root/p4c/../../behavioral-model/build/targets/simple_switch.
Will not run BMv2 tests. (missing:  SIMPLE_SWITCH SIMPLE_SWITCH_CLI) 
-- Using the GNU gold linker.
targets: /root/p4c/build/p4c_src/main.py;/root/p4c/build/p4c_src/driver.py;/root/p4c/build/p4c_src/util.py;/root/p4c/build/p4c_src/config.py;/root/p4c/build/p4c_src/__init__.py;/root/p4c/build/p4c_src/p4c.bmv2.cfg;/root/p4c/build/p4c_src/p4c.ebpf.cfg
-- Available extensions 
CMake Warning at backends/bmv2/CMakeLists.txt:121 (MESSAGE):
  BMv2 simple switch is not available, not adding BMv2 tests

-- Added 9 tests to 'ebpf' (0 xfails)
-- Added 497 tests to 'p4' (1 xfails)
-- Added 181 tests to 'p14_to_16' (0 xfails)
-- CTest parallel: -j 4
-- Configuring done
-- Generating done
-- Build files have been written to: /root/p4c/build
root@ubuntu:~/p4c/build# make -j4
[  0%] Built target linkgraphs
[  0%] Built target update_includes
[  0%] Built target linkbmv2
[  0%] Built target linkp4cebpf
[  1%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/bitvec.cpp.o
[  1%] Built target linkp4test
[  1%] Built target mkp4dirs
[  1%] Built target mkv1dirs
[  2%] Building CXX object test/CMakeFiles/gtest.dir/frameworks/gtest/googletest/src/gtest-all.cc.o
[  2%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/compile_context.cpp.o
[  2%] Built target mkP4configdir
[  2%] Copying p4c driver
[  2%] Built target p4c_driver
[  3%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/crash.cpp.o
[  3%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/cstring.cpp.o
[  4%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/gc.cpp.o
[  4%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/gmputil.cpp.o
[  4%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/hex.cpp.o
[  5%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/indent.cpp.o
[  5%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/json.cpp.o
[  6%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/log.cpp.o
[  6%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/match.cpp.o
[  7%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/nullstream.cpp.o
[  7%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/options.cpp.o
[  8%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/path.cpp.o
[  8%] Linking CXX static library libgtest.a
[  8%] Built target gtest
[  8%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/source_file.cpp.o
[  8%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/stringify.cpp.o
[  9%] Linking CXX static library libp4ctoolkit.a
[  9%] Built target p4ctoolkit
[ 10%] [BISON][IRgenParser] Building parser with bison 3.0.4
[ 10%] [FLEX][IRgenLexer] Building scanner with flex 2.6.0
Scanning dependencies of target irgenerator
[ 10%] Building CXX object tools/ir-generator/CMakeFiles/irgenerator.dir/type.cpp.o
[ 10%] Building CXX object tools/ir-generator/CMakeFiles/irgenerator.dir/generator.cpp.o
[ 11%] Building CXX object tools/ir-generator/CMakeFiles/irgenerator.dir/irclass.cpp.o
[ 11%] Building CXX object tools/ir-generator/CMakeFiles/irgenerator.dir/methods.cpp.o
[ 12%] Building CXX object tools/ir-generator/CMakeFiles/irgenerator.dir/ir-generator.cpp.o
[ 12%] Linking CXX executable irgenerator
[ 12%] Built target irgenerator
[ 12%] Generating IR class files
[ 12%] Built target genIR
make[2]: *** No rule to make target '../control-plane/PI/proto/p4/config/p4info.proto', needed by 'control-plane/p4/config/p4info.pb.cc'.  Stop.
CMakeFiles/Makefile2:1069: recipe for target 'control-plane/CMakeFiles/controlplane.dir/all' failed
make[1]: *** [control-plane/CMakeFiles/controlplane.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
frontends/CMakeFiles/frontend.dir/build.make:91: warning: overriding recipe for target 'frontends/parsers/v1/v1parser.output'
frontends/CMakeFiles/frontend.dir/build.make:73: warning: ignoring old recipe for target 'frontends/parsers/v1/v1parser.output'
Scanning dependencies of target midend
[ 13%] [BISON][v1Parser] Building parser with bison 3.0.4
[ 12%] [BISON][p4Parser] Building parser with bison 3.0.4
Scanning dependencies of target ir
[ 14%] Building CXX object ir/CMakeFiles/ir.dir/base.cpp.o
[ 15%] Building CXX object midend/CMakeFiles/midend.dir/actionSynthesis.cpp.o
[ 15%] Building CXX object ir/CMakeFiles/ir.dir/dbprint.cpp.o
[ 15%] Running Flex on parsers/v1
[ 17%] Running Flex on parsers/p4
Scanning dependencies of target frontend
frontends/CMakeFiles/frontend.dir/build.make:91: warning: overriding recipe for target 'frontends/parsers/v1/v1parser.output'
frontends/CMakeFiles/frontend.dir/build.make:73: warning: ignoring old recipe for target 'frontends/parsers/v1/v1parser.output'
[ 17%] Building CXX object frontends/CMakeFiles/frontend.dir/common/applyOptionsPragmas.cpp.o
[ 17%] Building CXX object midend/CMakeFiles/midend.dir/complexComparison.cpp.o
[ 18%] Building CXX object ir/CMakeFiles/ir.dir/dbprint-expression.cpp.o
[ 19%] Building CXX object frontends/CMakeFiles/frontend.dir/common/constantFolding.cpp.o
[ 19%] Building CXX object ir/CMakeFiles/ir.dir/dbprint-stmt.cpp.o
[ 19%] Building CXX object ir/CMakeFiles/ir.dir/dbprint-type.cpp.o
[ 20%] Building CXX object midend/CMakeFiles/midend.dir/convertEnums.cpp.o
[ 21%] Building CXX object ir/CMakeFiles/ir.dir/dbprint-p4.cpp.o
[ 21%] Building CXX object frontends/CMakeFiles/frontend.dir/common/constantParsing.cpp.o
[ 21%] Building CXX object ir/CMakeFiles/ir.dir/dump.cpp.o
[ 21%] Building CXX object midend/CMakeFiles/midend.dir/copyStructures.cpp.o
[ 22%] Building CXX object ir/CMakeFiles/ir.dir/expression.cpp.o
[ 23%] Building CXX object frontends/CMakeFiles/frontend.dir/common/options.cpp.o
[ 24%] Building CXX object midend/CMakeFiles/midend.dir/eliminateTuples.cpp.o
[ 24%] Building CXX object midend/CMakeFiles/midend.dir/expandEmit.cpp.o
[ 24%] Building CXX object ir/CMakeFiles/ir.dir/ir.cpp.o
[ 24%] Building CXX object frontends/CMakeFiles/frontend.dir/common/parseInput.cpp.o
[ 25%] Building CXX object ir/CMakeFiles/ir.dir/json_parser.cpp.o
[ 25%] Building CXX object midend/CMakeFiles/midend.dir/expandLookahead.cpp.o
[ 26%] Building CXX object frontends/CMakeFiles/frontend.dir/common/resolveReferences/referenceMap.cpp.o
[ 26%] Building CXX object ir/CMakeFiles/ir.dir/node.cpp.o
[ 27%] Building CXX object ir/CMakeFiles/ir.dir/pass_manager.cpp.o
[ 28%] Building CXX object midend/CMakeFiles/midend.dir/interpreter.cpp.o
[ 28%] Building CXX object midend/CMakeFiles/midend.dir/local_copyprop.cpp.o
[ 28%] Building CXX object frontends/CMakeFiles/frontend.dir/common/resolveReferences/resolveReferences.cpp.o
[ 28%] Building CXX object ir/CMakeFiles/ir.dir/type.cpp.o
[ 28%] Building CXX object ir/CMakeFiles/ir.dir/v1.cpp.o
[ 28%] Building CXX object frontends/CMakeFiles/frontend.dir/parsers/parserDriver.cpp.o
[ 29%] Building CXX object midend/CMakeFiles/midend.dir/nestedStructs.cpp.o
[ 30%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/actionsInlining.cpp.o
[ 31%] Building CXX object ir/CMakeFiles/ir.dir/visitor.cpp.o
[ 31%] Building CXX object midend/CMakeFiles/midend.dir/noMatch.cpp.o
[ 32%] Building CXX object midend/CMakeFiles/midend.dir/parserUnroll.cpp.o
[ 32%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/callGraph.cpp.o
[ 34%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/checkConstants.cpp.o
[ 34%] Building CXX object midend/CMakeFiles/midend.dir/predication.cpp.o
[ 34%] Building CXX object ir/CMakeFiles/ir.dir/write_context.cpp.o
[ 35%] Building CXX object midend/CMakeFiles/midend.dir/removeExits.cpp.o
[ 35%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/createBuiltins.cpp.o
[ 36%] Linking CXX static library libir.a
[ 36%] Built target ir
[ 37%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/def_use.cpp.o
[ 37%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/deprecated.cpp.o
[ 37%] Building CXX object midend/CMakeFiles/midend.dir/removeLeftSlices.cpp.o
[ 38%] Building CXX object midend/CMakeFiles/midend.dir/removeParameters.cpp.o
[ 39%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/directCalls.cpp.o
[ 39%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/dontcareArgs.cpp.o
[ 40%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/evaluator/evaluator.cpp.o
[ 40%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/evaluator/substituteParameters.cpp.o
[ 40%] Building CXX object midend/CMakeFiles/midend.dir/removeSelectBooleans.cpp.o
[ 40%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/externInstance.cpp.o
[ 41%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/fromv1.0/converters.cpp.o
[ 41%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/fromv1.0/programStructure.cpp.o
[ 41%] Building CXX object midend/CMakeFiles/midend.dir/removeUnusedParameters.cpp.o
[ 42%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/frontend.cpp.o
[ 43%] Building CXX object midend/CMakeFiles/midend.dir/simplifyBitwise.cpp.o
[ 43%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/hierarchicalNames.cpp.o
[ 44%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/inlining.cpp.o
[ 44%] Building CXX object midend/CMakeFiles/midend.dir/simplifyKey.cpp.o
[ 44%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/localizeActions.cpp.o
[ 45%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/methodInstance.cpp.o
[ 46%] Building CXX object midend/CMakeFiles/midend.dir/simplifySelectCases.cpp.o
[ 46%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/modelInstances.cpp.o
[ 46%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/moveConstructors.cpp.o
[ 47%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/moveDeclarations.cpp.o
[ 47%] Building CXX object midend/CMakeFiles/midend.dir/simplifySelectList.cpp.o
[ 47%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/parserCallGraph.cpp.o
[ 48%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/parserControlFlow.cpp.o
[ 48%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/removeReturns.cpp.o
[ 50%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/reservedWords.cpp.o
[ 51%] Building CXX object midend/CMakeFiles/midend.dir/synthesizeValidField.cpp.o
[ 51%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/resetHeaders.cpp.o
[ 52%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/setHeaders.cpp.o
[ 52%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/sideEffects.cpp.o
[ 52%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/simplify.cpp.o
[ 52%] Building CXX object midend/CMakeFiles/midend.dir/tableHit.cpp.o
[ 53%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/simplifyDefUse.cpp.o
[ 53%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/simplifyParsers.cpp.o
[ 54%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/specialize.cpp.o
[ 55%] Building CXX object midend/CMakeFiles/midend.dir/validateProperties.cpp.o
[ 55%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/strengthReduction.cpp.o
[ 55%] Linking CXX static library libmidend.a
[ 56%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/symbol_table.cpp.o
[ 56%] Built target midend
[ 56%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/tableApply.cpp.o
[ 57%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/tableKeyNames.cpp.o
[ 57%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/toP4/toP4.cpp.o
[ 57%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/typeChecking/bindVariables.cpp.o
[ 58%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/typeChecking/syntacticEquivalence.cpp.o
[ 58%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/typeChecking/typeChecker.cpp.o
[ 59%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/typeChecking/typeConstraints.cpp.o
[ 59%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/typeChecking/typeSubstitution.cpp.o
[ 60%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/typeChecking/typeSubstitutionVisitor.cpp.o
[ 60%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/typeChecking/typeUnification.cpp.o
[ 61%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/typeMap.cpp.o
[ 61%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/uniqueNames.cpp.o
[ 61%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/unusedDeclarations.cpp.o
[ 62%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/uselessCasts.cpp.o
[ 62%] Building CXX object frontends/CMakeFiles/frontend.dir/p4/validateParsedProgram.cpp.o
[ 63%] Building CXX object frontends/CMakeFiles/frontend.dir/p4-14/typecheck.cpp.o
[ 63%] Building CXX object frontends/CMakeFiles/frontend.dir/p4-14/header_type.cpp.o
[ 64%] Building CXX object frontends/CMakeFiles/frontend.dir/parsers/p4/p4lexer.cc.o
[ 64%] Building CXX object frontends/CMakeFiles/frontend.dir/parsers/p4/p4parser.cpp.o
[ 65%] Building CXX object frontends/CMakeFiles/frontend.dir/parsers/v1/v1lexer.cc.o
[ 65%] Building CXX object frontends/CMakeFiles/frontend.dir/parsers/v1/v1parser.cpp.o
[ 65%] Building CXX object frontends/CMakeFiles/frontend.dir/__/ir/ir-generated.cpp.o
[ 67%] Linking CXX static library libfrontend.a
[ 67%] Built target frontend
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cc10512** [comment]
Have you updated your submodules? `git submodule update --init --recursive`.
It looks that you have not cloned the PI repo as a submodule.

**Comment by cc10512** [comment]
All built objects are in the p4c build directory, so you do not need anything else additional.
