### ISSUE TITLE
Compiler bug: no definitions

### ISSUE THREAD

**Issue by o-ran** [p4lang/p4c#1452]
Frontend fails with
```
Compiler Bug: arg: no definitions
```
on the following P4 program:
```
control c() {
    bit<32> x;

    action a(inout bit<32> arg) {
        arg = 1;
        return;  // <-----
    }
    table t {
        actions = { a(x); }
        default_action = a(x);
    }
    apply {
        t.apply();
    }
}

control proto();
package top(proto p);

top(c()) main;
```
Compilation:
```
p4test test.p4
```
The problem is in `def_use.cpp` and triggered by the `ReturnStatement` in the action `a`.
`ComputeWriteSet` resets the current definitions every time it finds a `ReturnStatement`:
```
bool ComputeWriteSet::preorder(const IR::ReturnStatement* statement) {
    ...
    return setDefinitions(new Definitions());
}
```
Those empty definitions are then associated with the `BlockStatement` of the action body:
```
bool ComputeWriteSet::preorder(const IR::BlockStatement* statement) {
    ...
    return setDefinitions(currentDefinitions);
}
```
The whole action body now has no definitions associated with it, which makes the further logic in `simplifyDefUse.cpp` unable to locate a definition for `arg`.

**Comment by mbudiu-vmw** [comment]
I am not sure I was thinking that return statements are allowed in actions.
But especially if we will allow conditional execution in actions this may be useful.

**Comment by o-ran** [comment]
Thanks for your attention to this, Mihai!
Yes, `return` in actions makes more sense when it is conditional. I was able to find a couple of such examples in `testdata/p4_16_samples`: `issue512.p4` and `issue420.p4`. They should not trigger this problem however as `return` there is owned by an `IfStatement` and not by an action body's `BlockStatement`.
