### ISSUE TITLE
All ebpf-kernel/testdata/p4_16_samples/*.p4 tests failed

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#1459]
About few months back, before the EBPF backend was reorganized, p4c did not have a dependency on the llvm compiler nor did "make check|recheck" in p4c required sudo priviledge to run.   Both these issues were seen today when using a p4c from today.  More details below.

All ebpf-kernel/testdata/p4_16_samples/*.p4 tests failed.  Debugging the failure, I had to do two things which are not mentioned in the README.md file.  It would be good to update the README.md file.
 
1.	I had to install llvm using “sudo apt-get install llvm”. 
2.	Still “make recheck” failed.  Using “sudo make recheck” worked.  So, now one has to use sudo with “make check “or “make recheck”.

Fix:
----
1. Please add "llvm" to "sudo apt-get install" line in README.md.
2. Change this line in README.md : from "make -j4 check" to  "sudo make -j4 check"

For long-term, find out why ebpf-kernel tests need sudo privilege and change software to not require sudo.

**Comment by mbudiu-vmw** [comment]
Loading ebpf programs into the kernel requires su privileges, so we cannot do it without it.
We should find a way so that you need to type your password only when running these particular tests, and not for all tests.

**Comment by mbudiu-vmw** [comment]
The dependences for the ebpf backend are described in the README in that back-end folder.
We can duplicate this in the main readme, though.

**Comment by hesingh** [comment]
I have pulled a branch to commit the changes to main README.md.  See the changes committed to the branch.  I can use a new Pull of p4c to send out the code review.

https://github.com/hesingh/p4c/commit/dc13f68b59cd40b8ffba4a10269e5033332c2ca8

**Comment by mbudiu-vmw** [comment]
If you don't submit a PR I don't know how to comment.
I don't think we should run the tests with sudo. 
I would rather try to not run the ebpf kernel tests by default; if you want those you have to type a separate command-line.

Also, please note that the documentation is modular, so in theory the ebpf back-end-related documentation should be in the README in that folder, although no one can find it there.

**Comment by hesingh** [comment]
Right now, the global "make check" is running the ebpf-kernel tests and fails on ebpf-kernel.  This is why sudo was required.

**Comment by ChrisDodd** [comment]
It's desirable not to run the entire test suite as root, so I think it would be ok to put a `sudo` into the test script, though that will then stop and prompt for a password if you're not running as root (unless you configure sudo to not require passwords).  Another possibility is to build a setuid-root shim to handle the part of the test that requires root privs -- then put the sudo in the CMakeLists.txt as a custom command.

Using sudo works with the Travis jobs because they run as root, in which case the sudo becomes a noop (no stop for prompt).

**Comment by hesingh** [comment]
@ChrisDodd Agree. 
@mbudiu-vmw I agree that we should not run ebpf-kernel, by default, with 'make check'.  Makes sense to run another command to run ebpf-kernel tests.  Travis can also do the same.

**Comment by hesingh** [comment]
I downloaded latest code after the fix, but am not sure if tests are skipped.  See my test log below from 'make check' invocation.  thanks.

99% tests passed, 14 tests failed out of 1136

Label Time Summary:
XFAIL          =  19.08 sec*proc (13 tests)
bmv2           = 1204.13 sec*proc (311 tests)
cpplint        =  24.45 sec*proc (1 test)
ebpf           =  43.39 sec*proc (13 tests)
ebpf-bcc       =  13.24 sec*proc (13 tests)
ebpf-kernel    =  26.81 sec*proc (13 tests)
gtest          =   8.28 sec*proc (1 test)
p14_to_16      = 612.21 sec*proc (195 tests)
p4             = 480.67 sec*proc (589 tests)

Total Test time (real) = 1237.00 sec

The following tests FAILED:
	285 - bmv2/testdata/p4_16_samples/parser_error-bmv2.p4 (Failed)
	313 - ebpf-kernel/testdata/p4_16_samples/action_call_ebpf.p4 (Failed)
	314 - ebpf-kernel/testdata/p4_16_samples/action_call_table_ebpf.p4 (Failed)
	315 - ebpf-kernel/testdata/p4_16_samples/bool_ebpf.p4 (Failed)
	316 - ebpf-kernel/testdata/p4_16_samples/count_ebpf.p4 (Failed)
	317 - ebpf-kernel/testdata/p4_16_samples/hit_ebpf.p4 (Failed)
	318 - ebpf-kernel/testdata/p4_16_samples/init_ebpf.p4 (Failed)
	319 - ebpf-kernel/testdata/p4_16_samples/issue870_ebpf.p4 (Failed)
	320 - ebpf-kernel/testdata/p4_16_samples/key-issue-1020_ebpf.p4 (Failed)
	321 - ebpf-kernel/testdata/p4_16_samples/key_ebpf.p4 (Failed)
	322 - ebpf-kernel/testdata/p4_16_samples/switch_ebpf.p4 (Failed)
	323 - ebpf-kernel/testdata/p4_16_samples/test_ebpf.p4 (Failed)
	324 - ebpf-kernel/testdata/p4_16_samples/two_ebpf.p4 (Failed)
	325 - ebpf-kernel/testdata/p4_16_samples/valid_ebpf.p4 (Failed)
Errors while running CTest
CMakeFiles/check-all.dir/build.make:57: recipe for target 'CMakeFiles/check-all' failed
make[3]: *** [CMakeFiles/check-all] Error 8
CMakeFiles/Makefile2:616: recipe for target 'CMakeFiles/check-all.dir/all' failed
make[2]: *** [CMakeFiles/check-all.dir/all] Error 2
CMakeFiles/Makefile2:138: recipe for target 'CMakeFiles/check.dir/rule' failed
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
Makefile:201: recipe for target 'check' failed
make: *** [check] Error 2

**Comment by mbudiu-vmw** [comment]
Did you do a `cmake ..` before running?
I have changed some makefiles.

**Comment by hesingh** [comment]
I pulled a new workspace, and did invoke cmake .., then invoked 'make -j3", after which I ran 'make check' and saw the failures.

**Comment by mbudiu-vmw** [comment]
Can you please run a test by hand and post the output?
`ebpf-kernel/testdata/p4_16_samples/valid_ebpf.p4`
My machine does not have a new enough kernel...

**Comment by hesingh** [comment]
hemant@ubuntu:/tmp/p4c/build/ebpf-kernel/testdata/p4_16_samples$ **./valid_ebpf.p4.test -v**
Check for  /tmp/p4c/testdata/p4_16_samples/valid_ebpf.stf
Writing temporary files into  /tmp/p4c/build/tmpNYfsBs
Loading target  targets.kernel_target
Writing make -f runtime.mk -C /tmp/p4c/backends/ebpf/runtime TARGET=kernel /tmp/p4c/build/tmpNYfsBs/test.c BPFOBJ=/tmp/p4c/build/tmpNYfsBs/test.c P4FILE=/tmp/p4c/testdata/p4_16_samples/valid_ebpf.p4 P4C=/tmp/p4c/build/p4c-ebpf
Executing make -f runtime.mk -C /tmp/p4c/backends/ebpf/runtime TARGET=kernel /tmp/p4c/build/tmpNYfsBs/test.c BPFOBJ=/tmp/p4c/build/tmpNYfsBs/test.c P4FILE=/tmp/p4c/testdata/p4_16_samples/valid_ebpf.p4 P4C=/tmp/p4c/build/p4c-ebpf

########### PROCESS OUTPUT BEGIN:
make: Entering directory '/tmp/p4c/backends/ebpf/runtime'
/tmp/p4c/build/p4c-ebpf --Werror -I./p4include --target kernel -o /tmp/p4c/build/tmpNYfsBs/test.c /tmp/p4c/testdata/p4_16_samples/valid_ebpf.p4 
make: Leaving directory '/tmp/p4c/backends/ebpf/runtime'
########### PROCESS OUTPUT END

Generating LALR tables
WARNING: 8 shift/reduce conflicts
Writing make -f kernel.mk -C /tmp/p4c/backends/ebpf/runtime /tmp/p4c/build/tmpNYfsBs/test.o BPFOBJ=/tmp/p4c/build/tmpNYfsBs/test.o INCLUDES+=-I/tmp/p4c/testdata/p4_16_samples
Executing make -f kernel.mk -C /tmp/p4c/backends/ebpf/runtime /tmp/p4c/build/tmpNYfsBs/test.o BPFOBJ=/tmp/p4c/build/tmpNYfsBs/test.o INCLUDES+=-I/tmp/p4c/testdata/p4_16_samples

########### PROCESS OUTPUT BEGIN:
make: Entering directory '/tmp/p4c/backends/ebpf/runtime'
clang -O2 -g -D__KERNEL__ -D__ASM_SYSREG_H -Wno-unused-value  -Wno-pointer-sign -Wno-compare-distinct-pointer-types -Wno-gnu-variable-sized-type-not-at-end -Wno-address-of-packed-member -Wno-tautological-compare -Wno-unknown-warning-option -Wnoparentheses-equality -I/tmp/p4c/testdata/p4_16_samples -I/tmp/p4c/backends/ebpf/runtime/ -emit-llvm -c /tmp/p4c/build/tmpNYfsBs/test.c -o /tmp/p4c/build/tmpNYfsBs/test.bc
llc -march=bpf -mcpu=probe -filetype=obj /tmp/p4c/build/tmpNYfsBs/test.bc -o /tmp/p4c/build/tmpNYfsBs/test.o
make: Leaving directory '/tmp/p4c/backends/ebpf/runtime'
########### PROCESS OUTPUT END

*** This test requires root privileges! Failing...
hemant@ubuntu:/tmp/p4c/build/ebpf-kernel/testdata/p4_16_samples$

**Comment by mbudiu-vmw** [comment]
This is strange: the error message you are showing should no longer be in the code:
`*** This test requires root privileges! Failing...`
The message should be:
`This test requires root privileges; skipping execution.`
Can you track down where this message is coming from?

**Comment by hesingh** [comment]
Sorry, I was using a different workspace for the test.  I created a new workspace of latest p4c and do see the "skipping execution." message when I run the test manually with sudo.  Without sudo, the test has different set of failures I sent to you via email.

**Comment by mbudiu-vmw** [comment]
If you still have failures we should not yet close this.

**Comment by hesingh** [comment]
I saw the "fixed" label and closed it.  Yes, there is one catch in that, only if I use "sudo" to run a ebpf-kernel manually, the testing passes.  However, without sudo, the same test fails.  A user is expected to run 'make check' without sudo and then ebfp-kernel test will fail.  I will reopen - thanks.

**Comment by mbudiu-vmw** [comment]
I hope that this has now been fixed.

**Comment by hesingh** [comment]
Yes, thanks.

**Comment by HusterHaoYoung** [comment]
when I use sudo make -j4 check ,I still have these error.How can I to fix them.

      99% tests passed, 13 tests failed out of 1156

Label Time Summary:
XFAIL          =  17.24 sec*proc (13 tests)
bmv2           = 1293.36 sec*proc (317 tests)
cpplint        =  28.87 sec*proc (1 test)
ebpf           =  24.70 sec*proc (13 tests)
ebpf-bcc       =   7.22 sec*proc (13 tests)
ebpf-kernel    =  11.94 sec*proc (13 tests)
gtest          =   9.92 sec*proc (1 test)
p14_to_16      = 750.10 sec*proc (197 tests)
p4             = 561.08 sec*proc (601 tests)

Total Test time (real) = 701.02 sec

The following tests FAILED:
	319 - ebpf-kernel/testdata/p4_16_samples/action_call_ebpf.p4 (Failed)
	320 - ebpf-kernel/testdata/p4_16_samples/action_call_table_ebpf.p4 (Failed)
	321 - ebpf-kernel/testdata/p4_16_samples/bool_ebpf.p4 (Failed)
	322 - ebpf-kernel/testdata/p4_16_samples/count_ebpf.p4 (Failed)
	323 - ebpf-kernel/testdata/p4_16_samples/hit_ebpf.p4 (Failed)
	324 - ebpf-kernel/testdata/p4_16_samples/init_ebpf.p4 (Failed)
	325 - ebpf-kernel/testdata/p4_16_samples/issue870_ebpf.p4 (Failed)
	326 - ebpf-kernel/testdata/p4_16_samples/key-issue-1020_ebpf.p4 (Failed)
	327 - ebpf-kernel/testdata/p4_16_samples/key_ebpf.p4 (Failed)
	328 - ebpf-kernel/testdata/p4_16_samples/switch_ebpf.p4 (Failed)
	329 - ebpf-kernel/testdata/p4_16_samples/test_ebpf.p4 (Failed)
	330 - ebpf-kernel/testdata/p4_16_samples/two_ebpf.p4 (Failed)
	331 - ebpf-kernel/testdata/p4_16_samples/valid_ebpf.p4 (Failed)
Errors while running CTest
CMakeFiles/check-all.dir/build.make:57: recipe for target 'CMakeFiles/check-all' failed
make[3]: *** [CMakeFiles/check-all] Error 8
CMakeFiles/Makefile2:616: recipe for target 'CMakeFiles/check-all.dir/all' failed
make[2]: *** [CMakeFiles/check-all.dir/all] Error 2
CMakeFiles/Makefile2:138: recipe for target 'CMakeFiles/check.dir/rule' failed
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
Makefile:201: recipe for target 'check' failed
make: *** [check] Error 2

**Comment by mbudiu-vmw** [comment]
Make sure you have installed all dependencies required by the ebpf tests. These are listed in the backends/ebpf/README.md file.
If your kernel does not support these tests normally when you run cmake some of them should be disabled.

Mihai

**Comment by HusterHaoYoung** [comment]
Thanks you,It works for me!
