### ISSUE TITLE
Proposed changes to p4runtime generation for values with custom P4_16 `type`

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1461]
@antoninbas @mbudiu-vmw Looking for your comments here to see if this issue is suggesting changes that you expect.

The attached portid.zip file contains these files:
[portid.zip](https://github.com/p4lang/p4c/files/2337306/portid.zip)

+ portid-type.p4
+ portid-type.p4rt.json
+ portid-typedef.p4
+ portid-typedef.p4rt.json

portid-typedef.p4 and portid-type.p4 are nearly identical P4_16
programs for arch v1model.

portid-typedef.p4 uses "typedef bit<9> PortId_t" and values with type
PortId_t in a couple of places.

portid-type.p4 replaces the "typdef" with "type".

I ran the command below to generate the file portid-typedef.p4rt.json:

    p4c --p4runtime-format json --p4runtime-file portid-typedef.p4rt.json portid-typedef.p4

There are two places where values declared with the typedef name
PortId_t occur in the P4runtime file:

+ match field "meta.inport" in table "ingress.ipv4_da_pm"
+ parameter "port" of action "ingress.set_output_port"

Because the P4 compiler treats typedef as just an alias for the
underlying type, here `bit<9>`, the P4runtime file generated is the
same as if there were no typedef declaration for PortId_t, and
everything with that type were declared as `bit<9>` instead.  This is
expected.

Below is the part of file "portid-typedef.p4rt.json" for match field
"meta.inport" of table "ingress.ipv4_da_lpm":

    {
     "id": 1,
     "name": "meta.inport",
     "bitwidth": 9,
     "matchType": "EXACT"
    },

Below is the part of file "portid-typedef.p4rt.json" for action
parameter "port" of action "ingress.set_output_port":

    {
     "id": 1,
     "name": "port",
     "bitwidth": 9
    }

With the latest p4c as of 2018-Aug-30 trying the command below gives
an error.

    p4c --p4runtime-format json --p4runtime-file portid-type.p4rt.json portid-type.p4

That error is:

    portid-type.p4(85): error: Action parameter port has a type which is not bit<> or int<> or bool
        action set_output_port(PortId_t port) {
                                        ^^^^

This error is generated in method `addAction` of class
`P4RuntimeAnalyzer` in source file
`p4c/control-plane/p4RuntimeSerializer.cpp`.  For each action
parameter there is code that checks whether its type is either
`IR::Type_Bits` or `IR::Type_Boolean`, and gives the error message
above if it is neither of those.

I believe what we want to happen instead, is that if the type is
neither of those, the code should check if it is a type defined via
`type` in the P4 source code (I do not yet know how to check that in
the IR classes).

If it is, then use one of these approaches:

(a) Look up the source code type name, e.g. `PortId_t`, in a table of
PSA-specific types that have potentially different control plane and
data plane bit widths (there are only 7 defined so far, listed in the
PSA spec).  If it is one of those 7 type names, ignore the bit width
in the P4 source code, and use the bit width from the following table:

    PortId_t 32
    MulticastGroup_t 32
    CloneSessionId_t 16
    ClassOfService_t 8
    PacketLength_t 16
    EgressInstance_t 16
    Timestamp_t 64

(b) Look for an annotation on the type with a name like
`p4runtime_controller_width` whose value should be an integer, and the
bit width to put into the p4runtime file.

Regardless of whether approach (a) or (b) is used, I think the
P4runtime file should also contain the original P4 `type` name
associated with the value, because type names could in the future
carry more purposes than merely different bit widths between
controller and data plane.  For example, the user might want to use
`type bit<32> IPv4Address_t` in their source code, and have this type
name annotating occurrences of values with that type as action
parameters, table match fields, etc.  In that case, the controller and
data plane widths would both be 32 bits.  The type name
`IPv4Address_t` could be used by the P4Runtime client and/or server
for customizing debug output for values with that type, e.g. to show
them in dotted decimal format instead of hexadecimal.

Below are modified versions of the P4Runtime JSON file excerpts above,
that I propose should appear after p4c is modified to do so.

Below is the part of the proposed file "portid-type.p4rt.json" for
match field "meta.inport" of table "ingress.ipv4_da_lpm":

    {
     "id": 1,
     "name": "meta.inport",
     "type": "PortId_t",
     "bitwidth": 32,
     "matchType": "EXACT"
    },

Below is the part of proposed file "portid-type.p4rt.json" for action
parameter "port" of action "ingress.set_output_port":

    {
     "id": 1,
     "name": "port",
     "type": "PortId_t",
     "bitwidth": 32
    }

**Comment by mbudiu-vmw** [comment]
This sounds reasonable.
If the width of a type depends on the controller and not on the P4 program then it should not be set in the P4 program, but by some other external mechanism. If a P4 program is tied to a specific controller then we could have the width an annotation on the `type` in the architecture description file.

**Comment by mbudiu-vmw** [comment]
Yes, I saw that. However, this lookup is somehow controller-dependent. You need to pass enough information to p4c to know how to represents these datatypes for whatever controller you are targeting. Perhaps we need an additional controller-description file?

**Comment by jafingerhut** [comment]
There are definitely implementation choices to be made for where this architecture-dependent maybe-controller-dependent data comes from.  Nobody wants it in their back yard :)

I can definitely see wanting to keep it out of the compiler source code.  A data file included with p4c that is read by p4c during p4runtime generation would be reasonable,  where the data file included has the tbitwidths that p4runtime folks are expecting initially, e.g. 32 for PortId_t, etc.

If someone wanted the flexibility in the future, p4c might have a command line option to specify a different file.  I don't see a strong reason to implement such an option until someone actually has a need for it.

**Comment by jafingerhut** [comment]
A small amendment to my original proposal for how to modify this code: https://github.com/p4lang/p4c/blob/32fba3dc8057a2e6d907c63bb0b08c4bb73a32ab/control-plane/p4RuntimeSerializer.cpp#L738-L747

It roughly follows these steps:
(1) get the type of the data value (in this case an action parameter, but the same seems like it ought to apply for anything else represented in a p4runtime file, e.g. table search keys, digest fields, etc.)
(2) if it is not one of the supported types, issue an error
(3) handle each of the supported cases by adding appropriate field values to be put into the p4runtime file.

I think we should add a new step 1.5 after 1, before 2:

(1.5) check if the value has a type defined via a `type` declaration.  If no, continue on as before.  If yes, add that type _name_ as an attribute about the data value written to the p4runtime file, e.g. as the value of an attribute called "type".  Then forget the custom type and replace it with the "underlying type", proceeding on to step (2) with that underlying type.

Most commonly that "underlying type" will be determined in a single "step" because the `type` definition in the P4 source code will often be `type bit<9> PortId_t` where `bit<9>` is one of the primitive types of P4.  It seems reasonable to handle following a chain of multiple such `type` definition, if necessary, e.g. because the type `foo` is declared as `type PortId_t foo`, and `PortId_t` is declared as in the previous sentence.

If/when the P4 compiler supports nested structs/etc. for types in the p4runtime file, this technique would be done similarly, recursing into the fields of the nested structs, with custom type names perhaps appearing at arbitrary places in the data type.

**Comment by jafingerhut** [comment]
@antoninbas and I had a brief conversation on this issue today.  Recording my notes from that conversation:

Regarding config file vs. P4 source code annotations for specifying the 'control plane API type' to replace a PSA type with, we came up with this proposal:

Always include the P4 type names in the P4Runtime Info file, if the value is defined via a named 'type' in the P4 source code.  Use "type_name" as the key instead of the "type" string that I proposed in an earlier comment.

if (a "P4 type to P4Runtime API type mapping" config file is specified on the command line) {
    look up the P4 type name in that mapping, and if an exactly matching entry exists, use the type listed there as the control plane type.  Initially specifying simply a bit width and assuming `bit<W>` for some bit width W should be enough, but perhaps some day we would want such a mapping to be more flexible.
} else if (P4 source code 'type' definition has the annotation @p4runtime_translation on it) {
    use the bit width specified in the annotation
    Example annotation: @p4runtime_translation("https://p4.org/psa_v1/PortId_t", 32) type bit<9> PortId_t;
} else {
    use the underlying type specified in the P4 source code, e.g. if the type definition is 'type bit<9> Foo_t', use bit width 9.  This enables P4 developers to notify type names to the control plane API, even if they do _not_ want a target-dependent data plane width for values of that type, e.g. 'type bit<32> IPv4Address_t;'
}

Having the config file option override annotations in the source code lets the source code specify the default bit widths we expect P4Runtime to use, but yet still allow someone with custom requirements for the control plane API sizes of these types to override the source code, without having to edit perhaps one or many places where those annotations occur in the P4 source code.

**Comment by mbudiu-vmw** [comment]
This looks like a very good proposal. This looks like it belongs to the control-plane API spec.
The other specs should cross-link to that description.

**Comment by jafingerhut** [comment]
Glad you like it.

It is not time-urgent, but if I create a proposed PR for p4c to make these changes, it would help if you or someone more familiar with the p4c IR and its API could show what function calls to make for these purposes:

+ determine whether an action parameter, table key field, digest call parameter, etc. has a type that was defined using the P4 `type` keyword, and if so, what the name of that type is.  Hopefully that code might be the same regardless of which of those uses of the value it is.

+ If someone actually did something like `type bit<9> T1;   type T1 T2;   type T2 T3;    T3 foo;` in a P4 program, does the p4c IR record that `foo` is type `T3`, or something else?  If `T3`, is there some other API call to make to determine if type `T3` is _also_ defined via a `type` declaration, and can 'follow the chain' of `type` declarations to end up at `T1` with type `bit<9>`?  An example of what that code would look like would also be helpful.

+ Similarly, a snippet of code to determine whether a `type` definition had any annotations on them, e.g. in particular an annotation named `p4runtime_translation`.

**Comment by antoninbas** [comment]
See https://github.com/p4lang/p4runtime/pull/50 for corresponding P4Runtime PR

**Comment by mbudiu-vmw** [comment]
All of these should be very simple in the compiler. The hard part is generating the proper structure for P4Runtime. If you find that something is missing in the IR we should fix the IR.

**Comment by jafingerhut** [comment]
A PR for the PSA specification is here that updates it to match things discussed here, and I believe also for the latest plans in the P4Runtime API spec: https://github.com/p4lang/p4-spec/pull/678

I added a footnote in those changes mentioning the idea above of p4c having an option to specify additional types to enable for numerical translation, but there is no detailed specification of how that will work there, only a mention.

Mihai, the hard part you mention for generating the proper structure in P4Runtime is I think fairly precisely specified in the latest p4runtime spec in https://github.com/p4lang/p4runtime which Antonin added in the last month or so.  I say this not because I expect you to go read that an implement this, just so you know there are details worked out there.

**Comment by mbudiu-vmw** [comment]
What is the status of this issue?

**Comment by mbudiu-vmw** [comment]
I will assume that this issue is fixed and closed it; please reopen if I am wrong.
