### ISSUE TITLE
"errors" key in BMv2 JSON empty

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1462]
With this commit of p4c: https://github.com/p4lang/p4c/commit/8319d3213e5e28abd76015d68e5586993ae5fb99
the "errors" key of a compiled BMv2 JSON file contains a mapping of P4_16 error names to numerical values selected by the compiler.

With this commit a few days later: https://github.com/p4lang/p4c/commit/9c76c9fd5e4880b6b3f5e78a9588e63ca9288e8a
the "errors" key of a compiled BMv2 JSON file is the empty list `[]`.

I suspect this may have started with this big set of changes: https://github.com/p4lang/p4c/commit/5998e0d6170db9f1fd302df5ea96e52f6d425e1c

**Comment by hesingh** [comment]
Wonder if commit of p4c: 8319d32 added a test case?  Then, if any subsequent commit breaks code or changes code behavior, one would catch it.  I would use "patch -p0|p1 -R < 5998e0d" to back out the changes and see if the issue is fixed.

**Comment by mbudiu-vmw** [comment]
#1456 should have a test that exercises this case. I have recently merged a PR which should have fixed the issue you describe: #1448

**Comment by mbudiu-vmw** [comment]
Perhaps you can approve #1456 too so we can merge it.

**Comment by jafingerhut** [comment]
Looks like #1456 was approved by someone else and merged, so good to go there.

I updated to latest p4c as of now on 2018-Aug-31, and the "errors" key in the BMv2 JSON file has expected contents again.  I realize that it may have been a recent commit other than #1456 that caused this, but I'm not too worried right now about exactly which commit fixed things.

Thanks.  Closing this issue.
