### ISSUE TITLE
NameMap should support IDs as keys

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#1474]
Using just cstrings as keys prevents us from displaying good error messages related to the identifiers that are used as keys.

**Comment by ChrisDodd** [comment]
You can use any type as the `name` field in the NameMap that supports `==` with cstrings.  So in particular, using an IR::ID should work just fine.

**Comment by mbudiu-vmw** [comment]
But how can I declare something like this: `NameMap<ID, Expression>`?
I do want to know that all keys are IDs.
The template supports only one argument.
