### ISSUE TITLE
cmake .. fails

### ISSUE THREAD

**Issue by gareging** [p4lang/p4c#1477]
Hello, 

I'm following the commands from this script (https://raw.githubusercontent.com/p4lang/tutorials/master/vm/user-bootstrap.sh) on a VM with Ubuntu 16.04.5 LTS.

Unfortunately, it fails on **cmake ..** at p4c installation stage. Can I ask for the assistance to solve this issue? I already tried re-installing libboost-dev-all but it didn't help.

cmake ..
CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.60.0

  Boost include path: /home/p4/Documents/boost_1_60_0

  Could not find the following Boost libraries:

          boost_iostreams

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:77 (find_package)

-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Program 'psa_switch_CLI' (https://github.com/p4lang/behavioral-model.git) not found;
Searched .
Will not run PSA BMv2 tests. (missing:  PSA_SWITCH PSA_SWITCH_CLI) 
-- Using the GNU gold linker.
-- Available extensions 
-- Added 307 tests to 'bmv2' (8 xfails)
CMake Warning at backends/bmv2/CMakeLists.txt:172 (MESSAGE):
  BMv2 PSA switch is not available, not adding PSA BMv2 tests

CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:178 (include):
  include could not find load file:

    /usr/share/llvm/cmake/LLVMExports.cmake
Call Stack (most recent call first):
  backends/ebpf/CMakeLists.txt:108 (find_package)

CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:181 (include):
  include could not find load file:

    /usr/share/llvm/cmake/LLVM-Config.cmake
Call Stack (most recent call first):
  backends/ebpf/CMakeLists.txt:108 (find_package)

-- Found LLVM 3.8.0
-- Added 13 tests to 'ebpf-kernel' (0 xfails)
-- Added 13 tests to 'ebpf-bcc' (0 xfails)
-- Added 13 tests to 'ebpf' (0 xfails)
-- Added 154 tests to 'p4' (0 xfails)
-- Added 440 tests to 'p4' (1 xfails)
-- Added 195 tests to 'p14_to_16' (0 xfails)
-- CTest parallel: -j 1
-- Configuring incomplete, errors occurred!
See also "/home/p4/p4c/build/CMakeFiles/CMakeOutput.log".
See also "/home/p4/p4c/build/CMakeFiles/CMakeError.log".

**Comment by jnfoster** [comment]
These scripts are designed to work with specific, pinned versions of Bmv2, P4c, etc.

It appears your environment is different. 

In particular, I don't think you've executed the commands in root-bootstrap.sh?

**Comment by gareging** [comment]
I get the same issue even when I follow the main instruction for README.md.
I have just executed root-bootstrap.sh, but it didn't help.

**Comment by jnfoster** [comment]
What is the Git hash of the version of p4c and bmv2 on your VM? (`git log -1`)

**Comment by gareging** [comment]
48a57a6ae4f96961b74bd13f6bdeac5add7bb815

**Comment by gareging** [comment]
For p4c: 48a57a6ae4f96961b74bd13f6bdeac5add7bb815
For bmv2: 7e25eeb19d01eee1a8e982dc7ee90ee438c10a05

**Comment by gareging** [comment]
I'm sorry, the log above was related to the latest version (5ae30eed11cd6ae2fcd54f01190b9e198f429420). 

Here is for 48a57a6ae4f96961b74bd13f6bdeac5add7bb815:

CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.60.0

  Boost include path: /home/p4/boost_1_60_0

  Could not find the following Boost libraries:

          boost_iostreams

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:77 (find_package)


-- Could NOT find PY_tenjin (missing:  PY_TENJIN) 
-- Using the GNU gold linker.
-- Available extensions 
-- Added 286 tests to 'bmv2' (8 xfails)
-- Added 9 tests to 'ebpf' (0 xfails)
-- Added 511 tests to 'p4' (1 xfails)
-- Added 184 tests to 'p14_to_16' (0 xfails)
-- CTest parallel: -j 1
-- Configuring incomplete, errors occurred!
See also "/home/p4/p4c/build/CMakeFiles/CMakeOutput.log".
See also "/home/p4/p4c/build/CMakeFiles/CMakeError.log".

**Comment by jnfoster** [comment]
What happens if you run the relevant command from `root-bootstrap.sh`
`apt-get install \
  libboost-dev \
  libboost-filesystem-dev \
  libboost-iostreams1.58-dev \
  libboost-program-options-dev \
  libboost-system-dev \
  libboost-test-dev \
  libboost-thread-dev
`

**Comment by gareging** [comment]
~/p4c/build$ sudo apt-get install libboost-dev libboost-filesystem-dev libboost-iostreams1.58-dev libboost-program-options-dev libboost-system-dev libboost-test-dev libboost-thread-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-dev is already the newest version (1.58.0.1ubuntu1).
libboost-program-options-dev is already the newest version (1.58.0.1ubuntu1).
libboost-filesystem-dev is already the newest version (1.58.0.1ubuntu1).
libboost-system-dev is already the newest version (1.58.0.1ubuntu1).
libboost-test-dev is already the newest version (1.58.0.1ubuntu1).
libboost-thread-dev is already the newest version (1.58.0.1ubuntu1).
libboost-iostreams1.58-dev is already the newest version (1.58.0+dfsg-5ubuntu3.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by cc10512** [comment]
It seems you have both boost-1.58 and boost-1.60. The apt-get check is for 1.58, while your cmake command detects 1.60, which seems to be missing libboost-iostreams. I suggest you keep 1.58 and remove 1.60 from your system.
