### ISSUE TITLE
Check value of size property for keyless tables?

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#1478]
Would it be a good idea to check the value of the `size` table property for keyless tables in a midend pass? If the `size` is greater than 0, I would suggest printing a warning and replacing the program-provided value with 0 in the IR.
```
table {
  key = { }
  actions = { a; }
  size = 2;
}
```
We actually ran into a situation recently where someone wrote a similar program, so it may be worth it to do this check in the compiler and I would imagine it would benefit most backends (thus my suggestion to make it a midend pass).

**Comment by hesingh** [comment]
size is an optional property of a table.  If a table is keyless, a backend should be robust enough to ignore size.  I don't have a strong preference.  It's fine to add such a check to a midend pass, but we should make sure the midend pass is included by all backends.

**Comment by mbudiu-vmw** [comment]
There are other interesting cases to consider, like specifying the size and specifying the const table intializers...
