### ISSUE TITLE
Constant propagation conflicts with P4_16 + v1model + resubmit/recirculate 'field list' parameters?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1479]
I know P4_14 has field lists, but P4_16 doesn't (at least not as of submitting this issue).

I know that I can compile a P4_16 + v1model program using p4c with `--target bmv2` and `--arch v1model`, with a call to `resubmit` like `resubmit({standard_metadata.ingress_port});`, and as long as the compiler doesn't simplify that expression to a constant, then in the BMv2 JSON file output by the BMv2 back end, there is a field lists created inside the `"field_lists"` key that has that list of field names, and the `resubmit` primitive action has the `"id"` value of the field_list as its parameter.  All good.

I have seen a case where if there is one field in the list between the curly braces, and shortly before the call to `resubmit` I assign a constant value to that metadata field, the BMv2 JSON file has that constant in the field list, not the field name.  In such a case, simple_switch has no field name information available for that field, to know that it should preserve that field value.  I suspect this is due to how the compiler propagates constant values interacting badly with the 'field list'.

I can create a small P4_16 test program and attach it to this issue at some point.

I don't need a fix for this any time soon.  I just wanted to record this issue while it was fresh in my mind.  I know that when P4_16 + PSA architecture implementation is available, this should not be an issue for the PSA architecture, at least not for the existing PSA operations I can think of, because PSA does not use these 'field lists as references' there.  It can use 'field lists as values', but in that case constant propagation is correct behavior, I believe.

**Comment by mbudiu-vmw** [comment]
If you use resubmit with an explicit struct type argument it will be used to generate the field names.

**Comment by jafingerhut** [comment]
Thanks, good to know.  In some cases it sounds like that might preserve more than one wants, e.g. you can preserve all of standard_metadata that way, or none of it.  Again, all of this hopefully only a temporary annoyance, until we have P4_16+PSA working.

**Comment by jafingerhut** [comment]
It seems to me like the real root of this issue is actually https://github.com/p4lang/p4c/issues/1514

Constant propagation is only conflicting with the way resubmit() is currently implemented in P4_16 + v1model arch, which as described in #1514 is a little bit off from the P4_16 language semantics.  Closing this issue, but leaving that one open.
