### ISSUE TITLE
Create packet-based tests for resubmit, recirc, clone, multicast, unicast, and drop

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1480]
For P4_16 + v1model architecture, perhaps the demo program v1model-special-ops.p4 in this directory would be a good start (the README has some sample table contents and packets): https://github.com/jafingerhut/p4-guide/tree/master/v1model-special-ops

For P4_16 + PSA architecture there should be separate issues created other than this one.  One or more of the PSA example programs in the p4-spec Github repository are probably a better start for that purpose.

**Comment by jnfoster** [comment]
Thanks for doing this Andy! It's a great improvement to V1model documentation.

**Comment by jafingerhut** [comment]
Closing this issue, as the PR https://github.com/p4lang/p4c/pull/1486 has now been merged, adding the test program that exercises resubmit, recirculate, ingress-to-ingress clone, ingress-to-egress clone, and multicast replication, with checking of actual vs. expected output packets.
