### ISSUE TITLE
run"make -j4 check“，error occurs

### ISSUE THREAD

**Issue by panweixu** [p4lang/p4c#1483]
![2018-09-14_085858](https://user-images.githubusercontent.com/40857784/45523571-97218c80-b7fc-11e8-84ba-64a313b0b1d2.png)

**Comment by panweixu** [comment]
> At least 'sudo make -j4 check' should work for you. Other folks who are working on issues with p4c testing may know more.

I use "sudo make check -j4" and the same error occurs.Have you successfully installed p4c?

**Comment by hesingh** [comment]
About two days back, I downloaded latest p4c and could run 'make check' fine.  Let me download right now and get back.

**Comment by hesingh** [comment]
I just downloaded latest p4c and 'make check -j3' is running fine for me.

**Comment by panweixu** [comment]
> I just downloaded latest p4c and 'make check -j3' is running fine for me.

run 'make check -j3' is occuring the same error.

**Comment by hesingh** [comment]
I think the p4c branch which is old by 5-7 days shows the error you reported.  Could you please download a new p4c and see if you see the same error?

**Comment by hesingh** [comment]
I see, when a specific test fails, one gets the error.  I got this error with latest p4c.  See my log below.

The following tests FAILED:
	286 - bmv2/testdata/p4_16_samples/parser_error-bmv2.p4 (Failed)
Errors while running CTest
CMakeFiles/recheck-all.dir/build.make:57: recipe for target 'CMakeFiles/recheck-all' failed
make[3]: *** [CMakeFiles/recheck-all] Error 8
CMakeFiles/Makefile2:680: recipe for target 'CMakeFiles/recheck-all.dir/all' failed
make[2]: *** [CMakeFiles/recheck-all.dir/all] Error 2
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/recheck.dir/rule' failed
make[1]: *** [CMakeFiles/recheck.dir/rule] Error 2
Makefile:188: recipe for target 'recheck' failed
make: *** [recheck] Error 2

**Comment by panweixu** [comment]
> I think the p4c branch which is old by 5-7 days shows the error you reported. Could you please download a new p4c and see if you see the same error?



> I see, when a specific test fails, one gets the error. I got this error with latest p4c. See my log below.
> 
> The following tests FAILED:
> 286 - bmv2/testdata/p4_16_samples/parser_error-bmv2.p4 (Failed)
> Errors while running CTest
> CMakeFiles/recheck-all.dir/build.make:57: recipe for target 'CMakeFiles/recheck-all' failed
> make[3]: *** [CMakeFiles/recheck-all] Error 8
> CMakeFiles/Makefile2:680: recipe for target 'CMakeFiles/recheck-all.dir/all' failed
> make[2]: *** [CMakeFiles/recheck-all.dir/all] Error 2
> CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/recheck.dir/rule' failed
> make[1]: *** [CMakeFiles/recheck.dir/rule] Error 2
> Makefile:188: recipe for target 'recheck' failed
> make: *** [recheck] Error 2
For network reasons, I am still re-downloading the latest p4c. If you can install p4c successfully, I will check it

**Comment by panweixu** [comment]
> I see, when a specific test fails, one gets the error. I got this error with latest p4c. See my log below.
> 
> The following tests FAILED:
> 286 - bmv2/testdata/p4_16_samples/parser_error-bmv2.p4 (Failed)
> Errors while running CTest
> CMakeFiles/recheck-all.dir/build.make:57: recipe for target 'CMakeFiles/recheck-all' failed
> make[3]: *** [CMakeFiles/recheck-all] Error 8
> CMakeFiles/Makefile2:680: recipe for target 'CMakeFiles/recheck-all.dir/all' failed
> make[2]: *** [CMakeFiles/recheck-all.dir/all] Error 2
> CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/recheck.dir/rule' failed
> make[1]: *** [CMakeFiles/recheck.dir/rule] Error 2
> Makefile:188: recipe for target 'recheck' failed
> make: *** [recheck] Error 2

I re-download the latest p4c, run "sudo make -j4 check", the same error still occurs

**Comment by mbudiu-vmw** [comment]
There isn't enough information to diagnose your problem. Can you just run one test and show us the output? 
```
 bmv2/testdata/p4_16_samples/parser_error-bmv2.p4.test -v
```

**Comment by jafingerhut** [comment]
If you are willing to start with a fresh Ubuntu Linux 16.04 installation (whether physical machine or virtual), I have tested that starting with that and doing these 3 commands, then typing in your password one or maybe a couple of times when various commands need superuser privileges, will lead to an installation of behavioral-model and p4c in which `make check` passes all tests for p4c:
```
$ sudo apt install git
$ git clone https://github.com/jafingerhut/p4-guide
$ ./p4-guide/bin/install-p4dev.sh

then if you wish to run tests

$ cd p4c/build
$ make check
```
It is very easy to accidentally miss steps in the README instructions if you follow them by hand.  It might also be that on an Ubuntu machine that has been used for installing other software, some packages may have been installed that could conflict with the ones needed by the P4 build process.  If you are not using Ubuntu Linux at all, then it gets even more challenging to modify the README steps to figure out what is needed.  What OS are you using?

**Comment by panweixu** [comment]
> There isn't enough information to diagnose your problem. Can you just run one test and show us the output?
> 
> ```
>  bmv2/testdata/p4_16_samples/parser_error-bmv2.p4.test -v
> ```

Writing temporary files into  ./tmpF1ki5I
Executing  ./p4c-bm2-ss -o bmv2/testdata/p4_16_samples/parser_error-bmv2.json /home/sdn/tools/p4c/testdata/p4_16_samples/parser_error-bmv2.p4
Exit code  0
Check for  /home/sdn/tools/p4c/testdata/p4_16_samples/parser_error-bmv2.stf
Running model
Running simple_switch --log-file switch.log --log-flush --use-files 0 --thrift-port 9435 --device-id 345 -i 0@pcap0 ../bmv2/testdata/p4_16_samples/parser_error-bmv2.json
Calling target program-options parser
The most recent bmv2 JSON version number supported is 2.12 but this JSON input is tagged with version number 2.18
bad json:
{
   "compiler" : "https://github.com/p4lang/p4c",
   "version" : [ 2, 18 ]
}

Removing ./tmpF1ki5I
*** Test failed

**Comment by panweixu** [comment]
> If you are willing to start with a fresh Ubuntu Linux 16.04 installation (whether physical machine or virtual), I have tested that starting with that and doing these 3 commands, then typing in your password one or maybe a couple of times when various commands need superuser privileges, will lead to an installation of behavioral-model and p4c in which `make check` passes all tests for p4c:
> 
> ```
> $ sudo apt install git
> $ git clone https://github.com/jafingerhut/p4-guide
> $ ./p4-guide/bin/install-p4dev.sh
> 
> then if you wish to run tests
> 
> $ cd p4c/build
> $ make check
> ```
> It is very easy to accidentally miss steps in the README instructions if you follow them by hand. It might also be that on an Ubuntu machine that has been used for installing other software, some packages may have been installed that could conflict with the ones needed by the P4 build process. If you are not using Ubuntu Linux at all, then it gets even more challenging to modify the README steps to figure out what is needed. What OS are you using?

Thank you, I followed the steps to find you, completely passed the test.
100% tests passed, 0 tests failed out of 1129

Label Time Summary:
XFAIL        =  12.25 sec (13 tests)
bmv2         = 1053.07 sec (312 tests)
cpplint      =  31.23 sec (1 test)
ebpf         =  16.07 sec (13 tests)
ebpf-bcc     =   6.15 sec (13 tests)
gtest        =   6.95 sec (1 test)
p14_to_16    = 539.97 sec (195 tests)
p4           = 446.23 sec (594 tests)

Total Test time (real) = 601.16 sec
Built target check-all
Scanning dependencies of target check
Built target check
According to your steps, have I installed p4compiler? How can I check the p4c version? Do I still have to run "sudo make install"? In addition, I want to write a p4 file that adds MPLS header to the data packet. Can you give me some reference materials for me to learn? Thanks

**Comment by panweixu** [comment]
> My best guess is that you have a version of behavioral-model / simple_switch installed from source code that is at least several months old, but are trying to run tests from a recent version of p4c source using it.
> 
> I would recommend installing a recent version of behavioral-model from source, if you are also using recent p4c source code.


How can I check the version of p4c? I run "p4c-bm2-ss --version" to show:
p4c-bm2-ss
Version 0.0.5

Is this command correct?

**Comment by panweixu** [comment]
> This means that you are using an old version of the behavioral simulator. You need to upgrade it.

How can I check the version of p4c? I run "p4c-bm2-ss --version" to show:
p4c-bm2-ss
Version 0.0.5

Is this command correct?

**Comment by panweixu** [comment]
> 安装

![error](https://user-images.githubusercontent.com/40857784/45586096-66884280-b923-11e8-8c0c-0a6e5efecbed.png)
Is this command correct? Why is it wrong?

**Comment by mbudiu-vmw** [comment]
There are two versions of the p4 language. This program is written using the old version, so you have to indicate that:
`p4c-bm2-ss --std p4-14 simple_router.p4`

**Comment by jafingerhut** [comment]
@panweixu wrote:

"According to your steps, have I installed p4compiler? How can I check the p4c version? Do I still have to run "sudo make install"? In addition, I want to write a p4 file that adds MPLS header to the data packet. Can you give me some reference materials for me to learn? Thanks"

If you run the install-p4dev.sh shell script successfully, it installs these things:
+ The library called Thrift, which is a prerequisite for compiling the behavioral-model simple_switch code
+ behavioral-model simple_switch, a software switch that can run P4 programs that you compile using p4c
+ the Google Protobuf library, which is a prerequisite for compiling the p4c compiler
+ the p4c compiler

That script will install simple_switch in /usr/local/bin.  It does not install p4c in /usr/local/bin, but if you want to do that, too, you can do `cd ~/p4c/build` followed by `sudo make install`.  You do not need to do that to run the p4c compiler, but if you do not do that step, you will need to add ~/p4c/build to your shell's command PATH, or type the full path to the executable.

There is a first P4_16 program to learn from with many many comments in it here: https://github.com/jafingerhut/p4-guide/blob/master/demo1/demo1-heavily-commented.p4_16.p4  (it is file demo1/demo1-heavily-commented.p4_16.p4 in the p4-guide Github repository you cloned).  The README.md file in the same directory as that file has instructions for compiling and running it with simple_switch, adding a few table entries to the P4 tables in that program, and sending packets in and observing the packets that come out.

There are several hours of tutorial videos from the Fall 2017 P4 Developer Day on YouTube here: https://www.youtube.com/watch?v=3DJeqS_dl_o&list=PLf7HGRMAlJBzGC58GcYpimyIs7D0nuSoo

Warning: The exercises from the developer day often rely upon a particular version of simple_switch and p4c being installed, which are unlikely to be the latest versions of the source code you have installed so far.  The developer day instructions hopefully give a way to create a virtual machine with the specific versions of the software that they used on that day.

**Comment by panweixu** [comment]
> p4语言有两个版本。该程序是使用旧版本编写的，因此您必须指出：
> `p4c-bm2-ss --std p4-14 simple_router.p4`

![e1](https://user-images.githubusercontent.com/40857784/45595130-8ed27880-b9d9-11e8-9983-759bb3d4ce0f.png)

Still can't compile, I want to know that p4_16 p4 file can run "p4c-bm2-ss -o test.json test.p4" to generate json file, p4_14 p4 file need to run what command to generate json file? Thanks

**Comment by ChrisDodd** [comment]
You need `--std p4-16` on the command line to compile a P4_16 file -- `--std p4-14` is for P4_14...

**Comment by panweixu** [comment]
> 您需要`--std p4-16`在命令行上编译P4_16文件 - `--std p4-14`适用于P4_14 ...

What command can I use to compile the p4 file of p4_14 into a json file?

**Comment by panweixu** [comment]
> You need `--std p4-16` on the command line to compile a P4_16 file -- `--std p4-14` is for P4_14...

![e2](https://user-images.githubusercontent.com/40857784/45626649-991c7180-bac2-11e8-9dfb-7101a33eda63.png)
![e11](https://user-images.githubusercontent.com/40857784/45626672-a5a0ca00-bac2-11e8-87e7-3338581a3b9c.png)

I want to know where I am wrong?

**Comment by mbudiu-vmw** [comment]
This program is written in a dialect of P4-14 which is unsupported, it is version 1.1 of P4-14.
@ChrisDodd was maintaining the P4-14 v1.1 language support.
