### ISSUE TITLE
Delete fields `drop` and `recirculate_port` from v1model.p4?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1484]
As far as I can tell, these two fields were added to p4c in April 2016, and except for mentions in some compiled BMv2 JSON files, and `drop` being mentioned in a few test P4_16 programs for p4c, they are not used for anything in the p4c or behavioral-model code.

Removing recirculate_port is probably easiest, since I believe no test programs use it.

Removing drop is a little bit more work, since mentions of it in P4_16 test programs should be changed to `mark_to_drop()` if they assign drop = 1, or some other benign assignment to replace it if they assign drop = 0 (or just delete such assignments with no replacement, if the test case doesn't need an assignment statement in that part of the program to exercise the bug).

**Comment by jafingerhut** [comment]
@antoninbas This is a low priority issue, but wanted to tag your name for your thoughts on it, in case I am missing something about use of these fields that I couldn't find in the p4c or behavioral-model code.

**Comment by antoninbas** [comment]
I would be fine with that but maybe other backends actually require these fields somehow?
The drop field in particular must be confusing to people, since I imagine it is completely ignored by the bmv2 backend.

**Comment by jnfoster** [comment]
Can confirm that students learning P4 on Bmv2 get confused by this. I support removing it.

**Comment by jafingerhut** [comment]
I do not mind removing those two fields if others want it to happen, but at least for now #1493 has a big comment block explaining that these two metadata fields are not used by simple_switch at all, and what methods people should call in order to drop packets.

**Comment by jafingerhut** [comment]
There are now comments in the v1model.p4 file declaring these two fields deprecated, and explaining how the packet should be dropped in P4_14 or P4_16+v1model programs, so I will go ahead and close this issue.
