### ISSUE TITLE
How can I find the version 0.1 of p4c

### ISSUE THREAD

**Issue by LiPeio-o** [p4lang/p4c#1487]
hello, I've correctly run the 0.5 version of p4c, but  another project I have at hand need 0.1 version of p4c, so where can I get it？

thx a lot!

**Comment by mbudiu-vmw** [comment]
We do not really advance the versions carefully. Your best best is to check when the options.compilerVersion field was changed and to roll-back to a previous commit. We should probably automate the version incrementation somehow with every check-in.
