### ISSUE TITLE
Data plane vs. control plane data representations in PSA arch

### ISSUE THREAD

**Issue by dingrui37** [p4lang/p4c#1488]
Hi,all. I have read the `Data plane vs. control plane data representations` section of PSA spec https://p4.org/p4-spec/docs/PSA.html. But I have some questions. 

- controller may control multiple devices with different PSA implementations, these different PSA implementations will include different` psa.p4` or the same one? For example, target X will include psa.p4(port id size is 9), while target Y will include psa.p4(port id size is 16), or target X and target Y will include the same psa.p4(port id size is 32). 

- Some PSA implementations are expected to use noticeably fewer resources(e.g. PortId_t). For a specific target agent, how does the agent know which field needs to be truncated? according to the field name from P4Info?

- p4runtime_translation. I want to know where the translation rules are?  Are they customized by the agent? 
```
header to_cpu_error_header_t {
    bit<8> error_idx;
    bit<1> ingress;
    bit<3> packet_path;
    bit<4> reserved1;

    // port is ingress_port if ingress is 1, else egress_port

    // This annotation is needed by the P4 compiler and tool chain so
    // that a P4 Runtime API agent knows that this is a field of type
    // PortId_t or PortIdInHeader_t that needs its values numerically
    // translated between the control plane and data plane.
    @p4runtime_translation("port")
    PortIdInHeader_t port;
}
```

- I think there may be two possible operations on PortId:
1) truncate or pad.
2) numerically translated between the control plane and data plane. 
Is it right?

**Comment by dingrui37** [comment]
@jafingerhut

**Comment by jafingerhut** [comment]
Regarding this comment:

"controller may control multiple devices with different PSA implementations, these different PSA implementations will include differentpsa.p4 or the same one? For example, target X will include psa.p4(port id size is 9), while target Y will include psa.p4(port id size is 16), or target X and target Y will include the same psa.p4(port id size is 32)."

Our thinking here is that each target will have its own slightly-customized version of the psa.p4 include file, which is the same as the published one, except it has its own custom bit widths defined for those few PSA types expected to have target-dependent widths.  The P4 compiler will thus see these target-dependent widths when compiling an "executable" or "binary blob" specific to that target.

When generating a "P4 info" file for P4Runtime, either an annotation on the `type` definition for type `PortId_t` and the others, or the type name itself, will be used to determine the P4Runtime width for that field, e.g. 32 bits for `PortId_t`.  This has not been implemented in the open source P4 tools yet, but see this issue if you want to keep track of details and progress there: https://github.com/p4lang/p4c/issues/1461

**Comment by jafingerhut** [comment]
At least part of the agent software (aka P4Runtime server software) will be target-specific, and will need to be intimately familiar with many details about the target that the controller (aka P4Runtime client) will not be aware of.

The field name from the P4Info file will not be enough, because there could be 7 action parameters and 3 table key fields spread throughout your P4_16 + PSA program that are all of type `PortId_t`, and all of them will be 32 bits wide in messages between the controller and agent, and all of them will be the target-specific custom width in the target device.  If numeric translation occurs in the agent, as we plan to support for type `PortId_t` values, it needs to occur for all of those places, independent of the name of the field.

The plan is for the P4Runtime server / agent to determine these places from the contents of the P4Info file.  Again, for details of exactly what in the P4Info file will represent that, follow the issue I linked above and any related issues that arise from completing that work.

**Comment by dingrui37** [comment]
Thank you for your detailed explanation @jafingerhut . I counted the occurrences of  `PortId_t `  is about 7 times in psa.p4, except some type defines and const values, but what about "3 table key fields" means?
> because there could be 7 action parameters and 3 table key fields spread throughout your P4_16 + PSA program that are all of type PortId_t

```
struct psa_ingress_parser_input_metadata_t {
  PortId_t                 ingress_port;
  ...
}

struct psa_egress_parser_input_metadata_t {
  PortId_t                 egress_port;
  ...
}

struct psa_ingress_input_metadata_t {
  PortId_t                 ingress_port;
  ...
}

struct psa_ingress_output_metadata_t {
  ...
  PortId_t                 egress_port;      // initial value is undefined
}

struct psa_egress_input_metadata_t {
  ...
  PortId_t                 egress_port;
  ...
}

struct psa_egress_deparser_input_metadata_t {
  PortId_t                 egress_port;
}

action send_to_port(inout psa_ingress_output_metadata_t meta,
                    in PortId_t egress_port)
{
  ...
}
```

**Comment by jafingerhut** [comment]
Sorry if I was confusing.  I did not mean to count the number of occurrences of type `PortId_t` in the psa.p4 code.  I meant that when you write a data plane P4_16+PSA architecture program, you can in general have any number of table key fields and/or action parameters that are of type `PortId_t`.  7 was just an example.  However many occurrences your P4 program has of values of type `PortId_t` in these places, it would be preferably for you if they are all automatically labeled as such in the P4Info file, whether there are 0, 7, or 100 such occurrences.  That is the plan.  The same goes for the other types defined in the PSA specification like ClassOfService_t, etc. listed here: https://p4.org/p4-spec/docs/PSA.html#sec-psa-type-definitions

**Comment by dingrui37** [comment]
Thanks, I get it! @jafingerhut
