### ISSUE TITLE
Support key fields of type error in bmv2 back-end

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#1490]

**Comment by jafingerhut** [comment]
This issue is perhaps more general, but if you want more focused issues on smaller pieces of the problem, that makes sense, too: https://github.com/p4lang/p4c/issues/1067

**Comment by mbudiu-vmw** [comment]
I thought that there was an issue, but I could not find it using search. This is a duplicate, so I will close it.
