### ISSUE TITLE
ERROR - execute make -j4 

### ISSUE THREAD

**Issue by euclidesfjr** [p4lang/p4c#1495]
Good morning, I need some help to solve this problem. When executing the installation instructions:

3. Build. Building should also take place in a subdirectory named `build`.
    (I.e.
    mkdir build ==> OK
    cd build ==> OK
  mininet @ mininet-p4c: ~ / p4c / build $ cmake .. -DCMAKE_BUILD_TYPE = RELEASE ==> OK

mininet @ mininet-p4c: ~ / p4c / build $ make -j4
Scanning dependencies of target linkgraphs
Scanning dependencies of target update_includes
Scanning dependencies of target linkbmv2
Scanning dependencies of target linkp4cebpf
[0%] Built target linkgraphs
Scanning dependencies of target linkp4test
[0%] Built target update_includes
Scanning dependencies of target p4ctoolkit
[0%] Built target linkbmv2
[1%] Building CXX object lib / CMakeFiles / p4ctoolkit.dir / unified_libp4ctoolkit_srcs_1.cpp.o
Scanning dependencies of target mkv1dirs
[1%] Built target linkp4test
[1%] Built target mkv1dirs
[1%] Built target linkp4cebpf
Scanning dependencies of target mkp4dirs
Scanning dependencies of target gtest
Scanning dependencies of target mkP4configdir
[1%] Built target mkp4dirs
[3%] Building CXX object test / CMakeFiles / gtest.dir / frameworks / gtest / googletest / src / gtest-all.cc.o
Scanning dependencies of target p4c_driver
[3%] Built target mkP4configdir
[4%] Copying p4c driver
[4%] Built target p4c_driver
[6%] Linking CXX static library libp4ctoolkit.a
[6%] Built target p4ctoolkit
[7%] [BISON] [IRgenParser] Building parser with bison 3.0.4
[9%] [FLEX] [IRgenLexer] Building scanner with flex 2.6.0
Scanning dependencies of target irgenerator
[10%] Building CXX object tools / ir-generator / CMakeFiles / irgenerator.dir / unified_irgenerator_srcs_1.cpp.o
[12%] Building CXX object tools / ir-generator / CMakeFiles / irgenerator.dir / ir-generator.cpp.o
In file included from ir-generator.ypp: 126: 0:
/home/mininet/p4c/build/tools/ir-generator/ir-generator-lex.c:584:5: warning: '{anonymous} :: yy_flex_debug' defined but not used [-Wunused-variable]
 int yy_flex_debug = 0;
     ^ ~~~~~~~~~~~~
/home/mininet/p4c/build/tools/ir-generator/ir-generator-lex.c:356:5: warning: '{anonymous}:: yylineno' defined but not used [-Wunused-variable]
 int yylinene = 1;
     ^ ~~~~~~~
[14%] Linking CXX static library libgtest.a
[14%] Built target gtest
[15%] Linking CXX executable irgenerator
[15%] Built target irgenerator
Scanning dependencies of target genIR
[17%] Generating IR class files
[17%] Built target genIR
make [2]: *** No rule to make target '../control-plane/PI/proto/p4/v1/p4data.proto', needed by 'control-plane / google / rpc / status.pb.cc '. Stop.
frontends / CMakeFiles / frontend.dir / build.make: 93: warning: overriding recipe for target 'frontends / parsers / v1 / v1parser.output'
CMakeFiles / Makefile2: 1229: recipe for target 'control-plane / CMakeFiles / controlplane.dir / all' failed
make [1]: *** [control-plane / CMakeFiles / controlplane.dir / all] Error 2
make [1]: ** Waiting for other processes to finish.
frontends / CMakeFiles / frontend.dir / build.make: 74: warning: ignoring old recipe for target 'frontends / parsers / v1 / v1parser.output'
Scanning dependencies of target ir
Scanning dependencies of target midend
[20%] [BISON] [v1Parser] Building parser with bison 3.0.4
[20%] [BISON] [p4Parser] Building parser with bison 3.0.4
[21%] Building CXX object ir / CMakeFiles / ir.dir / unified_ir_srcs_1.cpp.o
[23%] Building CXX object midend / CMakeFiles / midend.dir / unified_midend_srcs_1.cpp.o
[25%] Building CXX object midend / CMakeFiles / midend.dir / unified_midend_srcs_2.cpp.o
[26%] Running Flex on parsers / p4
[28%] Running Flex on parsers / v1
Scanning dependencies of target frontend
frontends / CMakeFiles / frontend.dir / build.make: 93: warning: overriding recipe for target 'frontends / parsers / v1 / v1parser.output'
frontends / CMakeFiles / frontend.dir / build.make: 74: warning: ignoring old recipe for target 'frontends / parsers / v1 / v1parser.output'
[29%] Building CXX object frontends / CMakeFiles / frontend.dir / parsers / p4 / p4lexer.cc.o
[31%] Building CXX object frontends / CMakeFiles / frontend.dir / parsers / p4 / p4parser.cpp.o
[32%] Building CXX object ir / CMakeFiles / ir.dir / unified_ir_srcs_2.cpp.o
In file included from /home/mininet/p4c/build/ir/unified_ir_srcs_2.cpp:5:0:
/home/mininet/p4c/ir/pass_manager.cpp: In member function 'virtual const IR :: Node * PassManager :: apply_visitor (const IR :: Node *, const char *)':
/home/mininet/p4c/ir/pass_manager.cpp:45:53: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (stop_on_error && :: errorCount ()> initial_error_count)
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mininet/p4c/ir/pass_manager.cpp: In member function 'virtual const IR :: Node * PassRepeated :: apply_visitor (const IR :: Node *, const char *)':
/home/mininet/p4c/ir/pass_manager.cpp:109:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (stop_on_error && :: errorCount ()> initial_error_count)
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 34%] Building CXX object midend/CMakeFiles/midend.dir/unified_midend_srcs_3.cpp.o
[ 35%] Building CXX object frontends/CMakeFiles/frontend.dir/parsers/v1/v1lexer.cc.o
[ 37%] Building CXX object frontends/CMakeFiles/frontend.dir/parsers/v1/v1parser.cpp.o
[ 39%] Building CXX object frontends/CMakeFiles/frontend.dir/__/ir/ir-generated.cpp.o
[ 40%] Linking CXX static library libmidend.a
[ 40%] Built target midend
[ 42%] Building CXX object frontends/CMakeFiles/frontend.dir/unified_frontend_sources_1.cpp.o
In file included from /home/mininet/p4c/ir/ir.h:40:0,
                 from /home/mininet/p4c/build/ir/ir-generated.cpp:1:
/home/mininet/p4c/ir/indexed_vector.h: In instantiation of ‘void IR::IndexedVector<T>::check_valid() const [with T = IR::Property]’:
/home/mininet/p4c/ir/ir.def:288:51:   required from here
/home/mininet/p4c/ir/indexed_vector.h:165:18: warning: variable ‘it’ set but not used [-Wunused-but-set-variable]
             auto it = declarations.find(el->getName());
                  ^~
[ 43%] Linking CXX static library libir.a
[ 45%] Building CXX object frontends/CMakeFiles/frontend.dir/unified_frontend_sources_2.cpp.o
[ 45%] Built target ir
[ 46%] Building CXX object frontends/CMakeFiles/frontend.dir/unified_frontend_sources_3.cpp.o
In file included from /home/mininet/p4c/lib/compile_context.h:23:0,
                 from /home/mininet/p4c/lib/error.h:22,
                 from /home/mininet/p4c/lib/null.h:22,
                 from /home/mininet/p4c/ir/ir.h:25,
                 from /home/mininet/p4c/frontends/common/applyOptionsPragmas.h:22,
                 from /home/mininet/p4c/frontends/common/applyOptionsPragmas.cpp:17,
                 from /home/mininet/p4c/build/frontends/unified_frontend_sources_1.cpp:2:
/home/mininet/p4c/lib/cstring.h: In static member function ‘static cstring cstring::make_unique(const T&, cstring, char) [with T = std::set<cstring>]’:
/home/mininet/p4c/lib/cstring.h:273:27: warning: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 7 [-Wformat-truncation=]
 template<class T> cstring cstring::make_unique(const T &inuse, cstring base, char sep) {
                           ^~~~~~~
/home/mininet/p4c/lib/cstring.h:273:27: note: directive argument in the range [0, 2147483647]
In file included from /usr/include/stdio.h:936:0,
                 from /usr/include/c++/7/cstdio:42,
                 from /usr/include/c++/7/ext/string_conversions.h:43,
                 from /usr/include/c++/7/bits/basic_string.h:6349,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/stdexcept:39,
                 from /usr/include/boost/optional/bad_optional_access.hpp:15,
                 from /usr/include/boost/optional/optional.hpp:27,
                 from /usr/include/boost/optional.hpp:15,
                 from /home/mininet/p4c/frontends/common/applyOptionsPragmas.h:20,
                 from /home/mininet/p4c/frontends/common/applyOptionsPragmas.cpp:17,
                 from /home/mininet/p4c/build/frontends/unified_frontend_sources_1.cpp:2:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 3 and 12 bytes into a destination of size 8
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
[ 48%] Building CXX object frontends/CMakeFiles/frontend.dir/unified_frontend_sources_4.cpp.o
[ 50%] Building CXX object frontends/CMakeFiles/frontend.dir/unified_frontend_sources_5.cpp.o
[ 51%] Building CXX object frontends/CMakeFiles/frontend.dir/unified_frontend_sources_6.cpp.o
In file included from /home/mininet/p4c/lib/compile_context.h:23:0,
                 from /home/mininet/p4c/lib/error.h:22,
                 from /home/mininet/p4c/lib/null.h:22,
                 from /home/mininet/p4c/ir/ir.h:25,
                 from /home/mininet/p4c/frontends/p4/evaluator/substituteParameters.h:22,
                 from /home/mininet/p4c/frontends/p4/evaluator/substituteParameters.cpp:17,
                 from /home/mininet/p4c/build/frontends/unified_frontend_sources_3.cpp:2:
/home/mininet/p4c/lib/cstring.h: In static member function ‘static cstring cstring::make_unique(const T&, cstring, char) [with T = std::unordered_set<cstring>]’:
/home/mininet/p4c/lib/cstring.h:273:27: warning: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 7 [-Wformat-truncation=]
 template<class T> cstring cstring::make_unique(const T &inuse, cstring base, char sep) {
                           ^~~~~~~
/home/mininet/p4c/lib/cstring.h:273:27: note: directive argument in the range [0, 2147483647]
In file included from /usr/include/stdio.h:936:0,
                 from /usr/include/c++/7/cstdio:42,
                 from /usr/include/c++/7/ext/string_conversions.h:43,
                 from /usr/include/c++/7/bits/basic_string.h:6349,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from /usr/include/c++/7/istream:38,
                 from /usr/include/c++/7/sstream:38,
                 from /home/mininet/p4c/ir/ir.h:22,
                 from /home/mininet/p4c/frontends/p4/evaluator/substituteParameters.h:22,
                 from /home/mininet/p4c/frontends/p4/evaluator/substituteParameters.cpp:17,
                 from /home/mininet/p4c/build/frontends/unified_frontend_sources_3.cpp:2:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 3 and 12 bytes into a destination of size 8
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
In file included from /home/mininet/p4c/lib/compile_context.h:23:0,
                 from /home/mininet/p4c/lib/error.h:22,
                 from /home/mininet/p4c/lib/null.h:22,
                 from /home/mininet/p4c/ir/ir.h:25,
                 from /home/mininet/p4c/frontends/p4/evaluator/substituteParameters.h:22,
                 from /home/mininet/p4c/frontends/p4/evaluator/substituteParameters.cpp:17,
                 from /home/mininet/p4c/build/frontends/unified_frontend_sources_3.cpp:2:
/home/mininet/p4c/lib/cstring.h: In static member function ‘static cstring cstring::make_unique(const T&, cstring, char) [with T = std::set<cstring>]’:
/home/mininet/p4c/lib/cstring.h:273:27: warning: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 7 [-Wformat-truncation=]
 template<class T> cstring cstring::make_unique(const T &inuse, cstring base, char sep) {
                           ^~~~~~~
/home/mininet/p4c/lib/cstring.h:273:27: note: directive argument in the range [0, 2147483647]
In file included from /usr/include/stdio.h:936:0,
                 from /usr/include/c++/7/cstdio:42,
                 from /usr/include/c++/7/ext/string_conversions.h:43,
                 from /usr/include/c++/7/bits/basic_string.h:6349,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from /usr/include/c++/7/istream:38,
                 from /usr/include/c++/7/sstream:38,
                 from /home/mininet/p4c/ir/ir.h:22,
                 from /home/mininet/p4c/frontends/p4/evaluator/substituteParameters.h:22,
                 from /home/mininet/p4c/frontends/p4/evaluator/substituteParameters.cpp:17,
                 from /home/mininet/p4c/build/frontends/unified_frontend_sources_3.cpp:2:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 3 and 12 bytes into a destination of size 8
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
[ 53%] Building CXX object frontends/CMakeFiles/frontend.dir/unified_frontend_sources_7.cpp.o
[ 54%] Linking CXX static library libfrontend.a
[ 54%] Built target frontend
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
mininet@mininet-p4c:~/p4c/build$ 

And I'm not resolving this problems.

Thanks alot.

**Comment by jafingerhut** [comment]
It is very easy to miss one or more steps in the README of these tools.  Also, if you attempt installing them on a machine that already has many other packages installed, a few packages will hinder the building of P4 tools (I don't have a list of these handy, sorry, but have seen one or two mentioned in other issues).

If you are able to create a fresh Ubuntu 16.04 Linux installation on a bare machine, or a new virtual machine, these steps have worked for me repeatedly:
```
sudo apt install git
git clone https://github.com/jafingerhut/p4-guide
./p4-guide/bin/install-p4dev.sh
```
then provide your password when prompted.  That shell script has about 30 commands in it, all of which are obtained from the READMEs of the behavioral-model and p4c repositories, both of which are installed.

**Comment by mbudiu-vmw** [comment]
There are a bunch of duplicates for this question, with small variations. I will close this one.
