### ISSUE TITLE
Create source info in BMv2 JSON for more primitive actions

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1496]
Right now a `"source_info"` key is created for many constructs in the BMv2 JSON file written by the bmv2 back end, e.g. assignment statements, evaluation of if conditions, etc.  The BMv2 simple_switch software switch uses these to print file and line number info when executing those actions, when `--log-console` or `--log-file` command line options are specified.

There is no `"source_info"` key created for several cases in the latest code right now, that would be nice to have for better debugging when these occur in your program.  Examples: resubmit(), recirculate(), clone(), clone3().  There may be others, too, but even adding only those would be a small useful enhancement.

If it helps test the changes, there is a P4_16 program that uses all of those primitive operations, and right now prints only the message "Primitive (no source info)" when they are executed.  See the program, table entries, and test packets to exercise these paths, here: https://github.com/jafingerhut/p4-guide/tree/master/v1model-special-ops

**Comment by mbudiu-vmw** [comment]
You added much of this code, but you left a bunch of TODOs. Maybe it's one of them.

**Comment by jafingerhut** [comment]
Yes, I did, and I may end up implementing this myself, so the issue is a reminder if I do it.  I was contacted by someone looking for ways to get their feet wet with P4 open source tools, and created this in case they find it interesting to work on.

**Comment by jafingerhut** [comment]
Enhancement completed via PR https://github.com/p4lang/p4c/pull/1518
