### ISSUE TITLE
Extend error in v1mode.p4 to include an InvalidChecksum member

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#1505]
The v1model.p4 declaration of `standard_metadata` includes the following:
```
/// Indicates that a verify_checksum() method has failed.
// TODO: this should be deprecated in favor of parser_error
bit<1>  checksum_error;
/// Error produced by parsing
error parser_error;
```
This seems to indicate that we should use `parser_error` to signal invalid checksums to the ingress control. However, core.p4 doesn't define any appropriate error symbol for this, so should we add one in v1model.p4:
```
error {
    InvalidChecksum
}
```

**Comment by jnfoster** [comment]
I'm not sure I agree that checksum verification failures should be encoded into `parser_error`. In the logical pipeline, the parser comes first and the checksum control comes second. Although targets like Bmv2 implement the both in a single phase of computation, that's not the only design...

 So having two distinct error fields in the metadata actually seems sensible.

**Comment by antoninbas** [comment]
That makes sense to me. But the we should update the comment in v1model.p4.

**Comment by antoninbas** [comment]
Thanks for taking care of this @jafingerhut
