### ISSUE TITLE
Is behavior of P4_16+v1model resubmit() primitive action outside of P4_16 language spec?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1514]
The same is true for recirculate and clone3 operations, but I will focus on resubmit in the question.

Right now with p4c using v1model, you can do a resubmit() primitive operation, giving it a list of metadata variables whose value you want to be preserved from the current ingress processing, to the packet that will be resubmitted and processed in ingress again.

With the latest p4c and behavioral-model simple_switch code as of 2018-Sep-22, the values of these metadata fields that are included with the resubmitted packet are *not* the current values at the time the resubmit() operation is called.  Instead, they are the values that those metadata variables have *at the time ingress processing is complete*.

There is no way I can think of to define an operation like this that behaves according to the rules of the P4_16 language spec.  The P4_16 language spec defines direction `in`, `out`, and `inout`, and in the v1model.p4 include file the resubmit parameter is defined as direction `in`, as are the similar arguments for the recirculate and clone3 primitives.  According to the P4_16 language spec, I believe this means that at the time of the call, the current values of those fields are copied to the callee.  When the callee returns, it will no longer have access to how the values of those variables might change afterwards.

Is this a bug in simple_switch's execution behavior?

Is it the way that things ought to behave for P4_16+v1model architecture to more accurately match the P4_14 behavior, and it is just kind of the way the existing tools work, without regard for the P4_16 language spec?

Something else?

Note: For PSA v1.0 the way that metadata is specified to be carried along with packets is different than in v1model, and avoids this issue.  It is all done via explicit assignment statements involving new input and output parameters to parsers and deparser control blocks, with explicit assignments to read or modify their values required in your P4_16 code.

**Comment by jafingerhut** [comment]
I didn't read the P4_14 v1.0.4 spec exhaustively, but searched for occurrences of resubmit.  That spec says that resubmit takes a list of metadata fields, whose values are to be preserved with the resubmitted packet, but it does not seem to explicitly say when during the execution of the program those values should be used.

**Comment by jafingerhut** [comment]
I have created a fairly short test program to demonstrate the behavior here, in case anyone is surprised by this.  README here: https://github.com/jafingerhut/p4-guide/blob/master/v1model-special-ops/README-test-resubmit.md

P4_16 + v1model architecture source code here: https://github.com/jafingerhut/p4-guide/blob/master/v1model-special-ops/resubmit-maybe-violates-p416-spec.p4

**Comment by mbudiu-vmw** [comment]
The compiler can copy the values in a temporary at the resubmit time and restore them at the end of the pipeline. This will implement the correct semantics on the simulator.

**Comment by jafingerhut** [comment]
If the current behavior is the expected one for P4_14 programs, that might make it a little challenging to auto-translate P4_14 to P4_16+v1model programs with the same behavior.

**Comment by mbudiu-vmw** [comment]
Why not use an STF file to exhibit the bug?
If I read correctly your message this is a bug. We can fix this either with the simulator or with the compiler.

**Comment by jafingerhut** [comment]
Partly this is a question about what the expected P4_14 behavior is for resubmit, too, because if resubmit() called anywhere during ingress in P4_14 is _supposed_ to preserve the values of those metadata fields at the _end_ of ingress processing, not at the time the resubmit() call is made, then supporting all of these 3 things in p4c + BMv2 sounds a bit strange to me:

+ p4c compiles p4_14 straight to bmv2, where resubmit() call means "preserve end-of-ingress metadata values"
+ p4test auto-translates p4_14 to p4_16+v1model with same packet processing behavior, but all calls in the resulting P4_16 source code have only immediate effects at the call site.
+ p4_16+v1model with only immediate effects at the call site semantics compiles straight to bmv2

If that combination of results is what is desired, it seems one way to do that is for the P4_14 auto-translated-to P4_16+v1model resubmit() calls to only be made as "near the end of ingress", possibly with more than one resubmit call, each with different field lists, in some conditional switch or if-then-else structure.  That way it gets the field values at the end of ingress.  The P4_14 resubmit calls would be translated into assigning a numeric 'field list id' to some hidden variable like standard_metadata.resubmit_flag, which is exactly what BMv2 is doing now.

That sounds like a semi-fancy transformation for p4test to make from P4_14 to P4_16+v1model code, so I wouldn't recommend it unless the current P4_14 resubmit 'spooky action at a distance' semantics is the expected one, and worth working to preserve.

The similar transformations would need to be done for recirculate and clone operations, too, I believe.

**Comment by jafingerhut** [comment]
I chatted with Han Wang and Calin Cascaval today, and they confirmed that the desired P4_14 behavior of resubmit, recirculate, and clone operations there is that you give a field list, and effectively a reference to that field list is remembered until the _end_ of the execution of the current ingress or egress control is complete, and _then_ the values of the fields in that field list are used and preserved.  So it intentionally by design has this "delayed effect".

With the current p4test, p4c, and behavioral-model repositories, if you take a P4_14 program and auto-translate it to P4_16, you get P4_16+v1model architecture source code that has similar-looking resubmit, recirculate, and clone calls as in the original program, at a similar place in the control flow, and if you then compile and run them on behavioral-model simple_switch, the behavior does match the P4_14 program behavior.  It just happens to do so by using not-really-P4_16 semantics of the recirculate, resubmit, and clone calls.

Their summary, and I agree, is that any effort that would be spent in fixing this, to avoid the not-really-P4_16 semantics, would be better spent in making progress on the implementation of P4_16 + PSA architecture.   (This not-really-P4_16 semantics issue is _not_ present in the way that PSA defines how to do recirculate, resubmit, and clone operations.)

I may create a PR adding a comment in v1model.p4 about this, in case anyone else happens to wonder about this issue.

**Comment by mbudiu-vmw** [comment]
If you look at the code for digest in the back-end, it actually handles the semantics of P4-16 programs correctly by saving the digested values into temporaries and digesting the temporaries. This prevents the temporaries from being overwritten. We can do the same thing for the other primitives.

To handle P4-14 programs when converted to P4-16 we have to do the opposite: convert any call to these primitives to a call that sets a boolean flag, and then execute these primitives last thing in the pipeline conditioned on that boolean flag. Part of this translation should be done in the P4-14 to P4-16 conversion step.

**Comment by jafingerhut** [comment]
The P4_14 to P4_16 auto-translation would need more than just a boolean flag.  It would need to store an identifier for the last field list done for any resubmit call on that packet, in case more than one were done.  At least, that is how the "resubmit" BMv2 JSON primitive is implemented, by storing an id of a field list in the standard_metadata.resubmit_flag field.

And a separate identifier for the field list associated with the last recirculate call (standard_metadata.recirculate_flag is what BMv2 JSON uses today).

And similarly for clone (BMv2 JSON today uses 16 out of the 32 bits inside of standard_metadata.clone_spec.  The other 16 bits store the other parameter of the clone operation).

I think the reason for Calin and my evaluation is whether it is worth all that effort for updating v1model code?

**Comment by mbudiu-vmw** [comment]
This has been effectively solved by #2902
