### ISSUE TITLE
p4test/p4c give errors for this P4_16 program with function calls

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1538]
Program attached.  It seems like a fairly straightforward and expected use of functions in P4_16 to me.

[p4-functions.p4.txt](https://github.com/p4lang/p4c/files/2436037/p4-functions.p4.txt)

**Comment by mbudiu-vmw** [comment]
The fix is small, but it will cause lots of reference outputs to change, because it needs to rename some temp variables...

**Comment by jafingerhut** [comment]
My test program was added as a new test case in testdata, and I have compared the output files for it in testdata/p4_16_samples_outputs against the original program, and they appear to correctly implement the original source code.  Closing this issue.
