### ISSUE TITLE
incorrect sharing of IR nodes between package instance.

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1540]
The following example is for an architecture with two pipelines. Each pipeline instantiated two control blocks: Ingress and IngressDeparser. There is a top level package that instantiate two pipelines p0 and p1.

It seems that some IR nodes are shared between these two pipelines, which is unexpected. For example, the IR nodes for `IngressMirror` have the same ID in both pipelines, which seems wrong. The IR node for `SwitchIngress` and `SwitchIngressDeparser` have different IDs, which is correct.

```
./p4test ../testdata/p4_16_samples/issue1032.p4 -Tinlining:3
Will inline <ControlBlock>(15806) IngressMirror@<Declaration_Instance>(9870) im_0/im into <ControlBlock>(15805) SwitchIngressDeparser
Will inline <ControlBlock>(15818) IngressMirror@<Declaration_Instance>(9870) im_0/im into <ControlBlock>(15817) SwitchIngressDeparser
```
```
#include <core.p4>

control Ingress<H, M>(inout H h, inout M m);
control IngressDeparser<H>(packet_out pkt, inout H h);
package Pipeline<H, M>(Ingress<H, M> g, IngressDeparser<H> _c);
package Top<H1, M1, H2, M2>(Pipeline<H1, M1> p0, Pipeline<H2, M2> p1);

header header_t {}
struct metadata_t {}

control IngressMirror() {
  apply { }
}

control SwitchIngress(inout header_t t, inout metadata_t m) {
  apply { }
}

control SwitchIngressDeparser(packet_out pkt, inout header_t h) {
  IngressMirror() im;
  apply {
    im.apply();
  }
}

Pipeline(SwitchIngress(), SwitchIngressDeparser()) p0;
Pipeline(SwitchIngress(), SwitchIngressDeparser()) p1;

Top(p0, p1) main;
```

**Comment by mbudiu-vmw** [comment]
First, there's a pr waiting with a related fix. Second, it is the blocks that must be distinct even if they point to the same ir nodes.

**Comment by hanw** [comment]
Sorry, I should be clearer on why the issue was filed. The inlining pass did not inline the `IngressMirror` block. After some investigation, I concluded that it was due to the two instances of `SwitchIngressDeparser()` are sharing the same IR node for `IngressMirror`.

**Comment by hanw** [comment]
It's probably a bug.

**Comment by mbudiu-vmw** [comment]
Is this bug still happening after merging #1525?

**Comment by hanw** [comment]
@mbudiu-vmw  Any further thoughts on this?

**Comment by mbudiu-vmw** [comment]
Once I merge 1539 I will look again. Hopefully I can tackle it this week-end.

**Comment by mbudiu-vmw** [comment]
I think I got it.

**Comment by hanw** [comment]
Thanks!
