### ISSUE TITLE
Valid P4 program?

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1545]
Is this a valid P4 program? 

```
control C() { apply {} };
control D() { apply {} };

control E()(C ctrl, D dep) {
    apply {
	    ctrl.apply();
    }
}

control F() {
    C() c;
    D() d;
    E(c, d) e;
    apply {
	e.apply();
    }
}
```

Frontend returns the following error.
```
$ ./p4test --std p4-16 test.p4
test.p4(4): error: ctrl: parameter cannot have type control C
control E()(C ctrl, D dep) {
              ^^^^
test.p4(1)
control C() { apply {} };
        ^
test.p4(4): error: dep: parameter cannot have type control D
control E()(C ctrl, D dep) {
                      ^^^
test.p4(2)
control D() { apply {} };
```

**Comment by mbudiu-vmw** [comment]
We agreed that one cannot pass controls or parsers as compile-time arguments. This may allow you to write recursive programs.

**Comment by jafingerhut** [comment]
The tables in the spec show that controls can be compile time parameters to controls, and parsers for parsers: https://p4.org/p4-spec/docs/P4-16-v1.1.0-draft.html#sec-calling-restrictions

Controls and parameters cannot be run-time parameters to other things.

Could one truly write a recursive program, if controls can be compile-time parameters to other controls, with all of the other restrictions still met?

**Comment by jnfoster** [comment]
Controls *can* be passed as compile-time arguments. However, declarations of a control like `C` does not introduce a new type. 

One can write the program like this:
```p4
//Declaration of a control type X with no data-plane arguments
control X();

//Declaration of a control object of type X.
control C() { apply {} };
control D() { apply {} };

//Declaration of a control object of type X, whose constructor takes two arguments of type X.
control E()(X ctrl, X dep) {
    apply {
	    ctrl.apply();
    }
}

control F() {
    C() c;
    D() d;
    E(c, d) e;
    apply {
	e.apply();
    }
}
```

**Comment by jnfoster** [comment]
@jafingerhut I haven't proved it formally but I think it should be possible to show that no recursive controls can be expressed with our current restrictions.

**Comment by hanw** [comment]
https://github.com/p4lang/p4c/blob/master/frontends/p4/typeChecking/typeChecker.cpp#L1416
line 1416 - 1420 should be removed then.

**Comment by mbudiu-vmw** [comment]
OK, my explanation was not very correct. @jnfoster is right: you can use a parameter whose type is a "control type", but not a "control".

**Comment by mbudiu-vmw** [comment]
No, Type_Control is a different node from P4Control.

**Comment by mbudiu-vmw** [comment]
Think if Type_Control as the prototype for a control.

**Comment by jafingerhut** [comment]
So in your sample code, Nate, you call this a declaration of a control object:
```
//Declaration of a control object of type X.
control C() { apply {} };
```
That does not actually _instantiate_ a control named C, does it?

If I try to make maybe bad analogies to Java's object system, is this somewhere about right?

+ Java interface <-> P4 declaration of a control type (e.g. `control X();`)
+ Java class definition that extends an interface <-> P4 declaration of control object (e.g. `control C() { apply {} };`)     (a breakdown in this analogy is that a Java class definition that extends an interface always names the interface(s) being extended explicitly, whereas a P4 declaration of a control object doesn't _name_ any control types at all -- it just automatically extends all of them it has a compatible signature with?)
+ Java `new ClassName();` to allocate and run constructor for an object, returning a fresh object <-> P4 instantiation of a control (e.g. `C() c;`)

**Comment by mbudiu-vmw** [comment]
This is a good analogy. The only restriction is that new is evaluated at compile-time.

**Comment by jnfoster** [comment]
The breakdown in the analogy stems from the fact that type checking for controls in P4 is structural whereas Java has a nominal type system.

```p4
control X();
control Y();

control C()(X x, Y y) {
  apply { 
    x.apply();
    y.apply();
  } 
}

control D() {
  apply { 
  } 
}

control Main() {
  D() d1;
  C(d1,d1) c1;
  C(c1,c1) c2;
  C(c1,c2) c3;
  C(d1,c3) c4;
  apply {
    c4.apply();  
   } 
}
```
In particular, note that the various `c`s and `d`s can all be used as an `X` or a `Y` -- i.e., those are really two names for the same type, which denotes the set of `control`s whose `apply` takes no data-plane arguments.

**Comment by jafingerhut** [comment]
So maybe this is another difference between P4 and Java where my analogy breaks down, but the current p4c compiler effectively auto-instantiates controls (and probably also parsers) when you apply them.  For example, this code, with no explicit instantiations:
```
control A() { ... }
control B() {
    apply { A.apply(); }
}
control C() {
    apply { A.apply(); }
}
```
behaves the same as this code with explicit instantiations:
```
control A() { ... }
control B() {
    A() a1;
    apply { a1.apply(); }
}
control C() {
    A() a2;
    apply { a2.apply(); }
}
```
I believe this is intentional, for the convenience of the programmer, but wanted to double-check.

**Comment by hanw** [comment]
Yes, that is specified in section 14.1

**Comment by hanw** [comment]
So the origin example can be simplified to.
```
control C() { apply {} };
control D() { apply {} };

control E()() {
    apply {
	 C.apply();
         D.apply();
    }
}

control F() {
    apply {
	E.apply();
    }
}
```

**Comment by hanw** [comment]
@milad14000 see if the above solved your issue?

**Comment by milad14000** [comment]
@hanw The two examples are completely different. In one scenario you have a single instance that can be applied from multiple controls
```
control C() { apply {} };
control D()(C c) {
    apply {
        c.apply();
    }
}

control E()(C c) {
    apply {
	c.apply();
    }
}
```

In the other example you have multiple instances 
```
control C() { apply {} };
control D()() {
    apply {
         C c1;
	 c1.apply();
    }
}

control E() {
    apply {
        C c2;
	c2.apply();
    }
}
```

@mbudiu-vmw  According to the spec both are valid examples but compiler is rejecting the first one which is a bug.

**Comment by mbudiu-vmw** [comment]
No, it is not a bug. We just had that conversation a few days ago.
C is not a type, it is a control. You must specify a type for the argument.
```
control c_type();
control D()(c_type c) {...}
```

**Comment by hanw** [comment]
Just to keep a record. The following example is how to share the same control instance between multiple controls.

```
control M();
package Main(M m);

control Z();

action NoAction() {}
control C()(bit<8> n) {
	table t {
		actions = { NoAction; }
	}
	apply {
		t.apply();
	}
};
control D() { apply {} };

control E()(Z z) {
    apply {
         z.apply();
    }
}

control X()(Z z) {
    apply {
	z.apply();
    }
}

control F() {
    C(8w0) c;
    E(c) e;
    X(c) x;
    apply {
	e.apply();
	x.apply();
    }
}

Main(F()) main;
```

**Comment by jafingerhut** [comment]
Yes, Han's example in previous comment looks correct to me.  I've tried something similar in p4c, and of course the limitation of apply'ing a table at most once for each call to ingress or egress code prevents the bmv2 back end from being able to generate BMv2 JSON for it.  But it is syntactically correct P4_16 that will create only one instantiation of control C and apply it from 2 places.  It seems to compile correct for BMv2 back end if you eliminate the table from control C, e.g. update an indexed counter instead.

**Comment by jafingerhut** [comment]
Created this issue with a program based on Han's example code above, except the 'leaf control' in the call tree updates an indexed counter instead of applying a table.  The code generated by p4c (before the BMv2 back end) appears to be slightly wrong.  https://github.com/p4lang/p4c/issues/1566

I do not think that issue affects any of the discussion above -- it simply appears to be a bug uncovered by trying code like that discussed here.
