### ISSUE TITLE
assert and assume

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1548]
Proposal for adding 'assert' and 'assume' statements to P4.

These could probably be introduced into the P4_16 language as extern
functions.  I would guess that their implementation in p4c and BMv2
simple_switch would be fairly straightforward, and an experimental
implementation there could precede adding them to the language spec
(if adding them to the language spec is even desirable).

Assert statements are part of the standard library of many programming
languages.  During testing of a P4 program, it can be useful to have
statements like this:

    assert(<boolean expression>)

The default behavior would be that such statements are no-ops, and for
optimization purposes, that they are removed early during compilation
so as not to hinder andy optimizations.

When assert statements are enabled in a software switch like BMv2
simple_switch, and the expression evaluates to false, debugging
information and a distinctive error message should be printed that can
be searched for by test case post-processing code to cause test cases
to fail, if desired.

It should be easy for the developer to get debugging information, such
as:

+ file name
+ line number
+ text of condition that failed
+ The values of the header fields or variables involved in the
  expression, at least, and perhaps _all_ header and metadata values
  for the packet, too.  Ideally the developer would probably also like
  the entire path of execution up to that point, similar to what
  simple_switch outputs when the `--log-console` command line option
  is given.
+ Optionally, at run time drop into an interactive debugger session
  that lets the developer examine the values of more things.

In an FPGA or ASIC, if the compiler supported enabling assert
statements, they could be implemented as if replaced by this code:
```
    if (! (<boolean expression>)) {
        mark_to_drop();   // for v1model, or the equivalent for PSA.

	// Probably also a good idea to change any state that would
	// cause the packet to be resubmitted, recirculated, cloned,
	// generate_digest "off" for this packet.

        // Record as much information in an implementation-specific
	// manner that allows the software to derive as much of the
	// above debugging information as is practical.
        exit;
    }
```
A formal verification tool could use assert statements, too.  For
example, a tool like p4pktgen [1] could attempt to find example input
packets and table entry contents that would cause the assert condition
to evaluate to false.

[1] https://github.com/p4pktgen/p4pktgen

The statement:

    assume(<boolean expression>)

looks similar to assert, but has a fairly different meaning in the
context of a formal verification tool.  Whereas an assert statement
gives a condition that you _hope_ is true at that point of execution
of the program, and you want to know if it is ever false,
assume(condition) means that you as a developer somehow know or
strongly believe that this condition _will always be true_.

Even if the P4 program text itself has nothing it that would require
it to be true, you know that the control plane software will always
install table entries that cause the condition to be true.  Or,
neighboring devices in the network will always send you packets that
make the condition true, if the expression refers to packet header
field values.  Or, some combination of those things.

A formal verification tool could basically include in its logical
constraints the formula <boolean expression> == TRUE, and _never
consider_ any execution scenario where the condition is false.  For
example, the developer can use an assume statement in combination with
assert statements to say: Try to find an example that makes one of the
assert conditions false, but I only want to see examples that
simultaneously make all of the assume conditions true.  Don't show me
examples that violate any of the assume conditions, because I consider
them irrelevant.

Now, during execution of a P4 program in BMv2 simple_switch, assume
statements could be treated exactly like assert statements.  If one of
these conditions ever evaluated to false, it could be a sign that the
developer was wrong in their belief that the statement is always true,
and they should change or remove it.  It could also be a sign that the
control plane software installed a combination of table entries that
violated the P4 developer's assumptions, and someone should look into
where the problem lies (perhaps the control plane software, perhaps
the P4 program, or perhaps both).

The same is also true for execution in a hardware target.  See above
for suggested behavior of the assert statement.

Some proof tools could likely take advantage of more general
expressions than those that can be written in P4 syntax,
e.g. existential or univeral quantifiers.  I am not proposing adding
anything like that here yet -- start with what P4 syntax can do, and
if more powerful things are desired, probably passing P4 strings
through would be the most flexible thing that doesn't require lots of
new P4 syntax that would only be useful inside of assert and assume
statements.

**Comment by jnfoster** [comment]
Should this be posted to p4-spec instead?

**Comment by jafingerhut** [comment]
It could be.  Some features like this have led with an experimental implementation in p4c / behavioral-model rather than leading with the spec, but I'm fine creating an issue in p4-spec.

Given that the proposed behavior is that these assert/assume statements would by default have 0 effect on the generated products, they seem fairly safe to include in the open source implementations.

**Comment by jnfoster** [comment]
Sure. Developing it as an experimental feature in p4c and then bringing it to the LDWG makes sense.

One small tweak: should `assert` be a no-op in non-debug mode on an ASIC (which I think is standard in many language) or should it drop the packet (which also seems sensible)?

**Comment by mbudiu-vmw** [comment]
P4 does not have a notion of dropping a packet. That's a target-specific action.

**Comment by mbudiu-vmw** [comment]
I think that a log function would also be handy.
Also, note that exit can only be called within a control. If you want to use asserts in parsers you may need something else.

**Comment by jafingerhut** [comment]
One reason I suggest that assert and assume both be complete no-ops by default, and even be eliminated before any internal compiler optimization passes, is that the mere act of *reading* some header or metadata fields can cause a new use later in the pipeline than might exist if the assert is removed, hindering packet header vector optimizations that could reuse that space if it were gone.

I think it would be better if there were new command line options for compilers that could do something like drop a packet and record error info if an assert fails (as I think is in the long-ish writeup), but as Mihai says that would be architecture-specific behavior.

Regarding the behavior in parser code rather than a control, the behavior could perhaps instead be to transition to reject state after assigning a new "AssertFailure" error code.

**Comment by jafingerhut** [comment]
@jnfoster One question I wanted to ask you -- if you read through the proposal for 'assume', you'll see the  difference in semantics I am proposing for that vs. assert.  The difference would be biggest in a proof assist tool.

In a proof assist tool, can you think of any other behaviors other than 'assert' and 'assume' that might be useful?

**Comment by jnfoster** [comment]
Without saying these things should be added to P4, these two things are generally useful in verification tools.

1. Ghost state.

2. Commands for maintaining a trace (e.g., for printing counter-examples).

**Comment by mbudiu-vmw** [comment]
Please note that `verify` is very much like the proposed `assert`.

**Comment by hesingh** [comment]
Having programmed one programmable switching asic and another router asic, the parsers of both drop a packet on any parsing failure.  After the parser, the switch pipeline processes the packet.  Thus, it does not surprise me if P4-16 restricts use of verify only in the P4 parser.    If one would still like to use assert in subsequent blocks such as ingress/egress control, maybe we allow verify outside the parser as well. 

I support a trace/log feature for the data plane.

@jnfoster what do you mean by a Ghost state?

**Comment by hesingh** [comment]
@jafingerhut  Thanks for the Ghost state details.  

Mihai says, even P4 does not have any concept of dropping a packet - it's target-specific behavior.

In regards to dropping a packet, let's take an example of a packet with martian IP address.  Whether the P4 parser or the ingress processing performs the martian check, on detection of a martian IP address, the data plane should drop the packet.  An 'exit' in ingress control sounds reasonable to me.

**Comment by jafingerhut** [comment]
When Mihai says P4 does not have any concept of dropping a packet, I believe he is referring to the P4_16 language specification alone.  Any notion of dropping a packet, and how that should be achieved, is left to the architecture definitions in P4_16.  The two existing switch architecture v1model and PSA both have well-defined techniques for dropping packets, but they are slightly different.  Thus one could not in the P4_16 language specification describe a way to drop a packet that works across all architectures.

**Comment by jafingerhut** [comment]
`assert` and `assume` extern functions have been added to p4c and behavioral-model with these commits:

* behavioral-model - https://github.com/p4lang/behavioral-model/commit/c0a2d01ff1f034e1403db447eb66b4663fecac91
* p4c - https://github.com/p4lang/p4c/commit/6466ecce2bc74165d96a85a36e88be5198a415a4

Unlike the original proposal, the default behavior of p4c is for assert and assume statements to affect packet processing in the behavioral-model simple_switch process, by aborting the entire simple_switch process if either an assert or an assume condition is evaluated to false.

There is a command line option `--ndebug` that can be passed to the `p4c-bm2-ss` command to cause assert and assume statements to be effectively no-ops, by not including them at all in the compiled BMv2 JSON output file used by simple_switch.  https://github.com/p4lang/p4c/pull/1859#issuecomment-490208361

Unfortunately there isn't currently any command line option that can be used by the `p4c` command for this.  I will create a separate issue to add that.
