### ISSUE TITLE
Issue with inserting cast in p4-14 primitives

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1559]
Following program triggers an warning in frontend which should not happen. The issue is related to how cast is inserted in the typecheck pass for p4-14 programs.

```header_type user_metadata_t {
    fields {
	global_pkt_count: 32;
 	status_cycle: 2; // should only be 0,1,2,3
    }
}
metadata user_metadata_t md;

parser start {
    return ingress;
}

action maintain_2bit_variable(){
	shift_right(md.status_cycle, md.global_pkt_count, 4);
}
table tb_maintain_2bit_variable{
	actions {maintain_2bit_variable;}
	default_action: maintain_2bit_variable;
}

control ingress{
	apply(tb_maintain_2bit_variable);
}
control egress {
}
```

Warning:
```
cast_bug.p4(14): warning: >>: shifting value with 2 bits by 4
 shift_right(md.status_cycle, md.global_pkt_count, 4);
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jafingerhut** [comment]
Have you checked the BMv2 JSON 'code' generated by that shift_right() statement to verify that it is not masking away the upper 30 bits of md.global_pkt_count before doing the shift?

If it is doing that, that sounds like the warning is telling you something pretty significant, and probably that issue should be fixed in the compiler, vs. merely silencing the warning.

**Comment by hanw** [comment]
This is p4-16 code after the PrettyPrint pass. I talked to Chris offline about the issue. I think we understand what's going on. I am just creating an issue here to keep track. It should be fixed in the compiler.
```
control ingress(inout headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
    @name(".maintain_2bit_variable") action maintain_2bit_variable() {
        meta.md.status_cycle = (bit<2>)meta.md.global_pkt_count >> 4;
    }
    @name(".tb_maintain_2bit_variable") table tb_maintain_2bit_variable {
        actions = {
            maintain_2bit_variable;
        }
        default_action = maintain_2bit_variable();
    }
    apply {
        tb_maintain_2bit_variable.apply();
    }
}
```

**Comment by hanw** [comment]
yes. it's most likely a bug.

**Comment by jafingerhut** [comment]
You may want to be careful about how p4c handles different P4_14 arithmetic ops here, in fixing this.

e.g. bit_shift_left on a small unsigned int to a larger one should probably first cast to the wider width, then shift, whereas bit_shift_right on a large unsigned int to a smaller one should first shift, then cast to the smaller width.  That is, assuming that is what P4_14 defines for the results of those operations, and/or what people expect to happen.

**Comment by hanw** [comment]
PR #1561

**Comment by mbudiu-vmw** [comment]
I assume you can close this one too.
