### ISSUE TITLE
P4_16 program that appears legal gives Compiler Bug in bmv2 back end

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1560]
The error message is similar to that for issue https://github.com/p4lang/p4c/issues/1544, but the line number of code in the bmv2 back end is different, and the program exhibiting the bug does not use P4_16 functions at all, so perhaps a different root cause.  I do get the error with the latest version of p4c after the fix for #1544 was merged in.

Command and error message I see:
```
action-profile.p4(136): warning: Target does not support default_action for cIngress.t1 (due to action profiles)
    table t1 {
          ^^
In file: /home/jafinger/p4c/backends/bmv2/common/expression.cpp:636
Compiler Bug: action-profile.p4(176): hdr.ipv4.dstAddr[15:0];: Unhandled case
        meta.hash1 = hdr.ipv4.dstAddr[15:0];
                     ^^^^^^^^^^^^^^^^^^^^^^
```
[action-profile.p4.txt](https://github.com/p4lang/p4c/files/2493399/action-profile.p4.txt)

**Comment by jafingerhut** [comment]
Adding a slightly larger example program, with some similar lines added in comments near the one that causes the problem.  If any of those commented-out lines replaces the one causing the problem, the compiler appears to create a correct BMv2 JSON output.  Perhaps the issue is something to do with the bit slice operator in particular places of the compiler's IR, that the bmv2 back end does not expect or handle yet.
[action-profile.p4.txt](https://github.com/p4lang/p4c/files/2493477/action-profile.p4.txt)

**Comment by mbudiu-vmw** [comment]
@ChrisDodd @hanw: this is an issue with the LocalCopyPropagation pass. It propagates an expression into a table key which turns out to be too complicated for the back-end. This happens after the SimplifyKey pass in the midend, which can simplify such expressions. In this case the expression contains a bit slice.

**Comment by jafingerhut** [comment]
Tried out the test program after the fix to the compiler was merged in.  No more compiler error, and a quick examination of the last midend pass P4_16 compiler output, and the BMv2 JSON, looks reasonable.  I didn't try testing it yet, but if any further problems detected will file a separate issue.  Closing this one.
