### ISSUE TITLE
Error: parameter should be assigned in call

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1563]
Attached is a sample program that triggers a new error in typeChecker.cpp

```
issue-1560.p4(32): error: Gheen: parameter should be assigned in call Tingley
action Tingley(Gheen) {
```

[issue1560.p4.txt](https://github.com/p4lang/p4c/files/2494016/issue1560.p4.txt)

**Comment by hanw** [comment]
I think it is related to #1556

**Comment by mbudiu-vmw** [comment]
I don't think this is a bug, I think you have to give an argument to Tingley when you initialize the default action.

**Comment by hanw** [comment]
Thanks Mihai. Good catch.
