### ISSUE TITLE
@metadata annotation causes missing header using p4c-bm2-ss

### ISSUE THREAD

**Issue by isaac-ped** [p4lang/p4c#1564]
Adding metadata annotations or aliases to a user-defined metadata struct causes it not to be added to headers in the output json, which in turn causes an error starting bmv2:

``` p4
@metadata @name("my_metadata")
struct my_metadata_t {
    @alias("meta.field") bit<1> my_field;
}
```

With the code code below, `my_metadata` is added to the `header_types` list, but not to the `headers` list.
Starting bmv2 with the output json produces the error:

```
simple_switch: P4Objects.cpp:2172: int bm::P4Objects::init_objects(std::istream*, bm::LookupStructureFactory*, bm::device_id_t, bm::cxt_id_t, std::shared_ptr<bm::TransportIface>, const std::set<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >&, const bm::P4Objects::ForceArith&): Assertion `field_exists(header_name, field_name)' failed.
```

If the `my_metadata_t` struct is used in P4 (`m1.my_field = 1` uncommented below), it produces an error upon compilation:
```
Compiler Bug: .../p4c/backends/bmv2/common/expression.cpp:292: Null name
```

Full code to reproduce issue:
```P4
#include "v1model.p4"

header headers_t {}

@metadata
struct my_metadata_t {
    bit<1> my_field;
}

parser MyParser(packet_in pkt, out headers_t hdr,
                inout my_metadata_t m1, inout standard_metadata_t m2) {
    state start {
        transition accept;
    }
}

control MyIngress(inout headers_t hdr, inout my_metadata_t m1, inout standard_metadata_t m2) {
    apply {
        // If the next line is uncommented, produces a "Compiler Bug" error
        // m1.my_field = 1;
    }
}

control MyEgress(inout headers_t hdr, inout my_metadata_t m1, inout standard_metadata_t m2) { apply {} }
control MyVerify(inout headers_t hdr, inout my_metadata_t m) { apply {} }
control MyCheck(inout headers_t hdr, inout my_metadata_t m) { apply {} }
control MyDeparser(packet_out pkt, in headers_t hdr) { apply {} }

V1Switch(MyParser(), MyVerify(), MyIngress(), MyEgress(), MyCheck(), MyDeparser()) main;
```

**Comment by mbudiu-vmw** [comment]
The spec does not say anything about a `@metadata` annotation.
I personally don't know what it is supposed to mean.

**Comment by jafingerhut** [comment]
Is p4c intended to do nothing except pass on annotations that it does not understand itself?

Perhaps the p4c bmv2 back end is treating `@metadata` annotation in an unexpected or incorrect way?

**Comment by isaac-ped** [comment]
Unsure precisely how it is supposed to be handled, but v1model.p4 utilizes the @metadata annotation here:
https://github.com/p4lang/p4c/blob/56142a583addef3b37b741472168dd9261aabd87/p4include/v1model.p4#L31

**Comment by hanw** [comment]
I think the `@metadata` annotation was added to assist certain backend to distinguish the standard_metadata from other metadata. It is not very well defined and should be removed from v1model.p4. User should definitely not rely on it.

**Comment by jafingerhut** [comment]
@isaac-ped It is definitely possible to declare struct types and variables/etc. for packet-local metadata all over a P4_16 + v1model arch. program without using any special annotation at all.

**Comment by antoninbas** [comment]
I've observed that when declaring
```
struct M {
    @alias("aaa") bit<32> f1;
}
```
and using `M` as the metadata struct in your ingress & egress controls, the `@alias` annotation gets lost.
However, if I write
```
struct M1 {
    @alias("bbb") bit<32> f1;
}
struct M {
    @alias("aaa") bit<32> f1;
    M1 m;
}
```
then I do see an alias entry for the `f1` field in `M1`.
The difference is a bit strange and seems to be caused by the introduction of the `scalars` header type in the bmv2 backend.

However, since `@alias` is not a user-facing P4_16 annotation, I'm not sure this can really be considered as a bug. @isaac-ped the takeaway here IMO is that you should not hard-code field names for non standard metadata fields in your bmv2 externs: if a field is defined by the program and not the architecture, it doesn't make sense.
