### ISSUE TITLE
Default argument in architecture definition?

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1593]
The following program currently fails with error:
```
struct intrinsic_metadata_t {
   bit<8> f0;
   bit<8> f1;
}
control C<H, M>(
    inout H hdr,
    inout M meta,
    in intrinsic_metadata_t intr_md = { 0, 0 });
package P<H, M>(C<H, M> c);

struct hdr_t { }
struct meta_t { }
control MyC(inout hdr_t hdr, inout meta_t meta) {
   apply {}
}

P(MyC()) main;
```

```
test.p4(17): error: main: Cannot unify functions with different number of arguments:  function(hdr, meta) to  function(hdr, meta, intr_md)
P(MyC()) main;
         ^^^^
```

But there is a default value on the `in` parameter. Does it make sense to allow code written this way? It seems like a legal program.

**Comment by mbudiu-vmw** [comment]
The default value is for a parameter of the TYPE C.
You would need a default value for the parameter of MyC instead, which is a control.

I think we should not even accept default parameter values for type declarations for controls and parsers, they are not useful. So this is actually a different bug.

**Comment by cc10512** [comment]
@mbudiu-vmw having default values for arguments of packages, controls, and parsers defined in the architecture was the entire idea behind pushing for named arguments and default values. We wanted to reduce the boiler plate that users of an architecture need to write. If you recall, some of the controls in PSA have more than 4 arguments (e.g. EgressParser has 7!). A fair number of P4 programs will not need to worry about the different options enabled by these arguments, so having a default value in the type would seriously help.

**Comment by mbudiu-vmw** [comment]
Well, the package at least works.
I will have to think about this for a bit.

**Comment by jnfoster** [comment]
I see that this would improve some programs, but it seems quite specific. AFAIK even Scala, which tends to have everything in its type system, doesn't have this feature.

I would propose that we prioritize this below other type system improvements -- e.g., adding back generics -- and perhaps consider other solutions. For example, if we had more pervasive type inference then probably almost all type arguments could be omitted.

**Comment by jnfoster** [comment]
Apologies, yes, I conflated two threads.

Default arguments for controls etc. is indeed important for usability of PSA.

**Comment by hanw** [comment]
> Well, the package at least works.
> I will have to think about this for a bit.

Seems to me that the package does not work either.

The following code returns error:
```
error: main: No argument for parameter c
```

```
struct intrinsic_metadata_t {
   bit<8> f0;
   bit<8> f1;
}

struct empty_t {}

control nothing(inout empty_t hdr, inout empty_t meta, in intrinsic_metadata_t imeta) {
   apply {}
}

control C<H, M>(
    inout H hdr,
    inout M meta,
    in intrinsic_metadata_t intr_md);

package P<H, M>(C<H, M> c = nothing());

struct hdr_t { }
struct meta_t { }

P() main;
```

**Comment by mbudiu-vmw** [comment]
Can you also add this example as a test? It does not seem to be the same as the test you submitted with the PR.

**Comment by mbudiu-vmw** [comment]
I think that this issue has been solved by some commit in the past. I will close it, but if you think it is not solved feel free to reopen it.
