### ISSUE TITLE
p4c incorrectly optimizes away action assignment statements

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1595]
With latest p4c as of 2018-Nov-07, I think it is pass 30 of the front end that incorrectly optimizes away the assignment statements in actions a1 through a4 of the attached P4_16 program, which seems like a bug to me.  Those are legitimate side effects that should be happening, and are visible in the output packet.  Perhaps the fact that bit slices are being used in the assignment left-hand side for later actions is causing the compiler to "believe" that the earlier assignments are killed?  Note that the left-hand side slices are assigning to _different_ bits of the field, so the earlier assignments also need to happen.

[switch-stmt-behavior1.p4.txt](https://github.com/p4lang/p4c/files/2559981/switch-stmt-behavior1.p4.txt)

**Comment by mbudiu-vmw** [comment]
You are probably right, the compiler models the slices as writes to the whole field, so it thinks that the later ones kill the first ones.

**Comment by jafingerhut** [comment]
If you want a program with corresponding STF test for this, let me know and I can cook one up.  I am guessing that fixing the bug should also be visible in the P4_16 program output by the front end, though.

**Comment by jafingerhut** [comment]
A small corner of my mind is wondering whether you are considering doing def-use analysis on each of the W bits of a `bit<W>` independently :-)   Or perhaps only if a slice operator is used on a value at least once.

**Comment by mbudiu-vmw** [comment]
The bug is not in the model of the slices, but in keeping track of what the write set is at each program point. The notion of program point is not consistent between the writes set computation and the read set computation. Haven't fixed it yet.

**Comment by jafingerhut** [comment]
I have tried out the after-fix-merged version of p4c on my program exhibiting the problem, and the BMv2 JSON file and intermediate P4_16 source files output by the compiler look correct now.
