### ISSUE TITLE
move tests that use experimental features ?

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#1597]
The following test programs in the p4_16_samples directory are not actually legal P4 -- they make use of abstract functions which are an experimental feature.
```
[Failed] p4c/testdata/p4_16_samples/virtual.p4
[Failed] p4c/testdata/p4_16_samples/bfd_offload.p4
[Failed] p4c/testdata/p4_16_samples/serenum.p4
[Failed] p4c/testdata/p4_16_samples/issue304-1.p4
[Failed] p4c/testdata/p4_16_samples/virtual2.p4
```
Not a huge deal, but what would people think about moving these programs to another directory?

**Comment by mbudiu-vmw** [comment]
I don't have any particular objection.
We could also tag them somehow with a comment on the first line, so a script could omit them.

**Comment by liujed** [comment]
I just merged in a few more tests that use a different experimental feature:
```
testdata/p4_16_samples/pragma-action.p4
testdata/p4_16_samples/pragma-pkginfo.p4
testdata/p4_16_samples/pragma-deprecated.p4
testdata/p4_16_samples/pragma-string.p4
testdata/p4_16_samples/pragmas.p4
```

**Comment by mbudiu-vmw** [comment]
I will close this.

**Comment by jnfoster** [comment]
So we are okay with having tests in this directory that are for the compiler, and not the language spec. That's fine with me.
