### ISSUE TITLE
What would be a good way to define a default constructor parameter in architecture definition?

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1603]
I am looking for a way to define a parser to have some constant default parameters. For example, I am looking for a way to define a parser `ingressParser` with a default parameter `instances` that is default to -1.

```
parser IngressParser<H, M>(
    packet_in pkt,
    out H hdr,
    out M ig_md)(int instances = -1);
```

When user creates a parser, if he/she does not specify a constructor parameter, the value of `instances` will be assumed to be -1.
```
parser MyIngressParser<hdr_t, meta_t>(
   packet_in pkt,
   out hdr_t hdr,
   out meta_t meta) {
   state start {
      transition accept;
   }
}
```

If the user specifies a constructor parameter `instances`, it overrides the value provided in architecture file.

```
parser MyIngressParser<hdr_t, meta_t>(
   packet_in pkt,
   out hdr_t hdr,
   out meta_t meta)(int instances = 0xff) {
   state start {
      transition accept;
   }
}
```

**Comment by mbudiu-vmw** [comment]
You can't. 

In Java terms, think of IngressParser as being a Function object.  MyIngressParser is actually a factory that can produce an IngressParser. So IngressParser does not have constructor arguments, only the factory does.

**Comment by mbudiu-vmw** [comment]
The only thing you can do is to provide a factory in the architecture file which has some default arguments. Then people will invoke the factory (in terms of P4 they will instantiate it) with the desired constructor arguments. This should work.

**Comment by mbudiu-vmw** [comment]
What are you trying to achieve?

**Comment by hanw** [comment]
I am trying to define a package that contains 32 ingress parsers, 1 ingress pipeline and 1 ingress deparsers. 16 of ingress parsers uses implementation A and program the odd number of the ports. The other 16 ingress parsers uses implementation B and program the even number of ports. 

Instead of enumerating all 32 parsers in the top level package, I would like to do be something like this:

```
Parsers (ParserImplA(0x5555_5555), ParserImplB(0xaaaa_aaaa)) parsers;
Pipeline(parsers, IngressImpl(), IngressDeparserImpl()) pipe;
```

0x5555_5555 is a bitmask that represents the ports using the implementation.

I would like to define _explicitly_ in the architecture file that the top level parser can take a parameter named `instances` or `portmask`.

**Comment by ChrisDodd** [comment]
It probably makes more sense to leave the decision of which parser runs on which port to the ABI/runtime -- so the P4 program should just specify that there are two parsers.

**Comment by jnfoster** [comment]
I agree with Mihai. P4's architecture sub-language was designed to specify the P4-programmable components, their data plane interfaces, and how they are organized into pipelines and switches. Features like this should be described in the main language, and having "meta-programming" constructs to support generating parsers, controls etc. programmatically is most consistent with our current design.

**Comment by jnfoster** [comment]
Going to close this issue for now...

**Comment by hanw** [comment]
I am happy if we could add 'meta-programming' constructs in P4.
