### ISSUE TITLE
Change p4 tests using Python to be more descriptive if Python 2 is not used

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#1621]
p4c tests rely on a specific python version in python 2 to run.   If a machine is using python 3 and p4c tests are run (using 'make check'), many test cases fail with a Timeout error.  An example is given below.

207/1186 Test #207: bmv2/testdata/p4_16_samples/array-copy-bmv2.p4 ................................***
Timeout 977.36 sec

This Issue is filed so that p4c code is changed to give an error if the wrong version of python is being used.

**Comment by mbudiu-vmw** [comment]
I think we can close this issue; now all python files that contain a main entry point specify python2.
