### ISSUE TITLE
parser select statement without default key?

### ISSUE THREAD

**Issue by zma-barefoot** [p4lang/p4c#1651]
I don't know if this has been asked before, but what happens with parser select statement without default key?

In example below, what happens if `etherType` is not `0x0800`? Does it transition to ingress control? 

```
parser parse_ethernet {
    extract(ethernet);
    return select(latest.ethertype) {
        0x0800 : parse_ipv4;
    }
}
```

**Comment by jnfoster** [comment]
In this case, it behaves the same as executing `(verify, error.NoMatch)`

See: https://p4.org/p4-spec/docs/P4-16-v1.1.0-spec.html#sec-select

**Comment by mbudiu-vmw** [comment]
The question is about a p4-14 program.
The P4-14 spec https://p4lang.github.io/p4-spec/p4-14/v1.0.5/tex/p4.pdf on page 23 says that this case should trigger a parser exception of type p4_pe_unhandled_select: A select statement had no default specified but the expression value was not in the case list.

The reference compiler does not support parser exceptions, and thus does not implement missing default cases in this way. This may be a bug in the compiler.

**Comment by mbudiu-vmw** [comment]
unless you consider the NoMatch error equivalent to the p4_pe_unhandled select exception... and in this case the compiler is correct.

**Comment by jnfoster** [comment]
Mea culpa! Good point.

-N

**Comment by zma-barefoot** [comment]
Thanks.
