### ISSUE TITLE
bmv2 backend generates incorrect prefix lengths for const entries lpm table

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1661]
I will attach an example P4_16 program and BMv2 JSON output file demonstrating this soon, after I whittle it down to the essentials.

**Comment by jafingerhut** [comment]
Hahaha!  Laughing at myself here.

Read over this program fragment and see if you can find what is most likely a logic bug:
```
    table eth_da_lpm {
        key = { hdr.ipv4.dstAddr: lpm; }
        actions = { set_output_port; my_drop; }
        const entries = {
            0x0c010203 / 32 : set_output_port(1);
            0x0c010200 / 24 : set_output_port(2);
        }
    }
```
Looks like a 32-bit prefix followed by a 24-bit prefix, if you are accustomed to how they are specified in the control plane CLIs.  But in P4_16, that is integer division, leaving an integer constant that is exact match on all 32 bits for both entries.

The compiler would have helped me catch my logic mistake a lot faster if I had tried a `/ 0` prefix :-)

Closing this issue.

**Comment by cc10512** [comment]
BTW, does the compiler strength reduce the expressions? If so, it might be easy to add a pass that checks whether there are duplicate entries and at least print a warning.

**Comment by jafingerhut** [comment]
The compiler does do the integer divisions in one of the front end passes.  In my particular example, the values are no longer duplicates after the division, and that would be a pretty special case if they were.
