### ISSUE TITLE
Relative priority of const entries for lpm table

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1663]
It isn't clear to me yet what should be done about this issue, if anything.  It is pretty minor, so not urgent.

About tables with `const entries`, the P4_16 v1.1.0 language specification says: "Entries in a table are matched in the program order, stopping at the first matching entry." (Section 13.2.1.4 "Entries")

I believe that p4c and bmv2 simple_switch do this for all kinds of tables except one: tables whose keys have no `range` or `ternary` match_kind fields, one `lpm` field, and any number of `exact` fields.

In that case, if you write a P4_16 program like the one I will attach soon, where you explicitly decide to be perverse and put keys with shorter prefixes before keys with longer prefixes, I have confirmed that while the BMv2 JSON file preserves the source code order of the entries, BMv2 does use longest-prefix matching (as I would expect, and seems like the right thing to do for this kind of table).

One possible change that could be made: For such tables, if they have `const entries`, make it a compile-time error to have longer prefixes after shorter ones.  Such an error _could_ be in the bmv2 back end code, but this kind of issue I would expect would be common across multiple back ends that implement longest-prefix match tables.

**Comment by jafingerhut** [comment]
Attaching program that demonstrates the issue.
[issue1663-bmv2.p4.txt](https://github.com/p4lang/p4c/files/2757572/issue1663-bmv2.p4.txt)

**Comment by jafingerhut** [comment]
Another potential change would be to update the P4_16 language spec to call out this case, and describe that the implementation should effectively sort the entries from longest prefix length to shortest.

**Comment by cc10512** [comment]
If you recall, we had an optional priority field in the entry specification. In the end we decided to remove it as we did not have a solid use case, but that could be brought back and then explicitly set the priorities. I believe bmv2 does support explicit priorities.

**Comment by jafingerhut** [comment]
@cc10512 FYI I recently had a conversation with Antonin on the behavior of open source BMv2 here.  The results of what I learned are on this issue, and the documentation PR that is linked from one of the comments: https://github.com/p4lang/behavioral-model/issues/698

Note that I do not see any obvious bugs in BMv2's behavior there.  I just wanted to confirm it was working as designed, and write down the behavior in what to me seemed like weird cases of having a single table with some ternary or range fields, and an lpm field, which is supported in a looks-reasonable-to-me way.

**Comment by mbudiu-vmw** [comment]
Another solution is to implement this by assigning priorities in program order. @cc10512 I will assign you, since you wrote most of the code for this feature.

**Comment by mbudiu-vmw** [comment]
Either the spec or the implementation is wrong.
We have to fix one of them.
If we promise that entries are matched in program order that's what we should do.
The compiler could at least give a warning for LPM matches if the order does not match decreasing lengths.

**Comment by ChrisDodd** [comment]
Perhaps the simplest would be to change the spec just to say "Ternary entries in a table are matched in the program order" -- leaving off other key types for architectures/implementations to deal with.

**Comment by mbudiu-vmw** [comment]
Actually Chris' solution may be the only reasonable one, because match_kinds are extensible by architectures, so we cannot promise this for any conceivable match_kind. We can promise something for the match_kinds that are in core.p4.

**Comment by jafingerhut** [comment]
Chris's suggested change to the spec would work.

**Comment by antoninbas** [comment]
To be generic enough without assuming specific match kinds, we could keep "Table entries are matched in the program order, stopping at the first matching entry" and add something like:
" except for certain match kinds for which the key implies a specific matching priority, such as LPM"

**Comment by jafingerhut** [comment]
Proposed docs for adding to the PSA specification that will cover this, without any changes to the p4c implementation: https://github.com/p4lang/p4-spec/pull/737

**Comment by jafingerhut** [comment]
Created this PR for the P4_16 language spec, following Chris Dodd's suggestion above: https://github.com/p4lang/p4-spec/pull/738

The behavior for 'const entries' table entry order has now been added to the latest draft PSA specification, and I can make similar changes to the docs for v1model in BMv2 simple_switch to match.

**Comment by mbudiu-vmw** [comment]
Can we mark this as fixed?
