### ISSUE TITLE
Save and compare p4runtime files as part of testing

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#1671]

**Comment by mbudiu-vmw** [comment]
We should probably do this at least for v1model programs.

**Comment by mbudiu-vmw** [comment]
This seems to do it for all p4 programs. Perhaps this should be part of the backends/bmv2/run-bmv2-test.py script instead.

**Comment by antoninbas** [comment]
This was purposely done for p4test and not p4c-bmv2, because the P4Info generation is supposed to be backend-independent and work for all v1model or psa programs.
