### ISSUE TITLE
Are there automated tests passing that should be failing?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1678]
I ran the tests below with p4c as of commit d286199567a19f846cb2f48758e37c22501d8581
and the latest version of behavioral-model built before p4c as of 2018-Dec-31 (only documentation changes have been made since then), so that bmv2 tests were enabled to execute, too.

When I built p4c using the options for `cmake` that I most often use: `cmake .. -DCMAKE_BUILD_TYPE=DEBUG`, and then did `cd build ; make check`, all 1220 tests passed.

I believe there are multiple tests with P4 source files that have 'psa' in their name that are in a similar category as the example one I give below.  Let me know if it would be helpful to have a complete list.  There may be other tests that showed as passing with `make check` for source files that do not have 'psa' in the file name, too -- again, I can check and report in a follow-up comment if anyone is curious.

Two of the tests were for the source file named: psa-fwd-bmv2.p4

Here are the relevant lines of output from `make check`:
```
        Start 343: bmv2/testdata/p4_16_samples/psa-fwd-bmv2.p4
344/1220 Test #343: bmv2/testdata/p4_16_samples/psa-fwd-bmv2.p4 ...................................   Passed    1.52 sec
        Start 902: p4/testdata/p4_16_samples/psa-fwd-bmv2.p4
899/1220 Test #902: p4/testdata/p4_16_samples/psa-fwd-bmv2.p4 .....................................   Passed    4.12 sec
```
When I search for and run the shell scripts with named ending in `.test` however, one of them looks like it fails:
```
$ find .|grep psa-fwd-bmv2
./bmv2/testdata/p4_16_samples/psa-fwd-bmv2.p4.test
./p4/testdata/p4_16_samples/psa-fwd-bmv2.p4.test

$ ./p4/testdata/p4_16_samples/psa-fwd-bmv2.p4.test 
./p4test --pp ./tmpEnQBjx/psa-fwd-bmv2.p4 --dump ./tmpEnQBjx --top4 FrontEndLast,FrontEndDump,MidEndLast --testJson --arch psa --p4runtime-format text --p4runtime-file ./tmpEnQBjx/psa-fwd-bmv2.p4.p4info.txt /home/jafinger/p4c/testdata/p4_16_samples/psa-fwd-bmv2.p4
./p4test -I. --pp ./tmpEnQBjx/psa-fwd-bmv2.p4-x --std p4-16 ./tmpEnQBjx/psa-fwd-bmv2.p4
./p4test -I. --pp ./tmpEnQBjx/psa-fwd-bmv2-midend.p4-x --std p4-16 ./tmpEnQBjx/psa-fwd-bmv2-midend.p4

$ ./bmv2/testdata/p4_16_samples/psa-fwd-bmv2.p4.test 
Error compiling
In file: /home/jafinger/p4c/backends/bmv2/psa_switch/psaSwitch.cpp:43
Compiler Bug: /home/jafinger/p4c/testdata/p4_16_samples/psa-fwd-bmv2.p4(37): struct headers {
  ethernet_t ethernet; }: nested structure
struct headers {
       ^^^^^^^


*** Test failed

```
Should the test `./bmv2/testdata/p4_16_samples/psa-fwd-bmv2.p4.test` that appears to fail when run by itself, cause a failure when run as part of `make check`, too?

If not, why isn't it causing a failure?

**Comment by jafingerhut** [comment]
Small additional bit of additional info, in case it helps: the exit status for the first test is 0 (ok), but for the second is 1 (error).  I do not know if `make check` uses that exit status value, or should.

**Comment by cc10512** [comment]
https://github.com/p4lang/p4c/blob/3572fbf06660b6093ac47714ee063d167e857a15/backends/bmv2/CMakeLists.txt#L160 lists the PSA tests as XFAILS (expected to fail) therefore the testing framework (ctest) will revert the error code and deem the test successful if the error code is non-zero.

**Comment by jafingerhut** [comment]
Makes sense.  I knew that there were xfail tests, but did not realize they showed up as Successful in the output of 'make check', rather than as xfail or something else.

**Comment by cc10512** [comment]
That is indeed a ctest limitation. We do save them in 'build/Testing/Temporary/LastXfail.txt' so you know what are your XFAILs. We could dump that file on the console at the end of the run if you think it is useful.

**Comment by jafingerhut** [comment]
It doesn't seem hurtful to dump such a list there, as long as there is a sentence explaining what the list is that is explanatory enough that people besides me do not file issues when they start seeing it :-)
