### ISSUE TITLE
p4c mangles P4_14 intrinsic_metadata header in BMv2 JSON file, preventing resubmit from working

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1694]
In writing a P4_14 test program with STF packet tests that exercise resubmit, recirculate, and clone operations, while preserving metadata (and for a program that would have different packet-in to packet-out behavior if BMv2 did _not_ preserve the metadata requested), I discovered that at least the resubmit operation does not work at all with the BMv2 JSON files from the latest p4c.  Or, if it is possible, I do not know the proper way to do it with the latest p4c version.

I tried older p4c versions, and found that it worked with the latest p4c code as of these dates:
+ 2018-Sep-01
+ 2018-Nov-01
+ 2018-Nov-14
+ 2018-Nov-26

The first commit I found after 2018-Nov-26 where it does not work is the very next commit: 22a5a13ee347dd40e6b7b6472e00ea2205db5358 on 2018-Nov-28.  It fails in a similar way with the 2018-Dec-01 p4c code and the latest code as of 2019-Jan-18.

The resubmit operation in BMv2 works by storing an id of a field_list from the "field_lists" key of the BMv2 JSON data, into a metadata field called `intrinsic_metadata.resubmit_flag`

With the working BMv2 JSON files, the attached P4_14 program produces a header_type in the "header_types" section of the BMv2 JSON data that looks like this:
```
    {
      "name" : "intrinsic_metadata_t",
      "id" : 3,
      "fields" : [
        ["ingress_global_timestamp", 48, false],
        ["egress_global_timestamp", 48, false],
        ["lf_field_list", 8, false],
        ["mcast_grp", 16, false],
        ["egress_rid", 16, false],
        ["resubmit_flag", 8, false],
        ["recirculate_flag", 8, false]
      ]
    },
```

With the non-working BMv2 JSON files, the same program puts the intrinsic_metadata fields into a "scalars" or "scalars_0" header_type along with user-defined metadata fields, and often looks something like this:
```
    {
      "name" : "scalars_0",
      "id" : 0,
      "fields" : [
        ["metadata._intrinsic_metadata_ingress_global_timestamp0", 48, false],
        ["metadata._intrinsic_metadata_egress_global_timestamp1", 48, false],
        ["metadata._intrinsic_metadata_lf_field_list2", 8, false],
        ["metadata._intrinsic_metadata_mcast_grp3", 16, false],
        ["metadata._intrinsic_metadata_egress_rid4", 16, false],
        ["metadata._intrinsic_metadata_resubmit_flag5", 8, false],
        ["metadata._intrinsic_metadata_recirculate_flag6", 8, false],
        ["metadata._mymeta_resubmit_count7", 8, false],
        ["metadata._mymeta_recirculate_count8", 8, false],
        ["metadata._mymeta_clone_e2e_count9", 8, false],
        ["metadata._mymeta_f110", 8, false],
        ["metadata._temporaries_temp111", 48, false],
        ["metadata._temporaries_temp212", 48, false],
        ["metadata._temporaries_temp313", 48, false],
        ["metadata._temporaries_temp414", 48, false]
      ]
    },
```

I was using a command like this to compile the program:
```
p4c --std p4-14 --target bmv2 p414-special-ops.p4
```
[p414-special-ops.p4.txt](https://github.com/p4lang/p4c/files/2790079/p414-special-ops.p4.txt)

**Comment by jafingerhut** [comment]
Whatever changes were made in the commit I mentioned above are _not_ causing the BMv2 JSOn file to put all of the `standard_metadata` fields in with the rest of the user-defined metadata fields, like it is with `intrinsic_metadata`.  If there is something in p4c that is treating `standard_metadata` differently than other header types, maybe it should also be treating `intrinsic_metadata` and `queueing_metadata` similarly special, at least for P4_14 source programs?  That is just a wild guess on my part, without digging into the compiler.

**Comment by antoninbas** [comment]
bmv2 definitely cares about the name, since it will look for `"intrinsic_metadata.resubmit_flag"` by name when initiating the resubmit operation in the ingress match-action pipeline, and when deciding whether to actually perform resubmit after ingress. The only way it could work with the field having a different name is if an alias is included in the bmv2 JSON to map `"intrinsic_metadata.resubmit_flag"` to `"metadata._intrinsic_metadata_resubmit_flag5"` or whatever the name of the field turns out to be (and the same would need to be done for all intrinsic metadata fields).

**Comment by mbudiu-vmw** [comment]
The compiled does something funny about the standard_metadata, I have the impression that it reuses some of the fields as intrinsic metadata. I didn't write that part of the code, and there are several issues related to that. There's an `@alias` annotation on some of the fields of the standard_metadata which guide this process.

**Comment by mbudiu-vmw** [comment]
This is in v1model.p4

**Comment by jafingerhut** [comment]
Mihai, regarding you comments about P4_16 v1model and special annotations for standard_metadata and intrinsic_metadata, I looked into that a little bit more.

The reason that resubmit/recirculate/clone work _at all_ when invoked in a P4_16 + v1model program (as opposed to not working even a little bit, ignoring the metadata preservation issues for the moment), is because of the @alias annotations in v1model.p4 here: https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4#L68

When compiled with p4c for the BMv2 target, that alias causes an entry to be created in a section of the BMv2 JSON file called "field_aliases", like this: https://github.com/jafingerhut/p4-guide/blob/master/v1model-special-ops/v1model-special-ops.p4c-2019-01-25.json#L2705-L2708

This enables BMv2 simple_switch to look up the name "intrinsic_metadata.resubmit_flag" and find it, causing all reads and writes needed to implement the resubmit operation to read/write the field named "standard_metadata.resubmit_flag" instead.

I tried to add annotations to my P4_14 program to create a similar alias, but it is a syntax error to try this:
```
header_type intrinsic_metadata_t {
     fields {
        @alias("intrinsic_metadata.ingress_global_timestamp") ingress_global_timestamp : 48;
        @alias("intrinsic_metadata.egress_global_timestamp") egress_global_timestamp : 48;
        @alias("intrinsic_metadata.lf_field_list")    lf_field_list : 8;
        @alias("intrinsic_metadata.mcast_grp")        mcast_grp : 16;
        @alias("intrinsic_metadata.egress_rid")       egress_rid : 16;
        @alias("intrinsic_metadata.resubmit_flag")    resubmit_flag : 8;
        @alias("intrinsic_metadata.recirculate_flag") recirculate_flag : 8;
     }
 }
```

I am not sure the history of why BMv2 chose to rely on new structs named "intrinsic_metadata" and "queueing_metadata" for the additional features their fields help implement, rather than simply lumping them all together into the existing "standard_metadata", but at least today that is what BMv2 simple_switch is expecting.

**Comment by mbudiu-vmw** [comment]
In principle this is clear, but in practice there may be some problems. We have several filed issues related to these aliases, e.g. #718, #1036, #1564. I have no idea whether these are solved, since we have no tests for them.

**Comment by mbudiu-vmw** [comment]
@jafingerhut : if you have an STF file to go with your p414-special-ops.p4 program then we can test it with my new PR.

**Comment by jafingerhut** [comment]
I do have an STF file.

If in my own local copy of p4c source, from 2018-Nov-26, I add this P4_14 source program and STF file to the testdata/p4_14_samples directory (files may need to be renamed with "-bmv2" suffix in their base name), the test passes.

P4_14 source: https://github.com/jafingerhut/p4-guide/blob/master/v1model-special-ops/p414-special-ops.p4
STF file: https://github.com/jafingerhut/p4-guide/blob/master/v1model-special-ops/p414-special-ops.stf

When I try to compile that P4_14 source program with the latest p4c source, or any of the handful of versions I have tried after 2018-Nov-26 commit, it fails consistently, because of the reasons I describe in earlier comments.

**Comment by mbudiu-vmw** [comment]
It looks like this `intrinsic_metadata` struct in P4-14, although it is defined by the user, it is magic: it's fields are populated automatically in some special way. The P4-14 says nothing about such a struct; it just says that some fields of the standard_metadata are intrinsic. 

Yes, the compiler treats specially standard_metadata, because that is part of the v1model architecture. But intrinsic_metadata isn't. What if the user writes a different definition for intrinsic_metadata in the P4_14 program? Also, how do we know something is intrinsic metadata - does the type have to be intrinsic_metadata_t, or does the instance name have to be intrinsic_metadata?

**Comment by jafingerhut** [comment]
Yes, intrinsic_metadata for BMv2 simple_switch programs (and also queueing_metadata) is effectively just as special/magic as standard_metadata is.  That may not have been the original intent, but it seems to be where simple_switch is today.

More details at these comments on one of the related issues you linked above, #718:
https://github.com/p4lang/p4c/issues/718#issuecomment-458316830
https://github.com/p4lang/p4c/issues/718#issuecomment-458322158

As far as I can tell, if the user chooses to use the name intrinsic_metadata for one of their own user-defined metadata in a P4_14 program, and they happen to use a field in it like mcast_grp or resubmit_flag, then it will trigger, or interfere with, the way simple_switch implements multicast, resubmit, recirculate, and/or clone operations.

We could change that about simple_switch, or deal with it.  I don't know which is the best approach.

**Comment by mbudiu-vmw** [comment]
v1model.p4 already has all these fields as part of standard_metadata (except some fields like recirculate_flag). What we should probably be doing is converting any references to intrinsic_metadata fields in P4-14 to references to standard_medata fields in P4-16. Then I am not even sure we need all this alias stuff, which I never understood. We can hardwire the names `intrinsic_metadata_t` and `intrinsic_metadata` in the converter. The P4-14 spec says nothing about these structures.

**Comment by mbudiu-vmw** [comment]
I got the test you wrote to run correctly by doing some surgery on it and on the compiler. What I did is very simple: I just changed all references to intrinsic_metadata to be instead to standard_metadata. We could have the compiler front-end do this also automatically for P4-14 programs.

Also, the compiler front-end has its own definition of standard_metadata in `ir/v1.cpp`, written in code, which didn't have all these fields; I have added them by hand.

**Comment by mbudiu-vmw** [comment]
If you look at switch.p4 in the test directory, it has a much larger intrinsic metadata structure:
```
header_type ingress_intrinsic_metadata_t {
    fields {
        resubmit_flag : 1;              // flag distinguishing original packets
                                        // from resubmitted packets.

        ingress_global_tstamp : 48;     // global timestamp (ns) taken upon
                                        // arrival at ingress.

        mcast_grp : 16;                 // multicast group id (key for the
                                        // mcast replication table)

        deflection_flag : 1;            // flag indicating whether a packet is
                                        // deflected due to deflect_on_drop.
        deflect_on_drop : 1;            // flag indicating whether a packet can
                                        // be deflected by TM on congestion drop

        enq_qdepth : 19;                // queue depth at the packet enqueue
                                        // time.
        enq_tstamp : 32;                // time snapshot taken when the packet
                                        // is enqueued (in nsec).
        enq_congest_stat : 2;           // queue congestion status at the packet
                                        // enqueue time.

        deq_qdepth : 19;                // queue depth at the packet dequeue
                                        // time.
        deq_congest_stat : 2;           // queue congestion status at the packet
                                        // dequeue time.
        deq_timedelta : 32;             // time delta between the packet's
                                        // enqueue and dequeue time.

        mcast_hash : 13;                // multicast hashing
        egress_rid : 16;                // Replication ID for multicast
        lf_field_list : 32;             // Learn filter field list
        priority : 3;                   // set packet priority
    }
}
metadata ingress_intrinsic_metadata_t intrinsic_metadata;
```

**Comment by mbudiu-vmw** [comment]
Another complication is that the types of these fields are not compatible; for example, here `resubmit_flag` is 1 bit, whereas in other p4-14 programs it's 32 bits.

**Comment by jafingerhut** [comment]
Most likely that switch.p4 was last updated before BMv2 simple_switch had its current documentation for intrinsic_metadata and queueing_metadata structs, and no one ever went back to update it to match.  Without an STF test exercising the packet forwarding operations that rely on the existence of those metadata fields, there is no way to notice such out-of-date programs except manual inspection.
