### ISSUE TITLE
posted to wrong project -- ignore

### ISSUE THREAD

**Issue by johndevans2** [p4lang/p4c#1699]

**Comment by johndevans2** [comment]
Oops. Please delete that. (I will try, too.)

**Comment by johndevans2** [comment]
It seems that only the project owner can delete. (There should be an option
under "Notification")
Please delete the issue as a professional courtesy.

I will be more careful next time. I often have your project and mine open
at the same time.
Github should have a feature that while logged in as XYZ, you're only
allowed to post to XYZ projects. (Github personas)

Regards,
John Evans

**Comment by antoninbas** [comment]
I'm deleting the issue
