### ISSUE TITLE
IGeneralNamespace::getDeclsByName could be slow

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#1703]
The implementation of getDeclsByname requires a full scan. I am wondering whether this is not a significant source of slowdown for large programs - it seems to entail a quadratic cost for checking references. The solution would be to maintain an index within the data structure. However, P4Program does not only contain declarations. @ChrisDodd : could we store the data in a NameMap instead of a Vector, where things that do not have a name use an empty string?

**Comment by ChrisDodd** [comment]
Yes, it should be possible to use a `NameMap<StatOrDecl, std::multimap>` for the data structuure, using an empty name for all the statements (that don't have names).  This has a potential issue that it does not maintain the order of declarations.  If we need that we'd need to create an `ordered_mulitmap` collection for the underlying map.

**Comment by mbudiu-vmw** [comment]
We do need the order to be preserved.

**Comment by ChrisDodd** [comment]
Creating a workable `ordered_multimap` should be possible by just copying lib/ordered_map.h and changing the internal `std::map` into a `std::mulitmap`.  That would give a `oridered_multimap` where iteration order preserves insertion order, which would make it hard to iterate over all the elements with a particular name (std::find will give you the first element with a given name, but other elements with that name might be anywhere later in the map); we could add a special auxiliary iterator to make that easier?

**Comment by mbudiu-vmw** [comment]
Yes, that would be nice. find() should ideally return an iterator over all elements with the same key.

**Comment by mbudiu-vmw** [comment]
Maybe we should call it findByKey()

**Comment by mbudiu-vmw** [comment]
Although I don't know if we need the regular find(), it would be confusing to change its behavior.

**Comment by mbudiu-vmw** [comment]
We actually need a very narrow interface to implement P4Program's IGeneralNamespace interface.

**Comment by ChrisDodd** [comment]
We could have a sorted_iterator that iterates over the contents of the map in (key) sorted order, and has an implicit conversion to a normal iterator (so it could be compared `==`/`!=` against normal iterators) and have `find` return a sorted iterator.  That way `for (auto it = x.find(key); it != x.end() && it->first == key; ++it)` (the normal way of iterating over the values with a particular key in a multimap) would continue to work, though the `MapForKey` adaptor would break, as it uses `decltype(map.begin())`, which is the wrong kind of iterator.

**Comment by mbudiu-vmw** [comment]
I have experimented trying to speed this up but it didn't make a difference in the compilation time, so I will close this issue.
