### ISSUE TITLE
Compilation error caught vs. not-caught when seemingly unrelated code is changed

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1713]
The attached program strength5.p4 is a copy of one that Chris Dodd included in a recent PR.  I was looking at the P4 code and wanted to experiment with it to see what it was doing, and came across a very odd behavior that makes me wonder whether there is something wrong in p4c.

The program strength5.p4 gives no errors with the command below, and the latest version of p4c as of this commit: 00cf6c82b6f30e32d086a8267757e80f65b1783f
```
p4c --target bmv2 --arch v1model strength5.p4
```
when I change the code of action case2 slightly as in the attached program strength5-alt1.p4, I get an error for the code of action case3, which has not been changed.

It seems like either both programs should give an error, or neither should.
```
p4c --target bmv2 --arch v1model strength5-alt1.p4
strength5-alt1.p4(36): [--Werror=legacy] error: cast: Cannot unify int<32> to bit<13>
    action case3() { h.h.c = (bit<8>)((int<32>)(int<16>)h.h.a)[14:2][10:3]; }
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
strength5-alt1.p4(36): [--Werror=type-error] error: cast: Illegal cast from int<32> to bit<13>
    action case3() { h.h.c = (bit<8>)((int<32>)(int<16>)h.h.a)[14:2][10:3]; }
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
[strength5.p4.txt](https://github.com/p4lang/p4c/files/2838007/strength5.p4.txt)
[strength5-alt1.p4.txt](https://github.com/p4lang/p4c/files/2838008/strength5-alt1.p4.txt)

**Comment by ChrisDodd** [comment]
I don't see any errors from either version, though I'm still behind the commit you note -- I'll try advancing.  The error message you show is odd, as there are no bit<13>s anywhere (the intermediate slice is 13 bits, but it should be int<13> as its a signed slice.)

**Comment by jafingerhut** [comment]
I will try a fresh VM with a build of p4c to see if there is something stale on the system I tested with.

**Comment by jafingerhut** [comment]
I had a fresh VM with this commit of p4c already built: 264da2c524c849df0d9ba478cdd1d61b29d64722

It gave same behavior as I described in my original comment.

**Comment by jafingerhut** [comment]
Also, my main reason for reporting was not the content of the error message, so much as the compiler's dependence on reporting it based upon modifying code that seems like it should not affect the generation of that error message at all.  Why should action case3 be correct in one case, and the identical code for action case3 in the other program be an error?

It smells of some kind of bug in p4c innards somewhere, e.g. mutating of data objects shared between different actions?  I have no evidence of that particular cause -- just that the evidence is very hard to explain without something like that going on.

In case it makes a difference, I typically build p4c using the linked script, with the lines highlighted: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev.sh#L158-L165

**Comment by jafingerhut** [comment]
A little more data:
With this commit and a few older ones I tried, both programs give a similar error message: 0559c32f24320efd0db6d0d13b2d432381f40f1f

With the next commit and later, only strength5-alt1.p4 gives the error, but not strength5.p4: 0b03c0224d79b1c61416985dd7b22e2f318ec1a6

**Comment by jafingerhut** [comment]
Mihai, out of curiosity, does it make sense to you that the _same_ code in an action would give an error for one program, but not the other, when the only change is in a different action that had no error?  That just seems very odd.
