### ISSUE TITLE
Develop sizeof solution until module system is available in p4c

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#1717]
It is better to file this new issue so that implementation discussions can take place here.  This way, the spec changes don't get cluttered with implementation details.

See spec-changes that are discussing the problem.

https://github.com/p4lang/p4-spec/issues/660
https://github.com/p4lang/p4-spec/pull/712

Right now, the implementation is focused on supporting ```type.size()```.  After a LDWG discussion, we may change the implementation.

**Comment by hesingh** [comment]
p4c has been changed to support ```type.size``` in a P4 program.  See a commit in this repo.

https://github.com/hesingh/p4c

What is TODO is to convert the expression to an IR::Constant.  The typeChecker.cpp code does not deal with transforming IR.  Thus, a home is needed in frontend code where the conversion code can be added. 

@mbudiu-vmw Would you know a frontend .cpp file where this TODO code could go in?

**Comment by mbudiu-vmw** [comment]
Either constantFolding.cpp or typeChecker.cpp

**Comment by hesingh** [comment]
> Either constantFolding.cpp or typeChecker.cpp

thanks!

**Comment by hesingh** [comment]
Prototyped code for type.size() has pinged.  I will look into concatenated type.size() next and make sure that code works.  

Log is included below.
```
hemant@ubuntu:~/int/p4c/build$ ./p4test --std p4-16 ../testdata/p4_16_samples/v1model-special-ops-bmv2.p4
sizeBits: 112
sizeBytes: 14
hemant@ubuntu:~/int/p4c/build$
```
P4 code used:
```
state parse_ethernet {
        packet.extract(hdr.ethernet);
        len = hdr.ethernet.sizeBits();     <===
        len = hdr.ethernet.sizeBytes();  <===
        transition select(hdr.ethernet.etherType) {
            ETHERTYPE_IPV4: parse_ipv4;
            default: accept;
        }
}
```

**Comment by hesingh** [comment]
I fixed a bug in the code to support multiple sizeof computation with the arithmetic Add operator.   This was the P4 program used to test. 

```
len = hdr.ethernet.sizeBits() + hdr.ethernet.sizeBits();
len = hdr.ethernet.sizeBytes() + hdr.ethernet.sizeBytes();
```

**Comment by hesingh** [comment]
I added nested struct inside header test and testing passed.  Few tests were added and 'make check' passed for p4c.  Thus, I have issued a code review PR.

https://github.com/p4lang/p4c/pull/1720
