### ISSUE TITLE
make check fails

### ISSUE THREAD

**Issue by maharishib** [p4lang/p4c#1721]
make is 100% complete
make check fails for ebpf and xdp
LogTest.log is attached
[LastTest.log](https://github.com/p4lang/p4c/files/2846495/LastTest.log)

**Comment by hesingh** [comment]
EBPF has dependencies which are listed at this URL:

https://github.com/p4lang/p4c/blob/master/backends/ebpf/README.md

Install the software below and 'make check' will pass.

```
$ sudo apt-get install clang llvm libpcap-dev libelf-dev iproute2 net-tools
$ sudo pip install pyroute2 ply scapy==2.4.0
```

**Comment by maharishib** [comment]
I tried, but same errors

**Comment by hesingh** [comment]
Please email p4-dev with this issue and see if others can reply.  I have seen Issues filed in the past when make check fails for EBPF.  p4c did fix some failures, but all failures may not have been fixed.

**Comment by hesingh** [comment]
See https://github.com/p4lang/p4c/issues/1376

**Comment by mbudiu-vmw** [comment]
Some of the errors in your log are related to the xdp extension, which is not part of this project.
Can you first try to compile without that extension?
Just delete the symlink from the extensions folder.
Second, when you install the extension, can you make sure you follow the instructions from the p4c-xdp project web page?

**Comment by maharishib** [comment]
Solved this problem by first removing /usr/include/linux/bpf.h and then creating a soft link /usr/include/linux/bpf.h which points to /usr/src/linux-headers-`uname -r`/include/uapi/linux/
