### ISSUE TITLE
Corner case handling in strength reduction

### ISSUE THREAD

**Issue by ChrisDodd** [p4lang/p4c#1724]
This trivial program fragment

    action test(inout bit<16> a, inout bit<2> b) {
        b = (a << 3)[1:0];
    }

gives the error "[--Werror=type-error] error: -2: negative bit index" (with no line number or context information!) when run with p4test.  There are probably other such untested corner cases in strength reducing various combinations of things; I've also seen cases where a single pass of StrengthReduction doesn;t get everything, but repeating it does.

The lack of an error message with any location info is also a quality problem

**Comment by hesingh** [comment]
Recently, I was dealing with a getType() failure in typeChecker.cpp which has a zillion getType()'s.  It would be good to deal with such issues as well to define who the caller to getType() was.  Linux supports backtrace().
