### ISSUE TITLE
Frontend does not validate `@match` annotation

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#1732]
The `@match` annotation is defined in the "Select Expressions" section of the spec. IMO, the frontend should complain if `@match` is not used as intended. The annotation's expression list should include a single path expression corresponding to a match kind. p4test currently compiles the following program without complaining:
```
#include <v1model.p4>

header Hdr {
    bit<32> fA;
    bit<16> fB;
}
struct H {
    Hdr h;
};
struct M { }

struct pvs_t {
    @match(ternary) bit<32> f32;
    @match(1+1) bit<16> f16;
}

parser ParserI(packet_in pk, out H hdr, inout M meta, inout standard_metadata_t smeta) {
    value_set<pvs_t>(16) pvs;
    state start { pk.extract(hdr.h); transition select(hdr.h.fA, hdr.h.fB) {
        pvs: accept;
        _: reject;
    } }
}

action empty() { }

control IngressI(inout H hdr, inout M meta, inout standard_metadata_t smeta) {
    apply { smeta.egress_spec = smeta.ingress_port; }
};

control EgressI(inout H hdr, inout M meta, inout standard_metadata_t smeta) {
    apply { }
};

control DeparserI(packet_out pk, in H hdr) {
    apply { }
}

control VerifyChecksumI(inout H hdr, inout M meta) {
    apply { }
}

control ComputeChecksumI(inout H hdr, inout M meta) {
    apply { }
}

V1Switch(ParserI(), VerifyChecksumI(), IngressI(), EgressI(),
         ComputeChecksumI(), DeparserI()) main;
```

**Comment by hesingh** [comment]
The P4-16 latest doc says, if a match is not exact, 

"A single non-exact field must be placed into a struct by itself, with the desired @match annotation."

In the example of this Issue, the struct has two fields which is not correct.  p4c has to, first, complain that match is ternary but the struct has more than one field.

**Comment by antoninbas** [comment]
I think are misunderstanding the spec. The spec is saying that if you want to do a non-exact match on a single field, you have to wrap it in a struct. On the other hand to do an exact match on a single field, you don't have to define a struct, you can just use `value_set<bit<W> >`.

**Comment by hesingh** [comment]
I agree with you regarding non-exact match on a single field.  Having read the section one more time, I think the spec is saying a struct is allowed with multiple fields of different match types.  If that is so, the struct in your example is valid because:

1. It has two fields - multiple fields are allowed.
2. A ```@match``` type is allowed for each field of a struct and the types can be different for each member. 

I am not sure what the specific problem p4c is supposed to catch and fail.

**Comment by antoninbas** [comment]
`1 + 1` is not a match kind element, it's an arbitrary expression
I shouldn't be able to use `@match(1+1)` for the same reason I am not able to define a table like this:
```
table t {
    key { hdr.ipv4.dstAddr : 1 + 1; }
    //...
}
```

**Comment by hesingh** [comment]
This is what even I thought.  So now the question is "if a struct has multiple fields, do all fields have to be the same type?"

**Comment by hesingh** [comment]
We should fix p4c to check if a value set is using a struct, then check if the struct has any bogus ```@match``` annotation.
