### ISSUE TITLE
Fix P4Runtime to support new psa.p4

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#1734]
With new psa.p4 added by this PR <https://github.com/p4lang/p4c/pull/1730> 'make check' fails for four PSA related tests.  Having debugged one test, the problem is due to incomplete P4Runtime code.

```
hemant@ubuntu:~/int/p4c/build$ p4/testdata/p4_16_samples/p4rt_digest_complex.p4.test -v
Writing temporary files into  ./tmpIJMgd8
./p4test /home/hemant/int/p4c/testdata/p4_16_samples/p4rt_digest_complex.p4
./p4test --pp ./tmpIJMgd8/p4rt_digest_complex.p4 --dump ./tmpIJMgd8 --top4 FrontEndLast,FrontEndDump,MidEndLast --testJson --arch psa --p4runtime-files ./tmpIJMgd8/p4rt_digest_complex.p4.p4info.txt /home/hemant/int/p4c/testdata/p4_16_samples/p4rt_digest_complex.p4
Exit code  134
Error compiling
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  In file: /home/hemant/int/p4c/control-plane/typeSpecConverter.cpp:107
Compiler Bug: /home/hemant/int/p4c/testdata/p4_16_samples/p4rt_digest_complex.p4(65): Unexpected named type PortId_t
    PortId_t port;
    ^^^^^^^^
```
The following diffs fix the issue.

```
diff --git a/control-plane/typeSpecConverter.cpp b/control-plane/typeSpecConverter.cpp
index 349d641c..7b69c90a 100644
--- a/control-plane/typeSpecConverter.cpp
+++ b/control-plane/typeSpecConverter.cpp
@@ -103,6 +103,16 @@ bool TypeSpecConverter::preorder(const IR::Type_Name* type) {
         CHECK_NULL(typeSpec);
         map.emplace(type, typeSpec);
         return false;
+    } else if (decl->is<IR::Type_Newtype>()) {
+        // Type_Name nodes for NewType are only replaced in the midend, not the
+        // frontend, but the P4Info generation happens after the frontend, so we
+        // have to handle this case.
+        auto newType = decl->to<IR::Type_Newtype>()->type;
+        visit(newType);
+        typeSpec = map.at(newType);
+        CHECK_NULL(typeSpec);
+        map.emplace(type, typeSpec);
+        return false;
     } else {
         BUG("Unexpected named type %1%", type);
     }
```

**Comment by jafingerhut** [comment]
Hemant, I tested your diff, and it does seem to give better results for the test you tried, for me as well.

I believe the PortId_t type name should appear in the P4Info file generated in some way, but from a quick look I do not recall exactly what the recommended way to represent it in that file is.  The P4Runtime server needs to know which values have type PortId_t so it can do runtime numeric translation of values between the controller and the device.

**Comment by hesingh** [comment]
Let me test how the old typedef shows up in P4Info file and then figure out what needs to be done for the new PortId_t type.  Thanks for testing.

**Comment by jafingerhut** [comment]
Here is an issue I created a while back that might have some correct details: https://github.com/p4lang/p4c/issues/1461

**Comment by jafingerhut** [comment]
Minor detail comment: `typedef` should not affect the P4Info file produced at all.  Only `type` should.

**Comment by hesingh** [comment]
ok, thanks for both the notes.  Will take a look.

**Comment by hesingh** [comment]
I have fixed p4c p4runtimeSerializer.cpp to support an Action with "type PortId_t..." for parameter.  Code is checked in to this repo:

https://github.com/hesingh/p4c-p4runtime-psa

Now the last-known pending problem is all three tests failing in typeUnification.  I think, when Type_Newtype was added to p4c, the new psa.p4 using "type PortIdUint_t         PortId_t;" is not supported because this is the failure:

```
./tmpxkERb1/psa-example-register2-bmv2-midend.p4(74): [--Werror=legacy] error: AssignmentStatement: Cannot unify bit<32> to PortId_t
        ostd.egress_port = 32w0;
                         ^
/tmp/int/p4c-p4runtime-psa/build/backends/p4test/p4include/psa.p4(78)
type PortIdUint_t PortId_t;
                  ^^^^^^^^
Exit code  1
Removing ./tmpxkERb1
hemant@ubuntu:/tmp/int/p4c-p4runtime-psa/build$ 
```

**Comment by hesingh** [comment]
I could get most of the way there for changes to typeUnification.cpp, but due to lack of typeMap in this file, I cannot complete the code.  However, I put in a temporary fix and rest of the three failing tests passed.  Code has been checked in to the repo.  

I think typeChecker or typeSubstitution are next to look at to change the Type_Newtype to its final form before typeUnification operates.

**Comment by hesingh** [comment]
The final fix has been checked into the repo and all testing has passed including the 4 failing psa tests.

https://github.com/p4lang/p4c

I have to wrestle with a PR because the repo above is not a fork.

**Comment by jafingerhut** [comment]
@hesingh Were you aware that you can have a single forked repository on Github, and create many PRs from that one repository, as long as you create each of them on a non-master branch when creating the PR?  There is no need to have multiple forks to create multiple concurrent PRs.

The management of such branches can get a little confusing after you have a dozen of them or so, but every PR gives the name of the branch from which it was created, which I often refer to if I forget which branch name I used.

I will try out your proposed changes soon to see what happens.

**Comment by hesingh** [comment]
Ah, yes - thanks.   I do have one fork from p4c which has a PR out for sizeof code changes.  Unfortunately, I created another branch for the psa fixes which is not from the fork.  Anyway, I am sending out a PR soon since I have a second github account that allowed me to pull a fork from p4c.

**Comment by hesingh** [comment]
New PR is out.

https://github.com/p4lang/p4c/pull/1736

thanks.
