### ISSUE TITLE
p4test gives error for table key with `type` type

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1739]
The attached program p416-type-use1.p4 gives an error even when one attempts to compile it using `p4test`, e.g.:
```
$ p4test p416-type-use1.p4
p416-type-use1.p4(99): [--Werror=type-error] error: Key hdr.ipv4.dstAddr field type must be a scalar type; it cannot be IPv4AddressUint_t
            hdr.ipv4.dstAddr: lpm;
            ^^^^^^^^^^^^^^^^
p416-type-use1.p4(110): [--Werror=type-error] error: Key hdr.ipv4.srcAddr field type must be a scalar type; it cannot be IPv4Address_t
            hdr.ipv4.srcAddr : ternary;
            ^^^^^^^^^^^^^^^^
```
This is the result with the latest version of p4c source as of 2019-Feb-18:
```
$ git log -n 1 | cat
commit 6b761be48da3b1f1c19b6c9f6d911b378ead5bb6
Author: Han Wang <hanw@users.noreply.github.com>
Date:   Mon Feb 18 07:21:06 2019 -0800
```

I can understand if a P4_16 architecture rejects table search keys that do not have one of a restricted set of types, but it seems odd that p4test does.

p4c-bm2-ss also fails with the same errors.  Here it seems plausible that the desired behavior is to allow this, if the underlying type of the `type` of the key fields is `bit<W>` or `int<W>`, which it is in this case.

Tried this example while looking into support for PSA in p4c-bm2-psa.  If architecture-independent parts of p4c reject such programs, is there a straightforward way for a particular architecture to override that?

[p416-type-use1.p4.txt](https://github.com/p4lang/p4c/files/2877537/p416-type-use1.p4.txt)

**Comment by jafingerhut** [comment]
Note that if you delete all of the tables and their apply statements so that ingress and egress are both empty, as in the attached program p416-type-use0.p4, the rest of this code compiles with p4test _and_ p4c-bm2-ss, and p4c-bm2-ss produces a BMv2 JSON file that has the ethernet and IPv4 addresses in the headers replaced with `bit<48>` or `bit<32>` types as appropriate, with no errors.

Thus it seems that there are parts of p4c that reject these user-defined types, and others that allow them.

[p416-type-use0.p4.txt](https://github.com/p4lang/p4c/files/2877551/p416-type-use0.p4.txt)

**Comment by jafingerhut** [comment]
If it is decided that p4test and/or p4c-bm2-ss are both changed to allow these programs (I hope so), then note that they should preserve in the compiler's IR the original user-defined `type`s on these fields until after the point where the P4Runtime p4info files are generated.  The p4info file generation must preserve these types.

**Comment by hesingh** [comment]
Agree with Andy.  For another switching asic my company developed p4c for, the architecture supported such a program in 2017 as well as nested structs.

**Comment by hesingh** [comment]
Thanks for finding this bug in the p4c code.  Here is the fix.  

Unfortunately, I have used two forked repos to make changes and issue a PR rather than leaving the fork untouched and creating new non-master branches under the fork.  Thus, I cannot issue a PR.  I already used my 2nd and last github account to issue a 2nd PR.  Please send out a PR.

```
diff --git a/frontends/p4/typeChecking/typeChecker.cpp b/frontends/p4/typeChecking/typeChecker.cpp
index 9d959ba6..d6341dc4 100644
--- a/frontends/p4/typeChecking/typeChecker.cpp
+++ b/frontends/p4/typeChecking/typeChecker.cpp
@@ -3258,7 +3258,8 @@ const IR::Node* TypeInference::postorder(IR::KeyElement* elem) {
     while (ktype->is<IR::Type_Newtype>())
         ktype = ktype->to<IR::Type_Newtype>()->type;
     if (!ktype->is<IR::Type_Bits>() && !ktype->is<IR::Type_Enum>() &&
-        !ktype->is<IR::Type_Error>() && !ktype->is<IR::Type_Boolean>())
+        !ktype->is<IR::Type_Error>() && !ktype->is<IR::Type_Boolean>() &&
+        !ktype->is<IR::Type_Name>())
         typeError("Key %1% field type must be a scalar type; it cannot be %2%",
                   elem->expression, ktype->toString());
     auto type = getType(elem->matchType);
```

**Comment by hesingh** [comment]
Or I can include the change in the existing PR which fixes p4c for PSA 1.1 tests.

**Comment by jafingerhut** [comment]
Hemant, thanks for taking a look at this.

However, is it possible your proposed change allows things that maybe should not be?

For example, suppose someone did this:

```
type ipv4_t myCustomIPv4Header_t;
```
where `ipv4_t` was a header type.   _If_ there are good reasons to disallow matching on a header type (I think there might be, since I do not know what the semantics should be for matching a full header value as a table search key), then the compiler should also reject a user-defined `type` whose underlying type is a header, shouldn't it?

**Comment by jafingerhut** [comment]
In other words, if there truly is some list of allowable types in a particular place in a P4_16 program, and we want to generalize it to allow user-defined `type` types, then it seems to me that the compiler should look for the definition of that user-defined `type`, find the underlying type, and then check that underlying type against the list of types allowed at that point (in the code you showed above, that looks like Bits, Error, Enum, and Boolean only right now).

Note that while I would not expect it to be common, a user can also "stack" their user-defined types, like this:

```
type ipv4_t myCustomIPv4Header_t;
type myCustomIPv4Header_t myCustomIPv4Header2_t;
type myCustomIPv4Header2_t myCustomIPv4Header3_t;
```

and then use a value of type `myCustomIPv4Header3_t` as a table search key field.

**Comment by hesingh** [comment]
Andy, Yes, one has to check what is the type for Type_Name.  I do have such a check in my changes to typeUnification.cpp in the PR to fix PSA 1.1 issues.   Here is the new code - one can add more checks for what to block.

```
diff --git a/frontends/p4/typeChecking/typeChecker.cpp b/frontends/p4/typeChecking/typeChecker.cpp
index 9d959ba6..e0b849ad 100644
--- a/frontends/p4/typeChecking/typeChecker.cpp
+++ b/frontends/p4/typeChecking/typeChecker.cpp
@@ -3255,10 +3255,18 @@ const IR::Node* TypeInference::postorder(IR::KeyElement* elem) {
     auto ktype = getType(elem->expression);
     if (ktype == nullptr)
         return elem;
+    if (ktype->is<IR::Type_Newtype>()) {
+        auto p4 = ktype->getP4Type();
+        if (p4->is<IR::Type_Struct>() || p4->is<IR::Type_Struct>()) {
+            typeError("Key failed: %1%", p4);
+            return elem;
+        }
+    }
     while (ktype->is<IR::Type_Newtype>())
         ktype = ktype->to<IR::Type_Newtype>()->type;
     if (!ktype->is<IR::Type_Bits>() && !ktype->is<IR::Type_Enum>() &&
-        !ktype->is<IR::Type_Error>() && !ktype->is<IR::Type_Boolean>())
+        !ktype->is<IR::Type_Error>() && !ktype->is<IR::Type_Boolean>() &&
+        !ktype->is<IR::Type_Name>())
         typeError("Key %1% field type must be a scalar type; it cannot be %2%",
                   elem->expression, ktype->toString());
     auto type = getType(elem->matchType);
```

**Comment by jafingerhut** [comment]
Attached is another test program that tries more combinations of typedef and type applied to earlier typedef and type, stacked up to 3 deep, just to see if it flushes out anything else.
[p416-type-use3.p4.txt](https://github.com/p4lang/p4c/files/2877889/p416-type-use3.p4.txt)

**Comment by hesingh** [comment]
thanks.  The typeChecker p4c code does use a while loop to get to the deepest type.  Thus, at least this code will be fine.

**Comment by hesingh** [comment]
It is tricky to check specific type from Type_Name to make sure a header or struct does not slip through for a table key.  All other issues work fine.  

(a) Adding a !Type_Name check does not block the type.
(b) Howsoever deeply typed data is, the code has no problem.

**Comment by jafingerhut** [comment]
I tried a small test program that did `type h1_t H1T_t;` where `h1_t` is a header type, and the compiler does not allow that, giving an error like this:
```
p416-type-use4.p4(61): error: H1T_t: `type' can only be applied to base types or tuple types
type h1_t H1T_t;
          ^^^^^
```
and it gives the same error message if I replace h1_t with the name of a struct type.  That cuts down the cases to check for fairly significantly.
so that seems to cut down the cases

**Comment by hesingh** [comment]
Cool, thanks! Then augmenting the check by ```&& !ktype->is<IR::Type_Name>()``` would do the trick.  I will still do due diligence and see what are the complete changes because it depends when the error you caught above occurs vs. when the check is made.

**Comment by hesingh** [comment]
Oops, the error you caught is from the same method.   The scope is totally narrowed down.

**Comment by hesingh** [comment]
Update:

The fix has been checked in to the PSA 1.1 PR repo.  p416-type-use3.p4 is checked in as a test to test deep type and psa-type-hdr.p4 to test p4c catching header is not allowed - thanks for test files and testing, Andy.  Code changes were also made to p4c p4runtime API generation to support p416-type-use3.p4  and other PSA 1.1 tests. 

Since the fix changes p4c frontend, the fix is available for any p4c backend.

**Comment by mbudiu-vmw** [comment]
If I understand correctly this is a problem with the control-plane API generation.
Does the P4runtime support such types for table keys?

**Comment by jafingerhut** [comment]
As long as the "bottom most" type is `bit<W>` or `enum bit<W>`, then yes P4Runtime does support types defined via `type` as the types of table search key fields, and also for fields match by a value_set.

See this section of the P4Runtime spec (latest working version, since this was only recently clarified in the P4Runtime spec after v1.0 was published): https://s3-us-west-2.amazonaws.com/p4runtime/docs/master/P4Runtime-Spec.html#sec-known-limitations-of-p4runtime-v100

**Comment by hesingh** [comment]
See Andy's test log at the top of this Issue and see it's not a  control-plane API generation issue.  He just runs `p4test p416-type-use1.p4`.  The test program uses new psa.p4 due to PSA 1.1 and use `type`.   Thus, this error is seen.  After the while loop the type found is Type_Name.

**Comment by mbudiu-vmw** [comment]
So when you emit information about a key whose type is a `type` what do you write in the P4info file? The name of the type or the base type that it represents?

**Comment by hesingh** [comment]
PortId_t, viz., name of the type.

**Comment by jafingerhut** [comment]
I have a proposal of what should happen in all cases written up here, but I would not treat it as 'draft' status until Antonin and/or a few other P4Runtime experts have had a chance to review it: https://github.com/jafingerhut/p4-guide/blob/master/p4runtime/README-p4info-and-type.md#proposed-p4c-rules-for-generating-types-in-p4info-files

**Comment by jafingerhut** [comment]
But I think the shorter answer to that question is that the `type_name` should always be the first `type` name reached while traversing the list of `typedef` and `type` names toward the base type.

**Comment by hesingh** [comment]
Yes, Andy.
