### ISSUE TITLE
CMake Error: Cannot determine link language for target "gtest".

### ISSUE THREAD

**Issue by abhisavadiya** [p4lang/p4c#1740]
fatal: Not a git repository (or any of the parent directories): .git
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   iostreams
--   regex
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Program 'simple_switch_CLI' (https://github.com/p4lang/behavioral-model.git) not found;
Searched .
Will not run BMv2 tests. (missing:  SIMPLE_SWITCH SIMPLE_SWITCH_CLI) 
-- Program 'psa_switch_CLI' (https://github.com/p4lang/behavioral-model.git) not found;
Searched .
Will not run PSA BMv2 tests. (missing:  PSA_SWITCH PSA_SWITCH_CLI) 
-- Using the GNU gold linker.
-- Available extensions 
CMake Warning at backends/bmv2/CMakeLists.txt:190 (MESSAGE):
  BMv2 simple switch is not available, not adding v1model BMv2 tests

CMake Warning at backends/bmv2/CMakeLists.txt:196 (MESSAGE):
  BMv2 PSA switch is not available, not adding PSA BMv2 tests

-- Added 160 tests to 'p4' (0 xfails)
-- Added 492 tests to 'p4' (5 xfails)
-- Added 203 tests to 'p14_to_16' (0 xfails)
-- CTest parallel: -j 1
-- Configuring done
CMake Error at test/CMakeLists.txt:34 (add_library):
  Cannot find source file:

    /home/p4/Desktop/p4c-master/test/frameworks/gtest/googletest/src/gtest-all.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: Cannot determine link language for target "gtest".
CMake Error: CMake can not determine linker language for target: gtest
-- Generating done
-- Build files have been written to: /home/p4/Desktop/p4c-master/build

**Comment by antoninbas** [comment]
Did you run `git submodule update --init --recursive` like the README asks you to (https://github.com/p4lang/p4c#getting-started)?

**Comment by abhisavadiya** [comment]
It's not working @antoninbas

**Comment by abhisavadiya** [comment]
https://github.com/iat-cener/tonatiuh/wiki/Installing-Google-Test-For-Linux

**Comment by jafingerhut** [comment]
@abhisavadiya Starting from a freshly installed Ubuntu 16.04 or Ubuntu 18.04 Linux system, I have a bash script which I have successfully used _many_ times to install p4c and behavioral-model from source code.

There are two variants, depending upon whether you want P4Runtime code installed or not:
+ https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev.sh - install p4c, behavioral-model, and the software they depend upon.  No P4Runtime code installed
+ https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-p4runtime.sh - install all of the above plus P4Runtime

Troubleshooting tips for those scripts available here: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

**Comment by antoninbas** [comment]
> for solve error clone this repo,
> https://github.com/iat-cener/tonatiuh/wiki/Installing-Google-Test-For-Linux

I don't want people to believe that this is required. There is no need to install Google Test separately, it comes as a submodule with this repo (see under https://github.com/p4lang/p4c/tree/master/test/frameworks).

Maybe you downloaded the project as a zip archive directly from Github, in which case what you get is not a git clone and you cannot pull in submodules (and in particular Google Test). The recommended way to build this project starts with cloning it.
