### ISSUE TITLE
Compile failed: Local header variable cannot be stacked

### ISSUE THREAD

**Issue by samuel-larsson** [p4lang/p4c#1743]
I'm using P4 16 using the v1model. When I have added a header stack `nc_value_t[8] nc_value;` to my header struct, I get the following build error:

> Build error during Generate PIF step:
Compile failed: Local header variable parser::nc_value cannot be stacked

My header looks like this:

```
header nc_value_t {
    bit<32> value_1;
    bit<32> value_2;
    bit<32> value_3;
    bit<32> value_4;
    bit bos;
}

struct headers {
    ...
    nc_value_t[8] nc_value;
}
```

The build error refers to this parser snippet:
```
state parse_value {
    packet.extract(hdr.nc_value.next);
    transition select(hdr.nc_value.last.bos) {
        0: parse_value;
        _: accept;
    }
}
```

I've been trying to mess around with how the header is passed to the parser as I can't find anything online on this problem, but as soon as the header is passed into any parser, I get the build error when trying to compile.

**Comment by hesingh** [comment]
Could you please include the full P4 program so that we can try it and get back.

**Comment by jafingerhut** [comment]
And also which command you are using to try to compile the program.  I do not see "PIF" in any of the error messages that the p4c compiler source code can possibly print, so I suspect you may be using a P4 compiler that is not p4c.

**Comment by samuel-larsson** [comment]
@jafingerhut I'm compiling using the Netronome Developer Studio, which uses p4c. But generating the pif could be subsequent to the p4c compilation, even though it says "compile failed".

**Comment by jafingerhut** [comment]
I would recommend contacting Netronome support about this issue, as I doubt very much that the cause is in the p4c portion of their compiler.

**Comment by samuel-larsson** [comment]
Okay, I'll do that and close the issue. Thanks for your help!
