### ISSUE TITLE
p4c make fails

### ISSUE THREAD

**Issue by maharishib** [p4lang/p4c#1746]
I have libprotoc 3.7.0 installed

[ 37%] Building CXX object control-plane/CMakeFiles/controlplane.dir/google/rpc/status.pb.cc.o
In file included from /home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:5:0:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
In file included from /home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:5:0:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.h:101:30: error: ‘google::protobuf::uint8* google::rpc::Status::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’ marked ‘final’, but is not virtual
   ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
                              ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:36:56: error: expected primary-expression before ‘,’ token
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Status, _internal_metadata_),
                                                        ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:36:58: error: ‘_internal_metadata_’ was not declared in this scope
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Status, _internal_metadata_),
                                                          ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:36:77: error: ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’ was not declared in this scope
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Status, _internal_metadata_),
                                                                             ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:39:56: error: expected primary-expression before ‘,’ token
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Status, code_),
                                                        ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:39:58: error: ‘code_’ was not declared in this scope
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Status, code_),
                                                          ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:39:63: error: ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’ was not declared in this scope
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Status, code_),
                                                               ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:40:56: error: expected primary-expression before ‘,’ token
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Status, message_),
                                                        ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:40:58: error: ‘message_’ was not declared in this scope
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Status, message_),
                                                          ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:40:66: error: ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’ was not declared in this scope
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Status, message_),
                                                                  ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:41:56: error: expected primary-expression before ‘,’ token
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Status, details_),
                                                        ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:41:58: error: ‘details_’ was not declared in this scope
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Status, details_),
                                                          ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:41:66: error: ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’ was not declared in this scope
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Status, details_),
                                                                  ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc: In function ‘void google::rpc::protobuf_google_2frpc_2fstatus_2eproto::{anonymous}::protobuf_AssignDescriptors()’:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:59:38: error: cannot convert ‘const char*’ to ‘google::protobuf::internal::AssignDescriptorsTable*’ for argument ‘1’ to ‘void google::protobuf::internal::AssignDescriptors(google::protobuf::internal::AssignDescriptorsTable*)’
       file_level_metadata, NULL, NULL);
                                      ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc: In function ‘void google::rpc::protobuf_google_2frpc_2fstatus_2eproto::{anonymous}::protobuf_AssignDescriptorsOnce()’:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:63:43: error: ISO C++ forbids declaration of ‘GOOGLE_PROTOBUF_DECLARE_ONCE’ with no type [-fpermissive]
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
                                           ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:63:39: error: ‘once’ was not declared in this scope
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
                                       ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:64:3: error: ‘GoogleOnceInit’ is not a member of ‘google::protobuf’
   ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
   ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:63:10: warning: unused variable ‘GOOGLE_PROTOBUF_DECLARE_ONCE’ [-Wunused-variable]
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
          ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc: At global scope:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:67:51: error: expected initializer before ‘GOOGLE_ATTRIBUTE_COLD’
 void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
                                                   ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc: In function ‘void google::rpc::protobuf_google_2frpc_2fstatus_2eproto::{anonymous}::protobuf_RegisterTypes(const string&)’:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:70:3: error: ‘RegisterAllTypes’ is not a member of ‘google::protobuf::internal’
   ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
   ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc: In static member function ‘static void google::rpc::protobuf_google_2frpc_2fstatus_2eproto::TableStruct::Shutdown()’:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:76:29: error: ‘class google::rpc::StatusDefaultTypeInternal’ has no member named ‘Shutdown’
   _Status_default_instance_.Shutdown();
                             ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc: In static member function ‘static void google::rpc::protobuf_google_2frpc_2fstatus_2eproto::TableStruct::InitDefaultsImpl()’:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:84:23: error: ‘google::protobuf::protobuf_google_2fprotobuf_2fany_2eproto’ has not been declared
   ::google::protobuf::protobuf_google_2fprotobuf_2fany_2eproto::InitDefaults();
                       ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc: In function ‘void google::rpc::protobuf_google_2frpc_2fstatus_2eproto::InitDefaults()’:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:89:43: error: ISO C++ forbids declaration of ‘GOOGLE_PROTOBUF_DECLARE_ONCE’ with no type [-fpermissive]
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
                                           ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:89:39: error: ‘once’ was not declared in this scope
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
                                       ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:90:3: error: ‘GoogleOnceInit’ is not a member of ‘google::protobuf’
   ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
   ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:89:10: warning: unused variable ‘GOOGLE_PROTOBUF_DECLARE_ONCE’ [-Wunused-variable]
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
          ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc: In function ‘void google::rpc::protobuf_google_2frpc_2fstatus_2eproto::AddDescriptorsImpl()’:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:104:55: error: invalid conversion from ‘void (*)(const string&) {aka void (*)(const std::__cxx11::basic_string<char>&)}’ to ‘void*’ [-fpermissive]
     "google/rpc/status.proto", &protobuf_RegisterTypes);
                                                       ^
In file included from /home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.h:27:0,
                 from /home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:5:
/usr/local/include/google/protobuf/message.h:1115:15: note:   initializing argument 2 of ‘static void google::protobuf::MessageFactory::InternalRegisterGeneratedFile(const char*, void*)’
   static void InternalRegisterGeneratedFile(const char* filename,
               ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:105:23: error: ‘google::protobuf::protobuf_google_2fprotobuf_2fany_2eproto’ has not been declared
   ::google::protobuf::protobuf_google_2fprotobuf_2fany_2eproto::AddDescriptors();
                       ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc: In function ‘void google::rpc::protobuf_google_2frpc_2fstatus_2eproto::AddDescriptors()’:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:110:43: error: ISO C++ forbids declaration of ‘GOOGLE_PROTOBUF_DECLARE_ONCE’ with no type [-fpermissive]
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
                                           ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:110:39: error: ‘once’ was not declared in this scope
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
                                       ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:111:3: error: ‘GoogleOnceInit’ is not a member of ‘google::protobuf’
   ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
   ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:110:10: warning: unused variable ‘GOOGLE_PROTOBUF_DECLARE_ONCE’ [-Wunused-variable]
   static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
          ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc: In constructor ‘google::rpc::Status::Status()’:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:133:62: error: ‘GOOGLE_PREDICT_TRUE’ was not declared in this scope
   if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
                                                              ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc: In member function ‘virtual void google::rpc::Status::SetCachedSize(int) const’:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:169:39: error: ‘GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN’ was not declared in this scope
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
                                       ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:171:37: error: ‘GOOGLE_SAFE_CONCURRENT_WRITES_END’ was not declared in this scope
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
                                     ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc: In member function ‘virtual bool google::rpc::Status::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)’:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:200:60: error: ‘GOOGLE_PREDICT_TRUE’ was not declared in this scope
 #define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
                                                            ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:212:11: note: in expansion of macro ‘DO_’
           DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
           ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:200:60: error: ‘GOOGLE_PREDICT_TRUE’ was not declared in this scope
 #define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
                                                            ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:224:11: note: in expansion of macro ‘DO_’
           DO_(::google::protobuf::internal::WireFormatLite::ReadString(
           ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:200:60: error: ‘GOOGLE_PREDICT_TRUE’ was not declared in this scope
 #define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
                                                            ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:226:11: note: in expansion of macro ‘DO_’
           DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
           ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:200:60: error: ‘GOOGLE_PREDICT_TRUE’ was not declared in this scope
 #define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
                                                            ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:239:11: note: in expansion of macro ‘DO_’
           DO_(input->IncrementRecursionDepth());
           ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:240:15: error: ‘ReadMessageNoVirtualNoRecursionDepth’ is not a member of ‘google::protobuf::internal::WireFormatLite’
           DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursio
               ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:200:50: note: in definition of macro ‘DO_’
 #define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
                                                  ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:200:60: error: ‘GOOGLE_PREDICT_TRUE’ was not declared in this scope
 #define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
                                                            ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:240:11: note: in expansion of macro ‘DO_’
           DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursio
           ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:200:60: error: ‘GOOGLE_PREDICT_TRUE’ was not declared in this scope
 #define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
                                                            ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:256:9: note: in expansion of macro ‘DO_’
         DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
         ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc: In member function ‘google::protobuf::uint8* google::rpc::Status::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:321:43: error: no matching function for call to ‘google::protobuf::internal::WireFormatLite::InternalWriteMessageNoVirtualToArray(int, const google::protobuf::Any&, bool, google::protobuf::uint8*&)’
         3, this->details(i), false, target);
                                           ^
In file included from /usr/local/include/google/protobuf/parse_context.h:39:0,
                 from /usr/local/include/google/protobuf/generated_message_util.h:49,
                 from /home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.h:25,
                 from /home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:5:
/usr/local/include/google/protobuf/wire_format_lite.h:639:21: note: candidate: template<class MessageType> static google::protobuf::uint8* google::protobuf::internal::WireFormatLite::InternalWriteMessageNoVirtualToArray(int, const MessageType_WorkAroundCppLookupDefect&, google::protobuf::uint8*)
   INL static uint8* InternalWriteMessageNoVirtualToArray(
                     ^
/usr/local/include/google/protobuf/wire_format_lite.h:639:21: note:   template argument deduction/substitution failed:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:321:43: note:   candidate expects 3 arguments, 4 provided
         3, this->details(i), false, target);
                                           ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc: In member function ‘virtual size_t google::rpc::Status::ByteSizeLong() const’:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:358:39: error: ‘GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN’ was not declared in this scope
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
                                       ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:360:37: error: ‘GOOGLE_SAFE_CONCURRENT_WRITES_END’ was not declared in this scope
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
                                     ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc: In member function ‘virtual void google::rpc::Status::MergeFrom(const google::protobuf::Message&)’:
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:368:7: error: ‘DynamicCastToGenerated’ is not a member of ‘google::protobuf::internal’
       ::google::protobuf::internal::DynamicCastToGenerated<const Status>(
       ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:368:7: note: suggested alternative:
In file included from /home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.h:27:0,
                 from /home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:5:
/usr/local/include/google/protobuf/message.h:1176:4: note:   ‘google::protobuf::DynamicCastToGenerated’
 T* DynamicCastToGenerated(Message* from) {
    ^
/home/p4client/p4/p4c/build/control-plane/google/rpc/status.pb.cc:368:60: error: expected primary-expression before ‘const’
       ::google::protobuf::internal::DynamicCastToGenerated<const Status>(
                                                            ^
control-plane/CMakeFiles/controlplane.dir/build.make:97: recipe for target 'control-plane/CMakeFiles/controlplane.dir/google/rpc/status.pb.cc.o' failed
make[2]: *** [control-plane/CMakeFiles/controlplane.dir/google/rpc/status.pb.cc.o] Error 1
CMakeFiles/Makefile2:1419: recipe for target 'control-plane/CMakeFiles/controlplane.dir/all' failed
make[1]: *** [control-plane/CMakeFiles/controlplane.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jafingerhut** [comment]
Others besides me may be better at recognizing what install step you may have missed to get the errors you see.  I do not know.

I _do_ know that I have well-tested bash scripts that, starting from a freshly installed Ubuntu Linux 16.04 or 18.04 system, will install p4c, behavioral-model, P4Runtime, and all of the dependencies they require.

+ If you do want P4Runtime support, or do not mind having it installed (recommended if you are not sure): https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-p4runtime.sh
+ If for some reason you do not want P4Runtime support at all: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev.sh

**Comment by hesingh** [comment]
Please read the README.md for p4lang/p4c.  The document recommends using protobuf 3.2.0.   You are using 3.7.0.

It is best to use Andy's install scripts which install from scratch.  First, remove any prootbuf etc.
