### ISSUE TITLE
P4Info generation fails with serializable enum

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1756]
[v1model-digest-containing-ser-enum.p4.txt](https://github.com/p4lang/p4c/files/2923501/v1model-digest-containing-ser-enum.p4.txt)

At least, it does if that serializable enum is a field in a struct used as a digest message.  I have not tried it in other contexts.  Results when attempting to compile the attached v1model arch program using this command with latest p4c as of 2019-Feb-26:
```
$ p4c --target bmv2 --arch v1model v1model-digest-containing-ser-enum.p4 --p4runtime-files v1model-digest-containing-ser-enum.p4.p4info.txt
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  In file: /home/jafinger/p4c/control-plane/typeSpecConverter.cpp:107
Compiler Bug: v1model-digest-containing-ser-enum.p4(60): Unexpected named type MySerEnum1
    MySerEnum1 my_thing;
    ^^^^^^^^^^
```
I saw no such error, and the P4Info file contents looked reasonable, when I remove that serializable enum.  In particular, it seems to be working when digest messages contain fields of a non-serializable enum type, and also type `error`.

**Comment by hesingh** [comment]
This issue has been fixed in the following PR:

https://github.com/p4lang/p4c/pull/1736

Please see my test log below.  I have also attached the generated p4info txt file. 

```
hemant@ubuntu:/tmp/p4c/build$ ./p4c --target bmv2 --arch v1model ../testdata/p4_16_samples/v1model-digest-containing-ser-enum.p4 --p4runtime-files v1model-digest-containing-ser-enum.p4.p4info.txt
hemant@ubuntu:/tmp/p4c/build$ 
```

[v1model-digest-containing-ser-enum.p4.p4info.txt](https://github.com/p4lang/p4c/files/2923546/v1model-digest-containing-ser-enum.p4.p4info.txt)

**Comment by jafingerhut** [comment]
The contents of that p4info file you attached looks correct to me.  Thanks.

**Comment by hesingh** [comment]
Since I added support for serEnum to p4c API generation, I did add a P4 program to test serEnum being used as a table key.  See 

https://github.com/p4lang/p4c/pull/1736/files#diff-0ec73ddf3ed4e90a01854abee77ba349R1

At the URL above, please scroll up a few lines and you will see the test program. 

I just checked in two more tests, viz., `action_param_serenum.p4` to test Param and also your digest test of this issue.

**Comment by hesingh** [comment]
My action_param_serenum.p4 merely uses core.p4 for include and was a small test.   This test did not generate p4info for action param.  So I developed a larger P4 program which includes psa.p4 and then see a failure and closure to the problem.  The changes to the larger program are included below the failure to show what I changed to test.

It cannot be supported because such an argument is not a compile-time constant.

```
hemant@ubuntu:/tmp/p4c/build$ ./p4test --std p4-16 ../testdata/p4_16_samples/psa-example-digest-bmv2.p4 --p4runtime-files tmp.txt
../testdata/p4_16_samples/psa-example-digest-bmv2.p4(177): [--Werror=type-error] error: hdr.type: action argument must be a compile-time constant
        default_action = unknown_source(hdr.type);
                                        ^^^^^^^^
hemant@ubuntu:/tmp/p4c/build$ 
```

```
diff --git a/testdata/p4_16_samples/psa-example-digest-bmv2.p4 b/testdata/p4_16_samples/psa-example-digest-bmv2.p4
index 7236344c..38b9d17a 100644
--- a/testdata/p4_16_samples/psa-example-digest-bmv2.p4
+++ b/testdata/p4_16_samples/psa-example-digest-bmv2.p4
@@ -25,6 +25,16 @@ limitations under the License.
 #include <core.p4>
 #include "psa.p4"
 
+enum bit<16> EthTypes {
+    IPv4 = 0x0800,
+    ARP = 0x0806,
+    RARP = 0x8035,
+    EtherTalk = 0x809B,
+    VLAN = 0x8100,
+    IPX = 0x8137,
+    IPv6 = 0x86DD
+}
+
 typedef bit<48>  EthernetAddress;
 
 header ethernet_t {
@@ -51,6 +61,7 @@ header ipv4_t {
 struct headers {
     ethernet_t       ethernet;
     ipv4_t           ipv4;
+    EthTypes         type;
 }
 
 struct empty_metadata_t {
@@ -153,7 +164,7 @@ control ingress(inout headers hdr,
                 in    psa_ingress_input_metadata_t  istd,
                 inout psa_ingress_output_metadata_t ostd)
 {
-    action unknown_source () {
+    action unknown_source (EthTypes type) {
         meta.send_mac_learn_msg = true;
         meta.mac_learn_msg.srcAddr = hdr.ethernet.srcAddr;
         meta.mac_learn_msg.ingress_port = istd.ingress_port;
@@ -163,7 +174,7 @@ control ingress(inout headers hdr,
     table learned_sources {
         key = { hdr.ethernet.srcAddr : exact; }
         actions = { NoAction; unknown_source; }
-        default_action = unknown_source();
+        default_action = unknown_source(hdr.type);
     }
 
     action do_L2_forward (PortId_t egress_port) {

```

**Comment by jafingerhut** [comment]
I believe all action parameters for an action specified as a default_action must be compile time constants, even if they are type `bit<W>`.  Try making it _not_ a default_action, but just a regular action, e.g. try removing the `default_action` property for the table.

**Comment by hesingh** [comment]
Ah, ha, got it - thanks much, Andy!  Now, I am moving further and changing p4c API generation serialization code to get this working.

**Comment by hesingh** [comment]
Done.  Checked in the code to support an Action param to be a serEnum.  

Please see the p4info generated at this URL.

https://github.com/p4lang/p4c/pull/1736/commits/dd34272eb213c6bdd1f59f2361526718b510b49b#diff-c1ece0ecdb01edc016d630bba378428eL104

**Comment by hesingh** [comment]
All but one item to support for serEnum from Antonin's comments below are working now.

https://github.com/p4lang/p4-spec/pull/739#discussion_r260033932

The one I am not sure about is "controller packet metadata fields" and how to test it because it could be data the p4runtime controller maintains.

**Comment by jafingerhut** [comment]
See this example program: https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples/psa-portid-using-newtype2.p4

Despite having 'psa' in its name, it appears to be using the v1model architecture.  It uses a `type` definition for PortIdInHeader_t that is used inside of a header with an annotation of @controller_header, I believe with the same syntax proposed for this in the P4Runtime spec, Section 6.4.6 linked here: https://s3-us-west-2.amazonaws.com/p4runtime/docs/master/P4Runtime-Spec.html#sec-controller-packet-meta

**Comment by hesingh** [comment]
Ah, ha, it's the good old @controller_header annotation for packet_in/packet_out.  Thanks for the copious details!  I will look into testing this next - probably by tomorrow.

**Comment by hesingh** [comment]
This p4 program uses a new annotation vs. the @p4runtime_translation used in pas.p4.  

```
@p4runtime_translate("port")
type bit<32> PortIdInHeader_t;
```
If the annotation above needs to be parsed and have its `PortIdInHeader_t` be used as type_name, then more code changes are needed.  I checked in code to unblock processing this `type` in the code. 

Additionally, I don't see any .p4info.txt file in testdata/p4_16_samples_outputs/ for this P4 program?

**Comment by jafingerhut** [comment]
Any occurrences of p4runtime_translate are probably my mistake when writing that example code about a year ago, either a pure mistake on my part, or I was guessing at the time what the not-yet-defined annotation name would be.

In any case, that file is the only occurrence of the string "p4runtime_translate" anywhere in the p4c or p4runtime repositories, and if you could correct them, I would appreciate it.

**Comment by hesingh** [comment]
I'd be happy to change the program in my PR.

I will change "p4runtime_translate"  to "p4runtime_translation"

**Comment by hesingh** [comment]
I checked the p4runtime protobuf definitions and realized that a header/struct field does not support type_name.   Thus, the p4runtime_annotation is not even needed in this P4 program because the `type` use is with a field in a header.   I have removed the annotation.

**Comment by hesingh** [comment]
@jafingerhut FYI: In the recent code change for my PSA 1.1 PR, when a serializable enum is a parameter to an Action, the bitwidth of the serializable enum is being calculated as (entries*bit_size).  bit_size is such as 16 when the enum is defined as `enum bit<16> ...`.  

@antoninbas Please see this TODO which you may have the answer to the question.

```
bool TypeSpecConverter::preorder(const IR::Type_SerEnum* type) {
    if (p4RtTypeInfo) {
        auto name = std::string(type->controlPlaneName());
        auto enums = p4RtTypeInfo->mutable_serializable_enums();
        if (enums->find(name) == enums->end()) {
            auto enumTypeSpec = new p4configv1::P4SerializableEnumTypeSpec();
            auto bitTypeSpec = enumTypeSpec->mutable_underlying_type();
            // TODO(hemant): is the bitwidth, the width of the enum such
            // as <bit<16> or should we multiply 16 times number of members
            // in the enum?
```

**Comment by jafingerhut** [comment]
It definitely seems to me like `entries*bit_size` is incorrect, and `bit_size` should be used as the width in bits according to the P4Runtime API.

**Comment by mbudiu-vmw** [comment]
Is this issue still accurate?

**Comment by hesingh** [comment]
The issue has been fixed in the giant PSA11 PR.

**Comment by jafingerhut** [comment]
Meaning this PR, I think: https://github.com/p4lang/p4c/pull/1792

**Comment by hesingh** [comment]
1792 is the correct PR.

**Comment by jafingerhut** [comment]
Closing this issue as PR #1792 that fixes it has been merged, and I have verified that it includes the test program that was attached to this issue.
