### ISSUE TITLE
Add variant of 'expect' to STF with stricter checking

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1762]
Somehow I had missed that the STF 'expect' command means "expect an output packet that begins with the following bytes, but it the test will also pass if the actual output packet contains arbitrary additional bytes"  (it already fails if the actual output packet is shorter than the expected one)

The proposal here is to add a new STF command, with a similar but different name than 'expect', with the semantics of "expect an output packet that is exactly the following bytes, and the test will fail if the actual output packet contains additional bytes".

Except for the name and slightly different semantics, everything else about the new command would be the same.

Possible names for the new STF command:
+ expectstrict
+ expectExact - the only reason I do not recommend this one is that you can still specify wildcard hex nybbles with '*', so the word 'Exact' seems somewhat misleading to me.

I am sure others are possible.  STF files are not written terribly often, so longer names should not be onerous.  I think `expects` as an abbreviation of `expectstrict` would be too similar to `expect` such that people would too often miss the difference when reading an STF file.

**Comment by ChrisDodd** [comment]
Alternately just add it to the pattern that appears in the expect statement -- if it ends with a trailing `$` it must match the end of the packet, not just a prefix.

**Comment by jafingerhut** [comment]
Good suggestion, Chris.  Added proposed PR following that idea here: https://github.com/p4lang/p4c/pull/1763

**Comment by mbudiu-vmw** [comment]
I think we can close this, since we have merged the PR fixing it.
