### ISSUE TITLE
Is there an input queue in ingress port to storage packets arriving at line rate?

### ISSUE THREAD

**Issue by castilhorosa** [p4lang/p4c#1764]
Hi there.

I'm a begginer in P4 and BMv2. As far I know when we resubmit or recirculate a specific packet in bmv2, it will be reinjected at same ingress port that it arrived, right? My question is, what's happen when we resubmit or recirculate a packet in bmv2 but at the same time the same ingress port is receiving another packet? Which one would be parsed first, for example? Is there an input queue at ingress port to storage packets when bmv2 is receiving or parsing a resubmited/recirculated packet? 

Thanks in advance.

**Comment by mbudiu-vmw** [comment]
This question is more suitable for the bmv2 repository https://github.com/p4lang/behavioral-model/issues, this one is for the compiler. But yes, the behavioral model has queues in several places.
The notion of "at the same time" is not well defined, so the answer to your question is "it depends on the timing".

**Comment by castilhorosa** [comment]
I see. That make sense. I just moved the question to the right repository as you mentioned. Thanks anyway.
