### ISSUE TITLE
bmv2 backend does not compile correctly calls to lookahead that ignore their results

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#1768]

**Comment by jafingerhut** [comment]
I am not sure what you have found that triggered creating this issue, but just a quick thought:

Any call to lookahead, like any call to extract, has the possibility of causing the parser to go to an error state, if there are not enough bits remaining in the packet to satisfy the call.  So even if the normal return value of lookahead is not used later, calls to it should technically not be optimized away.

**Comment by mbudiu-vmw** [comment]
yes, that's the bug
