### ISSUE TITLE
Error message from p4test about read-only value that appears incorrect

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1777]
For the attached test program, I get the following error message from the following command, using the latest version of p4c source code as of 2019-Mar-09:
```
$ p4test v1model-register-struct-misleading-error-msg.p4
/home/jafinger/p4c/build/backends/p4test/p4include/v1model.p4(111): error: : Read-only value used for out/inout parameter result
    void read(out T result, in bit<32> index);
                    ^^^^^^
```
The corresponding register read operation that has a first parameter of type `bit<8>` gives no such error, only the one whose first parameter is of type `struct`, where in this case the struct contains only a single field of type `bit<8>`.

P4Runtime v1.0 supports register array elements with arbitrary P4_16 types, so this one seems like it would be nice to support.  Since the sample command line above is neither generating a P4Info file, nor invoking any of the p4 back ends, this error seems to be caused by some kind of check in the front/mid end of the compiler somewhere.
[v1model-register-struct-misleading-error-msg.p4.txt](https://github.com/p4lang/p4c/files/2948952/v1model-register-struct-misleading-error-msg.p4.txt)

**Comment by jafingerhut** [comment]
Related to https://github.com/p4lang/p4c/issues/1591 but this issue seems like at least the first piece of the puzzle.

**Comment by hesingh** [comment]
Declaring a local variable for use fixes your issue.

```
        bit<8> result = meta.reg_data1; 
        reg1.read(result, (bit<32>) reg_idx);
        meta.reg_data1 = meta.reg_data1 + 1;
        reg1.write((bit<32>) reg_idx, meta.reg_data1);

	reg_data2_t res = meta.reg_data2;
        reg2.read(res, (bit<32>) reg_idx);
```

**Comment by hesingh** [comment]
P4info also looks good after using a local variable.  This is what I did:

```
hemant@ubuntu:~/int/p4c-aci/build$ ./p4test --std p4-16 v1model-register-struct-misleading-error-msg.p4 --p4runtime-files tmp.txt
hemant@ubuntu:~/int/p4c-aci/build$ 
```

**Comment by jafingerhut** [comment]
Thanks for the info on the workaround, but it seems to me like the error with the original program is the sign of some kind of compiler bug.

**Comment by hesingh** [comment]
The first workaround is not needed.  So, you are right, it's the 2nd read with a struct that is causing the compiler to emit an error.  Looking at the p4c code, the error is emitted if the arg is not a left value - maybe because the struct points to a bit-field which is the final destination.  This is why, when I use a local variable,, the variable is a left value and the compiler works.

**Comment by mbudiu-vmw** [comment]
A pass in the compiler (FlattenInterfaceStructs) assumes that there are no functions that return structs or that have out struct arguments. The way you instantiate your register makes register.read be such a function. What we need is a check that detects such cases and reports a good error message. This should be true for p4c-bm2-ss. However, the same pass is used in p4test, so it will inherit the same constraint, although other back-ends could certainly support struct out values.
