### ISSUE TITLE
Why P4_16+v1model handles user-defined enum, but not enum defined in v1model.p4?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1779]
I can compile the attached file v1model-enum1.p4 just fine.  It has a simple use of a user-defined enum called `Choice`.  I have not spent a lot of time looking at the BMv2 JSON file produced with the following command, but one is produced, and it does appear to replace all occurrences of values of type `Choice` with 32-bit unsigned integer variables and/or constants selected by the compiler for the different `Choice` values that are declared.
```
$ p4c --target bmv2 --arch v1model v1model-enum1.p4 
```

If I then change that variable of type `Choice` to type `CounterType`, an `enum` defined in `v1model.p4`, I get an error in the BMv2 back end:
```
$ p4c --target bmv2 --arch v1model v1model-enum2.p4 
In file: /home/jafinger/p4c/backends/bmv2/common/header.cpp:385
Unimplemented compiler support: /home/jafinger/p4c/build/p4include/v1model.p4(78): <Type_Enum>(347): type not yet handled on this target
enum CounterType {
     ^^^^^^^^^^^
```
Why are these two `enum` types handled differently in this way?

I only noticed this because of someone working on a PSA implementation asking about it.  In the psa.p4 include file there are several `enum` types defined that we expect developer P4_16+PSA programs to use in their programs.  They would like to learn how to handle this situation, and whether P4_16+v1model is behaving "correctly" here.

[v1model-enum1.p4.txt](https://github.com/p4lang/p4c/files/2949944/v1model-enum1.p4.txt)
[v1model-enum2.p4.txt](https://github.com/p4lang/p4c/files/2949945/v1model-enum2.p4.txt)

**Comment by jafingerhut** [comment]
Looking a bit more at results of the intermediate compiler passes and how they transform the program, the fairly early mid-end pass named ConvertEnums is the one replacing `enum Choice` variables and constants with `bit<32>` type variables and constants, for the program `v1model-enum1.p4`.

I am guessing it is not doing that for `v1model-enum2.p4`, probably because it is not doing any conversion on the `enum` types defined within the header file `v1model.p4`.

There was a recent issue created that I cannot find right now where some intermediate compiler pass outputs were not compile-able when given as input to the compiler, because `type` definitions replaced by `typedef` in some mid-end pass of the compiler, but only for user-defined `type` values, not ones inside of `psa.p4`.  This seems somewhat similar, but hopefully there is some fix to the ConvertEnums pass that could enable it to work on `enum` types defined within "standard" architecture header files?

**Comment by derekso1** [comment]
It is possible to do a quick and simple change to the compiler at `backends/bmv2/common/midend.h` line 35 to force the compiler to handle `CounterType` just like a user defined enum and allows the the example brought up to compile. However, using the same logic in `psa_switch` has caused a compiler error. `p4c/build/ir/ir-generated.cpp:6924: Null type` Perhaps logic to handle `v1model.p4` enums might need to be different than user defined enums?

**Comment by mbudiu-vmw** [comment]
If something shows up in a model file you should expect that the compiler needs some target-specific code to handle it. In your case, convertEnums takes a policy conversion function which should know how to convert the new enums. All enums that are in v1model today do not require a conversion, since all should be used as compile-time constants.

**Comment by jafingerhut** [comment]
I agree that v1model.p4 `enum`s do not have much of a use case for being the type of run-time variables, and so the restriction that they cannot be used that way is not an onerous one.  I am not suggesting that we must change `v1model.p4` or the way its `enum` types are compiled, or it is unusable.

However, psa.p4 is unusable in its current form if several of its `enum` types cannot be used as the type of run-time variables.  Not all of them, but at least several, like `PSA_MeterColor_t` and `PSA_PacketPath_t` seem to me like we must support them as the type of run-time variables in a user's program.

It looks like @derekso1 has tried a simple change to allow those two types to be converted, and is hitting some other error.  I do not know what the cause of that other error is.

**Comment by hesingh** [comment]
@jafingerhut The midend pass is the eliminateNewtype.cpp which converts `type` to typedef. 

The issue you could not find seems to be this one: https://github.com/p4lang/p4c/issues/646

Yes, this is the change I and Chris discussed which would be trivial to make and shown in our discussion in the issue.

https://github.com/p4lang/p4c/issues/646#issuecomment-466792264

**Comment by derekso1** [comment]
Would it make sense to keep the current functionality where only programmer defined enums are converted? If the target requires certain enums within psa.p4 to be converted, the target backend can implement logic to do so at the "expression conversion level" when the p4 program gets serialized into JSON format.

**Comment by hesingh** [comment]
The bmv2 backend already process `error` which is a twin to `enum`.  I'd give it a shot to change code in expression.cpp to process any `enum`.  The code for error can be leveraged.

**Comment by jafingerhut** [comment]
Again, hopefully others more knowledgeable than I on p4c internals will provide more informed responses than mine here, but it seems reasonable to have part of the p4c back end code for psa_switch that replaces the `enum` values defined in `psa.p4` with `bit<32>` numeric values, and also the name<->number mapping in an `"enum"` key in the JSON file like is done now for user-defined enums.

I would guess that such a pass could be implemented nearly identically to how the ConvertEnums pass is done today, without the exception for enums's defined in psa.p4.

**Comment by derekso1** [comment]
This might be a long shot, but I think I have a somewhat of a solution. We want the target to be able to define a mapping so the logic for `enum` translation should exist in `psa_switch backend`. What we can do is implement a new pass in `PsaSwitchMidEnd` that works very similar to `ConvertEnums`. This way, a lot of the logic in `ConvertEnums` pass can be reused, we are letting the target define the model `enum` mappings, and making sure that we don't run into the bug(which may not even be a bug if `ConvertEnums` was never designed to handle model file `enums`) I have mentioned above regarding `ConvertEnums`. Thoughts?

**Comment by hanw** [comment]
You can provide a 'policy' class to customize ConvertEnums to choose which enum in `psa.p4` to convert to `bit<8>` or `bit<32>`.

```
class PacketPathTo8Bits : public P4::ChooseEnumRepresentation {
    bool convert(const IR::Type_Enum *type) const override {
        if (type->name != "PSA_PacketPath_t") {
            return false;
        }
        return true;
    }

    unsigned enumSize(unsigned /* size */) const override { return 8; }
};

new P4::ConvertEnums(refMap, typeMap, new PSA::PacketPathTo8Bits),
```

**Comment by derekso1** [comment]
@hanw I tried something like that and encountered an issue? https://github.com/p4lang/p4c/issues/1779#issuecomment-471337579 Not entirely sure how to proceed with debugging.

**Comment by hanw** [comment]
You can run `p4c-bm2-psa` under a debugger, such as gdb or lldb and set a breakpoint at `ir-generated.cpp:6924` to catch the error. It is also useful to open the ir-generated.cpp file, and see the code at line 6924. This file is generated by the compiler, and used to as part of the compiler source.

I suspect the error is related to typeMap.

You may need to do the following
```
new P4::ConvertEnums(refMap, typeMap, new PSA::PacketPathTo8Bits),
new TypeChecking(refMap, typeMap, true),
```

**Comment by mbudiu-vmw** [comment]
Your comments are about v1model, but you say you want to compile for psa. Which one is it?

**Comment by jafingerhut** [comment]
The end goal is to compile for PSA.  The comments about v1model are experiments on a mostly-working system for purposes of learning and comparison with what a PSA implementation could/should do.

**Comment by mbudiu-vmw** [comment]
This pass should work fine in PSA if you supply a suitable policy. I tagged this issue as a question, because I don't see a bug to fix.

**Comment by mbudiu-vmw** [comment]
Is this question satisfactorily answered?

**Comment by jafingerhut** [comment]
Yes, I think so.  Thanks for the answers.  Closing.
