### ISSUE TITLE
p4c p4runtime serializer fails with two Action parameters

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#1788]
If an Action has two parameters, the parameters are not processed correctly.   I have fixed the issue with an existing PR: https://github.com/p4lang/p4c/pull/1736

See this checkin

https://github.com/familysingh/p4c/commit/69e2a940be0e0a717ef7b527b236a0c01cd3cfae

**Comment by mbudiu-vmw** [comment]
You should supply a separate pull request to fix this bug, which should also contain a test case.
The other PR is already too complex.

**Comment by hesingh** [comment]
I do have a test case which found this bug.  When I get spare cycles, I will add the test case to a new PR and use this Issue's diffs to that PR.

**Comment by hesingh** [comment]
Please review the one-line fix for this issue in this PR.

https://github.com/p4lang/p4c/pull/1794

**Comment by mbudiu-vmw** [comment]
This seems to be solved.
