### ISSUE TITLE
How to create extern with multiple constructors with the same number of constructor parameters.

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1790]
Currently frontend does not support extern constructors with the same number of constructor parameters. What needs to be done to support this feature?

```
extern DynamicHash<W> {
    DynamicHash(HashAlgorithm_t algo);
    DynamicHash(tuple<HashAlgorithm_t, HashAlgorithm_t> algo);
    W get();
}
```

**Comment by hanw** [comment]
I guess the following would work for this example, but the question remains.
```
extern DynamicHash<W, T> {
    DynamicHash(T algo);
    W get();
}
```

**Comment by mbudiu-vmw** [comment]
The first one would be easier if you use two arguments instead of a tuple.
You can use named arguments to disambiguate:
```
extern DynamicHash<W> {
    DynamicHash(HashAlgorithm_t algo0);
    DynamicHash(tuple<HashAlgorithm_t, HashAlgorithm_t> algo1);
}

DynamicHash(algo0 = blah) dh;
```

**Comment by hanw** [comment]
I am actually looking for ways to create extern with arbitrary number of HashAlgorithm_t paramters.
```
extern DynamicHash<W> {
    DynamicHash(HashAlgorithm_t algo0);
    DynamicHash(tuple<HashAlgorithm_t, HashAlgorithm_t> algo1);
    DynamicHash(tuple<HashAlgorithm_t, HashAlgorithm_t, HashAlgorithm_t> algo2);
    ...
}

DynamicHash(algo0 = blah) dh;
```

So, maybe using `T` is the right things to do.

**Comment by hanw** [comment]
till we support `vector<6, HashAlgorithm_t>` as the type for the constructor parameter one day? =)

**Comment by mbudiu-vmw** [comment]
Yes, T will work, and the back-end can put constraints on it.
