### ISSUE TITLE
Two tests fail with latest p4c

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#1791]
I suppose Travis has passed for p4lang/p4c.  However, since yesterday, each time, I have downloaded latest p4c, these two tests fail. 

The following tests FAILED:
	277 - bmv2/testdata/p4_16_samples/issue1755-1-bmv2.p4 (Failed)
	278 - bmv2/testdata/p4_16_samples/issue1755-bmv2.p4 (Failed)

```
$ bmv2/testdata/p4_16_samples/issue1755-1-bmv2.p4.test 
Check for  /tmp/p4c/testdata/p4_16_samples/issue1755-1-bmv2.stf
Calling target program-options parser
Adding interface pcap0 as port 0 (files)
Obtaining JSON from switch...
Done
Control utility for runtime P4 table manipulation
RuntimeCmd: 
WARNING: PcapReader: unknown LL type [0]/[0x0]. Using Raw packets
*** Received packet  000011223344
*** Packet different at position 0 : expected 1 , received 0
*** Full expected packet is  11223344
*** Full received packet is  000011223344
*** Packet 0 on port 0 differs
*** Test failed
```

```
$ bmv2/testdata/p4_16_samples/issue1755-bmv2.p4.test 
Check for  /tmp/p4c/testdata/p4_16_samples/issue1755-bmv2.stf
Calling target program-options parser
Adding interface pcap0 as port 0 (files)
Obtaining JSON from switch...
Done
Control utility for runtime P4 table manipulation
RuntimeCmd: 
WARNING: PcapReader: unknown LL type [0]/[0x0]. Using Raw packets
*** Received packet too long 4 vs 2 (in units of hex digits)
*** Full expected packet is  00
*** Full received packet is  0000
*** Packet 0 on port 0 differs
*** Test failed
```

**Comment by jafingerhut** [comment]
Likely this test failure will go away if you update your copy of the p4lang/behavioral-model repo, rebuild, and reinstall simple_switch from latest source.  Issue #1755 implemented the `packet.advance()` call in the compiler, which had not been implemented before, and it requires corresponding additions in BMv2 to support that, which you probably do not have, hence the test failures.

**Comment by hesingh** [comment]
Thanks, Andy!  Wow, I missed that behavioral-model may still be changing as of last week and didn't update my local repo.  Yes, I saw 1755 is the new advance feature for bmv2 and thought, with p4c bmv2 backend updated, I am all set.  I didn't realize the behavioral-model and simple_switch needs an update too.  

Now, both the tests passed.
