### ISSUE TITLE
IR::ParameterList and IR::Vector<IR::Argument>

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1801]
There seems to be two ways to represent things of this form in the frontend IR today.

```
name (type param0, type param1, type param2)
```

If the above is a ConstructorCallExpression, then the list of parameter is represented as 

`IR::Vector<IR::Argument>` where each argument does not have a name until user provides a name in P4. 

If the above is a parser,control,func,action, etc, then the list of parameters is represented as 

`ParameterList`, where the compiler implementer can use helper method such getParameters and getParameter(cstring name) to access a member in the list.

My question is why do we need to have two ways to represent a list of parameters in the IR. I understand it is needed to implement named argument, but it would be nice to make the name of an Argument not null, so that a helper function can be implemented to access an argument in a vector based on name.

**Comment by ChrisDodd** [comment]
A `ParameterList` is a list of parameters from/for a declaration -- that is a list of names and types, but no values; a "formal" parameter list.  a `IR::Vector<IR::Argument>` is an ACTUAL argument list -- a list of (optional) names and actual values.  So the first is a declaration, and the second is a use (an actual call).
