### ISSUE TITLE
Introducing conflicting names with the @name annotation, should it be a frontend error?

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#1803]
I wrote the following P4 program:
```
#include <core.p4>
#include <v1model.p4>

struct H { };
struct M {
    bit<32> hash1;
}

parser ParserI(packet_in pk, out H hdr, inout M meta, inout standard_metadata_t smeta) {
    state start { transition accept; }
}

action empty() { }

control MyC(inout standard_metadata_t smeta)() {
    action drop() { mark_to_drop(); }

    @name(".t0")
    table t0 {
        key = { smeta.ingress_port : exact; }
        actions = { drop; NoAction; }
        const default_action = NoAction();
    }
    apply {
        t0.apply();
    }
}

control IngressI(inout H hdr, inout M meta, inout standard_metadata_t smeta) {

    MyC() c1;
    MyC() c2;

    apply {
        c1.apply(smeta);
        c2.apply(smeta);
    }

};

control EgressI(inout H hdr, inout M meta, inout standard_metadata_t smeta) {
    apply { }
};

control DeparserI(packet_out pk, in H hdr) {
    apply { }
}

control VerifyChecksumI(inout H hdr, inout M meta) {
    apply { }
}

control ComputeChecksumI(inout H hdr, inout M meta) {
    apply { }
}

V1Switch(ParserI(), VerifyChecksumI(), IngressI(), EgressI(),
         ComputeChecksumI(), DeparserI()) main;
```

I compiled it with the the following command: `./p4test same_name.p4 --p4runtime-files=same_name.p4info.pb.txt`.

I didn't get any error and a P4Info message is generated. The generated P4Info is invalid however, because it includes 2 entries for table "t0":
```
tables {
  preamble {
    id: 33580881
    name: "t0"
    alias: "t0"
  }
  match_fields {
    id: 1
    name: "smeta.ingress_port"
    bitwidth: 9
    match_type: EXACT
  }
  action_refs {
    id: 16815162
  }
  action_refs {
    id: 16800567
  }
  const_default_action_id: 16800567
  size: 1024
}
tables {
  preamble {
    id: 33580881
    name: "t0"
    alias: "t0"
  }
  match_fields {
    id: 1
    name: "smeta.ingress_port"
    bitwidth: 9
    match_type: EXACT
  }
  action_refs {
    id: 16790297
  }
  action_refs {
    id: 16800567
  }
  const_default_action_id: 16800567
  size: 1024
}
```
One thing I could to is add a check in the P4Info generation code to detect duplicate names for distinct objects. However, the P4_16 spec describes this exact same scenario (section 18.2.3.1) and explicitly calls it out as illegal, which is why **I believe this should be caught in the frontend**:

> Without the @name annotation, this program would produce two controllable entities with fully-qualified names main.c1.t and main.c2.t. However, the @name(".foo.bar") annotation renames table t in both instances to foo.bar, resulting in one name that refers to two controllable entities, which is illegal.

I'm attaching my test program.
[same_name.p4.txt](https://github.com/p4lang/p4c/files/2985012/same_name.p4.txt)

**Comment by antoninbas** [comment]
@milad14000 @amreshk FYI

**Comment by mbudiu-vmw** [comment]
This is the same as #595
But perhaps we should keep this one.

**Comment by mbudiu-vmw** [comment]
Frankly, I think this is easier to do in P4info generation; the code already has to gather all names and put them together. But it is indeed common across all architectures. So perhaps it could be done by generating always P4info - but not always writing it to some output file. That's probably it has been open for so long.

**Comment by antoninbas** [comment]
It is easy to add a check in the P4Info generation code, and honestly I don't mind doing that myself. The p4RuntimeSerializer builds a SymbolTable and we just need to check for duplicates there once everything has been added to it. But it's a poor man's solution:
 * we cannot always generate a P4Info message because of some P4Runtime limitations (e.g. an expression with type `error` used as a match field, and many other)
 * some architectures / backends may not support P4Info generation

**Comment by mbudiu-vmw** [comment]
Since we are running P4info after the front-end we should be able to run it for any architecture, even if the back-end does not care about this information. We would still get some validation. Perhaps later we can move the validation logic to its own pass, especially if it turns out to be simple. 

Regarding unsupported features, this is a more interesting problem. One solution would be to somehow redirect errors to /dev/null if one is not interested in them, but that's more like a hack.

**Comment by antoninbas** [comment]
The backend main function decides whether to run the P4Info generation. If the backend generates the P4Info, it is responsible for registering an "arch handler" to handle architecture-specific externs. The arch handler is responsible for adding extern instances to the symbol table.

I'll add the check. One can argue that 1) the `@name` annotation is meant specifically for control-plane interaction, 2) the P4Info generator is responsible for making sure a correct P4Info message is generated, and 3) if P4Runtime / P4Info is not used but instead some other control-plane API, it's not the responsibility of the P4Info generator (and per 1., not the responsibility of the compiler) to ensure name integrity. It's still not a very strong argument IMO since the semantics of `@name` are clearly defined in the P4 spec.

**Comment by antoninbas** [comment]
I opened a PR for this. Not sure I would call it a full fix, because I still think some checks could be done in the fronted, but at least it will make sure that no incorrect P4Info is generated.
