### ISSUE TITLE
Several small bugs in generation of table entries for P4_16 'const entries'

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1805]
Details of problems found are given in comments on this PR: https://github.com/p4lang/p4c/pull/1804

The main categories of problems found were:

+ When the P4_16 source file had a ternary match field with (value & mask) != mask, an entries file was generated with that value/mask pair, anyway, in violation of P4Runtime rules against such value/mask pairs.  Seems like the best thing to do would be to at least warn about such bad value/mask pairs in the source file, or even give an error during compilation.

+ P4Runtime canonical representation is to omit the description of table search key fields, if the field is ternary, lpm, or range, and is completely "don't care", i.e. can match any legal value for the field.  The current entries files generated mention such fields, although it appears with correct "match anything" rules (value=mask=0 for ternary, value=prefix_length=0 for lpm, min=0 max=2^W-1 for range).

+ P4Runtime canonical representation of unsigned bit strings is to use the fewest number of bytes in the byte sequence possible, omitting any leading bytes that are completely 0.  The existing files produce values with unnecessary leading 0 bytes in some cases.

+ The test program testdata/p4_16_samples/table-entries-priority-bmv2.p4 has a ternary table with `@priority` annotations on several of the entries.  Such annotations were considered by the P4 language design work group, but ultimately rejected (or at least postponed) for the latest P4_16 language spec (v1.1 as of this writing), in favor of always having the relative priorities of multiple table entries determined by the order they appear in the source file.  I am not sure whether `@priority` is desired as an experimental extension for the `p4c` compiler or not.  If so, they should be used and carried through into the entries file.  If not, maybe this test program should be removed?  It seems odd to give an error for an ignored annotation, but at least a warning from the compiler that they are ignored would be good, if we want to keep this test program around, else people might infer that this is supported.

**Comment by jafingerhut** [comment]
One more related issue from Antonin: "I was actually missing 4 files (tests added recently that didn't get picked up when I ran ctest locally), one of them action-two-params.p4"

I agree that it seems reasonable to leave out the source file names ending with "-epbf.p4" from generating and checking entries files.

**Comment by antoninbas** [comment]
@jafingerhut I don't think that last part is an actual issue. My branch was probably out-of-date and the tests got picked up after rebasing from master and running cmake again.

**Comment by jafingerhut** [comment]
Sounds good.  I assumed it was left out in the commit because I say only the 1 commit in the PR.  Glad to know the other files are in there already.

**Comment by mbudiu-vmw** [comment]
Is this fixed?

**Comment by antoninbas** [comment]
It's mostly fixed. Andy's 3rd bullet point hasn't been fully addressed because it would break existing software and it is not a bug per se.

**Comment by jafingerhut** [comment]
I will create an enhancement issue to remind us of the 3rd bullet point.  That one sounds like it will require changes across multiple p4lang repos.
