### ISSUE TITLE
Out of range exception when number of error consts is more than 9

### ISSUE THREAD

**Issue by enisah** [p4lang/p4c#1824]
Hi,
I have noticed when there is more than 9 error values in p4 file, out_of_range exception is reported during simple_switch execution.

**Comment by jnfoster** [comment]
A small request: to help folks fix the bug, perhaps you can supply an example to illustrates the behavior you're seeing? Having both the P4 code and the JSON output would be useful. The description is precise enough, but still it will take someone a few minutes to hack together an example whereas you already have one.

Also, this seems like it could be a BmV2 bug.

**Comment by enisah** [comment]
For example, for the following part of the program:
error {
    IPv4OptionsNotSupported,
    IPv4ChecksumError,
    IPv4HeaderTooShort,
    IPv4BadPacket
}

parser MyParser(packet_in pkt,
               out headers hdr,
               inout metadata meta,
               inout standard_metadata_t stdmeta)
{
   state start {
        pkt.extract(hdr.h1);
        verify(false, error.IPv4BadPacket);
        verify(false, error.IPv4HeaderTooShort);
        transition accept;
    }
}

json for the verify function will look like:

              "parameters" : [
                {
                  "type" : "bool",
                  "value" : false
                },
                {
                  "type" : "hexstr",
                  "value" : "10"
                }
              ],
              "op" : "verify"
            },
            {
              "parameters" : [
                {
                  "type" : "bool",
                  "value" : false
                },
                {
                  "type" : "hexstr",
                  "value" : "9"
                }
              ],
              "op" : "verify"
            }
Error value 10 during execution will be read as hex value 16, not 10 as it should be.

**Comment by mbudiu-vmw** [comment]
He already supplied a reproduction and fix for this bug in #1825
