### ISSUE TITLE
P4_16 + v1model mark_to_drop violates P4_16 language semantics

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1828]
First pointed out by Mihai Budiu here: https://github.com/p4lang/p4c/pull/1818#discussion_r269311117

When BMv2 simple_switch executes a P4_16 + v1model architecture program that executes a `mark_to_drop()` action, it implements it by immediately modifying `standard_metadata.egress_spec` and `standard_metadata.mcast_grp`.  See here for the implementation: https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/primitives.cpp#L143-L150

The problem from the P4_16 language specification point of view is: `mark_to_drop` should not be able to do so, because it does not take the standard_metadata struct as a parameter.  Yes, externs have "arbitrary power", but not really arbitrary, because they are not permitted to access variables in your program that are not run-time parameters.  See the first two paragraphs of the P4_16 language specification, version 1.1, Section 6.7.1 titled "Justification".

This is similar to issues raised about the current P4_16 + v1model implementations of recirculate, resubmit, and clone when preserving user-defined metadata fields.  Now that I write this, I realize that those operations _also_ currently modify fields within the standard_metadata struct (e.g. clone_spec, recirculate_flag, resubmit_flag, lf_field_list) without having access to them, according to P4_16 language specification restrictions.

One could argue in those cases that perhaps those fields in standard_metadata should not even be visible to the user's P4 program, and are instead "hidden state inside the architecture", but that argument does not apply for the mark_to_drop case, since egress_spec and mcast_grp fields are fully expected to be visible to, both read and write, by the user's P4 program.

Possible change that could be made: change the definition of mark_to_drop to take the standard_metadata struct as an inout parameter, like so:
```
extern void mark_to_drop(inout standard_metadata_t stdmeta);
```
This would require updating a fair number of P4_16 test programs in p4c, as well as P4 tutorials based on P4_16 + v1model architecture, etc.

**Comment by jafingerhut** [comment]
Another possible approach: Keep mark_to_drop() with no parameters, but change its implementation so that instead of modifying standard_metadata.egress_spec and mcast_grp fields, have it assign a value to a "hidden state inside the architecture" variable that is neither of those.

That would have a more subtle effect, which is that later assignments to egress_spec or mcast_grp fields would _not_ undo the effect of mark_to_drop().

It also requires some changes to BMv2 simple_switch, e.g. the pseudocode here (and its implementation inside BMv2 code): https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md#pseudocode-for-what-happens-at-the-end-of-ingress-and-egress-processing

**Comment by jnfoster** [comment]
Yikes. And I agree with extreme caution. Best to get this right.

**Comment by jafingerhut** [comment]
Looking through the rest of the features defined in v1model.p4, I think these are the only things that are affected by this issue:

+ mark_to_drop - fixable by adding standard_metadata as inout parameter
+ recirculate, resubmit, clone, clone3 - for the reason mentioned in the first comment, which can be fixed by either making standard_metadata an additional inout parameter, or by making some fields currently in standard_metadata inaccessible to the user's program, e.g. resubmit_flag, recirculate_flag, clone_spec.  Also this separate issue, of course: https://github.com/p4lang/p4c/issues/1669
+ digest - Similar to the extern functions in the previous bullet point, because of current implementation that writes to standard_metadata.lf_field_list.  I haven't checked what the current implementation does, but believe it may be like the previous bullet point in that it captures the field values at the end of the ingress pipeline, not at the time of the digest call.
+ action_selector - As far as I can tell, this one only becomes questionable depending upon how conversations about how one of several field lists are fed into the hash function, e.g. virtual functions or this issue: https://github.com/p4lang/p4-spec/issues/744.  Everything else about it is modifying how a table apply operation happens internally, without accessing variables in the user's P4 program.

The two verify_* calls below are on the boundary, in that from one perspective their implementations do modify fields in standard_metadata that are accessible in the user's P4 program, but since these can only be called in the verifyChecksum control, and nothing else can be done inside of that control, the modification to standard_metadata contents can be considered to be delayed until just before the ingress control begins processing the packet.

+ verify_checksum, verify_checksum_with_payload - currently like mark_to_drop, in that they can assign standard_metadata.checksum_error the value of 1.  Unlike mark_to_drop, this should be straightforward to fix simply "by careful definition" - define them to store the detected error in some architecture-private place, and then before ingress processing begins, the architecture gets that state about the packet and puts it into the value of standard_metadata given as input to the ingress pipeline.  There should be no problem if an architecture does things like this between parsers or controls that are the major pieces of the architecture, as is already done for initializing fields like instance_type to indicate whether a packet is new from a port, recirculated, or resubmitted.

I have high confidence that the things below do not exhibit this issue, i.e. the only way they access a user's P4 program variables are through run-time parameters:

+ counter, direct_counter, meter, direct_meter, register - all inputs/outputs go through parameters, and all other state is private to the extern.
+ random, hash - these immediately return a value, or write it to an out parameter, based upon the current values of input parameters, and at least for random, state private to the extern implementation.  No variables in the user's P4 program are accessed that are not parameters.
+ Checksum16 - deprecated anyway, but I believe its implementation doesn't have this problem, because it is like hash.
+ update_checksum, update_checksum_with_payload - like hash, and OK as long as we say that the payload is "private to the architecture", which it pretty much is in v1model because the payload is not accessible as a P4 program variable.
+ truncate - I think this one is OK.  Its implementation does not seem to access anything in standard_metadata.  As far as I can tell, it is recording the desired truncation length in some extern-private location, and then the architecture effectively uses the data in that private location to modify the packet after the deparser is done.
+ action_profile - As far as I can tell this one does not have this issue.  It modifies the way a table behaves internally, without accessing variables in the user's P4 program.

**Comment by jafingerhut** [comment]
And just to put PSA under the same scrutiny, I've reviewed psa.p4 features the same way.

drop is implemented via explicit assignment to a metadata field visible to the user's program, and nothing in PSA accesses it without it being an explicit parameter.

recirculate, resubmit, clone are defined quite differently than in P4_14 and v1model, and do not have this issue.

digest is defined in a way where the only P4_16-compatible way to implement it is to capture the values of the fields provided when the call to create the digest is made.

ActionSelector does not have any problems as defined in PSA, but will have the same potential issues as v1model's action_selector described in the previous comment, e.g. virtual functions or having a control-plane-configurable one of several field lists over which to calculate a hash.  Nothing unique to PSA here.

**Comment by jafingerhut** [comment]
OK, one more potential suggestion for what to do about v1model mark_to_drop() specifically, which may be a smoother transition for many P4_16 users:

(1) Add a new action, e.g. perhaps named mark_to_drop2 unless that makes people's hackles rise up, in which case they can suggest another name, that would just be a plain old action in v1model.p4 defined like so:

```
#define BMV2_V1MODEL_SPECIAL_DROP_PORT  511

action mark_to_drop2(inout standard_metadata_t stdmata) {
    stdmeta.egress_spec = BMV2_V1MODEL_SPECIAL_DROP_PORT;
    stdmeta.mcast_grp = 0;
}
```

(2) deprecate the existing mark_to_drop() extern function, preferably with a message appearing recommending that they use the new action instead.

After such changes, people will get deprecation warnings whenever they use mark_to_drop, but for now, and perhaps indefinitely, their code keeps working as it does today.  They will update their code when they want the warnings to go away.

I know the desire would be to remove mark_to_drop soon-ish, but even if it hung around for years, would it hurt anything?

**Comment by mbudiu-vmw** [comment]
I started working on this; I have a partial fix along these lines, using an external function instead of an action. But this solution is cleaner. If this is the exact semantics of mark_to_drop, we should indeed write down the action - then we don't need to write the complicated explanation in comments, it's plain code.

If you write the action in this way, today the compiler will actually copy all standard metadata in and out of the action. It's not smart enough to understand that the mutation can be done in place.

**Comment by mbudiu-vmw** [comment]
The only problem with this approach is that it is BMV2 specific - this won't work on other architectures which don't use 511 for the port number. But I still favor this solution.

**Comment by jafingerhut** [comment]
One advantage to making mark_to_drop2() an extern function, and not an action as suggested in an earlier comment, is that doing so avoids putting the special constant 511 into the compiled BMv2 JSON files, and thus changes like this planned one: https://github.com/p4lang/behavioral-model/issues/743

will work with the same BMv2 JSON files before and after simple_switch is changed in that way.

**Comment by jafingerhut** [comment]
I have created a separate follow-up issue https://github.com/p4lang/p4c/issues/1845 regarding the fields in standard_metadata that v1model extern functions like clone, resubmit, etc. currently modify.  Given that separate issue, it seems reasonable to close this issue as soon as mark_to_drop is fixed.
