### ISSUE TITLE
Using last outside the parser.

### ISSUE THREAD

**Issue by santos-lucas** [p4lang/p4c#1853]
I was using last for a header_stack on p4_14 outside the parser, what by the specification should not be possible, but the code has compiled well, with no erros from the compiller, but i was gettin a error at the setup of the switch at mininet (probably because i was with a invalid code)... So, i think there is a bug in the compiler, because the code should't be copilled in the first place.

**Comment by jnfoster** [comment]
Can you post an example program? It will be easier to debug that way...

**Comment by santos-lucas** [comment]
I dont have the code anymore, i changed it because my test did not work...
but i was just acessing the las statement in a table+action like this:

parser parse_values{
    extract(value[next]);
    return select(latest.bos){
        0: parse_values;
        1: ingress;
    }
}

table table_clean_bos{
     actions{
         clean_bos;
     }
     size: 1;
 }

 action clean_bos(){
     modify_field(value[last].bos, 0);
 }


I'm sorry about not keep the code, i just realized that was a bug in the
copiller after change it..

Best regards,

Lucas Santos






Em dom, 14 de abr de 2019 às 16:18, Nate Foster <notifications@github.com>
escreveu:
