### ISSUE TITLE
Structure flattening pass is probably buggy

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#1863]
I suspect it does not handle correctly this case:
```
struct S { bit a; bit b; }
S s = { 0, 1 };
s = { s.b, s.a };
```

**Comment by jafingerhut** [comment]
Confirmed.  From looking at the P4_16 program output after each of the compiler's front and mid end passes, it appears that the first one that is incorrect is just after the midend CopyStructures pass (pass number 18 in the latest version of p4c as of writing this comment).

You probably already have a test program for this whipped up, and it appears that the bug can be caught from looking at the '-midend.p4' test output file, so the attached STF test file is probably unnecessary.
[issue1863-bmv2.p4.txt](https://github.com/p4lang/p4c/files/3095480/issue1863-bmv2.p4.txt)
[issue1863-bmv2.stf.txt](https://github.com/p4lang/p4c/files/3095481/issue1863-bmv2.stf.txt)

**Comment by mbudiu-vmw** [comment]
I am still fighting to rebase my old pull requests, so I haven't started working on this - all these XFAILs that keep changing and a changing bmv2 are giving me trouble; we are also churning changes in v1model which affect lots of outputs.

But your discussion on overlays pointed that this is a problem for all structs.

**Comment by mbudiu-vmw** [comment]
The bug is actually in copyStructures.

**Comment by mbudiu-vmw** [comment]
I will also add the test you supplied to the PR if it runs fine
