### ISSUE TITLE
Add fabric.p4 to the list of tests

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#1864]

**Comment by mbudiu-vmw** [comment]
https://github.com/opennetworkinglab/onos/blob/master/pipelines/fabric/src/main/resources/fabric.p4

**Comment by jafingerhut** [comment]
First draft of a PR for adding that program here: https://github.com/p4lang/p4c/pull/1869

**Comment by mbudiu-vmw** [comment]
Fixed by #1869
