### ISSUE TITLE
Found 1 duplicate name(s) in the P4Info with psa-counter6.p4

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#1867]
I just downloaded p4c and built it to debug a failure with `psa-counter6.p4` in my PSA11 PR.  I see the issue with this latest p4c as well.  See log below.

```
hemant@ubuntu:/tmp/p4c/build$ p4/testdata/p4_16_samples/psa-counter6.p4.test
./p4test --pp ./tmpDSBuXn/psa-counter6.p4 --dump ./tmpDSBuXn --top4 FrontEndLast,FrontEndDump,MidEndLast --testJson --maxErrorCount 100 --arch psa --p4runtime-files ./tmpDSBuXn/psa-counter6.p4.p4info.txt --p4runtime-entries-files ./tmpDSBuXn/psa-counter6.p4.entries.txt /tmp/p4c/testdata/p4_16_samples/psa-counter6.p4
Error compiling
[--Werror=duplicate] error: Name 'MyIC.counter0' is used for multiple direct counter objects in the P4Info message
[--Werror=duplicate] error: Found 1 duplicate name(s) in the P4Info

hemant@ubuntu:/tmp/p4c/build$ 
```

**Comment by antoninbas** [comment]
The psa-counter6.p4 program violates the PSA spec:

> A DirectCounter instance must appear as the value of the psa_direct_counter table attribute for at most one table.

**Comment by hesingh** [comment]
So what should we do with this test?  Move it to p4_16_errors directory as a negative test?  I don't understand why this failing test was added to the branch when it fails.

**Comment by antoninbas** [comment]
I already added it to XFAIL (https://github.com/p4lang/p4c/blob/master/backends/p4test/CMakeLists.txt#L84), you may not have resolved your merge conflict properly

**Comment by hesingh** [comment]
ok, thanks.

**Comment by hesingh** [comment]
Hmm, so why does latest p4c fail on this test?

**Comment by antoninbas** [comment]
Is it: https://travis-ci.org/p4lang/p4c/branches ?

**Comment by hesingh** [comment]
It's a https://github.com/p4lang/p4c branch.

**Comment by hesingh** [comment]
Interestingly, these changes fix the issue in latest p4c.

```
diff --git a/backends/p4test/CMakeLists.txt b/backends/p4test/CMakeLists.txt
index effd626f..b2c67b96 100644
--- a/backends/p4test/CMakeLists.txt
+++ b/backends/p4test/CMakeLists.txt
@@ -72,6 +72,11 @@ set (P4RUNTIME_EXCLUDE
   # These tests use 'error' as a table key
   testdata/p4_16_samples/issue1304.p4
   testdata/p4_16_samples/issue1062-1-bmv2.p4
+  # This program is invalid according to the PSA specification as one direct
+  # counter is shared by multiple match tables: "A DirectCounter instance must
+  # appear as the value of the psa_direct_counter table attribute for at most
+  # one table."
+  testdata/p4_16_samples/psa-counter6.p4
 )
 
 set (P4_XFAIL_TESTS
@@ -81,11 +86,6 @@ set (P4_XFAIL_TESTS
   testdata/p4_16_samples/psa-example-digest-bmv2.p4
   testdata/p4_16_samples/p4rt_digest_complex.p4
   testdata/p4_16_samples/psa-example-counters-bmv2.p4
-  # This program is invalid according to the PSA specification as one direct
-  # counter is shared by multiple match tables: "A DirectCounter instance must
-  # appear as the value of the psa_direct_counter table attribute for at most
-  # one table."
-  testdata/p4_16_samples/psa-counter6.p4
   )
 # we invoke p4c with --p4runtime-files even for programs in p4_16_errors. This
 # enables us to use p4_16_errors even for programs which pass compilation but
```

**Comment by hesingh** [comment]
Can anyone else please download latest p4c and see if they can also reproduce this issue - thanks.

**Comment by jafingerhut** [comment]
I have this version of the behavioral-model source built and installed:
```
commit fff3171f2a7e3fcbb2ae8dec9aa425e282025b10
Author: Antonin Bas <antonin@barefootnetworks.com>
Date:   Thu Apr 18 18:55:54 2019 -0700
```
and this version of p4c:
```
commit c951c457eb6fc42393e4b46521cf443105ff80b6
Author: Mihai Budiu <mbudiu@vmware.com>
Date:   Fri Apr 19 12:48:00 2019 -0700
```
and I see 0 test failures out of 1305 from `make check`.

**Comment by hesingh** [comment]
Thanks @jafingerhut!  I also tested `make check` and all tests passed.  However, when I run the individual test, the test fails.

`hemant@ubuntu:/tmp/p4c/build$ p4/testdata/p4_16_samples/psa-counter6.p4.test`

I think, even if you try the individual test above, the test should fail. 

I had to debug this test because for my PSA11 PR, Travis failed on the same test.

**Comment by hesingh** [comment]
It is well-known requirement of p4c that `make check` pass for any code changes.  However, if `make check` passes, any individual test must also pass, otherwise how does one debug a failing test?  One individual test fails after  checkin of https://github.com/p4lang/p4c/pull/1849

The reason is because p4runtime args are used with p4test.

```
hemant@ubuntu:/tmp/p4c/build$ p4/testdata/p4_16_samples/psa-counter6.p4.test
./p4test --pp ./tmpNVDuRN/psa-counter6.p4 --dump ./tmpNVDuRN --top4 FrontEndLast,FrontEndDump,MidEndLast --testJson --maxErrorCount 100 --arch psa --p4runtime-files ./tmpNVDuRN/psa-counter6.p4.p4info.txt --p4runtime-entries-files ./tmpNVDuRN/psa-counter6.p4.entries.txt /tmp/p4c/testdata/p4_16_samples/psa-counter6.p4
```

**Comment by hesingh** [comment]
PR has been sent out to fix this issue.

https://github.com/p4lang/p4c

**Comment by hesingh** [comment]
All these files which were added to P4_XFAIL_TESTS actually fail p4test when used with --p4runtime... args.  Thus the files actually belong in P4RUNTIME_EXCLUDE.  If the files had been added to P4RUNTIME_EXCLUDE, then this issue would have have occurred.

```
  testdata/p4_16_samples/psa-example-digest-bmv2.p4
  testdata/p4_16_samples/p4rt_digest_complex.p4
  testdata/p4_16_samples/psa-example-counters-bmv2.p4
  # This program is invalid according to the PSA specification as one direct
  # counter is shared by multiple match tables: "A DirectCounter instance must
  # appear as the value of the psa_direct_counter table attribute for at most
  # one table."
  testdata/p4_16_samples/psa-counter6.p4
```

**Comment by antoninbas** [comment]
I think you don't know what XFAIL stands for.

**Comment by hesingh** [comment]
p4c/README.md explains XFAIL.  It's a set of tests that are expected to fail.  The tests I listed above fail due to use of `--p4runtime-files` with p4test.  Thus, the tests could just as well be in P4RUNTIME_EXCLUDE list.  

But why does `make check` passes, but when one runs an individual test using `p4/testdata/p4_16_samples/psa-counters6.p4`, the test fails?  Don't we have to fix this issue?

**Comment by hesingh** [comment]
I understand, a test included in XFAIL list fails when run individually.  The reason, I am chasing the problem is because, `make check` passes for my p4c code changes.  I commit the changes, but then Travis fails on one or more tests in the XFAIL list.

**Comment by hesingh** [comment]
The Travis failures turned out to be churn in changes to CMakelist.  I finalized the CMakelist in the PSA11 PR and now Travis passes.
