### ISSUE TITLE
Segmentation fault with recursive control flow

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#187]
The attached program uses a recursive control flow (guarded by a `hit` block). This should be illegal, but the compiler crashes with a segmentation fault.

> $../p4c/build/p4test --p4-14 recurse.p4 
> Segmentation fault (core dumped)

[recurse.p4.txt](https://github.com/p4lang/p4c/files/652418/recurse.p4.txt)

**Comment by mbudiu-vmw** [comment]
Is there a reproduction we can use to diagnose this reopened issue?
The recurse.p4 test is handled correctly. Unfortunately the test is not in the testsuite due to issue #96: we actually don't have negative tests for p4-14 programs.

**Comment by mbudiu-vmw** [comment]
This seems to be solved.
