### ISSUE TITLE
Bug in p4c hash?

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#1872]
This is the P4 code using v1model.p4.

```
hash(meta.meta.lb_hash, HashAlgorithm.crc16, 12w0, { hdr.inner_ipv4.srcAddr, hdr.inner_ipv4.dstAddr }, 12w4096);
```
Latest p4c gives this warning:

```
[--Wwarn=mismatch] warning: 4096: value does not fit in 12 bits
        hash(meta.meta.lb_hash, HashAlgorithm.crc16, 12w0, { hdr.inner_ipv4.srcAddr, hdr.inner_ipv4.dstAddr }, 12w4096
                                                                                                               ^^^^^^^
```

The code looks correct because (base+max-1) = (0+4096-1) = 4095.

I have included the comment for hash from p4c/p4include/v1model.p4 below.

In p4c/p4inclide/v1model.p4, the comment above the hash function says "result will always be in the range [base, base+max-1] inclusive,"

**Comment by hesingh** [comment]
It's the p4c bitwitdth checker code that would say "warning: 4096: value does not fit in 12 bits".  But, then, how does one use hash with range 0-4095?  I suppose, use 13w0 and 13w4096

**Comment by hesingh** [comment]
I think, it's an API design issue.  The hash should use a range of (base+max) where base MUST be zero.  Then, it's more intuitive for base to be 12w0 and max to be 12w4095

**Comment by jafingerhut** [comment]
I agree that it does not make much sense in v1model to use the hash extern function if (base+max-1) does not fit into the result type `O`.

Other than some kind of optimization of 1 bit width in the implementation, is there any problem using 13w4096 to get a range of 4096 possible return values?

**Comment by hesingh** [comment]
I have used 13w4096 for now and result should include a 12-bit value because the first arg of the hash API is the result whose width is 12.  

But having used hash functions for over 20 years now in C programming, I have always used a range of 0 to (2^12 - 1).  Thus, the P4 v1model hash API is confusing and should change to (base+m) if base starts with zero.

**Comment by jafingerhut** [comment]
I understand that it might not be the API you wish it were, but there is at least some amount of code written for the current API, which has remained the same for a little over 2 years now.

In my opinion, there is value in not changing APIs that have at least some existing user base.  Adding a new second function with a different API makes more sense to me than changing the semantics/behavior of an existing API.

**Comment by hesingh** [comment]
Second function sounds ok to me.   Also, while we are discussing the API and documentation of v1model.p4 in another PR, seeing the params for the hash API confuses me a bit.   See below.

```
 * @param O          Must be a type bit<W>
 * @param D          Must be a tuple type where all the fields are bit-fields (type bit<W> or int<W>) or varbits.
 * @param T          Must be a type bit<W>
 * @param M          Must be a type bit<W>
```

Seeing "W" in each param for `bit<W>` I tend to think "W" is a constant value which is same for all params.  For example if W=12, I assume, each param is `bit<12>`.   Is that correct?

If "W" is different, then unambiguous descriptions of params should be `bit<W1>`, `bit<W2>`, etc.

**Comment by jafingerhut** [comment]
The "type variables" O, T, and M are all different, so none of them are restricted to be the same bit width as each other.  I don't see any problem giving the bit widths different names if that makes it clearer.  You want to open a PR for that?

**Comment by hesingh** [comment]
Soon as I entered my prior note, I realized the template variable are different and thus the `bit<W>` are different - thanks for clarifying.   When, we open the PR, we should also develop a second hash function.  What should the second function be called?

Would it be possible for your to open a PR for this work?  I am juggling a few other balls right now?

**Comment by hesingh** [comment]
What about hashZeroBase() for second function?

**Comment by mbudiu-vmw** [comment]
v1model is supposed to model the p4-14 architecture. It has inherited all APIs from that design.
Ideally we should not enhance it, but we should design better APIs for PSA.

**Comment by hesingh** [comment]
Ok, thanks.  However, aren't many P4-16 programs also using v1model.p4 in which case, we could consider adding a second has API to v1model.p4?

**Comment by hesingh** [comment]
Ok, let's change the API for psa.p4 and thereafter, change the behavioral-model which implements the hash.

**Comment by jafingerhut** [comment]
If you are interested in creating an issue on the p4lang/p4-spec Github repository, marked for a proposed change (or perhaps addition) to PSA, with the proposed signature and a precise description of its behavior, the Arch working group can consider it.  I make no promises whether they will find it enough of a difference from the existing one to motivate making the change.

If the existing API is confusing, I would recommend improving any documentation you find lacking or confusing about the existing API.  From the existing PSA documentation for the Hash extern here: https://p4.org/p4-spec/docs/PSA.html#sec-hash-algorithms it seems pretty clear to me how max is used.

Now if you want to change the _name_ of the parameter `max` to something clearer, that is arguably not even really a signature change, just a clearer name that might help people understand how the parameter is used.  It doesn't break anyone.

**Comment by hesingh** [comment]
There is other churn regarding hashes in P4 on hardware that could use clarification for IPv6.

Practical deployments commonly use a symmetric hash which takes for input, a sum of src and dst IPv6 addresses of a packet.  Let's say, the switching asic runs a 64-bit machine internally for hashing.
One cannot add src+dst which are 128-bits wide.

So, do we use a tuple with bit Slices?  
Example, `{src[127:64]+dst[127:64], src[63:0]+dst[63:0]}`
Don't we use the lower bits of the IPv6 address first and then the upper? 

An example with such details would be good to add to P4 code or other documentation.

**Comment by hesingh** [comment]
For IPv6, I would also add an implementation of symmetric hash to simple_switch assuming a 64-bit machine.

**Comment by jafingerhut** [comment]
The examples you describe seem to me better suited for some kind of tutorial or book teaching P4, rather than a specification document.  I know the specifications have some example code, and I am not in principle against that, obviously, given how much of it I have written, but at some point you need the reader's brain to kick in and start solving some of the problems they encounter :-)

**Comment by jafingerhut** [comment]
@hesingh Can this issue be closed now?  I read through the comments, and don't see anything I would call a bug, just ideas for documentation improvements (which have been merged in recently for v1model as of now), and ideas for new extern functions that do not exist yet.

**Comment by hesingh** [comment]
We can close this one - thanks.  I just did.
