### ISSUE TITLE
Question: Is llvm Class PointerIntPair<> compatible with BDW GC?

### ISSUE THREAD

**Issue by jde1** [p4lang/p4c#1880]
PointerIntPair<> appears to store a 3 bit int in the lower3 lsb of a pointer. Theoretically, this could cause double frees. (This is pure speculation on my part, as I do not know the internals of the CG). In my test case, about 1 in 6 times, I have a nonsense crash, and about 1 in 20, I see a "Duplicate large block deallocation" abort in GC_freehblk(). Please forgive me if this is a dup. I did search for "GC" and "bdw" before posting.

**Comment by mbudiu-vmw** [comment]
Theoretically the GC is conservative, which means it will never delete a memory block that may have a reference. Using such strange pointers can only cause false positives, not false negatives. In our codebase we never call free, so the conservative approximation holds.

**Comment by ChrisDodd** [comment]
The GC recognizes any byte pointer to the interior of any object as a pointer by default, and we don't disable that, so changing the bottom 3 bits of a pointer should not have any effect on it being recognized as a pointer by the GC.  If you munge any other bits (ie, if you try to store anything in the unused top 16 bits of a 64-bit pointer) then problems will occur.  Similarly, if you store a pointer into a non-8-byte-aligned memory location, it won't be recognized (in memory) as a pointer.

**Comment by jde1** [comment]
Thanks. Regarding your last point, if a Pointer-Int (i.e. an unaligned byte
pointer) points to a pointer-to-X, will the CG still find the live
reference to X?
