### ISSUE TITLE
Extern object instances not emitted by p4c-bm2-ss

### ISSUE THREAD

**Issue by isaac-ped** [p4lang/p4c#1882]
When compiling a p4 program with p4c-bm2-ss which uses an extern object and method, the call to the extern method is added to the output json, but the extern instantiation is not added to `extern_instances`.

Attempting to run the behavioral model with the created dataplane results in an error:
```
Calling target program-options parser
Invalid reference to object of type 'extern' with name 'extr_0'
```

Manually adding the extern instance to `extern_instances` in the json works around the issue.

With the extern defined in https://github.com/p4lang/behavioral-model/blob/master/tests/test_extern.cpp implemented in a modified version of the simple_switch, the following code excerpts reproduce the issue (full code attached):

In p4:
```p4
extern ExternCounter {
    ExternCounter();
    void increment();
}

control SampleProcess(inout headers_t hdr, inout metadata_t meta, inout standard_metadata_t smd) {
    ExternCounter() extr;

    apply {
        extr.increment();
    }
}
```

Produces:
```json
  "actions" : [
    {
      "name" : "act",
      "id" : 0,
      "runtime_data" : [],
      "primitives" : [
        {
          "op" : "_ExternCounter_increment",
          "parameters" : [
            {
              "type" : "extern",
              "value" : "extr_0"
            }
          ],
          "source_info" : {
            "filename" : "Sources/ExternObj.p4",
            "line" : 24,
            "column" : 8,
            "source_fragment" : "extr.increment()"
          }
        }
      ]
    }
  ],
...
  "extern_instances" : [],
```

Adding the object:
```json
    {
      "type" : "ExternCounter",
      "name" : "extr_0",
      "id" : 0
    }
```
to `extern_instances` resolves the error.

P4 code and output json: 
[ExternObj.zip](https://github.com/p4lang/p4c/files/3109547/ExternObj.zip)

**Comment by jderuiter** [comment]
As I was looking at a seemingly similar issue (#1897) I had a quick look at this. It seems that the declaration of `extr` is an instance declaration (as opposed to variable declaration). Instance declarations are ignored in `DiscoverStructure` of the BMV2 backend and therefore do not end up in `structure` so this might explain why it does not end up in the JSON file. It seems that instances of externs are not supported at the moment. I'd be happy to help with adding this, but I'm not sure what the best (correct) approach would be here.

**Comment by mbudiu-vmw** [comment]
I think that the back-end handles each type of extern separately, but it doesn't do anything for the externs that are not part of the v1model architecture description.

**Comment by antoninbas** [comment]
I thought someone added the `--emit-externs` flag to p4c-bm2-ss specifically for that purpose (unconditionally emitting generic extern "code" in the JSON even if the extern is not part of v1model.p4). Are you saying that this flag is broken?

**Comment by mbudiu-vmw** [comment]
I don't know if the flag was used for this test.

**Comment by isaac-ped** [comment]
I did include the --emit-externs flag in the compilation

**Comment by isaac-ped** [comment]
To provide a bit more detail, the `--emit-externs` flag does successfully cause p4c to emit extern functions, however extern objects are still not emitted.

Without the `--emit-externs` flag, p4c-bm2-ss fails at compilation time with the message:
```
ExternObj.p4(10): [--Werror=unknown] error: increment: Unknown error Unknown extern method increment from type ExternCounter
```

**Comment by isaac-ped** [comment]
Unfortunately, this fix did not completely solve the issue for me.
With the updated version of p4c, the `extern_instances` list produced is:
```json
  "extern_instances" : [
    {
      "name" : "SampleProcess.extr",
      "id" : 0,
      "type" : "ExternCounter",
      "attribute_values" : []
    }
  ],
```
including the name `SampleProcess.extr`

Elsewhere in the produced Json, the extern object is referenced by the name `extr_0`, not `SampleProcess.extr`:

```json
      "primitives" : [
        {
          "op" : "_ExternCounter_increment",
          "parameters" : [
            {
              "type" : "extern",
              "value" : "extr_0"
            }
          ],
          "source_info" : {
            "filename" : "ExternObj.p4",
            "line" : 24,
            "column" : 8,
            "source_fragment" : "extr.increment()"
          }
        }
      ]
```

startup of bmv2 fails when using this json file:
```
Calling target program-options parser
Invalid reference to object of type 'extern' with name 'extr_0'
```
