### ISSUE TITLE
Counter/meter/register shared between controls does not work

### ISSUE THREAD

**Issue by ChrisDodd** [p4lang/p4c#1908]
The attached test case used to work, but recent changes cause the compiler to give errors about the counter conflicting with itself

**Comment by ChrisDodd** [comment]
[counter6.p4](https://github.com/p4lang/p4c/files/3125415/counter6.p4.txt)
[counter6.stf](https://github.com/p4lang/p4c/files/3125416/counter6.stf.txt)

**Comment by jafingerhut** [comment]
The counter6-first.p4 P4_16 program created from P4_14 to P4_16 conversion has a separate control `processA` and `processB` for each of the corresponding controls in the P4_14 program, but each of those has its own independent "copy" of the counter `cntDum` instantiated within it.

From that starting point, it is already not equivalent in behavior to the P4_14 program, which has only a single counter `cntDum`.  Am I getting that right?

If so, it seems like the correction should be in the P4_14 to P4_16 translation, perhaps by having only a single instantiation of `cntDum` at the top level that both controls `processA` and `processB` call its `count` method on.

**Comment by ChrisDodd** [comment]
Yes, that would be correct.  That is the way it used to work, but it changed some time fairly recently.

**Comment by jafingerhut** [comment]
Do you have a version of p4c that it used to work?  Out of curiosity, I have looked for one, about every month in 2019, and about every 3 months before that in 2018 and late 2017, and every one of the versions I tried auto-translated P4_14 to P4_16 in the same way for program counter6.p4

**Comment by mbudiu-vmw** [comment]
This happens in the conversion from p4-14 to p4-16.

**Comment by ChrisDodd** [comment]
I've narrowed down the problem to

    commit 7fbe8d3ad56b056f544c8f5907a2227459dab05c
    Author: Antonin Bas <antonin@barefootnetworks.com>
    Date:   Tue Apr 9 09:58:10 2019 -0700

        Detect duplicate names in P4Info (#1844)
    
        * Detect duplicate names in P4Info

prior to this change, the attached program works fine with the barefoot backend (the only place we'd been testing this sort of thing previously, apparently), while afterwards it give the error

    [--Werror=duplicate] error: Name 'cntDum' is used for multiple objects in the P4Info message
    [--Werror=duplicate] error: Found 1 duplicate name(s) in the P4Info
    ./p4c FAILED

Looking into it a bit more, it seems that we have some code working around the duplication in the barefoot backend, but after this change, it fails in the frontend and never gets to the backend.

In any case, the duplication looks to be a bug in the P4_14->16 conversion.

**Comment by mbudiu-vmw** [comment]
The error just flags the fact that two counters have the same name, but you should not have two counters, there should be just one.

**Comment by mbudiu-vmw** [comment]
This also suggests that the barefoot back-end has a bug, since it was treating two different counters as one.

**Comment by jafingerhut** [comment]
I think Chris's earlier comment implies that they have an intentional work-around for this bug in P4_14 to P4_16 translation.  The workaround was broken when recently p4c's P4Info generation was tightened up to fix what looks like a real bug -- there should not be two instances with the same global name.

**Comment by ChrisDodd** [comment]
So I'm experimenting with just making all (non-direct) counters/meters/registers global instead of in the control that uses them.  That seems to avoid this problem and is simpler than trying to figure out which ones are shared between controls.  It doesn't seem to break anything so far...

**Comment by jafingerhut** [comment]
It certainly matches the P4_14 semantics, for sure, and avoids worrying about corner cases of whether something is shared between controls or not.

The same could be done for action_profile and action_selector.

**Comment by ChrisDodd** [comment]
action profiles and selectors are already done in the global scope.  extern instances actually have a per-extern callback to decide whether instances should be global or local to the control.
