### ISSUE TITLE
Can p4c handle default parameter values for packages that are controls with type variables?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1914]
Attached is a program that tries to make one of the package parameters have a default value for one parameter.  I have tried a few variations, but nothing I have thought of enables this program to compile using `p4test`.

Should this be possible?  If so, what is the syntax?

FYI, this is related to a possible change/enhancement to the PSA architecture definition Calin and I are mulling over.  It would be nice if this were legal to do in some way.

[default-package-params.p4.txt](https://github.com/p4lang/p4c/files/3129630/default-package-params.p4.txt)

**Comment by hanw** [comment]
Similar issue reported here? https://github.com/p4lang/p4c/issues/1639

**Comment by jafingerhut** [comment]
Closing this one, as it does look like it is probably a duplicate of that earlier issue.

**Comment by jafingerhut** [comment]
Had a chat with Mihai, who I believe mentioned that he thought these issues were different.  Re-opening this one, in case they are different.  Feel free to close as a duplicate if I've misjudged this.

**Comment by jafingerhut** [comment]
Attaching 3 separate minor variants of the P4_16 program attached to this issue originally.  The latest version of p4c as of 2020-Jun-14 gives compile time errors for all 3 variants.  I am happy to try other variants if people can suggest what should work, if there is anything that currently does.

```
$ ./compile.sh 
+ p4c --version
p4c 1.2.0 (SHA: ebd446fac BUILD: DEBUG)
+ p4c --target bmv2 --arch v1model default-package-params-try1.p4
default-package-params-try1.p4(31):syntax error, unexpected IDENTIFIER "H"
control EmptyVerifyChecksum(inout H
                                  ^
error: 1 errors encountered, aborting compilation
+ p4c --target bmv2 --arch v1model default-package-params-try2.p4
In file: /home/andy/p4c/frontends/p4/specialize.h:50
Compiler Bug: /home/andy/p4c/frontends/p4/specialize.h:50: Null insertion

+ p4c --target bmv2 --arch v1model default-package-params-try3.p4
default-package-params-try3.p4(49): [--Werror=not-found] error: H: declaration not found
                       VerifyChecksum<H, M> vr = EmptyVerifyChecksum<H, M>(),
                                                                     ^
default-package-params-try3.p4(49): [--Werror=not-found] error: M: declaration not found
                       VerifyChecksum<H, M> vr = EmptyVerifyChecksum<H, M>(),
```
[p4c-issue-1914.zip](https://github.com/p4lang/p4c/files/4777248/p4c-issue-1914.zip)

**Comment by jafingerhut** [comment]
Looking at the history of this issue further, it appears that issue https://github.com/p4lang/p4c/issues/2019 has a smaller test case and some analysis of the root cause of this issue.

**Comment by mbudiu-vmw** [comment]
Looks like this one is solved.
