### ISSUE TITLE
Modify STF to allow ignoring x bytes starting at position y in expect output

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#1921]
A hashed value is being used for field in STF expected packet.   The behavioral-model hash returns a different hashed value with multiple invocations of the same hash.  Therefore if the hashed value is used for a field in expected output, the match fails.  The solution is to allow STF to to ignore x bytes starting at position y in expect packet.  We can use a new symbol to denote bits to be ignored.

**Comment by ChrisDodd** [comment]
You can already use `*` characters in expect for don't care --  There's lots of existing .stf files that do that (see p4_14_samples ternary_match4.stf, for example)

**Comment by hesingh** [comment]
@ChrisDodd thanks!
