### ISSUE TITLE
PSA back end assignments in ingress apply block not represented in BMv2 JSON file

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1923]
When compiling a PSA program, if there are assignment statements in the ingress apply block directly, they do not become represented by code in the BMv2 JSON file at all.  A simple workaround is to take such assignment statements and put them into an action, then call the action.

I would bet this is because of this commented out line in the file psaSwitch.cpp:
```
// new P4::SynthesizeActions(refMap, typeMap, new SkipControls(&non_pipeline_controls)),
```
It looks like uncommenting that line alone is not enough to fix this issue.

The attached program and STF file currently fail if you try to run them as a test because of this issue -- the call to send_to_port has code to represent it in the BMv2 JSON file, but the assignment statements in the ingress apply block do not.

[psa-simple-reflector-bmv2.p4.txt](https://github.com/p4lang/p4c/files/3146776/psa-simple-reflector-bmv2.p4.txt)
[psa-simple-reflector-bmv2.stf.txt](https://github.com/p4lang/p4c/files/3146777/psa-simple-reflector-bmv2.stf.txt)

**Comment by mbudiu-vmw** [comment]
@hanw: I suspect you have commented-out that pass. Do you know of any reason why we cannot remove this comment?

**Comment by hanw** [comment]
I am working on a PR to fix this issue. should be ready later today.

**Comment by hanw** [comment]
https://github.com/p4lang/p4c/pull/1964

**Comment by jafingerhut** [comment]
Fixed with PR https://github.com/p4lang/p4c/pull/1970 which was same code as Han's #1964 with different test program.
