### ISSUE TITLE
Why does v1model have separate structs for types H and M?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1928]
@mbudiu-vmw @ChrisDodd This is not an urgent question -- more of a curiosity on my part on the origins of these things, in case there is anything I may learn from the answer.

v1model has separate types H and M, where H is intended to contain only headers, header stacks, and header_union values, and M can contain anything (including headers in P4_16, although that seems very uncommon to want to have header types inside of M by P4 developers, given that H is the more "natural" place to put them).

I realized that the only reason PSA has these as separate types is because it was copied from v1model.

I don't think the answer is "because of the way P4_14 is designed", because nothing in P4_14 seems to require you to have H and M separate in P4_16 architectures, not even for the purposes of auto-translation from P4_14 to P4_16+v1model.  There could be a single type M that combines together everything one would put into types H or M today.

The answer might be nothing deeper than: "It seemed like a good idea to keep headers separate from everything else".

**Comment by mbudiu-vmw** [comment]
The intent was to separate the headers that are supposed to come from the parser from all the other metadata that may be initialized an used in various different places. It also makes the job of the compiler marginally simpler.

**Comment by jafingerhut** [comment]
So is it an intended part of the existing v1model implementation that you can extract into headers that are defined as fields of type M, and they are passed from the parser to the ingress control just fine?  Or is that perhaps something that just accidentally works?  I have verified that this does work with latest behavioral-model and p4c code with a P4_16+v1model arch program as of 2019-May-10.

**Comment by mbudiu-vmw** [comment]
There cannot be anything specific to this in the front end. Perhaps some backend code takes advantage of this.

**Comment by mbudiu-vmw** [comment]
Also, notice that in the parser the H argument is out. And originally M arguments for some controls were just in, but they have all been changed to inout.

**Comment by jafingerhut** [comment]
Closing this issue, since it was a question about the current design, not a bug, and it has been answered.
