### ISSUE TITLE
p4_14include directory

### ISSUE THREAD

**Issue by HelenHZhang** [p4lang/p4c#1942]
I am trying to compile p4c with default options. I found out the following symlink is empty. Could anyone explain to me the reason?

backends/p4test/p4_14include -> <my build path>/build/p4_14include
backends/ebpf/p4_14include -> <my build path>/build/p4_14include
backends/bmv2/p4_14include -> <my build path>/build/p4_14include

However, "p4_14include" does not exist in my "build" directory.

simple "grep" result:
----
p4c/tools/driver/p4c.in:os.environ['P4C_14_INCLUDE_PATH'] = os.path.join(artifacts_dir, "p4_14include")
p4c/frontends/common/options.cpp:const char* p4_14includePath = CONFIG_PKGDATADIR "/p4_14include";
p4c/frontends/common/options.cpp:        snprintf(p, buffer + sizeof(buffer) - p, "p4_14include");
p4c/frontends/common/options.cpp:        if (!setIncludePathIfExists(p4_14includePath, buffer)) {
p4c/frontends/common/options.cpp:            snprintf(p, buffer + sizeof(buffer) - p, "../p4_14include");
p4c/frontends/common/options.cpp:            setIncludePathIfExists(p4_14includePath, buffer);
p4c/frontends/common/options.cpp:            + " -I" + (isv1() ? p4_14includePath : p4includePath) + " " + file;
p4c/frontends/common/options.h:extern const char* p4_14includePath;
p4c/backends/p4test/CMakeLists.txt:  COMMAND ${CMAKE_COMMAND} -E create_symlink ${P4C_BINARY_DIR}/p4_14include ${CMAKE_CURRENT_BINARY_DIR}/p4_14include
p4c/backends/ebpf/CMakeLists.txt:  COMMAND ${CMAKE_COMMAND} -E create_symlink ${P4C_BINARY_DIR}/p4_14include ${CMAKE_CURRENT_BINARY_DIR}/p4_14include
p4c/backends/bmv2/CMakeLists.txt:  COMMAND ${CMAKE_COMMAND} -E create_symlink ${P4C_BINARY_DIR}/p4_14include ${CMAKE_CURRENT_BINARY_DIR}/p4_14include

Thanks
Helen

**Comment by jnfoster** [comment]
I assume the first block of text is meant so show us some symbolic links inside of the `p4c` repository, or perhaps the `build` subdirectory? 

If yes, are they really pointing to `/build/p4include`? That would be surprising unless `p4c` repository had been checked out at the root of your file system.

**Comment by jnfoster** [comment]
For example, here's a precise sequence of commands that shows what I have:
```
~% cd p4c
~/p4c% pwd
/Users/nate/p4c
~/p4c% ls -al build/backends/bmv2/p4_14include 
lrwxr-xr-x  1 nate  staff  41 Mar 26 16:31 build/backends/bmv2/p4_14include -> /Users/nate/shared/p4c/build/p4_14include
```

**Comment by HelenHZhang** [comment]
Yes, the first part of log shows the symbolic link. when I removed my specific build path, it should be:

lrwxr-xr-x  1 helzhang  staff  79 May 17 10:34 /Users/helzhang/Documents/hg/third-party/may-ship/p4c/target/build/backends/p4test/p4_14include -> /Users/helzhang/Documents/hg/third-party/may-ship/p4c/target/build/p4_14include

**Comment by jafingerhut** [comment]
I have a build of the most recent version of p4c source code on an Ubuntu 16.04 Desktop Linux system, and it also has symbolic links named p4_14include that "point at" a non-existent directory.

There are also several symbolic links named p4include that point at an existing directory.

I can still compile P4_14 programs without errors in this state.

Thus, as far as I can tell, the links named p4_14include are unnecessary.  Perhaps they need not be created at all?

**Comment by ChrisDodd** [comment]
They're used for backend-specific P4_14 include files.  The default bmv2 and ebpf backends don't have any, mostly as they only have minimal support for P4_14 in the first place.  Other backends with more extensive backwards compatibility for P4_14 extensions use them.

As long as you never try to compile a P4_14 program with an \#include \<...\> of such an extension, the fact that none are there should not be a problem.

**Comment by jafingerhut** [comment]
Closing this issue, as it seems the questions were answered.  No follow-up questions or comments have been added for over 3 years.
