### ISSUE TITLE
Bit Shifting on A Very Large Bit Vector

### ISSUE THREAD

**Issue by aatish17varma** [p4lang/p4c#1944]
Hello,

I was wanting to do bit shifting on a 2147483648 bit-vector, but I noticed that the P4 compiler would return a compilation error stating that "Width cannot be negative or zero". But my bit-vector width was neither negative nor zero. I referred to the P416 language specification which states that "P4 architectures may impose additional constraints on bit types: for example, they may limit the max size". I then checked the BMv2 specification, which states that "For most of these fields, their is not strict requirement to bit-width". Do you know why I am getting this message? 

Attached is a screen shot of the error message and my code

Thanks
Aatish

<img width="714" alt="Screen Shot 2019-05-17 at 5 39 14 PM" src="https://user-images.githubusercontent.com/13193277/57973618-bbc89800-7979-11e9-93bf-0d7f7b0665b3.png">

[Bit_vector_error.pdf](https://github.com/p4lang/behavioral-model/files/3194364/Bit_vector_error.pdf)

**Comment by cc10512** [comment]
P4-16 spec, section 7.1.6.2:

A bit-string of width W is declared as: bit<W>. W must be an expression that evaluates to a compile-time known value (see Section 17.1) that is a **positive integer** greater than 0.

**Comment by antoninbas** [comment]
To be fair, it doesn't say it has to be a 32-bit integer. I would actually expect the compiler to treat it as an infinite precision integer (P4 type `int`).

**Comment by cc10512** [comment]
That is fair. We might be able to bump it to 64-bits fairly easily, however, at some point in the backend we need to limit it to some specific target value. As @jafingerhut said, no HW target will support such sizes. And it will be expensive to support in SW targets as well.

**Comment by aatish17varma** [comment]
Maybe a clearer specification of an int's bit width would help.
