### ISSUE TITLE
Missing GC library 

### ISSUE THREAD

**Issue by wangxiaoge** [p4lang/p4c#195]
When I ran ./bootstrap.sh, There was an error 'missing GC library'. I don't know what steps have I missed? Could you give me some guidance？

**Comment by mbudiu-vmw** [comment]
The software required for building is described in docs/README.md.

**Comment by mbudiu-vmw** [comment]
The #198 pull request moves the section describing the required software dependences into README.md (from docs/README.md). The GC library is described there.
