### ISSUE TITLE
bug in match_t output stream operator?

### ISSUE THREAD

**Issue by zma-barefoot** [p4lang/p4c#1953]
When `match_t` assumes its default value,

https://github.com/p4lang/p4c/blob/b806cecb70c19620acbb86c963d4f84b48c0a51f/lib/match.h#L33

the `<<` operator will simply print `0`.

https://github.com/p4lang/p4c/blob/b806cecb70c19620acbb86c963d4f84b48c0a51f/lib/match.cpp#L31-L48

Is this a bug? Shouldn't we print `*` (don't care) for the default value?

**Comment by ChrisDodd** [comment]
The default value is a special invalid/match nothing code (and returns false for operator bool -- every other pattern returns true).  So it doesn't really have a proper printable form.

**Comment by zma-barefoot** [comment]
I see. What's the recommended way of creating a don't care match?

**Comment by zma-barefoot** [comment]
If the default value means invalid/null, then the `<<` operator should probably have a `CHECK_NULL`, instead of outputting it as `0`.

**Comment by ChrisDodd** [comment]
A don't care would be something like `match_t(width, 0, 0)`,  where `width` is the width of the don't care.  So `match_t(4, 0, 0)` would print as `0x*`, while `match_t(12, 0, 0)` will print as `0x***`.  I don't recall why we wanted to the special "don't care" pattern -- perhaps just to catch improperly initialized match_t values.
