### ISSUE TITLE
Direct typed invocation gives error for duplicate value_set, but not table or counter?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1955]
Test cases for some statements about what P4_16 programs are correct
vs. incorrect when they use "direct type invocation", as explained in
Section 14.1 "Direct type invocation" of version 1.1 of the P4_16
language specification.

Using latest p4c source as of this commit:
```
$ git log -n 1 | head -n 3
commit b806cecb70c19620acbb86c963d4f84b48c0a51f
Author: fruffy <5960321+fruffy@users.noreply.github.com>
Date:   Thu May 23 23:26:23 2019 +0200
```

The program parser-dti-1-bmv2.p4 uses DTI twice on the same subparser,
and this subparser contains a value_set, which according to my reading
of the spec should be an erroneous program, and p4test agrees.

```
$ p4test parser-dti-1-bmv2.p4
parser-dti-1-bmv2.p4(78): [--Wwarn=uninitialized_use] warning: hdr.ethernet_1 may not be completely initialized
        subParser.apply(packet, hdr.ethernet_1, hdr.ipv4_1);
                                ^^^^^^^^^^^^^^
parser-dti-1-bmv2.p4(78): [--Wwarn=uninitialized_use] warning: hdr.ipv4_1 may not be completely initialized
        subParser.apply(packet, hdr.ethernet_1, hdr.ipv4_1);
                                                ^^^^^^^^^^
parser-dti-1-bmv2.p4(79): [--Wwarn=uninitialized_use] warning: hdr.ethernet_2 may not be completely initialized
        subParser.apply(packet, hdr.ethernet_2, hdr.ipv4_2);
                                ^^^^^^^^^^^^^^
parser-dti-1-bmv2.p4(79): [--Wwarn=uninitialized_use] warning: hdr.ipv4_2 may not be completely initialized
        subParser.apply(packet, hdr.ethernet_2, hdr.ipv4_2);
                                                ^^^^^^^^^^
parser-dti-1-bmv2.p4(57): [--Werror=legacy] error: ipv4_ethertypes: Duplicates declaration ipv4_ethertypes
    value_set<bit<16>>(8) ipv4_ethertypes;
                          ^^^^^^^^^^^^^^^
parser-dti-1-bmv2.p4(57)
    value_set<bit<16>>(8) ipv4_ethertypes;
                          ^^^^^^^^^^^^^^^
```

But when I try to use DTI twice on a sub-control that has a table, or
a counter, both of which have a control plane API like a value_set
does, there is no error.

Program control-dti-1-bmv2.p4 has a sub-control invoked twice via DTI
that contains a table.  The '-3' variant of the program has a counter
instead of a table in the sub-control.

Shouldn't p4test give an error for these programs, too, for a similar
reason that the program parser-dti-1-bmv2.p4 gives an error?

```
$ p4test control-dti-1-bmv2.p4
control-dti-1-bmv2.p4(77): [--Wwarn=uninitialized_use] warning: hdr.ethernet_1 may not be completely initialized
        subParser.apply(packet, hdr.ethernet_1, hdr.ipv4_1);
                                ^^^^^^^^^^^^^^
control-dti-1-bmv2.p4(77): [--Wwarn=uninitialized_use] warning: hdr.ipv4_1 may not be completely initialized
        subParser.apply(packet, hdr.ethernet_1, hdr.ipv4_1);
                                                ^^^^^^^^^^

$ p4test control-dti-3-bmv2.p4
control-dti-3-bmv2.p4(77): [--Wwarn=uninitialized_use] warning: hdr.ethernet_1 may not be completely initialized
        subParser.apply(packet, hdr.ethernet_1, hdr.ipv4_1);
                                ^^^^^^^^^^^^^^
control-dti-3-bmv2.p4(77): [--Wwarn=uninitialized_use] warning: hdr.ipv4_1 may not be completely initialized
        subParser.apply(packet, hdr.ethernet_1, hdr.ipv4_1);
                                                ^^^^^^^^^^
```
[parser-dti-1-bmv2.p4.txt](https://github.com/p4lang/p4c/files/3254029/parser-dti-1-bmv2.p4.txt)
[control-dti-1-bmv2.p4.txt](https://github.com/p4lang/p4c/files/3254031/control-dti-1-bmv2.p4.txt)
[control-dti-3-bmv2.p4.txt](https://github.com/p4lang/p4c/files/3254032/control-dti-3-bmv2.p4.txt)

**Comment by mbudiu-vmw** [comment]
If you use the `--p4-runtime-file` you will get errors.
For the parser you may be getting errors for the wrong reason... you should also get errors only when generating the runtime API. That may be a real bug. We know if it's a real bug if you cannot instantiate manually the parser twice without getting an error.

**Comment by mbudiu-vmw** [comment]
So it looks like indeed the parser inliner does not rename the value_set when creating a new instance; that's a bug.

**Comment by mbudiu-vmw** [comment]
This is the reproduction:
```
parser parserImpl(packet_in packet,
                  out headers_t hdr,
                  inout metadata_t meta,
                  inout standard_metadata_t stdmeta)
{
    subParser() p1;
    subParser() p2;
    state start {
        p1.apply(packet, hdr.ethernet_1, hdr.ipv4_1);
        p2.apply(packet, hdr.ethernet_2, hdr.ipv4_2);
        transition accept;
    }
}
```

**Comment by jafingerhut** [comment]
Thanks for correct diagnosis of the actual problem.  I should have looked more carefully at the intermediate compiler output to see what was going on.
