### ISSUE TITLE
Possible regression on old inlining bug

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1958]
I will attach a sample program, but it seems to be similar symptoms as an older issue filed and fixed earlier, but it must have regressed in the mean time.  I will add a test program that uses v1model rather than the older issue's custom prototype of the PSA include file, so perhaps easier to make this test program into a new automated test.

**Comment by jafingerhut** [comment]
The older issue that seems to have regressed was this one: https://github.com/p4lang/p4c/issues/794

Test program attached.  It gives error when run with latest 'p4test' as of 2019-May-23.
[issue1958.p4.txt](https://github.com/p4lang/p4c/files/3258238/issue1958.p4.txt)

**Comment by mbudiu-vmw** [comment]
This is actually a new bug, and it's a tricky one. We may need to amend the spec to make this work.
A control is instantiated and then an instantiation can be invoked using "apply()".

The question is what is the difference between an instantiation and an invocation. For example, if the control has an action A inside, is there a copy of A made per instantiation or per invocation? Today there's a copy made per instantiation. So if A uses a register, it must be the same for all invocations... To fix this we would need to copy actions and tables for each invocation of a control, not for each instantiation. The spec does not say anything about this really.

**Comment by jafingerhut** [comment]
I think I know what you mean by an instantiation -- a compile-time constructor call of a control, with compile-time constant expressions for all of its constructor parameters.

By an invocation, do you mean a run-time call of the control?  It seems no, because there is no way to make copies of tables or actions for each run-time call.

What do you mean by an invocation?

**Comment by jafingerhut** [comment]
OK, I think I get your question now.  By invocation, you mean that there can be two or more different apply() calls to the same control instantiation in the source code.

If I have that correct, then it seems to me that already today if there are no constructor parameters for a control that is instantiated once, but there are multiple apply() calls to it, each of those apply() calls is for "the same instance", i.e. the tables referred to by each of those apply() calls are the same, because the control instance is the same.

When you add constructor parameters to the mix, it seems like each instantiation of the control should get its own independent copies of all tables the control contains, and whatever constructor parameter values each instantiation is given, whether those are the same or different than other instantiations.

For any one instantiation of a control C1, whatever externs, tables, etc. instances that it has access to, should be the same instances for all apply() calls to C1.

**Comment by jnfoster** [comment]
I think Mihai is worried about a situation like this...

register<bit<8>>(256) reg1;
register<bit<8>>(256) reg2;
foo2() foo2_inst;
 apply {
   stdmeta.egress_spec = 0;
   foo2_inst.apply(hdr, meta, reg1);
   foo2_inst.apply(hdr, meta, reg2);
}

The straightforward implementation of this program -- passing references to
the registers -- doesn't seem possible on PISA.

But assuming the compiler can analyze all invocations why couldn't it
replace passing references to actual registers with an enum to disambiguate
which of the invocations we're in?

Concretely, for the example above, I'm thinking of code like this:

enum foo_call_t {
  reg1_call;
  reg2_call;
}

control foo(inout headers_t my_headers, inout metadata_t meta,
register<bit<8>> reg1, register<bit<8>> reg2, in foo_call_t fc) {
  action foo2_action() {
     ...
      if (fc == reg1_call) {
        reg1.read(val,index);
     } else {
        reg2.read(val, index);
    }
   ...
  }
  ...
}

This ensures that actions can be compiled in a way where all of the extern
objects they references are known, yet doesn't require changing the
semantics of control instantiation.

-N

**Comment by mbudiu-vmw** [comment]
Yes, I was confused. When you instantiate a control you have to allocate space for all the stateful objects, and that is tables and externs. So tables must be instantiated. Invocation is achieved with apply, and it binds the apply arguments. Unfortunately directionless arguments are not bound, but directly substituted (they have no assignment operation). So tables cannot really refer to such arguments...

Actions are somewhere in between, we could clone actions for each invocation. But this would make this issue with duplicate names even worse.

Nate's solution is not legal at this point because we cannot have conditionals in actions.

There is no easy workaround. The "right" solution would be to require all directionless arguments to be used in the constructor. This won't work anymore, since parsers have packet_in as a directionless argument. 

The only workable solution I can imagine is to require that multiple instances of anything have exactly the same values for all directionless arguments. Since no one found this bug so far, I expect that no one used this capability, so no one will suffer when we introduce this extra constraint.

This shows yet again how dangerous it is to create new language constructs, that no one has used before; you can very easily create something that does not really make sense, and not realize it until very late. Hopefully the practical impact of this will be small. Sigh.

**Comment by jafingerhut** [comment]
So in terms of potential spec changes, are you thinking of changing some entries in the 3rd table of Appendix F of the language spec, the one with column headings "This type" and "can be a run-time parameter to this callable thing"?

In particular, we could change the row "extern" and column "control" from "yes" to "no", and perhaps also the column "method"?

Maybe I'm not being imaginative enough, but perhaps leaving the row "extern" and column "parser" as "yes", since as you point out we allow packet_in to be passed there, and there can be no tables nor actions in parsers that seem to be complicating the interaction with run-time extern parameters.

There is still the issue of "packet_out" objects being passed as run-time parameters to deparser controls, which again maybe doesn't cause the same headaches because there can be no tables or actions in the deparser controls of the existing architectures.

Maybe "extern objects cannot be passed as run-time parameters to controls that contain tables"?

**Comment by jnfoster** [comment]
> Maybe "extern objects cannot be passed as run-time parameters to controls that contain tables"?

Another possible solution would be keep the current non-restrictions but specify which objects can be referenced in actions and tables -- e.g., only locally-instantiated externs. That seems cleaner and less disruptive to me.

Responding to @mbudiu-vmw: actions do support conditional expressions, so I think the essence of my example can still be encoded. Another possible way to go would be to lift the conditional up to the surrounding table -- i.e., extend the table keys with `fc : exact`, but then we'd have to do unholy and automagic things with the P4Runtime API.

**Comment by jnfoster** [comment]
In any event, let's not rush to judgment and clutter up the language with a hack. This is bread-and-butter compiler transformation stuff. Let's see if we can find a clean solution.

**Comment by hesingh** [comment]
Even if we allow conditionals inside an Action, the compiler internals may break up the conditional into two separate actions.  I agree with Nate about any rush to judgement for changing the spec.

**Comment by jafingerhut** [comment]
What is the fundamental reason that passing run-time parameters whose "values" are extern references/names to controls, and then using those inside of actions within that control, is more tricky than passing run-time parameters whose "values" are "inout bit<10> x"?

My guess is that because with the "inout bit<10> x" parameter, the compiler treats it something like this: "copy the caller's run-time parameter value into a 'storage place' foo that is allocated specifically for that instantiation of the control C.  Now every action of C that accesses the name x will access the 'place' foo, which will be copied back from foo into the caller's 'place' after the control C returns".

That doesn't work for extern references/names, because its execution model has no way to store an extern reference/name in a common "storage place" like the foo in my example above.  If it could, and actions of the control C could make method calls on an extern object through a "storage place", then it would be no more tricky to handle run-time extern parameters than non-stateful parameters.

Of course, having such a mechanism could easily raise other tricky issues -- I am not here suggesting that simply adding such references-to-extern-objects is a solution that raises zero problems.  I am only trying to clarify in my mind why this is tricky, but bit vectors and other "value types" are not.

**Comment by mbudiu-vmw** [comment]
Values of type extern do not have an assignment operation, so one cannot talk about copying their values. There are no references in P4. Even if there were, it is not clear that one can take a reference to an extern for some architectures - e.g., when compiling externs to hardware objects in an FPGA.

**Comment by mbudiu-vmw** [comment]
Here is a small example:
```
extern E { ... }

control C(E e) {
}

control D() {
    E(1) e1;
    E(2) e2;
    C() c;
    apply {
        c.apply(e1);
	c.apply(e2);
    }
}
```

**Comment by jafingerhut** [comment]
In the 2019-Sep-17 Language Design Work Group meeting, several people thought that the semantics of this were well defined, but it is simply that the p4c compiler's technique for implementing it fails in some cases when controls are parsers are applied multiple times with not all directionless parameter values the same as each other.

Attempting to write P4 code like this does not seem to be a high priority for P4 users that we are aware of, so an error or warning message from the compiler that such code is not currently supported by p4c may be a better use of p4c developer time, versus working on a full solution to support such programs right now.
