### ISSUE TITLE
removing unused passes

### ISSUE THREAD

**Issue by rhalstea** [p4lang/p4c#197]
After removing a .cpp and .h file for an unneeded pass I try to recompile and get a "No such file or directory" error. It looks like one of the ```unified-sources-<backend>-<n>.cpp``` doesn't get rid of the removed files.

Is there a better way to handle this than deleting the build folder, and rebuilding from scratch?

**Comment by rhalstea** [comment]
I did some background reading about unit builds and this is one of the common disadvantages traded off for faster builds.

I'm still curious if there is a way to rebuild without deleting the build folder, or does bootstrap always have to be run in this case?

**Comment by ChrisDodd** [comment]
Just rerunning bootstrap.sh should be enough to regenerate the Makefiles in this case -- its not necessary to actually delete the entire build directory.  Part of the problem is that bootstrap.sh is generating a couple of .am files that automake then processes; we have no rules in the Makefile to regenerate those files if something changes; we should look into doing that.

**Comment by sethfowler** [comment]
Yep. As I understand it from my discussion with Chris, automake adds rules to the output Makefile that trigger regeneration of the Makefile if one of the automake input files (Makefile.am etc) changes. We just need to detect this case and rerun the program that generates unified-compilation.am before automake is rerun. I'd expect that to be a straightforward matter of adding an additional make rule that does the job. I need to take a quick look at the structure of the rules automake generates, but I don't foresee any problems.

**Comment by sethfowler** [comment]
FWIW, I have patches that implement this, but I can't push them to Github because there's an issue with my fork of the p4c repository. I've contacted them and I'm hoping that'll get straightened out by tomorrow.

**Comment by rhalstea** [comment]
Thanks. 

Is your fork "temporarally unavailable" on GitHub? I had the same issue when p4lang/p4c.git went public. I contacted them, but they couldn't give a time estimate for the fix. After a day I just deleted the repo and re-forked it which seemed to work.

**Comment by sethfowler** [comment]
Yeah, that's my problem! That's a good idea; I'll delete and refork.
