### ISSUE TITLE
Constructor overloading

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1980]
Do we allow overloading constructor with the same arity but different type for constructor parameters in P4-16? See code below for an example.

```
#include <core.p4>

enum HashAlgorithm_t {
    CRC16
}

extern Polynomial<W> {
    Polynomial(W w);
}

extern Hash {
    Hash(HashAlgorithm_t algo);
    Hash(Polynomial<_> poly);
    bit<16> get<D>(in D data);
}

struct meta_t {
    bit<16> f0;
}

control ingress(inout meta_t meta) {
    Hash(Polynomial<bit<16>>(16w5678)) hash;
    apply {
        hash.get({meta.f0});
    }
}
```

**Comment by mbudiu-vmw** [comment]
You have to make the instantiation non-ambiguous:

```
Hash(poly = Polynomial<bit<16>>(16w567u8)) hash;
```

**Comment by hanw** [comment]
It is non-intuitive to the programmer that they have to specify the argument name to disambiguate the overloads. 

Can we leverage TypeInference to try to match the type of the parameter with the generic type specified in the architecture file? Apart from a more complex implementation for overload resolution, do you see any case that using type to resolve overload cannot be done?

**Comment by mbudiu-vmw** [comment]
In C++ I really don't like the overload resolution based on types; I find it a source of many ugly bugs. We don't have many implicit type casts - if we had these the problem would be even harder. But implementation complexity is indeed a significant concern. Type inference is already quite complicated.

Based on the rate at which we merge pull requests I don't think this will be done in a few years.

**Comment by jnfoster** [comment]
The language spec says the following:

Whe [sic] overloading is used, the compiler must be able to disambiguate at
> compile-time which method or function is being called, either by the number
> of arguments or by the names of the arguments, when calls are specifying
> argument names. Argument type information is not used in disambiguating
> calls.
>

**Comment by mbudiu-vmw** [comment]
So it may be unintuitive to C programmers, but the spec does say it.

**Comment by hanw** [comment]
I understand that it is said in spec that type is not used to disambiguate calls. I am asking why we made this decision.

**Comment by mbudiu-vmw** [comment]
The language has evolved gradually. Named arguments were added relatively recently, and we decided they are a good way to disambiguate calls. They don't need to be the only way. Previously we used the number of arguments only.

**Comment by mbudiu-vmw** [comment]
In the future we can add type-based disambiguation if anyone contributes the code.
