### ISSUE TITLE
How to delete MethodCallStatement from IndexedVector ?

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#1981]
In p4c ir.def, notice ParserState has ```optional inline IndexedVector<StatOrDecl>   components;  ```.
I am interested in deleting one of the components shown below.

```
[1542] IndexedVector<StatOrDecl>
  [1280] MethodCallStatement
    methodCall: [1279] MethodCallExpression
      type: [1263] Type_Unknown
      method: [1272] Member member=extract
        type: [1263] Type_Unknown
        expr: [1271] PathExpression
          type: [1263] Type_Unknown
          path: [1270] Path name=packet absolute=0
      typeArguments: [1278] Vector<Type>
      arguments: [1277] Vector<Argument>
        [1276] Argument name=<null>
          expression: [1275] Member member=eth
            type: [1263] Type_Unknown
            expr: [1273] PathExpression
              type: [1263] Type_Unknown
              path: [1274] Path name=hdr absolute=0
```

Is it even possible to delete the component above using removeByName?  What "name" would one use? I see removeByName works off of IDeclaration, but IDeclaration is not available for a Statement.

 If not removeByName, I see IndexedVector has erase() but erase() needs an iterator.  How do I get an iterator?

**Comment by mbudiu-vmw** [comment]
To delete something return null in the corresponding method (e.g., preorder(IR::MethodCallStatement).

**Comment by hesingh** [comment]
Is there any way to delete MethodCallStatement using IndexedVector methods?  

Understood about returning null in the preorder method.

**Comment by hesingh** [comment]
@mbudiu-vmw Thanks much for the alternative solution.  Appreciate the expedited reply on a weekend!

**Comment by mbudiu-vmw** [comment]
This class extends vector, so all C++ methods for std::vector should work

**Comment by hesingh** [comment]
Incidentally, it would be good to add a comment in IndexedVector code around removeByName to say, the method supports only Declarations.  The IndexedVector is being used with IR::StatOrDecl and new folks start searching all over to see where a Statement may have a name for use with removeByName.
