### ISSUE TITLE
Dangling else

### ISSUE THREAD

**Issue by dragosdmtrsc** [p4lang/p4c#1992]
Hi, I have a problem with a dangling else when converting from p4-14 to p4-16. The converter essentially modifies the semantics of the initial p4-14 program in a subsequent pass.
Sample p4-14 code (dangling.p4):
```
header_type data_t {
    fields {
        f1 : 32;
        f2 : 32;
    } }
action _nop() {}
metadata data_t m;
table t1 { actions { _nop; } }
table t2 { actions {  _nop; } }
parser start {
    return ingress; }
control ingress {
    if (m.f1 == 32w0) {
        if (m.f2 == 32w0) {
            apply(t1);
        }
    } else { 
        apply(t2);  
    }
}
```
`p4test --top4 FrontEndLast --std p4-14 dangling.p4 && mv dangling-*FrontEndLast* dangling16.p4` produces the following ingress code:
```
if (meta.m.f1 == 32w0) 
   if (meta.m.f2 == 32w0) 
      t1_0.apply();
else
   t2_0.apply()
```
which contains a dangling else. When running again `p4test --top4 FrontEndLast dangling16.p4` the ingress code looks like this:
```
if (meta.m.f1 == 32w0) 
   if (meta.m.f2 == 32w0) 
       t1.apply();
   else 
       t2.apply()
```
which is different from the original p4 14 program.

Quick workaround: modified ToP4 pass to add braces to if and else whenever the inner statement is not a BlockStatement and now it appears to work

**Comment by jafingerhut** [comment]
I verified with this command run on the P4_14 program dangling.p4 above, using this command with the latest p4c code as of 2019-Jul-10:
```
p4test --top4 FrontEndLast --std p4-14 dangling.p4 --pp dangling-xlated.p4
```
It is true that the code printed to the file dangling-FrontEnd_54_FrontEndLast.p4 is missing proper braces, and does not match the behavior of the P4_14 program.

However, the output file dangling-xlated.p4 from the command above _does_ contain the braces needed to make that program match the original behavior.

It would be nice if the intermediate file dangling-FrontEnd_54_FrontEndLast.p4 could be fed as input to p4c and have the same behavior as the original, too.  If you have a change you have made to p4c that seems to work, you are welcome to create a PR and see how it goes in code review, if you or an organization you belong to are a P4.org member (or perhaps the requirement is now that one be a Linux Foundation member?).

**Comment by mbudiu-vmw** [comment]
I will always add braces. This will change quite a few reference outputs.
