### ISSUE TITLE
Add elements of header stack?

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#2008]
I am using v1model and p4-16.  P4 does not support a for loop.  If I have a header stack with headers just comprising of a 32-bit field.  How would I add all the elements of the header stack/array?

**Comment by jafingerhut** [comment]
Again, the best workaround I know of for the limitation of not having loops is to "unroll them by hand", because except for parser loops, the compiler doesn't do it for you.  Using some other programming language like Python, or whatever you like, to print out repetitive P4_16 code can be helpful to avoid tedious repetitive typing here, and avoid copy/paste mistakes.

You can have one action that adds 1 header, another that adds 2, another that adds 3, etc., and choose between them at run time via a table lookup.

**Comment by hesingh** [comment]
Wow, if the header stack array has 50 elements, we use 50 actions...

**Comment by jafingerhut** [comment]
I would guess that for at least some of the highest speed targets, you could easily run out of room in the total amount of packet headers and user-defined metadata that can be manipulated per packet, before you got to 50 elements, unless those elements are quite small.

But yes, you would need 50 actions in the case you are describing.

**Comment by hesingh** [comment]
I sure would like the authors of the paper and talk presented in 2019 at Stanford P4 Workshop to open up their source code.  A URL to the paper is below.  I am trying to implement Algorithm 1 on page 4 of the paper, using IPv6 and v1model.

https://arxiv.org/pdf/1903.06701.pdf

See this text from the paper where the index 128 comes from.

"Based on our measurements (Figure 2), we use 128 and 512 as the pool size for 10 and 100 Gbps, respectively.  The pool is mentioned in Algorithm."

The element is of bit<8> type if pool size is 128 - it's small.

**Comment by jafingerhut** [comment]
Asking in a Github issue for p4c is probably not the most effective place.  Send the authors email.  They may be restricted if the working code uses proprietary extensions, of course.  I also would not be surprised if they used multiple similar actions, perhaps not 128-way, but e.g. 32-way, with 4 ways handled via variable right/left shifts inside of the action.  People can get creative when they want the result, and are willing to jump through hoops to get it to work with existing tools.

**Comment by hesingh** [comment]
Understood.  

I wanted to highlight what are switch ML operations so one could think more and see what extensions to p4-16 would make sense.  It is jumping through hoops.

**Comment by hesingh** [comment]
A simpler solution exists.

Let's say, a vector has 32-bit elements.  Add a byte (for bmv2 byte alignment) fields to each element.  The field has 0 or 1 value akin to mpls bos.  The last element of the vector has the byte set to 1.  Then, the P4 parser recurses through the vector, the recursion has a termination condition, and the vector sum is computed and saved in metadata.
