### ISSUE TITLE
Handling of generic arguments with default values is incorrect

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#2019]
The following program does not compile; in particular, the type argument for the default value should be scoped to the `vr` parameter's type argument H.

```
control V<H>(inout H hdr);
control EmptyV<H>(inout H hdr) {
    apply { }
}

struct E {}

package S<H>(V<H> vr = EmptyV<H>());
S<E>() main;
```

**Comment by mbudiu-vmw** [comment]
This is the fundamental issue behind #1914

**Comment by mbudiu-vmw** [comment]
The bug is actually in the defaultArguments pass. It needs to substitute type variables when using the default argument value.

**Comment by jnfoster** [comment]
Yes, that makes sense.

**Comment by jafingerhut** [comment]
I would not call this issue urgent, but the P4 Architecture working group is actively meeting again, on Fridays, and looking at finishing an open source PSA implementation, while making some small changes to the PSA architecture specification based on the implementation work that is ongoing.  It is a nice-to-have if this feature of p4c would work.  It is more of a P4 developer convenience than a requirement, though -- it would enable the PSA architecture to be defined in a way that P4 developers do not need to provide about half a dozen controls as parameters to the top level package, in the common case when users do not need to override their default values.

**Comment by mbudiu-vmw** [comment]
You should assume it works and use the feature and I will try to find time to fix it.

**Comment by mbudiu-vmw** [comment]
I hope that this is now fixed. The fix itself is not complicated, but it revealed a few bugs in other places.
