### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#2021]
Compiling this program
```
#include <core.p4>

control C();
package S(C c);
const bit<8> x = 8w1;
control MyC() {
  apply {
    .x = 8w3;
  }
}
S(MyC()) main;
```
generates the following error message:
```
[--Werror=type-error] error: Expression 1 cannot be the target of an assignment
const bit<8> x = 8w1;
                 ^^^
```
I can imagine why the compiler is treating 1 as the left-hand side of an assignment, but it's pretty confusing...

**Comment by mbudiu-vmw** [comment]
constants should not be left-values; this is a bug.

**Comment by jnfoster** [comment]
I assume some compiler pass is replacing the occurrence of `.x` in `MyC` with `8w1`, leading to this error.

**Comment by mbudiu-vmw** [comment]
Yes, constant folding happens before type checking, so it blindly replaces x with 1.
We will have to refrain from doing this to expressions that are the left-hand side of an assignment.
