### ISSUE TITLE
Type error due to inference/substitution?

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#2036]
Compiling this program,
```p4
#include <core.p4>

//Architecture
parser C();
package S(C p);

//User Program
struct s {
  bit<8> x;
}

parser D(in s z) { 
  state start {
    transition accept;
  } 
}

parser E() {
  tuple<bit<8>> a = { 0 };
  s b = { 1 };
  D() d;
  state start {
    d.apply(a);
    d.apply(b);	
    transition accept;
  }
}

S(E()) main;
```
using `p4test` yields an error:
```
foo.p4(19): [--Werror=type-error] error: AssignmentStatement: Cannot assign a Tuple(1) to a struct s
  tuple<bit<8>> a = { 0 };
  ^^^^^^^^^^^^^
foo.p4(8)
struct s {
       ^
```
However, if we comment out either one of the `d.apply(...)` calls, it compiles fine.

My best conjecture is that type inference on the first occurrence is substituting one type for the other, which then causes a mismatch later on? 

This is also reminiscent of #1830.

**Comment by mbudiu-vmw** [comment]
We should not allow a tuple to be assigned to a struct. This happens because a the type of a list expression is in fact a tuple, and we allow list expressions to be assigned to structs. But we don't allow tuples to be assigned to structs...

Probably the solution is to introduce a new type internally for list expressions which can be unified with tuples and structs.

**Comment by jnfoster** [comment]
Actually, this variant of the program, which `p4test` accepts, should actually be rejected, right? Because we are using a variable whose type is a tuple in a place where a struct is expected.

```p4
#include <core.p4>

//Architecture
parser C();
package S(C p);

//User Program
struct s {
  bit<8> x;
}

parser D(in s z) { 
  state start {
    transition accept;
  } 
}

parser E() {
  tuple<bit<8>> a = { 0 };
  s b = { 1 };
  D() d;
  state start {
    d.apply(a);
    transition accept;
  }
}

S(E()) main;
```

**Comment by mbudiu-vmw** [comment]
Yes, this program is incorrect.
