### ISSUE TITLE
Can't find source file build/lib/unified_libp4ctoolkit_srcs_1.cpp

### ISSUE THREAD

**Issue by BDHU** [p4lang/p4c#2041]
I was following the README and installed all dependencies on Debian 8 with kernel version 3.16.0-6-amd64. When I executed cmake .. it shows the following error:

CMake Error at lib/CMakeLists.txt:80 (add_library):
  Cannot find source file:
     /home/edward/p4c/build/lib/unified_libp4ctoolkit_srcs_1.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

I've searched for a while but there isn't much information about this issue. Could the issue be related to OS distro? Thanks for any help!

**Comment by cc10512** [comment]
Unlikely it is related to the distro, we built p4c on Debian 8. 
That file is created when you enable the unified build. I have two suggestions for you to try:
1. Look in build/CMakeFiles/CMakeError.log and  build/CMakeFiles/CMakeOutput.log for more detailed messages on what happened and how come the files are not generated. You may be able to spot the error.
2. Disable the unified build when you run cmake: `-DENABLE_UNIFIED_COMPILATION=OFF`.
