### ISSUE TITLE
Ubuntu Linxu build problem for ebpf back end - missing kernel include file?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#2048]
Trying to build the latest p4c source code on a freshly installed Ubuntu 16.04 Linux system, with all updates from Canonical as of 2019-Oct-09, I get an error message while it attempts to compile p4c with ebpf back end, due to a missing include file.  Full error message below.

Perhaps it requires not only the "user-facing" kernel include files, but actual full kernel source code to be installed?  I haven't yet determined what changes might enable it to compile successfully.

```
[ 80%] Building CXX object backends/ebpf/CMakeFiles/p4c-ebpf.dir/unified_p4c_ebpf_srcs_1.cpp.o
In file included from /usr/include/stdio.h:33:0,
                 from /home/jafinger/p4c/backends/ebpf/p4c-ebpf.cpp:17,
                 from /home/jafinger/p4c/build/backends/ebpf/unified_p4c_ebpf_srcs_1.cpp:2:
/usr/src/linux-headers-4.15.0-65-generic/include/uapi/linux/stddef.h:2:34: fatal error: linux/compiler_types.h: No such file or directory
compilation terminated.
backends/ebpf/CMakeFiles/p4c-ebpf.dir/build.make:62: recipe for target 'backends/ebpf/CMakeFiles/p4c-ebpf.dir/unified_p4c_ebpf_srcs_1.cpp.o' failed
make[2]: *** [backends/ebpf/CMakeFiles/p4c-ebpf.dir/unified_p4c_ebpf_srcs_1.cpp.o] Error 1
CMakeFiles/Makefile2:1597: recipe for target 'backends/ebpf/CMakeFiles/p4c-ebpf.dir/all' failed
make[1]: *** [backends/ebpf/CMakeFiles/p4c-ebpf.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by cc10512** [comment]
Is that file present in any of the directories under `/usr/src/linux-headers-4.15.0-65-generic/include/`?

**Comment by jafingerhut** [comment]
Yes:
```
$ find /usr/src/linux-headers-4.15.0-65 | grep compiler_types
/usr/src/linux-headers-4.15.0-65/include/linux/compiler_types.h
```

**Comment by jafingerhut** [comment]
Actually, correction to my previous comment.  I was searching in a different directory than the one you asked about in my previous comment.

The correct answer is no for the directory with `-generic` in its name:
```
$ find /usr/src/linux-headers-4.15.0-65-generic | grep compiler_types
```
(i.e. no output, so no file with that name)

**Comment by jafingerhut** [comment]
This proposed PR is just me hacking and experimenting, but it might be useful: https://github.com/p4lang/p4c/pull/2049

**Comment by fruffy** [comment]
Building and testing ebpf via Ubuntu 16.04 is a big pain in general. I do not think the kernel tests work at all with the current version we have.
From what I have seen, these dependency issues are resolved by including and building with [libbpf](https://github.com/libbpf/libbpf) which includes all necessary header files and functions. I have some code but it is unfortunately bit-rotted. 

This bug seems to be in the compiler though. I do not understand why it would break, I do not remember any unusual include statements there. 
The only place "stddef.h" is included is in uthash.h which is part of the user test hashing library. But why would stddef.h cause issues in the first place, it is not part of the ebpf includes at all?

**Comment by mbudiu-vmw** [comment]
Forget about stddef, that was a mistaken fix which used the kernel include files for the g++ compiler.
I am fine checking if Ubuntu 16.04 is involved and skipping the tests.
The real solution is indeed to use libbpf and not copy random parts of the kernel headers into ebpf_kernel.h; that is not robust. That file should not exist.

**Comment by jafingerhut** [comment]
Closing this issue, as with the latest version of p4c after these two PRs were merged:
https://github.com/p4lang/p4c/pull/2049
https://github.com/p4lang/p4c/pull/2050

p4c again builds with no errors on a freshly installed Ubuntu 16.04 system, with the prerequisites described in the README.  Also, all tests pass.  That set of tests does not include 16 of the EBPF-specific tests, since the EBPF-specific p4c back end is not built, but this is expected.

**Comment by mbudiu-vmw** [comment]
Just a sec, my change should not disable the ebpf back-end, only the kernel-based tests of that back-end. You should still compile the back-end and run the user-level tests with this change. You can check whether `make check-ebpf` does something.

**Comment by jafingerhut** [comment]
I will check and report back.  I may have questions on how to tell whether it is doing what you hope it does, but I will start with determining whether it builds the p4c executable with ebpf in its name.

**Comment by jafingerhut** [comment]
OK, with a freshly installed Ubuntu 16.04 system, installing all p4c dependencies first (including llvm, behavioral-model and the things it needs), the executable p4c/build/p4c-ebpf _is_ built, and `p4c-ebpf -h` produces help output.  I have attached the output I see from the command `cd p4c/build ; make check-ebpf`.

Let me know if there is anything else that would help you verify that things are working as you expect.
[make-check-ebpf-output.txt](https://github.com/p4lang/p4c/files/3718869/make-check-ebpf-output.txt)

**Comment by mbudiu-vmw** [comment]
This looks very good. Thank you.
