### ISSUE TITLE
p4c make -j4 error 

### ISSUE THREAD

**Issue by kphf1995cm** [p4lang/p4c#2052]
![image](https://user-images.githubusercontent.com/24762583/66700945-29c08380-ecbc-11e9-95b0-1c49c97e1491.png)

**Comment by jafingerhut** [comment]
I do not know why that error occurred for you, but I do have a shell script that, starting from a freshly installed Ubuntu 16.04 or 18.04 Linux system, downloads and builds all software upon which p4c depends, e.g. protobuf, grpc, behavioral-model simple_switch, etc..  I have tested it many times over multiple years to ensure that it continues to work, most recently 2 days ago.

You can find it here: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-p4runtime.sh

**Comment by hesingh** [comment]
If -j4 fails, try -j2 and let us know if that works.  If -j2 works, try -j3 as well.

**Comment by kphf1995cm** [comment]
try make -j2 and make -j3, both failed

**Comment by kphf1995cm** [comment]
After install grpc
![image](https://user-images.githubusercontent.com/24762583/66717979-4c2dcc00-eda4-11e9-9b37-c36b54ce7695.png)

**Comment by kphf1995cm** [comment]
After rm /build, and redo cmake, I run make -j4 successfully
