### ISSUE TITLE
Is register support saving 128 bits value ?

### ISSUE THREAD

**Issue by kphf1995cm** [p4lang/p4c#2055]
typedef bit<128> IPv6Address;
register<IPv6Address>(100) port_ipv6;
I can not save 128 bits IPv6 address in register?

**Comment by ChrisDodd** [comment]
`register` needs a type argument.  So at the least you would need

    register<bit<128>>(100) port_ipv6;

however, I don't know if bmv2-ss supports such wide registers.

**Comment by kphf1995cm** [comment]
register<IPv6Address>(100) port_ipv6;
This is what I write.
I can pass p4c compile, but when I push json program to bmv2, I can not save 128 bits IPv6 address in register

**Comment by jafingerhut** [comment]
You say "this is what I write": `register(100) port_ipv6`.

Chris is saying that is incorrect P4_16 for the register you want.  You _should_ write something like this instead:
`register<bit<128>>(100) port_ipv6`

If you do not change your P4 program to look like that, you will never achieve your goal.

I have tested 128-bit wide registers in p4c and simple_switch using a line like the above, and it seems to be working as desired.

**Comment by jafingerhut** [comment]
I do not know what the maximum width of register supported by p4c plus simple_switch is, but I have also tested up to 1024-bit wide register array elements, and it all seems to be working.

**Comment by antoninbas** [comment]
There is no hard limit on bmv2 register values. The code uses arbitrary-precision numbers.

The Thrift RPC service for bmv2 however is limited to 64-bit registers: https://github.com/p4lang/behavioral-model/blob/master/thrift_src/standard.thrift#L159. Which means that the runtime_CLI is also limited to 64-bit registers.

The P4Runtime API does not have this limitation, but there is no implementation yet for bmv2: https://github.com/p4lang/PI/issues/376
