### ISSUE TITLE
Is p4c support ingress_timestamp?

### ISSUE THREAD

**Issue by kphf1995cm** [p4lang/p4c#2056]

**Comment by jafingerhut** [comment]
Yes.  Or more precisely, p4c plus behavioral-model simple_switch support ingress and egress time stamps.  Search for ingress_global_timestamp in this document for details: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md

**Comment by jafingerhut** [comment]
@kphf1995cm OK to close this issue?
