### ISSUE TITLE
make -j4 error /p4/p4c/test/gtest/load_ir_from_json.cpp:52:1: error: expected ‘}’ at end of input

### ISSUE THREAD

**Issue by jibanli** [p4lang/p4c#2060]
In file included from /root/p4/p4c/build/test/unified_gtest_base_sources_3.cpp:9:0:
/root/p4/p4c/test/gtest/load_ir_from_json.cpp:52:1: error: expected ‘}’ at end of input
 }  // namespace Test
 ^
/root/p4/p4c/test/gtest/load_ir_from_json.cpp: At global scope:
/root/p4/p4c/test/gtest/load_ir_from_json.cpp:52:1: error: expected ‘}’ at end of input
make[2]: *** [test/CMakeFiles/gtestp4c.dir/unified_gtest_base_sources_3.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/gtestp4c.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Linking CXX executable p4c-graphs
[ 98%] Built target p4c-graphs
make: *** [all] Error 2

**Comment by jafingerhut** [comment]
I do not know why that error occurred for you, but I do have a shell script that, starting from a freshly installed Ubuntu 16.04 or 18.04 Linux system, downloads and builds all software upon which p4c depends, e.g. protobuf, grpc, behavioral-model simple_switch, etc.. I have tested it many times over multiple years to ensure that it continues to work, most recently 2 days ago.

You can find it here: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-p4runtime.sh

**Comment by jibanli** [comment]
> I do not know why that error occurred for you, but I do have a shell script that, starting from a freshly installed Ubuntu 16.04 or 18.04 Linux system, downloads and builds all software upon which p4c depends, e.g. protobuf, grpc, behavioral-model simple_switch, etc.. I have tested it many times over multiple years to ensure that it continues to work, most recently 2 days ago.
> 
> You can find it here: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-p4runtime.sh

I found the error: find: ‘/root/.local’: No such file or directory. WHY...

**root@VM-0-13-ubuntu:/home/ubuntu/p4-guide/bin# ./install-p4dev-p4runtime.sh**
......
......
......
make[3]: Leaving directory '/home/ubuntu/p4-guide/bin/PI/frontends_extra/cpp/example'
make[2]: Leaving directory '/home/ubuntu/p4-guide/bin/PI/frontends_extra/cpp'
make[2]: Entering directory '/home/ubuntu/p4-guide/bin/PI/frontends_extra'
rm -rf .libs _libs
rm -f *.lo
make[2]: Leaving directory '/home/ubuntu/p4-guide/bin/PI/frontends_extra'
make[1]: Leaving directory '/home/ubuntu/p4-guide/bin/PI/frontends_extra'
Making clean in proto
make[1]: Entering directory '/home/ubuntu/p4-guide/bin/PI/proto'
make[1]: *** No rule to make target 'clean'.  Stop.
make[1]: Leaving directory '/home/ubuntu/p4-guide/bin/PI/proto'
Makefile:461: recipe for target 'clean-recursive' failed
make: *** [clean-recursive] Error 1
end install PI:
Thu Oct 17 08:58:14 CST 2019
find: ‘/root/.local’: No such file or directory
------------------------------------------------------------
Installing p4lang/behavioral-model
start install behavioral-model:
Thu Oct 17 08:58:14 CST 2019
git clone https://github.com/p4lang/behavioral-model.git
fatal: destination path 'behavioral-model' already exists and is not an empty directory.
Already up-to-date.
commit 33e221fd879c1aa2f16b04ab0adbf341619003ae
Author: Antonin Bas <abas@vmware.com>
Date:   Fri Sep 20 08:55:10 2019 -0700

    Cleanup the "parameters_vector" code

**Comment by jafingerhut** [comment]
I would recommend that if you can create a _fresh new_ Ubuntu Linux system or virtual machine (version 16.04 or 18.04), that meets these requirements for RAM and disk space: https://github.com/jafingerhut/p4-guide/blob/master/README-using-bmv2.md#what-to-install-for-compiling-p4-programs-and-running-them-on-bmv2

Then when you first log on to the system, while it has a reliable Internet connection, run these commands from your home directory:
```
git clone https://github.com/jafingerhut/p4-guide
./p4-guide/bin/install-p4dev-p4runtime.sh |& tee log.txt
```
The `|& tee log.txt` part will cause the output to be written to the file log.txt, as well as be shown on the terminal.

If you do not run it as a superuser (which is the way I usually run it), then enter your password when prompted, for the parts of the script that need superuser privileges, e.g. the parts that copy files into system-wide directories like /usr/local/bin

That is how I test these scripts every month or so, and I fix them if they are not working, but that is rare.

**Comment by jibanli** [comment]
Successfully installed futures-3.3.0 grpcio-1.24.1
You are using pip version 8.1.1, however version 19.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting protobuf
  Downloading http://mirrors.tencentyun.com/pypi/packages/c5/49/ffa7ab9c52ec56b535cffec3bc844254c073888e6d4aeee464671ac97480/protobuf-3.10.0-cp27-cp27mu-manylinux1_x86_64.whl (1.3MB)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from protobuf)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9 in /usr/lib/python2.7/dist-packages (from protobuf)
Installing collected packages: protobuf
Successfully installed protobuf-3.10.0
You are using pip version 8.1.1, however version 19.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
end install python packages:
Thu Oct 17 14:31:43 CST 2019
find: ‘/root/.local’: No such file or directory
------------------------------------------------------------
Time and disk space used when installation was complete:
Thu Oct 17 14:31:43 CST 2019
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        50G  9.3G   38G  20% /
Filesystem     1M-blocks  Used Available Use% Mounted on
/dev/vda1         50268M 9452M    38240M  20% /

Created files: p4setup.bash p4setup.csh

If you use a Bash-like command shell, you may wish to copy the lines
of the file p4setup.bash to your .bashrc or .profile files in your
home directory to add commands like p4c and simple_switch_grpc to your
command path every time you log in or create a new shell.

If you use the tcsh or csh shells, instead copy the contents of the
file p4setup.csh to your .tcshrc or .cshrc file in your home
directory.
root@VM-0-13-ubuntu:~# 
root@VM-0-13-ubuntu:~# ls
behavioral-model  install-details  log.txt  p4-guide      p4setup.csh  protobuf
grpc              libyang          p4c      p4setup.bash  PI           sysrepo
root@VM-0-13-ubuntu:~#

**Comment by jibanli** [comment]
Hi, whether I'm succeeded ???

**Comment by jibanli** [comment]
Hi. Have I succeeded?

**Comment by jafingerhut** [comment]
Probably.  Try doing these commands and see what output you get, assuming you are running a bash-like command shell:
```
$ source p4set.bash
$ protoc --version
libprotoc 3.2.0

$ thrift --version
Thrift version 0.9.2

$ simple_switch --version
1.13.0-33e221fd

$ p4c --version
p4c 1.1.0-rc1 (SHA: 474ea783)
```
If everything succeeded for you, you might get different version numbers from the last two commands than shown above, since you might have compiled a different version of the behavioral-model and p4c source code than I did on my system.

If you want to run many p4c tests that will exercise your p4c and simple_switch executables, try these commands (it can take 10 to 20 minutes to complete, approximately):
```
$ cd p4c/build
$ make check
```
That will run almost 1,400 tests on p4c, some of which also run simple_switch and check that packets are being processed by simple_switch as expected.

**Comment by jibanli** [comment]
![无标题2](https://user-images.githubusercontent.com/39478794/67060695-7ad6e880-f190-11e9-92fc-3b46ef0302d0.png)

**Comment by jafingerhut** [comment]
Looks like you are all set up!

**Comment by jibanli** [comment]
I have a new question.
Now I want to achieve https://github.com/czivar/p4-retransmissions
What additional environment is needed？

**Comment by jafingerhut** [comment]
I would recommend asking the author, and/or on the P4 language Slack channel.  A link to the P4 Slack channel can be found by going to p4.org, click on "Community" in the top right corner, and choose "Slack" from the pop up menu.

**Comment by mbudiu-vmw** [comment]
The slack link says this: "This invite link is no longer active."
So it should probably be removed from p4.org.

**Comment by jnfoster** [comment]
Oops. I will add an updated, functional link.

**Comment by jafingerhut** [comment]
It appears that the Slack channel link is updated now, as far as I can tell -- I see a text box inviting me to enter my email address, instead of a message that the invite link has expired.

I see that @jibanli has followed my suggestion of directly asking the author of the Github repository they were curious about.

Perhaps this issue can be closed now?

**Comment by jibanli** [comment]
Yes.(Smile

**Comment by jnfoster** [comment]
It seems this issue can be safely closed?
