### ISSUE TITLE
Cannot unify bit<8> to bit<32>

### ISSUE THREAD

**Issue by sanaa50** [p4lang/p4c#2064]
Hi,
I'm trying to get a random number by using the random method `random(meta.be, (bit<8>)0,(bit<8>)100);`
During the compilation I get the error `Cannot unify bit<8> to bit<32>`. The (be) variable is 8 bits.
I tried `random((bit<8>)meta.be, (bit<8>)0,(bit<8>)100);` but got `Read-only value used for out/inout parameter`.
Any solution please?

**Comment by jafingerhut** [comment]
Are you able to share a complete program that gives this error?  If so, someone else could try to reproduce the issue you are seeing.

I tried creating a small P4_16 program (attached as rand.p4.txt) that makes a call to `random`, and when I use this version of the p4c compiler and the command below that to compile the program, I get no error messages:
```
$ p4c --version
p4c 1.1.0-rc1 (SHA: 474ea783)

$ p4c --target bmv2 --arch v1model rand.p4
```
[rand.p4.txt](https://github.com/p4lang/p4c/files/3747074/rand.p4.txt)

**Comment by sanaa50** [comment]
> Are you able to share a complete program that gives this error? If so, someone else could try to reproduce the issue you are seeing.
> 
> I tried creating a small P4_16 program (attached as rand.p4.txt) that makes a call to `random`, and when I use this version of the p4c compiler and the command below that to compile the program, I get no error messages:
> 
> ```
> $ p4c --version
> p4c 1.1.0-rc1 (SHA: 474ea783)
> 
> $ p4c --target bmv2 --arch v1model rand.p4
> ```
> 
> [rand.p4.txt](https://github.com/p4lang/p4c/files/3747074/rand.p4.txt)

I managed to solve the issue as following:
`bit<32>tempRan;
random(tempRan, 0, 100);
meta.be=(bit<8>)tempRan;`

Thank you for your response.

**Comment by jafingerhut** [comment]
Glad you got something working for you.

I find it a little bit odd that you could not get it to compile with your original call to `random`.  I tried the attached program rand2.p4.txt that contains a call to `random(output_port, (bit<8>) 0, (bit<8>) 100);` where `output_port` is declared with type `bit<8>`, and I get no error with the version of p4c mentioned in my earlier comment.

My best guess is that you may be using an older version of p4c than mine, which has some bug in it preventing it from working, or there is something else different about our programs such that your `random` call really is not correct somehow, but it is difficult for others to determine that without seeing the entire program.

[rand2.p4.txt](https://github.com/p4lang/p4c/files/3747123/rand2.p4.txt)

**Comment by sanaa50** [comment]
> Glad you got something working for you.
> 
> I find it a little bit odd that you could not get it to compile with your original call to `random`. I tried the attached program rand2.p4.txt that contains a call to `random(output_port, (bit<8>) 0, (bit<8>) 100);` where `output_port` is declared with type `bit<8>`, and I get no error with the version of p4c mentioned in my earlier comment.
> 
> My best guess is that you may be using an older version of p4c than mine, which has some bug in it preventing it from working, or there is something else different about our programs such that your `random` call really is not correct somehow, but it is difficult for others to determine that without seeing the entire program.
> 
> [rand2.p4.txt](https://github.com/p4lang/p4c/files/3747123/rand2.p4.txt)

I'm using p4c v3.0.2.

**Comment by sanaa50** [comment]
> Glad you got something working for you.
> 
> I find it a little bit odd that you could not get it to compile with your original call to `random`. I tried the attached program rand2.p4.txt that contains a call to `random(output_port, (bit<8>) 0, (bit<8>) 100);` where `output_port` is declared with type `bit<8>`, and I get no error with the version of p4c mentioned in my earlier comment.
> 
> My best guess is that you may be using an older version of p4c than mine, which has some bug in it preventing it from working, or there is something else different about our programs such that your `random` call really is not correct somehow, but it is difficult for others to determine that without seeing the entire program.
> 
> [rand2.p4.txt](https://github.com/p4lang/p4c/files/3747123/rand2.p4.txt)

How Can I find out which version of p4c is being used?

**Comment by jafingerhut** [comment]
To find out the version of p4c you are using, type the command `p4c --version` (mentioned in an earlier comment of mine, where you can see the version number I am using, which is built from a less-than-1-month-old version of p4c source code).

**Comment by sanaa50** [comment]
> To find out the version of p4c you are using, type the command `p4c --version` (mentioned in an earlier comment of mine, where you can see the version number I am using, which is built from a less-than-1-month-old version of p4c source code).

My version of p4c is 0.1. I'm going to update it.
thank you.
