### ISSUE TITLE
Error while installing p4c

### ISSUE THREAD

**Issue by sanaa50** [p4lang/p4c#2065]
I'm following the procedure in this   [link](https://github.com/p4lang/p4c), and when it comes to `make -j4 check` I get the following error:

`The following tests FAILED:
	967 - p14_to_16/testdata/p4_14_samples/switch_20160512/switch.p4 (Timeout)
Errors while running CTest
CMakeFiles/check-all.dir/build.make:57: recipe for target 'CMakeFiles/check-all' failed
make[3]: *** [CMakeFiles/check-all] Error 8
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/check-all.dir/all' failed
make[2]: *** [CMakeFiles/check-all.dir/all] Error 2
CMakeFiles/Makefile2:234: recipe for target 'CMakeFiles/check.dir/rule' failed
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
Makefile:238: recipe for target 'check' failed
make: *** [check] Error 2
`

I'm using Ubuntu 16 on a VM.
Any help please?

**Comment by jafingerhut** [comment]
I do not know why that error is occurring, but most likely it is due to missing a step in the install instructions, either in p4c itself, or missing an install step in one of the software packages that is a prerequisite for p4c to compile.

This shell script recommended in these instructions: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

has been successfully tested many times to install p4runtime, protobuf, grpc, behavioral-model, and p4c code on a freshly installed Ubuntu 16.04 and 18.04 Linux system.  It doesn't do anything that is different than the README instructions say (or at least it shouldn't), but there can be a lot of them.

**Comment by jafingerhut** [comment]
Oh, and looking early in your error message I just noticed the word "Timeout".  Even if you installed everything perfectly, I believe that could happen if the machine were too slow, or busy doing other things while running the test.  If it happens repeatedly on a reasonably fast machine that is not busy doing other things, then I would say it is still worth trying a fresh build using the shell script linked above, and see if the problem occurs there, too.

**Comment by sanaa50** [comment]
> I do not know why that error is occurring, but most likely it is due to missing a step in the install instructions, either in p4c itself, or missing an install step in one of the software packages that is a prerequisite for p4c to compile.
> 
> This shell script recommended in these instructions: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md
> 
> has been successfully tested many times to install p4runtime, protobuf, grpc, behavioral-model, and p4c code on a freshly installed Ubuntu 16.04 and 18.04 Linux system. It doesn't do anything that is different than the README instructions say (or at least it shouldn't), but there can be a lot of them.

This didn't solve the issue.

**Comment by jafingerhut** [comment]
Did all tests except for the one that timed out pass?  If so, I would guess the main issue is that your machine is running too slowly to finish that one long test.

**Comment by jafingerhut** [comment]
There are three Python programs within the p4c repository that are used when running the p4c tests.  Each of them currently enforces a 600 second timeout, where if the test has not completed in that long, you will see the Timeout error message that you pasted in your original question.

You could try an experiment where you increase the timeout, e.g. double it to 1200 seconds, and see if the test passes for you then.  Here is where you can find the occurrences of that timeout setting within those Python programs:
```
 find . -name '*.py' | xargs egrep '\btimeout ='
./backends/p4test/run-p4-sample.py:timeout = 10 * 60
./backends/bmv2/run-bmv2-test.py:timeout = 10 * 60
./backends/bmv2/bmv2stf.py:timeout = 10 * 60
```

**Comment by ChrisDodd** [comment]
I noticed that the original message suggests he was running with -j4?  This would run 4 testing threads simultaneously, which might get stalled if the VM in question has fewer than 4 CPUs or less than about 16GB of memory.

**Comment by jafingerhut** [comment]
True.  Trying with `make -j1` would take longer in wall clock time, but be more likely to succeed.

**Comment by mbudiu-vmw** [comment]
I think we can close this issue since there was no follow-up.
