### ISSUE TITLE
Can i hook eBPF ( to XDP) with only one CPU core

### ISSUE THREAD

**Issue by TummanapallyAnuraag** [p4lang/p4c#2067]
I have `3 BPF codes`, and `3 NICs` (eth0, eth1, and eth2) 
I have `4 core CPU`
How can I assign 
* CPU core 0 to BPF-0 for `eth0`
* CPU core 1 to BPF-1 for `eth1`
* CPU core 2 to BPF-2 for `eth2`
![t7F8l](https://user-images.githubusercontent.com/21244258/67391247-ef0ff280-f5bb-11e9-9c03-1481d0b1991c.png)

**Comment by jnfoster** [comment]
This seems like a question for the XDP community (or perhaps [vmware/p4c-xdp](https://github.com/p4lang/p4c-xdp)). I'm afraid I don't see what it has to do with `p4c` itself.
