### ISSUE TITLE
[bmv2] BMV2 does not support conditionals in actions

### ISSUE THREAD

**Issue by vikramnathan** [p4lang/p4c#207]
I have a very simple p4 program (attached) containing an action that uses an if statement. When compiled for bmv2, I get the error:
`test_bug.p4(185): error: IfStatement: not yet supported on this target`
This happens whether I use a ternary operator or an if statement.

According to the p4_16 [grammar](https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/grammar.mdk#L461) and spec (section 14.1), conditionals are allowed in actions. Sure - certain targets may choose not to support them, but my understanding is that bmv2 is intended to be permissive, i.e. supporting most (or all) available language constructs. If that's the case, I think it should allow actions with conditionals.

[test_bug.p4.txt](https://github.com/p4lang/p4c/files/670056/test_bug.p4.txt)

**Comment by mbudiu-vmw** [comment]
BMv2 is a framework which allows one to create multiple P4 simulators. The simple_switch simulator is one of these, and it was designed for P4-14 - it closely models the capabilities of the architecture described in the P4-14 (P4 v1.0) spec.

P4-16 is a language that can target multiple architectures. When you target the v1model.p4 architecture you are subject to its constraints; this architecture also closely models P4-14 capabilities. That architecture does not support if statements in actions - but it does support conditional expressions.

The p4c-bm2-ss back-end targets v1model.p4 and generates code for simple_switch, so it cannot support constructs that do not work on this architecture.

You are correct that we should support conditional expressions - this is a bug. The front-end converts conditionals to ifs - we should have another pass in the mid-end which reverts this transformation.

However, the example you supplied has a conditional method call:
```
if (p)
  debug.write(0, n);
```

simple_switch does not support this construct, and there is nothing that the compiled can do.

**Comment by TrishaDatta** [comment]
I am using the latest bmv2 version and P4-16, but conditional statements are not recognized at all. If I say 
`hdr.ipv4.srcAddr == 10.0.0.1 ? result = result + 1 : result = result - 1`

I get the error: `syntax unexpected ==`

is the conditional expression not supported in the newest version (I would like to emit a certain header from the Deparser in only certain conditions)?

**Comment by antoninbas** [comment]
That's just not correct P4. Did you mean:
```
result = (hdr.ipv4.srcAddr == 32w0x0a000001) ? (result + 1) : (result - 1)
```
I'm not saying this will compile for bmv2 though, but the compiler frontend should accept it.

**Comment by TrishaDatta** [comment]
Sorry about that I was very confused about syntax. 

I would like to write a conditional statement in my Deparser such that if the statement evaluates to true, a certain header will be emitted. I assumed it would be something like this: 

`(hdr.ipv4.srcAddr == 32w0x0a000001) ? (packet.emit(header)) : // nothing`

but the "emit" function's return type is void, so I was unsure of what to set this statement equal to?

**Comment by jafingerhut** [comment]
Try using a normal 'if' statement in your deparser, although I have never tried such a statement in the deparser code for P4_16 + v1model architecture to see if bmv2 could implement that or not.  It might not be able to support that right now.

The ternary operator (expr) ? (true_val) : (false_val) is really only intended to be used in expressions, e.g. as an 'if' condition, or in the right hand side of assignment statements.

**Comment by mbudiu-vmw** [comment]
Alternatively, if you don't want to emit this header at all, you can call setInvalid() on it in egress.

**Comment by TrishaDatta** [comment]
The 'if' statement is not accepted in the deparser for P4_16, but the setInvalid() worked perfectly. Thank you all so much!
