### ISSUE TITLE
Upgrade to Python3

### ISSUE THREAD

**Issue by rst0git** [p4lang/p4c#2079]
Hello, I noticed that most of the python scripts in this repository (and other p4lang repositories) explicitly specify dependency on Python 2. However, Python 2 will be deprecated at the end of this year (https://pythonclock.org/). Are there any plans to upgrade to Python3?

**Comment by mbudiu-vmw** [comment]
I haven't heard of anyone contributing code to help the porting.
We don't have that much Python, it's used mostly for testing. We could only run into trouble if some of the modules we are using are not supported.

**Comment by jafingerhut** [comment]
As far as I can tell, Jan 1 2020 means no more bug fixes to Python 2 and many popular Python 2 libraries as of that date.  It doesn't mean Python 2 will stop working on that date.  It would be nice to transition to Python 3 when someone volunteers to make the necessary code changes.

https://stackoverflow.blog/2019/11/14/why-is-the-migration-to-python-3-taking-so-long/

**Comment by jafingerhut** [comment]
I think that conversion from Python 2 to Python 3 may be complete for the p4c repository now, and this could be closed?  If so, it seems reasonable to close this one, and create a separate issue for the other p4lang repositories that have Python 2 code.

**Comment by rst0git** [comment]
Thank you @jafingerhut!
