### ISSUE TITLE
BMV2 does not support nested structs

### ISSUE THREAD

**Issue by sethfowler** [p4lang/p4c#208]
This code should work, but it causes the BMV2 backend to throw when it attempts to output JSON:

```
header foo {
  bit<8> foo_1;
  bit<7> foo_2;
  bit<8> foo_3;
}

header bar {
  bit<2> bar_1;
}

struct baz {
  foo baz_1;
}

struct Headers {
    bar a;
    baz b;
}
```

The exception is:

```
libc++abi.dylib: terminating with uncaught exception of type Util::CompilerBug:
COMPILER BUG: ../backends/bmv2/jsonconverter.cpp:2016
```

**Comment by mbudiu-vmw** [comment]
This code is not syntactically correct, can you please submit a reproduction?
The back-end should support nested structs. However, the "hdr" parameter in the v1model.p4 is expected indeed to be a struct which contains just headers.

**Comment by mbudiu-vmw** [comment]
Line 2016 is jsonconverter.cpp is an ::error statement, and not BUG, so you must be using an old version of the code.

**Comment by sethfowler** [comment]
Yeah, it looks like there was a copy paste error. I've updated the code. While I was at it, I replaced `hdr` with something defined within the code snippet.

The restriction on the `hdr` parameter is indeed the issue.

I'm not using an old version of the code, but it seems the line has moved around somewhat because I've inserted some logging messages. https://github.com/p4lang/p4c/blob/master/backends/bmv2/jsonconverter.cpp#L2050 is the line in question.

**Comment by mbudiu-vmw** [comment]
When I refresh this web page I see the same code as before.

**Comment by sethfowler** [comment]
Try again, sorry.

**Comment by mbudiu-vmw** [comment]
I have added a fix for this to my last PR.
Your program will be rejected with an error message instead of the compiler crashing.
The restriction is documented in v1mode.p4:

```
// H should be a struct of headers or stacks
```

**Comment by mbudiu-vmw** [comment]
I believe that this issue has been solved.
