### ISSUE TITLE
Is p4c out of alpha yet?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#2080]
I ask because the first sentence of its README is: "p4c is a new, alpha-quality reference compiler for the P4 programming language."

I just helped a person who turned out to be using the older p4c-bm repository (https://github.com/p4lang/p4c-bm) to compile a P4_14 program.  They are working on trying again by using p4c instead, and recently I suggested, and Antonin Bas approved, the addition of the following text to the beginning of that repository's README: "NOTE: This repository is no longer under active development or maintenance. We recommend that you instead consider using the currently developed open source P4 tools, which are p4c and behavioral-model."

The word 'p4c' there is a link to this repository, and if they read the README, the above is the first sentence they will see, which seems to leave one with an uneasy feeling that you must choose between "historical/no-longer-maintained" and "alpha-quality" if you want an open source P4 compiler.

Is it safe to say p4c is past alpha-quality yet?

**Comment by cc10512** [comment]
We have a production compiler based on p4c. While we only exercise the front-end, mid-end, and p4c-graphs backend, I think we can claim that the compiler has passed into a (permanent?) beta.

**Comment by jafingerhut** [comment]
Closing this issue since the corresponding PR has been approved and merged in: https://github.com/p4lang/p4c/pull/2081
