### ISSUE TITLE
Build a costume topology

### ISSUE THREAD

**Issue by sanaa50** [p4lang/p4c#2088]
Hi,
I'm not sure if it is the suitable place to ask the question, but I did not know where to ask.
I want to build a topology with more than five switches. Each switch has its own rules. 
I know I should write a JSON file for each switch but I don't want to use p4apprunner to create the topology, I have my own code to do this. 
My question is how to add the JSON files to the switches? 
I found many examples to build a costume topology but all of them use one switch only and use a python code like :

```
import os
os.system('sudo /home/someone/behavioral-model/targets/simple_switch/simple_switch_CLI --thrift-port=9090 < cmd.txt')
```
to add the JSON (or text) file.

Any idea?

**Comment by hesingh** [comment]
simple_switch_CLI uses a '--json' flag to provide a json description of a P4 program.  Does this help?

**Comment by antoninbas** [comment]
@sanaa50 if you are using `simple_switch_grpc` and P4Runtime, then the easiest thing to do is to start all the switches with the `--no-p4` flag. It enables the switch to start without a P4 program / a JSON file. After that, P4Runtime - and more precisely the `SetFowardingPipelineConfig` RPC - can be used to push the appropriate JSON file to each switch. So you can essentially write your own P4Runtime client ("controller") to push connect to each switch and push the JSON file, then install all the appropriate table entries. You can refer to the P4Runtime specification for more details.

**Comment by jafingerhut** [comment]
I believe there may be some confusion about which JSON file is being talked about.

There is the BMv2 JSON file that is the output of the p4c compiler, and describes the behavior of the P4 program to simple_switch.

Then there is a custom schema JSON format file used in several exercises in the tutorials repository, used to hold the table entries that should be installed by very simple controller software included with the tutorials.  I am guessing from the statement "Each switch has its own rules." in the original question that this might be what @sanaa50 is asking about.

If so, this question is very specific to the files used by the tutorials repository, and likely belongs there, as it has little to do with p4c.
