### ISSUE TITLE
Type error in Bmv2 MidEnd?

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#2090]
Compiling the attached [switch.p4.txt](https://github.com/p4lang/p4c/files/3869430/switch.p4.txt) using the following command
```
p4c-bm2-ss --p4v 16 -Tpass_manager:1 switch.p4 
```
produces a type error:
```
...
BMV2::SimpleSwitchMidEnd invoking ExpandEmit
  ExpandEmit invoking P4::TypeChecking
    P4::TypeChecking invoking ResolveReferences
    P4::TypeChecking invoking P4::TypeInference
[--Werror=legacy] error: AssignmentStatement: Cannot unify bit<32> to int<32>
```

**Comment by jnfoster** [comment]
The culprit seems to be this parser state,
```
    state parse_current_instruction {
        meta.current_instr.setValid();
        meta.current_instr = packet.lookahead<instr_t>();
        transition next_instruction;
    }
```
which the front-end and mid-end convert into [switch-BMV2::SimpleSwitchMidEnd_12_ExpandLookahead.p4.txt](https://github.com/p4lang/p4c/files/3870261/switch-BMV2.SimpleSwitchMidEnd_12_ExpandLookahead.p4.txt)
```
    state parse_current_instruction {
        meta.current_instr.setValid();
        {
            tmp_0 = packet.lookahead<bit<40>>();
            tmp.setValid();
            tmp = {tmp_0[39:32],tmp_0[31:0]};
        }
        meta.current_instr = tmp;
        transition next_instruction;
    }
```
Just hazarding a guess, could this be related to our recent change to bit slices, giving them unsigned types?

**Comment by mbudiu-vmw** [comment]
The diagnostic seems correct.

**Comment by jnfoster** [comment]
Thanks for the quick fix!
