### ISSUE TITLE
Custom C-externs in p4c-ebpf?

### ISSUE THREAD

**Issue by BDHU** [p4lang/p4c#2094]
Since P4 is not Turing complete, is it possible to add custom C-functions as externs for p4c-ebpf to work? Thanks.

**Comment by hesingh** [comment]
Any p4c backend supports externs.  Externs are defined in a P4 include file for a target.  For example, see externs defined in https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4.

The extern is implemented by a p4 backend such as ebpf.  Since p4c is written in C++, the extern implementation is written in C++, not C.  The ebpf backend emit C code.
,

**Comment by BDHU** [comment]
So essentially what I want is something similar to Netronome compiler where you can write actions in C and have them be called from the P4. I don't see an easy way to do it here? Perhaps compiler modification is needed?

**Comment by hesingh** [comment]
I know of only calling p4 externs from P4 code.  I suspect even Netronome is calling a P4 extern from P4 code and the extern's implementation is written in C.   Why don't you implement an extern in p4c backend in C++? 

Further, the PSA specification and its Action Profile allows for a mechanism to populate table entries with action specifications that have been defined outside the table entry specification.  See

https://p4.org/p4-spec/docs/PSA.html#sec-action-profile

Also, see Action Selector in the same specification.  

I don't see a need for p4c to change yet.

**Comment by BDHU** [comment]
I see. Is there any documentation regarding how to add extern implementation for ebpf backend? I've been searching for a while without some concrete information.

**Comment by hesingh** [comment]
I have actually added externs for a specific architecture.   I will find my code and get back and code examples.

**Comment by hesingh** [comment]
Here is some documentation I prepared.  

1. See the P4 include file where externs are defined.  https://github.com/p4lang/p4c/blob/master/backends/ebpf/p4include/ebpf_model.p4

2.  Any architecture that uses externs must define xxxModel.h and xxxModel.cpp.  See ebpfModel.h and .cpp. 
  https://github.com/p4lang/p4c/blob/master/backends/ebpf/ebpfModel.h[.cpp].

3.  See how P4 code calls one extern defined in ebpf here.  See CounterArray in the following code.

https://github.com/p4lang/p4c/blob/5d83957346aef6d0f1abb3f65691744a4738cc3f/testdata/p4_16_samples/valid_ebpf.p4#L33

4. The backend implements the extern around the following line of code.

https://github.com/p4lang/p4c/blob/de77fd172d33c07af57f2b633532b5d37ff05c3d/backends/ebpf/ebpfTable.cpp#L488

Also, see 

https://github.com/p4lang/p4c/blob/5da4bf340f408861dd461e7d111efc826f36d7ae/backends/ebpf/ebpfControl.cpp#L241

**Comment by mbudiu-vmw** [comment]
This is related to this issue as well: https://github.com/vmware/p4c-xdp/issues/119
The short answer is that at this point p4c-ebpf does not have support for "extern" externs - written in some other language. I estimate the work needed to implement this to a couple of days. So if you really want this feature we can try to prioritize it. Implementing it in the compiler is actually the easy part: you just ask the compiler not to warn you about any extern it does not know about. This feature is already supported for the bmv2 back-end. The (slightly) harder part is to define a calling convention in the generated code. For example, how are IPv6 addresses going to be passed to the C code? How about 3-bit fields? If we settle on these then it won't be much work.

I also hope you realize that ebpf is also not Turing complete, so much that you cannot do in P4 you also cannot do in ebpf.

**Comment by mbudiu-vmw** [comment]
BTW: if you can help implementing this feature it would be great. Even writing the documentation for the calling convention would be great.

**Comment by BDHU** [comment]
It is useful since P4 is very limited in terms of functionalities provided. The project I'm working on involves constant interaction with shared memories between processes with changes to global states which is simply impossible to do in P4. I'd like to look further into the possibility of adding externs in other languages.

**Comment by hesingh** [comment]
P4 PSA architecture shares memory between ingress and egress control blocks.  Any global state can be mapped to metadata between ingress and egress.  I don't see why a physical memory location for read/write can't be setup in P4 code.  

Commercial P4 implementations (e.g., Kaloom) uses Tofino for P4 and a FPGA for functionality not supported by P4.  Surely, such an implementation has used API between the two "processors" for data packets and other control including any shared memory.

I like what Mihai is proposing.  If the work is undertaken, it's useful work for others in the community.

**Comment by BDHU** [comment]
If all I want to do is to add a extern function like:
`extern bit<32> get_current_time_ns();`
and I want to achieve this in p4-ebpf, does it go through the same process as discussed? @hesingh 
I've seem some other custom model linking similar functionalities but the functionality is provided by the software switch itself. Is there anyway to do the same thing here?

**Comment by hesingh** [comment]
The steps I outlined in this comment "https://github.com/p4lang/p4c/issues/2094#issuecomment-556998228" are applicable to add an extern to any p4c backend including ebpf.

**Comment by osinstom** [comment]
Hi, are you still interested in this enhancement? I would like to take it over, as it could be also useful for our `ubpf` backend, which is currently under review. My idea is to write a design doc firstly to agree an interface (calling convention) and, then, move on with the implementation.

**Comment by BDHU** [comment]
That would be great. I think having custom functionalities supported will be a huge help. We got around the issue by modifying the compiler but that will not be trivial for people without background.

**Comment by osinstom** [comment]
I've prepared a draft of design document for this feature: https://docs.google.com/document/d/1oOo8zDzMAMkdhEx6NLkEYty0l4ji-UUSnhZQIbJ-45g/edit?usp=sharing. Please, take a look at the document. Your suggestions, comments or remarks are welcome! 

At the moment, I think the biggest challenge is to determine how the "interface" (in the OOP terminology) of the extern function should be defined.

**Comment by osinstom** [comment]
I've just added Calling convention section to the document. @mbudiu-vmw Could you share your opinion on the current approach?

**Comment by danisrcnl** [comment]
> What is "p4 compiler"?

*p4c

**Comment by mbudiu-vmw** [comment]
p4c is just a python program that calls the other binaries. You can try to use p4c-ebpf directly.
