### ISSUE TITLE
Compiler Bug: no definitions

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2104]
There is another issue we keep encountering while generating programs. When passing variables to actions or methods by reference, the compiler sometimes emit "no definitions" for a variable. I do not exactly understand the key factor behind the bug but we have two different version where this occurred:

Using local actions:
```
#include <core.p4>
#include <v1model.p4>

control c() {
    bit<16> FHaSkb = 0;
    bit<128> YIafjU = 0;
    action rxNET() {
        YIafjU = (bit<128>) FHaSkb;

    }
    action vKNsz() {
        return; // the return comes before the action call
        rxNET();
    }
    apply {
        vKNsz();
    }

}

control e<T>();
package top<T>(e<T> e);

top(c()) main;
```
Using global methods:
```
#include <core.p4>
#include <v1model.p4>

// adding the inout qualifier leads to a compiler crash
bit<8> test(inout bit<8> x) {
    return x;
}

header H {
    bit<8> a;
    bit<8> b;
}

struct headers {
    H h;
}

control c(inout headers hdr) {
    apply {
        test(hdr.h.a);
    }
}

control e<T>(inout T t);
package top<T>(e<T> e);

top(c()) main;

```

The first program is nonsensical but still causes a crash. @mbudiu-vmw  What do you think?

**Comment by mbudiu-vmw** [comment]
The second example fails because in the def-use analysis the returns statement currently kills all variables, in fact the out parameters should not be killed, they continue to exist.

**Comment by mbudiu-vmw** [comment]
The first example fails because of a related reason; the return kills all variables, including the ones in the caller's scope. That's also wrong.
