### ISSUE TITLE
Compiler Bug:  no locations known for <Mux>

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2105]
This is a weird one.
I do not understand what is going on here but this statement leads to another crash. I reduced it to a minimum but all the components (the slice and the bor) are required to generate this crash. 

```
#include <core.p4>
#include <v1model.p4>

control c() {
    apply {
        bit<8> x = 0;
        bit<8> y = 0;
        // the crash happens when reassigning y while referencing x
        // removing either the slice or the bor operation will fix the crash
        y = (x < 4 ? 8w2 : 8w1)[7:0] | 8w8;
    }
}

control e<T>();
package top<T>(e<T> e);

top(c()) main;
```
[tmp.txt](https://github.com/p4lang/p4c/files/3928909/tmp.txt)

**Comment by mbudiu-vmw** [comment]
There was no case handling Mux (?:) in a visitor. Since no test of ours ever used Mux as a sub-expression we didn't notice.
