### ISSUE TITLE
Unused code in p4c bmv2 backend

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#2117]
In `p4c/backends/bmv2/common/JsonObjects.cpp`

`JsonObjects::create_primitive(Util::JsonArray* parent, cstring name)`

is not used by any p4c code.  

Should we delete it?

**Comment by mbudiu-vmw** [comment]
Feel free to submit a PR that deletes it.

**Comment by hesingh** [comment]
> Feel free to submit a PR that deletes it.

Will do. thanks.
