### ISSUE TITLE
spurious warnings on constant folding

### ISSUE THREAD

**Issue by zma-barefoot** [p4lang/p4c#2122]
With #1776, a few spurious warning messages on constant folding were exposed, e.g. below:

testdata/p4_14_samples_outputs/issue1013.p4-stderr

```
issue1013.p4(13): [--Wwarn=mismatch] warning: -0x1: negative value with unsigned type
     modify_field(h.x, h.x, 0x0);
```

testdata/p4_16_samples_outputs/issue1334.p4-stderr

```
issue1334.p4(28): [--Wwarn=mismatch] warning: -2: negative value with unsigned type
     d(b = 2) dinst;
           ^
```

See discussion in https://github.com/p4lang/p4c/pull/1776/files for more details.

**Comment by mbudiu-vmw** [comment]
I cannot reproduce these errors.
