### ISSUE TITLE
InlineFunctions pass sometime seems to generate invalid code.

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2126]
The intermediate output after the InlineFunctions pass occasionally leads to invalid P4 code.
 
If we compile issue1538.p4 with
`./p4c/build/p4c --top4 FrontEnd,MidEnd  --dump dmp p4c/testdata/p4_16_samples/issue1538.p4 ` and then try to run 
`./p4c/build/p4c dmp/issue1538-FrontEnd_44_InlineFunctions.p4i`
on the generated file we get the following output:
```
dmp/issue1538-FrontEnd_44_InlineFunctions.p4i(37): error: Duplicate declaration of hasReturned; previous at 
            bool hasReturned = false;
                 ^^^^^^^^^^^
dmp/issue1538-FrontEnd_44_InlineFunctions.p4i(26)
            bool hasReturned = false;
                 ^^^^^^^^^^^
dmp/issue1538-FrontEnd_44_InlineFunctions.p4i(38): error: Duplicate declaration of retval; previous at 
            bit<16> retval;
                    ^^^^^^
dmp/issue1538-FrontEnd_44_InlineFunctions.p4i(27)
            bit<16> retval;
                    ^^^^^^
error: 2 errors encountered, aborting compilation
```

**Comment by jafingerhut** [comment]
I tried reproducing this, but with latest p4c source code built, I get errors about the `--top4` and `--dump` command line options not being recognized.  I know I have used these before.  Is anyone else seeing such messages for those options, or know why I might be?

**Comment by jafingerhut** [comment]
Never mind.  I figured it out.  By default, if you run a copy of p4c that you have installed using `sudo make install`, the Python command line parsing code is in 'INSTALLED' mode, which does not recognize a few options like `--top4`.  It does if you run the executable in the p4c/build directory.

**Comment by hesingh** [comment]
Right.  I just used --top4 and --dump yesterday with latest p4c and see no problems. I always use `p4c/build/p4c`

**Comment by jafingerhut** [comment]
I don't see the error on the file you mentioned, but I do on the file `issue1538-FrontEnd_44_InlineFunctions.p4` and a few others.

It appears the errors should not be issued, though, since the variables are scoped locally within a block `{ in braces}` inside a parser state, so perhaps there is a bug in scoping of local variables?

**Comment by hesingh** [comment]
> I don't see the error on the file you mentioned, but I do on the file `issue1538-FrontEnd_44_InlineFunctions.p4` and a few others.
> 
> It appears the errors should not be issued, though, since the variables are scoped locally within a block `{ in braces}` inside a parser state, so perhaps there is a bug in scoping of local variables?

It looks like an issue only in parser code.  The same p4i file has `bool hasReturned` used in ingress control with no issues.

**Comment by jafingerhut** [comment]
The attached program is close to minimal one that exhibits the bug.  When I attempt to compile it with the 2020-Jan-04 master version of p4c, I get this error, which appears to me like no such error should occur:
```
$ p4c --target bmv2 --arch v1model issue-2126.p4
issue-2126.p4(58): error: Duplicate declaration of retval; previous at 
            bit<16> retval;
                    ^^^^^^
issue-2126.p4(42)
            bit<16> retval;
                    ^^^^^^
error: 1 errors encountered, aborting compilation
```
[issue-2126.p4.txt](https://github.com/p4lang/p4c/files/4022420/issue-2126.p4.txt)

**Comment by hesingh** [comment]
The `Duplicate declaration` error is from the symbols table used by the lang parser (yacc code) in p4c.  This symbols table has no knowledge of code blocks such as code within `{ }`.  The damage is already done when FrontEnd_xx_InlineFunctions.p4i is created.  p4c's frontend passes have to be looked at to see which pass declares variables such as `hasReturned` inside code blocks of parser instead of declaring the variable outside of any parser state.  This is one way to fix the error.

**Comment by fruffy** [comment]
I accidentally provided the first pass where the issue is fixed again after InlineFunctions. I edited the post.
Normally brackets should be interpreted as `parserBlockStatement`,  maybe there is something amiss here?

**Comment by mbudiu-vmw** [comment]
There are several problems, but one of them is certainly a bug - the one highlighted by Andy.
