### ISSUE TITLE
Parse Structured Annotations

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/p4c#2128]
Implement  https://github.com/p4lang/p4-spec/pull/796.  As discussed in the LDWG, once we have agreed on the spec and see a working implementation we may adopt the new language proposal.

**Comment by mbudiu-vmw** [comment]
@liujed : should I assign you for this issue?

**Comment by liujed** [comment]
Please see if Stefan, Konstantin, or anyone else with a vested interest in this feature is available to implement this. It should be a pretty simple change, and I'm happy to provide direction as needed, but I don't currently have bandwidth to do the implementation myself.

**Comment by antoninbas** [comment]
I can probably take care of the IR -> P4Info translation once the parser & IR support structured annotations. The P4Runtime WG is still working on defining the P4Info Protobuf format for this.
