### ISSUE TITLE
Compilation error p4c with p4fpga back-end

### ISSUE THREAD

**Issue by SStriver** [p4lang/p4c#213]
../extensions/c++/src/p4-fpga.cpp:110:17: error: no member named 'verbosity' in
      'FPGAOptions'
    if (options.verbosity > 0)
make error...

**Comment by hanw** [comment]
@SStriver, please report this error to p4fpga repo. p4fpga is not maintained by p4.org

**Comment by SStriver** [comment]
thank you!
