### ISSUE TITLE
bmv2 test -f fails to generate files

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#2136]
I ran this command on an existing test case with latest p4c downloaded today.   I was expecting `*midend*` `*frontend*` files to be generated in `p4ctestdata/p4_16_samples_outputs` but they are not.  I am using Ubuntu 18.04.  Anyone else see this issue?

```
hemant@ubuntu:~/p4c/build$ ./bmv2/testdata/p4_16_samples/issue983-bmv2.p4.test -f
Check for  /home/hemant/p4c/testdata/p4_16_samples/issue983-bmv2.stf
Calling target program-options parser
Adding interface pcap0 as port 0 (files)
Obtaining JSON from switch...
Done
Control utility for runtime P4 table manipulation
RuntimeCmd: 
hemant@ubuntu:~/p4c/build$ 
```

EDITED: 

I see the files are already generated.  But, then I changed the P4 program for /issue983-bmv2.p4 but still no updated files are generated.

**Comment by mbudiu-vmw** [comment]
Only p4test generates these files. Use p4/ at the beginning.

**Comment by hesingh** [comment]
Ok, thanks!  

In older p4 compliler slides I saw `$ ./bmv2/testdata/p4_16_samples/mytest.p4.test –f` and a statement saying "Overwrite test reference outputs" and this is why I tried.
