### ISSUE TITLE
Compilation error p4c with p4fpga back-end

### ISSUE THREAD

**Issue by SStriver** [p4lang/p4c#214]
../extensions/c++/src/midend.cpp:62:13: error: no matching constructor for
      initialization of 'P4::UniqueParameters'
        new P4::UniqueParameters(&refMap),
            ^                    ~~~~~~~
../frontends/p4/uniqueNames.h:131:7: note: candidate constructor (the implicit copy
      constructor) not viable: no known conversion from 'P4::ReferenceMap *' to
      'const P4::UniqueParameters' for 1st argument
class UniqueParameters : public PassManager {
      ^
../frontends/p4/uniqueNames.h:131:7: note: candidate constructor (the implicit move
      constructor) not viable: no known conversion from 'P4::ReferenceMap *' to
      'P4::UniqueParameters' for 1st argument
class UniqueParameters : public PassManager {
      ^
../frontends/p4/uniqueNames.h:135:5: note: candidate constructor not viable:
      requires 2 arguments, but 1 was provided
    UniqueParameters(ReferenceMap* refMap, TypeMap* typeMap);
    ^
1 error generated.
../extensions/c++/src/profile.cpp:17:19: error: no member named 'TableProperty' in
      namespace 'IR'
    if (p->is<IR::TableProperty>()) {
              ~~~~^
../extensions/c++/src/profile.cpp:17:33: error: expected unqualified-id
    if (p->is<IR::TableProperty>()) {
                                ^
../extensions/c++/src/profile.cpp:18:27: error: no member named 'TableProperty' in
      namespace 'IR'
      auto pp = p->to<IR::TableProperty>();
                      ~~~~^
../extensions/c++/src/profile.cpp:18:41: error: expected unqualified-id
      auto pp = p->to<IR::TableProperty>();
                                        ^
../extensions/c++/src/profile.cpp:20:54: error: expected '(' for function-style cast
      or type construction
        auto expr = pp->value->to<IR::ExpressionValue>();
                                  ~~~~~~~~~~~~~~~~~~~^
../extensions/c++/src/profile.cpp:20:56: error: expected expression
        auto expr = pp->value->to<IR::ExpressionValue>();
                                                       ^
../extensions/c++/src/profile.cpp:21:46: error: expected '(' for function-style cast
      or type construction
        if (expr->expression->is<IR::Constant>()) {
                                 ~~~~~~~~~~~~^
../extensions/c++/src/profile.cpp:21:48: error: expected expression
        if (expr->expression->is<IR::Constant>()) {
                                               ^
../extensions/c++/src/profile.cpp:22:55: error: expected '(' for function-style cast
      or type construction
          auto cst = expr->expression->to<IR::Constant>();
                                          ~~~~~~~~~~~~^
../extensions/c++/src/profile.cpp:22:57: error: expected expression
          auto cst = expr->expression->to<IR::Constant>();
                                                        ^
10 errors generated.

**Comment by mbudiu-vmw** [comment]
This issue should be filed with the p4fpga back-end, which is not part of this repository.

**Comment by SStriver** [comment]
@mbudiu-vmw thank you!
