### ISSUE TITLE
Follow-up to issue 2104, exit also kills all variables

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2151]
A follow up to a previous bug. In issue #2104  return statements killed all subsequent variables. This also happens with exit statements, we missed to cover these.
[2151.txt](https://github.com/p4lang/p4c/files/4109385/2151.txt)

**Comment by mbudiu-vmw** [comment]
If you have a program that crashes the compiler can you please post it?

**Comment by fruffy** [comment]
Attached.

**Comment by mbudiu-vmw** [comment]
The sad thing is that the fix for #2104 does handle exit statements. But, obviously, this is not good enough.
