### ISSUE TITLE
Switchstatement: Assignment in switch-case removed

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2153]
Hello again

I have a question about the semantics of switch statements. During code generation and validation we have encountered a pass which removes the assignment to a variable, which is later used for a condition. The example program is attached.
The pass in question is `SimpleSwitchMidEnd_29_LocalCopyPropagation`. It changes the program from

    control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
        bit<8> tmp_condition_0;
        @name(".NoAction") action NoAction_0() {
        }
        @name("ingress.do_something") action do_something() {
            h.h.a = 8w7;
        }
        @name("ingress.simple_table") table simple_table {
            key = {
                h.h.b: exact @name("h.h.b") ;
            }
            actions = {
                NoAction_0();
                do_something();
            }
            default_action = do_something();
        }
        apply {
            tmp_condition_0 = 8w0;
            switch (simple_table.apply().action_run) {
                NoAction_0: {
                    tmp_condition_0 = 8w1;
                }
            }

            if (tmp_condition_0 > 8w0) {
                sm.egress_spec = 9w1;
            }
        }
    }

to

    control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
        @name(".NoAction") action NoAction_0() {
        }
        @name("ingress.do_something") action do_something() {
            h.h.a = 8w7;
        }
        @name("ingress.simple_table") table simple_table {
            key = {
                h.h.b: exact @name("h.h.b") ;
            }
            actions = {
                NoAction_0();
                do_something();
            }
            default_action = do_something();
        }
        apply {
            switch (simple_table.apply().action_run) {
                NoAction_0: {
                }
            }

            if (8w1 > 8w0) {
                sm.egress_spec = 9w1;
            }
        }
    }

The variable `tmp_condition_0` is removed because it is assumed that `NoAction` is always executed. Is this correct? Our assumption was this expression either does nothing or, if `NoAction` has previously been executed, changes the value of `tmp_condition_0`. The spec says

> At runtime, if no case matches, execution of the program simply continues. However, no label can appear twice in a switch statement. 

which would imply that it might happen that `tmp_condition_0 = 8w1;` is not executed.

[switch_statement.txt](https://github.com/p4lang/p4c/files/4105950/switch_statement.txt)

[2153.p4.txt](https://github.com/p4lang/p4c/files/4109437/2153.p4.txt)
[2153.stf.txt](https://github.com/p4lang/p4c/files/4109438/2153.stf.txt)

**Comment by jafingerhut** [comment]
The first and second programs you show look like they are not equivalent to me, because the first, on the call to simple_table.apply(), might match a table entry installed by the control plane that has action do_something, or the control plane can also install a table entry with action NoAction_0.  At least, nothing in the P4_16 source code, or the ways I know about that auto-generate a control plane API from this source code, would prevent the control plane from doing so.

It seems to me that the compiler should assume that the switch case labeled NoAction_0 might not be executed.

**Comment by jafingerhut** [comment]
Using p4c built from the version of the source code mentioned below, the latest as of 2020-Jan-23, I tried dumping P4_16 source code after each of the compiler's front and mid end passes, to see which was the first pass result that appears incorrect.

It seems to be the one in this file, when I named the test program attached to the original issue as issue2153-1.p4: issue2153-1-BMV2::SimpleSwitchMidEnd_29_LocalCopyPropagation.p4

```
commit 350ab864ca7ecb23e29049b199e5bdb6509ff73e
Author: Andy Fingerhut <andy_fingerhut@alum.wustl.edu>
Date:   Tue Jan 21 13:33:58 2020 -0800

    Add test program that tests catching of incorrect lpm const entries (#2145)
```

**Comment by fruffy** [comment]
Attached a sample program with an stf test

**Comment by jafingerhut** [comment]
I have checked the attached P4 program 2153.p4.txt and STF test 2153.stf.txt.  With the latest p4c, the STF test does fail because of the bug, and I agree that the proposed STF test should pass with a correct P4 compiler.

**Comment by mbudiu-vmw** [comment]
@ChrisDodd : there are two outstanding bugs that seem to be due to the LocalCopyPropagation pass. This is one of them.

**Comment by ChrisDodd** [comment]
Yes, I'm planning on looking into this -- just haven't done so yet.

**Comment by ChrisDodd** [comment]
The problem here is that the ControlFlowVisitor (used by localCopyprop) assumes the switch cases are exhaustive and cover every possible case.  That's not the case here as there is no default: case and not every action is covered in the switch.  We need to detect when the switch cases are not exhaustive and add an implicit do-nothing default.  This is probably easiest to do as a separate pass that inserts a `default: {}` into switch statements that need it, before localCopyprop (or any other control flow analysis) runs.

**Comment by hesingh** [comment]
I take it, the ControlFlowVisitor does not see the switch IR with open and close curly braces that could cue the start and end of the switch block? Once the end of switch block is known, any search for exhaustive switches cases would end.

**Comment by ChrisDodd** [comment]
It sees the SwitchCases in the SwitchStatement, and assumes that exactly one of the BlockStatements in the set of SwitchCases will run.  We could change it to assume 0 or 1, but then if the switch cases *were* exhaustive and none of them were empty, it would incorrectly assume a noop was possible.

**Comment by jafingerhut** [comment]
Closing this issue as I believe it should be fixed by this commit: https://github.com/p4lang/p4c/commit/f01184db7bae64c6fa9bb1f8cb5de80b5b9682f7
