### ISSUE TITLE
Metadata assignment incorrectly eliminated in parser?

### ISSUE THREAD

**Issue by zma-barefoot** [p4lang/p4c#2155]
In program below, if the `start` state transitions to `reject`, the assignment  `m.foo = 32w1` is somehow eliminated after frontend.

```
    state start {
        b.extract<data>(p.hdr);
        transition select(p.hdr.da) {
            8w0xaa: parse_b;
            default: reject;
        }
    }
```

If we change `reject` to `accept`, the issue is not seen. Is this a bug?

```
    state start {
        b.extract<data>(p.hdr);
        m.foo = 32w1;
        transition select(p.hdr.da) {
            8w0xaa: parse_b;
            default: accept;
        }
    }
```

Program:

```
#include <v1model.p4>

header data {
  bit<8> da;
  bit<8> db;
}

struct headers {
    data hdr;
}

struct metadata {
  bit<32> foo;
}

parser ParserImpl(
    packet_in b,
    out headers p,
    inout metadata m,
    inout standard_metadata_t s)
{
  state start {
    b.extract(p.hdr);
    m.foo = 32w1;
    transition select(p.hdr.da) {
        0xaa: parse_b;
#ifdef ISSUE
        default: reject;
#else
        default: accept;
#endif
    }
  }

  state parse_b {
      m.foo = 32w2;
      transition accept;
  }
}

control ingress(
    inout headers hdr,
    inout metadata meta,
    inout standard_metadata_t standard_metadata)
{
    apply {
    }
}

control egress(
    inout headers hdr,
    inout metadata meta,
    inout standard_metadata_t standard_metadata)
{
    apply {
    }
}

control verifyChecksum(inout headers hdr, inout metadata meta) {
    apply { }
}

control computeChecksum(inout headers hdr, inout metadata meta) {
    apply { }
}

V1Switch(
    ParserImpl(),
    verifyChecksum(),
    ingress(),
    egress(),
    computeChecksum(),
    DeparserImpl())
main;

```

**Comment by hesingh** [comment]
It would be good to mention what p4c command you used to test. For example, the bmv2 backend does not even support the code.  See below.

```
hemant@ubuntu:~/int/p4c/build$ ./p4c-bm2-ss --std p4-16 -DISSUE ./foo.p4
./foo.p4(28): [--Wwarn=unsupported] warning: Explicit transition to reject not supported on this target
        default: reject;
                 ^^^^^^
hemant@ubuntu:~/int/p4c/build$ 
```

Next, the P4 program does not include a DepaserImpl().  On adding one and testing with p4test, I don't see a bug.  When default is accept, `m.foo = 32w1;` is retained.  When default is reject, the packet is not processed, so who cares if `m.foo = 32w1;`  is removed.  Also, with default as reject, if the transition goes to state `parse_b`, the `parse_b` state has an assignment (`m.foo = 32w2;`) that overrides any in state start.

**Comment by jafingerhut** [comment]
@hesingh The P4_16 language specification does _not_ say that the packet is not processed if the parser transitions to reject.  It is up to an architecture to define whether that is the case, or not.

About the only thing that the P4_16 language spec says about a parser transitioning to `reject` is that if it is in a sub parser, called from another parser, then the top level parser will transition to reject, too, if a sub parser it calls does, without performing any more state transitions in the calling parser.

So this appears to me like it is a bug, and from looking at the output of the passes in p4c, it appears that the assignment is eliminated in pass 31 of the front end, SimplifyDefUse.

**Comment by hesingh** [comment]
I am going by this example in the p4-16 spec that says "all other packets rejected".  So why wouldn't an architecture not process packets on `default : reject`?  It would be good for the p4-16 spec to clarify the reject state even if the clarification says "up to architecture".  Some text would be useful.

```
transition select(p.ethernet.etherType) {
            0x0800: parse_ipv4;
            // no default rule: all other packets rejected
        }
```

**Comment by jafingerhut** [comment]
Here is a quote from the current P4_16 language spec, section 12.3 "The Parser abstract machine".  If it doesn't make it explicit, please suggest what would:

"An architecture must specify the behavior when the accept and reject states are reached. For example, an architecture may specify that all packets reaching the reject state are dropped without further processing. Alternatively, it may specify that such packets are passed to the next block after the parser, with intrinsic metadata indicating that the parser reached the reject state, along with the error recorded."

**Comment by hesingh** [comment]
Thanks.  Never mind any spec clarification.  

If the architecture does not process any packets with state reject, the SimplifyDefUse pass is doing its job and isn't my analysis correct?

**Comment by jafingerhut** [comment]
The v1model architecture does not drop packets that reach the reject state, and is documented that at least the simple_switch implementation does process packets reaching the reject state, here: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md#restrictions-on-parser-code

**Comment by jafingerhut** [comment]
Hmm, the PSA spec does not say what happens to packets reaching the reject state in the parser, which I consider a bug in the PSA spec, given what the P4_16 language spec says about architecture definitions.  I will file a bug on the PSA spec to address that.

**Comment by jafingerhut** [comment]
Is the p4c front end code is intended to be independent of architecture?  If so, then it definitely seems to be doing the wrong thing here.

If the p4c front end is intended to have architecture-specific behavior in it, then it seems to be doing the wrong thing for the v1model architecture, at least.

**Comment by hesingh** [comment]
Yes, the frontend is architecture-independent.

However, the v1model should differentiate between reaching a reject state via verify and a `default: reject` key set expression.

**Comment by jafingerhut** [comment]
Whether v1model should be visibly different between the two kinds of reject you describe seems like a separate issue to me, from this issue about p4c.  I would recommend creating a separate issue for such a change, from this issue, so it can be discussed and acted upon on its own merits.

**Comment by hesingh** [comment]
If the frontend is architecture-agnostic, why is v1model architecture being enforced on the frontend?  A better approach is to have a configurable option with p4c to enforce parser reject state.

**Comment by mbudiu-vmw** [comment]
How is v1model "enforced by the frontend"?

**Comment by hesingh** [comment]
For this issue, p4c has already assumed parser reject state and "not process the packet" and SimplifyDefUse has changed the IR accordingly.  Isn't the frontend assuming reject state to not process the packet and enforcing a specific architecture behavior?

If this issue is deemed to be bug, then the bug fix has incorporated v1model behavior by letting the packet continue to ingress.

**Comment by mbudiu-vmw** [comment]
Here is a somewhat simpler reproduction:
```
#include <core.p4>

header data {
  bit<8> da;
  bit<8> db;
}

struct headers {
    data hdr;
}

struct metadata {
  bit<32> foo;
}

parser ParserImpl(
    packet_in b,
    out headers p,
    inout metadata m)
{
  state start {
    b.extract(p.hdr);
    m.foo = 32w1;
    transition select(p.hdr.da) {
        0xaa: parse_b;
#ifdef ISSUE
        default: reject;
#else
        default: accept;
#endif
    }
  }

  state parse_b {
      m.foo = 32w2;
      transition accept;
  }
}

parser P<H, M>(packet_in b, out H h, inout M m);
package top<H, M>(P<H, M> p);
top(ParserImpl()) main;
```

**Comment by jafingerhut** [comment]
@hesingh I do not know the root cause of this bug.  I trust that others will figure that out and be able to fix it.

By fixing it, I mean that the generated code for a P4 parser should end in the state that the P4_16 language specification says it should end in, which is true _regardless of the architecture_.  If an architecture then behaves the same way processing the packets that end in reject state vs. accept state, that is architecture-specific, but the P4 code for the parser would be correct for all architectures.

**Comment by hesingh** [comment]
Ok, sounds good to me - thanks.

**Comment by hesingh** [comment]
Without looking at any p4c code, I had surmised what was going on by just reading the few lines of parser code.  This debugged log proves my analysis is correct.

[debugged-reject-log.pdf](https://github.com/p4lang/p4c/files/4131392/debugged-reject-log.pdf)
