### ISSUE TITLE
Associative order of shift operators

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2161]
Follow-Up to #2156 
Thanks for fixing this so quickly. I have a minor follow-up running the latest version of the compiler. I reran all the p4c tests and stumbled across an issue in one of the test files (`strength3.p4`). After the lowering pass (`PassManager_7_LowerExpressions`) I get the following output:

```c
/* 
<AssignmentStatement>(120252)
  <Member>(84583)c
    <Member>(84584)h
      <PathExpression>(84585)
        h
  <Cast>(120273)
    <Cast>(120272)
      <Shr>(120271)
        <Shr>(84588)
          <Member>(84589)a
            <Member>(84590)h
              <PathExpression>(84591)
                h
          <Constant>(1166) 3
            <Type_InfInt>(1165)
        <Constant>(120270) 8
          <Type_InfInt>(120269)
      <Type_Bits>(1111)
    <Type_Bits>(1111) */
h.h.c = (bit<8>)(bit<8>)(h.h.a >> 3 >> 8);
```

Parsing this again I get:

```c
/* 
<AssignmentStatement>(1218)
  <Member>(1201)c
    <Member>(1200)h
      <PathExpression>(1198)
        h
  <Cast>(1217)
    <Cast>(1216)
      <Shr>(1215)
        <Member>(1209)a
          <Member>(1208)h
            <PathExpression>(1206)
              h
        <Shr>(1214)
          <Constant>(1211) 3
            <Type_InfInt>(1210)
          <Constant>(1213) 8
            <Type_InfInt>(1212)
      <Type_Bits>(1111)
    <Type_Bits>(1111) */
h.h.c = (bit<8>)(bit<8>)(h.h.a >> (3 >> 8));
```

Functionally, this is the same since shifts are associative, right? But why is the parser bracketing from right-to-left instead of left-to-right?
Full programs:
[shift_associativity.p4.txt](https://github.com/p4lang/p4c/files/4125104/shift_associativity.p4.txt)
[shift_associativity_parsed.p4.txt](https://github.com/p4lang/p4c/files/4125105/shift_associativity_parsed.p4.txt)

**Comment by mbudiu-vmw** [comment]
shifts are not associative.

**Comment by mbudiu-vmw** [comment]
I cannot reproduce this problem. What have you done to produce the second code fragment?

**Comment by fruffy** [comment]
Oh you are right.
Hmm I just tried this again and I got the same output.
The command is:
```
/p4c/build/p4c --top4 ParseAnnotationBodies_0_ParseAnnotations --dump
 dmp -v shift_associativity.p4
```
On the example file I provided.

**Comment by mbudiu-vmw** [comment]
Actually the following seems to be a reproduction:
```
action c(inout bit<16> a) {
    a = a >> 3 >> 8;
}
```

@ChrisDodd : shouldn't `>>` associate left? This seems to be parsed as `a = a >> (3 >> 8)`, as you can see by dumping it with `--pp x.p4`.

**Comment by hesingh** [comment]
At least C treats `>>`  as left to right associative.  I don't see the P4-16 spec say anything about such operator associativity.

**Comment by mbudiu-vmw** [comment]
An even simpler example is `const bit<32> c = 1 >> 3 >> 8;`
This program is parsed right-associative.
If you change the shift to a left shift it is parsed as left-associative.
@ChrisDodd : is this because we actually have two associativity rules with different priorities, one for R_ANGLE and one for R_ANGLE_SHIFT?
```
%left COMMA
%nonassoc QUESTION
%nonassoc COLON
%left OR
%left AND
%left EQ NE
%left L_ANGLE R_ANGLE LE GE
%left BIT_OR
%left BIT_XOR
%left BIT_AND
%left SHL R_ANGLE_SHIFT
```
