### ISSUE TITLE
Annotating extern functions

### ISSUE THREAD

**Issue by rhalstea** [p4lang/p4c#217]
Is their a way to annotate extern functions? I was looking around p4-parse.ypp and it didn't look like it. I also tried the following code (which seemed natural to me), but p4test gave me a syntax error.
```
@name("foo")
extern void foo(inout bit<8> arg);
```
Do I just have the syntax wrong?

I didn't see anywhere in the spec that this shouldn't be allowed, and externs are a place target specific annotations would be useful.

**Comment by mbudiu-vmw** [comment]
Normally externs are part of the architectural description for your target.
So it is expected that normal P4 users cannot declare any new externs - after all, the back-end would not know what to do with them. 

If you can make a case that annotations on externs do provide some value, then we can consider extending the grammar to accommodate them. 

Given your example, why would you want to use a @name annotation on an extern?

**Comment by rhalstea** [comment]
I can see why some back-ends would want to restrict users from declaring externs. From an FPGA point-of-view though I'd like to use the externs as interface declarations that create holes in the switch pipeline. We'll write some of our own (i.e. checksums, hashes, etc.) with the relevant RTL that fills in the hole, but this can also be opened up to users who want to customize their own design (different hash function for example).

The @name annotation may not be useful here, but knowing the # of cycles would be useful for an FPGA. So something like:
```
@CYCLES(5)
extern void my_hash_function(inout bit<8> arg);
```
Knowing this would allow the FPGA back-end to allocate registers instead of back pressuring (which would also like to know the number of cycle so it doesn't have to allocate buffers for the worst case if it doesn't have to).

**Comment by mbudiu-vmw** [comment]
That makes sense: you consider externs as interface declarations, and you allow users to write new extern implementations. Then you have a linker stage which resolves them, so the compiler back-end does not need to know how to handle unknown externs. I will look into adding annotations for extern function and object declarations; I hope that the grammar will not cause any problems.

**Comment by mbudiu-vmw** [comment]
You can now have annotations on extern objects and functions.
(I didn't add annotations on each extern method, but you may want that too.)

**Comment by rhalstea** [comment]
Thanks.

Having annotations at the object level is enough for my current needs. I'll close this for now, and reopen it later if I find a need for them around each method.
