### ISSUE TITLE
RemoveReturns deletes return in SwitchStatements

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2170]
I have the following program snippet tested on the latest compiler version (f01184d).

```c
@name("do_something") action do_something_0() {
    stdmeta.egress_spec = 9w0;
}
@name("simple_table") table simple_table_0 {
    key = {
        hdr.h.b: exact @name("hdr.h.b") ;
    }
    actions = {
        NoAction();
        do_something_0();
    }
    default_action = NoAction();
}
apply {
    switch (simple_table_0.apply().action_run) {
        NoAction: {
            return;
        }
        default: {
        }
    }

    hdr.h.a = 8w0;
}
```
after the `RemoveReturns` pass this is turned into:

```c
@name("do_something") action do_something_0() {
    stdmeta.egress_spec = 9w0;
}
@name("simple_table") table simple_table_0 {
    key = {
        hdr.h.b: exact @name("hdr.h.b") ;
    }
    actions = {
        NoAction();
        do_something_0();
    }
    default_action = NoAction();
}
apply {
    bool hasReturned = false;
    switch (simple_table_0.apply().action_run) {
        NoAction: {
            {
                hasReturned = true;
            }
        }
        default: {
        }
    }

    hdr.h.a = 8w0;
}
```

This does not look right to me. What is the scope of a return statement in 
a switch statement? Are they meant to be valid? The spec says: 

> The return statement immediately terminates the execution of the action, function or control containing it.

So that would mean that the control terminates and `hdr.h.a = 8w0` is not executed. However, after the pass this assignment is always executed.
[return_in_switch.p4.txt](https://github.com/p4lang/p4c/files/4136239/return_in_switch.p4.txt)
[return_in_switch.stf.txt](https://github.com/p4lang/p4c/files/4136247/2153.stf.txt)

**Comment by hesingh** [comment]
I am curios. Why is `do_something_0` action not included in the switch statement?  You seem to process such an action in `default`?

Also, if I dump FrontEndLast, the code looks correct:

```
control ingress(inout Parsed_packet hdr, inout Metadata meta, inout standard_metadata_t stdmeta) {
    @name(".NoAction") action NoAction_0() {
    }
    @name("ingress.do_something") action do_something() {
        stdmeta.egress_spec = 9w0;
    }
    @name("ingress.simple_table") table simple_table_0 {
        key = {
            hdr.h.b: exact @name("hdr.h.b") ;
        }
        actions = {
            NoAction_0();
            do_something();
        }
        default_action = NoAction_0();
    }
    apply {
        bool hasReturned = false;
        switch (simple_table_0.apply().action_run) {
            NoAction_0: {
                hasReturned = true;
            }
        }

        if (!hasReturned) {
            hdr.h.a = 8w0;
        }
    }
}
```

**Comment by jafingerhut** [comment]
@hesingh I do not understand why you ask this question: "Why is do_something_0 action not included in the switch statement? You seem to process such an action in default?"

I think the point of the issue is that _if_ this particular P4 program is given as input to the compiler, its output seems to be incorrect.  That input P4 program looks syntactically correct, and its behavior is defined by the P4_16 language spec to be be a particular behavior.

Is your question: "Why would a P4 developer write a program like this?"  That seems to be a different question from "is the p4c compiler correctly handling this program?"

**Comment by hesingh** [comment]
@jafingerhut ok.  I asked only out of curiosity.

The P4 compiler aims to have correct output at the end of frontend and midend processing.  Any intermediate processing may not match the spec. 

As I showed in my test log, the program dumped at FrontEndLast looks correct to me because the return causes exiting out of the switch statement.  However, the spec does not mention any exit out of switch statement due to a return.   So, FrontEndLast is not compliant with the spec.

**Comment by jafingerhut** [comment]
@hesingh If intermediate processing steps are not equivalent to the input program, then that is a red flag that is likely the sign of a compiler bug in that pass, or an earlier pass, yes?  If the behavior changes _again_ in a later pass to be back to the original input program behavior, then that sounds like either masking of the bug in an earlier pass, or even worse, a second bug in a later pass masking the bug in the earlier pass.

I will try out the input program with a matching version of p4c source code as linked in the original issue to do a little triage on this, and see where things appear to first go wrong.

The spec also does not mention explicitly the behavior of a `return` statement inside of an `if` statement.  So either that isn't defined, or what I believe is more likely: the intent of the existing spec language in the spec is that if you call `return` _anywhere_ inside of an action, function, or control, it is defined to behave as stated.

**Comment by fruffy** [comment]
@hesingh 
The programs are designed to stress-test the compiler, so they are often nonsensical, but valid. In this case, do_something is just an alternative action to NoAction.

I just retested this and the issue, at least for me, appears in every output after `FrontEnd_37_RemoveReturns` with the latest commit (f01184d) , b0a1168 does not have this problem.

**Comment by hesingh** [comment]
Thanks @fruffy Understood.  I had only asked my questions out of curiosity.   Great that you narrowed down the issue between two checkin's to p4c.   

All your work is greatly appreciated to find issues in p4c.

**Comment by jafingerhut** [comment]
Nothing new here, just confirming that with the same version of p4c source code as reported in the original comment: https://github.com/p4lang/p4c/commit/f01184db7bae64c6fa9bb1f8cb5de80b5b9682f7
the output of the RemoveReturns pass looks wrong, assuming that the intent of the P4_16 language spec is that a `return` statement should also work from within a  `switch` statement.  If for some reason it should not work, the spec should be clarified on that point.

**Comment by hesingh** [comment]
More corroboration. The switchCase in the p4 lang grammar uses blockStatement.  The removeReturns pass works with blockStatements and this is why the pass processed the switchCases's blockStatement as an entity for return.   We should edit the spec or change the removeReturns pass.
