### ISSUE TITLE
Question on precise behavior of copy-out

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2176]
I have the following program:

```p4
control ingress(inout Parsed_packet h, inout Metadata m, inout standard_metadata_t sm) {
    action do_action(inout bit<8> val_0, inout bit<8> val_1, inout bit<8> val_2) {
        val_1 = 8w2;
        val_2 = 8w0;
    }
    apply {
        do_action(h.h.b, h.h.b, h.h.b);
        if (h.h.b > 8w1) {
            h.h.a = 8w1;
        }
    }
}
```
After `FrontEnd_28_SideEffectOrderin`, this gets turned into 

```p4
control ingress(inout Parsed_packet h, inout Metadata m, inout standard_metadata_t sm) {
   action do_action(inout bit<8> val_0, inout bit<8> val_1, inout bit<8> val_2) {
        val_1 = 8w2;
        val_2 = 8w0;
    }
    bit<8> tmp;
    bit<8> tmp_0;
    apply {
        {
            tmp = h.h.b;
            tmp_0 = h.h.b;
            do_action(tmp, tmp_0, h.h.b);
            h.h.b = tmp;
            h.h.b = tmp_0;
        }
        if (h.h.b > 8w1) {
            h.h.a = 8w1;
        }
    }
}
```
According to the [copy-out](https://p4.org/p4-spec/docs/P4-16-v1.2.0#sec-calling-convention) semantics, variables are copied back left-to-right. So the assignment of val_2 should be copied back. However, in this case it is ignored. Why?

I also attached an stf test that shows that `val_2 = 8w0;` is not executed. Oddly enough, this only happens with an uneven amount of parameters. For example, I have only been able to trigger this behaviour with three or five parameters, not four or seven.

[inout_copy_out.p4.txt](https://github.com/p4lang/p4c/files/4148462/inout_copy_out.p4.txt)
[inout_copy_out.stf.txt](https://github.com/p4lang/p4c/files/4148463/inout_copy_out.stf.txt)

**Comment by jafingerhut** [comment]
That does appear to be a bug.

I would add that I think a lot of people would prefer to see a big fat warning from a compiler for programs that pull these kinds of shenanigans, i.e. copy-out is done to the same to the same bits of storage multiple times at the caller on return.  While the behavior is defined in the language spec, it seems guaranteed to be confusing to anyone trying to understand the behavior of such code.

**Comment by mbudiu-vmw** [comment]
@jafingerhut : perhaps you can file a separate issue if you think this is worth a warning.

**Comment by mbudiu-vmw** [comment]
@fruffy : I think I have a fix, but the STF file you supplied does not seem to be correct.
Can you please double-check it?

**Comment by fruffy** [comment]
The stf file you provided is correct, I think mine was meant for a different case, sorry about the confusion. I can validate the full fix tomorrow, too.
