### ISSUE TITLE
Support exact match on values of `type` types

### ISSUE THREAD

**Issue by konne-google** [p4lang/p4c#2177]
p4c currently only allows exact matches on bits, serializable enums, enums, errors, and booleans ([source](https://github.com/p4lang/p4c/blob/master/frontends/p4/typeChecking/typeChecker.cpp#L3405)). It should also support exact matches on values of `type` types.

**Comment by jafingerhut** [comment]
Can you provide a complete sample test program, and what error messages, if any, it gives when you attempt to compile it with these commands and a recent version of p4c source code `p4test file.p4`, `p4c file.p4`?  My memory may be fuzzy here, but I think that already works with `p4test` without errors, and that the current limitations might be localized to the BMv2 back end.

**Comment by jafingerhut** [comment]
You may also want to try generating a P4Info file with your test program, and if one is generated, whether it looks like it conforms to what you expect.

**Comment by konne-google** [comment]
I get the error message "... field type must be a scalar type; it cannot be ...". I search this string an it only appears in the compiler front end ([source](https://github.com/p4lang/p4c/blob/master/frontends/p4/typeChecking/typeChecker.cpp#L3405)). So I'm pretty sure this is in the compiler frontend. Do you still think I should run some experiments?

**Comment by konne-google** [comment]
Oh, you are actually right, this should already work as expected. I just used an old version of the compiler and didn't parse the code correctly. `IR::Type_Newtype` corresponds to the `type` keyword ([source](https://github.com/p4lang/p4c/blob/master/frontends/parsers/p4/p4parser.ypp#L1053)).

**Comment by hesingh** [comment]
I added support for `type` to p4c via this checkin.

https://github.com/p4lang/p4c/commit/8dc6f510fada60c0ebc50937280484be1a5b7382#diff-3978db25bf69a1a9b64e21ce4135fd02

See testdata/p4_16_samples/p416-type-use3.p4 with several examples of `type` as table key which works.

**Comment by jafingerhut** [comment]
Well, which definitely works at least through p4c's front end, and I have forgotten how far it went in terms of P4Info generation and BMv2 generation.  It wouldn't be surprising if there are some rough edges left to be found there, but best to have an explicit test case and problem in a report for what is believed to be missing at this point, to localize what isn't working (if anything isn't).

**Comment by hesingh** [comment]
`type` has been tested for table matchkey and not anything else.  It was Andy who provided the P4 code to test the `type` p4c changes..
