### ISSUE TITLE
C++17?

### ISSUE THREAD

**Issue by smolkaj** [p4lang/p4c#2186]
Are there plans to move to C++17 in the near future?

I assume p4c currently sticks to C++11 out of a desire to compile on Ubuntu 16.4 using the default compilers. However, Ubuntu 16.4's support will end in [about a year](https://en.wikipedia.org/wiki/Ubuntu#Releases) and has been superseded by Ubuntu 18.4 LTS since 2018; Ubuntu 20.4 LTS is about to be releaed; and both support C++17 out of the box. So I'm curious if moving to C++17 may be on the table?

**Comment by hesingh** [comment]
Gee, I asked the same question during making some code changes to p4c for a new feature.  I was told there are production p4c releases for hardware with some companies which are still using c++11.  A move to higher version of c++ is blocked as a result.  I suppose when the p4 community is ready, a move may happen.

**Comment by hesingh** [comment]
I noticed at Barefoot's support page that they too support Ubuntu 18.04 for their SDE.  I and some 
others build p4c on Ubuntu18.04.  At least I have used p4c and Ubuntu 18.04 for over one year.

**Comment by smolkaj** [comment]
@hesingh: Right, compiling C++11 on newer Ubuntus should not be an issue since the compilers are backward compatible.

**Comment by hesingh** [comment]
@smolkaj Anything specific from c++17 you were looking at to use for p4c?  IMHO, there's no reason why you can't fork p4c, use c++17, and develop your p4c feature.   Later, when c++17 is approved for p4c, the code changes would be useful.

**Comment by jafingerhut** [comment]
"IMHO, there's no reason why you can't fork p4c, use c++17, and develop your p4c feature. Later, when c++17 is approved for p4c, the code changes would be useful."  No reason except perhaps having to wait an unknown length of time before the changes are possibly acceptable, during which they are not very useful to anyone else, and may gain conflicting merges over that waiting time. Who wants to plan to wait an unknown length of time?

**Comment by hesingh** [comment]
It's not unknown time.  For example, I have my new super duper asic.  I pull a branch of p4c in my private repo.  I use c++17 compiler and make sure p4c builds and passes testing.  Then I develop new c+=17 code.  At periodic instances, I sync down changes from p4c.  When I am ready, I ship my asic, its private p4c, and my customer uses the software.

**Comment by hesingh** [comment]
https://www.theregister.co.uk/2018/06/18/bjarne_stroustrup_c_plus_plus/

With this note about c++17 I put between double quotes.

"The foundation begun in C++11 is not yet complete, and C++17 did little to make our foundation more solid, regular, and complete. Instead, it added significant surface complexity and increased the number of features people need to learn. C++ could crumble under the weight of these – mostly not quite fully-baked – proposals. We should not spend most our time creating increasingly complicated facilities for experts, such as ourselves."

**Comment by smolkaj** [comment]
Feel free to close this if there is no further information on this currently.
