### ISSUE TITLE
Compiler Bug: At this point in the compilation typechecking should not infer new types  anymore, but it did.                                                                                          

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2190]
Hello again,
after commit 1159ced13676cba54520474d4e416b314302c1db we encounter the compiler bug in the title for specific programs. I attached an example.
The exact command is `p4c/build/p4c -v bad_type_checking.p4`.
[bad_type_checking.p4.txt](https://github.com/p4lang/p4c/files/4161569/bad_type_checking.p4.txt)

**Comment by mbudiu-vmw** [comment]
We should only add the numbers if they have the same type.

**Comment by jafingerhut** [comment]
A question about this strength reduction transformation that sometimes changes ((a >> b) >> c) to (a>> (b + c)).  Could the transformation be done if the type of the expression (b+c) is `bit<W>`, and the addition of (b+c) wraps around?

**Comment by mbudiu-vmw** [comment]
Yes, with the current code this can happen.
We could also only do it if both b and c are InfInt.

**Comment by mbudiu-vmw** [comment]
Please file another issue.

**Comment by mbudiu-vmw** [comment]
Or perhaps let's fix it in this PR, just request changes.

**Comment by mbudiu-vmw** [comment]
@fruffy can you catch this overflow bug?

**Comment by fruffy** [comment]
Yes, I tested it on the branch. I attached a sample program and stf file.
The overflow causes the shift to turn to zero.
[addition_overflow.p4.txt](https://github.com/p4lang/p4c/files/4171112/addition_overflow.p4.txt)
[addition_overflow.stf.txt](https://github.com/p4lang/p4c/files/4171113/addition_overflow.stf.txt)

**Comment by fruffy** [comment]
Output of the tool where it detected a difference is something like this:

```
FrontEnd_13_BindTypeVariables:
mk_Parsed_packet(
	mk_ethernet_t(
		dstAddr(eth(hdr(ingress_0))),
		srcAddr(eth(hdr(ingress_0))),
		etherType(eth(hdr(ingress_0)))),
	 mk_H(
		 0, <--- value of hdr.h.a
		 b(h(hdr(ingress_0))))
	)
)

FrontEnd_17_StrengthReduction:
mk_Parsed_packet(
	mk_ethernet_t(
		dstAddr(eth(hdr(ingress_0))),
		srcAddr(eth(hdr(ingress_0))),
		etherType(eth(hdr(ingress_0)))),
	 mk_H(
		 1, <--- value of hdr.h.a
		 b(h(hdr(ingress_0))))
	)
)
```
