### ISSUE TITLE
Werror=overlimit when failing compilation?

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#2197]
Recent versions of p4c print the following when they abort compilation because of a program error:
```
[--Werror=overlimit] error: 1 errors encountered, aborting compilation
```
What's the point of the `[--Werror=overlimit]` tag here? We are not outputting a new error, just summarizing the error count and indicating that compilation failed.

**Comment by mbudiu-vmw** [comment]
All error messages must have some category (shown in []), since we are deprecating the old API.
Among the existing categories this was the best match...

**Comment by mbudiu-vmw** [comment]
This is in fact a new call to the ::error function, so it is treated as a new error.

**Comment by antoninbas** [comment]
I personally don't think it should be a call to `::error`. It increases the error count for no reason?

I count 3 different places in the code base where we print a similar error message. Only one uses the `ERR_OVERLIMIT` error type.
