### ISSUE TITLE
Implicit reject transition when select expressions has no default

### ISSUE THREAD

**Issue by rhalstea** [p4lang/p4c#220]
In the CreateBuiltins pass an implicit transition to reject is inserted if there is no selectExpression. For completeness shouldn't this also be done if the SelectExpression has no default transition?

**Comment by mbudiu-vmw** [comment]
The spec requires the error to be set to "NoMatch" in this case.
So the two are not equivalent. But maybe we can insert an extra state for this purpose:

```
state X { select (e) { } }
```
becomes
```
state X { select (e) { default: nomatch; } }
state nomatch { verify(false, error.NoMatch); } 
```

**Comment by rhalstea** [comment]
I see. That makes sense. I think the extra state would be useful then since a goal for the front-end is to enforce these type of cases.

**Comment by mbudiu-vmw** [comment]
I have created a mid-end pass called HandleNoMatch. The bmv2 backend does not use or need it, but it is part of the ebpf and p4test mid-ends. I will submit a pull request soon.

**Comment by rhalstea** [comment]
thank you Mihai.
