### ISSUE TITLE
Compiler Bug: boost::too_few_args

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2207]
Similar to #2206, the attached program leads to a boost error after the `FrontEnd_9_CheckNamedArgs` pass. 
I think because of the slice operation the `FrontEnd_4_ResolveReferences` does not detect that the width of the expression is unknown?
[b.p4.txt](https://github.com/p4lang/p4c/files/4239638/b.p4.txt)

**Comment by mbudiu-vmw** [comment]
I cannot reproduce this issue.
```
$ ./p4test --top4 4 issue2207.p4
issue2207.p4(25): error: ~: Operation cannot be applied to values with unknown width;
please specify width explicitly
        h.h.a = ~(0 << 8w1);
                ^^^^^^^^^^^
```

Are you running the latest version of the compiler? 
The error you are indicating suggests a bug in an error message format; we have recently merged a change in the way error message formats are handled.

**Comment by mbudiu-vmw** [comment]
BTW: compilation does not reach pass 9, it stops in pass 5. So I don't know how you reached FrontEnd_9.

**Comment by fruffy** [comment]
I rebuilt and tried to reproduce this. I can't and I also cannot identify the commit that might have caused this. Seems like a fluke.
