### ISSUE TITLE
Compiler bug when attempting to compile nested struct initializer

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#2213]
The attached program causes a compiler bug when attempting to compile it with p4c 1.2.0 SHA: 62fd40a0.  Commenting out the following line enables the same version of p4c to compile the rest of the code:
```
        meta.s2 = {s1={f1=2, f2=3}, f3=5, f4=8};
```
Similar lines that use struct initializers that are not nested appear to work correctly, so perhaps the issue is because of the nested struct initializer expression.

Is this an expected use of struct initializer expressions according to the language spec?  It seems grammatically correct, at least, but may be bad for other reasons.

[nested-struct-initializers.p4.txt](https://github.com/p4lang/p4c/files/4252345/nested-struct-initializers.p4.txt)

**Comment by mbudiu-vmw** [comment]
The problem is that typeInference does not convert the list initializer for the inner struct to a struct-valued expression.
