### ISSUE TITLE
StrengthReduction ignores side-effects in function calls

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2221]
`StrengthReduction` (or `PassRepeated` in the latest version) transforms the following program:

```p4
bit<16> function_with_side_effect(inout bit<16> eth_type) {
    eth_type = 16w0x806;
    return 16w2;
}
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    apply {
        bit<16> dummy_var;
        dummy_var = 16w0 & function_with_side_effect(h.eth_hdr.eth_type);
        dummy_var = 16w0 * function_with_side_effect(h.eth_hdr.eth_type);
        dummy_var = 16w0 >> function_with_side_effect(h.eth_hdr.eth_type);
    }
}
```
into 
```p4 
bit<16> function_with_side_effect(inout bit<16> eth_type) {
    eth_type = 16w0x806;
    return 16w2;
}
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    apply {
        bit<16> dummy_var;
        dummy_var = 16w0;
        dummy_var = 16w0;
        dummy_var = 16w0;
    }
}
```
which ignores the side effects in the method-call expression.

[zero_op_with_side_effects.p4.txt](https://github.com/p4lang/p4c/files/4276248/zero_op_with_side_effects.p4.txt)
[zero_op_with_side_effects.stf.txt](https://github.com/p4lang/p4c/files/4361525/zero_op_with_side_effects.stf.txt)

**Comment by mbudiu-vmw** [comment]
@fruffy : is this stf file the expected output?
It looks wrong to me.

**Comment by fruffy** [comment]
Fixed. There was some bug with the tool I was using to generate these. 

[zero_op_with_side_effects.stf.txt](https://github.com/p4lang/p4c/files/4361529/zero_op_with_side_effects.stf.txt)

**Comment by mbudiu-vmw** [comment]
you should probably write a stronger test; this one will still work if one of the calls is eliminated.
you can for example count the number of calls made.

**Comment by fruffy** [comment]
Is that list of optimizations even exhaustive? What other expressions could lead to this?
[2221.p4.txt](https://github.com/p4lang/p4c/files/4361672/2221.p4.txt)
[2221.stf.txt](https://github.com/p4lang/p4c/files/4361674/2221.stf.txt)

**Comment by mbudiu-vmw** [comment]
Feel free to review my PR for fixing this. I hope I have covered all cases, but who knows?
In general, there may be an error if you look at one operand of a binary expression and remove the other.
