### ISSUE TITLE
Calling exit in actions after an assignment

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2225]
I have a question on the behaviour of exit in the control pipeline.
I have the following transformation in an action

```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    @name("ingress.do_action") action do_action(inout bit<16> val_0) {
        val_0 = 16w3;
        exit;
    }
    apply {
        do_action(h.eth_hdr.eth_type);
    }
}
```
to
```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    bit<16> val_0;
    @name("ingress.do_action") action do_action() {
        val_0 = h.eth_hdr.eth_type;
        val_0 = 16w3;
        exit;
        h.eth_hdr.eth_type = val_0;
    }
    apply {
        do_action();
    }
}
```
So `eth_type` is assigned after the exit call, instead of before. What is supposed to happen when I call `exit`? Is the program still emitting the packet? Or is the header reset?
This happens after `SimpleSwitchMidEnd_4_RemoveActionParameters`.

[exit_in_action.p4.txt](https://github.com/p4lang/p4c/files/4289067/exit_in_action.p4.txt)
[exit_in_action.stf.txt](https://github.com/p4lang/p4c/files/4289068/exit_in_action.stf.txt)

**Comment by jafingerhut** [comment]
When you say "I have the following transformation in an action", do you mean that the p4c compiler in one of its front or midend passes turned the first program into the second?  If so, that sounds very odd to me, but a full example program of that might be interesting for debug purposes.

My understanding is that when 'exit' is executed, the enclosing control, and all of the controls "up the call stack" are immediately terminated.  Whatever happens in the architecture _after_ that control finishes executing still happens, e.g. after Ingress in v1model, the architecture still checks whether standard_metadata.mcast_grp is 0 or non-0 (meaning the packet should be multicast using that group id), and if 0 whether standard_metadata.egress_spec is the special drop port, or a normal port, whether the packet should be cloned, etc.  'exit' does _not_ mean "drop the packet".  It means "immediately terminate the current control, executing no further statements within it".

**Comment by fruffy** [comment]
> do you mean that the p4c compiler in one of its front or midend passes turned the first program into the second? 

Yes, I attached a sample program with the corresponding stf test. The pass in question is `SimpleSwitchMidEnd_4_RemoveActionParameters`.

>My understanding is that when 'exit' is executed, the enclosing control, and all of the controls "up the call stack" are immediately terminated. Whatever happens in the architecture after that control finishes executing still happens

Okay that would be in line with my interpretation of exit.

**Comment by fruffy** [comment]
The ultimate version of this program after `exit_in_action-PassManager_4_MoveActionsToTables.p4i` is actually this

```p4 
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    @name("ingress.do_action") action do_action() {
        exit;
        h.eth_hdr.eth_type = 16w3;
    }
    @hidden table tbl_do_action {
        actions = {
            do_action();
        }
        const default_action = do_action();
    }
    apply {
        tbl_do_action.apply();
    }
}
```

**Comment by jafingerhut** [comment]
Sorry, I missed that you included a complete program when writing my earlier comment.  I tried it out, and see the same transformation.  That step appears to me not to change the behavior of the program, because the first assignment introduced is killed by the later assignment, and the assignment after the exit will never be executed.

The next change I see is after step 29 LocalCopyPropagation, where it changes the action from this:
```
    @name("ingress.do_action") action do_action() {
        val_0 = h.eth_hdr.eth_type;
        val_0 = 16w3;
        exit;
        h.eth_hdr.eth_type = val_0;
    }
```
to this:
```
    @name("ingress.do_action") action do_action() {
        exit;
        h.eth_hdr.eth_type = 16w3;
    }
```
Given that `val_0` is not used anywhere else in the program after this, that still appears equivalent to the original program behavior, since the statement after the exit will not be executed, but it does make me wonder whether there might be bugs in the compiler involving moving things from before to after exit in other programs.  I do not know the compiler internals well enough to make more than a guess on that, though.

**Comment by jafingerhut** [comment]
As an aside, the transformed program would definitely be a little bit simpler and clearer if there were no statements remaining in the action after the `exit;` call, since they cannot be executed.

**Comment by fruffy** [comment]
So the original input program is this
```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    action do_action(inout bit<16> val_0) {
        val_0 = 3;
        exit;
    }
    apply {
        do_action(h.eth_hdr.eth_type);

    }
}
```
since val_0 is an `inout` parameter `h.eth_hdr.eth_type` is assigned `3`. But this assignment is flipped after the pass.
`h.eth_hdr.eth_type = val_0;` should be above the `exit` not below.

**Comment by fruffy** [comment]
Unless this is related to the copy-in, copy-out semantics, then you are right and this is not a bug.

**Comment by jafingerhut** [comment]
In P4_16 'inout' does not mean "pass by reference", but "copy in at call time, copy out on return".  Due to the 'exit', I am pretty sure the "copy out on return" should never happen, but it seems good to ping other language experts like @mbudiu-vmw and @jnfoster on that detail.

**Comment by jafingerhut** [comment]
@fruffy You might want to have your fuzzer try some `if` statements inside of actions where `exit` is done conditionally, with `inout` parameters to the action, to see if those find any problems.  That is just a guess on my part -- maybe no bugs will be found as a result, but the local copy propagation "transmitting information from before the exit call to after" that we see here makes me wonder.

**Comment by jafingerhut** [comment]
I created an issue on the language spec to raise this question: https://github.com/p4lang/p4-spec/issues/822

It seems worthwhile to be more explicit in the spec about this, whatever the answer is to whether the copy-out should or should not be performed after executing return/exit statements.

**Comment by fruffy** [comment]
Thanks! I just tested some combinations of conditional exit in actions but could not detect any suspicious behaviour.

**Comment by jafingerhut** [comment]
I would recommend leaving this issue open until that language spec issue is resolved.  Some of the comments I have added there since creating it lead me to believe that perhaps it _should_ be the case that copy-out occurs, even if a `return` or `exit` statement are executed inside of a control/action.

**Comment by fruffy** [comment]
Just to add another test, sideEffectOrdering may also be influenced by exit calls

```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    @name("call_exit") action call_exit_0(out bit<48> val, in bit<48> val1) {
        exit;
    }
    apply {
        call_exit_0(h.eth_hdr.src_addr, h.eth_hdr.src_addr);
    }
}
```

to 

```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    @name("call_exit") action call_exit_0(out bit<48> val, in bit<48> val1) {
        exit;
    }
    bit<48> tmp;
    bit<48> tmp_0;
    apply {
        {
            tmp_0 = h.eth_hdr.src_addr;
            call_exit_0(tmp, tmp_0);
            h.eth_hdr.src_addr = tmp;
        }
    }
}
```

[side_effect_ordering_exit.p4.txt](https://github.com/p4lang/p4c/files/4361621/side_effect_ordering_exit.p4.txt)

**Comment by jafingerhut** [comment]
The P4 language specification issue https://github.com/p4lang/p4-spec/issues/822 mentioned earlier was resolved today.  You can read the details of the changes in the newest language spec, but basically the idea is that after a return or exit is executed, all relevant copy-out behavior for all `out` and `inout` direction parameters should happen after that.

**Comment by jafingerhut** [comment]
@fruffy I suspect you are following changes in state on these issues, but in case not, the latest version of p4c has a proposed fix for this issue.  I believe it correctly handles at least the two test programs attached in comments to this issue, exit_in_action.p4.txt and side_effect_ordering_exit.p4.txt.  Hopefully it handles arbitrary programs correctly, too, but just wanted to ping you so you realize you can try out more test cases in this area that you may have.

**Comment by fruffy** [comment]
Thanks for letting me know about this! I mostly track everything that is ongoing in p4c and p4-spec nowadays to keep everything up-to-date and avoid false-positives. I will start testing again in the coming week, will definitely check exits statements.
