### ISSUE TITLE
No compile-time error for assignment between headers of different types, or between header and struct, with same fields

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#2230]
Should the attached program give compile-time errors, once for each of the assignments between headers/structs of different types in the ingress control?

The indicated version of p4c gives no compile-time errors at all.  It produces a BMv2 JSON file using the normal shown command for attempting to do so.  Bmv2 simple_switch gives run-time errors for 2 of the 3 assignments (exiting the simple_switch process), because the src and dst of the assignment have different types.

```
$ p4c --version
p4c 1.2.0 (SHA: 62fd40a0)

$ p4c --target bmv2 --arch v1model assign-compatibility2.p4
```

[assign-compatibility2.p4.txt](https://github.com/p4lang/p4c/files/4309716/assign-compatibility2.p4.txt)

**Comment by hesingh** [comment]
According to the type unification rules of p4c and my understanding, I see that p4c should not generate an error.   See

https://github.com/p4lang/p4c/blob/master/frontends/p4/typeChecking/typeUnification.cpp#L320

and the code segment under the line mentioned above.

**Comment by jafingerhut** [comment]
If that test program is considered a bug, then the one attached to this comment probably is, too.  It is nearly the same, except instead of performing assignments between structs/headers with different type names, but same field names and types, it passes them as run-time parameters of a control, or as a value returned from a function.  I do not know if this exercises different code paths in p4c than the test program attached to the original comment of this issue, or not, but perhaps it is worth adding this as a test program, too, or combining this one with the original above.

[assign-compatibility3.p4.txt](https://github.com/p4lang/p4c/files/4333474/assign-compatibility3.p4.txt)

**Comment by hesingh** [comment]
I see that @mbudiu-vmw marked this issue as a bug.  I am curious why the typeUnification.cpp code was written in the first place to allow assignment of a struct to a header or vice versa if the sizes of both are the same?
