### ISSUE TITLE
p4c-ubpf backend tests breaking CI regressions

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#2236]
I'm observing errors in Travis for my PR (https://github.com/p4lang/p4c/pull/2235) that seems unrelated to the changes I made (localized to the P4Info serialization code). Not every ubpf test is failing but all the failing tests are ubpf tests:

```
The following tests FAILED:
	448 - ubpf/testdata/p4_16_samples/ipv4-actions_ubpf.p4 (Failed)
	449 - ubpf/testdata/p4_16_samples/metadata_ubpf.p4 (Failed)
	452 - ubpf/testdata/p4_16_samples/csum_ubpf.p4 (Failed)
	453 - ubpf/testdata/p4_16_samples/simple-actions_ubpf.p4 (Failed)
	454 - ubpf/testdata/p4_16_samples/tunneling_ubpf.p4 (Failed)
Errors while running CTest
```

I am a bit confused because it seems other PRs have been merged since the p4c-ubpf backend was added to this repo, but maybe the branches for these PRs were behind master.

It also seems that the master branch is broken according to the README, which confirms that these failures are unrelated to my own PR.

For an example of a job that failed, see https://travis-ci.org/github/p4lang/p4c/builds/661379568

**Comment by jnfoster** [comment]
@osinstom can you take a look?

**Comment by osinstom** [comment]
Yep, I've already observed this issue in my other PR, but it's seems strange to me as no modifcations were applied to p4c-ubpf since that merge https://github.com/p4lang/p4c/commit/22cc431859078ee47b3ea7477a8f76dffcd6c37e with positive job result: https://travis-ci.org/github/p4lang/p4c/builds/658850623

**Comment by mbudiu-vmw** [comment]
All these errors look like "packet too short". Must be some application-level problem. The tests are producing wrong outputs.

**Comment by antoninbas** [comment]
We should consider disabling the tests temporarily if this takes a while to troubleshoot & fix.

**Comment by osinstom** [comment]
I've already resolved it. See #2237.
