### ISSUE TITLE
Empty type_info section of P4Info file, when it should be non-empty

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#2239]
The two attached example programs both cause the indicated version of p4c (which includes the fix in recent PR https://github.com/p4lang/p4c/pull/2235 ) to generate a P4Info file with an empty `type_info` section, when that section should contain the definition for at least one type `IPv4Addr_t` used as the type of a table key field, or an action parameter (different case for each test program).
```
$ p4c --version
p4c 1.2.0 (SHA: a1f21cb9)
```
[custom-type-table-key.p4.txt](https://github.com/p4lang/p4c/files/4327139/custom-type-table-key.p4.txt)
[custom-type-action-parameter.p4.txt](https://github.com/p4lang/p4c/files/4327140/custom-type-action-parameter.p4.txt)

**Comment by antoninbas** [comment]
Nice catch @jafingerhut. The serialization code currently doesn't update `type_info` when the user-defined type is only used for match fields / action parameters, since for these P4Info currently doesn't use `P4DataTypeSpec`. It should be a fairly easy fix for me though.
