### ISSUE TITLE
Implement use of @id annotation on action parameters, table match keys and packetio metadata

### ISSUE THREAD

**Issue by stefanheule** [p4lang/p4c#2242]
The P4RT working group has slightly expanded the use of the `@id` annotation beyond just the P4 objects (like tables, actions, etc), to the other entities in P4Info that get IDs, such that the programmer can also choose IDs for those.  The updated spec is here: https://github.com/p4lang/p4runtime/pull/272.

This is a feature request for the compiler to implement the change in the specification. Unlike for P4 Objects, there is no tag in the upper 8 bits for these, so it should be slightly simpler to implement (and in particular will not need the fix asked for in #2241).

**Comment by antoninbas** [comment]
Will implement this after the https://github.com/p4lang/p4runtime/pull/272 is merged.
