### ISSUE TITLE
@ignore_table_dependency Cause a ERROR Overlapping instructions

### ISSUE THREAD

**Issue by sisyphus1212** [p4lang/p4c#2244]
This error occurred when i add this annotation **@ignore_table_dependency("SwitchEgress.tunnel_decap.decap_inner_ip")** to the front of **table nexthop_rewrite**
How can I solve this problem?
![image](https://user-images.githubusercontent.com/45515761/76773118-e6bf8a80-67dc-11ea-9ef8-20714d4a8d93.png)
![image](https://user-images.githubusercontent.com/45515761/76774115-7b76b800-67de-11ea-9ec4-cc28f3f270b6.png)
![image](https://user-images.githubusercontent.com/45515761/76773226-1d95a080-67dd-11ea-9c6c-9987d09d213b.png)

**Comment by jnfoster** [comment]
This looks like an issue with the Barefoot compiler. 

You are likely violating your NDA / SELA by posting this on a public forum.

Please take it up with Barefoot customer engineering.
