### ISSUE TITLE
Predication pass leads to unsafe variable assignment

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2248]
I had a failing test for `issue512.p4` on the latest commit (0190f95422d219000a617ff46343e63a418e3186) and apparently the predication pass was changed. 

From `SimpleSwitchMidEnd_4_RemoveActionParameters` to `SimpleSwitchMidEnd_26_Predication` the transformation used to be:

```p4
    @name("cIngress.foo") action foo() {
        hasReturned = false;
        meta.b = meta.b + 4w5;
        if (meta.b > 4w10) {
            meta.b = meta.b ^ 4w5;
            hasReturned = true;
        }
        if (!hasReturned) {
            meta.b = meta.b + 4w5;
        }
    }
```
to 
```p4 
    @name("cIngress.foo") action foo() {
        hasReturned = false;
        meta.b = meta.b + 4w5;
        {
            bool cond;
            {
                bool pred;
                cond = meta.b > 4w10;
                pred = cond;
                {
                    meta.b = (pred ? meta.b ^ 4w5 : meta.b);
                    hasReturned = (pred ? true : hasReturned);
                }
            }
        }
        {
            bool cond_0;
            {
                bool pred_0;
                cond_0 = !hasReturned;
                pred_0 = cond_0;
                meta.b = (pred_0 ? meta.b + 4w5 : meta.b);
            }
        }
    }
```

Now it is:

```p4
    @name("cIngress.foo") action foo() {
        hasReturned = false;
        meta.b = meta.b + 4w5;
        if (meta.b > 4w10) {
            meta.b = meta.b ^ 4w5;
            hasReturned = true;
        }
        if (!hasReturned) {
            meta.b = meta.b + 4w5;
        }
    }
```

to

```p4
    @name("cIngress.foo") action foo() {
        hasReturned = false;
        meta.b = meta.b + 4w5;
        {
            meta.b = (meta.b > 4w10 ? meta.b ^ 4w5 : meta.b);
            hasReturned = (meta.b > 4w10 ? true : hasReturned);
        }
        {
            meta.b = (!hasReturned ? meta.b + 4w5 : meta.b);
        }
    }
```
which has a problem I think.
For certain inputs the line `hasReturned = (meta.b > 4w10 ? true : hasReturned);` will be evaluated incorrectly because the value of `meta.b` is overwritten in the previous line. One such input could be `10` for `meta.b`. 
I created an alternative version that is tested with stf.

[predication_assignment.txt](https://github.com/p4lang/p4c/files/4360007/predication_assignment.txt)

[predication_assignment.stf.txt](https://github.com/p4lang/p4c/files/4357318/predication_assignment.stf.txt)

**Comment by fruffy** [comment]
Another instance of this problem:
```p4 
bit<48> tmp_val_0;
bit<48> tmp;
action simple_action() {
    if (h.eth_hdr.eth_type != 16w0) {
        if (h.eth_hdr.src_addr != 48w0) {
            tmp = 48w1;
        } else {
            tmp = 48w2;
        }
        tmp_val_0 = tmp;
        h.eth_hdr.dst_addr = tmp_val_0;
    }
}
apply {
    simple_action();
}
```
is turned into 

```p4 
bit<48> tmp_val_0;
bit<48> tmp;
action simple_action() {
    tmp = (h.eth_hdr.eth_type != 16w0 ? (h.eth_hdr.src_addr != 48w0 ? 48w1 : 48w2) : tmp);
    h.eth_hdr.dst_addr = (h.eth_hdr.eth_type != 16w0 ? tmp_val_0 : h.eth_hdr.dst_addr);
}
apply {
    simple_action();
}
```

which effectively leaves `h.eth_hdr.dst_addr` unassigned.


[2248b.p4.txt](https://github.com/p4lang/p4c/files/4389607/2248b.p4.txt)
[2248b.stf.txt](https://github.com/p4lang/p4c/files/4389608/2248b.stf.txt)

**Comment by fruffy** [comment]
Also just adding an expression to the Mux statement leads to a compiler bug.

[2248c.p4.txt](https://github.com/p4lang/p4c/files/4389675/2248c.p4.txt)

**Comment by jafingerhut** [comment]
@fruffy I just wanted to give a big THANK YOU for all the work you have been doing to find subtle bugs in p4c, especially with attached P4 code and often STF files.  Really cool stuff there.

This may not be the most appropriate venue to ask, but I didn't know your email address, and wanted to ask if there is a link to any papers, documentation, and/or tools you are using to do this.  I completely understand if the answer is "still research work in progress, hopefully with published paper to appear in N months from now".

**Comment by hesingh** [comment]
I think this is the repo fruffy uses to find p4c bugs.

https://github.com/p4gauntlet/p4_tv

**Comment by fruffy** [comment]
Yes that is correct, the repository includes a fuzz tester and some tools to check equivalence of individual compiler passes. Still work in progress though. 
@jafingerhut I sent you an email!

**Comment by fruffy** [comment]
@matijasyrmia Have you seen this issue? I think it still happens even with the latest pull request.

**Comment by matijasyrmia** [comment]
@fruffy  Thank you for your time to document this issue. I will take look to localize the problem.

**Comment by matijasyrmia** [comment]
@fruffy check out this PR #2276 . I think that it solves this issue, because `h.eth_hdr.dst_addr` will not be uninitialized in any case. Also it will not skip `temp_val_0` assignment. 

If you need anything more from me please let me know.

**Comment by fruffy** [comment]
@matijasyrmia Thanks for looking into this so quickly! I just checked the bugs and 2248b.p4 is fixed. Unfortunately, 2248a (the example in the original post) and 2248c.p4 (the compiler bug) still occur.

**Comment by matijasyrmia** [comment]
@fruffy Can you pull new commits from #2276 ? 2248a and 2248c are fixed now.

**Comment by fruffy** [comment]
lgtm, all tests pass on my end.
