### ISSUE TITLE
Negative constant is translated in the overflow positive version

### ISSUE THREAD

**Issue by richiMarchi** [p4lang/p4c#2256]
Here's my piece of code:
```
new_ttl = hdr.ip.ttl - 1;
```
Both new_ttl and hdr.ip.ttl are bit<8> variables. When the translation occurs, the result I get is
```
new_ttl = hdr.ip.ttl + 255;
```
Am I doing something wrong or is it a bug?

**Comment by mbudiu-vmw** [comment]
Because of the rules of addition in two's complement the result will be the same.

**Comment by richiMarchi** [comment]
You're right, I stupidly didn't think about it. Thank you!
