### ISSUE TITLE
Cloned packet not keeping all header fields

### ISSUE THREAD

**Issue by drobinkent** [p4lang/p4c#2257]
I am writing a data plane program that clones a packet to the ingress port. But in the cloned version of the packet (standarad_metadata.instance_type ==1) all the header fields are not kept intact. What's the probable reason behind this? Can anyone kindly help?

I have attached the log here. Here the incoming packet  has ingress port 4 and egress_spec 1. So, I am cloning the packet. Hence there should be 2 version of the packet, one with egress port 4 and another with egress port 1. I get 2 versions of the packet. But, the packet with ingress port 4 and egress port 1 (this is the original packet) hass all the fields intact. But the cloned one ingress port 4 and egress port 4 is not keeping all the header fields.

Moreover there is a call to parser again after end of ingress. Should a cloned packet go to parser again? Here I am using I2E clone.  As far as my understandings, a packet cloned at ingress should have 2 copy of the packet to egress and it is not parsed again. But the call to parser is making me confused. Am I missing something?

> 
> [11:51:02.041] [bmv2] [D] [thread 19202] [134.0] [cxt 0] Looking up key:
> * standard_metadata.ingress_port                  : 0004
> * standard_metadata.egress_spec                   : 0001
> * standard_metadata.egress_port                   : 0000
> * standard_metadata.packet_length                 : 00000083
> * standard_metadata.enq_timestamp                 : 00000000
> * standard_metadata.enq_qdepth                    : 000000
> * standard_metadata.deq_timedelta                 : 00000000
> * standard_metadata.deq_qdepth                    : 000000
> * standard_metadata.ingress_global_timestamp      : 000002f28fe8
> * standard_metadata.egress_global_timestamp       : 000000000000
> * standard_metadata.mcast_grp                     : 0000
> * standard_metadata.egress_rid                    : 0000
> * standard_metadata.checksum_error                : 00
> * standard_metadata.instance_type                 : 00000000
> * standard_metadata.packet_length                 : 00000083
> * standard_metadata.priority                      : 00
> * local_metadata.l4_src_port                      : 0000
> * local_metadata.l4_dst_port                      : 0000
> * local_metadata.is_multicast                     : 00
> * hdr.flag_hdr.is_control_pkt_from_delay_proc     : 01
> * hdr.flag_hdr.is_control_pkt_from_ing_queue_rate : 00
> * hdr.flag_hdr.is_control_pkt_from_ing_queue_depth: 01
> * hdr.flag_hdr.is_control_pkt_from_egr_queue_depth: 00
> * hdr.flag_hdr.do_l3_l2                           : 01
> * hdr.flag_hdr.my_station_table_hit               : 01
> * hdr.flag_hdr.downstream_routing_table_hit       : 01
> * hdr.flag_hdr.is_pkt_toward_host                 : 01
> * hdr.mdn_int.next_hdr                            : 3a
> * hdr.mdn_int.src_enq_timestamp                   : 000002e88ad2
> * hdr.mdn_int.src_deq_timestamp                   : 000002e88ad2
> * hdr.delay_info_hdr.event_src_type               : 01
> * hdr.delay_info_hdr.path_delay_event_type        : 01
> * hdr.delay_info_hdr.path_delay_event_data        : 0000000a0516
> * hdr.egress_rate_event_hdr.egress_traffic_color  : 00000000
> * hdr.ipv6.next_hdr                               : fd
> 
> [11:51:02.041] [bmv2] [D] [thread 19202] [134.0] [cxt 0] Table 'IngressPipeImpl.ingress_end_debug.dbg_table': miss
> [11:51:02.041] [bmv2] [D] [thread 19202] [134.0] [cxt 0] Action entry is NoAction - 
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.0] [cxt 0] Looking up key:
> 
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.0] [cxt 0] Table 'tbl_leaf192': miss
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.0] [cxt 0] Action entry is leaf192 - 
> [11:51:02.042] [bmv2] [I] [thread 19202] hdr.mdn_int.next_hdr after checking for  ingress debug  = 58
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.0] [cxt 0] Pipeline 'ingress': end
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.0] [cxt 0] Cloning packet at ingress
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Parser 'parser': start
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Parser 'parser' entering state 'start'
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Parser state 'start': key is 0001
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Parser 'parser' entering state 'parse_ethernet'
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Extracting header 'ethernet'
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Parser state 'parse_ethernet': key is 86dd
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Parser 'parser' entering state 'parse_ipv6'
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Extracting header 'ipv6'
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Parser state 'parse_ipv6': key is fd
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Parser 'parser' entering state 'parse_mdn_int'
> [11:51:02.042] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Extracting header 'mdn_int'
> [11:51:02.043] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Parser state 'parse_mdn_int': key is 3a
> [11:51:02.043] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Parser 'parser' entering state 'parse_icmpv6'
> [11:51:02.043] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Extracting header 'icmpv6'
> [11:51:02.043] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Parser state 'parse_icmpv6': key is 81
> [11:51:02.043] [bmv2] [D] [thread 19202] [134.1] [cxt 0] Parser 'parser': end
> [11:51:02.043] [bmv2] [D] [thread 19202] [134.0] [cxt 0] Cloning packet to egress port 4
> [11:51:02.043] [bmv2] [D] [thread 19202] [134.0] [cxt 0] Egress port is 1
> [11:51:02.043] [bmv2] [D] [thread 19203] [134.1] [cxt 0] Pipeline 'egress': start
> [11:51:02.043] [bmv2] [D] [thread 19204] [134.0] [cxt 0] Pipeline 'egress': start
> [11:51:02.043] [bmv2] [D] [thread 19203] [134.1] [cxt 0] Looking up key:
> * standard_metadata.ingress_port                  : 0004
> * standard_metadata.egress_spec                   : 0000
> * standard_metadata.egress_port                   : 0004
> * standard_metadata.packet_length                 : 00000083
> * standard_metadata.enq_timestamp                 : 02f2ad65
> * standard_metadata.enq_qdepth                    : 000000
> * standard_metadata.deq_timedelta                 : 00000086
> * standard_metadata.deq_qdepth                    : 000000
> * standard_metadata.ingress_global_timestamp      : 000002f28fe8
> * standard_metadata.egress_global_timestamp       : 000002f2ade1
> * standard_metadata.mcast_grp                     : 0000
> * standard_metadata.egress_rid                    : 0000
> * standard_metadata.checksum_error                : 00
> * standard_metadata.instance_type                 : 00000001
> * standard_metadata.packet_length                 : 00000083
> * standard_metadata.priority                      : 00
> * local_metadata.l4_src_port                      : 0000
> * local_metadata.l4_dst_port                      : 0000
> * local_metadata.is_multicast                     : 00
> * hdr.flag_hdr.is_control_pkt_from_delay_proc     : 00
> * hdr.flag_hdr.is_control_pkt_from_ing_queue_rate : 00
> * hdr.flag_hdr.is_control_pkt_from_ing_queue_depth: 00
> * hdr.flag_hdr.is_control_pkt_from_egr_queue_depth: 00
> * hdr.flag_hdr.do_l3_l2                           : 00
> * hdr.flag_hdr.my_station_table_hit               : 00
> * hdr.flag_hdr.downstream_routing_table_hit       : 00
> * hdr.flag_hdr.is_pkt_toward_host                 : 00
> * hdr.mdn_int.next_hdr                            : 3a
> * hdr.mdn_int.src_enq_timestamp                   : 000002e88ad2
> * hdr.mdn_int.src_deq_timestamp                   : 000002e88ad2
> * hdr.delay_info_hdr.event_src_type               : 00
> * hdr.delay_info_hdr.path_delay_event_type        : 00
> * hdr.delay_info_hdr.path_delay_event_data        : 000000000000
> * hdr.egress_rate_event_hdr.egress_traffic_color  : 00000000
> * hdr.ipv6.next_hdr                               : fd
> 
> [11:51:02.044] [bmv2] [D] [thread 19204] [134.0] [cxt 0] Looking up key:
> * standard_metadata.ingress_port                  : 0004
> * standard_metadata.egress_spec                   : 0000
> * standard_metadata.egress_port                   : 0001
> * standard_metadata.packet_length                 : 000000b3
> * standard_metadata.enq_timestamp                 : 02f2adc1
> * standard_metadata.enq_qdepth                    : 000000
> * standard_metadata.deq_timedelta                 : 00000083
> * standard_metadata.deq_qdepth                    : 000000
> * standard_metadata.ingress_global_timestamp      : 000002f28fe8
> * standard_metadata.egress_global_timestamp       : 000002f2ae3a
> * standard_metadata.mcast_grp                     : 0000
> * standard_metadata.egress_rid                    : 0000
> * standard_metadata.checksum_error                : 00
> * standard_metadata.instance_type                 : 00000000
> * standard_metadata.packet_length                 : 000000b3
> * standard_metadata.priority                      : 00
> * local_metadata.l4_src_port                      : 0000
> * local_metadata.l4_dst_port                      : 0000
> * local_metadata.is_multicast                     : 00
> * hdr.flag_hdr.is_control_pkt_from_delay_proc     : 01
> * hdr.flag_hdr.is_control_pkt_from_ing_queue_rate : 00
> * hdr.flag_hdr.is_control_pkt_from_ing_queue_depth: 01
> * hdr.flag_hdr.is_control_pkt_from_egr_queue_depth: 00
> * hdr.flag_hdr.do_l3_l2                           : 01
> * hdr.flag_hdr.my_station_table_hit               : 01
> * hdr.flag_hdr.downstream_routing_table_hit       : 01
> * hdr.flag_hdr.is_pkt_toward_host                 : 01
> * hdr.mdn_int.next_hdr                            : 3a
> * hdr.mdn_int.src_enq_timestamp                   : 000002e88ad2
> * hdr.mdn_int.src_deq_timestamp                   : 000002e88ad2
> * hdr.delay_info_hdr.event_src_type               : 01
> * hdr.delay_info_hdr.path_delay_event_type        : 01
> * hdr.delay_info_hdr.path_delay_event_data        : 0000000a0516
> * hdr.egress_rate_event_hdr.egress_traffic_color  : 00000000
> * hdr.ipv6.next_hdr                               : fd
> 
> [11:51:02.044] [bmv2] [D] [thread 19203] [134.1] [cxt 0] Table 'EgressPipe

**Comment by jafingerhut** [comment]
This is the way the simple_switch program was written.

There are switch ASICs where it is the desired behavior that packets cloned on ingress are copies of the packet _as they began ingress processing_, not _as they were at the end of ingress processing_, e.g. because you want to implement a feature that makes copies of packets as they arrived to the switch on an input port, and send them to some monitoring system.

The BMv2 simple_switch process does this in a slightly odd way, perhaps, by reparsing cloned packets.  I believe it does this so that in the common case (for most P4 programs, which do not do ingress clone operations, or at least not on every packet), no copy needs to be made of the parse results before the packet begins ingress processing.

**Comment by drobinkent** [comment]
The problem is, I am passing a list of fields in the clone3 function. But those fields are not having the updated value in the cloned version. Is there any work around for this?  Even the packet length is also changed. Is there any workaround for this?

**Comment by jafingerhut** [comment]
There are two possible reasons that I know of why this can happen:

+ some fields of standard_metadata are overwritten at the beginning of ingress and egress processing by the simple_switch process, even if you request that they be preserved.  Those fields _cannot_ be preserved, and there is no warning or error from the compiler if you attempt to do so.  I do not have a complete list of these to give you, but you can discover at least some of them from looking at the functions ingress_thread and egress_thread in the source file targets/simple_switch/simple_switch.cpp of the p4lang/behavioral-model repository, e.g. these lines show that the field `parser_error` is overwritten just before a packet begins executing the ingress control P4 code: https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.cpp#L500-L503

+ This section of the simple_switch docs: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md#restrictions-on-recirculate-resubmit-and-clone-operations and the one immediately after that describe the issue that sometimes when you explicitly request packet metadata to be preserved for a recirculate, resubmit, or clone operation, sometimes that will not work correctly given the current v1model implementation, and that will likely never be fixed.  If/when the PSA architecture implementation is complete, it uses mechanisms for preserving metadata that are different than v1model that should work reliably in the P4_16 language.

**Comment by drobinkent** [comment]
My problem is not with the metadata. Assume the scenario

Packet {
header1;
header2;
header3;
}

In an incoming packet, header3 may not exists, only header1 and 2 exists. In the ingress pipeline I am adding header3. Then I am cloning the whole packet . So I was expecting that, header1,2,3 will  be copied and they will be available in the packet header in egress pipeline. But, as after the ingress when the packet is cloned it is again sent to parser. Now the parser is not filling the header3. So, I am not getting any valid value for header3 in egress. 

Is my assumption wrong or I am expecting anything fundamentally wrong?

**Comment by jafingerhut** [comment]
It is fundamentally wrong.  The issue isn't that it is going through the parser again.

I believe the issue is that you are thinking "whatever the packet looks like at the _end_ of ingress, after my P4 code has finished ingress processing, that is what the state of the cloned packet should look like".

But it is not.  By design, it is closer to "whatever the packet looked like _just before_ ingress processing began, when an ingress clone operation is performed, that is what the cloned packet will look like when it starts egress processing".

Why?  The main motivating reason is the one I mentioned earlier: there are features like "SPAN" (Switch Port ANalyzer), and similar monitoring features in other switches, where for some packets received by a switch, you want to make a copy of them as received by that switch, with as few modifications as possible, and copied to some monitoring system.

**Comment by drobinkent** [comment]
Got the point. 

Another question: as far as my understandings for writing some complex stateful algorithms it is necessary to add extra headers in the ingress stage and use them in egress. Is there any way to achieve that?

**Comment by jafingerhut** [comment]
You could consider the following alternative: send the packet from ingress to egress with the extra headers, but without cloning during ingress processing.

During egress processing, clone the packet.  Packets cloned during egress processing keep all metadata and headers as they are at the end of egress processing, as mentioned in the docs I linked above.

**Comment by drobinkent** [comment]
Thanks.
