### ISSUE TITLE
"Compiler Bug Null stat" also triggered in action properties

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2266]
PR https://github.com/p4lang/p4c/pull/2259 does not catch function calls in action arguments. Are there any other table properties where this could occur?

[2258b.p4.txt](https://github.com/p4lang/p4c/files/4384221/2258b.p4.txt)

**Comment by boblytton** [comment]
Should you be allowed a function call in a binary op?
```
bit<16> f1() {
    return 1;
}
bit<16> f2(in bit<16> val) {
    return f1() +val;  // **Need to out of line the call**
}
control Widget(...) {
    apply {
        thingy = f2(f1()); // **Need to out of line argument creation**
    }
}
```

**Comment by jafingerhut** [comment]
@boblytton I believe this has been allowed by the language specification for quite some time now.  Section 8.1 "Expression evaluation order" specifies the order of evaluation, in case sub-expressions of an expression can have side effects.  Do you see anything in that section that is missing, or ambiguous in some way?

**Comment by boblytton** [comment]
Hi @jafingerhut, sorry I should have been more specific, the front-end hits BUG_CHECK() in the example above.

**Comment by jafingerhut** [comment]
@boblytton I tried a couple of variations of the code you described with the latest master version of p4c as of now (2020-Apr-30), but did not experience any Compiler Bug messages or errors of any kind.  If you can reproduce a BUG_CHECK() call, can you create a separate p4c issue with the exact program, command line, and output of `p4c --version` that you used?

**Comment by boblytton** [comment]
@jafingerhut, I am still trying to track down where my issue is arising from, but as you say the latest p4c does not exhibit them - sorry for being too hasty.

**Comment by boblytton** [comment]
The root of the problem was disabling 'frontend side-effect ordering'. Cheers.

**Comment by mbudiu-vmw** [comment]
A spec change could be the solution, outlawing such programs.
https://github.com/p4lang/p4-spec/pull/852
