### ISSUE TITLE
Fixing add_cpplint_files() statement causes lint errors

### ISSUE THREAD

**Issue by boblytton** [p4lang/p4c#2270]
Please see pull request:
    Replace $$() with ${} in CMakeList.txt #2269
This triggers a slew or lnit errors, as list in #2269 and Travis CI.

The errors need to be fixed first, and then the braces fixed in the CMakelist.txt file.

**Comment by boblytton** [comment]
@mbudiu-vmw  @osinstom
I can't see Tomek on the assignee list.

**Comment by mbudiu-vmw** [comment]
That's alright, he will receive the ping from the mention and probably will fix it. If not, I can do it.

**Comment by osinstom** [comment]
Sorry for late response. I've noticed that and I'll try to fix it ASAP.
