### ISSUE TITLE
Bazel build files?

### ISSUE THREAD

**Issue by stefanheule** [p4lang/p4c#2271]
It would be useful to have Bazel build files for p4c, like other p4lang projects already do (e.g. p4runtime). If I go ahead and write them, could we add them to this repository?

**Comment by mbudiu-vmw** [comment]
If you commit to maintain them, certainly.
The build system is quite complicated, though, you should expect this will be a non-trivial effort.
If there is a tool to convert cmake to bazel you may save some time.

**Comment by cc10512** [comment]
@stefanheule how do you plan to test the Bazel builds?

**Comment by stefanheule** [comment]
Just invoking them would be enough, I imagine? Or is there anything else that you would want to test?

**Comment by jafingerhut** [comment]
Using the existing cmake-based build, a good check that things went well (or at least most of it went well), is to do "cd build ; make check".   If a Bazel-based build also enabled something similar, that would be a fairly thorough way to check the build results.

I do not know that people would want to immediately enable the Travis/CI to automatically do Bazel-based builds and use them as additional prerequisites for merging PRs, but I suppose it is a possibility if the extra compute resources are not an issue (they could be done in parallel to avoid extra latency).

**Comment by cc10512** [comment]
Yes, but they need to be invoked any time someone changes any of the cmake files. Since we do not have such smarts, the next best thing is to have a bazel build run as part of Travis. That support is not there yet. I suppose it should not be too hard to add, but it does imply adding another row to the build matrix.

**Comment by mbudiu-vmw** [comment]
Travis seems less and less reliable; doubling the build time in CI is not really a great option. But I agree that one would have to run the bazel builds periodically to make sure they don't break.

**Comment by hesingh** [comment]
I don't consider p4runtime as any yardstick to borrow from for p4c.  p4runtime is essentially worked by one person in Antonin while p4c, in comparison, has an army. 

Second, if one sees this comparison between bazel and cmake, I am underwhelmed by bazel.  

https://tinyurl.com/ybq89q88

**Comment by stefanheule** [comment]
Nobody is suggesting to replace cmake, only to offer bazel in addition to cmake. If you prefer cmake, you can continue to use cmake.

**Comment by hesingh** [comment]
@stefanheule I see, thanks.

So, by default, does Travis run Bazel or cmake to test a PR code changes to p4c?
Which one of Bazel or make (after cmake) runs faster?

What is the biggest advantage to also add Bazel to p4c build?

**Comment by stefanheule** [comment]
It would build with both, in parallel. I don't know from the top of my head which one is faster.

The advantage is that not everyone wants to use cmake, and this enables the people who use bazel to use p4c.

**Comment by stefanheule** [comment]
Closing this, as we have added Bazel build files now.
