### ISSUE TITLE
Support P4RT string translation

### ISSUE THREAD

**Issue by konne88** [p4lang/p4c#2283]
Add support for strings in the `@p4runtime_translation` annotation as described in:
https://github.com/p4lang/p4runtime/pull/274
https://github.com/p4lang/p4runtime/issues/270

**Comment by smolkaj** [comment]
@antoninbas: Do you mind if I take a crack at this? We're interested in getting support for this right away and I figured you probably wouldn't mind if I took this off your plate?

**Comment by antoninbas** [comment]
Don't mind at all :) Hopefully you can find an elegant way to do it.
