### ISSUE TITLE
BMV2 Backend Compiler Bug unhandled case

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2291]
This strange sequence of function calls seems to lead to a compiler bug in `expression.cpp `the bmv2 backend. 
[function_inlining_alt.p4.txt](https://github.com/p4lang/p4c/files/4437680/function_inlining_alt.p4.txt)

**Comment by mbudiu-vmw** [comment]
The inliner leaves some functions not inlined, so the back-end is justifiably upset.
