### ISSUE TITLE
move away from the custom python2-only cpplint fork

### ISSUE THREAD

**Issue by flokli** [p4lang/p4c#2293]
p4c currently uses a custom, python2 only fork of cpplint, which has gotten quite some p4-specific quirks over the course of time.

It's unclear if the version in the initial commit to this repo was a public cpplint release (so changes should be visible in the git history) or already deviated from upstream before the initial commit.

With Python 2 being EOL, this should be moved to Python 3. Maybe it'd also be a better path forward to move to a well-maintained and standard linter (like clang-format) with  set of custom, p4c-specific rules.

**Comment by mbudiu-vmw** [comment]
@ChrisDodd created our linter by modifying the official google one.

**Comment by mbudiu-vmw** [comment]
Fixed by #2703
