### ISSUE TITLE
[bmv2] "Could not find declaration for cond"

### ISSUE THREAD

**Issue by vikramnathan** [p4lang/p4c#230]
I have the following P4-16 program:
[test_bug.p4.txt](https://github.com/p4lang/p4c/files/703371/test_bug.p4.txt)

This gives the following error when compiled with -vvv:
```
<omitted>
MidEnd_21_Predication
error: Could not find declaration for cond
error: Could not find declaration for cond
error: Could not find declaration for cond
error: Could not find declaration for cond
error: Could not find declaration for cond
```
Note: there is no variable `cond` in my program. My guess is that this is something in the IR.

However, if I do any of the following, the program compiles:
1.  line 76 is changed from:
`
iszero = (key.field1 == 0) ? true : false; 
`
to
`
iszero = (key.field1 == 0);
`
the program compiles.
2. Remove line 83 (the repeated `keyIsZero(key, done)`)
3. The apply body is replaced with the contents of `testKey`

Why is the attached program rejected? Is there something about the limitations of actions in the spec that I'm missing? Either way, the compiler should print out a more helpful error.

**Comment by vikramnathan** [comment]
Apologies for closing and reopening. This is still a bug.

**Comment by mbudiu-vmw** [comment]
I cannot reproduce this bug with the most recent version of the compiler.
The program compiles just fine for me.

**Comment by vikramnathan** [comment]
You're correct - it does compile. My bad.
