### ISSUE TITLE
Mismatch with specification for integer literals.

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#2301]
The p4c lexer supports writing decimal integer literals with a leading `0d`, by analogy to `0b`, `0o`, and `0x` for binary, octal, and hex respectively.
 https://github.com/p4lang/p4c/blob/master/frontends/parsers/p4/p4lexer.ll#L183

However, this syntax is not actually a part of the language specification:

https://p4.org/p4-spec/docs/P4-16-v1.2.0.html#sec-integer-literals

Perhaps there are situations where it's useful (though, why not just omit the `0d`?) but it does seem bad to have spurious differences in the implementation. Should we either: remove this or add it to the specification?

**Comment by jnfoster** [comment]
H/T @liujed-intel for pointing this out.

**Comment by mbudiu-vmw** [comment]
we should fix the spec.

**Comment by jnfoster** [comment]
Made a PR (above).
