### ISSUE TITLE
p4c-bm2-ss erroneously permits multiple LPM keys in some cases

### ISSUE THREAD

**Issue by robertmacdavid** [p4lang/p4c#2307]
Multiple LPM keys are accepted when combined with a ternary key, although the bmv2 switch will reject the pipeline json. For example, this set of keys is accepted by the compiler:
```
key = {
            hdr.ipv4.version : ternary;
            hdr.ipv4.srcAddr: lpm;
            hdr.ipv4.dstAddr: lpm;
        }
```
Whereas this one is not:
```
key = {
            hdr.ipv4.srcAddr: lpm;
            hdr.ipv4.dstAddr: lpm;
        }
```
Issue can be reproduced by modifying the ipv4_lpm table of https://github.com/p4lang/tutorials/blob/master/exercises/basic/basic.p4 and using the latest version of this p4c docker image https://hub.docker.com/r/opennetworking/p4c)

**Comment by jafingerhut** [comment]
It seems to me like a reasonable minor enhancement for at least the v1model architecture back end to reject such programs with an error.  Likely most back ends would reject it, unless some architecture actually chose to define such a table to have useful behavior (I cannot currently imagine what that useful behavior might be).

**Comment by jnfoster** [comment]
I believe the bug is here: https://github.com/p4lang/p4c/blob/master/backends/bmv2/common/control.cpp#L355

**Comment by jafingerhut** [comment]
I would like to retract part of my previous comment.  I _can_ imagine a useful behavior for tables with multiple lpm fields, if they also have at least one ternary or range field.  This is documented here: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md#range-tables

as well as the restriction that bmv2 simple_switch made a design decision not to support such tables.  bmv2 simple_switch could reasonably be generalized in this respect, I believe, but it doesn't seem like a burning desire to support such tables.

Given that bmv2 simple_switch doesn't, I see no problem if the p4c bmv2 back end catches it a few seconds earlier, but today it is caught as soon as you try to load the bmv2 son file into simple_switch.

**Comment by hesingh** [comment]
Memory organization on switch hardware, typically, uses TCAM (ternary match_kind in P4) for fast lookup and  slower SRAM for lpm.   Thus, if a P4 table mixes match_kind, the p4c backend gets interesting looking up one keyElement in TCAM and another in SRAM. 

For bmv2, or any switching asic,  I agree,, one should support all keyElements as lpm.

**Comment by mbudiu-vmw** [comment]
So is this still an issue or not?
It yes, what is the right solution?

**Comment by jafingerhut** [comment]
The behavior as described in the original issue does exist: The p4c v1model back end can generate a BMv2 JSON file that simple_switch rejects, for the good reason that simple_switch does not support multiple lpm fields in the same table key.

Without any changes, a P4 developer will find out that there is a problem as soon as they try to run simple_switch with the BMv2 JSON file as input.  The error message from simple_switch is, in my perhaps-skewed opinion, reasonably clear as to why it happens.

Would it be nicer for the P4 developer if p4c gave an error message, and did not generate a BMv2 JSON file?  Yes, a little bit.

**Comment by hesingh** [comment]
Potential fix to p4c bmv2 backend is in this PR:

https://github.com/p4lang/p4c/pull/2440
