### ISSUE TITLE
Update the repository description

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#2312]
If we consider that p4c is sufficiently mature, maybe we should update this repo's description from "P4_16 prototype compiler" to "P4_16 reference compiler". @jnfoster @mbudiu-vmw

**Comment by jafingerhut** [comment]
That would certainly be consistent with this 2019-Nov change to the early part of p4c's README: https://github.com/p4lang/p4c/commit/1cbcd6a9d4159afe1f685f1ad54ca203d6f31d3c

I do not know who has permission to change the repository description, but it appears that I am not one of them.

**Comment by jnfoster** [comment]
I appear to have this authority. Fixed.
