### ISSUE TITLE
[bmv2] Could not find type for <Mux>

### ISSUE THREAD

**Issue by vikramnathan** [p4lang/p4c#232]
Note: I think this is a different bug than #216 since no bit slices are used here.

The following program: 
[test_bug2.p4.txt](https://github.com/p4lang/p4c/files/706219/test_bug2.p4.txt)

gives me this error:
```
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  COMPILER BUG: ../frontends/p4/typeMap.cpp:82
Could not find type for <Mux>(90708)

Aborted (core dumped)
```
What does this error mean? Is it a compiler bug or program issue?

Some notes:
1. Removing the conditional on line 98 (but keeping the body) seems to compile.
2. If line 97 is replaced with `bool ok = same;`, the code gives an Unexpected JSON error, likely the same as #231 .
3. If the Key instances are replaced with primitive types (e.g., bit<8>), the code compiles.

**Comment by mbudiu-vmw** [comment]
If you see COMPILER BUG it means this is a bug. You should not expect a very good error message from a compiler bug - something we didn't expect has happened.

**Comment by vikramnathan** [comment]
seems to be fixed.
