### ISSUE TITLE
Going up to the application layer

### ISSUE THREAD

**Issue by sanaa50** [p4lang/p4c#2322]
Let say I want insert a code within the data, such that the first few bytes of the data represent that code. My switches should do Action1 if the code exists, and Action2 if not.
My question is how to make a P4 switch read this code?

I know it may sound a simple question, but I couldn't figure out how to make things work. 

Note: I'm really new to P4.

Any help is appreciated.

**Comment by jafingerhut** [comment]
The calculator example program in the p4lang/tutorials repository demonstrates doing something like this.  Basically there is a custom header format defined with one field that is an "op code", short for operation code, and the P4 program has an if/then/else-if statement that checks one of 5 to 10 different op code values, and does a different arithmetic operation on operand fields in the custom header, writing the result back to the custom header, depending upon the numeric value of the op code.

That is part of what a general purpose CPU does to decode and execute one machine code instruction.

**Comment by jafingerhut** [comment]
A general rule in computer science: data can be interpreted as code, if you write an appropriate interpreter for that code.

**Comment by jafingerhut** [comment]
Sorry, I intended to include a link to the calculator example program I mentioned, but forgot: https://github.com/p4lang/tutorials/tree/master/exercises/calc

**Comment by mbudiu-vmw** [comment]
Note that your programs cannot really have loops and they will probably be limited to a very small depth on most real hardware devices.

**Comment by mbudiu-vmw** [comment]
You could emulate loops too, but the number of steps executed will need to be bounded.
