### ISSUE TITLE
Parser Key

### ISSUE THREAD

**Issue by sanaa50** [p4lang/p4c#2325]
My network consists of one switch and three host (h1, h2 and h3). h3 acts as a TCP server and h2 as a UDP server. h1 is my host which send request to the server.
Running a simple UDP client-server model works great but trying a TCP client server gives this:
`Parser state 'start': key is 86dd` 
In fact, I'm not using IPv6  (86dd). Consequently, h1 receive no reply from h3.

Any idea ?

**Comment by jnfoster** [comment]
This is almost certainly your host networking stack sending IPv6 packets.  Try disabling IPv6 and see if it persists?

**Comment by hesingh** [comment]
@sanaa50 Is your network using mininet nodes or you have a physical switch and hosts?

Anyway, by default, IPv6 may be enabled, and even if you haven't configured a global IPv6 address on host, the host is sending out packets using the host's link-local address.  Just use `tcpdump`, capture packets, and see what the packets are.  I suspect the interface on the host is doing Duplicate Address Detection (DAD) for its IPv6 link-local address.

**Comment by sanaa50** [comment]
After disabling IPv6, there are no more sending and receiving packets.
`tcpdump`  shows there are actually IPv6 packets.
Now, what can I do to overcome the problem?

**Comment by hesingh** [comment]
For TCP client-server, I suppose, you want to send IPv4 packets.  But when you disable IPv6, ipv4 packet flow in/out of the host does not happen?

Is linux the OS running on the host or is the host a mininet host?  Depending on the answer, I could try to suggest other debugging.

**Comment by sanaa50** [comment]
> For TCP client-server, I suppose, you want to send IPv4 packets. But when you disable IPv6, ipv4 packet flow in/out of the host does not happen?

Yes. No ipv4 packsts flow.


> Is linux the OS running on the host or is the host a mininet host? Depending on the answer, I could try to suggest other debugging.

I'm using mininet to emulate my network.

**Comment by hesingh** [comment]
Got it.  Let me take a look at mininet host behavior docs.  I am not a mininet expert.

**Comment by hesingh** [comment]
Use pingall on mininet switch and see which hosts ping.  See if you can check for dropped packets on the switch.

**Comment by sanaa50** [comment]
pingall works just fine.

**Comment by hesingh** [comment]
Maybe, you can take this discussion to the P4 Slack channel so that we don't send debugging issues to 300-400 users.  

In general, if packets are not heading out, use tcpdump on the sender to see what packets, if any, are sent out.   If the packet made it out the host, debug the next node in the path.  It should be the switch.  Did the switch drop the packet?  If not, check the receiver host with tcpdump.
