### ISSUE TITLE
Server response encapsualted with IPv6

### ISSUE THREAD

**Issue by sanaa50** [p4lang/p4c#2327]
I posted an issue two days ago about getting the Ethernet type =0x86dd . But it makes sense to me to post a new issue after making a complete new project and tests.
So, I have two client-server model, one for TCP and the other is for UDP. I tested these two models with mininet using `sudo mn` , and they worked just fine. After that, I tried to run the models in a simple mininet network of two hosts and one P4 switch. The packets of the client request are being received by the server, but (by reading the switch log) the response of the server is encapsulated with IPv6, which can't be possible since the client uses IPv4.
I double checked my P4 code and switch runtime json file. I can't see any problem.

I really need help.

Note: Sorry for my poor English.

**Comment by mbudiu-vmw** [comment]
This isn't really the right forum for such questions; this is the repository of the p4 compiler.
For such questions I would recommend either the tutorials repository or one of the P4 mailing lists.

**Comment by sanaa50** [comment]
> This isn't really the right forum for such questions; this is the repository of the p4 compiler.
> For such questions I would recommend either the tutorials repository or one of the P4 mailing lists.

I'm sorry. I'm going to close this issue and post a copy in the tutorials repository.
