### ISSUE TITLE
Member Operator Precedence

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2329]
I was looking into why #2303 was still failing for me and I saw that the precedence of the `Member` class is Prefix, because it inherits from `Operation_Unary`:
https://github.com/p4lang/p4c/blob/master/ir/expression.def#L274

According to cpp operator precedence, "." should be postfix, right? Is this intentional? I think because of this StructExpressions may not be correctly parenthesised.

**Comment by mbudiu-vmw** [comment]
@ChrisDodd

**Comment by ChrisDodd** [comment]
Yes, Member should have Prec_Postfix, as it is a postfix `.`.

**Comment by mbudiu-vmw** [comment]
Fixed by #2018
