### ISSUE TITLE
Untyped constant folding not sound

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#2332]
The compiler front-end does several transformations on the input program prior to type checking. One of these is constant folding, which appears to be transforming the following program, which is not well-typed,
```
const bit<32> x = 1w1;
```
into this program, which is:
```
const bit<32> x = 32w1;
```

(H/T @hackedy for finding this bug.)

**Comment by hackedy** [comment]
Another example of what looks like the same bug. If you remove the const qualifiers, p4c rejects this program, but it accepts it as written.
```
void f() {
    const int<8> x8 = 8s1;
    // RHS of shift cannot be signed.
    const int<8> shift8 = x8 << x8;
}
```
