### ISSUE TITLE
Compiler Bug message with program defining variable with type int

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#2335]
With the version of p4c source code indicated below, the attached program causes a Compiler Bug to occur.  I believe the program should be illegal, since it attempts to define a variable with type `int`, which I think is considered illegal in the language spec (values of type `int` should all be compile-time known values).

```
$ p4c --version
p4c 1.2.0 (SHA: b1374a14)

$ p4c type-int-variable.p4 
In file: /home/andy/p4c/frontends/p4/typeChecking/typeChecker.cpp:2009
Compiler Bug: /home/andy/p4c/frontends/p4/typeChecking/typeChecker.cpp:2009: Null cst
```

Discovered by @hackedy and reported in this comment on another issue, but seemed worth creating its own issue to track separately from that one: https://github.com/p4lang/p4c/issues/2334#issuecomment-618437733

[type-int-variable.p4.txt](https://github.com/p4lang/p4c/files/4524081/type-int-variable.p4.txt)

**Comment by fruffy** [comment]
So is the implication here that declaring values of type `int` is only possible when prefixing with the `const` qualifier?

**Comment by jafingerhut** [comment]
I believe that there is at least one other desired use case, which is allowing a type `int` constructor parameter to anything that has a constructor parameter, which is only a control or parser, if I remember correctly.

All desired use cases should be restricted to compile-time known values.  I had not thought of declaring a `const`-qualified entity with type `int` until you asked about it.

**Comment by fruffy** [comment]
I was just thinking of section `7.1.6.5` in the spec, where there were a couple of examples. it might be interesting to see what happens when I fuzz test this a bit. 

Regarding constructor parameters, do you mean something like this?
```p4
control c(inout bit<8> val)(int a) {
    apply {
       val = (bit<8>) a;
    }
}

control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    c(0) x;
    apply {
        x.apply(h.h.a);
    }
}
```
This actually also causes a compiler bug: 

```bash
In file: /mnt/windows/Projekte/p4_tv/p4c/frontends/p4/typeChecking/typeChecker.cpp:168      
Compiler Bug: out.p4(40): Could not find type of @name("x") c x_0/x(0)                      
    c(0) x; 
```

`InfInt` is a treasure trove of bugs.

**Comment by hesingh** [comment]
Just to give an idea of issues with `InfInt`, the last time large changes were made for it were during sizeof development for p4c.  See 

https://github.com/p4lang/p4c/commit/e5f68627d710514b3a0c3263c60e3447345ceda4#diff-ac7ed0f3ecd1057692c467bd565056ab

With current issues, the typeChecker would need more changes.

**Comment by mbudiu-vmw** [comment]
@fruffy : please post a complete example.

**Comment by fruffy** [comment]
The complete program should be in #2336 unless you are referring to another issue.
