### ISSUE TITLE
Compiler Bug: Could not find type of @name

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2336]
Since we are on a roll regarding integer bugs, here is another instance that causes a compiler bug.
Emerged from the discussion in #2335.

[control_call_with_int.p4.txt](https://github.com/p4lang/p4c/files/4528688/control_call_with_int.p4.txt)

**Comment by mbudiu-vmw** [comment]
Fixed by #2337

**Comment by fruffy** [comment]
Looks like this one is fixed.
