### ISSUE TITLE
Question: Add pna.p4 to p4c/p4include/ for NIC

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#2376]
I have started a pna.p4 include file for NIC at this repo:

https://github.com/hesingh/PNA/blob/master/pna.p4

The file leverages psa.p4 and any new P4 programs for NIC use pna.p4 and p4c-bm2-psa.

I would like to check in the file to p4c.

**Comment by jnfoster** [comment]
Let's discuss the processes by which we want to accommodate new architectures at June LDWG.

**Comment by hesingh** [comment]
One extern in pna.p4 is a Timer.  Several folks in the community have asked for a Timer in P4.  There was a paper from Stanford at the 2019 P4 Stanford Workshop related to event-driven processing.  Also, many switches in the data center use BFD (RFC 5880), for keepalive, which uses a timer.   Once the API for the Timer extern is final, we could add the extern to psa.p4.

Another goal of adding pna.p4 to p4c is to have a strawman header for use for concurrent prototyping as a PNA (Portable NIC Architecture) gets hashed out.  As the PNA spec evolves, so does pna.p4. 

Thanks.
