### ISSUE TITLE
Mysterious p4runtime backend behavior

### ISSUE THREAD

**Issue by smolkaj** [p4lang/p4c#2379]
While trying to write unit tests for #2365,  I came across some mysterious behavior of the gunit test `test/gtest/p4runtime.cpp` that you can observe in #2378 (look at the CI logs). I would be most grateful if someone more familiar with p4c and the testing setup could help me understand what's going on here.

## Source diff
I modified `p4RuntimeSerializer.cpp` so as to make the annotation `@p4runtime_translation` take zero instead of two arguments:
```diff
--- a/control-plane/p4RuntimeSerializer.cpp
+++ b/control-plane/p4RuntimeSerializer.cpp
@@ -790,8 +790,7 @@ class ParseAnnotations : public P4::ParseAnnotations {
         // annotation is for them).
         PARSE("max_group_size", Constant),
         // @p4runtime_translation has two args
-        PARSE_PAIR("p4runtime_translation",
-                   Expression),
+        PARSE_EMPTY("p4runtime_translation"),
     }) { }
 };
```

## Expected behavior
The test `NewType` in `test/gtest/p4runtime.cpp` should now fail; here is the relevant excerpt from the test:
```C++
TEST_F(P4RuntimeDataTypeSpec, NewType) {
    std::string program = P4_SOURCE(R"(
        type bit<8> my_type_t;
        @p4runtime_translation("p4.org/myArch/v1/Type2", 32)
        type bit<8> my_type2_t;
        struct my_struct { my_type_t f; my_type2_t f2; }
        extern my_extern_t<T> { my_extern_t(bit<32> v); }
        my_extern_t<my_struct>(32w1024) my_extern;
    )");
    auto pgm = getProgram(program);
    ASSERT_TRUE(pgm != nullptr && ::errorCount() == 0);
    // omitting the rest of the test
}
```

## Actual behavior
The test passes (see #2378, in particular https://travis-ci.com/github/p4lang/p4c/jobs/334307433#L4320).

**Comment by antoninbas** [comment]
This test invokes `P4::ControlPlaneAPI::TypeSpecConverter::convert` directly, i.e. the P4 program does not go through the entire p4RuntimeSerializer code and your code has no effect on this test case.

You need to look at the test fixture class. You'll see exactly what happens to the P4 program: it gets parsed, then goes through a few passes. It does not go through the regular frontend passes & the p4RuntimeSerializer passes. So you need to edit this [line](https://github.com/p4lang/p4c/blob/master/test/gtest/p4runtime.cpp#L1646) to match your changes to p4RuntimeSerializer.cpp:
```
class P4RuntimeDataTypeSpec : public P4Runtime {
 protected:
    const IR::P4Program* getProgram(const std::string& programStr) {
        auto pgm = P4::parseP4String(programStr, CompilerOptions::FrontendVersion::P4_16);
        if (pgm == nullptr) return nullptr;
        PassManager  passes({
            new P4::ParseAnnotations("P4RuntimeDataTypeSpecTest", false, {
                // @p4runtime_translation has two args
                PARSE_PAIR("p4runtime_translation", Expression), // HERE!
            }),
            new P4::ResolveReferences(&refMap),
            new P4::TypeInference(&refMap, &typeMap, false)
        });
        pgm = pgm->apply(passes);
        return pgm;
    }
```

**Comment by smolkaj** [comment]
Gotcha. Thanks for the quick reply!
