### ISSUE TITLE
Clarification question on uninitialized local headers

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2383]
After the recent discussions and spec merges I have a (hopefully) last question on header initialization. Are these constructs equivalent?

```p4
ethernet_t tmp;
tmp = { 48w1, 48w1, 16w1 };

```

```p4
ethernet_t tmp;
tmp.dst_addr = 48w1;
tmp.src_addr = 48w1;
tmp.eth_type = 16w1;
```

My initial guess was **no**, since the in the first example the header ist set to valid, whereas in the second I assume the header stays invalid. Otherwise any assignment to an invalid header would set it to valid again.

Based on my assumptions I have observed potentially incorrect behavior in the "CopyStructures" pass. The example program this time is actually something a sane person might write:

```p4
ethernet_t do_function() {
    return  {1, 1, 1};
}
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    apply {
        h.eth_hdr = do_function();
    }
}
```

With  `BMV2::SimpleSwitchMidEnd_19_CopyStructures`
```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    bool hasReturned;
    ethernet_t retval;
    apply {
        {
            hasReturned = false;
            hasReturned = true;
            retval = { 48w1, 48w1, 16w1 };
            h.eth_hdr = retval;
        }
    }
}
```

is converted to 

```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    bool hasReturned;
    ethernet_t retval;
    apply {
        {
            hasReturned = false;
            hasReturned = true;
            {
                retval.dst_addr = 48w1;
                retval.src_addr = 48w1;
                retval.eth_type = 16w1;
            }
            h.eth_hdr = retval;
        }
    }
}
```
Which lacks the `setValid` call. Maybe there is already a plan to fix this with the `setHeaders` pass?. 

[header_function_cast.p4.txt](https://github.com/p4lang/p4c/files/4643522/header_function_cast.p4.txt)
[header_function_cast.stf.txt](https://github.com/p4lang/p4c/files/4643524/header_function_cast.stf.txt)

**Comment by jafingerhut** [comment]
My understanding is that your assumption described early in the comment is correct:

The first code snippet will make the header `tmp` valid, as a result of the assignment `tmp = { 48w1, 48w1, 16w1 };`, and at the end all 3 fields of the header are guaranteed to have the indicated values.

The second code snippet will guarantee that `tmp` is initialized to invalid, and the later assignments to the fields of `tmp` will leave the header still invalid, and reading any of the fields after those assignments will not guarantee any particular read value, as those fields are still undefined.
