### ISSUE TITLE
Enum Underlying Representation Using Typedef

### ISSUE THREAD

**Issue by CommitThis** [p4lang/p4c#2391]
Apologies if I have missed something again but I am having some trouble with `p4c`. 
I am using version 1.2.0, targeting bmv2/v1model and using the simple switch.

I was expecting to be able to do something like:
```
typedef bit<16> EtherType_t;

enum EtherType_t EtherType_e {
    IPv4 = 0x0800
}
```

However this returns an error:
```
./simple.p4(15):syntax error, unexpected IDENTIFIER, expecting {
enum EtherType_t EtherType_e
                 ^^^^^^^^^^^
```
Compiling the following is ok though:
```
enum bit<16> EtherType_e {
    IPv4 = 0x0800
}
```

The p4-spec issue https://github.com/p4lang/p4-spec/issues/774 seemed to be somewhat relevant however @vgurevich used a similar syntax in their motivating example. I replicated this (providing a const int for the bit width) which didn't work either.

This isn't a big issue for me, I was just wondering If I had missed something.

Thanks

**Comment by jnfoster** [comment]
The grammar in the [language specification](https://p4.org/p4-spec/docs/P4-16-v1.2.0.html#sec-enum-types) requires serializable `enum`s to be declared with this syntax:
```
enumDeclaration
    : optAnnotations ENUM name '{' identifierList '}'
    | optAnnotations ENUM BIT '<' INTEGER '>' name '{' specifiedIdentifierList '}'
    ;
```
I just checked and the grammar seems fine if we replace this with `typeRef`, so we should probably generalize this...

**Comment by vgurevich** [comment]
Interesting... I didn't realize that the current grammar doesn't allow (a) bit<N>, where N is an expression and, more importantly  (b) int<N>. 

Replacing with typeRef seems like a good idea as long as we check that the underlying type is a scalar one with a specific bit width.

**Comment by hesingh** [comment]
`typeRef` does not include `TYPEDEF` which is included in p4 lang grammar to support typedef.  `typeRef` includes `baseType` which has checks for `bit<W>` type.   I am working with latest p4c.

**Comment by jnfoster** [comment]
@hesingh you don't want to literally write `typedef` in a serializable `enum`, so the token `TYPEDEF` is neither here nor there.

In the example, we want to refer to a name that was previously `typedef`'d. Hence `typeRef` is the right thing to put here: it includes both `baseType` and `typeName`.

**Comment by hesingh** [comment]
@jnfoster Ah, yes, you are correct.  I see `typedefDeclaration` include both typedef and `type`.  It's best to compile code changes and see what works.

**Comment by hesingh** [comment]
This issue should be marked as an enhancement.  

At least, I don't see an easy fix for this issue because `serEnum`  constructor needs a `Type_Bits` parameter but the yacc code only has `Type_Name` during processing of `serEnum`.   I don't see an easy way to get `Type_Typedef` from the `Type_Name`.  The yacc code has no lookup.  We cannot change constructor API for `Type_SerEnum` because p4runtime protobuf has already defined a `Type_Bits` for the API.

**Comment by hesingh** [comment]
FYI.  First-cut in a PR.

https://github.com/p4lang/p4c/pull/2394

**Comment by mbudiu-vmw** [comment]
Even if we allow a name defined by `typedef`, I don't think we should allow a name defined using a `type`. We should take this to the design group.

**Comment by mbudiu-vmw** [comment]
i have placed this on the agenda for our next design meeting.

**Comment by hesingh** [comment]
> Interesting... I didn't realize that the current grammar doesn't allow (a) bit, where N is an expression and, more importantly (b) int.
> 
> Replacing with typeRef seems like a good idea as long as we check that the underlying type is a scalar one with a specific bit width.

How is an enum defined using bit if N is an expression?  An example would help.

**Comment by jafingerhut** [comment]
@hesingh I believe this is an example of what vgurevich means, which is allowed in other contexts where `bit<expression>` is allowed:
```
bit<(5+3-2)> x;   // supported today by p4c, I believe
enum bit<(5+3-2)> MySerEnum_t {   // this is what is not supported by current grammar
// ... named values defined here, omitted in this example
}
```

**Comment by hesingh** [comment]
@jafingerhut Wow, thanks!  I was scratching my head thinking how an expression such as `h.eth.src_mac` could be used because the enum is defined globally.   I am clarifying such details so that I don't miss any case in the PR to develop this enhancement.

Also, note, folks or two have asked to use `typeRef` in the parser to allow more types.  If you see the parser code, these are the types.

https://github.com/p4lang/p4c/blob/master/frontends/parsers/p4/p4parser.ypp#L930

I don't think the enum should support `headerStackType` or `specializedType`.  If we agree, then the parser should define a new enumTypeRef for use which is a subset of `typeRef`.

**Comment by hesingh** [comment]
"5+3-2" does not qualify as a `typeRef`.  It's an `expression` which makes the serEnum more complicated.  I wonder why we should allow an expression when one can write "6"?

**Comment by jnfoster** [comment]
Ok, but `bit<5 + 3 - 2>` is a `baseType` which is in turn a `typeRef`.

See https://github.com/p4lang/p4c/blob/master/frontends/parsers/p4/p4parser.ypp#L965

It's  extremely convenient to allow compile-time known expressions for expressions over contants defined by the C-preprocessor...

**Comment by hesingh** [comment]
Sorry, my bad!  @jnfoster you are correct - thanks.

**Comment by jafingerhut** [comment]
@hesingh asked: ""5+3-2" does not qualify as a typeRef. It's an expression which makes the serEnum more complicated. I wonder why we should allow an expression when one can write "6"?"

`5+3-2` is probably not what people would want to write, I agree.

More useful for a P4 developer would be to write something like:
```
#define PORT_SIZE 9
#define IPV4_ADDR_SIZE 32

bit<(IPV4_ADDR_SIZE + PORT_SIZE)> x;
```
