### ISSUE TITLE
Question on comparison to negative constants

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2392]
So I am a little bit confused on how to treat the following expression:
Is this true, false, or undefined?

```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    apply {
        if (8w255 == -1) {
            h.eth_hdr.eth_type = 1;
        } else {
            h.eth_hdr.eth_type = 2;
        }
    }
}
```
After `FrontEnd_6_ConstantFolding` this evaluates to false.
The compiler naturally also gives a warning:
```
bugs/negative_equality.p4(30): [--Wwarn=mismatch] warning: -1: negative value with unsigned type
        if (8w255 == -1) {
```
I assumed this equality would evaluate to true since both expressions are 8w255 after the implicit cast. **Unless** such a comparison always evaluates to false, regardless of value, because of the type mismatch. I was digging through the `constantFolding.cpp` code and saw that the result is evaluate before the cast: https://github.com/p4lang/p4c/blob/master/frontends/common/constantFolding.cpp#L419
Is this intentional? 

[negative_equality.p4.txt](https://github.com/p4lang/p4c/files/4672082/negative_equality.p4.txt)
[negative_equality.stf.txt](https://github.com/p4lang/p4c/files/4672081/negative_equality.stf.txt)

**Comment by mbudiu-vmw** [comment]
Good question, I think this is a bug, because the spec says that -1 should be cast to whatever type is on the left, and then this should be true.

**Comment by mbudiu-vmw** [comment]
We will discuss this in the design working group nevertheless.
