### ISSUE TITLE
Egress Pipeline does not works

### ISSUE THREAD

**Issue by Hoangttrieu** [p4lang/p4c#2397]
Hello,
I sent a ping with GTP header, the Ingress pipeline works and forwards the packet to egress port. But the egress pipeline doesn't start and then, the switch starts again with the new packet. Do you have any idea about that problem and what I have to do to debug this? Thanks

**Comment by hesingh** [comment]
Are you using bmv2 simple_switch?

**Comment by Hoangttrieu** [comment]
yes, I used the bmv2 simple_switch_grpc. I send the packet without GTP header, when the ingress pipeline finished, the egress starts the pipeline. But the one with GTP, The Ingress pipeline finishs, the switch starts to paser packet.

**Comment by Hoangttrieu** [comment]
And i use the v1model too.

**Comment by hesingh** [comment]
One reason for egress pipeline not starting is if egress_port is not set by ingress processing.  It's hard to debug your issue without seeing your P4 program.

**Comment by mbudiu-vmw** [comment]
This is not an appropriate place for this bug report, this is the repository of the p4c compiler. If you think that this is a compiler bug, then please provide more information so we can reproduce your issue.

**Comment by Hoangttrieu** [comment]
Thanks for your help. Like hesingh said, i found the problem.
