### ISSUE TITLE
Question about P4 meter

### ISSUE THREAD

**Issue by skywood123** [p4lang/p4c#2406]
As I know, P4 meter will return values 0,1,2 representing the tricolor marking related to the meter rate we configured.
Can I know is there any way to read the current bytes/second Bps for that meter?
Or any other methods to get that information.

Thanks.

**Comment by jafingerhut** [comment]
From the P4 program, there is no built-in way to read the current bytes/second configuration for a meter.

One can of course create a table that, if you write control plane software that populates the contents of that table with that information, the P4 program can apply that table to read that information.

**Comment by jafingerhut** [comment]
I believe the question has been answered, and it is not obvious that there are any issues with the compiler that result from it or the answer, so closing this issue.  Feel free to reopen, or create issues for other questions, if some were left unanswered.
