### ISSUE TITLE
tcp connection refused.

### ISSUE THREAD

**Issue by mcvzon** [p4lang/p4c#2411]
I'm trying to connect docker container by the  p4 bmv2 switch on different host using p4_14 language. Pinging remote containers (also connected to a p4 switch) works fine. But when i want to establish a tcp connection, the connection gets reseted everytime. At tcp level only the checksum is updated. For this i used the example of: https://github.com/lorenzosaino/p4-tutorials/blob/master/examples/simple_nat/p4src/simple_nat.p4. Below the code i used:
```javascript
field_list tcp_checksum_list {
        ipv4_hdr.src;
        ipv4_hdr.dst;
        8'0;
        ipv4_hdr.proto;
        meta.tcpLength;
        tcp_hdr.src;
        tcp_hdr.dst;
        tcp_hdr.seq;
        tcp_hdr.ack;
        tcp_hdr.offset;
        tcp_hdr.resrv;
        tcp_hdr.flags;
        tcp_hdr.window;
        tcp_hdr.urgent;
        payload;
}

field_list_calculation tcp_checksum {
    input {
        tcp_checksum_list;
    }
    algorithm : csum16;
    output_width : 16;
}

calculated_field tcp_hdr.checksum {
    update tcp_checksum if(valid(tcp_hdr));
}
```

For two containers on the same host because there is no Nat involved .Two container on the same host can establish a tcp connection. I can just measure throughput with iperf3 server/client tools.

**Comment by jnfoster** [comment]
This is the repository for the P4 compiler. It's not a great place to ask this question.

Can you maybe post it on the p4-dev email list or perhaps the [P4 Slack](https://p4-lang.slack.com/join/shared_invite/enQtODA0NzY4Mjc5MTExLTRlMWVmN2I5ZTY4MTAzMDI3MGQ1OTZjM2ZmM2Q1MWE2YzZjYTQ2ZWMyMGUyYjQ2ZmIxMjFjZDE4ZThiN2ZkZWI#/)?
