### ISSUE TITLE
Broken STF test

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#2421]
It looks to me like these two lines in the `runtime-index-bmv2` STF test are wrong.

https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples/runtime-index-bmv2.stf#L46
https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples/runtime-index-bmv2.stf#L78

**Comment by hesingh** [comment]
@jnfoster Yes, this was temporary code.  The P4 program has to change to use registers and then STF test cases will be updated.  I nor others at the IETF hackathon did not get the time to work on these issues yet.

**Comment by jafingerhut** [comment]
Do you mean that those lines should be comments, but have no '#' as a prefix?  If so, I agree, and the fix is simply to prefix those lines with '#' characters.

**Comment by mbudiu-vmw** [comment]
Finally, a bug which is easy to fix.
