### ISSUE TITLE
p4c make fail on .def

### ISSUE THREAD

**Issue by czusual** [p4lang/p4c#2422]
I followed the instructions in README.md，and met this problem :
![deferror](https://user-images.githubusercontent.com/17592533/83968597-dc54ee80-a8fc-11ea-9fbc-7cbdd6b22284.jpg)

I have installed all the dependencies . Please offer guidance on how to fix it , really thanks!

**Comment by jafingerhut** [comment]
I do not recognize that error, so do not know what you might be missing.  There are incomparably more ways to install the dependencies incorrectly, than there are ways to install them correctly.

One way to install them correctly is by starting from a freshly installed Ubuntu Linux 16.04 or 18.04 system, and running a script like the one described here: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

If that doesn't work for you, and if you save the complete output from trying to run such an installation script, then someone has a chance of knowing what steps you followed, and whether you have actually installed all of the dependencies or not.

**Comment by ChrisDodd** [comment]
I haven't seen that error before, which appears to be coming from the ir-generator, complaining about unrecognized characters in its input files.  Best guess is perhaps that you have some old, weird version of flex or bison installed?  Other than that, something has perhaps corrupted the .def source files (perhaps if you have some tool installed that thinks it should do something with files with a .def extension?)

**Comment by ChrisDodd** [comment]
Suggestions of things to look at:

- run `bison --version` and `flex --version` to see which versions you have installed (I forget which versions we suggest as minimums but I use 3.0.4 and 2.6.0 repectively)
- from the ~/p4c directory, do `git diff ir` to make sure none of those files have been modified by anything.  If they have `git checkout -- ir` should restore them.
