### ISSUE TITLE
p4test: x: declaration not found

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2435]
Running `p4test` there seem to be a problem with the way variables are propagated in the mid end. This only happens in combination with exit statements. There are two examples. One happens after inlining a global action, the other happens after a constant key is simplified. In both cases `MidEnd_25_LocalCopyPropagation` removes variables that it should not. 

[key_after_exit.p4.txt](https://github.com/p4lang/p4c/files/4769830/key_after_exit.p4.txt)
```
MidEnd_20_FlattenInterfaceStructs
MidEnd_21_ReplaceSelectRange
MidEnd_22_Predication
MidEnd_23_MoveDeclarations
MidEnd_24_ConstantFolding
MidEnd_25_LocalCopyPropagation
[--Werror=not-found] error: key_0: declaration not found
Done.*/
```

[global_action_after_exit.p4.txt](https://github.com/p4lang/p4c/files/4769831/global_action_after_exit.p4.txt)
```
MidEnd_20_FlattenInterfaceStructs
MidEnd_21_ReplaceSelectRange
MidEnd_22_Predication
MidEnd_23_MoveDeclarations
MidEnd_24_ConstantFolding
MidEnd_25_LocalCopyPropagation
bugs/crash/global_action_after_exit.p4(348): [--Werror=not-found] error: val: declaration not found
action do_action(inout ethernet_t val) {
```

**Comment by hesingh** [comment]
@mbudiu-vmw and @ChrisDodd  In our prior discussion, we seem to be converging on removing exit statements inside action if the action includes any `hasOut` parameter.  

This issue uses an exit inside the control apply block and global action.  I thought we could leave this exit for the bmv2 backend to deal with.  If we do, the midend screws up the IR.  

```p4
action do_action(inout ethernet_t val) {
    val.eth_type = 0xDEAD;
}
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {

    apply {
        exit;
        do_action(h.eth_hdr);
    }
}
```

**Comment by hesingh** [comment]
@mbudiu-vmw Having poked around more, I see p4c already supports an exit statement inside if-else.  For example, I found `p4c/testdata/p4_16_samples/exit2.p4`.  This test case do not include any action with `hasOut` parameter or even a parameter.  But the control the action is inside has an out parameter.  So now, one should also check if the control has a `hasOut` parameter and remove exit statement(s) from control actions.

The current behavior for handling exit in exti2.p4 looks correct to me.  Should we bother changing the behavior for such a test if exits are removed in frontend code?

**Comment by mbudiu-vmw** [comment]
@ChrisDodd : here the LocalCopyProp removes a variable used in a table key. So the dead code elimination is not conservative enough.

**Comment by ChrisDodd** [comment]
localCopyProp removes the key because the table is never applied, so it doesn't actually use the key.  Unfortunately, as it doesn't remove the dead table, it leaves in the reference to the key in the table.  For global_after_exited, the same applies, except it is the action that is dead, so the reference to the global in it is not noticed by local copyprop.

Easiest fix is probably to have a pass that removes unused tables and actions before local copyprop.

**Comment by mbudiu-vmw** [comment]
Actually I believe that our pass to remove unused references should do this, but we explicitly prevent it from doing that, because this would change the P4Runtime API generated. I think dead tables should be removed.

**Comment by hesingh** [comment]
This is why I developed the rmExits pass to remove dead tables and call rmExits just before unused references in frontend.cpp in my recent [PR ](https://github.com/p4lang/p4c/pull/2443).  The PR has fixed this issue.

**Comment by ChrisDodd** [comment]
So I added a PR #2446 that avoids the problem in LocalCopyProp

- by default, it will treat unreferenced actions/tables in a control as sources for potential access to local vars (so will not eliminate them)
- with a flag, will remove the unreferenced local tables and actions (along with the other dead locals that were only referenced by them).
