### ISSUE TITLE
Published P4C docker image: python3 missing

### ISSUE THREAD

**Issue by b3n-l** [p4lang/p4c#2438]
Docker image is missing python3, this stops p4c from being able to run.

To reproduce:
`docker run -it --rm p4lang/p4c` returns `/usr/bin/env: 'python3': No such file or directory`

Bug is caused in tools/travis-build, when in build mode, python3 is uninstalled as part of the cleanup script

**Comment by BenRLewis** [comment]
#2439 Pull request with potential fix
