### ISSUE TITLE
There are two different versions of ubpf_model.p4 in the repository

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#2442]
Which one is right?
backends/ubpf/p4include
and 
p4include

**Comment by mbudiu-vmw** [comment]
@osinstom : do you know the answer to this question?

**Comment by osinstom** [comment]
The one under `backends/ubpf/p4include` is right. The other one was not part of my original PR with uBPF backend implementation.

**Comment by mbudiu-vmw** [comment]
Fixed by #2464
