### ISSUE TITLE
Casting integers to bool

### ISSUE THREAD

**Issue by hackedy** [p4lang/p4c#2444]
The following code is accepted.
```
const int a =  1;
const bool b = (bool)a;
```

If I change the 1 to a 2w1, then the program is rejected with a message that "only bit<1> values can be cast to bool":
```
const int a =  2w1;
const bool b = (bool)a;
```

I would expect the first program to fail since it's casting an int and not a bit<1> to bool, and I'd think the second program would result in an error on the first line because it's assigning a bit<2> to an int variable.

**Comment by mbudiu-vmw** [comment]
The first one actually will require the spec to clarify whether we expect int values to be cast to bool or not. Arguably it is wrong, but we may want to allow this.

The second one does look like a bug, but we may want to allow this one too - a would then be assigned the value 1, and not 2w1.

**Comment by mbudiu-vmw** [comment]
I have added an entry to the LDWG discussion list to tackle this next time.
I won't fix it until we clarify what we should be doing.

**Comment by hackedy** [comment]
Sounds good--I wasn't sure whether this was a spec problem or a p4c problem.

**Comment by mbudiu-vmw** [comment]
`int a = 2s2;`

**Comment by mbudiu-vmw** [comment]
LDWG: allow casts from int to bool if the int is 0 or 1.

**Comment by mbudiu-vmw** [comment]
Allow assignments from bit<W> and int<w> to int.
