### ISSUE TITLE
Are headers with multiple varbit fields allowed?

### ISSUE THREAD

**Issue by hackedy** [p4lang/p4c#2445]
The spec says that `extract` doesn't allow headers to have multiple varbit fields, but I don't think there's a restriction on header declarations in general. P4C will reject programs like this, for example, even if the header type H isn't used anywhere.
```
header H {
    varbit <120> x;
    varbit <120> u;
}
```

**Comment by jafingerhut** [comment]
If headers with multiple varbit fields were permitted, they would not be _useful_ for anything, at least given the existing operations on headers in the public specs.  It would require new extern functions/methods to make such a header useful for anything.

Of course, P4 implementations are free to provide such extensions to the language, so at least not giving an error for such header definitions seems reasonable, if it is not being used in an extract operation.
