### ISSUE TITLE
Table default_action code organization in p4c

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#2461]
A p4-16 table has an optional property in `default_action`.  I was expecting yacc code for it in `p4c/frontends/parser/p4/p4parser.ypp` which is p4-16 code.  However, to my surprise, yacc code for it exists in p4-14 yacc code in `p4c/frontends/parser/v1/v1parser.ypp`.

Why is that?

Any plans to move this code to the p4-16 yacc code?

**Comment by mbudiu-vmw** [comment]
That is a table property matched by this rule:
```
 | optAnnotations optCONST nonTableKwName "=" initializer ";"
```

**Comment by hesingh** [comment]
Thanks.  I only searched for "default_action" in p4c code, but having looked at `ir.def` I found `defaultActionPropertyName`
