### ISSUE TITLE
Compiler Bug: Null expression

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4c#2465]
Attached is a simple test program [lookahead-stack.p4.txt](https://github.com/p4lang/p4c/files/4859090/lookahead-stack.p4.txt) that results in the compiler crash with the following message:

```
$ p4test lookahead-stack.p4 
lookahead-stack.p4(24): [--Werror=legacy] error: header h1[]: unexpected type in lookahead argument
    h1[3] h;
    ^^^^^
In file: /home/vgurevich/trees/org/p4c/build/ir/ir-generated.cpp:541
Compiler Bug: /home/vgurevich/trees/org/p4c/build/ir/ir-generated.cpp:541: Null expression
```

The crash itself is probably the result of the warning before it, but more importantly, this is a pretty important use case that simulates how people usually do fast parsing of VLAN tags or MPLS labels in P4. This is related to the issue p4lang/p4-spec#879.

**Comment by mbudiu-vmw** [comment]
Fixing the crash is easy.
Indeed, currently lookahead does not support stacks. I will have to spend a bit of time to add support for that, so I am thinking to submit a PR which fixes both.
If we had a syntax for initializing a header stack it actually would be somewhat easier.
