### ISSUE TITLE
Which commit correspond to most recent version of P4-16 standard?

### ISSUE THREAD

**Issue by jphurl** [p4lang/p4c#2476]
We are looking to do a merge with p4c and would like to know which commit would be best to merge with. Preferably it would correspond with the most recent version of the P4-16 standard. @mbudiu-vmw I am guessing you might know :). Thanks

**Comment by mbudiu-vmw** [comment]
The code does not track the standard exactly, but it is pretty close.
There are some experimental features in the code not yet in the standard.
The support for `...` initializers is in the standard but not yet merged in the code; we have a PR for that.

**Comment by jphurl** [comment]
So you would recommend ToT? or do you have a favourite commit?

**Comment by hesingh** [comment]
My 2 cents is to just merge with latest p4c from July 20th.  If you can share more details for what you'd do with p4c, we can let you know if p4c has support or rough ETA for support, etc.

**Comment by mbudiu-vmw** [comment]
I guess that now that we have automatic releases it's easier to answer this question.
