### ISSUE TITLE
Conditional execution in actions with struct initializers

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2486]
This is something I have been wondering about:
Running `p4test` on the following program

```p4
control ingress(inout Headers h) {
    action dummy_action() {
        if(h.eth_hdr.eth_type == 0xDEAD) {
            ethernet_t swap = { h.eth_hdr.src_addr, h.eth_hdr.dst_addr, h.eth_hdr.eth_type };
            h.eth_hdr =  swap;
        }
    }
    apply {
        dummy_action();
    }
}
```
gives me the error:
```
conditional_execution_p4test.p4(26): [--Werror=target-error] error: swap.setValid: Conditional execution in actions unsupported on this target                                                                   
            ethernet_t swap = { h.eth_hdr.src_addr, h.eth_hdr.dst_addr, h.eth_hdr.eth_type };                 
                       ^^^^                                                                                   
conditional_execution_p4test.p4(26): [--Werror=target-error] error: swap.setValid: Conditional execution in actions unsupported on this target                                                                   
            ethernet_t swap = { h.eth_hdr.src_addr, h.eth_hdr.dst_addr, h.eth_hdr.eth_type };   
```

Is this intentional? It looks to me that the compiler inserts the `setValid()` call, which is considered as an illegal conditional execution in later passes. 

[conditional_execution_p4test.p4.txt](https://github.com/p4lang/p4c/files/5021348/conditional_execution_p4test.p4.txt)

**Comment by mbudiu-vmw** [comment]
There is no illegal conditional execution; at this point the bmv backend does not support conditionals in actions.
Neither does p4test.
Some conditionals can be replaced with predicated execution, but not all. 
bmv2 itself does support conditionals in actions, but we never got to implementing this feature. We have an issue open tracking this request.
