### ISSUE TITLE
Side effects in StructInitializers

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2488]
I have a question about side effects in StructInitializerExpressions:
The following program
```p4
bit<48> set(inout bit<48> set) {
    set = 1;
    return 48w2;
}
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    Headers tmp = { { h.eth_hdr.dst_addr, set(h.eth_hdr.dst_addr), 1 } };

    apply {
        h = tmp;
    }
}
```

 is transformed from

```p4
bit<48> set(inout bit<48> set) {
    set = 48w1;
    return 48w2;
}
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    Headers tmp_0;
    apply {
        tmp_0 = (Headers){eth_hdr = (ethernet_t){dst_addr = h.eth_hdr.dst_addr,src_addr = set(h.eth_hdr.dst_addr),eth_type = 16w1}};
        h = tmp_0;
    }
}
```

to 

```p4
bit<48> set(inout bit<48> set) {
    set = 48w1;
    return 48w2;
}
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    Headers tmp_0;
    bit<48> tmp;
    apply {
        {
            tmp = set(h.eth_hdr.dst_addr);
            tmp_0 = (Headers){eth_hdr = (ethernet_t){dst_addr = h.eth_hdr.dst_addr,src_addr = tmp,eth_type = 16w1}};
        }
        h = tmp_0;
    }
}
```
after `31_SideEffectOrdering`.
is this correct? Intuitively I would assume that the function call is evaluated _after_ `h.eth_hdr.dst_addr `has been assigned.

[side_effects_in_initializer.stf.txt](https://github.com/p4lang/p4c/files/5021620/side_effects_in_initializer.stf.txt)
[side_effects_in_initializer.p4.txt](https://github.com/p4lang/p4c/files/5021621/side_effects_in_initializer.p4.txt)

**Comment by mbudiu-vmw** [comment]
yes, the value of dst_addr should be saved and then the call to set should be executed.
side-effects are evil.

**Comment by mbudiu-vmw** [comment]
@fruffy : the stf file you have attached seems wrong. AT the very least eth_type should be 1 but your file is all zeros.

**Comment by fruffy** [comment]
Yes, it should have been
```bash
packet 0 00 00 00 00 00 00 00 00 00 00 00 00 00 00
expect 0 00 00 00 00 00 00 00 00 00 00 00 02 00 01
```
