### ISSUE TITLE
Why is table direct_counter not a list instead of an object?

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#2491]
Please see this line of code.

 https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4#L188

Forget for a moment that the v1model is frozen for changes.  We can make changes to PSA. 

Anyone see any pitfalls if we changed the `counters` to a list such as what is used with table `actions`?

My use case is an ACL (access list) which uses a table.  I'd like the table counters to support 

`counters ={ permit_counter; drop_counter; }`

**Comment by hesingh** [comment]
When I gave this example in the P4 Slack channel, @vgurevich replied.  His reply is included below the code.

```
direct_counter<bit<64>>(CounterType_t.PACKETS_AND_BYTES) direct_counter;
    action permit() {
        direct_counter.count();
    }
    action drop() {
        // drop pkt.
        direct_counter.count();
    }
    table acl {
        key = {
	    ...
	}
        actions = { drop; permit; }
        const default_action = drop;
        counters = direct_counter;
    } 
```

"When you retrieve a counter, it is associated with an entry in this table. Each entry has either a drop or permit action. Therefore, if a counter belongs to an entry with the permit action, that means that it counts the packets that were allowed to go through and if a counter belongs to an entry with the drop action, that means that it counts the packets that were dropped."

I think would be good to document the counter behavior in a PSA Appendix or in v1model.p4

**Comment by jafingerhut** [comment]
Does Section 7.7 of the PSA specification make it clear?  https://p4.org/p4-spec/docs/PSA-v1.1.0.html#sec-counters

In particular, this text: "A single instantiation of a direct counter always contains as many independent counter values as the number of entries in the table with which it is associated."
