### ISSUE TITLE
Assignment statement incorrectly eliminated inside subparser?

### ISSUE THREAD

**Issue by zma-barefoot** [p4lang/p4c#2493]
When compiling program below with `-DSUBPARSER`, the assignment `meta.bar.field = x.field;` within  the subparser is missing at the end of frontend.

`FrontEndLast:`

```
parser ParserImpl(packet_in pkt, out headers_t hdr, inout metadata_t meta, inout standard_metadata_t standard_metadata) {
    foo_t x_0;
    state start {
        x_0.setInvalid();
        pkt.extract<foo_t>(x_0);
        hdr.ethernet.setInvalid();
        hdr.ipv4.setInvalid();
        meta.bar.setInvalid();
        transition PacketParser_start;
    }
    state PacketParser_start {
        pkt.extract<ethernet_t>(hdr.ethernet);
        pkt.extract<ipv4_t>(hdr.ipv4);
        transition start_0;
    }
    state start_0 {
        transition accept;
    }
}
```

If compiled without `-DSUBPARSER`, everything looks good. Is this a bug?

`FrontEndLast:`

```
parser ParserImpl(packet_in pkt, out headers_t hdr, inout metadata_t meta, inout standard_metadata_t standard_metadata) {
    foo_t x_0;
    state start {
        x_0.setInvalid();
        pkt.extract<foo_t>(x_0);
        meta.bar.field = x_0.field;
        pkt.extract<ethernet_t>(hdr.ethernet);
        pkt.extract<ipv4_t>(hdr.ipv4);
        transition accept;
    }
}
```

Full test:

```
#include <core.p4>
#include <v1model.p4>

header ethernet_t {
    bit<48> dstAddr;
    bit<48> srcAddr;
    bit<16> etherType;
}

header ipv4_t {
    bit<4>  version;
    bit<4>  ihl;
    bit<8>  diffserv;
    bit<16> totalLen;
    bit<16> identification;
    bit<3>  flags;
    bit<13> fragOffset;
    bit<8>  ttl;
    bit<8>  protocol;
    bit<16> hdrChecksum;
    bit<32> srcAddr;
    bit<32> dstAddr;
}

struct headers_t {
    ethernet_t ethernet;
    ipv4_t     ipv4;
}

header foo_t {
    bit<16> field;
};

struct metadata_t {
    foo_t bar;
}

parser PacketParser(
        packet_in pkt,
        out headers_t hdr,
        out metadata_t md) {
    state start {
        pkt.extract(hdr.ethernet);
        transition parse_ipv4;
    }

    state parse_ipv4 {
        pkt.extract(hdr.ipv4);
        transition accept;
    }
}

parser ParserImpl(packet_in pkt,
                  out headers_t hdr,
                  inout metadata_t meta,
                  inout standard_metadata_t standard_metadata)
{
#ifdef SUBPARSER
    PacketParser() packet_parser;
#endif

    state start {
        foo_t x;
        pkt.extract(x);

        meta.bar.field = x.field;

#ifdef SUBPARSER
        transition parse_packet;
    }

    state parse_packet {
        packet_parser.apply(pkt, hdr, meta);
        transition accept;
    }
#else

        transition parse_ethernet;
    }

    state parse_ethernet {
        pkt.extract(hdr.ethernet);
        transition parse_ipv4;
    }

    state parse_ipv4 {
        pkt.extract(hdr.ipv4);
        transition accept;
    }
#endif
}


control ingress(inout headers_t hdr,
                inout metadata_t meta,
                inout standard_metadata_t standard_metadata)
{
    apply { }
}

control egress(inout headers_t hdr,
               inout metadata_t meta,
               inout standard_metadata_t standard_metadata)
{
    apply { }
}

control DeparserImpl(packet_out packet, in headers_t hdr) {
    apply { }
}

control verifyChecksum(inout headers_t hdr, inout metadata_t meta) {
    apply { }
}

control computeChecksum(inout headers_t hdr, inout metadata_t meta) {
    apply { }
}

V1Switch(ParserImpl(),

         verifyChecksum(),
         ingress(),
         egress(),
         computeChecksum(),
         DeparserImpl()) main;



```

**Comment by fruffy** [comment]
I think this is okay. Looking at the sub-parser signature `PacketParser(packet_in pkt, out headers_t hdr, out metadata_t md)` it looks like both `md` and `hdr` will be uninitialized, which renders previous assignments void. So `meta.bar.field = x.field;` can safely be removed.

**Comment by zma-barefoot** [comment]
I'm not sure I follow. How can I use the subparser without rending previous assignments void in this case?

**Comment by fruffy** [comment]
As far as I know, you will have to label `hdr` and `md` as `inout`. It should work then.
https://p4.org/p4-spec/docs/P4-16-v1.2.1.html#sec-calling-convention

**Comment by zma-barefoot** [comment]
`md` is declared `out` in `PacketParser` but as `inout` in the caller `ParserImpl`. If I read the spec correctly, this means `md` is uninitialized in the context of `PacketParser`, but why should be assignment in the caller be removed? Help me understand this better?

**Comment by fruffy** [comment]
Copy-in/copy-out works in the way that any variable with the label `inout`/`out` will be copied back once the function returns. 

> On function return, the temporaries that correspond to out or inout arguments are copied in order from left to right into the l-values saved in step 2. 

So when you have an input that is labelled `out` it will be first uninitialized and then whatever value it has once the callee returns is copied back into the input reference. For `out` the implication is that any value the variable might have before that is meaningless because the input is uninitialized at the beginning of the call. With that in mind the compiler is free to remove any previous assignments. 

In your case, the `Inline` compiler pass removes the assignment. Whether that is intentional or not I do not know, but it does not affect the correctness of the program.

**Comment by zma-barefoot** [comment]
Thanks for you explanation, @fruffy. I see what you mean now.

I think the source of my confusion comes from the understanding of "uninitialized". I thought "uninitialized" meant the variable will remain uninitialized, and will retain previous value if there's any, and if there's no previous value, uninitialized variable will have indeterminate value, i.e. garbage value. This is as if I write `int x;` in a local scope, and `x` will assume indeterminate value.

@mbudiu-bfn would you be able to help us confirm if the removal the assignment in the caller when doing inlining is intentional or not? Thanks!

**Comment by fruffy** [comment]
It is `simplifyDefUse` that removes the assignment, sorry about that.

**Comment by jafingerhut** [comment]
I do not know whether there might be a bug in p4c related to the behavior you are seeing with this P4 program, but I do have a different P4 code snippet and a link to part of the P4_16 language spec that might clarify the meaning of 'uninitialized' in the comments above.

See this section of the P4_16 language spec: https://p4.org/p4-spec/docs/P4-16-v1.2.1.html#sec-uninitialized-values-and-writing-invalid-headers

Also consider this code snippet:
```
    bit<8> x;
    bit<8> y;

    y = 5;
    if (hdr.ipv4.isValid()) {
        y = x;
    }
```
If `hdr.ipv4.isValid()` is false, then the language spec says that the final state will be one where `y` deterministically has the value `(bit<8>) 5`

If `hdr.ipv4.isValid)` is false, the language spec does not specify what the value of `x` or `y` will be, other than that they will have some value of type `bit<8>` when you try to read them.

A fast path data plane implementation will typically not use extra bits of storage to record whether a variable has been assigned a value, or not.

**Comment by mbudiu-vmw** [comment]
A header that is `out` will be initialized to invalid in the callee - the definition of uninitialized headers still requires the valid bits to be false. If an argument has no "in" there is no copy-in, but there will be a copy-out. Think of having a local in the subparser which is copied on return into the out headers. So you lose everything you used to have in the headers in the caller.

I no longer use mbudiu-bfn, my current alias is mbudiu-vmw.

**Comment by zma-barefoot** [comment]
Thanks @jafingerhut, and @mbudiu-vmw. It's clear to me now.
