### ISSUE TITLE
Shifts with very large values

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2496]
This is a quirk I have encountered while investigating int expressions. When shifting with a very large InfInt value the compiler can take a fairly long time (minutes) just to print out a warning. Not sure if that is the intended behaviour. Maybe it would make sense to just point to the expression instead of the calculated value? 

[big_warning_message.p4.txt](https://github.com/p4lang/p4c/files/5056825/big_warning_message.p4.txt)

**Comment by mbudiu-vmw** [comment]
`e =  1985245330 << 903012108;`
This is a funny one. The constant folding will try to actually compute this using infinite precision, so it will really generate a very large number. In principle I don't know how to avoid this, you could be doing `(1 << (BILLION + 1)) >> BILLION`. We could have the compiler refuse to handle any shift by an amount that is ridiculously large (more than 5K?). @ChrisDodd ?
