### ISSUE TITLE
Memory Utilization of a P4 switch

### ISSUE THREAD

**Issue by sanaa50** [p4lang/p4c#2507]
I'm working on an emulated network which is consists of two host connected to each other by a P4 switch. The two hosts transfer files to each other. 
By running `top | grep simple_switch` I can see the CPU utilization is increased during the transfer, but the memory utilization is almost fixed.
Can anybody explain why the memory usage is not changing during the file transfer?

**Comment by jnfoster** [comment]
Well, the files get chopped up into packets, which have a maximum size, often 1500 bytes. I don't know how many packets are being buffered and processed by Bmv2, but if it's not a large number, I suppose the memory needed to store those bits could be negligible compared to a large C++ binary?

More generally, I would warn against drawing conclusions about operational considerations like memory usage from Bmv2. It's really just a functional simulator and not realistic in many aspects.

**Comment by sanaa50** [comment]
Thank you.
