### ISSUE TITLE
Ternary "const entries" do not seem to work when the key has only one field in it

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4c#2514]
Attached is a trivial test program [issue2514.p4.txt](https://github.com/p4lang/p4c/files/5112819/issue2514.p4.txt), which fails to compile with the following syntax error:
```
issue2514.p4(43):syntax error, unexpected ), expecting ","
            (16w0x0101 &&& 16w0x0505)
                                    ^
error: 1 errors encountered, aborting compilation
```

The problem seems to be in the fact that the table has only one field in the key:
```
    table t {
        key = {
            hdr.h.f1 : ternary;
        }
        actions = { hit; }
        const entries = {
            (16w0x0101)               : hit(1);
            (16w0x0101 &&& 16w0x0505) : hit(5);
            (_)                       : hit(0);
        }
    }
```

Adding one more field (compile with `-DCASE_FIX`) seems to "fix" the problem:
```
    table t {
        key = {
            hdr.h.f1 : ternary;
            hdr.h.f2 : ternary;
        }
        actions = { hit; }
        const entries = {
            (16w0x0101, 0)                     : hit(1);
            (16w0x0101 &&& 16w0x0505, 0 &&& 0) : hit(5);
            (_,_)                              : hit(0);          
        }
    }
```

**Comment by jfingerh** [comment]
I do not know the full reason, but I believe if you leave the parentheses off of the const entries field match expressions when there is only one table key field, it works.

I suspect the reason is related to the P4_16 type being considered a tuple when there are multiple key field, but not a tuple when there is only one.  I'm not saying this is a fun detail to remember when programming such const entries, nor that it necessarily ought to be that way, but I think that is the way it is now in p4c.

**Comment by vgurevich** [comment]
@jafingerhut -- you are right! If there is only one field in the key, parentheses have to be omitted. Although this might be a nice trivia to teach, I'd certainly prefer that we settle on a uniform syntax :)

Also, the same issue exists in `select()`, so it might be a nice way to remember the current situation, i.e. "code the keys for the entries the same way you would code the keys in `select()`).

In other words:
```
transition select (hdr.ethernet.ether_type) {
     0x8100  : parse_1; /* Works */
    (0x9100) : parse_2; /* Also Works */
     0xA100 &&& 0xEFFF  : parse_3: /* Works */
    (0xC100 &&& 0xEFFF) : parse_4; /* Syntax error: ',' expected */
     _ : parse_5; /* Works */
    (_): parse_6: /* Doesn't work */
}
```

Proposal is probably to allow tupleKeysetExpression with 1 element. Currently the grammar seems to specify at least two, indeed:
```
tupleKeysetExpression
    : '(' simpleKeysetExpression ',' simpleExpressionList ')'
    ;

simpleExpressionList
    : simpleKeysetExpression
    | simpleExpressionList ',' simpleKeysetExpression
    ;
```

**Comment by jnfoster** [comment]
Totally agree with @vgurevich. The syntax should be consistent and should not have these kinds of little "gotchas."

**Comment by mbudiu-vmw** [comment]
This is also related: https://github.com/p4lang/p4c/issues/2456

**Comment by apinski-cavium** [comment]
Note after this change, if you use select and keyset expressions with a tuple type itself, things are interesting.

Take:
```
    typedef bit t;

    parser MyParser1(in tuple<t, t> tt1) {
        state start {
            transition select(tt1[0], tt1[0]) {
                    //({1, 1}): accept;
                    //{tt1}: accept;
                    (tt1[0], tt1[1]): reject;
                    tt1: accept;
                    (tt1): accept;
                    _: reject;
            }
        }
    }
```
And
```
    typedef bit t;

    parser MyParser1(in tuple<t> tt1) {
        state start {
            transition select(tt1) {
                    {{1}}: accept;
                    {tt1}: accept;
                    {{tt1[0]}}: reject;
                    //tt1: accept;
                    //(tt1): accept;
                    _: reject;
            }
        }
    }
```

I would have expected the commented out ones to work. Rather than the other ones.  The second example is even more fun.
