### ISSUE TITLE
p4c --help-annotations option doesn't work

### ISSUE THREAD

**Issue by blp** [p4lang/p4c#2521]
`p4c --help-annotations` just yields an error message:

```
$ p4c --help |grep -e --help-annotations
  --help-pragmas, --pragma-help, --pragmas-help, --help-annotations, --annotation-help, --annotations-help
$ p4c --help-annotations
cc: error: dummy.p4: No such file or directory
cc: fatal error: no input files
compilation terminated.
$ 
```

Similarly for `--help-pragmas`.

**Comment by hanw** [comment]
It now exits with a proper message in https://github.com/p4lang/p4c/pull/2522

`bmv2-v1model backend does not provide help message for pragmas/annotations`
