### ISSUE TITLE
p4c macros clash with user code

### ISSUE THREAD

**Issue by pudelkoM** [p4lang/p4c#2523]
User code including `lib/log.h`, either directly or through something like `ir/ir.h`, will also pull in a bunch of p4c internal macros like `ERROR` or `LOGN` into the global namespace: https://github.com/p4lang/p4c/blob/ebde76c05d14edbea62add9675b973eb0e6fc56c/lib/log.h#L128

These are very common names and bound to create naming conflicts in the user application. E.g. glog also defines `ERROR`.

Stratum currently work around this by `#undefine`ing the offending macros directly after the p4c includes. This is error prone and repetitive.

Common practice for libraries suggests prefixing library / internal macros with `P4C_` to prevent these clashes: [libuv](https://github.com/libuv/libuv/blob/43c74a6ee92a8e646201eef1fd056799cdccbfde/include/uv/errno.h#L23), [abseil](https://github.com/abseil/abseil-cpp/search?q=define&unscoped_q=define), [Boost](https://www.boost.org/doc/libs/master/libs/config/doc/html/boost_config/boost_macro_reference.html)

Unless there is a lot of external code that depends on these, this change could be a simple search and replace job.

**Comment by mbudiu-vmw** [comment]
I have no problems with this. Feel free to submit a pull request if you have it handy. 
Do you see other macros that would deserve this treatment?

**Comment by pudelkoM** [comment]
Good to hear. I'll prepare a PR with the changes. If I find other macros I'll put them up for discussion as well.
