### ISSUE TITLE
Should it be error if last switch label has no body?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#2527]
This is not currently mentioned in the P4_16 language spec version 1.2.1 that I can see, but it seems like it might be reasonable if it is an error if the last switch label has no body after it.  As of the latest p4c on 2020-Sep-04, no error is given for such source code.  I have not yet checked how such code behaves -- probably as if there were an empty body after the last switch label.

[last-switch-label-without-body.p4.txt](https://github.com/p4lang/p4c/files/5176598/last-switch-label-without-body.p4.txt)

**Comment by jfingerh** [comment]
This seems worth at least a brief discussion in the P4 LDWG, but note that this PR for generalizing the switch statement currently proposes that such a program would be a compile-time error.  If you want the last switch label to do nothing, you should explicitly but an empty body `{}` after the last label.

**Comment by jafingerhut** [comment]
I did a bit more investigation, and when there are one or more consecutive labels with no bodies at the end of a switch statement, the latest p4c as of 2020-Sep-04 removes those trailing labels with no following body in the front end pass called RemoveParserControlFlow.

Later in pass SwitchAddDefault, if there are actions of the table with no labels for them, a last switch case `default: { }` is added.

The combination of these two changes is to treat a switch statement with one or more labels at the end, with no following body, is to behave as if there were a final empty body `{}` after the last label.

If the LDWG decides such a source program is legal, that seems like the most reasonable meaning to assign to the program, but it also seems best to explicitly say so in the spec.

**Comment by mbudiu-vmw** [comment]
Please add this to the LDWG wiki

**Comment by jafingerhut** [comment]
Added to LDWG wiki, with same PR and status as "probably best discussed as part of the more general switch statement issue"

**Comment by jafingerhut** [comment]
I have changed the proposed PR for the spec here: https://github.com/p4lang/p4-spec/pull/887 to explicitly define the behavior of such switch statements to be what p4c implements today, since there did not seem to be any strong opinions among the language design work group members on whether it should be illegal or legal.

**Comment by mbudiu-vmw** [comment]
I will close this, since it is a question about the spec.
