### ISSUE TITLE
Is there a way to reduce frame size in P4-16?

### ISSUE THREAD

**Issue by vitor-l** [p4lang/p4c#2528]
Hello, I am new at P4 and I'm trying to reduce a packet with 1514 bytes to be a ACK packet (66 bytes). 

When I define the size of payload in the Ethernet header, packets stop arriving at the host. Is it possible to reduce frame size in P4?

**Comment by hesingh** [comment]
Please go to the P4 Slack channel: https://app.slack.com/client/T8ZMP3QR0/C8ZR5EN3F

Use the Search toolbar at the top and search for "payload".  You will see discussions related to your question.

**Comment by vitor-l** [comment]
I need a invitation to enter in the Slack channel.

**Comment by vitor-l** [comment]
I think the link is broken. I can't access that channel.

**Comment by hesingh** [comment]
Try this link:

https://p4-lang.slack.com

**Comment by vitor-l** [comment]
I can't login or create a account.

**Comment by jnfoster** [comment]
Try the link under the "Community" tab on the p4.org web page.

-N

**Comment by vitor-l** [comment]
@jnfoster, It worked. Thank you.
