### ISSUE TITLE
IR loop detected with minor mod to ebpf_model.p4

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#2541]
Sorry, this issue needs a minor modification to the ebf_model.p4 to be reproduced.  I have dumped FrontEndLast and MidEndLast passes but I don't see any obvious loop in the dumps.

This is the modification to ebpf_model.p4

```p4
diff --git a/backends/ebpf/p4include/ebpf_model.p4 b/backends/ebpf/p4include/ebpf_model.p4
index f9b4e1ef73708e8a918255298e187d7ea41e77cc..4904627509f4a24487ad705110ea3f5e99d81c0a 100644
--- a/backends/ebpf/p4include/ebpf_model.p4
+++ b/backends/ebpf/p4include/ebpf_model.p4
@@ -63,10 +63,10 @@ extern hash_table {
 
 /* architectural model for EBPF packet filter target architecture */
 
-parser parse<H>(packet_in packet, out H headers);
+parser parse<H, M>(packet_in packet, out H headers, out M metadata);
 control filter<H>(inout H headers, out bool accept);
 
-package ebpfFilter<H>(parse<H> prs,
-                      filter<H> filt);
+package ebpfFilter<H, M>(parse<H, M> prs,
+                         filter<H> filt);

```

Please see this repo (https://gitlab.com/hemant_mnkcg/p4c-temp) for all code changes to p4c and switch_ebpf.p4 to cause the issue. 

```bash
$ ./p4c-ebpf -o tmp.c ../testdata/p4_16_samples/switch_ebpf.p4
In file: /tmp/p4c-temp/ir/visitor.cpp:280
Compiler Bug: IR loop detected

``` 

The relevant line of code that causes the IR loop is with this code snippet from ebpf_switch.p4

```p4
state start
    {
        p.extract(headers.ethernet);
        meta.l4port = 0;
        transition select(headers.ethernet.etherType)
        {
            16w0x800 : ip;
            default : reject;
        }
    }
```

Soon as ` meta.l4port = 0;` is removed from the above program, the IR loop detected problem is not seen.

**Comment by hesingh** [comment]
For good measure, I did add metadata as a 3rd parameter to the filter control as well, thinking metadata is used later to the parser.  Still the error persists. This is why I didn't include the other changes to this issue.  However, if folks would like to see the filter control changes, they are included in the second commit to the repo.

https://gitlab.com/hemant_mnkcg/p4c-temp/-/commit/377ad66f2a617b389501db6c56521dd94280618b

I moved the same code in a v1model.p4 program and the issue is not seen.

**Comment by hesingh** [comment]
The P4 program used to test with p4c-ebpf is included below.

[switch_ebpf_p4.txt](https://github.com/p4lang/p4c/files/5210926/switch_ebpf_p4.txt)

The changed ebpf model is included below.

[ebpf_model_p4.txt](https://github.com/p4lang/p4c/files/5210939/ebpf_model_p4.txt)

Due to change in model, p4c/backends/ebpf/ebpfParser.cpp and ebpfControl.cpp need to change 2 parameters to 3. 

https://github.com/p4lang/p4c/blob/master/backends/ebpf/ebpfParser.cpp#L406

https://github.com/p4lang/p4c/blob/master/backends/ebpf/ebpfControl.cpp#L502

**Comment by hesingh** [comment]
I found the corresponding code for this issue to be different in the UBPF backend.  Using that code starting from this line:

https://github.com/p4lang/p4c/blob/master/backends/ubpf/ubpfParser.cpp#L435

fixes this issue.

We should create a common directory and put code common between EBPF and UPBF in that directory.

**Comment by mbudiu-vmw** [comment]
Yes, the ebpf code is wrong; you cannot call the "super" visitor on the same node.
Feel free to submit a fix.
It would be nice to deduplicate the code, but there is no one working on this.

**Comment by hesingh** [comment]
I will see what I can do and also try a first attempt at deduplicating the code - thanks.

**Comment by mbudiu-vmw** [comment]
Almost the entire code is duplicated. so there is no hope for that.
You should submit the fix as a separate PR.

**Comment by hesingh** [comment]
Regarding a fix for this issue, if the ebpf_model.p4 is not changed, I don't see a way how to reproduce this issue.  If a fix is checked into p4c for this issue, then the ebpf_model.p4 changes.   I think changing ebpf_model.p4 is fine because the change is akin to how ubpf is.  The ubpf backend includes a third parameter to parser and filt control as metadata. 

After ebpf_model.p4 changes, one will have to use a version check to support old vs. new API in P4 programs such as this ubpf version variable.

https://github.com/p4lang/p4c/blob/master/p4include/ubpf_model.p4#L29

Should we do this work?

**Comment by hesingh** [comment]
I used these diffs to an existing ebpf test and this PR's p4c changes fix the test.

```p4
diff --git a/testdata/p4_16_samples/calc-ebpf.p4 b/testdata/p4_16_samples/calc-ebpf.p4
index b90b002b7..4ab39a191 100644
--- a/testdata/p4_16_samples/calc-ebpf.p4
+++ b/testdata/p4_16_samples/calc-ebpf.p4
@@ -61,6 +61,7 @@ parser Parser(packet_in packet, out headers hdr)
 {
    state start {
         packet.extract(hdr.ethernet);
+        hdr.ethernet.srcAddr = 0;
         transition select(hdr.ethernet.etherType) {
             P4CALC_ETYPE : check_p4calc;
             default      : accept;

```
Test log below. 
```bash
$ ./p4c-ebpf -o tmp1.c ../testdata/p4_16_samples/calc-ebpf.p4
hemant@hemant-S5500BC:/tmp/p4c/build$ 

```

This PR looks good to be to check in code - thanks.
