### ISSUE TITLE
Control Inlining: Key declaration not found

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2542]
For the following program the compiler throws this error:
```
bugs/crash/ctrl_inline.p4(26): [--Werror=not-found] error: eth_type: declaration not found
            eth_type: exact @name("dummy_key") ;
            ^^^^^^^^*/
```
This does not look right. I think something is going wrong during inlining. This only happens with directionless parameters.

[ctrl_inline.p4.txt](https://github.com/p4lang/p4c/files/5217647/ctrl_inline.p4.txt)

**Comment by mbudiu-vmw** [comment]
This is actually the same bug as #1958
