### ISSUE TITLE
Some problems with function calls in struct initialization 

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2543]
I think one of the recent merges has unearthed some problems with structure initializations and function calls within them.
The following two programs throw errors that do not seem correct. 

[return_hdr_struct.p4.txt](https://github.com/p4lang/p4c/files/5217665/return_hdr_struct.p4.txt)
```
MidEnd_10_HandleNoMatch
MidEnd_11_SimplifyParsers
MidEnd_12_StrengthReduction
bugs/crash/return_hdr_struct.p4(17): [--Werror=type-error] error: AssignmentStatement: Cannot unify tuple_0 with ethernet_t
    return { { 1, 1, produce_val() }};
    ^^^^^^
bugs/crash/return_hdr_struct.p4(2)
header ethernet_t {
       ^^^^^^^^^^
```

[struct_function_call.p4.txt](https://github.com/p4lang/p4c/files/5217668/struct_function_call.p4.txt)
```
FrontEnd_47_InlineFunctions
P4::TypeChecking_0_ResolveReferences
P4::TypeChecking_1_TypeInference
SetHeaders_0_TypeChecking
In file: p4c/frontends/p4/typeMap.cpp:95
[31mCompiler Bug[0m: Could not find type for <StructExpression>(7655)
```

**Comment by mbudiu-vmw** [comment]
These are actually two different bugs.
