### ISSUE TITLE
Side-effect function call in table key

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2546]
I am not sure what the decision of allowing or forbidding function calls in keys and actions is currently. Depending on the outcome this issue may not matter but I recorded it just for completeness sake. 
The following program

```p4
control ingress(inout Headers h) {
    @noWarn("unused") @name(".NoAction") action NoAction_0() {
    }
    @noWarn("unused") @name(".NoAction") action NoAction_3() {
    }
    @name("ingress.simple_table_1") table simple_table {
        key = {
            48w1: exact @name("KOXpQP") ;
        }
        actions = {
            @defaultonly NoAction_0();
        }
        default_action = NoAction_0();
    }
    @name("ingress.simple_table_2") table simple_table_0 {
        key = {
            (simple_table.apply().hit ? 8w1 : 8w2): exact @name("key") ;
        }
        actions = {
            @defaultonly NoAction_3();
        }
        default_action = NoAction_3();
    }
    apply {
        if (simple_table_0.apply().hit) {
            h.eth_hdr.dst_addr = 48w1;
        }
    }
}
```
is transformed into

```p4
control ingress(inout Headers h) {
    @noWarn("unused") @name(".NoAction") action NoAction_0() {
    }
    @noWarn("unused") @name(".NoAction") action NoAction_3() {
    }
    bit<48> key_0;
    @name("ingress.simple_table_1") table simple_table {
        key = {
            key_0: exact @name("KOXpQP") ;
        }
        actions = {
            @defaultonly NoAction_0();
        }
        default_action = NoAction_0();
    }
    bit<8> key_1;
    @name("ingress.simple_table_2") table simple_table_0 {
        key = {
            key_1: exact @name("key") ;
        }
        actions = {
            @defaultonly NoAction_3();
        }
        default_action = NoAction_3();
    }
    apply {
        {
            key_1 = (simple_table.apply().hit ? 8w1 : 8w2);
            if (simple_table_0.apply().hit) {
                h.eth_hdr.dst_addr = 48w1;
            }
        }
    }
}
```
which causes `simple_table_1` to match on a key with undefined behavior. This call is side-effect free from what I can tell.

For what it is worth changing the key from `48w1` to something like `h.eth_hdr.eth_type` leads to a compiler bug. 

[nested_tbl_apply.p4.txt](https://github.com/p4lang/p4c/files/5217828/nested_tbl_apply.p4.txt)
[nested_tbl_apply_crash.p4.txt](https://github.com/p4lang/p4c/files/5217829/nested_tbl_apply_crash.p4.txt)

**Comment by anasyrmia** [comment]
I've implemented some changes in simplifyKey pass which solved the problem with undefined key behavior. With the changes, transformation in ingress looks like this:

control ingress(inout Headers h) {
	@noWarn("unused") @name(".NoAction") action NoAction_0() {
	}
	@noWarn("unused") @name(".NoAction") action NoAction_3() {
	}
	bit<48> key_0;
	@name("ingress.simple_table_1") table simple_table {
		key = {
			key_0: exact @name("KOXpQP") ;
		}
		actions = {
			@defaultonly NoAction_0();
		}
		default_action = NoAction_0();
	}
	bit<8> key_1;
	@name("ingress.simple_table_2") table simple_table_0 {
		key = {
			key_1: exact @name("key") ;
		}
		actions = {
			@defaultonly NoAction_3();
		}
		default_action = NoAction_3();
	}
	apply {
		{
			key_0 = 48w1;
			key_1 = (simple_table.apply().hit ? 8w1 : 8w2);
			if (simple_table_0.apply().hit) {
				h.eth_hdr.dst_addr = 48w1;
			}
		}	
	}
}

However, p4 output of this test has an error, because it has a table invoked from an action (code after MidEndLast is given below).
Is this expected behavior, or should we change the logic in SynthesizeActions pass?

After MidEndLast ingress looks like this:

control ingress(inout Headers h) {
	bit<48> key_0;
	bit<8> key_1;
	@noWarn("unused") @name(".NoAction") action NoAction_0() {
	}
	@noWarn("unused") @name(".NoAction") action NoAction_3() {
	}
	@name("ingress.simple_table_1") table simple_table {
		key = {
			key_0: exact @name("KOXpQP") ;
		}
		actions = {
			@defaultonly NoAction_0();
		}
		default_action = NoAction_0();
	}
	@name("ingress.simple_table_2") table simple_table_0 {
		key = {
			key_1: exact @name("key") ;
		}
		actions = {
			@defaultonly NoAction_3();
		}
		default_action = NoAction_3();
	}
	@hidden action nested_tbl_apply39() {
		h.eth_hdr.dst_addr = 48w1;
	}
	@hidden action nested_tbl_apply25() {
		key_0 = 48w1;	
		key_1 = (simple_table.apply().hit ? 8w1 : 8w2);
	}			^^^^^^^^^^^^^^^^^^^^
	@hidden table tbl_nested_tbl_apply25 {
		actions = {
			nested_tbl_apply25();
		}
		const default_action = nested_tbl_apply25();
	}
    @hidden table tbl_nested_tbl_apply39 {
        actions = {
            nested_tbl_apply39();
        }
        const default_action = nested_tbl_apply39();
    }
    apply {
        tbl_nested_tbl_apply25.apply();
        if (simple_table_0.apply().hit) {
            tbl_nested_tbl_apply39.apply();
        }
    }
}

[simplifyKey.cpp.txt](https://github.com/p4lang/p4c/files/5391973/simplifyKey.cpp.txt)
[simplifyKey.h.txt](https://github.com/p4lang/p4c/files/5391974/simplifyKey.h.txt)

**Comment by jafingerhut** [comment]
Out of curiosity, what happens if in the apply block of a control, you have an assignment like this one (and define a table with that name earlier):
```
bit<8> key_1 = (simple_table.apply().hit ? 8w1 : 8w2);
```

I do not know for sure, but I believe it is standard practice for p4c to transform assignment statements that are directly in an apply block of a control, into a 'dummy table' that executes a new synthesized action that is the const default_action of that table, and the table has no key so will always miss and execute that default action.

That transformation is at odds with assignments like the one above that have `simple_table.apply().hit` inside of them, since the P4_16 spec and p4c do not allow table apply() calls within actions.

**Comment by jafingerhut** [comment]
One could imagine p4c taking assignments that appear in a control apply block that contain `some_table.apply().hit` or `some_table.apply().miss` in them, and turning them into `if` statements, e.g. like so:

```
// original code
bit<8> foo = (table1.apply().hit ? (table2.apply().miss ? 1 : 2) : 3);
```
could be transformed into:
```
// transformed code, generated mechanically by p4c in some front- or mid-end pass, before dummy tables are synthesized
bool tmp1;
if (table1.apply().hit) {
    tmp1 = true;
} else {
    tmp1 = false;
}
bool tmp2;
if (table2.apply().miss) {
    tmp2 = true;
} else {
    tmp2 = false;
}
bit<8> foo = (tmp1 ? (tmp2 ? 1 : 2) : 3);
```

**Comment by mbudiu-vmw** [comment]
There is a pass in the compiler which is supposed to do this.

**Comment by jafingerhut** [comment]
OK, I don't know what the name of the pass that does what I suggest, but let's call it "X".

There is another pass "Y" (either already existing, or proposed in some PR) that is moving expressions from within a table's `key` table property value to an assignment just before an `apply()` call on that table.

I could be missing some cases, but it seems like perhaps pass "Y" should be run before pass "X", and then it will handle code like that in the original comment.

**Comment by mbudiu-vmw** [comment]
The pass is called TableHit: https://github.com/p4lang/p4c/blob/master/midend/tableHit.h
