### ISSUE TITLE
UBPF fails examples P4 program

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#2554]
I picked the first example in p4c/backends/ubpf/examples/gtp.p4.  I am using latest p4c downloaded today.  Even though gtp.p4 includes a `#define UBPF_MODEL_VERSION 20200304` before including 'ubpf_model.p4`, the P4 program fails to compile.

```bash
$ ./p4c-ubpf -o tmp.c ../backends/ubpf/examples/gtp.p4
error: Expected parser to have exactly 4 parameters
hemant@hemant-S5500BC:/tmp/p4c/build$ 
```

Since the older UBPF model version is being used by gtp.p4, I expected p4c-upbf to accept 3 parameters in parser.

**Comment by osinstom** [comment]
@hesingh I'll fix it soon.
