### ISSUE TITLE
Question: How to swap P4 Program internally in p4c?

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#2563]
I am using v1model.p4 in a p4-16 program.

I wrote a new midend pass in p4c.  The pass changes few APIs and removes a data structure from v1model.p4.  After the pass is run I dumped the IR and the dump looks as expected - the APIs have changed and a data structure is removed.

However, the way p4c internal code is organized, each of midend and bmv2 backend runs `program->apply()` [here ](https://github.com/p4lang/p4c/blob/master/backends/bmv2/common/midend.h#L67) and [here ](https://github.com/p4lang/p4c/blob/master/backends/bmv2/simple_switch/simpleSwitch.cpp#L1106) and, during testing, end up reading `p4c/build/p4include/v1model.p4` causing an error because the removed data structure declaration is not found. 

Even, when I manually edit `p4c/build/p4include/v1model.p4` to change APIs and remove a struct, the test fails reading my P4 program, say, foo.p4, because foo.p4 is the original program with no change in API or a data struct removed.

Since the MidEndLast IR looks good, is there a way to propagate this IR to the backend and avoid reading old P4 files?

**Comment by mbudiu-vmw** [comment]
I don't understand what you are trying to do. Which test fails? You should expect our tests to fail if you do not respect the invariants promised by our backends. If you have your own custom tests it is difficult to judge without understanding what they do.

v1model is read by the compiler exactly once; in fact, it is read by the preprocessor and "inlined" in the source before the compiler starts. The toP4 pass has a "hack" which inserts back an "#include <v1model>" to avoid dumping the whole program, but this hack is in fact buggy; see for example https://github.com/p4lang/p4c/issues/646 (but there is really no general solution to this problem). The pass has an option to not dump `#include` directives, but that is not exposed through command-line options,

**Comment by hesingh** [comment]
Sorry for not being clear.  I have a new p4c, say, p4c-bm2-foo which I use to test my new midend pass.

`$./p4c-bm2-foo --std p4-16 ../testdata/p4_16_samples/test.p4`

In the midend pass, I have merged standard_metadata_t into another struct and removed standard_metadata_t from IR. 
 
When I run the above test, I get the error below.  Of course, my new midend pass is run before the error is emitting because the data struct has been removed by the pass. 

```
/home/hemant/p4c/build/p4include/v1model.p4(720): [--Werror=not-found] error: standard_metadata_t: declaration not found 0
                    inout standard_metadata_t standard_metadata);
                          ^^^^^^^^^^^^^^^^^^^
```

There are many p4-16 programs out there using v1model.p4.  Its cumbersome to change each program to a new v2model.p4 for my use case.  I would rather changed the program's IR in a midend pass.

Thanks for the note about `toP4`.  Let me change toP4 and also change the P4 program in the IR in my midend pass.  I do prefer to do the work internally in the compiler.

**Comment by hesingh** [comment]
This is why I was scratching me head because I know the pre-processor inlines any include file before the compiler starts.   So, why does any backend p4c internal reads the include file again?

I made this change to toP4.cpp, but still I see the error I have shown above.

```c
diff --git a/frontends/p4/toP4/toP4.cpp b/frontends/p4/toP4/toP4.cpp
index 57742c939..a8332800f 100644
--- a/frontends/p4/toP4/toP4.cpp
+++ b/frontends/p4/toP4/toP4.cpp
@@ -164,7 +164,7 @@ bool ToP4::preorder(const IR::P4Program* program) {
              * that would create a P4-16 file that tries to include a P4-14 header.  Unless we
              * want to allow converting headers independently (is that even possible?).  For now
              * we ignore mainFile and don't emit #includes for any non-system header */
-
+#if 0
             if (includesEmitted.find(sourceFile) == includesEmitted.end()) {
                 if (sourceFile.startsWith(p4includePath)) {
                     const char *p = sourceFile.c_str() + strlen(p4includePath);
@@ -183,6 +183,7 @@ bool ToP4::preorder(const IR::P4Program* program) {
                 }
                 includesEmitted.emplace(sourceFile);
             }
+#endif
             first = false;
             continue;
         }
```

**Comment by mbudiu-vmw** [comment]
No pass reads any file, the files are only read by the parser; this only happens if you dump source and reload.

**Comment by hesingh** [comment]
> No pass reads any file, the files are only read by the parser; this only happens if you dump source and reload.

Ah, you are correct.  Sorry, the error refers to the line of code.

`/home/hemant/p4c/build/p4include/v1model.p4(720):  [--Werror=not-found] error: standard_metadata_t: declaration not found`

Without changing toP4.cpp and using only my new midend pass, the MidEndLast IR dump is correct proving the P4 program has also changed properly.  I have attached the dump. 

[MidEndLast-dump.txt](https://github.com/p4lang/p4c/files/5270267/MidEndLast-dump.txt)

In the dump see that no `standard_metadata_t` exists.  Further see the API for prs, ingress, and egress do not include the standard_metadata_t parameter.

So why does this line of code cause the declaration not found error? In MidEndLast IR no `standard_metadata_t` exists.  So what IR was read and  `standard_metadata_t` was found?

https://github.com/p4lang/p4c/blob/master/backends/bmv2/common/midend.h#L67

**Comment by mbudiu-vmw** [comment]
You should run the code under a debugger and see who is looking for this declaration.

**Comment by hesingh** [comment]
Thanks @mbudiu-vmw  for all your help!

I debugged more and found the root case.  The definitions in v1model.p4 were missed to be changed for API in the IR and caused the error.  I fixed the issue.
