### ISSUE TITLE
where is the define of convert_to ?

### ISSUE THREAD

**Issue by tommychen2k** [p4lang/p4c#2612]
in bmv2stf.py have a function :

  def convert_packet_bin2hexstr(pkt_bin):
      return pkt_bin.convert_to(Raw).load.hex().upper()

while I run make chcek, always have exception error due to "convert_to"
where is the define of convert_to ?

**Comment by hesingh** [comment]
This is Python code, so either the definition is in python or Scapy which the Python code uses.  Scapy defines convert_to().  

See  https://github.com/secdev/scapy/search?q=convert_to

**Comment by tommychen2k** [comment]
Thanks.

I update scapy version from 2.4.0 to 2.4.4.dev179 ,  there are no error about convert_to now.
stiil have 8 failed. i will check that later.
