### ISSUE TITLE
Add libtoolize before autoreconf -i in bootstrap.sh

### ISSUE THREAD

**Issue by junghongkao** [p4lang/p4c#262]
Such that it can avoid the following error
Running autoconf/configure tools
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/local/bin/automake line 3936.
Makefile.am:35: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:35:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:35:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:35:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:35:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

**Comment by junghongkao** [comment]
Seth,

My development environment is ubuntu 16.04 with

jim@onie-server:~/sdb/p4c$ autoreconf -V
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html
>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
jim@onie-server:~/sdb/p4c$ uname -a
Linux onie-server 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC
2017 x86_64 x86_64 x86_64 GNU/Linux

Yes, LT_INIT os in configure.ac The issue shall be due to aclocal's search
path in my system which can be correct through libtoolize. This could add
additional coverage for some development environment.

Jim

**Comment by sethfowler** [comment]
Seems reasonable. Could you please submit a PR?

Note that `libtoolize` is known as `glibtoolize` on macOS, so you'll need to handle that case.

**Comment by junghongkao** [comment]
Seth,

Can you review the PR I have submitted ?

Jim

**Comment by ChrisDodd** [comment]
You need to make the pull request into p4lang/p4c:master
