### ISSUE TITLE
SimplifyDefUse doesn't remove redundant method calls

### ISSUE THREAD

**Issue by dbrajovic-syrmia** [p4lang/p4c#2628]
Unassigned (duplicate) method calls are not removed during this pass. For example, 
```
        header hdr {
             bit<32> a;
        }

        hdr h;
        // ...
        h.isValid();
        h.isValid();
        h.isValid();
```
All three `isValid()` statements are preserved after the pass. Assigning them to a variable only strips them of the lhs, turning the assignment into a method call statement.
[simplify_method_calls.txt](https://github.com/p4lang/p4c/files/5658058/simplify_method_calls.txt)

**Comment by jafingerhut** [comment]
I verified that the latest p4c as of 2022-Jan-04 has output from the SimplifyDefUse pass that has only one setInvalid call, not a sequence of several identical ones.  Closing this issue.
