### ISSUE TITLE
Could not infer a type for unused type parameter

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#2630]
This issue is described in this PR: https://github.com/p4lang/p4c/pull/2441

Unfortunately, we would need to a solution to avoid the aforementioned issue for all our customers. It is going to be a lot of support overhead to ask all customers to update their P4 program with explicit 'dont care' type.

```
control C<H>(inout H h);
package Pipeline<H>(C<H> c);
package Switch<H0, H1>(Pipeline<H0> p0, @optional Pipeline<H1> p1);


struct header_t {
}
control MyC(inout header_t h) {
    apply {}
}

Pipeline(MyC()) pipe;
Switch(pipe) main;
```

The above sample program gives this error when comping with p4test.

```
$>./p4test sample.p4
sample.p4(13): [--Werror=type-error] error: main: could not infer a type for variable H1
Switch(pipe) main;
             ^^^^
sample.p4(3)
package Switch<H0, H1>(Pipeline<H0> p0, @optional Pipeline<H1> p1);
                   ^^
```

If inferring 'dont care' type for unused type parameter is difficult, can we allow overloading package definition? 

```
package Switch<H0, H1>(Pipeline<H0> p0);
package Switch<H0, H1>(Pipeline<H0> p0, Pipeline<H1> p1);
```

**Comment by mbudiu-vmw** [comment]
This https://github.com/p4lang/p4c/pull/2494 was supposed to fix this issue.
