### ISSUE TITLE
Different resolveReference behavior with pragma that are registered and not registered.

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#2660]
I have a small example program that compiles fine with p4-test
```
control a() {
    @anno(bar)
    table foo {
        key = {}
        actions = {}
    }
    action bar () {}
    apply {
        foo.apply();
        bar();
    }
}
```

but the following is not.
```
control a() {
    @match(bar)
    table foo {
        key = {}
        actions = {}
    }
    action bar () {}
    apply {
        foo.apply();
        bar();
    }
}
```

The only difference is @match is registered as a pragma that takes in expression as argument.
```
annotation.p4(20): [--Werror=not-found] error: bar: declaration not found
    @match(bar)
           ^^^
```

Is this expected, or maybe there is an implementation issue with pragma parsing?

**Comment by mbudiu-vmw** [comment]
Are these two swapped?
In P4 the declaration order matters. When you resolve a symbol it is always resolved to a declaration that precedes it.
So bar must be declared before it's used.

**Comment by hanw** [comment]
I have came across some cases in the past that the declaration order rule on annotations is inconvenient/non-intuitive to p4 programmer. Is it possible loose the rule just for annotation? The rule makes sense for other declarations, but annotations can perhaps be evaluated last after everything else.

**Comment by hanw** [comment]
Regardless of whether the declaration order rule is in place. It is still puzzling that the first program compiles fine and the second does not.

**Comment by jnfoster** [comment]
I think the reason is as follows

* `@match(...)` is an official annotation that takes an expression, which
is expected to be a match-kind. So `bar` is treated as an expression. See
here:
https://p4.org/p4-spec/docs/P4-16-v1.2.1.html#sec-value-set-annotations

* @annot(...) is not an official annotation. So it is parsed and processed
as a free-form and uninterpreted string.

-N

**Comment by hanw** [comment]
That makes sense. I used `@match` as an example, but the same issue applies to all annotations that have expression as an argument. Does it make sense to have a different rule on declaration order for annotations? I cannot think of any reason against it.

**Comment by hanw** [comment]
Just for the record, the following code should work for my use case. 

```
control a() {
    table foo {
        key = {}
        actions = {}
    }
    @match(foo)
    action bar () {}
    apply {
        foo.apply();
        bar();
    }
}
```

Thanks for the comment.
