### ISSUE TITLE
does p4c-dpdk support lpm match method?

### ISSUE THREAD

**Issue by sunbin21** [p4lang/p4c#2675]
though p4c-dpdk can compile lpm match something wrong had happened when I tried to import my spec into dpdk machine. that dpdk machine shows that a table configuration error happeced. my p4 code and dpdk error show as follow:
```
    table ipv4_lpm {
        key = {
            hdr.ipv4.dstAddr: lpm;
        }
        actions = {
            ipv4_forward;
            ingress_drop(ostd);//
            NoAction;
        }
        size = 1024;
        default_action = NoAction();
    }
```
```
table ipv4_lpm_0 {
	key {
		h.ipv4.dstAddr lpm
	}
	actions {
		ipv4_forward
		ingress_drop
		NoAction_0
	}
	default_action NoAction_0 args none 
	size 0x400
}
```
![image](https://user-images.githubusercontent.com/52184358/108736884-fc047380-756c-11eb-9bb9-05f7f9466aad.png)

**Comment by jnfoster** [comment]
Please enter the error as text (ideally typeset in a <pre> code block), not an image. In particular, the image is illegible.

**Comment by hanw** [comment]
This should be a question for dpdk backend. Support for wildcard match was submitted recently (not yet upstreamed), and support for lpm match is on the todo list. You can subscribe to dpdk-dev email list to track the changes.

**Comment by jafingerhut** [comment]
Closing this issue, since it seems the question was answered (whether or not the feature has been implemented yet).
