### ISSUE TITLE
Split CompilerOptions into frontend and parser options

### ISSUE THREAD

**Issue by robotrobo** [p4lang/p4c#2679]
Hello,
a lot of our tools are implemented using p4c's infrastructure. This includes the CompilerOptions class. However, we only use the IR parser, not the front end. And the default options parser has too many options we do not need. Would it make sense to split the CompilerOptions into options only required for the parser and front end options, which are derived from the parser options? We can make a pull request for that.
@fruffy

**Comment by mbudiu-vmw** [comment]
Sure, why not? If you make a good argument this could be done.
