### ISSUE TITLE
p4c-dpdk unsupported select expression(s)

### ISSUE THREAD

**Issue by egerpon** [p4lang/p4c#2692]
ethmola@dpdk1:~/p4ci$ ./bin/p4c -b dpdk-psa ~/t4p4s20201115/examples/local/EPG-2020/transport.p4

Stops with this error:

In file: /home/ethmola/p4c/backends/dpdk/dpdkProgram.cpp:198
Compiler Bug: /home/ethmola/t4p4s20201115/examples/local/EPG-2020/transport.p4(54): Unsupported select expression {h.arp.htype, h.arp.ptype};
        transition select(hdr.arp.htype, hdr.arp.ptype) {
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The P4 code piece that causes this:

    state parse_arp {
        pkt.extract(hdr.arp);
        transition select(hdr.arp.htype, hdr.arp.ptype) {
            (ARP_HTYPE_ETHERNET, ARP_PTYPE_IPV4) : parse_arp2;
            default : accept;
        }
    }

**Comment by mbudiu-vmw** [comment]
I believe that tuples are not yet supported for select arguments.
I will mark this as a bug.
We could implement this by concatenating the elements of the tuple into a wide value.

**Comment by hanw** [comment]
I'm not aware of any limitation in dpdk. Do you mean a mid-end pass for the dpdk backend or as a generic pass for all backends?

**Comment by mbudiu-vmw** [comment]
Yes, this could be done in a generic way. I believe we have something similar for bmv2, which requires a specific concatenation, but the general-purpose one should be simpler.

**Comment by mbudiu-vmw** [comment]
Although I have to think a bit about default in a tuple. That requires a ternary match.

**Comment by jafingerhut** [comment]
One could imagine a P4 target restricting select expressions to be completely exact match in every element of a tuple, or default/_ in every element of a tuple, which simplifies the implementation.

Several P4 implementations I am aware of allow default or arbitrary ternary matching on every element of a tuple in select expressions, but that does require a TCAM for deterministic high speed performance in the implementation, independent of the number of transitions.

**Comment by mbudiu-vmw** [comment]
I assume in dpdk we'll do this using a cascade of ifs

**Comment by hanw** [comment]
In dpdk, this is implemented a sequence of jmp instructions, for example.

```
        transition select(hdr.ipv4.protocol) {
            ( ip_proto_t.ICMP ) : parse_icmp;
            ( ip_proto_t.IGMP ) : parse_igmp;
            ( ip_proto_t.TCP  ) : parse_tcp;
            ( ip_proto_t.UDP  ) : parse_udp;
            default : accept;
        }
```
is compiled to.
```
        jmpeq MYIP_PARSE_ICMP h.ipv4.protocol 0x1
        jmpeq MYIP_PARSE_IGMP h.ipv4.protocol 0x2
        jmpeq MYIP_PARSE_TCP h.ipv4.protocol 0x6
        jmpeq MYIP_PARSE_UDP h.ipv4.protocol 0x11
        jmp MYIP_ACCEPT
```

**Comment by hanw** [comment]
We can probably restrict the label to be exact match as Andy suggested.

**Comment by mbudiu-vmw** [comment]
There is an easy way to implement this then, but it won't be midend.
For labels that are "complete" just concatenate and compare the concatenated values.
For labels that have some "default" fields, do not concatenate the parts that correspond to "default"

**Comment by mbudiu-vmw** [comment]
```
transition select(a, b) {
  (x, y): p1;
  (default, z): p2;
  }
```

Translates to:
 
jmpeq P1 (a++b) (x ++ y)
jmpeq P2 b z

**Comment by jafingerhut** [comment]
If DPDK back end has bitwise AND operator, then arbitrary value/mask shouldn't be a problem, either.

**Comment by hanw** [comment]
I can confirm with Cristian if dpdk datapath supports concat operator. I doubt it does. In any case, it would be better to evaluate the concat operation at compile time versus runtime in dpdk.

**Comment by mbudiu-vmw** [comment]
This will work for x++y, which are supposed to be constants, but for a++b it has to be done at runtime.
We have a pass rewriting concat into << and |, it's used in the bmv2 backend.
But this would have to be done before generating the code.

**Comment by jafingerhut** [comment]
If concat is not available, but logical && of expressions is, then `jmpeq P1 (a == x) && (b == y)` might be a better fit.

**Comment by hesingh** [comment]
Please note I have filed the same issue against the EBPF backend.

https://github.com/p4lang/p4c/issues/2791

It would be good to change midend so that both dpdk and EBPF backend benefit - thanks.

**Comment by hesingh** [comment]
Note the cfp code #egerpon released uses wildcard with tuples.

```c
state parse_gtpu {
	pkt.extract(hdr.gtp);
	transition select(hdr.gtp.eFlag, hdr.gtp.sFlag, hdr.gtp.pnFlag) {
            (_, _, _) : parse_gtpopt;
	    (_, 1, _) : parse_gtpopt;
	    (_, _, 1) : parse_gtpopt;
	    default   : parse_ue_hdr;
	}
    }


```

**Comment by usha1830** [comment]
Tuple expressions are now supported for DPDK backend.
See PR https://github.com/p4lang/p4c/pull/2836
