### ISSUE TITLE
The BMv2 back-end cannot set default_actions for tables

### ISSUE THREAD

**Issue by mbudiu-bfn** [p4lang/p4c#27]
The problem is that BMv2 does not yet support setting the default actions.

**Comment by mbudiu-vmw** [comment]
@antoninbas @sethfowler 
Is this issue still an issue?

**Comment by antoninbas** [comment]
yes tables with action profiles still don't have default actions in bmv2, for now they still use default members / groups.

**Comment by mbudiu-vmw** [comment]
It looks like this is by design, so I am closing this issue.
