### ISSUE TITLE
[bug/enhancement] boolean fields

### ISSUE THREAD

**Issue by smolkaj** [p4lang/p4c#272]
Currently, the compiler does not accept boolean metadata, and raises errors such as this one:
```
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  COMPILER BUG: ../frontends/p4/typeChecking/typeChecker.h:100
./includes/meta.p4(90): Field bool urpf_hit of header l3_metadata_t cannot have type bool
    bool urpf_hit;
         ^^^^^^^^

Aborted (core dumped)
```
This seems like an arbitrary (and in practice, very annoying) restriction. Are there deeper reasons for this or is it just something that hasn't been implemented yet?
Boolean metadata is extremely common in switch.p4. It would be convenient to use `bool` rather than `bit<1>` for this purpose.

**Comment by mbudiu-vmw** [comment]
There is no "metadata" in P4-16 really; there are just structs, and they can have boolean fields. The spec forbids boolean fields in headers, and the error message indicates that this is a header. However, the error is a BUG, so it looks like this header was somehow synthesized by the compiler internally. Can you post a some code to reproduce this error, please?

**Comment by mbudiu-vmw** [comment]
This is actually easy to reproduce; it happens for a header with a bool field.
This is a bug; the compiler should just emit an error.
However, the question is whether we should allow boolean fields in headers. Most protocol specifications do not use booleans; headers are always expressed in bitstrings. So this issue should probably be filed first with the P4-16 spec.

**Comment by smolkaj** [comment]
@mbudiu-vmw: I opened an issue in p4-spec as you suggested, see p4lang/p4-spec#123. I cannot think of any good reasons to disallow booleans in header fields, but let's discuss there.

**Comment by smolkaj** [comment]
@mbudiu-vmw: Actually, it seems that structs cannot have boolean fields. I get the error
```
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  COMPILER BUG: ../backends/bmv2/jsonconverter.cpp:2122
switch.2.p4(6): bool: unexpected type for struct some_meta_t {
  bool flag; }.flag
struct some_meta_t { bool flag; }
       ^^^^^^^^^^^
switch.2.p4(6)
struct some_meta_t { bool flag; }
```
when trying to compile
```C
#include <core.p4>
#include <v1model.p4>

typedef standard_metadata_t std_meta_t;

struct some_meta_t { bool flag; }

struct H { }

struct M { some_meta_t some_meta; }

control DeparserI(packet_out packet, in H hdr) {
    apply { }
}

parser ParserI(packet_in pk, out H hdr, inout M meta, inout std_meta_t std_meta) {
    state start { transition accept; }
}

control VerifyChecksumI(in H hdr, inout M meta) {
    apply { }
}

control ComputeChecksumI(inout H hdr, inout M meta) {
    apply { }
}

control IngressI(inout H hdr, inout M meta, inout std_meta_t std_meta) {
    apply { }
}

control EgressI(inout H hdr, inout M meta, inout std_meta_t std_meta) {
    apply { }
}

V1Switch(ParserI(), VerifyChecksumI(), IngressI(), EgressI(), ComputeChecksumI(), DeparserI()) main;
```

**Comment by smolkaj** [comment]
Great, this is fixed 👍
