### ISSUE TITLE
Annotations are lost when a ControlBlock or ParserBlock is inlined

### ISSUE THREAD

**Issue by grg** [p4lang/p4c#2727]
@mbudiu-vmw: You wrote most of the code below:
https://github.com/p4lang/p4c/blob/ca4915d41f7cd5329b49c4235b906b859c0620cd/frontends/p4/inlining.cpp#L437-L455

Annotations on the block's instanceType are dropped during inlining since they're not copied into the parent's instanceType. Is this intentional?

**Comment by mbudiu-vmw** [comment]
Actually, this is an issue. Please add an example and mark it as bug.

**Comment by grg** [comment]
Here's a sample program that demonstrates the issue for both a ControlBlock and a ParserBlock: [issue-2727.p4.txt](https://github.com/p4lang/p4c/files/6266675/issue-2727.p4.txt)
(Please remove the .txt extension. It wouldn't allow me to directly attach a .p4 file :( )

One question that needs to be addressed is _when_ an annotation should be preserved or not. For example, which annotations should we keep when inlining the following parser block?
```
@my_anno_1                                                                                                                                                                            
@name("inner_parser")                                                                                                                                                                 
parser InnerParser(...) { ... }
```
It's probably a mistake to copy the `@name(...)` annotation to the parent ParserBlock, but we might reasonably expect `@my_anno_1` to be preserved.

Run p4c as follows to see the problem in the transformed p4 code. All annotations on the inlined blocks are discarded.
```
p4c --top4 FrontEndLast issue-2727.p4
```
