### ISSUE TITLE
Determine whether DPDK back end output for test program psa-isvalid.p4 is correct

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#2729]
It has no conditional jump instruction testing the value of the PSA drop field in it, which looks suspicious.  If the back end is truly optimizing that away somehow, perhaps this is correct, but seems worth investigating a bit to see if there is a bug here.

**Comment by mbudiu-vmw** [comment]
Do we have a diagnostic on this issue? Does it signal a bug or not?

**Comment by jafingerhut** [comment]
I have checked this output file from the DPDK back end for another PSA program that is tested on the DPDK back end, and might drop the packet, called psa-unicast-or-drop-bmv2.p4, here: https://github.com/p4lang/p4c/blob/main/testdata/p4_16_samples/psa-unicast-or-drop-bmv2.p4

Here is the expected .spec output checked into the p4_16_samples_output directory for that program: https://github.com/p4lang/p4c/blob/main/testdata/p4_16_samples_outputs/psa-unicast-or-drop-bmv2.p4.spec#L72

It appears that the DPDK back end variable named m.psa_ingress_output_metadata_drop is used to hold the ingress drop decision for the packet.  Everything looks correct, assuming 0 encodes the value "false" and 1 encodes the value "true", except for one thing, namely that the initial value should be 1 (true) according to the PSA specification (search for "drop" in this section https://p4.org/p4-spec/docs/PSA-v1.1.0.html#sec-psa-supported-metadata-types).

**Comment by jafingerhut** [comment]
@usha1830 Is this something you are tracking elsewhere?  It appears to still be a bug in the DPDK back end.  For example, see this test program, with empty ingress code: https://github.com/p4lang/p4c/blob/main/testdata/p4_16_samples/psa-drop-all-bmv2.p4#L80-L91

and the expected spec output file, which appears never to drop any packets, if I understand the spec file correctly: https://github.com/p4lang/p4c/blob/main/testdata/p4_16_samples_outputs/psa-drop-all-bmv2.p4.spec#L51-L63

It seems like this should be a straightforward fix in the DPDK back end, just by initializing drop to 1 instead of 0?

**Comment by usha1830** [comment]
Jump to label drop is always generated at the end of ingress deparser, whether or not any statement exist in the ingress block. Initializing with 1 and not changing anywhere in between might always end-up dropping the packet even when there are statements in ingress. I think we can instead set the value to 1 when the ingress block is empty?

I will assess further and confirm on this. Thanks!

**Comment by jfingerh** [comment]
FYI, the PSA specification requires that packets be dropped if the drop flag is not explicitly set to false during ingress.  The thing you say "might happen" is part of the specification, and should happen for any PSA implementation.  I can discuss why it is defined that way if you are curious, but it is defined that way.

**Comment by usha1830** [comment]
@jfingerh Thanks for clarifying on the specification side. 
I also confirmed with the dpdk target team here that the "drop" instruction only marks the packet for dropping and must be followed by "tx".
I will create a PR for this soon with these changes.
