### ISSUE TITLE
cpplint inconsistently enforcing blank line before public access modifier

### ISSUE THREAD

**Issue by grg** [p4lang/p4c#2732]
The code below shows a pair of class declarations with `public` access modifiers. Neither public modifier is preceded by a blank line and both pass cpplint. However, some changes I made as part of #2728 caused cpplint to flag an error for line 219 but not 238. The error reported was:
```
/p4c/frontends/p4/inlining.h:219:  "public:" should be preceded by a blank line  [whitespace/blank_line] [3]
```

https://github.com/p4lang/p4c/blob/84a39efcec0a973403314a84d21b254d7c5c1fc0/frontends/p4/inlining.h#L215-L240

**Comment by mbudiu-vmw** [comment]
I don't really want to understand cpplint bugs, and, frankly, this empty line does not improve code readability in any way. I expect no one will investigate this anomaly.

**Comment by fruffy** [comment]
cpplint has an odd rule defined here:
https://github.com/p4lang/p4c/blob/master/tools/cpplint.py#L4174
So if the class is smaller than 25 lines, they do not care.

**Comment by grg** [comment]
Ah, the 25 line rule would explain why the issue suddenly showed up. I added some commenting and that probably pushed it over the 25 line limit.

I'll close this issue since there's some rationale for the inconsistency in behavior.
