### ISSUE TITLE
Unable to compile PSA example

### ISSUE THREAD

**Issue by zyddnys** [p4lang/p4c#2753]
I was trying to compile PSA example found here https://github.com/p4lang/p4-spec/blob/main/p4-16/psa/examples/psa-example-incremental-checksum.p4
However it does not compile, output of `p4c-bm2-psa --std p4-16 psa-example-incremental-checksum.p4`:
```
psa-example-incremental-checksum.p4(191): [--Werror=unsupported] error: ck.clear: not supported within a deparser on this target
        ck.clear();
        ^^^^^^^^^^
psa-example-incremental-checksum.p4(192): [--Werror=unsupported] error: ck.add: not supported within a deparser on this target
        ck.add({
        ^
psa-example-incremental-checksum.p4(202): [--Werror=unsupported] error: AssignmentStatement: not supported within a deparser on this target
        hdr.ipv4.hdrChecksum = ck.get();
                             ^
psa-example-incremental-checksum.p4(209): [--Werror=unsupported] error: ck.clear: not supported within a deparser on this target
        ck.clear();
        ^^^^^^^^^^
psa-example-incremental-checksum.p4(211): [--Werror=unsupported] error: ck.subtract: not supported within a deparser on this target
        ck.subtract(hdr.tcp.checksum);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psa-example-incremental-checksum.p4(216): [--Werror=unsupported] error: ck.subtract: not supported within a deparser on this target
        ck.subtract(user_meta.fwd_metadata.old_srcAddr);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psa-example-incremental-checksum.p4(217): [--Werror=unsupported] error: ck.add: not supported within a deparser on this target
        ck.add(hdr.ipv4.srcAddr);
        ^^^^^^^^^^^^^^^^^^^^^^^^
psa-example-incremental-checksum.p4(218): [--Werror=unsupported] error: AssignmentStatement: not supported within a deparser on this target
        hdr.tcp.checksum = ck.get();
                         ^
```

**Comment by jafingerhut** [comment]
I get similar errors using the latest p4c-bm2-psa built from the latest source code in this repository.

There are two open source compilers for PSA under development now that I am aware of: p4c-dpdk and p4c-bm2-psa.  Neither of them are complete.  Both have bugs.  Both support only a fairly limited set of source program right now.  If you know anyone interested in helping make those implementations more complete (or you are such a person yourself), there is a PSA implementation status meeting every other Wednesday.   You should be able to search Google calendar for the "P4 Working groups" set of events, and make them visible on your Google Calendar if you want to know when, or join the p4-arch email list and watch for meeting announcements: https://lists.p4.org/list/p4-arch.lists.p4.org

**Comment by jafingerhut** [comment]
@zyddnys If you are still interested in compiling P4 programs written for the PSA architecture, I would recommend trying out the p4c-dpdk back end, which has a significantly more complete PSA implementation today (2022-Nov) than BMv2 does.  However, I have not checked whether the program you are trying to write is supported by p4c-dpdk yet.

**Comment by zyddnys** [comment]
Wow, looks a lot of progress were made in the past year, I will switch DPDK backend now. Closing this issue.
