### ISSUE TITLE
Are there any clear steps to impelent custom hash Algorithms besides CRC16, CRC32, XOR16?

### ISSUE THREAD

**Issue by gogamid** [p4lang/p4c#2764]
I want to have for example a simple custom hash function written in C++:

```
struct h1 {
  uint32_t operator()(const char *buf, size_t s) const {
    uint32_t hash = 27;
    
    return hash;
  }
};
```
Where should I input so that I can use it in Firewall example?
https://github.com/p4lang/tutorials/tree/master/exercises/firewall

**Comment by mbudiu-vmw** [comment]
I think that this question is rather related to the P4 simulator than to the compiler.
This is the repository of the P4 compiler.
https://github.com/p4lang/behavioral-model

**Comment by gogamid** [comment]
I will repost there, thank you
