### ISSUE TITLE
Visitor: apply vs visit

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2767]
I have a question about visitor usage. Currently, when an Inspector is used on a node for the first time, it always has to be called with `node->apply(visitor)`. Otherwise the Inspector crashes with a segmentation fault. This is because at https://github.com/p4lang/p4c/blob/main/ir/visitor.cpp#L281 `visited` is not initialized. In some cases however, I would just like to use `visitor->visit(node)` instead, without worrying about whether I have properly initialized the Inspector. I merely want to make use of the multiple dispatch feature.

Is there a way to safely initialize the Inspector without passing in a specific node or creating an entirely new visitor class? One workaround I use is to insert this check into the `apply_visitor` call:
```cpp
const IR::Node *Inspector::apply_visitor(const IR::Node *n, const char *name) {
    if (visited == nullptr) {
        visited = new visited_t();
    }
    if (ctxt) ctxt->child_name = name;
...
``` 
This works but it does not seem to be the right way to solve this.

**Comment by mbudiu-vmw** [comment]
I would recommend against changing the visitor code.
What is the difference between the effect you want from `visitor->visit(node)` and `node->apply(*visitor)`? Why isn't the latter doing the right thing?

**Comment by fruffy** [comment]
I have several utility functions which take a node and may called at any point in the visit process. For example, a function like
`gen_arch_block(Visitor *visitor, const IR::ConstructorCallExpression *cce) ` can be called multiple times - when applying the visitor for the first time or during a `visit` call.  Only when calling it for the first time we really need the `apply`. Within functions like these I would like to use `visit(node)` to resolve types, expressions etc. since `node->apply(*visitor)` seems to do more extra work compared to `visit`.

Another instance of this problem is when I have one visitor that uses a second, different visitor. I can not use `visit` for the second visitor either because, at runtime, we do not know where and when this visitor may be called for the first time.  So I have to generate a fresh instance every time, then call `apply` on the node. Or use `node->apply(*visitor)` everywhere.  That seems a little redundant since the only feature we really need is the multiple dispatch.

On that note, is it possible to define a new visitor, which returns a completely arbitrary type? Are there any example of this? I have a looked at the visitor class but was a little hesitant since it seems to have `Transform`, `Inspector`, etc as friend classes.

**Comment by mbudiu-vmw** [comment]
Don't worry about efficiency. Just go ahead and use a visitor, and allocate more than one if needed.
The compiler isn't really optimized for speed anyway.
Getting the visitors right was difficult, Chris fixed bugs even a few years after the initial framework was released.
