### ISSUE TITLE
The way of continuous "if" statements placement

### ISSUE THREAD

**Issue by jijinfanhua** [p4lang/p4c#2770]
I compiled the tutorial example [firewall](https://github.com/p4lang/tutorials/tree/master/exercises/firewall/solution), and _p4c_ generates json file. Judging statements are compiled to _"conditionals"_ as _"node_x"_ and tables are compiled to _"pipelines"_ as _"tables"_.
`
 if (direction == 0) {      
        if (hdr.tcp.syn == 1) {...} }
`
“direction == 0” is compiled as "node_10" and "hdr.tcp.syn == 1" is compiled as "node_11", so does compiler compile these two continuous nodes into one physical stage or two? Thanks.

**Comment by mbudiu-vmw** [comment]
It depends which backend you are using. This question makes most sense for a hardware target.


________________________________
From: jijinfanhua ***@***.***>
Sent: Tuesday, May 18, 2021 8:30:17 PM
To: p4lang/p4c ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [p4lang/p4c] The way of continuous "if" statements placement (#2770)


I compiled the tutorial example firewall<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fp4lang%2Ftutorials%2Ftree%2Fmaster%2Fexercises%2Ffirewall%2Fsolution&data=04%7C01%7Cmbudiu%40vmware.com%7C20618d2549a54a3630c108d91a766cb0%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637569918204300017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZLg4KfBfX9aN%2BYRs33MYME1%2FT%2B9iNpEVjbLIFTLEFtY%3D&reserved=0>, and p4c generates json file. Judging statements are compiled to "conditionals" as "node_x" and tables are compiled to "pipelines" as "tables".
if (direction == 0) { if (hdr.tcp.syn == 1) {...} }
“direction == 0” is compiled as "node_10" and "hdr.tcp.syn == 1" is compiled as "node_11", so does compiler compile these two continuous nodes into one physical stage or two? Thanks.

**Comment by jijinfanhua** [comment]
> It depends which backend you are using. This question makes most sense for a hardware target.
> […](#)
> ________________________________ From: jijinfanhua ***@***.***> Sent: Tuesday, May 18, 2021 8:30:17 PM To: p4lang/p4c ***@***.***> Cc: Subscribed ***@***.***> Subject: [p4lang/p4c] The way of continuous "if" statements placement (#2770) I compiled the tutorial example firewall<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fp4lang%2Ftutorials%2Ftree%2Fmaster%2Fexercises%2Ffirewall%2Fsolution&data=04%7C01%7Cmbudiu%40vmware.com%7C20618d2549a54a3630c108d91a766cb0%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637569918204300017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZLg4KfBfX9aN%2BYRs33MYME1%2FT%2B9iNpEVjbLIFTLEFtY%3D&reserved=0>, and p4c generates json file. Judging statements are compiled to "conditionals" as "node_x" and tables are compiled to "pipelines" as "tables". if (direction == 0) { if (hdr.tcp.syn == 1) {...} } “direction == 0” is compiled as "node_10" and "hdr.tcp.syn == 1" is compiled as "node_11", so does compiler compile these two continuous nodes into one physical stage or two? Thanks. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fp4lang%2Fp4c%2Fissues%2F2770&data=04%7C01%7Cmbudiu%40vmware.com%7C20618d2549a54a3630c108d91a766cb0%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637569918204300017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IkwoQ8RM612b4hGM%2Ff8izpvbKqq%2F5sjcD9ozSbGiAkc%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAET7TMRV2SMU3PHDUV5MF4DTOMWETANCNFSM45DXRZTQ&data=04%7C01%7Cmbudiu%40vmware.com%7C20618d2549a54a3630c108d91a766cb0%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637569918204310010%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=H7RlrXG5IEOcBJscasFlGhTzNDndgynTLrO5eV6R2M4%3D&reserved=0>.

We now use Barefoot Tofino P4 switch, PSA. Are there some references about the judgement statement placement? Thanks.

**Comment by mbudiu-vmw** [comment]
This question is the about the proprietary Tofino backend and this is not the right place for getting an answer, you should contact their tech support. I am pretty sure barefoot has some nice tools to visualize the layout of your code.

**Comment by jijinfanhua** [comment]
We now use Barefoot Tofino P4 switch, PSA. Are there some references about the judgement statement placement? Thanks.

**Comment by jijinfanhua** [comment]
Got it. Thank you.
