### ISSUE TITLE
Compiler does not give warnings on accessing fields of invalid headers

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#2784]

**Comment by jafingerhut** [comment]
I guess the intent is that fixing this issue would involve at least having the compiler catch cases where a header is "obviously" invalid when accessing one of its fields?  But that the compiler will not be able to guarantee it catches all such cases?

**Comment by mbudiu-vmw** [comment]
Yes, that's right.

**Comment by kostasyrmia** [comment]
Hello @mbudiu-vmw, are you currently working on this issue? If not, I would like to work on it.

**Comment by mbudiu-vmw** [comment]
I am not, but this is not so easy. It's a form  of def-use analysis.
