### ISSUE TITLE
There are no end-to-end tests for the EBPF back-end

### ISSUE THREAD

**Issue by mbudiu-bfn** [p4lang/p4c#28]

**Comment by nchallak** [comment]
As the backend now supports only programs written using ebpf_model.p4, it would be useful to include an example that is written using this model.

**Comment by mbudiu-vmw** [comment]
There are three simple examples in testdata/p4_16_samples, they all end in _ebpf.p4. However, there is no test to ensure that the output produced (a C file) is correct.

**Comment by nchallak** [comment]
Thanks. I will take a look at it.
