### ISSUE TITLE
EBPF/UBPF runtime?

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#2802]
@fruffy I have used the ebpf map to support a p4 register.  The code compiles and links fine.  I want to know what ebpf/ubpf runtime lib to I bundle with my C app for ubpf_map_lookup(), etc. to work at runtime?  I have seen the runtime directory in ebpf and ubpf, but not sure what to do.

**Comment by hesingh** [comment]
Even if I get steps for EBPF runtime, I can figure out what do to for UBPF.

**Comment by fruffy** [comment]
I have not worked with the eBPF code for a while, so I am not sure if can help. The runtime is compiled with the generated C code [here](https://github.com/p4lang/p4c/blob/main/backends/ebpf/targets/target.py#L76). But I am not sure what you want to do, maybe code examples can help.

**Comment by hesingh** [comment]
ok, no worries.

Fro ebpf [notes](https://github.com/p4lang/p4c/tree/main/backends/ebpf) I found

`python3 backends/ebpf/build_libbpf`

and used it.  In the generated src code, I could build a static libbpf.a.
