### ISSUE TITLE
DPDK backend can generate incorrect intermediate programs

### ISSUE THREAD

**Issue by mihaibudiu** [p4lang/p4c#2808]
The culprit is the function `ConvertBinaryOperationTo2Params::postorder(IR::AssignmentStatement *a)`
The bug is in handling comparison operations. These consume integers, but produce booleans.
The expansion in this function ignores the type and reuses the same temporary variable.
Unfortunately I don't have yet a small reproduction, since this happened while fixing other bugs in the compiler.

**Comment by mbudiu-vmw** [comment]
In fact there are several programs marked as xfail for the dpdk backend with the error "AssignmentStatement", so I suspect these trigger the same bug.

**Comment by jafingerhut** [comment]
@usha1830 @mbudiu-vmw Is this still a bug in the DPDK back end today?

**Comment by usha1830** [comment]
I  presume this is fixed.
We don't have any tests failing with the "AssignmentStatement" error. 
I also see the function `ConvertBinaryOperationTo2Params::postorder(IR::AssignmentStatement *a)` does not handle Relational operations 
https://github.com/p4lang/p4c/blob/main/backends/dpdk/dpdkArch.cpp#L1037

**Comment by fruffy** [comment]
Can we close this issue?
