### ISSUE TITLE
Unsupported p4-14 operations

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#2811]
There are a couple of p4-14 tests which use operations that the compiler warns are unsupported.
Currently the tests pass, but this is by luck:

```
./bmv2/testdata/p4_14_samples/p414-special-ops-3-bmv2.p4.test
./bmv2/testdata/p4_14_samples/p414-special-ops.p4.test
```

Does anyone object to marking these as xfail? I have a PR in preparation fixing another bug which breaks these tests.

**Comment by jafingerhut** [comment]
If we mark these as XFAIL, then we may as well just deprecate v1model while we are at it.

**Comment by jafingerhut** [comment]
Actually, I should amend that.  We should deprecate at least the recirculate, resubmit, and clone operations of v1model, when they take metadata to be preserved.  I guess the warnings we already have effectively do that.
