### ISSUE TITLE
The Dockerhub image is out of date

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2819]
Is this docker image still maintained? 
https://hub.docker.com/r/p4lang/p4c

We used to have a workflow that updated it for each commit.
Edit: It might be related to the switch to the main branch.
@antoninbas Do you maybe know?

**Comment by antoninbas** [comment]
No one updated the DockerHub build settings for the image after the default branch was renamed from "master' to "main". I just fixed it. I don't know if the image will stay up-to-date however, my understanding is that Docker will discontinue Autobuild very soon.

**Comment by fruffy** [comment]
Thanks for fixing this! Yeah this will probably a problem. Dockerhub has also started rate limiting pulls from free repositories, but so far this has not been an issue yet. It might also make sense to migrate to Github container registry at some point.

**Comment by mbudiu-vmw** [comment]
Can we close this?

**Comment by fruffy** [comment]
I was thinking of converting this topic into an enhancement issue, since migrating is something we have to deal with sooner or later. But we can close this one for now.
