### ISSUE TITLE
Initilialization behavior of latest p4c

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#2822]
The P4 program has this variable inside a control and the variable is used later in the control. All I see in ebpfType.cpp is `declare()`, but I need a `declare` and initialize as per the P4 program.  How to I initialize _id to 1?

control pipe(inout Headers_t headers, out bool pass)
{
    bit<4> _id = 1;
    ...
}

**Comment by mbudiu-vmw** [comment]
I am afraid I don't understand this question.

**Comment by hesingh** [comment]
A related question.  In the attached p4 program, I have defined `_id` in the code.  But the generated C code has no sign of `_id'? 
    
[ubpf-actions-p4.txt](https://github.com/p4lang/p4c/files/6711436/ubpf-actions-p4.txt)

` ./p4c-ubpf --std p4-16 ../backends/ubpf/examples/simple-actions.p4 -o foo.c`

**Comment by mbudiu-vmw** [comment]
First, we do not make any promises about the naming of objects in generated code (except objects that should be known to the control plane).
Second, in your program _id is dead, so the compiler just removes it. Its value cannot influence any visible program output. gcc will do the same in a C program. The def-use analysis finds that no one uses the assignment to _id, so it removes the assignment. The declaration can then be removed.

**Comment by hesingh** [comment]
See attached P4 program.  Look for last_seq_store in the code - it's a register.
This is the issue with my p4tovpp p4c backend.  It will take time to recreate with ubpf since I am using a register which ubpf supports.  When I compile the generated code in vpp, see this clear failure:

```c
plugins/cpf/CMakeFiles/cpf_test_plugin.dir/cpf.c.o.d -o plugins/cpf/CMakeFiles/cpf_test_plugin.dir/cpf.c.o   -c /home/hemant/vpp/src/plugins/cpf/cpf.c
/home/hemant/vpp/src/plugins/cpf/cpf.c:1198:58: error: variable 'res_1' is uninitialized when used here [-Werror,-Wuninitialized]
                                uint16_t key_local_var = res_1;
                                                         ^~~~~
/home/hemant/vpp/src/plugins/cpf/cpf.c:1027:23: note: initialize the variable 'res_1' to silence this warning
        uint16_t res_1;
                      ^
                       = 0
1 error generated.
```

Relevant generated C code is here:

```c
        uint32_t _my_ip_0;
        uint64_t L2_in__my_mac;
        uint16_t RANDownlink__sn;
        uint16_t res_1;
        uint8_t hit;

and line 1198 is

` uint16_t key_local_var = res_1;`
                                

[cpf_ran-p4.txt](https://github.com/p4lang/p4c/files/6712523/cpf_ran-p4.txt)

**Comment by mbudiu-vmw** [comment]
To compile your program one needs common_config.p4.
Is this a question about the ubpf back-end?

**Comment by hesingh** [comment]
> To compile your program one needs common_config.p4.
> Is this a question about the ubpf back-end?

[gNB_headers-p4.txt](https://github.com/p4lang/p4c/files/6712583/gNB_headers-p4.txt)
[util-p4.txt](https://github.com/p4lang/p4c/files/6712584/util-p4.txt)
[common_config-p4.txt](https://github.com/p4lang/p4c/files/6712585/common_config-p4.txt)

**Comment by hesingh** [comment]
> To compile your program one needs common_config.p4.
> Is this a question about the ubpf back-end?

The issue of unitialized variable could exist even with ebpf backend.  I am using register which is only supported by the ubpf backend.  My p4tovpp backend supports v1model.p4 register.

**Comment by mbudiu-vmw** [comment]
If it could exist perhaps you can contribute a small p4 program for the ebpf_model which exhibits the problem.
The example you gave is still missing transport.p4

**Comment by hesingh** [comment]
> If it could exist perhaps you can contribute a small p4 program for the ebpf_model which exhibits the problem.
> The example you gave is still missing transport.p4

Added transport.p4.  I could use help with the ebpf p4 program because unless a variable defined in the control is used and not eliminated by the compiler, it won't be easy to recreate the problem with ebpf.

**Comment by mbudiu-vmw** [comment]
I don't understand how you can compile this program. The ubpf back-end gives the following error:
```
/home/mbudiu/git/p4c/build/p4include/v1model.p4(753): [--Wwarn=invalid] warning: V1Switch: the main ubpf package should be called ubpf; are you using the wrong architecture?
package V1Switch<H, M>(Parser<H, M> p,
        ^^^^^^^^
/home/mbudiu/git/p4c/build/p4include/v1model.p4(753): [--Werror=Target model error] error: Expected toplevel package package V1Switch to have 3 parameters
package V1Switch<H, M>(Parser<H, M> p,
        ^^^^^^^^
```
So this is clearly not an ubpf program.

**Comment by hesingh** [comment]
Right.  I did say, it will take me time to recreate the issue with existing backends because ubpf uses different api for register than v1model.p4.  I have have to change cpf_ran.p4 code to use ubpf register api and its hairy to change cpf_ran.p4 from v1model.p4 to ubpf_model.p4.  As you said, our best hope is to create the issue with a small ebpf program which I could use help with - declare a variable and have it not removed by the compiler.

**Comment by hesingh** [comment]
This is the line of p4c code that declares vars.

https://github.com/p4lang/p4c/blob/main/backends/ebpf/ebpfControl.cpp#L522

and so  `uint16_t res_1;` gets declared.

Register in v1model.p4 only supports `bit<W>`.  For new p4c code, I could check if etype is EBPFScalarType, initialize the variable to zero.  That would fix my issue.  Any thoughts?

**Comment by mbudiu-vmw** [comment]
In general it's useful to understand the fundamental underlying problem.
The predication pass sometimes introduces benign uses of uninitialized variables (the code is guaranteed to never have an observable output depend on an uninitialized variable if the original program didn't).
Feel free to submit a PR to initialize all variables in C.
