### ISSUE TITLE
How to run any p4 code

### ISSUE THREAD

**Issue by hireTutor** [p4lang/p4c#2825]
I installed P4 compiler from debian repo. But now i don't know hoe to run any tutorial code given on github.Can somebody explain me the complete way of dealing with it. Like do i have to create a directory then i need to put a .p4 file or json in it or some other necessary information.
Please help its really urgent!!!!!!!!!

**Comment by fruffy** [comment]
It is probably best to get started with a premade tutorial like this one [here](https://github.com/p4lang/tutorials/tree/sigcomm19). What you downloaded were the compiler binaries. They just compile P4 code. What you also need is a switch or device to run these binaries on.
You could also this question in the [slack channel](https://app.slack.com/client/T8ZMP3QR0/C8ZR5EN3F) or the [forum](https://forum.p4.org/).
