### ISSUE TITLE
Update checksum ListExpression changed to StructExpression

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#2828]
See P4 code below.

In older p4c code (around November end 2020), my p4c backend processes the list below (between curly braces) as a ListExpression.  With latest p4c, I am shocked to see that IR changed from a ListExpression to StructExpression.  Thus, I also get this error:

`[--Werror=unsupported] error: StructExpression: Computations are not supported in update_checksum`

```p4
control update(inout headers_t hdr, inout metadata_t meta) {
    apply {
         update_checksum_with_payload(hdr.tcp.isValid(),
            { hdr.ipv6.src_address,
                hdr.ipv6.dst_address,
                8w0,
                hdr.ipv6.protocol,
                meta.l4Len,
                hdr.tcp.src_port,
                hdr.tcp.dst_port,
                hdr.tcp.seq_number,
                hdr.tcp.ack_number,
                hdr.tcp.data_offset_and_reserved,
                hdr.tcp.flags,
                hdr.tcp.window,
                hdr.tcp.urgent_pointer
		},
            hdr.tcp.checksum, HashAlgorithm.csum16);
}
```

**Comment by jfingerh** [comment]
This PR from only 4 days ago might be relevant: https://github.com/p4lang/p4c/pull/2796

**Comment by hesingh** [comment]
> This PR from only 4 days ago might be relevant: #2796

I reverted code from the PR and still see failure.

**Comment by hesingh** [comment]
@mbudiu-vmw Do you recommend my backend do the coversion like you did with this checkin?

https://github.com/p4lang/p4c/commit/d2f0585ce9f87755097d27ccdf398ca6e64ddd87

I would like to still understand why checksum functions use ListExpressions are being provided a StructExpression.

**Comment by fruffy** [comment]
Do you have a file to reproduce this? I can not reproduce with
`./p4c/build/p4c-bm2-ss modules/p4c/testdata/p4_16_samples/checksum-l4-bmv2.p4`

**Comment by hesingh** [comment]
@fruffy The p4 code you used is fine.  Maybe something is messed up in my repo..

**Comment by mbudiu-vmw** [comment]
He is talking about his private compiler

**Comment by hesingh** [comment]
For now,let me close.

**Comment by hesingh** [comment]
> Do you have a file to reproduce this? I can not reproduce with
> `./p4c/build/p4c-bm2-ss modules/p4c/testdata/p4_16_samples/checksum-l4-bmv2.p4`

The reason bmv2 works is because the backend converts StructExpression to ListExpression because of this checkin: https://github.com/p4lang/p4c/commit/d2f0585ce9f87755097d27ccdf398ca6e64ddd87

**Comment by hesingh** [comment]
I pulled a new repo for my work and used p4c only up to this checkin and do not see the issue.  So @jfingerh seems to be right that the commit he point to is the one. 

```
commit 4ee37964fdc437e3283b70ed24808dbccb8817ab
Author: Mihai Budiu <mbudiu@vmware.com>
Date:   Thu Jun 17 11:35:13 2021 -0700

    Fix bug in ebpf C code generation for parsers (#2806)
```

**Comment by hesingh** [comment]
With the new repo, I did revert https://github.com/p4lang/p4c/pull/2796 and this issue is fixed.  

So my suggestion is to add a new midend pass and move the bmv2 StructExpression conversion to ListExpression to the pass.

**Comment by hesingh** [comment]
Also, it is clear `update_checksum()` needs a ListExpression due to the error below.  Some p4c code should check update_checksum is being called and not convert its ListExpression to a StructionExpression.

`[--Werror=unsupported] error: StructExpression: Computations are not supported in update_checksum`

**Comment by hesingh** [comment]
I added this line to my backend code.

https://github.com/p4lang/p4c/blob/main/backends/bmv2/simple_switch/simpleSwitch.cpp#L931

to get rid of the `[--Werror=unsupported] error: StructExpression: Computations are not supported in update_checksum` error.

Then, in my backend checksum generation code, I used `convertToList()`, and now this issue is solved for me.
