### ISSUE TITLE
Compiler bug for table action parameter expression containing table_name.apply().hit

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#2835]
This test program is very similar to the one for https://github.com/p4lang/p4c/issues/2321 except that it has a table action parameter with table_name.apply().hit in an expression for an action parameter, instead of a function call.

This is also related to https://github.com/p4lang/p4-spec/issues/840

I am pretty sure there is another p4-spec or p4c issue where Nate Foster and I had some discussion in the comments of P4-16 programs like the test program for this issue, where I was arguing that this seems so complex to handle in general, that it seems to me to be perfectly reasonable to either disallow it in the language spec, or at least call it out as a case where support for it is not required.  I will link to that issue here if I can find it.

The primary reason I am filing an issue is because of the 'Compiler Bug' in the output.  Personally I would consider it a fix if there were simply an error message that said something like "table apply() calls are not supported in parameters to actions within a table's `actions` property", but if someone thinks this should be fully supported somehow then I can write even trickier test programs to make the compiler output correct, e.g. programs where such tables with these kinds of action parameters can nest 3 or 4 levels deep.

```
$ p4c --version
p4c 1.2.0+g202103291035~a69e52 (SHA: 9de755b7e BUILD: DEBUG)

$ p4c --target bmv2 --arch v1model p4c-issue-2835-bmv2.p4 
In file: /home/andy/p4c/frontends/p4/def_use.h:487
Compiler Bug: p4c-issue-2835-bmv2.p4(86): No location set known for t_two_0/t_two.apply().hit;
            a_two(t_two.apply().hit ? bump_val(hdr.ethernet.etherType) : hdr.ethernet.etherType, bump_val(hdr.ethernet.etherType));
                  ^^^^^^^^^^^^^^^^^
```

[p4c-issue-2835-bmv2.p4.txt](https://github.com/p4lang/p4c/files/6755803/p4c-issue-2835-bmv2.p4.txt)

**Comment by jafingerhut** [comment]
This related issue on p4-spec proposes forbidding certain kinds of complex expressions in parameters to an action that appear within a table's `actions` property: https://github.com/p4lang/p4-spec/pull/852

**Comment by jfingerh** [comment]
Here is an alternate change that might be considered to p4c, depending upon a decision of this p4-spec issue https://github.com/p4lang/p4-spec/issues/947 suggesting that table apply() calls be allowed in action bodies:

p4c could be changed to modify actions with table_name.apply().hit expressions in action parameters, so that those expressions are evaluated within the body of the action.

**Comment by mbudiu-vmw** [comment]
Indeed, the way we compile actions today we cannot support this idiom.
It may be possible to do it by using a temporary to store the result of the expression evaluation.
