### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by XavierDrak** [p4lang/p4c#2839]
I am getting this error while installing 
```make: Add missing "dynamic_bitset.h" (#1011)
    
    After commit da96f81 (Remove dependency on Judy1) the build fails with:
    
    In file included from ../../include/bm/bm_sim/match_units.h:37,
                     from ../../include/bm/bm_sim/match_tables.h:34,
                     from ../../include/bm/bm_sim/tables.h:29,
                     from ../../include/bm/bm_sim/P4Objects.h:33,
                     from actions.cpp:25:
    ../../include/bm/bm_sim/handle_mgr.h:31:10: fatal error: dynamic_bitset.h: No such file or directory
       31 | #include "dynamic_bitset.h"
          |          ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    make[4]: *** [Makefile:580: actions.lo] Error 1
    In file included from ../../include/bm/bm_sim/action_profile.h:35,
                     from action_profile.cpp:22:
    ../../include/bm/bm_sim/handle_mgr.h:31:10: fatal error: dynamic_bitset.h: 
```

**Comment by rst0git** [comment]
@XavierDrak `dynamic_bitset.h` is part of BMv2, and this error should be resolved with https://github.com/p4lang/behavioral-model/pull/1011

**Comment by XavierDrak** [comment]
@rst0git hey iam pretty new to this.can u plz tell me how to fix it?

**Comment by mbudiu-vmw** [comment]
Try again

**Comment by jfingerh** [comment]
Other recommendations here, including scripts that can be used to install most of the open source P4 development tools starting from a freshly installed Ubuntu Linux system: https://forum.p4.org/t/installing-open-source-p4-development-tools/84

**Comment by rst0git** [comment]
> can u plz tell me how to fix it?

If you are getting this error while installing [behavioral-model](https://github.com/p4lang/behavioral-model) (also known as BMv2), it means that you don't have the latest commit on the `main` GitHub branch. You can try to run the following commands in the BMv2 source directory:

```bash
git pull
git clean -dfx
./autogen.sh
./configure
make
sudo make install
```
I hope this helps.

**Comment by XavierDrak** [comment]
@rst0git  thanks, it is working now
