### ISSUE TITLE
protobuf should be a dependency of the bmv2 back-end

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#284]
The code to check for protobuf should be in backends/bmv2/addconfig.ac.

The dependency should be described in backends/bmv2/README.md

Today we don't have a way to skip back-ends, but if we had one, we should not require protobuf if we don't compile the bmv2 back-end. It would be nice to be able to compile without protobuf if it is not needed.

**Comment by sethfowler** [comment]
The P4Runtime stuff isn't intended to be specific to BMV2. It depends on BMV2 now, but we want to move away from that. For that reason, it probably wouldn't make sense to make this change.

**Comment by mbudiu-vmw** [comment]
Neither the EBPF back-end and the p4test back-end need this feature.

**Comment by mbudiu-vmw** [comment]
The EBPF back-end has a completely different way to communicate with the control plane - it uses EBPF tables.

**Comment by sethfowler** [comment]
That's not really the point, though. Like everything else in libfrontend, this is a generic feature that is provided for use by all backends that want to take advantage of it. It's fine if some backends choose not to use it, but the idea is that many backends will.

**Comment by mbudiu-vmw** [comment]
I don't think that this issue should be closed.
We should not take a dependency on a large piece of code if it unneeded.
This is really about how the control-plane interacts with the data-plane. This is VERY target-dependent.

**Comment by sethfowler** [comment]
P4Runtime is not supposed to be tied to a specific target, and there are targets besides BMV2 which will be getting support for it. That means that we can't really make the protobuf dependency BMV2-specific. I'm sorry. =(

**Comment by sethfowler** [comment]
One additional note is that having protobuf as a dependency probably won't feel nearly as onerous once we are able to use the version that package managers are shipping. We're actively working towards that. In the near future you'll just be able to type `sudo apt-get install protobuf` and the rest will be done for you.

**Comment by antoninbas** [comment]
I think you are both kind of right. The PI is meant to be target-independent and any P4-programmable target is supposed to be controllable by the PI. I imagine the PI could very well be implemented for the eBPF backend.
On the other hand, I imagine it would be possible to conditionally build the P4Runtime serializer based on whether or not protobuf is detected, if there were a strong desire to do that.
