### ISSUE TITLE
[PSA] Using if statements in Deparser control

### ISSUE THREAD

**Issue by DusanKrdzic** [p4lang/p4c#2840]
When I try to use `if-statement` in deparsers in p4 programs intended for psa architecture:
![Screenshot from 2021-07-06 12-05-33](https://user-images.githubusercontent.com/77269536/124582755-985f5080-de52-11eb-9a34-6e031bce0326.png)
compiler throws an error:
![Screenshot from 2021-07-06 12-08-29](https://user-images.githubusercontent.com/77269536/124583119-f9872400-de52-11eb-9bd0-168b3fb2c7c2.png)

Should branches be supported for PSA, according to PSA InternetChecksum example they should?
https://github.com/p4lang/p4-spec/blob/main/p4-16/psa/examples/psa-example-incremental-checksum2.p4

**Comment by jfingerh** [comment]
The PSA architecture does have a few examples of deparsers with if statements in them, primarily for handling multiple cases of preserved metadata with cloned, unicast, or multicast packets, e.g. here is one example for cloned packets: https://github.com/p4lang/p4-spec/blob/main/p4-16/psa/examples/psa-example-clone-to-port.p4#L193-L198

I would expect that it would be quite reasonable for a PSA implementation to support those `if` conditions and no others in an implementation, i.e. the if statement conditions and levels of nesting supported in a deparser would be quite reasonable if it were pretty much only the kinds you see in the PSA example programs, and no others, giving a compile time error if any other conditions are used.  Any other such `if` conditions can be done in the ingress or egress control, before the deparser begins.

It is possible that supporting such behavior in the BMv2 back end could require additions to the BMv2 JSON file format output by p4c and read by the `psa_switch` program, and/or additions to the `psa_switch` program in how they process deparsers.  There are no standards one must conform to here -- just whatever you and others maintaining those programs consider understandable and maintainable implementations.

**Comment by jfingerh** [comment]
Note that for the InternetChecksum example program you linked to, it is possible that a reasonable implementation technique would be to move the checksum-calculation part of the deparser into the end of the previous control, e.g. from the beginning of the egress deparser into the egress control.  That is, move this code automatically in the compiler, rather than requiring the developer to do so.

Note: This is merely one possible implementation approach for the `psa_switch` back end.  I haven't tried to enumerate others, nor to evaluate the effort required to implement this approach.

**Comment by mbudiu-vmw** [comment]
Indeed, this is not really a limitation of PSA, but of the various targets that implement PSA. BMv2 or Tofino do not support arbitrary ifs in deparsers.

**Comment by DusanKrdzic** [comment]
> @DusanKrdzic Is it reasonable to close this issue now? If you are interested in the PSA architecture, you may want to consider trying the p4c-dpdk back end, which has more full support for PSA than the BMv2 back end does, although I do not know whether it supports the particular program you were trying.

Yes.
