### ISSUE TITLE
psa.p4 include issue on main branch

### ISSUE THREAD

**Issue by DusanKrdzic** [p4lang/p4c#2851]
Some tests fail because of `psa.p4` include on main branch.

EXAMPLE:
![Screenshot from 2021-07-15 11-44-05](https://user-images.githubusercontent.com/77269536/125767338-b20403b9-d03e-4bcc-8709-296346de8227.png)

**Comment by hanw** [comment]
This is expected, the reference output needs to be updated.

P4TEST_REPLACE=1 ctest -R p4/testdata/p4_16_samples/psa-action-selector2.p4
