### ISSUE TITLE
Parser symbolic interpreter unable to evaluate lookahead statement

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#2860]
I am trying to compile the following psa program on dpdk. It uses varbit and lookahead.

[psa-example-dpdk-varbit.p4.txt](https://github.com/p4lang/p4c/files/6889686/psa-example-dpdk-varbit.p4.txt)

The error reported by the compiler is
```
./p4c-dpdk ../testdata/p4_16_samples/psa-example-dpdk-varbit.p4
In file: /home/hanwang/p4c-dpdk2/midend/interpreter.h:165
Compiler Bug: no evaluation for tmp_1[15:8];
```
You can reproduce with this branch: hanw/dpdk-varbit
Any help about how to resolve this issue is much appreciated.

**Comment by mbudiu-vmw** [comment]
The latest changes to the unrolling pass were made by @VolodymyrPeschanenkoLitSoft 
I will probably be offline for a few days, so if you are in a hurry you can possibly ask him to take a look.
I will only be able to look at this next week otherwise.

**Comment by hanw** [comment]
Thanks. @VolodymyrPeschanenkoLitSoft Please take a look if yo could.

**Comment by VolodymyrPeschanenkoLitSoft** [comment]
The main problem here is ExpressionEvaluator doesn't support Operation_Ternary. So, you can use #2861 code to solve this problem. After these changes I got the following error on your branch:
In file: p4c/backends/dpdk/dpdkHelpers.cpp:106
Compiler Bug: p4c/build/p4include/core.p4(34): packet_in Not implemented
extern packet_in {
       ^^^^^^^^^

**Comment by mbudiu-vmw** [comment]
Is this solved?

**Comment by mbudiu-vmw** [comment]
@hanw can you please check whether this issue can be closed?

**Comment by hanw** [comment]
Yes the problem is solved. Thanks.
