### ISSUE TITLE
Compiler Bug: Cannot find declaration for verify

### ISSUE THREAD

**Issue by kitlei-robert** [p4lang/p4c#2868]
When running the following command using today's `main`:

`p4c/build/p4test ./examples/switch-translated-to-p4-16.p4 -I p4c/p4include --toJSON sw.json --Wdisable=unused --Wdisable=not-found --p4v 16`

I get the following error message:

```
In file: ../frontends/common/resolveReferences/referenceMap.cpp:85
Compiler Bug: Cannot find declaration for verify
```

Looking at https://github.com/p4lang/p4c/blob/main/frontends/common/resolveReferences/referenceMap.cpp#L85, the most recent change seems to be 15 months old. The above command was working with much more recent commits of `p4c`.

The P4 file can be found at https://github.com/P4ELTE/t4p4s/blob/master/examples/switch-translated-to-p4-16.p4. Curiously, the P4 code doesn't even use `verify`, only `verify_checksum`, though it references `core.p4` which declares `verify`: https://github.com/p4lang/p4c/blob/main/p4include/core.p4#L66.

Note: the `--Wdisable=not-found` argument is a workaround to get rid of a similar error messages that appears during the compilation of several other files (e.g. https://github.com/P4ELTE/t4p4s/blob/master/examples/l2fwd-gen.p4):

`[--Werror=not-found] error: verify: declaration not found`

**Comment by mbudiu-vmw** [comment]
The compiler can generate code using verify even if you don't use it yourself.

**Comment by kitlei-robert** [comment]
That's the case when it's just a `not-found`: I can trick it as described above. However, when the `Compiler Bug` occurs, no JSON output is generated, and I think it's not possible to sidestep it. Luckily, it happens with only one P4 file that I know of, so it doesn't break things critically for me.

**Comment by mbudiu-vmw** [comment]
I cannot reproduce this issue on my machine. I have used the program  https://github.com/P4ELTE/t4p4s/blob/master/examples/switch-translated-to-p4-16.p4 and compiled it with the command line ./p4test program.p4.

**Comment by mbudiu-vmw** [comment]
Note that I also do not get any warnings from the compiler, so I am not sure what these --W flags are used for.

**Comment by kitlei-robert** [comment]
Apparently, it was the `-I p4c/p4include` option: if I remove it, no errors/warnings show up.

You may close the issue, or keep it open if you'd like to investigate further why using this option is acting up; at least up until a few months ago, it worked fine.

**Comment by mbudiu-vmw** [comment]
I cannot investigate this, since it depends on the files you have on your machine in that directory.
