### ISSUE TITLE
p4test fails for conditional statements in action body.

### ISSUE THREAD

**Issue by usha1830** [p4lang/p4c#2869]
p4test fails with the below error for all the statements within an if block inside action body. Is this expected?
**"Conditional execution in actions unsupported on this target"**

**Comment by mbudiu-vmw** [comment]
Yes, that is correct. This could be easily changed in p4test, but supporting conditionals in bmv2 is an issue that has been open for a few years. It should not be too hard - we could prioritize it if it is desired.

**Comment by mbudiu-vmw** [comment]
The main question is whether this is a realistic feature for high-speed targets.

**Comment by mbudiu-vmw** [comment]
Add it to xfail for p4test. We can also remove this check.
