### ISSUE TITLE
Can users customize the arch file similar to v1model.p4

### ISSUE THREAD

**Issue by daniel0720** [p4lang/p4c#2873]
Hello,
    I have one question, can someone help me to give some hints?
    Take bmv2 backend for example. Now users write p4 program. In the p4 program, they include <v1mode.p4>, and in the preprocess phase, p4c put the v1model.p4 and the user's p4 program into one file. Then 44 passes for frontends etc. 
    I was wandering, if the users can customize the arch file? In other words, if the user can write their own model similar to v1model.p4, instead of using the <v1model.p4>? If they can not, what should I do to modify the p4c to make this possible?

    Does the user write a v2model.p4, then put it in the p4include folder, and then it can be included in the program?
   
    Thanks very much for reply.

**Comment by mbudiu-vmw** [comment]
The compiler front-end is independent of any model, but it does know about core.p4. Some passes in the midend may depend on the model. The back-end is usually completely model-dependent. So you can indeed add any model you would like and then create a customized midend and backend for it.

**Comment by daniel0720** [comment]
Thank you @mbudiu-vmw.
Actually, I need the p4test backend to generate a json file for other midend and backend. Does the midend of p4test model independent?

**Comment by mbudiu-vmw** [comment]
It is not really possible to have a completely model-independent midend. Just the act of including some passes in a midend is in subtle ways model dependent. For example, p4test rejects programs that have conditionals in actions. That is really a target-dependent choice.

Also, some midend passes are parameterized with policies (e.g., the one which eliminates enums has a policy that tells it what bitwidth to use). These are also model- or target-dependent. 

We could have p4test contain only frontend passes, but this would make it harder to test many midend passes. So p4test implies a relatively generous target, but which still has some artificial limitations.

**Comment by mbudiu-vmw** [comment]
But note that you can skip the entire midend by generating json before the midend. I believe that's what --toJson does.

**Comment by daniel0720** [comment]
Thank you @mbudiu-vmw .

**Comment by daniel0720** [comment]
Thank you @mbudiu-vmw . But the p4test help doc specifies the --toJson is "Dump the compiler IR after the midend as JSON in the specified file."  I think this JSON file is after midend, not skip the midend. I don't know if I misunderstand it.

**Comment by mbudiu-vmw** [comment]
Sorry, you are right, this happens after the midend.
We could add a command-line option to p4test to skip the midend passes altogether if that's useful.

**Comment by daniel0720** [comment]
It's ok for me now.

**Comment by daniel0720** [comment]
It's ok for me now.
What i want to do now is to understand how the p4 keywords is processed. And what i should do if i want to add a keyword for p4.
I have one more question, @mbudiu-vmw , do you have some suggestions for the development IDE if i want to customize the p4test? like add a keyword for a customized backend?

Many thanks.

**Comment by mbudiu-vmw** [comment]
I am not sure I understand this question.
If you want to extend the grammar of P4 you have to modify the bison-based parser https://github.com/p4lang/p4c/blob/main/frontends/parsers/p4/p4parser.ypp
For IDE any tools that supports C++ will work. The compiler is written in C++.

**Comment by daniel0720** [comment]
OK，thany you very much @mbudiu-vmw . I have constructed the IDE using vscode and integrated the cmake/clang.
I am not sure if what i want to do is to extend the grammar of P4. There are many keywords such as **action**, **table**, **extern** etc. What I want to do is to add one keyword, e.g. c_func. This keyword will be translated to invoke one function of backend. In this way, we extend the ability of P4.
Our goal is that users can customize some back-end functions. And they can invoke these functions in their P4 programs. For example, for dpdk backend, user can write a new hash function, and invoke this hash function in their P4 program.

I am not sure if this goal is feasible. Can you give some advice?

**Comment by mbudiu-vmw** [comment]
P4 already supports extern functions. Don't these do what you want?

**Comment by daniel0720** [comment]
OK. I will learn more about the extern function and do some experiments.

**Comment by daniel0720** [comment]
I am afraid extern can't meet our needs. As far as I know, extern can only invoke the functions that backends implements. P4 users can not customize their own functions. In other words, they can not customize the backends. the target have no interfaces for users to customize their own functions. What i want to do is to expose the backend ability to p4 users.
I don't know whether i have express my idea clearly.

**Comment by jafingerhut** [comment]
@daniel0720 Is it reasonable to close this issue now?  Have you found answers to your questions?

**Comment by jafingerhut** [comment]
No additional follow-up for last 4 months, so closing this issue.  Feel free to create a new issue if new questions arise, or re-open this one if the questions above are unanswered.
