### ISSUE TITLE
DPDK backend: Different values for Meter color enum in psa.p4 and dpdk pipeline implementation.

### ISSUE THREAD

**Issue by usha1830** [p4lang/p4c#2874]
psa.p4 defines the meter color enum as  `enum PSA_MeterColor_t { RED, GREEN, YELLOW }`

which gets converted by midend convertEnums pass to bit<32> assigning the values `RED = 0, GREEN = 1, YELLOW = 2`

However, the dpdk implementation defines the meter colors as follows:

```
enum rte_color {
	RTE_COLOR_GREEN = 0, /**< Green */
	RTE_COLOR_YELLOW,    /**< Yellow */
	RTE_COLOR_RED,       /**< Red */
	RTE_COLORS           /**< Number of colors */
};
```

http://browse.dpdk.org/dpdk/tree/lib/meter/rte_meter.h

This difference leads to incorrect output for dpdk target whenever this enumeration is used.

Can we modify the **_dpdk/psa.p4_** enum to assign the DPDK compatible values?

**Comment by hanw** [comment]
How about improving convertEnums pass to use a custom encoding?

**Comment by usha1830** [comment]
One option is to handle the _PSA_MeterColor_t_ enum as special case and prevent it from being converted in the midend convertEnums pass .
Then, we can have another backend pass which converts the enum color constants to DPDK compatible values.

However, I am curious why we can't change the enum values in _**dpdk/psa.p4**_. Now that we have customized psa.p4 for each target, I think we can update the psa.p4 for dpdk.

**Comment by usha1830** [comment]
Fixing this issue by improving the convertEnums pass as suggested by @hanw 
Fixed by https://github.com/p4lang/p4c/pull/2882
