### ISSUE TITLE
Compile Error(if -DENABLE_BMV2=OFF): ‘IntMod’ in namespace ‘IR’ does not name a type

### ISSUE THREAD

**Issue by justalittlenoob** [p4lang/p4c#2876]
When I try to update p4c to the version #2871 , I got the following error when compile p4c.  The `cmake` command is ` cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DENABLE_GTESTS=ON -DENABLE_BMV2=OFF -DENABLE_EBPF=OFF -DENABLE_P4TEST=OFF -DENABLE_P4C_GRAPHS=OFF -DENABLE_GC=OFF`    
Did I miss something? Any advice would be appreciated.  

>[  6%] Built target mkp4dirs
[  7%] Building CXX object p4c/frontends/CMakeFiles/frontend.dir/unified_extension_frontend_sources_1.cpp.o
In file included from /home/pengfei/p4/p4_14_tests_fixup/p4/compiler/p4-16vhdl/p4c/backends/bmv2/common/helpers.h:26:0,
                 from /home/pengfei/p4/p4_14_tests_fixup/p4/compiler/p4-16vhdl/p4c/backends/bmv2/common/action.h:21,
                 from /home/pengfei/p4/p4_14_tests_fixup/p4/compiler/p4-16vhdl/p4c/backends/dpdk/dpdkHelpers.h:20,
                 from /home/pengfei/p4/p4_14_tests_fixup/p4/compiler/p4-16vhdl/p4c/backends/dpdk/spec.cpp:1,
                 from /home/pengfei/p4/p4_14_tests_fixup/p4/compiler/p4-16vhdl/build/p4c/frontends/unified_extension_frontend_sources_1.cpp:2:
/home/pengfei/p4/p4_14_tests_fixup/p4/compiler/p4-16vhdl/p4c/backends/bmv2/common/expression.h:121:30: error: ‘IntMod’ in namespace ‘IR’ does not name a type
     void postorder(const IR::IntMod* expression) override;
                              ^~~~~~
/home/pengfei/p4/p4_14_tests_fixup/p4/compiler/p4-16vhdl/p4c/backends/bmv2/common/expression.h:121:10: error: ‘void BMV2::ExpressionConverter::postorder(const int*)’ marked ‘override’, but does not override
     void postorder(const IR::IntMod* expression) override;
          ^~~~~~~~~
p4c/frontends/CMakeFiles/frontend.dir/build.make:265: recipe for target 'p4c/frontends/CMakeFiles/frontend.dir/unified_extension_frontend_sources_1.cpp.o' failed
make[2]: *** [p4c/frontends/CMakeFiles/frontend.dir/unified_extension_frontend_sources_1.cpp.o] Error 1
CMakeFiles/Makefile2:2190: recipe for target 'p4c/frontends/CMakeFiles/frontend.dir/all' failed
make[1]: *** [p4c/frontends/CMakeFiles/frontend.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mbudiu-vmw** [comment]
This is a bug. Indeed, the class IntMod is only defined if you compile the v1model bmv2 back-end, but some code used in the DPDK back-end is also using this class (because it shows up in files from the directory `bmv2/common`, which files are common to both back-ends).

**Comment by mbudiu-vmw** [comment]
For now the simple solution is to just not disable BMV2. We'll have to find a more robust solution.

**Comment by justalittlenoob** [comment]
@mbudiu-vmw Thank you very much:)

**Comment by justalittlenoob** [comment]
@mbudiu-vmw  Besides, Does P4 tests also need to turn on (`-DENABLE_P4TEST=ON`)?  
Because when I turn it off, I got error compile time.
>fatal error: backend/p4test/version.h: No such file or directory  
 #include "backends/p4test/version.h"

**Comment by mbudiu-vmw** [comment]
Yes, this is probably a similar bug.

**Comment by mbudiu-vmw** [comment]
@justalittlenoob can you please confirm that this bug is fixed, and if so close the issue?

**Comment by justalittlenoob** [comment]
@mbudiu-vmw  sure. thanks. it works for me
