### ISSUE TITLE
YYDEBUG caused the error overlimited

### ISSUE THREAD

**Issue by daniel0720** [p4lang/p4c#2877]
Hello, when I export YYDEBUG=1 in the terminal, then I run p4test basic.p4, there is an error.
`Cleanup: popping token START_PROGRAM ((0:0)-(0:0): )
[--Werror=overlimit] error: 1 errors encountered, aborting compilation`

I can't find what and where error happens.

**Comment by mbudiu-vmw** [comment]
If you search for `error:` you will see this being output:
```
ProgramStructure: popping ContainerType standard_metadata_t
-> $$ = nterm structTypeDeclaration ((160:0)-(211:1): /home/mbudiu/git/p4c/build/p4include/v1model.p4(72): [--Werror=invalid] error: @name: should contain a string
@metadata @name("standard_metadata")
          ^
```
This happens because we try to print the annotation before having parsed its contents as a string.
This is a bug.

**Comment by daniel0720** [comment]
Thank you @mbudiu-vmw . later I will reinstall the p4c and to see what happens.
