### ISSUE TITLE
ipv4 option field

### ISSUE THREAD

**Issue by mahfida** [p4lang/p4c#2889]
ISSUE: the packet does not arrive destination.

Hi,

My network has source ---p4 simple switch -- a non p4 hop --- a p4 switch ----dest

I want to use option field  of the ipv4 (as a separate header) for telemetry at fist p4 switch and want to make it invalid  at the second p4 switch.
In my scenario, from source the packets do not have option data, rather I have to add the option header (total 64 bits) at the first p4 switch. In p4 program, I
1. update the hdr.ipv4.ihl by an additional value of 2 (2 times 32-bits)
2. update the hdr.ipv4.packetLength by an additional value of 8 (8 bytes)
3. update udp header length by 8
and
update the checksums of ipv4 (including option fields) and udp checksum using following code
         update_checksum(
            hdr.ipv4.isValid(),
            { hdr.ipv4.version,
              hdr.ipv4.ihl,
              hdr.ipv4.diffserv,
              hdr.ipv4.totalLen,
              hdr.ipv4.identification,
              hdr.ipv4.flags,
              hdr.ipv4.fragOffset,
              hdr.ipv4.ttl,
              hdr.ipv4.protocol,
              hdr.ipv4.srcAddr,
              hdr.ipv4.dstAddr,
              hdr.ipv4_option.value, //I am using timestamp value of 68 so next hop (not a p4 switch can transmit the packet onwards)
              hdr.ipv4_option.optionLength,
              hdr.ipv4_option.swid, //switch id (16 bits)
              hdr.ipv4_option.packet_count // (32 bits)
},
            hdr.ipv4.hdrChecksum,
            HashAlgorithm.csum16);

        update_checksum_with_payload(hdr.udp.isValid(),
            { hdr.ipv4.srcAddr,
                hdr.ipv4.dstAddr,
                8w0,
                hdr.ipv4.protocol,
                meta.Len, //this i calculated earlier by hdr.ipv4.packetLen - hdr.ipv4.ihl
                hdr.udp.srcPort,
                hdr.udp.dstPort,
                hdr.udp.plength
            },
            hdr.udp.checksum, HashAlgorithm.csum16);

My packets do not arrive at switch 2, when I use the option field and update the checksum accordingly. Am I doing something wrong? Any help with be highly appreciated.

**Comment by jnfoster** [comment]
Please ask your question on [forum.p4.org](https://forum.p4.org). This repository is for the P4 compiler source code, not general P4 programming questions.
