### ISSUE TITLE
the ParsersUnroll pass throws "not calling apply properly"

### ISSUE THREAD

**Issue by rhalstea** [p4lang/p4c#289]
It looks like the ParserUnroll pass broke when PassManager::apply_visitor() was updated a few weeks ago.

I was also curious about its purpose. I assume it unrolls self referencing ParserStates for things like header stacks. Is that basically it, or does it encompass more?

**Comment by mbudiu-vmw** [comment]
This pass is commented-out in all mid-ends; it's original implementation was turning each parse graph into a DAG, but we realized that this does not scale if the parse graph has nested loops - it can generate parse graphs with millions of states. A different approach is needed, but the ideal choice depends on the target constraints. For example, if a target does not support loops, you need to generate a DAG. Some targets require constant array indexes in header stacks. So we may need multiple such passes for different goals.
