### ISSUE TITLE
P4C-DPDK: Egress does not generate tables and their actions

### ISSUE THREAD

**Issue by Paxyk** [p4lang/p4c#2893]
Hello,
As stated in the title, egress does not generate tables and their actions. Same happens when you try to use user defined control either in ingress or egress. Sample application with this bug is attached. 
[issue_egress.zip](https://github.com/p4lang/p4c/files/7097969/issue_egress.zip)

**Comment by rst0git** [comment]
@Paxyk Thank you for opening this issue. I was able to replicate the problem and opened a PR with a fix: https://github.com/p4lang/p4c/pull/2894
