### ISSUE TITLE
Does the compiler consider concurrency among multiple logical stages in a physical stage?

### ISSUE THREAD

**Issue by jijinfanhua** [p4lang/p4c#2897]
Hi, I read the article "Forwarding Metamorphosis: Fast Programmable Match-Action Processing in Hardware for SDN", i.e., RMT, and I think the idea of concurrency among multiple logical stages in a physical stage is excellent, because it can reduce the number of logical stages. I don't find the concurrency handling in the compiler source code, so does the process "frontend -> midend -> bmv2 backend" consider  concurrency? 
Thanks a lot.

**Comment by jnfoster** [comment]
This is a great question to ask on the [https://forum.p4.org](P4 Forum). This is the source code for the open-source P4 compiler, so it's not the best place for this kind of query.

**Comment by mbudiu-vmw** [comment]
The question seems to be about the compiler, so I will reopen this.

**Comment by jnfoster** [comment]
Sure, that's fine.

**Comment by mbudiu-vmw** [comment]
Most of P4 is actually race-free: https://p4.org/p4-spec/docs/P4-16-v1.2.2.html#sec-concurrency
The only place where concurrency can affect results is when you use extern objects that store state.
The only support for concurrency in the compiler is the `@atomic` annotation. The compiler attempts to preserve these annotations, but currently no back-end uses them in any way. We also do not have tests for concurrency.

**Comment by jijinfanhua** [comment]
Got it. So p4c for bmv2 doesn't consider concurrency as bmv2 is a CPU implementation, and it is more complicated for tofino target as the hardware should orchestrate the stages more carefully. Am I right? Thank you.

**Comment by mbudiu-vmw** [comment]
I don't think there are fundamental differences between bmv2 and tofino with regards to concurrency.
there are many programs that will compile and run on bmv2 but will never run on tofino, but the fundamental problems are similar - each packet runs in a separate "thread" and these threads are not synchronized with each other in any way.

**Comment by jijinfanhua** [comment]
Thank you. My confusion is solved.

**Comment by jafingerhut** [comment]
But in partial answer to your question, there is significantly more work in the Tofino P4 compiler back end to decide where table lookups can be "placed" in the hardware pipeline than there is in the bmv2 back end, because that problem does not even arise in the bmv2 target, a general-purpose CPU.

**Comment by jijinfanhua** [comment]
> But in partial answer to your question, there is significantly more work in the Tofino P4 compiler back end to decide where table lookups can be "placed" in the hardware pipeline than there is in the bmv2 back end, because that problem does not even arise in the bmv2 target, a general-purpose CPU.

Thank you for your reply. Yeah, there are multiple threads in a physical stage in Tofino, and I think Tofino P4 compiler focuses on table dependency and resources. bmv2 runs in Run-to-Completion mode, much more like a core in [dRMT](https://people.csail.mit.edu/alizadeh/papers/drmt-sigcomm17.pdf).

**Comment by jafingerhut** [comment]
@jijinfanhua Is it reasonable to close this issue now?  Were your questions answered?

**Comment by jijinfanhua** [comment]
> @jijinfanhua Is it reasonable to close this issue now? Were your questions answered?

Yes. Thank you.
