### ISSUE TITLE
Allow tables with an empty entries list.

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#2905]

**Comment by jnfoster** [comment]
Can't wait for the breathless unveiling of P4's new features:`bit<0>` values and tables without entries :-)

**Comment by vgurevich** [comment]
@jnfoster -- given that the compiler does accept an empty P4 program, I think we are on the right path :)
```
$ touch /tmp/null.p4
$ ./p4test /tmp/null.p4
[--Wwarn=missing] warning: Program does not contain a `main' module
```

Seriously, though, the empty constructs are very useful and add a degree of completeness and orthogonality to the language and we should be on the lookout for such misses, although they are often not of the highest priority.

**Comment by jnfoster** [comment]
Totally :-)
