### ISSUE TITLE
GlobalCopyPropagation is too aggressive in switch statements

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2956]
GlobalCopyPropagation transforms the following program segment

```p4
control ingress(inout Headers h) {
    @noWarn("unused") @name(".NoAction") action NoAction_1() {
    }
    @name("ingress.simple_assign") action simple_assign() {
        h.eth_hdr.eth_type = 16w1;
    }
    @name("ingress.simple_assign") action simple_assign_1() {
        h.eth_hdr.eth_type = 16w1;
    }
    @name("ingress.simple_assign") action simple_assign_2() {
        h.eth_hdr.eth_type = 16w1;
    }
    @name("ingress.dummy_table") table dummy_table_0 {
        key = {
            h.eth_hdr.src_addr: exact @name("key") ;
        }
        actions = {
            NoAction_1();
            simple_assign();
        }
        default_action = NoAction_1();
    }
    apply {
        switch (dummy_table_0.apply().action_run) {
            simple_assign: {
                simple_assign_1();
            }
            NoAction_1: {
            }
        }
        simple_assign_2();
    }
}
```
into 
```p4
control ingress(inout Headers h) {
    @noWarn("unused") @name(".NoAction") action NoAction_1() {
    }
    @name("ingress.simple_assign") action simple_assign() {
        h.eth_hdr.eth_type = 16w1;
    }
    @name("ingress.simple_assign") action simple_assign_1() {
        h.eth_hdr.eth_type = 16w1;
    }
    @name("ingress.simple_assign") action simple_assign_2() {
        ;
    }
    @name("ingress.dummy_table") table dummy_table_0 {
        key = {
            h.eth_hdr.src_addr: exact @name("key") ;
        }
        actions = {
            NoAction_1();
            simple_assign();
        }
        default_action = NoAction_1();
    }
    apply {
        switch (dummy_table_0.apply().action_run) {
            simple_assign: {
                simple_assign_1();
            }
            NoAction_1: {
            }
        }
        simple_assign_2();
    }
}
```
But this may be too aggressive. The table may not necessarily execute `NoAction_1`. 

[global_copy_prop_switch.p4.txt](https://github.com/p4lang/p4c/files/7576518/global_copy_prop_switch.p4.txt)

**Comment by jfingerh** [comment]
It seems true that the table must either execute `NoAction_1` or `simple_assign`, and in either case, the field is assigned a value of 1.  But maybe I am missing something.

**Comment by fruffy** [comment]
Apologies, while editing the files I created a case where this does not cause an issue.
I updated the original post. Here, the table may have a case where `NoAction_1` is executed, which does not call either `simple_assign` or `simple_assign_1` but the assignment in `simple_assign_2` is still removed.

**Comment by jafingerhut** [comment]
I agree that after your editing of the original post, it appears there is an incorrect transformation occurring.

**Comment by mbudiu-vmw** [comment]
@filipsyrmia it seems that your code is responsible for this.

**Comment by filipsyrmia** [comment]
It definitely is responsible for this, transformations for action calls inside switch cases need to be corrected. My colleague @Jovana-Syrmia would like to work on solving this issue. I will introduce her to the pass and the details of this issue so it can be resolved soon. Hopefully this is okay with you @mbudiu-vmw
