### ISSUE TITLE
SimplifyDefUse does not respect method calls in stack indices in parsers

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2957]
This is a little specific. 

Given this program 

```p4 
extern bit<8> extern_call(inout H val);
parser p(packet_in pkt, out Headers hdr) {
    H tmp = {extern_call(hdr.h[max(3w1, 3w2)])};
    state start {
        transition parse_hdrs;
    }
    state parse_hdrs {
        pkt.extract(hdr.eth_hdr);
        pkt.extract(hdr.h.next);
        pkt.extract(hdr.h.next);
        transition accept;
    }
}
```

SimplifyDefUse transforms the following segment

```p4
extern bit<8> extern_call(inout H val);
parser p(packet_in pkt, out Headers hdr) {
    @name("tmp") H tmp_0;
    bit<8> tmp_1;
    bit<3> tmp_2;
    bit<3> tmp_3;
    H tmp_4;
    bit<8> tmp_5;
    state start {
        tmp_2 = max(3w1, 3w2);
        tmp_3 = tmp_2;
        tmp_4 = hdr.h[tmp_3];
        tmp_5 = extern_call(tmp_4);
        hdr.h[tmp_3] = tmp_4;
        tmp_1 = tmp_5;
        tmp_0 = (H){a = tmp_1};
        transition start_0;
    }
    state start_0 {
        pkt.extract<ethernet_t>(hdr.eth_hdr);
        pkt.extract<H>(hdr.h.next);
        pkt.extract<H>(hdr.h.next);
        transition accept;
    }
}
```
into 

```p4
extern bit<8> extern_call(inout H val);
parser p(packet_in pkt, out Headers hdr) {
    @name("tmp") H tmp_0;
    bit<8> tmp_1;
    bit<3> tmp_2;
    bit<3> tmp_3;
    H tmp_4;
    bit<8> tmp_5;
    state start {
        tmp_2 = max(3w1, 3w2);
        tmp_3 = tmp_2;
        tmp_4 = hdr.h[tmp_3];
        extern_call(tmp_4);
        ;
        ;
        ;
        transition start_0;
    }
    state start_0 {
        pkt.extract<ethernet_t>(hdr.eth_hdr);
        pkt.extract<H>(hdr.h.next);
        pkt.extract<H>(hdr.h.next);
        transition accept;
    }
}
```
Removing the assignments after the extern call discards any potential writes are made to `hdr.h[tmp_3]`

[def_use_in_parsers.p4.txt](https://github.com/p4lang/p4c/files/7575190/def_use_in_parsers.p4.txt)

**Comment by mbudiu-vmw** [comment]
technically hdr.h is completely overwritten in the start_0 state, so the result won't change.
Does this happen with a single extract to?

**Comment by fruffy** [comment]
Good point. I just rechecked with this program 

```p4
struct Headers {
    ethernet_t eth_hdr;
    H[2]  h;
}

extern bit<8> extern_call(inout H val);

parser p(packet_in pkt, out Headers hdr) {
    H tmp = {extern_call(hdr.h[max(3w1, 3w1)])};
    state start {
        transition parse_hdrs;
    }
    state parse_hdrs {
        pkt.extract(hdr.eth_hdr);
        pkt.extract(hdr.h.next);
        transition accept;
    }
}
```
to 

```p4
struct Headers {
    ethernet_t eth_hdr;
    H[2]       h;
}

extern bit<8> extern_call(inout H val);
parser p(packet_in pkt, out Headers hdr) {
    @name("tmp") H tmp_0;
    bit<8> tmp_1;
    bit<3> tmp_2;
    bit<3> tmp_3;
    H tmp_4;
    bit<8> tmp_5;
    state start {
        tmp_2 = max(3w1, 3w1);
        tmp_3 = tmp_2;
        tmp_4 = hdr.h[tmp_3];
        extern_call(tmp_4);
        ;
        ;
        ;
        transition start_0;
    }
    state start_0 {
        pkt.extract<ethernet_t>(hdr.eth_hdr);
        pkt.extract<H>(hdr.h.next);
        transition accept;
    }
}
```

As far as I understand the behavior of  `next`, this should only extract the first header. `max(3w1, 3w1)` will pass the second header into `extern_call`. However, the assignments are still removed. 

[def_use_in_parsers.p4.txt](https://github.com/p4lang/p4c/files/7636917/def_use_in_parsers.p4.txt)

**Comment by fruffy** [comment]
Instead of an extern

```p4
bit<8> set_hdr(inout H val){
    val.setValid();
    val.a = 1;
    return 1;
}
```
should also suffice.

**Comment by Jovana-Syrmia** [comment]
Problem occurs in `ComputeWriteSet` pass while collecting definitions.
In `ComputeWriteSet::preorder(IR::Member)`, when visting `pkt.extract(hdr.h.next)` expression (this expression writes to location `hdr.h[0])`, method is setting it to write to whole stack, both `hdr.h[0]`,`hdr.h[1]`. 
Because of that, pass `FindUninitialized` sees that the `hdr.h` is overwritten by expression `pkt.extract(hdr.h.next)` and removes previous assignment,
Idea I'm currently working on is to keep track of the accessed element of stack with next and setting write to just that location.

**Comment by mbudiu-vmw** [comment]
In fact that assignment only writes some of the bits, not the entire object.
The solution is to mark the assignment as *reading* the entire object too (which it does - anything that writes only some bits in fact reads all bits and writes all bits by preserving some).

**Comment by mbudiu-vmw** [comment]
@Jovana-Syrmia let me know if you want to work on this, otherwise I will assign it to myself.
We have a similar problem with bit slices or with the valid bit of a header (which is not handled correctly).

**Comment by Jovana-Syrmia** [comment]
@mbudiu-vmw  I would like to work on this.
