### ISSUE TITLE
Compiler Bug: could not convert to Json

### ISSUE THREAD

**Issue by danisrcnl** [p4lang/p4c#2961]
Hi everyone, I've implemented a custom extern for bmv2/simple_switch based on engjefersonsantiago's repository which allowed me to bypass the json generation issues related to its implementation. Calls to methods work fine until I try to assign the return value to some variables.

Here's the compiler outcome (p4c-bm2-ss):
```bash
In file: ../backends/bmv2/jsonconverter.cpp:329
Compiler Bug: reflector.p4(84): socket_extern_instance;: could not convert to Json
       hdr.doubled = socket_extern_instance.sendData(0x00000001);
```

The line of code specified by the compiler is wrapped into the apply brackets of MyIngress block. Is it something that can be done? I wanted to achieve a result similar to the usage of p.ip.hdrChecksum = ck.get(); in the example provided by p4-16 specs at 5.3

**Comment by mbudiu-vmw** [comment]
The compiler should not crash, so this is a bug.
Can you supply a small example that can reproduce this failure?

**Comment by danisrcnl** [comment]
> The compiler should not crash, so this is a bug. Can you supply a small example that can reproduce this failure?

First of all, you should be aware about the fact I'm dealing with older versions of p4 tools. In particular, those listed in the README.md file belonging to [this repository](https://github.com/engjefersonsantiago/p4-programs), so it's pretty likely this bug has already been fixed in the newer releases

**Comment by mbudiu-vmw** [comment]
I am not sure exactly how to help. can these tools be rebased to use the newest versions of the compiler?
In principle what you want to do should not be difficult.

**Comment by danisrcnl** [comment]
> I am not sure exactly how to help. can these tools be rebased to use the newest versions of the compiler? In principle what you want to do should not be difficult.

I guess it shouldn't be that difficult, but the patch they provided isn't documented thus I don't actually know exactly which lines of codes did they add in order to support extern json auto generation. Would it be possible to write return value into a by ref variable just like it's done with packet_in extract method?

**Comment by mbudiu-vmw** [comment]
The compiler should support out or inout arguments for extern methods, no question about it.

**Comment by danisrcnl** [comment]
> The compiler should support out or inout arguments for extern methods, no question about it.

Yeah I tried and it worked, so I'm pretty satisfied about it. Thank you so much for your support! If you want I'm ok with closing the issue.
