### ISSUE TITLE
Official docker image out of date

### ISSUE THREAD

**Issue by pudelkoM** [p4lang/p4c#2965]
I was trying out the new p4c-dpdk backend, but found that the [official docker image](https://hub.docker.com/r/p4lang/p4c) does not contain it yet.

Is there a job or github action to trigger a rebuild?

**Comment by rst0git** [comment]
As far as I know, the Dockerhub autobuild service [has been discontinued](https://www.docker.com/blog/changes-to-docker-hub-autobuilds/). For [BMv2](https://github.com/p4lang/behavioral-model/pull/1027) and [PI](https://github.com/p4lang/PI/pull/562) there is a GitHub action that updates the docker image. However, P4C currently does not have similar GitHub action. This method also requires username and password secrets to be configured in the GitHub repository.

**Comment by rst0git** [comment]
@pudelkoM you can use the [opennetworking/p4c](https://hub.docker.com/r/opennetworking/p4c) container image instead.
https://github.com/opennetworkinglab/p4c-docker

**Comment by mbudiu-vmw** [comment]
If anyone wants to implement this feature we'd be very happy to accept such a contribution. Whose username and passwords are used?

**Comment by rst0git** [comment]
@mbudiu-vmw I opened a pull request in https://github.com/p4lang/p4c/pull/2973

> Whose username and passwords are used?

The username (`DOCKER_USERNAME`) is should be `p4lang` and the password (`DOCKER_PASSWORD`) is a [Docker Hub access token](https://docs.docker.com/docker-hub/access-tokens/). Both should be configured as [GitHub secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets).
