### ISSUE TITLE
Compiler Bug: cannot find replacement for <field with struct type> in type header <name>

### ISSUE THREAD

**Issue by kitlei-robert** [p4lang/p4c#2982]
Executing the following from the base directory of a fresh checkout of [T₄P₄S](https://github.com/P4ELTE/t4p4s/tree/master/), I get this compilation error. There is some macro trickery, which may or may not contribute to the issue; other than that, the two files involved are [test-checksum.p4](https://github.com/P4ELTE/t4p4s/blob/master/examples/testcases/test-checksum.p4) and [std_headers.p4](https://github.com/P4ELTE/t4p4s/blob/master/examples/include/std_headers.p4).

```
> $P4C/build/p4test -I examples/include -D__TARGET_V1__ examples/testcases/test-checksum.p4 
In file: ../midend/flattenHeaders.cpp:126
Compiler Bug: examples/include/std_headers.p4(108): cannot find replacement for .flags in type header tcp_options_t {
  bit<16> srcPort;
  bit<16> dstPort;
  bit<32> seqNo;
  bit<32> ackNo;
  bit<4> dataOffset;
  bit<4> res;
  tcp_flags_t flags;
  bit<16> window;
  bit<16> checksum;
  bit<16> urgentPtr;
  varbit<320> options; }
header tcp_options_t {
       ^^^^^^^^^^^^^
```

`tcp_flags_t` should definitely [be available there](https://github.com/P4ELTE/t4p4s/blob/master/examples/include/std_headers.p4#L102), as it is [defined about 30 lines above](https://github.com/P4ELTE/t4p4s/blob/master/examples/include/std_headers.p4#L84).

Note: if you fully setup T₄P₄S using `bootstrap.sh`, the same compiler bug shows if you execute `./t4p4s.sh %test-checksum`. I tried to minimise the P₄ code, but I couldn't make a smaller one that also produces the bug with reasonable effort.

**Comment by jafingerhut** [comment]
I've confirmed that open source p4c latest as of 2021-Dec-09 (commit 37cd30ee9dc79c65b057a1aa168b961d7aba4701) gives this same error for that same source program.

I know there was effort a year or two ago to add support for some kinds of nested structs in p4c, but I don't recall whether support for a header containing a struct was added.  Do any p4c developers recall, and can point at a test program for it in the testdata/p4_16_samples directory?

**Comment by jafingerhut** [comment]
If you comment out both of the following lines in the file examples/testcases/test-checksum.p4 mentioned in the original issue, the program compiles without error:

```
        verify_checksum_with_payload(hdr.tcp.isValid(), { hdr.ipv4.srcAddr, hdr.ipv4.dstAddr, 8w0, hdr.ipv4.protocol, hdr.ipv4.totalLen, 16w0xffeb, hdr.tcp.srcPort, hdr.tcp.dstPort, hdr.tcp.seqNo, hdr.tcp.ackNo, hdr.tcp.dataOffset, hdr.tcp.res, hdr.tcp.flags, hdr.tcp.window, hdr.tcp.urgentPtr, hdr.tcp.options }, hdr.tcp.checksum, HashAlgorithm.csum16);

// and later

        update_checksum_with_payload(hdr.tcp.isValid(), { hdr.ipv4.srcAddr, hdr.ipv4.dstAddr, 8w0, hdr.ipv4.protocol, hdr.ipv4.totalLen, 16w0xffeb, hdr.tcp.srcPort, hdr.tcp.dstPort, hdr.tcp.seqNo, hdr.tcp.ackNo, hdr.tcp.dataOffset, hdr.tcp.res, hdr.tcp.flags, hdr.tcp.window, hdr.tcp.urgentPtr, hdr.tcp.options }, hdr.tcp.checksum, HashAlgorithm.csum16);
```

If you uncomment either or both of those lines, the compiler gives an error.

It appears that the compiler can handle struct types as members of a header in many situations, but either (a) being included in a list, or (b) being a parameter to an extern call, or (c) the combination of those two factors, is causing the error.

**Comment by kitlei-robert** [comment]
I see, thank you for the prompt reply. Do these scenarios seem easy to add to the compiler? Will they be supported in the foreseeable future?

**Comment by mbudiu-vmw** [comment]
This is a bug. This should work today.

**Comment by mbudiu-vmw** [comment]
Here is a much smaller reproduction:
```
control ComputeChecksum<H>(inout H hdr);

extern void update_checksum_with_payload<T, O>(in T data, out O ck);

struct tcp_flags_t {
    bit<1>  cwr;
}

header tcp_options_t {
    tcp_flags_t flags;
    bit<16> checksum;
}

struct headers {
    tcp_options_t      tcp;
}

control computeChecksum(inout headers hdr) {
    apply {
        update_checksum_with_payload({ hdr.tcp.flags }, hdr.tcp.checksum);
    }
}

package top(ComputeChecksum<headers> _c);
top(computeChecksum()) main;
```
