### ISSUE TITLE
[QUESTION] How to push an element to a table?

### ISSUE THREAD

**Issue by sagarnilmajumdar** [p4lang/p4c#2984]
I have gone through the various tutorials and am learning about P4 and it's XDP backend. I want to know if there is a way to push a single element into a table? 
Suppose I have a table t0.
I have extracted the packets IPv4 and UDP headers. When a specific UDP destination port is found, the corresponding IP should be blacklisted and hence added to the table t0. I want to know if I can add an element to the table when a specific action is performed.
Any information is appreciated. Thanks is advance!

**Comment by mbudiu-vmw** [comment]
There are two ways to modify tables that you may consider. In P4 traditionally tables are modified by the control-plane.
However, P4 does not preclude tables where the data-plane makes the changes.
In fact, the target language, ebpf, lets both kernel (dataplane) and user (control-plane) programs make changes to tables.
The ebpf back-end (which is a subset of the xdp backend) takes advantage of this capability to implement counters. In the ebpf backend the table counters are stored in another table (called ebpf map).
Currently none of the target architecture files provides an API for the dataplane to modify (or read) tables from the dataplane, but I expect it should not be difficult to add one.

**Comment by sagarnilmajumdar** [comment]
So, using a BPF_MAP_LOOKUP_ELEM function is allowed in a P4 program or do I have to add something somewhere? or is that allowed only in the control plane?
Also, yes, I have looked at the statefulness of counters but could not find much about it in the spec doc. Is there anywhere else I can look more about using counters and meters in P4?

**Comment by mbudiu-vmw** [comment]
counters and meters are not standard constructs, they are architecture-dependent objects.
ebpf has a different notion of counters than v1model.
So you have to find the documentation specific for your target.
There is no support for BPF_MAP_LOOKUP_ELEM in p4 currently, but I expect it should not be difficult to add. Is this something you could consider contributing? I can help.

**Comment by sagarnilmajumdar** [comment]
Yeah I would be happy to learn and contribute towards it soon. Any help is appreciated.

**Comment by mbudiu-vmw** [comment]
In fact, there may not be too much to do, there's an --emit-externs flag which allows users to implement their own extern functions. You can just declare them in P4 and implement them in C. I am not sure how well-documented this is, though.
Also, probably we want these functions to be generic (work for many key-value combinations), but let's start simple.

**Comment by mbudiu-vmw** [comment]
So the first step is to declare an extern P4 function write_map(key, value) with some types for key and value and compile the code with this flag and check the generated C code.

**Comment by sagarnilmajumdar** [comment]
Is issue #2094 answer to my questions for externs?

**Comment by mbudiu-vmw** [comment]
That discussion is certainly relevant.

**Comment by jafingerhut** [comment]
@sagarnilmajumdar Is it reasonable to close this issue now?

**Comment by sagarnilmajumdar** [comment]
Yes, thanks
