### ISSUE TITLE
Is there a way to run p4c tests using 'make' that forces regeneration of expected output files?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#2989]
I know how to do this for a single test, using `-f` option to a command like this:
```
cd p4c/build
./bmv2/testdata/p4_16_samples/issue1814-bmv2.p4.test -f
```
but is there a way to add some option to a command like `make check` that runs most or all p4c tests, and for each one forces the regeneration of the test outputs?

If there is, or one is developed and added, it would also be nice to document it in the top level README in the "Tests" section.

**Comment by mbudiu-vmw** [comment]
`P4TEST_REPLACE=1; make check`

**Comment by mbudiu-vmw** [comment]
in fact, no semicolon

**Comment by jafingerhut** [comment]
Created a PR adding describing this command to README here: https://github.com/p4lang/p4c/pull/2990
