### ISSUE TITLE
How to parse packet-out packet from p4runtime?

### ISSUE THREAD

**Issue by FurryChicken** [p4lang/p4c#3008]
I want to inject a packet from the control plane to the data plane. I followed the instruction of [p4runtime-shell/usage/Packet IO](https://github.com/p4lang/p4runtime-shell/blob/main/usage/packet_io.md) and added `@controller_header("packet_out")` to my p4 program. But I don't know how to define `headers` struct and do the parser part. 
1. Should the headers be like 
```c++
@controller_header("packet_out") {
    bit<8>  egress_port;
}
struct headers {
    packetout_t  packetout;
    /* standard headers */
    ethernet_t  ethernet;
    ipv4_t  ipv4;
}
```
2. How to parse the packets? Specifically, how parser distinguishes packet-out packets from data packets and implement it in code？

**Comment by jafingerhut** [comment]
This Github repo is for questions specifically about the P4 compiler, e.g. bugs in the compiler, or desired enhancements in the compiler.

For questions about how to write P4 programs, I would recommend asking your question on https://forum.p4.org

**Comment by FurryChicken** [comment]
OK, I will close this issue.

**Comment by jafingerhut** [comment]
Closing is fine. No need to delete it.
