### ISSUE TITLE
CONVERT_PRIMITIVE no longer has second (optional) argument, why?

### ISSUE THREAD

**Issue by MichalKekely** [p4lang/p4c#3019]
The commit/PR https://github.com/p4lang/p4c/pull/2902 removed the secondary optional argument for `CONVERT_PRIMITIVE`, that was used to specify priority. The change is from `#define CONVERT_PRIMITIVE(NAME, ...)` to `#define CONVERT_PRIMITIVE(NAME)`

Is there any reason why this was removed? Different compilers were using this feature. If there is a reason for removing it, the comment for this macro should be updated as well.

**Comment by mbudiu-vmw** [comment]
It was removed because there are no users of this feature in the open-source repository.

**Comment by MichalKekely** [comment]
> It was removed because there are no users of this feature in the open-source repository.

So could we restore it? Or since it is not used in the open-source repository we don't want to keep it there and it should be redefined elsewhere?

**Comment by mbudiu-vmw** [comment]
Of course it can, I just asked for a comment explaining why it's there
