### ISSUE TITLE
Add helper functions to get info about the extern referenced by a Declaration_Instance

### ISSUE THREAD

**Issue by sethfowler** [p4lang/p4c#302]
While writing some code related to the P4Runtime serializer, I found myself wanting to assert that a `Declaration_Instance` was an instance of a certain extern (say, `direct_meter`).

The code required to make this check is surprisingly complicated. From memory, I believe the situation is that a `Declaration_Instance` has a type of `Type_Specialized`, representing a generic type which has been instantiated with certain parameters. `Type_Specialized` has a `baseType` member which refers to the original, unspecialized type, but this is a `Type_Name`, so you have to look it up in the `ReferenceMap` to produce the actual type you want - in this case, `Type_Extern`. Don't quote me on this, though; there are quite a few steps, and I may have left one out. =)

Obviously, that's a lot of code, especially since you have to handle potential failures at each step in the sequence. This seems to be useful in a lot of places for assertions, and I suspect there may be other places where need to do this in the code, though I haven't checked. We should add a helper function (or perhaps several of them, depending on what makes sense) to make this easier. It'd be ideal to be able to write an assertion like this as a one-liner.

**Comment by mbudiu-vmw** [comment]
You should be able to do typeMap->getType(baseType) as well to skip a step.
What C++ is missing is the ability to do nice pattern matching like ML.

**Comment by sethfowler** [comment]
Couldn't agree more. Once you get used to pattern matching it's hard to return to a language that doesn't have it. The C++ standards committee is working towards some form of pattern matching in C++, although I've been lukewarm on the drafts I've seen so far, but we may have something along those lines in C++20.

**Comment by sethfowler** [comment]
FWIW, you actually have to use `typeMap->getTypeType()`, because `typeMap->getType()` returns a `Type_Type`.
