### ISSUE TITLE
Support arbitrary number of arguments in a single package definition

### ISSUE THREAD

**Issue by jphurl** [p4lang/p4c#3030]
As an example:
```p4
control Ctrl<T>(inout T controlPlaneData);

package Pkg1<T...>(Ctrl<T...> args);
package Pkg2<T...>(Ctrl<T...> args);

package Wrapper<T...>(Pkg1<T..> p1, Pkg2<T..> p2);

package MainPkg<T...>(Wrapper<T...> w1, Wrapper<T...> w2);
```

If this is not easy to do, how much work/code do you think is required to at least make something functional for this specific purpose?

Please let me know if you need any more context. I appreciate you taking the time to help, thanks.

**Comment by jnfoster** [comment]
Can you share why this is useful? Is there a program you want to write that can't be written with the `...`s filled in with fixed-length lists?

It seems uses of this feature would have to bottom out with a parameterized/generic object that doesn't use the `...` in an interesting -- i.e., all but finitely many of the type variables are ignored. And, inductively, we can always eliminate the `...` too.

Maybe there's a parameterized/generic object that can be instantiated with different numbers of types. But, again, there's a maximum number of useful type variables computing bottom-up, so it seems you could always just set the length of the list to this number.

Did I miss something? Is this actually giving us programs we can't write today? Or is it just saving a some keystrokes?

**Comment by mbudiu-vmw** [comment]
At this point we don't even have generic controls, so doing varargs on top will require some work. But please note that we support many packages in an architecture, so you can declare packages with different number of arguments and only instantiate the one you need.

**Comment by jphurl** [comment]
> Did I miss something? Is this actually giving us programs we can't write today? Or is it just saving a some keystrokes?

It would be like a syntactic sugar. In our compiler, we base whether we support some package/model based off of the main module's package name. The issue is that our architecture can have a variable number of controls in this main package, but package definition overloading is not supported either.

I am thinking this can be done with some kind of macro.. but wanted to gauge how much work it would be to implement properly in the frontend. Thank you for the input.

 > At this point we don't even have generic controls

I am able to get away with this generic control declaration as a package parameter type:
```p4
control Ctrl<T>(inout T data);
package Pkg<T>(Ctrl<T> ctrl);

struct S {...}
control Control(inout S data) { ... }
Pkg(Control()) main;
```

S

**Comment by jphurl** [comment]
no longer needed, thanks for the help. Closing
