### ISSUE TITLE
Create test case verifying that table with empty const entries produces correct P4Runtime entries file

### ISSUE THREAD

**Issue by jfingerh** [p4lang/p4c#3036]
After https://github.com/p4lang/p4c/pull/3035 has been merged (unless we change plans and include such a test case in that PR).

**Comment by jafingerhut** [comment]
I attached a zip file to this comment: https://github.com/p4lang/p4c/pull/3035#issuecomment-1017060042 that has a P4 program and an expected empty <name>.p4.entries.txt file, that should be empty for that program.

**Comment by mbudiu-vmw** [comment]
Fixed by #3035
