### ISSUE TITLE
Bug when lookahead is used with header type

### ISSUE THREAD

**Issue by mvido** [p4lang/p4c#3041]
When lookahead is used with a header type as in following example:
```
header option_t {
    bit<8> type;
    bit<8> len;
}

struct headers_t {
    ethernet_t ethernet;
    ipv4_base_t             ipv4_base;
    ipv4_option_timestamp_t ipv4_option_timestamp;
    option_t                option;
}

...

    state parse_ipv4_options {
        hdr.option = pkt.lookahead<option_t>();
        transition select(hdr.option.type) {
            8w0x44 &&& 8w0xff: parse_ipv4_option_timestamp;
            default : accept;
        }
    }
    state parse_ipv4_option_timestamp {
        pkt.extract(hdr.ipv4_option_timestamp, (bit<32>)hdr.option.len * 8 - 16);
        transition accept;
    }
```
the whole sample program [pna-example-dpdk-varbit.p4.txt](https://github.com/p4lang/p4c/files/7905845/pna-example-dpdk-varbit.p4.txt) is a modification of https://github.com/p4lang/p4c/blob/main/testdata/p4_16_samples/pna-example-dpdk-varbit.p4 (this modification is also available in draft PR: https://github.com/p4lang/p4c/pull/3015) and we compile it with p4c-dpdk as follows:
`./build/p4c-dpdk ./testdata/p4_16_samples/pna-example-dpdk-varbit.p4 -o out.spec
`
we get following warning produced inside `ParsersUnroll` pass:
```
./testdata/p4_16_samples/pna-example-dpdk-varbit.p4(85): warning:  pkt.extract is ignored. Error: Reading field from invalid header
        pkt.extract(hdr.ipv4_option_timestamp, (bit<32>)hdr.option.len * 8 - 16);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

P4_16 spec does not explicitly state (or I didn't find it) whether lookahead returns a valid or invalid header, but it does not make sense to me if the returned header should be invalid.
If we assume that the header returned by lookahead should be valid, then there is probably a bug in `ParsersUnroll` pass which causes that warning.

There is also probably another problem in `ExpandLookahead` pass too because validator used in validate-p4c CI pipeline reports some error in that pass used in p4test, the details can be seen in the output of CI run in draft PR https://github.com/p4lang/p4c/pull/3015 : https://github.com/p4lang/p4c/runs/4695836576?check_suite_focus=true

**Comment by jafingerhut** [comment]
@mvido wrote: "P4_16 spec does not explicitly state (or I didn't find it) whether lookahead returns a valid or invalid header, but it does not make sense to me if the returned header should be invalid."

I am not aware of anywhere in the P4_16 spec that specifies that lookahead can change the validity of a header in any way.  I suspect by far the common case is that people call lookahead passing it a type that is not a header, so in such programs this question does not even arise.

It seems reasonable to create an issue on the repo https://github.com/p4lang/p4-spec asking this question, but I would not be surprised if the answer decided upon is "no change to header validity when passed to lookahead".  If you want to change validity, extract the header.

**Comment by vgurevich** [comment]
I think that the answer is very clear, but needs to be written in the spec. `lookahead()` returns a **valid** header, otherwise it is pretty much unusable. 

Assume that you have:
```
header_t h;
```

Then `pkt.extract(h);` is equivalent to `pkt.extract<header_t>(h)` and that, in turn, is equivalent to:
```
h = pkt.lookahead<header_t>();   /* Returns a valid header of type header_t */
pkt.advance(h.minSizeInBits());
```

**Comment by jafingerhut** [comment]
@vgurevich That is a very reasonable proposal, but do existing implementations already do this, and/or can they straightforwardly be changed so that they work that way?

**Comment by mbudiu-vmw** [comment]
We have a pass called expandLookahead which has the following documentation, which suggests that it does the right thing:
```
/// Given an assignment like
/// a = lookahead<T>();
/// this is transformed into
/// bit<sizeof(T)> tmp = lookahead<bit<sizeof(T)>>();
/// a.m.setValid();  // for header fields
/// a.m0 = tmp[f1,f0];
/// a.m1 = tmp[f2, f1+1];
```

**Comment by mbudiu-vmw** [comment]
This is for sure a bug - I don't know what the error message means. The generated code looks fine at this point.

**Comment by mbudiu-vmw** [comment]
If you think there is a bug in the ExpandLookahead pass please file a separate issue for it.

**Comment by mbudiu-vmw** [comment]
@fruffy : seems that Gauntlet is upset by some program; I asked for a separate issue with a reproduction to be filed.

**Comment by fruffy** [comment]
I will take a closer look at the Gauntlet issue next week.

**Comment by fruffy** [comment]
Was quicker to check than I expected. Yes, the issue was related to the insertion of a `setValid` call, which Gauntlet also complained about. I will need to fix this.

**Comment by mvido** [comment]
> Was quicker to check than I expected. Yes, the issue was related to the insertion of a `setValid` call, which Gauntlet also complained about. I will need to fix this.

@fruffy So the issue is in Gauntlet and not in ExpandLookahead pass, correct? So no need to file another issue for ExpandLookahead pass?

@mbudiu-vmw Thanks for really quick fix!

**Comment by mvido** [comment]
@fruffy So I rather filed an issue -> https://github.com/p4lang/p4c/issues/3044.
