### ISSUE TITLE
Error: `verify: declaration not found`

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#3048]
If I try to compile the following minimal (?) V1Model program,
```
#include <core.p4>
#include <v1model.p4>
typedef standard_metadata_t sm_t;
struct empty {}
parser MyP(packet_in b, out empty h, inout empty m, inout sm_t sm) { state start { transition accept; } }
control MyV(inout empty h, inout empty m) { apply { } } 
control MyC(inout empty h, inout empty m) { apply { } } 
control MyI(inout empty h, inout empty m, inout sm_t sm) { apply { } } 
control MyE(inout empty h, inout empty m, inout sm_t sm) { apply { } } 
control MyD(packet_out b, in empty h) { apply { } } 
V1Switch(MyP(), MyC(), MyI(), MyE(), MyV(), MyD()) main;
```
I get an error:
```
[--Werror=not-found] error: verify: declaration not found
```

Upon further review, the error is introduced in the `HandleNoMatch` pass, which introduces a (dead) state that invokes `verify`. 
```
parser MyP(packet_in b, out empty h, inout empty m, inout sm_t sm) {
    state start {
        transition accept;
    }
    state noMatch {
        verify(false, error.NoMatch);
        transition reject;
    }
}
```
Meanwhile, the `verify` extern from `core.p4` was removed by the `RemoveAllUnusedDeclarations` pass in the front-end.

**Comment by mbudiu-vmw** [comment]
RemoveAllUnusedDeclarations has a special check which should prevent removing objects declared in "system headers".

**Comment by mbudiu-vmw** [comment]
This doesn't happen with p4test. What command-line are you using?

**Comment by jnfoster** [comment]
`p4test`

**Comment by jnfoster** [comment]
Let me triple check. I have a new M1 Macbook. I had just re-built `p4c` from source, but I may have been running with an older binary...

**Comment by mbudiu-vmw** [comment]
This hasn't changed recently. What is the exact command-line?

**Comment by jnfoster** [comment]
It was just `p4test -I /path/to/p4c/p4include file.p4`

**Comment by mbudiu-vmw** [comment]
I wonder whether the detection of the system path fails when you use -I.

**Comment by mbudiu-vmw** [comment]
```
// Try to guess whether a file is a "system" file
bool RemoveUnusedDeclarations::isSystemFile(cstring file) {
    if (file.startsWith(p4includePath)) return true;
    // if the backend is invoked directly with '-I p4include'
    if (file.startsWith("p4include")) return true;
    return false;
}
```

**Comment by jnfoster** [comment]
Hmm. Let me just re-build p4c and confirm that I have the right binary.

**Comment by jnfoster** [comment]
Damn it. Indeed, I had an out-of-date binary.

In my own defense, I have a shiny new laptop. It was a silly mistake, but with the change in architecture (`amd64` vs. `x86_64`), some things are in a weird and parallel state and I was confused about what was where.

On the plus side, I have now compiled `p4c` on an M1 Mac :-)
