### ISSUE TITLE
Slicing arbitrary-width integers

### ISSUE THREAD

**Issue by MollyDream** [p4lang/p4c#3058]
p4c compiler allows the statement `bit<4> x = 16[3:0]`. This suggests variable-width integers should support slices, but the spec does not list bit slices among the supported operations for arbitrary-width integers. 

Since shifts are supported in the integers, integers already carry a notion of bits, so supporting bit slicing seems also fine. If we want to allow that, the spec needs an update; otherwise, the compiler needs a fix.

**Comment by mbudiu-vmw** [comment]
This one I would file in the spec section.
The main question about slices is sign-extension for negative values.

**Comment by jnfoster** [comment]
Agree. Please create a p4-spec issue, and create a PR adding this to Section 8.7.

Then we can close this p4c issue.
