### ISSUE TITLE
Unable to do or,and,sub when 2nd argument passed is const

### ISSUE THREAD

**Issue by kamleshbhalui** [p4lang/p4c#3071]
I think there is bug in ordered_set at this line https://github.com/p4lang/p4c/blob/main/lib/ordered_set.h#L224

all three function should take const ref for 2nd parm.

**Comment by mbudiu-vmw** [comment]
I am not sure I know what you mean. Can you give an example of something you want to achieve and cannot?

**Comment by kamleshbhalui** [comment]
I mean't Below example fails to compile, while it should compile without any error with code pretty much valid.
ordered_set<cstring> foo();
ordered_set<cstring> x;
x |= foo();
