### ISSUE TITLE
Crash when using obsolete architecture file

### ISSUE THREAD

**Issue by drobinkent** [p4lang/p4c#3077]
I am facing the following issue in compiling my p4 program. The code snippet below contains my header definition and the error code also. The code was perfectly working a few months ago. Recently I have newly set up my development environment and having this issue. So I guess this is a new compiler issue. And from the error message, I am having no clue about the problem. Can someone please guide me to resolve the issue? 

```
Compiler Bug: p4src/src/headers.p4(182): struct userMetadata {
  bit<16> l4_src_port;
  bit<16> l4_dst_port;
  bool is_multicast;
  bool is_pkt_rcvd_from_downstream;
  egress_queue_event_info_t egress_queue_event_hdr;
  egress_rate_event_info_t egress_rate_event_hdr;
  ingress_rate_event_info_t ingress_rate_event_hdr;
  bit<10> egr_port_rate_value_range;
  bit<10> egr_queue_depth_value_range;
  bit<10> minimum_group_members_requirement;
  bit<9> egr_queue_based_path;
  bit<9> egr_rate_based_path;
  bit<32> temp;
  bit<8> temp_8_bit; }: nested ctxt->structure
struct local_metadata_t {
       ^^^^^^^^^^^^^^^^
```

**Comment by mbudiu-vmw** [comment]
It's much easier to debug an issue if you supply a program to reproduce the issue and the command-line you used.

**Comment by mbudiu-vmw** [comment]
If your files are not proprietary you can zip them all and upload them here.
If you add the -v flag to the compiler what are the last few lines before the bug?

**Comment by drobinkent** [comment]
[compilerlog.txt](https://github.com/p4lang/p4c/files/8027704/compilerlog.txt)


I am attaching the log when the compiler is invoked with -v flag. That log also indicates same issue. 

Unfortunately, I can not expose all the P4 source files in public domain.

**Comment by mbudiu-vmw** [comment]
First, we can get a slightly more informative error message by replacing line 225 https://github.com/p4lang/p4c/blob/main/backends/bmv2/common/header.cpp#L225 in backends/bmv2/common/header.cpp with the following: `BUG("%1%: nested ctxt->structure %2%", st, f);` This will tell you which field of userMetadata has a header type. 

But I think the compiler should not really process userMetadata at all at this step (it seems to be passed as an argument to the function `addHeaderType`).

Do you have any variables that have type userMetadata (not arguments of controls)? If not, perhaps the compiler is synthesizing some.

**Comment by drobinkent** [comment]
I have thoroughly checked,  there is no variable of type userMetadata (except the control blocks). 

In my header definition 

```
Compiler Bug: p4src/src/headers.p4(182): struct userMetadata {
  bit<16> l4_src_port;
  bit<16> l4_dst_port;
  bool is_multicast;
  bool is_pkt_rcvd_from_downstream;
  egress_queue_event_info_t egress_queue_event_hdr;
  egress_rate_event_info_t egress_rate_event_hdr;
  ingress_rate_event_info_t ingress_rate_event_hdr;
  bit<10> egr_port_rate_value_range;
  bit<10> egr_queue_depth_value_range;
  bit<10> minimum_group_members_requirement;
  bit<9> egr_queue_based_path;
  bit<9> egr_rate_based_path;
  bit<32> temp;
  bit<8> temp_8_bit; }: nested ctxt->structure
struct local_metadata_t {
```
       ^^^^^^^^^^^^^^^^

Al of the following three is header type. Is it creating the issue?

**Comment by mbudiu-vmw** [comment]
Can you apply the patch and see which field is the problem?
I have made a test with headers as part of userMetadata and it works fine. This should not be a problem.
But perhaps this will help you create a smaller reproduction example by commenting out pieces of code which are not relevant.

**Comment by mbudiu-vmw** [comment]
Why do you disable the "unsupported" warning?
If you don't do you get any messages?

**Comment by drobinkent** [comment]
1) I have tried enabling all the warning messages. But that does not gives anything new. 
2) I have replaced all the header types inside the local_metadata (userMtadata) with their respective fields. And the P4 program now compiles without error. 
3) The same program was compiling perfectly around 2 months ago. I guess the issue is created by the new version of the compiler.

**Comment by mbudiu-vmw** [comment]
1. You should probably not disable the "unsupported" warning, if something is unsupported ignoring it won't make it compile.
2. If that is a solution for you it may be fine, but it won't help us fix the bug. Perhaps you can create a very small program that uses a local_metadata structure with a header field and have that fail. I tried, but it worked for me, so there must be something else going on.
3. What is the previous version of the compiler which worked for you? Perhaps we can bisect this to a commit which caused the regression.

**Comment by drobinkent** [comment]
I have the same header files with another P4 program. That works fine. 

But the program having the error is different. I am trying to find which version of the compiler it was, and I will also post the warnings.

**Comment by drobinkent** [comment]
When I enable the warnings, I get warning about some unused fields. Which is fully expected. 

The command I am using is following 

```
p4c-bm2-ss --arch v1model -o p4src/Build/leaf.json \
        --p4runtime-files p4src/Build/leaf_p4info.txt \
        p4src/src/leaf.p4 -Dports=256 -DENABLE_DEBUG_TABLES -DDP_ALGO_ECMP -DECN_ENABLED
```

The log is following. 

```
make p4-leaf-ecmp 
Makefile:220: warning: overriding recipe for target 'process-l2strideSmallLarge-48kFlowRate'
Makefile:151: warning: ignoring old recipe for target 'process-l2strideSmallLarge-48kFlowRate'
*** Building P4 program for the leaf switch...
p4c-bm2-ss --arch v1model -o p4src/Build/leaf.json \
        --p4runtime-files p4src/Build/leaf_p4info.txt \
        p4src/src/leaf.p4 -Dports=256 -DENABLE_DEBUG_TABLES -DDP_ALGO_ECMP -DECN_ENABLED
p4src/src/CONSTANTS.p4(157): [--Wwarn=unused] warning: egressPortCounter: unused instance
counter((bit<32>)MAX_PORTS_IN_SWITCH, CounterType.packets) egressPortCounter;
                                                           ^^^^^^^^^^^^^^^^^
p4src/src/CONSTANTS.p4(159): [--Wwarn=unused] warning: ctrlPktToCPCounter: unused instance
counter((bit<32>)MAX_PORTS_IN_SWITCH, CounterType.packets) ctrlPktToCPCounter;
                                                           ^^^^^^^^^^^^^^^^^^
p4src/src/CONSTANTS.p4(160): [--Wwarn=unused] warning: p2pFeedbackCounter: unused instance
counter((bit<32>)MAX_PORTS_IN_SWITCH, CounterType.packets) p2pFeedbackCounter;
                                                           ^^^^^^^^^^^^^^^^^^
p4src/src/CONSTANTS.p4(162): [--Wwarn=unused] warning: egress_port_meters: unused instance
meter((bit<32>)MAX_PORTS_IN_SWITCH, MeterType.packets) egress_port_meters;
                                                       ^^^^^^^^^^^^^^^^^^
p4src/src/CONSTANTS.p4(165): [--Wwarn=unused] warning: egress_queue_depth_value_map: unused instance
 @name("egress_queue_depth_value_map")register<bit<48>>(MAX_PORTS_IN_SWITCH) egress_queue_depth_value_map;
                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
p4src/src/CONSTANTS.p4(166): [--Wwarn=unused] warning: egress_queue_depth_last_update_time_map: unused instance
 @name("egress_queue_depth_last_update_time_map")register<bit<48>>(MAX_PORTS_IN_SWITCH) egress_queue_depth_last_update_time_map;
                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
p4src/src/CONSTANTS.p4(168): [--Wwarn=unused] warning: egress_queue_rate_last_update_time_map: unused instance
 @name("egress_queue_rate_last_update_time_map")register<bit<48>>(MAX_PORTS_IN_SWITCH) egress_queue_rate_last_update_time_map;
                                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
p4src/src/CONSTANTS.p4(169): [--Wwarn=unused] warning: port_to_port_delay_value_map: unused instance
 @name("port_to_port_delay_value_map")register<bit<48>>(MAX_PORTS_IN_SWITCH) port_to_port_delay_value_map;
                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
p4src/src/CONSTANTS.p4(170): [--Wwarn=unused] warning: port_to_port_delay_last_update_time_map: unused instance
 @name("port_to_port_delay_last_update_time_map")register<bit<48>>(MAX_PORTS_IN_SWITCH) port_to_port_delay_last_update_time_map;
                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
p4src/src/egress_queue_depth_monitor.p4(18): [--Wwarn=unused] warning: port_last_updated_egress_queue_avg_depth: unused instance
    register<bit<19>>(MAX_PORTS_IN_SWITCH) port_last_updated_egress_queue_avg_depth;
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
p4src/src/cp_assisted_multicriteria_upstream_policy_routing.p4(16): [--Wwarn=unused] warning: flowlet_id_map: unused instance
    @name("flowlet_id_map") register<bit<16>>(32w8192) flowlet_id_map;
                                                       ^^^^^^^^^^^^^^
p4src/src/leaf.p4(101): [--Wwarn=unused] warning: debug_std_meta_ingress_start: unused instance
    debug_std_meta() debug_std_meta_ingress_start;
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
p4src/src/leaf.p4(102): [--Wwarn=unused] warning: ingress_end_debug: unused instance
    debug_std_meta() ingress_end_debug;
                     ^^^^^^^^^^^^^^^^^
p4src/src/leaf.p4(115): [--Wwarn=unused] warning: cp_assisted_multicriteria_upstream_routing_control_block: unused instance
    cp_assisted_multicriteria_upstream_routing_tables() cp_assisted_multicriteria_upstream_routing_control_block;
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
p4src/src/leaf.p4(116): [--Wwarn=unused] warning: cp_assisted_multicriteria_upstream_policy_routing_control_block: unused instance
    cp_assisted_multicriteria_upstream_policy_routing() cp_assisted_multicriteria_upstream_policy_routing_control_block;
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
p4src/src/leaf.p4(270): [--Wwarn=unused] warning: debug_std_meta_egress_start: unused instance
    debug_std_meta() debug_std_meta_egress_start;
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
In file: /usr/src/packages/BUILD/backends/bmv2/common/header.cpp:225
Compiler Bug: p4src/src/headers.p4(182): struct userMetadata {
  bit<16> l4_src_port;
  bit<16> l4_dst_port;
  bool is_multicast;
  bool is_pkt_rcvd_from_downstream;
  egress_queue_event_info_t egress_queue_event_hdr;
  egress_rate_event_info_t egress_rate_event_hdr;
  flag_headers_t flag_hdr;
  bit<32> flowlet_map_index;
  bit<16> flowlet_id;
  bit<48> flow_inter_packet_gap;
  bit<48> flowlet_last_pkt_seen_time;
  bit<9> flowlet_last_used_path;
  bit<2> rate_control_allowed_for_the_tcp_flow;
  bit<6> rate_control_event;
  bit<32> last_seq_no_with_rate_control;
  ingress_rate_event_info_t ingress_rate_event_hdr;
  bit<10> egr_port_rate_value_range;
  bit<10> egr_queue_depth_value_range;
  bit<10> minimum_group_members_requirement;
  bit<9> egr_queue_based_path;
  bit<9> egr_rate_based_path;
  bit<32> temp;
  bit<8> temp_8_bit; }: nested ctxt->structure
struct local_metadata_t {
       ^^^^^^^^^^^^^^^^

make: *** [Makefile:4: p4-leaf-ecmp] Error 1

```

**Comment by mbudiu-vmw** [comment]
These warnings were in the previous log you sent as well.
You were only disabling the "unsupported" warning.

**Comment by drobinkent** [comment]
Yes. When I enable the unsupported warning everything remains the same. 
I am trying to find the last version of the compiler, unfortunately, I have never tracked it. My bad.

**Comment by mbudiu-vmw** [comment]
If you could use the `git bisect` command https://git-scm.com/docs/git-bisect by guessing an original version that worked (e.g., 6 months ago) you don't need to remember which one it was. That may take some time.
Ideally you'd be able to comment out half of your P4 program and in a few iterations be left with something small enough to share without disclosing your secrets. You can try by making an empty parser first, then commenting out the last part of your ingress control body...

**Comment by drobinkent** [comment]
Found the portion of my code which was creating the problem. 

```
if(local_metadata.flag_hdr.is_control_pkt_from_egr_queue_depth || local_metadata.flag_hdr.is_control_pkt_from_egr_queue_rate  )
{
                clone3(CloneType.E2E, (bit<32>)(standard_metadata.ingress_port)+ ((bit<32>)MAX_PORTS_IN_SWITCH * 2), {standard_metadata, local_metadata});
}
else if (local_metadata.flag_hdr.is_control_pkt_from_egr_queue_depth ) {
    clone3(CloneType.E2E, CPU_CLONE_SESSION_ID, {standard_metadata, local_metadata});
}
```

Sorry for the poor indention. When I comment out this part. The code compiles properly. 

Any idea about what is the issue?

**Comment by drobinkent** [comment]
The issue is in following line 

`clone3(CloneType.E2E, CPU_CLONE_SESSION_ID, {standard_metadata, local_metadata});`

If I do not want to preserve the local_metadata after cloning then it works fine. But with the local_metadata it gives the error.

**Comment by mbudiu-vmw** [comment]
The clone primitive was actually broken in the compiler; we have fixed it, and deprecated the original clone3 API.
The new API is called `clone_preserving_field_lists` and it requires you to tag the field of the user_metadata structure that you need cloned.
And you could never really clone standard_metadata even before; that should be populated by the hardware on packet receipt.
Here is a minimal example  with cloning:
```
#include <core.p4>
#include <v1model.p4>

struct Headers {}

enum bit<8> PreservedFieldList {
    Field = 8w1
}

struct Meta {
    @field_list(PreservedFieldList.Field)
    bit<1> b;
}

control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    apply {
        clone_preserving_field_list(CloneType.I2E, 32w64, PreservedFieldList.Field);
    }
}
```
Based on your example I may be able to create a reproduction for the bug; the compiler should give a better error message.
But the compiler should have warned you that clone3 is deprecated. Perhaps you are not using the most recent v1model.p4 file?

**Comment by mbudiu-vmw** [comment]
Please note that only fields of the user metadata can be cloned.

**Comment by mbudiu-vmw** [comment]
See also the comments in v1model.p4

**Comment by drobinkent** [comment]
Thanks a lot for the help. My scripts were not using the updated version of V1model.p4.

**Comment by mbudiu-vmw** [comment]
We shouldn't really break user programs, but these APIs were not working correctly, so we had to make this breaking change. Hopefully you'll be able to port your applications without loss of functionality.

**Comment by jfingerh** [comment]
@drobinkent It looks like this issue can be closed now?

**Comment by drobinkent** [comment]
@jfingerh,  sure.
