### ISSUE TITLE
serializer replicates action with same name and same id

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#308]
With this P4 program"
```
parser start {
    return ingress;
}

action a1(port) {
    modify_field(standard_metadata.egress_spec, port);
}

table t1 {
    actions { a1; }
}

table t2 {
    actions { a1; }
}

control c1 {
    apply(t1);
    apply(t2);
}

control ingress {
    c1();
}
```

Action `c1.a1` appears twice in the list of actions. It should only appear once:
```
"actions": [
  {
   "preamble": {
    "id": 16832930,
    "name": "NoAction_1"
   }
  },
  {
   "preamble": {
    "id": 16824969,
    "name": "NoAction_2"
   }
  },
  {
   "preamble": {
    "id": 16809539,
    "name": "c1.a1"
   },
   "params": [
    {
     "id": 58606336,
     "name": "port",
     "bitwidth": 9
    }
   ]
  },
  {
   "preamble": {
    "id": 16809539,
    "name": "c1.a1"
   },
   "params": [
    {
     "id": 58606336,
     "name": "port",
     "bitwidth": 9
    }
   ]
  }
 ]
```

I am running the lastest `p4c-bm2-ss` with the following options:
`./build/p4c-bm2-ss --p4-14 action_replication.p4 --p4runtime-as-json --p4runtime-file p4info.json`

**Comment by mbudiu-vmw** [comment]
The compiler actually does replicate action a1, once for each table that uses it; unfortunately it uses the same @name annotation for both, because the annotation preserves the original name. Logically these actions should be named based on the table that uses them, c1.t1.a1 and c1.t2.a1.

**Comment by antoninbas** [comment]
In the p4runtime case, ideally it would show up as a single action `c1.a1`, just like it does in the bmv2 JSON.

**Comment by sethfowler** [comment]
We can deduplicate this stuff in the serializer code in the short term. In the long term it would be much better to ensure that the names that the compiler generates are unique, and then assert in p4RuntimeSerializer that there are no duplicates. As Mihai says, logically these actions should be named in such a way as to reflect the hierarchical structure of the program.

**Comment by antoninbas** [comment]
Given the current P4_16 syntax, I am having trouble seeing why "logically" the table name should appear in the full action name. But I imagine that in a future version, a table could bind differently to a given action multiple times, in which case a local name may be needed for each binding.

**Comment by sethfowler** [comment]
Yeah, there are discussions about doing exactly that.

**Comment by mbudiu-vmw** [comment]
The reason the compiler replicates an action once for each table is that it is then ready to apply different optimizations to the actions in each table. Today we don't have any such optimizations, but this may be necessary. In particular, we talked about the ability to do code motion between different actions from different tables.

So the action name is only important for the control-plane really. The implementation of the action internally could be very different. The serializer could very well just generate the suffix of the action name - it should be unambiguous.

**Comment by sethfowler** [comment]
I suspect we'll have to revisit this after P4-16 is finalized.

For now, I can write a patch to deduplicate actions at serialization time.

**Comment by mbudiu-vmw** [comment]
There are two different actions in JSON. You should not deduplicate them.
The bug is that the @name annotation for these two actions is the same.

**Comment by sethfowler** [comment]
OK. That suggests that we should introduce the table name into the @name of the actions, then, as you suggested.

@antoninbas, will that work for you?

I consider either solution a temporary measure, since the way names are assigned to these actions is something that may be revisited in the P4-16 spec before it's finalized.

**Comment by mbudiu-vmw** [comment]
The control-plane naming isn't really in the scope of the P4 spec; there is a separate working group for the API. The spec does have a section about it, though.

**Comment by sethfowler** [comment]
It's in scope insofar as we may introduce new syntax to clarify the naming.

**Comment by mbudiu-vmw** [comment]
The fix belongs to the LocalizeAllActions pass.

**Comment by sethfowler** [comment]
Thanks.

**Comment by mbudiu-vmw** [comment]
Another issue to consider is that we allow actions to be called directly by controls or other actions.
For the bmv2 target the compiler will inline the latter and will create "special" tables for the former.
These tables should not be exposed to the control plane, since their content should never be changed after initialization.

**Comment by antoninbas** [comment]
The control plane wants to operate on information that matches the original P4 program. Whether the compiler creates multiple copies of the action because of table-specific optimizations or something else is somewhat irrelevant to this.
@sethfowler so no, this doesn't really work for me. If the action is declared inside control `c1`, the name should be `c1.a1`, not `c1.<tname>.a1`. When I add an entry to a table (`t1` or `t2`) and I refer to action `c1.a1`, there is 0 ambiguity. The runtime parameters needed by the action, whose values are provided by the control-plane, remain the same independently of which table is using the action. If later on we introduce the multiple-binding feature, this last statement still holds true (however, when adding an entry to a table we will have to disambiguate and explicitly specify a binding, but AFAIK this affects the Table proto message, not the Action one).
@mbudiu-bfn I do see a single `c1.a1` action in the bmv2 JSON, so don't you remove one copy at some point?

**Comment by mbudiu-vmw** [comment]
If one copy is removed it is probably a bug somewhere. The IR has two actions inside.
The unpleasant thing is that these actions have the same @name annotation.
Today they have the same body too, but that's an accident.

**Comment by mbudiu-vmw** [comment]
My JSON has two copies of c1.a1, with ids 0 and 1.

**Comment by mbudiu-vmw** [comment]
The way this is done in JSON is through the list of action_ids for a table; that's how the table disambiguates the actions even if they have the same name.

**Comment by mbudiu-vmw** [comment]
OK, so then I will assume we don't have a bug in the LocalizeAllActions; it generates names as @antoninbas describes.

**Comment by antoninbas** [comment]
@mbudiu-vmw my bad I didn't scroll until the end of the action list, I see them both now...
