### ISSUE TITLE
merge a new node to IR by Visitor

### ISSUE THREAD

**Issue by Mohxen** [p4lang/p4c#3090]
Hello everyone and @mbudiu-vmw,

I would be very grateful if you can give me some hints. I want to merge a new node for example a TCP header to IR by a new pass in the frontend using Transform(Visitor). 

This code was mentioned for inserting a node and SpecializeBlocks, blocks, and findInsertions were not declared. I don't know how to define them (I am not familiar with blocks in p4). I want to use IR::Header* cont to create a header node.

const IR::Node* SpecializeBlocks::postorder(IR::P4Control* cont) {
    auto insertions = blocks->findInsertions(getOriginal());
    auto result = new IR::Vector<IR::Node>();
    result->push_back(cont);
    for (auto d : *insertions)
        result->push_back(d);
    return result;
}

**Comment by mbudiu-vmw** [comment]
Can you give an example with some input P4 programs that you want to process and what the output that you want to obtain is?

**Comment by Mohxen** [comment]
Thank you so much. I have three codes (1. all UDP packets go to port one, 2. all TCP packets go to port two,  and 3. all UDP packets go to port one and all TCP packets go to port two). I want to merge IR 1 and IR 2 to have an IR similar to IR 3. 
I started to do it by merging a TCP header with IR 1 in a new pass in the frontend. Please let me know if you need more information

**Comment by mbudiu-vmw** [comment]
In P4 there are no concepts of TCP, UDP, or port.
There are function calls and assignments.
It is easy to give such a particular example which is nice and well-behaved, but if I give you two random P4 programs can you explain what the merged program is supposed to do?

**Comment by hesingh** [comment]
If one would like to merge twoP4 programs, a tool sold from my company will do it.

https://mnkcg.com/products/p4-ansible/
