### ISSUE TITLE
Questions on where match_kind values should be allowed

### ISSUE THREAD

**Issue by jfingerh** [p4lang/p4c#3091]
The attached test program demonstrates some places where it appears that values of type match_kind, e.g. `exact`, `ternary`, appear to be unsupported by the current p4c compiler.  See the README.md file in the attached zip file for which p4test commands succeed, and which give errors.  It is not clear to me if any of the ones that give errors should succeed, or not.  Most of them involve attempts to use a match_kind as a constructor parameter of an extern object constructor.
[match-kind-issues1.zip](https://github.com/p4lang/p4c/files/8121434/match-kind-issues1.zip)

**Comment by jfingerh** [comment]
Example program was inspired by investigating how to use the externs defined in this PR: https://github.com/p4lang/p4c/pull/2739

**Comment by mbudiu-vmw** [comment]
There are several examples that should never work:
```
const tuple<match_kind> exact_once = {exact};
ValueLookupTable<exact_once, bit<8>, bit<16>>(1024) velut;
```
This won't work because exact_once is not a type, it is a variable.

Same for this:
```
    ValueLookupTable<(tuple<match_kind>) {exact}, bit<8>, bit<16>>(1024) lut3;
```
`{exact}` is a value, not a type, and in the type parameters you can only have types. You can have values in the constructor *arguments*.

**Comment by mbudiu-vmw** [comment]
But this should work:
```
    ValueLookupTable<tuple<match_kind>, bit<8>, bit<16>>(1024) lut3;
```

**Comment by mbudiu-vmw** [comment]
More precisely, see a working example in #3099.
I will submit a fix for the spec too.
