### ISSUE TITLE
Should structure-valued expressions with fields that are all compile-time known, itself be compile-time known?

### ISSUE THREAD

**Issue by jfingerh** [p4lang/p4c#3098]
Attached is an example program where that appears to not be the case.

```bash
$ p4test --version
p4test
Version 1.2.2.1 (SHA: 289431c0d BUILD: DEBUG)

$ git log -n 1 | head -n 3
commit 289431c0de84543adf26372fe6c157bdfcf76733
Author: Kamlesh Kumar <kamleshbhalui@gmail.com>
Date:   Sat Feb 19 07:33:53 2022 +0530
```

The following command gives the compile-time error shown.  It seems
that perhaps p4c consideres that a structure-valued expression is
never a compile-time known value, even if all field values are
compile-time known values.

Is that true?

If it is true now, is it reasonable to change things so that if all
field values are compile-time known values, then the structure-valued
expression as a whole is also considered a compile-time known value?

```bash
$ p4test v1model_valuelut_with_const_entries1.p4 
v1model_valuelut_with_const_entries1.p4(149): [--Werror=invalid] error: StructExpression: Cannot evaluate to a compile-time constant
        default_value = (my_result1_t) {val1=0, val2=0})
                                       ^^^^^^^^^^^^^^^^
```

The command below has a similar error message, probably for the same
root cause, but I am not sure since the error is less specific.  Note
that the first occurrence of 'const_entries' for extern instance named
lut1 gives no such compile-time error, so it seems that list
expressions that bottom out in all compile-time known values are
considered compile-time known values by p4c today.

```bash
$ p4test -DCONST_ENTRIES_WITH_STRUCT_TYPES v1model_valuelut_with_const_entries1.p4 
v1model_valuelut_with_const_entries1.p4(142): [--Werror=invalid] error: ListExpression: Cannot evaluate to a compile-time constant
        const_entries = {
                        ^
```
[v1model_valuelut_with_const_entries1.p4.txt](https://github.com/p4lang/p4c/files/8134051/v1model_valuelut_with_const_entries1.p4.txt)

**Comment by jafingerhut** [comment]
The latest version of the language spec says that structure initializer expressions are compile-time known values, but I recall that there is also an open PR proposing to remove all occurrences of structure initializer expressions, in favor of the newer structure-valued expressions, which are more generally useful.  I will open a PR suggesting that structure-valued expressions whose element are all compile-time known, should also be compile-time known, and we can discuss that in a future LDWG meeting to see if it is reasonable.

**Comment by mbudiu-vmw** [comment]
There is only one difficulty, which is perhaps an implementation difficulty, which is that there is no literal to denote an uninitialized header. So it may be impossible to rewrite a constant initializer such as `{ ... }` into a legitimate constant expression.

**Comment by jfingerh** [comment]
I understand that this is a problem, but it does not cause issues for structs, does it?

**Comment by mbudiu-vmw** [comment]
Only if the structs have header fields.

**Comment by mbudiu-vmw** [comment]
Theoretically it's not a problem, only practically. The implementation will not be on par with the spec until we solve this problem.

**Comment by jafingerhut** [comment]
I have created this spec issue as an attempt to move forward on the spec question of what a literal syntax to represent the value of "an invalid header" ought to be.  Note that `{}` might be a bad choice, for reasons described there: https://github.com/p4lang/p4-spec/issues/1021
