### ISSUE TITLE
Error in compiling P4 14 programs

### ISSUE THREAD

**Issue by drobinkent** [p4lang/p4c#3140]
I am trying to compile some P4 programs (https://bitbucket.org/lavanyaj/switch-compiler/src/master/mapper/p4_programs/) using the P4C compiler. I am using the following command as mentioned in the P4C readme. 

`p4c --target bmv2 --arch v1model --std p4-14 my-p4-14-prog.p4
`
However, the compilation fails and the following error message is shown 

```
$ p4c --target bmv2 --arch v1model --std p4-14 l2l3simple.p4
actions.p4(32): [--Wwarn=shadow] warning: 'ipv6_prefix' shadows '.ipv6_prefix'
action set_ipv6_prefix_ucast(ipv6_prefix){
                             ^^^^^^^^^^^
tables.p4(90)
table ipv6_prefix {
^
actions.p4(36): [--Wwarn=shadow] warning: 'ipv6_prefix' shadows '.ipv6_prefix'
action set_ipv6_prefix_xcast(ipv6_prefix){
                             ^^^^^^^^^^^
tables.p4(90)
table ipv6_prefix {
^
actions.p4(28): [--Wwarn=shadow] warning: 'vrf' shadows '.vrf'
action set_vrf(vrf) {
               ^^^
tables.p4(59)
table vrf {
^
[--Werror=type-error] error: on_hit is not a legal label (action name)
[--Werror=type-error] error: on_miss is not a legal label (action name)

```

Is the conversion mechanism of the P4C compiler working properly or I am missing something.

**Comment by mbudiu-vmw** [comment]
It looks to me like the program you are compiling is actually incorrect.
Unfortunately the compiler does not point to the correct place in the code where the error is, and because of this I will mark this as a bug. 
The problem is here:
```
            apply(check_ucast_ipv4) {
                on_hit {
                    apply(urpf_v4);
                    apply(ipv4_forwarding);
                }
                on_miss {
                    apply(igmp_snooping);
                    apply(ipv4_xcast_forwarding);
                }
            }
```

This applies the check_ucast_ipv4 table and switches on the action that is being executed. However, this table cannot have actions called `on_miss` and `on_hit`:
```
table check_ucast_ipv4 {
    reads {
        ipv4.dstAddr : exact;
    }
    actions {
        nop; /* FIX */
    }
    size : CHECK_UCAST_IPV4_SIZE;
}
```

If you want to check for hit or miss you have to change this to:

```
  apply(check_ucast_ipv4) {
                hit {
                    apply(urpf_v4);
                    apply(ipv4_forwarding);
                }
                miss {
                    apply(igmp_snooping);
                    apply(ipv4_xcast_forwarding);
                }
            }
```
