### ISSUE TITLE
Unused types in extern definitions

### ISSUE THREAD

**Issue by rst0git** [p4lang/p4c#3145]
Since commit https://github.com/p4lang/p4c/commit/8eebedea818a2c788e0675d052a170be904a8e7f, the compiler shows warnings such as:

```
/usr/local/share/p4c/p4include/bmv2/psa.p4(546): [--Wwarn=unused] warning: 'W' is unused
extern Counter<W, S> {
               ^
/usr/local/share/p4c/p4include/bmv2/psa.p4(575): [--Wwarn=unused] warning: 'W' is unused
extern DirectCounter<W> {
                     ^
```
As far as I understand, in the definition for the extern `DirectCounter` in PSA, `W` is used to set the width of values used by the control plane API.

Would it make sense to add an annotation that can be used to specify parameters used the control plane API to suppress this warning?

For example, something like:

```P4
@ControlPlaneAPI(W)
extern DirectCounter<W> {
  DirectCounter(PSA_CounterType_t type);
  void count();

  /*
  @ControlPlaneAPI
  {
    W    read<W>      (in TableEntry key);
    W    sync_read<W> (in TableEntry key);
    void set          (in TableEntry key, in W seed);
    void reset        (in TableEntry key);
    void start        (in TableEntry key);
    void stop         (in TableEntry key);
  }
  */
}
```

**Comment by mbudiu-vmw** [comment]
We also have a `@noWarn` annotation, which is arguably less informative.

**Comment by mbudiu-vmw** [comment]
Another problem is that "noWarn" does not seem to work in this case. This looks like a bug.
