### ISSUE TITLE
Unary + is accepted for all types

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4c#3153]
While reading the specifications and the yacc/bison parser I came across some interesting thing about the unary + operator.
It will be accepted even for string and boolean types.

The reason why it will be accepted for all types is because the parse does not create an AST for the unary + operator so no semantic anaylsis (type checking) is done on it.
```
    | "+" expression %prec PREFIX        { $$ = $2; }
```
The specifications needs to be changed to say unary+ is allowed on all types or there needs to be a new IR node for unary+ to be added which gets removed during semantic anaylsis is done after parsing.

**Comment by mbudiu-vmw** [comment]
It's better to just fix the compiler and only allow it for numeric types.
