### ISSUE TITLE
add a new backend to generate llvm ir

### ISSUE THREAD

**Issue by chiliao** [p4lang/p4c#3156]
I want to design a hardware target (eg a switch device) which supports RISC-V instruction for V1Model architecture. what should I do?

I mean execute the command like below：
> p4c --target risc-v-target --arch v1model risc-v-example.p4

I'm not sure if I need to add a new backend.

My idea is to add a new pass(to emit llvm ir) in the [simple_switch](https://github.com/p4lang/p4c/tree/main/backends/bmv2/simple_switch),convert the P4 IR to LLVM IR, and then generate the risc-v executable through the LLVM backend, is this idea feasible? Are there other cases to refer to?

**Comment by mbudiu-vmw** [comment]
You can already use the p4 to ebpf backend which generates C, and compile the C using a C compiler for RISC-V.

**Comment by mbudiu-vmw** [comment]
Note that we call it "ebpf", but we have a version that runs entirely in userspace by replacing ebpf data structures (maps) with standard C data structures.

**Comment by chiliao** [comment]
@mbudiu-vmw  Thanks for your reply. 

> we have a version that runs entirely in userspace by replacing ebpf data structures (maps) with standard C data structures.

can you tell me how to find the version to run the code in userspace?  Because we don't have an operating system running on our hardware target.

**Comment by chiliao** [comment]
@mbudiu-vmw I've found UBPF, but I'm afraid it's not what I need, my target device is not running an OS, is there any implementation for this currently?

**Comment by mbudiu-vmw** [comment]
The code generated by the ebpf compiler does not invoke any system calls. Just some library functions that you would need to port. So it should work without an OS. 

> is there any implementation for this currently?

what is "this"?

**Comment by jafingerhut** [comment]
@chiliao Can this issue be closed now?  Has your question been answered?
