### ISSUE TITLE
Error message for checking of types inside header does not say what the specialization is location is

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4c#3170]
Take:
```
header yy
{
  bit tt;
}
struct y
{
  yy[2] tt;
}
header t<tt>
{
  tt y;
}

typedef t ty;
typedef ty<y> tty;
```
Right now the compiler outputs:
```
t2.p4(11): [--Werror=type-error] error: Field 'y' of 'header t' cannot have type 'struct y'
  tt y;
     ^
t2.p4(5)
struct y
       ^
```
But it does not reference the last typedef line for the subsitution that had happened so it is not obvious where the problem is located.
I suspect this is an issue with most places of subsitutions too include functions.

**Comment by apinski-cavium** [comment]
Another issue is it does not tell you why this struct cannot be part of the header, it is the header stack that is the issue.

**Comment by mbudiu-vmw** [comment]
I would ask a different question: should this be even legal: `typedef t ty`.
I am tempted to resolve the problem you point out by saying "no", when you typedef you cannot partially specialize a type; if you use a generic type you must supply type arguments.

**Comment by mbudiu-vmw** [comment]
@apinski-cavium not sure that this is a true solution to the problem you are raising.

**Comment by apinski-cavium** [comment]
That is a different issue really.
You can see the issue still with:
```
header yy
{
  bit tt;
}
struct y
{
  yy[2] tt;
}
header t<tt>
{
  tt y;
}

typedef t<y> tty;
```
Which gives:
```
t2.p4(11): [--Werror=type-error] error: Field 'y' of 'header t' cannot have type 'struct y'
  tt y;
     ^
t2.p4(5)
struct y
       ^
```
No where is the line for the typedef is referenced.

**Comment by mbudiu-vmw** [comment]
Reopening for the last example.

**Comment by mbudiu-vmw** [comment]
@apinski-cavium how does the solution in #3182 look like?

**Comment by apinski-cavium** [comment]
> @apinski-cavium how does the solution in #3182 look like?

Looks good (just looked at the testcase to see how it would look).
