### ISSUE TITLE
Single underscore _ can not be used to match on bool type

### ISSUE THREAD

**Issue by lzhzero** [p4lang/p4c#3179]
In P4 tables const entries, `_` can not be used to match on bool type, only `true` or `false` can be used.

Here is an example.
```
bool b;
action A1() {}
action A2() {}

table T {
  key = { b : exact;}
  actions = {A1;A2;}
  const entries = {
    _ : A1();
  }
}
apply {T.apply();}
```

Here is the compiler output.
```
bug/test_match.p4(34): [--Werror=invalid] error: DefaultExpression invalid key expression
      _ : A1();
      ^
```

**Comment by mbudiu-vmw** [comment]
Is this true just for booleans?

**Comment by lzhzero** [comment]
Thanks for the hint!

Looks like  I should use `optional` match for boolean if I want to use wildcard.

**Comment by mbudiu-vmw** [comment]
Since the key has to match exactly, I don't think that _ would make sense.
Even for integers _ is translated into a mask expression, which would require a ternary match.
