### ISSUE TITLE
Casting to struct is allowed? but not always?

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4c#3233]
Take:
```
struct s
{
  bit t;
  bit t1;
}

s func(bit t, bit t1)
{
  return (s)(s)(s){t, t1};
}
s func1(s t1)
{
  return (s)(s)(s)t1;
}
```
func is allowed but func1 is not allowed? I would assume both would be rejected. It seems like the multiple casts are being removed leaving only the last one before doing type checking.

**Comment by mbudiu-vmw** [comment]
Casts are only allowed to base types. These should both be rejected. A structure- valued expression can specify a type but that's not a cast, although it intentionally looks like one.

**Comment by jnfoster** [comment]
Just to clarify: this isn't a structure-valued expression though, right? It's a tuple...

**Comment by apinski-cavium** [comment]
So there seems to be two bugs then. One dealing with (s){...} where {..} is not a structured-valued expression (and only a list) and one with extra casts. I missed that the structured-valued expression is the only one valid with the cast when I wrote the testcase too :).

**Comment by mbudiu-vmw** [comment]
Yes, it is a tuple. This seems like a useful feature, to specify the type of a list expression when it's intended to intialize a struct, so I would rather amend the spec than declare that the list expression is a bug.
