### ISSUE TITLE
Error when reassigning standard standard_metadata.egress_spec after ipv4_forward action

### ISSUE THREAD

**Issue by gareging** [p4lang/p4c#3237]
Hello,

I'm getting this error below when I am trying to reassign standard_metadata.egress_spec after the standard ipv4_forward action:
`
[--Werror=invalid] error: Program is not supported by this target, because table MyIngress.ipv4_lpm has multiple successors`

Here's what I'm trying to do: I'm applying ipv4_forward table, and then, if standard_metadata.egress_spec is greater than 2, I try to use ECNP hashing instead:

```
apply{
        .....
                    ipv4_lpm.apply();
                    if (standard_metadata.egress_spec > 2) {
    	                hash(standard_metadata.egress_spec, HashAlgorithm.crc16, (bit<16>)3,
                        { hdr.ipv4.srcAddr,
	                  hdr.ipv4.dstAddr,
                          hdr.ipv4.protocol
                        }, (bit<32>)2);
                    }
           ....
    }
```

Is the error I am getting is expected behaviour of the p4c compiler for the bmv2 simple_switch target? I'm using the recent version of the P4 tutorial VM to run this code.

**Comment by mbudiu-vmw** [comment]
Indeed, the assignment to egress_spec is not the problem, and neither is the code that you have pasted.

**Comment by gareging** [comment]
Please see the code below:
`

/* -*- P4_16 -*- */
#include <core.p4>
#include <v1model.p4>

const bit<16> TYPE_IPV4 = 0x800;


/*************************************************************************
*********************** H E A D E R S  ***********************************
*************************************************************************/

#define TYPE1 0
#define TYPE2 1
#define TYPE3 2


typedef bit<9>  egressSpec_t;
typedef bit<48> macAddr_t;
typedef bit<32> ip4Addr_t;

header ethernet_t {
    macAddr_t dstAddr;
    macAddr_t srcAddr;
    bit<16>   etherType;
}

header ipv4_t {
    bit<4>    version;
    bit<4>    ihl;
    bit<8>    diffserv;
    bit<16>   totalLen;
    bit<16>   identification;
    bit<3>    flags;
    bit<13>   fragOffset;
    bit<8>    ttl;
    bit<8>    protocol;
    bit<16>   hdrChecksum;
    ip4Addr_t srcAddr;
    ip4Addr_t dstAddr;
}

struct metadata {
}

struct headers {
    ethernet_t   ethernet;
    ipv4_t       ipv4;
}

/*************************************************************************
*********************** P A R S E R  ***********************************
*************************************************************************/

parser MyParser(packet_in packet,
                out headers hdr,
                inout metadata meta,
                inout standard_metadata_t standard_metadata) {

    state start {
        transition parse_ethernet;
    }

    state parse_ethernet {
        packet.extract(hdr.ethernet);
        transition select(hdr.ethernet.etherType) {
            TYPE_IPV4: parse_ipv4;
            default: accept;
        }
    }

    state parse_ipv4 {
        packet.extract(hdr.ipv4);
        transition accept;
    }

}

/*************************************************************************
************   C H E C K S U M    V E R I F I C A T I O N   *************
*************************************************************************/

control MyVerifyChecksum(inout headers hdr, inout metadata meta) {
    apply {  }
}


/*************************************************************************
**************  I N G R E S S   P R O C E S S I N G   *******************
*************************************************************************/

control MyIngress(inout headers hdr,
                  inout metadata meta,
                  inout standard_metadata_t standard_metadata) {

    register<bit<2>>(1) type_reg;

    action drop() {
        mark_to_drop(standard_metadata);
    }

    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
        standard_metadata.egress_spec = port;
        hdr.ethernet.srcAddr = hdr.ethernet.dstAddr;
        hdr.ethernet.dstAddr = dstAddr;
        hdr.ipv4.ttl = hdr.ipv4.ttl - 1;
    }

    table ipv4_lpm {
        key = {
            hdr.ipv4.dstAddr: lpm;
        }
        actions = {
            ipv4_forward;
            NoAction;
        }
        size = 1024;
    }

    apply {
        if (hdr.ipv4.isValid()) {
	    bit<2> type;
	    type_reg.read(type, 0);
	    if (type == TYPE2) {
		ipv4_lpm.apply();
	    }
	    else {
		    ipv4_lpm.apply();
		    if (standard_metadata.egress_spec > 2) {
			hash(standard_metadata.egress_spec, HashAlgorithm.crc16, (bit<16>)3,
			{ hdr.ipv4.srcAddr,
			  hdr.ipv4.dstAddr,
			  hdr.ipv4.protocol
			}, (bit<32>)2);
		    }
		
	    }
	 }
     }
}

/*************************************************************************
****************  E G R E S S   P R O C E S S I N G   *******************
*************************************************************************/

control MyEgress(inout headers hdr,
                 inout metadata meta,
                 inout standard_metadata_t standard_metadata) {
    apply {  }
}

/*************************************************************************
*************   C H E C K S U M    C O M P U T A T I O N   **************
*************************************************************************/

control MyComputeChecksum(inout headers  hdr, inout metadata meta) {
     apply {
        update_checksum(
        hdr.ipv4.isValid(),
            { hdr.ipv4.version,
              hdr.ipv4.ihl,
              hdr.ipv4.diffserv,
              hdr.ipv4.totalLen,
              hdr.ipv4.identification,
              hdr.ipv4.flags,
              hdr.ipv4.fragOffset,
              hdr.ipv4.ttl,
              hdr.ipv4.protocol,
              hdr.ipv4.srcAddr,
              hdr.ipv4.dstAddr },
            hdr.ipv4.hdrChecksum,
            HashAlgorithm.csum16);
    }
}

/*************************************************************************
***********************  D E P A R S E R  *******************************
*************************************************************************/

control MyDeparser(packet_out packet, in headers hdr) {
    apply {
        packet.emit(hdr.ethernet);
        packet.emit(hdr.ipv4);
    }
}

/*************************************************************************
***********************  S W I T C H  *******************************
*************************************************************************/

V1Switch(
MyParser(),
MyVerifyChecksum(),
MyIngress(),
MyEgress(),
MyComputeChecksum(),
MyDeparser()
) main;
`

**Comment by mbudiu-vmw** [comment]
Indeed, in your code you have two different applications of table ipv4_lpm.
The compiler probably synthesizes another table after the second application.
So in the resulting code table ipv4 is followed by no table or some table, depending on the value of `type`.
How about lifting the application before the if?
```
ipv4_lpm.apply();
if (type != TYPE2) {
   if (standard_metadata...)
}
```

**Comment by gareging** [comment]
> Indeed, in your code you have two different applications of table ipv4_lpm. The compiler probably synthesizes another table after the second application. So in the resulting code table ipv4 is followed by no table or some table, depending on the value of `type`. How about lifting the application before the if?
> 
> ```
> ipv4_lpm.apply();
> if (type != TYPE2) {
>    if (standard_metadata...)
> }
> ```

That did not help - I'm getting the same error. Only if I initialize the variable type using any value, instead of reading it from the register, I manage to compile the code.

**Comment by mbudiu-vmw** [comment]
I just tried it and it worked for me.

**Comment by mbudiu-vmw** [comment]
```
	    ipv4_lpm.apply();
	    if (type != TYPE2) {
		if (standard_metadata.egress_spec > 2) {
		    hash(standard_metadata.egress_spec, HashAlgorithm.crc16, (bit<16>)3,
		    { hdr.ipv4.srcAddr,
			  hdr.ipv4.dstAddr,
			hdr.ipv4.protocol
		    }, (bit<32>)2);
		}
            }
```

**Comment by mbudiu-vmw** [comment]
`./p4c-bm2-ss -o x.json x.p4`

**Comment by gareging** [comment]
It's interesting, maybe my version of the compiler is outdated?

Here's the code I'm trying to compile:

```
/* -*- P4_16 -*- */
#include <core.p4>
#include <v1model.p4>

const bit<16> TYPE_IPV4 = 0x800;


/*************************************************************************
*********************** H E A D E R S  ***********************************
*************************************************************************/

#define TYPE1 0
#define TYPE2 1
#define TYPE3 2


typedef bit<9>  egressSpec_t;
typedef bit<48> macAddr_t;
typedef bit<32> ip4Addr_t;

header ethernet_t {
    macAddr_t dstAddr;
    macAddr_t srcAddr;
    bit<16>   etherType;
}

header ipv4_t {
    bit<4>    version;
    bit<4>    ihl;
    bit<8>    diffserv;
    bit<16>   totalLen;
    bit<16>   identification;
    bit<3>    flags;
    bit<13>   fragOffset;
    bit<8>    ttl;
    bit<8>    protocol;
    bit<16>   hdrChecksum;
    ip4Addr_t srcAddr;
    ip4Addr_t dstAddr;
}

struct metadata {
}

struct headers {
    ethernet_t   ethernet;
    ipv4_t       ipv4;
}

/*************************************************************************
*********************** P A R S E R  ***********************************
*************************************************************************/

parser MyParser(packet_in packet,
                out headers hdr,
                inout metadata meta,
                inout standard_metadata_t standard_metadata) {

    state start {
        transition parse_ethernet;
    }

    state parse_ethernet {
        packet.extract(hdr.ethernet);
        transition select(hdr.ethernet.etherType) {
            TYPE_IPV4: parse_ipv4;
            default: accept;
        }
    }

    state parse_ipv4 {
        packet.extract(hdr.ipv4);
        transition accept;
    }

}

/*************************************************************************
************   C H E C K S U M    V E R I F I C A T I O N   *************
*************************************************************************/

control MyVerifyChecksum(inout headers hdr, inout metadata meta) {
    apply {  }
}


/*************************************************************************
**************  I N G R E S S   P R O C E S S I N G   *******************
*************************************************************************/

control MyIngress(inout headers hdr,
                  inout metadata meta,
                  inout standard_metadata_t standard_metadata) {

    register<bit<2>>(1) type_reg;

    action drop() {
        mark_to_drop(standard_metadata);
    }

    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
        standard_metadata.egress_spec = port;
        hdr.ethernet.srcAddr = hdr.ethernet.dstAddr;
        hdr.ethernet.dstAddr = dstAddr;
        hdr.ipv4.ttl = hdr.ipv4.ttl - 1;
    }

    table ipv4_lpm {
        key = {
            hdr.ipv4.dstAddr: lpm;
        }
        actions = {
            ipv4_forward;
            NoAction;
        }
        size = 1024;
    }

    apply {
        if (hdr.ipv4.isValid()) {
	    bit<2> type;
	    type_reg.read(type, 0);
	    if (type == TYPE2) {
		ipv4_lpm.apply();
	    }
	    else {
	      ipv4_lpm.apply();
	      if (type != TYPE2) {
		if (standard_metadata.egress_spec > 2) {
		    hash(standard_metadata.egress_spec, HashAlgorithm.crc16, (bit<16>)3,
		    { hdr.ipv4.srcAddr,
			  hdr.ipv4.dstAddr,
			hdr.ipv4.protocol
		    }, (bit<32>)2);
		}
              }
	    }
	}
    }
}

/*************************************************************************
****************  E G R E S S   P R O C E S S I N G   *******************
*************************************************************************/

control MyEgress(inout headers hdr,
                 inout metadata meta,
                 inout standard_metadata_t standard_metadata) {
    apply {  }
}

/*************************************************************************
*************   C H E C K S U M    C O M P U T A T I O N   **************
*************************************************************************/

control MyComputeChecksum(inout headers  hdr, inout metadata meta) {
     apply {
        update_checksum(
        hdr.ipv4.isValid(),
            { hdr.ipv4.version,
              hdr.ipv4.ihl,
              hdr.ipv4.diffserv,
              hdr.ipv4.totalLen,
              hdr.ipv4.identification,
              hdr.ipv4.flags,
              hdr.ipv4.fragOffset,
              hdr.ipv4.ttl,
              hdr.ipv4.protocol,
              hdr.ipv4.srcAddr,
              hdr.ipv4.dstAddr },
            hdr.ipv4.hdrChecksum,
            HashAlgorithm.csum16);
    }
}

/*************************************************************************
***********************  D E P A R S E R  *******************************
*************************************************************************/

control MyDeparser(packet_out packet, in headers hdr) {
    apply {
        packet.emit(hdr.ethernet);
        packet.emit(hdr.ipv4);
    }
}

/*************************************************************************
***********************  S W I T C H  *******************************
*************************************************************************/

V1Switch(
MyParser(),
MyVerifyChecksum(),
MyIngress(),
MyEgress(),
MyComputeChecksum(),
MyDeparser()
) main;

```

And here's the error:
```

p4@p4:~/tutorials/exercises/basic$ p4c-bm2-ss -o x.json basic.p4
basic.p4(108): [--Werror=invalid] error: Program is not supported by this target, because table MyIngress.ipv4_lpm has multiple successors
    table ipv4_lpm {
          ^^^^^^^^

```

**Comment by mbudiu-vmw** [comment]
Your compiler is not outdated, this restriction has been there at least 5 years.
Please compare your code with mine. You still have 2 invocations of the table.

**Comment by gareging** [comment]
> Your compiler is not outdated, this restriction has been there at least 5 years. Please compare your code with mine. You still have 2 invocations of the table.

I see what you mean, thank you. 

Please correct me if I am wrong - in the original version of my code, at the runtime, there was no way ipv4_lpm table could have been invoked twice; however, the compiler threw an error. Is that something that should be fixed or do I need to close this issue?

**Comment by mbudiu-vmw** [comment]
Yes, at runtime there is at most one invocation, but the static control-flow graph has two instances of the table.
The static graph is the one mapped to the "hardware" and it has to obey the hardware restrictions.
This cannot be fixed in BMv2. Perhaps the compiler can be smarter about it, but that in general is not easy.
But the easiest fix is for you to change the program. I find it more readable too with one invocation of the table.

**Comment by jfingerh** [comment]
I mean, technically BMv2 _could_ be made more general, even allowing the same table to be applied more than once in the same control, but that would be a significant change to the BMv2 JSON file format and the p4c BMv2 back end code, and would require someone willing to enhance both of those things, as well as the part of the p4lang/behavioral-model code that would need updating for such an enhancement.

No one I know if is planning such enhancements, though.

@gareging Are you willing to close this issue, now that your questions appear to have been answered?

**Comment by gareging** [comment]
Yes, sure!
