### ISSUE TITLE
Is clone3 abandoned?

### ISSUE THREAD

**Issue by lifengfan13** [p4lang/p4c#3272]
/home/lff/Desktop/SDN/P4/In-band-Network-Telemetry/P4-Lint/p4src/int.p4(38): [--Wwarn=deprecated] warning: clone3: Using deprecated feature clone3. Please use 'clone_preserving_field_list' instead
                clone3(CloneType.I2E, 100, standard_metadata);
                ^^^^^^
/usr/share/p4c/p4include/v1model.p4(604)
extern void clone3<T>(in CloneType type, in bit<32> session, in T data);
            ^^^^^^
/usr/share/p4c/p4include/v1model.p4(604): [--Werror=unknown] error: clone3: unknown extern function
extern void clone3<T>(in CloneType type, in bit<32> session, in T data);

**Comment by mbudiu-vmw** [comment]
It is, as the message says, it has been replaced with clone_preserving_field_lists.

**Comment by lifengfan13** [comment]
> It is, as the message says, it has been replaced with clone_preserving_field_lists.
clone3(CloneType.I2E, 100, standard_metadata); doesn't work now, are there any other options?

**Comment by mbudiu-vmw** [comment]
There is no way to clone the standard Metadata. You have to copy the fields you need to the user Metadata.

**Comment by lifengfan13** [comment]
> It is, as the message says, it has been replaced with clone_preserving_field_lists.

Hello, I found that clone_preserving_field_lists can only pass local metadata, how can I pass standard_metadata

**Comment by lifengfan13** [comment]
> There is no way to clone the standard Metadata. You have to copy the fields you need to the user Metadata.

Thank you

**Comment by jafingerhut** [comment]
Everything Mihai has said in comments above is correct.  I simply wanted to mention that these facts, and a lot of other useful details about the v1model architecture as implemented on the simple_switch software switch, can be found on this page (the link takes you to the section describing the mechanism for preserving user-defined metadata fields with the new clone, resubmit, and recirculate operations, including the issue with standard metadata fields): https://github.com/p4lang/behavioral-model/blob/main/docs/simple_switch.md#notes-on-recirculate-resubmit-and-clone-operations

**Comment by jfingerh** [comment]
@lifengfan13 OK to close this issue, if your questions were answered to your satisfaction?
