### ISSUE TITLE
Consider relaxing the first-time contributor restrictions

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#3276]
There are some new options that relax the restrictions for first-time contributors. This means we do not always have to automatically approve workflows by first-time contributors, which sometimes can lead to workflow execution being stuck for hours/days.

https://github.blog/changelog/2021-07-01-github-actions-new-settings-for-maintainers/

**Comment by mbudiu-vmw** [comment]
I don't think I have permissions to do that, but I don't regard this as a big problem; we don't have that many first-time contributors.

**Comment by fruffy** [comment]
Well, it is happening frequently enough to become noticeable. I do approve a fair bit of pull requests. In particular, first-time contributors who push frequently are constantly blocked waiting for one of us to approve. I think the rules might be too strict in this case.
