### ISSUE TITLE
{1w1, 1w1}[0] is not a known at compile time constant

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4c#3283]
Take:
```
const int a = {1w1, 1w1} [0];
```
I would have expected this to be valid just for the same reason why:
```
const tuple<bit, bit> c = {1w1, 1w1};
const int a = c[0];
```
is valid.
The error message even makes it seems like it should be too:
```
const3.p4(2): [--Werror=type-error] error: Indexing ListExpression[0] applied to non-array and non-tuple type tuple<bit<1>, bit<1>>
const int a = {1w1, 1w1}[0];
              ^^^^^^^^^^^^^
const3.p4(2): [--Werror=type-error] error: ListExpression[0]: Cannot evaluate initializer to a compile-time constant
const int a = {1w1, 1w1}[0];
              ^^^^^^^^^^^^^
```
The error message says applied Indexing only applies to a tuple type (or a header stack type) and then lists a tuple type.

**Comment by mbudiu-vmw** [comment]
A list expression can be used to initialize a tuple, but it is not a tuple.
The first message is indeed strange.

**Comment by mbudiu-vmw** [comment]
In fact we don't have a tuple literal.

**Comment by apinski-cavium** [comment]
The specifications has the following though:
```
The type of a list expression is a tuple type (Section [#sec-synth-types]).
```
Hmm, so is it a tuple type or not?

**Comment by apinski-cavium** [comment]
This relates to https://github.com/p4lang/p4-spec/issues/1062 also.
