### ISSUE TITLE
warning for unsigned fixed width shift left is twice

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4c#3289]
Take:
```
bit<5> f(in int<3> a)
{
  return (5w1) << 6;
}
```
p4c produces:
```
shiftoverflow.p4(3): [--Wwarn=overflow] warning: <<: Shifting 5-bit value with 6
  return (5w1) << 6;
         ^^^^^^^^^^
shiftoverflow.p4(3): [--Wwarn=mismatch] warning: 5w64: value does not fit in 5 bits
  return (5w1) << 6;
         ^^^^^^^^^^
```

If we change 6 to 5, the first warning is gone but maybe it should not be; I think there is an off by one error.

The second warning is another interesting one as I thought shifts have a well defined behavior always. How can there be a mismatch?
Also the specification only talks about overflow for the signed case and no overflow for the unsigned case so both of these warnings should not be there.

**Comment by mbudiu-vmw** [comment]
Perhaps the spec can be improved, but I think from an usability point of view all these warnings are useful.
