### ISSUE TITLE
How to determine if a constant value is signed or unsigned? 

### ISSUE THREAD

**Issue by usha1830** [p4lang/p4c#3308]
I am stumbling upon this very basic question about determining the signed-ness of a constant.

Strength reduction pass in frontend converts `a - constant => a + (-constant).`
Example: 
`a - 1 => a + (-1)`
if a is bit<2> type, the constant -1 is represented as 2w3 making the expression `a + 2w3`. Is this correct?

At a later point, I need to convert this expression to subtraction if the constant value is negative.

Thanks!

**Comment by mbudiu-vmw** [comment]
IR::Constant has a type field.

**Comment by mbudiu-vmw** [comment]
If the values are unsigned then the constant will never be negative.

**Comment by usha1830** [comment]
```
 // Replace `a - constant` with `a + (-constant)`
    if (expr->right->is<IR::Constant>()) {
        auto cst = expr->right->to<IR::Constant>();
        auto neg = new IR::Constant(cst->srcInfo, **cst->type**, -cst->value, cst->base, true);

```
The type is same as the original constants type which would be bit<2> in the example. bit types are unsigned per the specification. So the value will be considered unsigned (2w3), correct?

**Comment by mbudiu-vmw** [comment]
The compiler can change the original type if casts are inferred. In your example 2w3 is unsigned. 2s3 would be signed.

**Comment by usha1830** [comment]
The intermediate P4 after `strengthReduction` (using --top4) shows the constant as `2w3`. Need to check if it is indeed unsigned.
Thanks a lot for the pointers!!
