### ISSUE TITLE
Annoying warnings about counter width type parameter not being used.

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4c#3319]
Attached is a trivial program that illustrates the problem. [emit_struct.p4.txt](https://github.com/p4lang/p4c/files/8684592/emit_struct.p4.txt)

When compiled, it produces the following bogus warnings:
```
$ ../../../../build/p4c-ebpf --arch psa --target kernel -o emit_struct.c emit_struct.p4
Setting XDP2TC 'meta' mode by default.
/media/psf/Home/trees/org/p4c/build/p4include/psa.p4(594): [--Wwarn=unused] warning: 'W' is unused
extern Counter<W, S> {
               ^
/media/psf/Home/trees/org/p4c/build/p4include/psa.p4(623): [--Wwarn=unused] warning: 'W' is unused
extern DirectCounter<W> {
                     ^
emit_struct.p4(102): [--Werror=target-error] error: Cannot emit a non-header type hdr
        pkt.emit(hdr);
                 ^^^
```

There are couple of ways to get rid of them:

1. Easiest: add `@noWarn("unused")` before the definitions of `Counter` and `DirectCounter` externs in `psa.p4`
2. Better: change the compiler and the spec to allow type arguments to accept annotations Then change `DirectCounter<W>` to `DirectCounter<@noWarn("unused") W>` and do the same for the `Counter`
3. The most radical: Given that the parameter `W` is not used in the data plane and, most probably it is not used in the control plane APIs either, remove it and provide a different mechanism to define counter width, but that would be a general  PSA issue :)

**Comment by mbudiu-vmw** [comment]
I actually don't see these warnings. We actually added `@noWarn` in https://github.com/p4lang/p4c/pull/3147 to some psa.p4 files. Can you check whether you are using a recent version?

**Comment by vgurevich** [comment]
@mbudiu-vmw -- thanks! I think that somehow my install directory contained one more psa.p4 file and that one was old. 
```
$ ls -lt `find ../../../../ -name psa.p4`
-rw-rw-r-- 1 vgurevich vgurevich 31802 May 12 23:22 ../../../../build/p4include/psa.p4
-rw-rw-r-- 1 vgurevich vgurevich 29685 May  5 18:42 ../../../../build/p4include/bmv2/psa.p4
-rw-rw-r-- 1 vgurevich vgurevich 29088 May  5 18:42 ../../../../build/p4include/dpdk/psa.p4
-rw-r--r-- 1 vgurevich vgurevich 29685 May  5 18:35 ../../../../install/share/p4c/p4include/bmv2/psa.p4
-rw-r--r-- 1 vgurevich vgurevich 29088 May  5 18:35 ../../../../install/share/p4c/p4include/dpdk/psa.p4
-rw-rw-r-- 1 vgurevich vgurevich 29685 May  5 18:35 ../../../../p4include/bmv2/psa.p4
-rw-rw-r-- 1 vgurevich vgurevich 29088 May  5 18:35 ../../../../p4include/dpdk/psa.p4
-rw-r--r-- 1 vgurevich vgurevich 31596 Mar 25  2020 ../../../../install/share/p4c/p4include/psa.p4
```

Once I completely cleared the contents of my install directory and ran `make install` again, the warnings disappeared.

Having said that, I am still not convinced that having an annotation on the whole extern is the better method, compared to other options I listed.
