### ISSUE TITLE
The check for action calls if inside parser or function is in different locations

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4c#3344]
I cannot test this change but I found this while trying to make sure my compiler rejected calls to actions in the correct location.
The check for parser context is in `TypeInference::actionCall` while the check for function context is in `TypeInference::postorder(IR::MethodCallExpression*` right before the call to actionCall.
It was just odd to find the checks in different locations and all.

**Comment by mbudiu-vmw** [comment]
I am not sure what to do about this issue, so I will close it.
