### ISSUE TITLE
Compiler Bug: parser1.p4(13): MyParser();: expected method call

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4c#3359]
I was doing some testing with parser and the type system around them and found this issue.

Take:
```
parser mypt(in bit tt);
package mypack(mypt t);

parser MyParser(in bit tt) {
  state start {
    transition select(tt) {
     0: accept;
     _: reject;
   }
 }
}
parser MyParser1(in bit tt) {
  mypt t = MyParser();
  state start {
    t.apply(tt);
    transition select(tt) {
     0: accept;
     _: reject;
   }
 }
}

mypack(MyParser1()) main;
```

This gives:
```
apinski@xeond:~/src/p4/p4c/build$ ./p4c parser1.p4
In file: /home/apinski/src/p4/p4c/frontends/p4/simplifyDefUse.cpp:1462
Compiler Bug: parser1.p4(13): MyParser();: expected method call
  mypt t = MyParser();
           ^^^^^^^^^^
```

If you comment out the constructor you get this compiler bug:
```
In file: /home/apinski/src/p4/p4c/frontends/p4/inlining.cpp:401
Compiler Bug: parser1.p4(13): @name("t") mypt t_0/t expected a constructor parameter
  mypt t;// = MyParser();
  ^^^^^^^
```

If you comment out the constructor and add `t =  MyParser();` in the start state, you get the original compiler bug (again) but for that statement instead of the variable definition.

**Comment by mbudiu-vmw** [comment]
The assumption is that parsers, controls, and packages are always instantiated using "instantiations"  and not "declarations" with initializers.
Initializers can be used for externs.

The spec does not really require this, but I will implement this restriction in the compiler.
(Alternatively, the compiler could allow declarations and could convert them automatically to instantiations.)

**Comment by mbudiu-vmw** [comment]
In fact there was a check, but it didn't apply to Type_Parser, just to P4PArser.

**Comment by apinski-cavium** [comment]
> The assumption is that parsers, controls, and packages are always instantiated using "instantiations" and not "declarations" with initializers.
> 
> The spec does not really require this, but I will implement this restriction in the compiler. (Alternatively, the compiler could allow declarations and could convert them automatically to instantiations.)

In my front-end, I had originally rejected all parsers (and controls) type for variables and I just happen to test p4c yesterday because I was finalizing the way parser type compatibility checks and ran into this compiler bug. I had changed the restrictions on my compiler but I think having restrictions is actually not a bad thing.

**Comment by apinski-cavium** [comment]
> The spec does not really require this
Actually it does:
```
In addition, variables of type  `parser`, `control`, `package`,
or `extern` types must be declared using instantiations (see Section [#sec-instantiations]).
```
So there is no need to change the spec.
