### ISSUE TITLE
Which IR fields does the Transform visitor actually cover?

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#3390]
We are writing a visitor that replaces `Type_Varbits` with a special custom type that has concrete information about the assigned width of the varbit. For that, we are trying to use a visitor that replaces all Type_Varbit in the program. However, we have noticed that postorder and preorder do not seem to walk many fields. 
For example, 
`const IR::Node* ConvertVarbits::postorder(IR::Type_Varbits* varbit) override;`
as a visitor function is never called. 

Is there a good way to figure out what IR nodes we need to cover to fully replace a certain type in a P4 program? We are aware that `expression->type` is not covered, for example. 

Or what is the best way to achieve this?

**Comment by mbudiu-vmw** [comment]
A visitor should always traverse the entire ir tree. VisitDagOnce controls whether shared children are visited multiple times. You can use the -Tnode:5 flag to enable logging in the node.cpp file to see all visited nodes. Note that nodes in the typeMap are not visited since they are not part of the IR tree. The expression->type field is never visited.

**Comment by fruffy** [comment]
Thanks for the clarification! Figured out the issue. When visiting an expression, we were not fully missing the type of the expression (e.g., complex types such as `Type_Structlike`). For reference, this is how our minimal type replacement visitor now looks like:
```cpp
class ConvertVarbits : public Transform {
    P4::ReferenceMap* refMap;
    P4::TypeMap* typeMap;

 public:
    ConvertVarbits(P4::ReferenceMap* refMap, P4::TypeMap* typeMap)
        : refMap(refMap), typeMap(typeMap) {
        CHECK_NULL(refMap);
        CHECK_NULL(typeMap);
        setName("ConvertVarbits");
        visitDagOnce = false;
    }

    const IR::Node* ConvertVarbits::postorder(IR::Type_Varbits* varbit) {
        auto varbitType = new IR::Sized_Type_Varbits(varbit->size, varbit->expression);
        return varbitType;
    }

    const IR::Node* ConvertVarbits::postorder(IR::Expression* expr) {
        auto varBits = ConvertVarbits(refMap, typeMap);
        expr->type = expr->type->apply(varBits)->checkedTo<IR::Type>();
        return expr;
    }
};
```

**Comment by mbudiu-vmw** [comment]
In general expr->type is not maintained by the compiler; think of it as a scratch area where you can save the type of an expression if you don't want to look it up in the typeMap.
