### ISSUE TITLE
Can we use p4c instead of p4c-bmv2 in the Bazel build rule?

### ISSUE THREAD

**Issue by lzhzero** [p4lang/p4c#3391]
https://github.com/p4lang/p4c/blob/f49d2282b61a55446b9c18f18bbe170f41fd9c96/bazel/p4_library.bzl#L143-L147

Currently the private attribute `_p4c` points to the `p4c-bmv2` binary.

We are interested in using Balze rules to compile for dpdk backend.
So can we set the rule to use `p4c` binary? Or maybe make the attribute non private so  people can choose it freely?

Thanks,
Zhang

**Comment by mbudiu-vmw** [comment]
I don't know anything about bazel, but it's a build system, so it should be able to express what you need.
Feel free to submit any changes that may be needed as a PR.
Can anyone with Bazel experience answer this question?

**Comment by lzhzero** [comment]
I will try to create a PR for that.

I think my question now is: what is the difference between `p4c` and `p4c-bm2-ss` or `p4c-dpdk` binaries generated by the default CMake?

I know that `p4c-bm2-ss` can use `--top4` to dump the P4 representations for different compiler stages. Are there other differences other than debugging support?

**Comment by mbudiu-vmw** [comment]
p4c-bm2-ss generates code for the bmv2 backend, a json file.
p4c-dpdk generates dpdk assembly code.
All such compilers share a common front-end, but have different back-ends. See the compiler-design.pptx document in the docs folde.
p4c is, as far as I know, a driver which invokes other compiler based on flags passed.
