### ISSUE TITLE
Compiler Bug: "Null cst" due to incorrect inf_int control parameter handling

### ISSUE THREAD

**Issue by vhavel** [p4lang/p4c#3394]
Blocks other than actions, like controls or functions, can have `int` parameters if they are called with a compile-time known constant value. The type checking, however, crashes when such `int` parameter is used in a binary expression  or a relation with a fixed-bit type on `Compiler bug: Null cst`:

```
control C1(int a, out bit<8> b) {
    apply {
        b = a + 1w8; 
    }
}
...and later...
C1.apply(1, r);
```

[typechecking_err1.p4.txt](https://github.com/p4lang/p4c/files/8891340/typechecking_err1.p4.txt)

The problem lies in TypeInference which attempts to convert all `int` parameters of every relation expression or binary arithmetic expression to a constant. Control parameters, however, cannot generally be converted to a single constant value.

**Comment by vhavel** [comment]
The crash is definitely not a desired behaviour, but should such constructs be rejected, or accepted by p4c? Current typechecking implementation assumes all `int` values are convertible to a constant, which is in line with this paragraph from the language specification:

> 7.1.6.5. Infinite-precision integers
> This type is reserved for integer literals and expressions that involve only literals. No P4 runtime value can have an int type; at compile time the compiler will convert all int values that have a runtime component to fixed-width types, according to the rules described below.

Is `int a` in the example a "runtime value"? In https://github.com/p4lang/p4c/pull/2360 it was established that `int` parameters of a control block are valid, if they are assigned only compile-time known constants, and are directionless. The language specification says (emphasis mine):

> 8.9.2. Implicit casts
> To keep the language simple and avoid introducing hidden costs, P4 only **implicitly casts from int to fixed-width types** and from enums with an underlying type to the underlying type. In particular, **applying a binary operation to an expression of type int and an expression with a fixed-width type will implicitly cast the int expression to the type of the other expression**.

which suggests using these `int` parameters in binary expressions is legal and therefore p4c should accept such code. Ideally with a warning in case of losing bits during the conversion:

> Casting an int value to a fixed-width type will preserve the least-significant bits. If truncation causes significant bits to be lost, the compiler should emit a warning.

which might be hard to implement because the block may be applied with various different constants.

**Comment by mbudiu-vmw** [comment]
I think I fixed this example, but in general this may be harder to solve.
