### ISSUE TITLE
Add compiler pass that attaches missing P4Runtime IDs to appropiate control plane objects

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#3448]
The P4RuntimeSerializer [tries to generate](https://github.com/p4lang/p4c/blob/main/control-plane/p4RuntimeSerializer.cpp#L464) deterministic IDs for control plane objects if they are missing the `@id` annotation. However, this is done in a fairly ad-hoc fashion when generating the P4Info file. It would be nice to instead have this step as a compiler pass in the simple_switch mid end. That way it is also possible to persist IDs for a given P4 program.

**Comment by mbudiu-vmw** [comment]
what is "persist"?

**Comment by fruffy** [comment]
Slightly wrong choice of words. The compiler pass would attach the `@id` annotation to nodes that are missing it. You can then emit the program using toP4 (persist in that sense).

**Comment by antoninb-ironfort** [comment]
I haven't looked at the code in a while, but this:

> It would be nice to instead have this step as a compiler pass in the simple_switch mid end

sounds wrong to me, as the whole P4Info-generation should be target-independent. `p4test` should be able to generate a P4Info file which is exactly the same as one generated by `p4c-bmv2-ss`. And the only dependency should really be frontend passes.

**Comment by antoninbas** [comment]
I haven't looked at the code in a while, but this:

> It would be nice to instead have this step as a compiler pass in the simple_switch mid end

sounds wrong to me, as the whole P4Info-generation should be target-independent. p4test should be able to generate a P4Info file which is exactly the same as one generated by p4c-bmv2-ss. And the only dependency should really be frontend passes.

**Comment by fruffy** [comment]
Currently, the P4Info generation depends on the `P4RuntimeArchHandlerIface`, which changes depending on the target and is also set by the target. This is why the pass can be called in the mid end the earliest. I would really like to reduce the dependencies to a minimum actually.

**Comment by antoninbas** [comment]
I may be wrong but `P4RuntimeArchHandlerIface` is supposed to depend on the _architecture_, not on the _target_. While adding code to a backend always makes that code target-dependent.
