### ISSUE TITLE
eBPF PTF tests are failing

### ISSUE THREAD

**Issue by osinstom** [p4lang/p4c#3453]
The eBPF PTF CI job is failing due to the new kernel (5.15) that has been released for Ubuntu 20.04 runner machine: https://github.com/actions/virtual-environments/commit/154099992ecb2fe92d55f51dc12827f47ee160da. 

@tatry and I are already looking into it. 

CC: @mbudiu-vmw

**Comment by fruffy** [comment]
Can this issue be closed or is there another fix coming?

**Comment by tatry** [comment]
Yes, it can be closed. Now tests should works for kernel 5.15.
