### ISSUE TITLE
Analyze the dependency of table

### ISSUE THREAD

**Issue by chiliao** [p4lang/p4c#3459]
I've seen the logic of p4-hlir before, which will analyzes the dependencies between tables. Is there a pass function in P4C to analyze table dependencies?

**Comment by mbudiu-vmw** [comment]
Try the p4-graphs compiler

**Comment by jafingerhut** [comment]
p4c-graph shows control flow graphs, but not data dependencies, true?

**Comment by mbudiu-vmw** [comment]
that  is correct, but I don't know of many tools for other languages that do that.

**Comment by jafingerhut** [comment]
It is especially useful to have such analysis for P4 programs for P4 developers that want to look for ways to minimize data dependencies where possible, or discover ones they were unaware of, to know why it takes as many stages as it does to implement in RMT-like hardware architectures.  That issue typically does not arise in other programming languages, I agree.
