### ISSUE TITLE
Compiler bug: Fall-through switch case statement broken

### ISSUE THREAD

**Issue by mukeshmv** [p4lang/p4c#3488]
I am hitting what seems like a basic issue with a fall-through action in a P4 switch statement.
I have a switch statement with a fall-through case, like so with the fall-through action at line number 105.

```
100 control aaa {
101   apply {  
102        ... 
103        meta.xxx = hdr.yyy;
104        switch (table1.apply().action_run) {
105            actionA:                         // fall-through
106            actionB: {
107                table2.apply();
108             }
109         }
110        table3.apply();
111     }
112 }
```

the json generated skips table 1, table 2 and directly jumps to table3

```
        {
          "name" : "tbl_aaa103",
          "source_info" : {
            "filename" : "aaa.p4",
            "line" : 103,
            "column" : 10,
            "source_fragment" : "= hdr.yyy; ..."
          },
          ... 
          "base_default_next" : "table3",
          "next_tables" : {
            "aaa103" : "table3"
          },

```

whereas if I change the code to remove just the fall-through action without any other changes

```
100 control aaa {
101   apply {  
102        ... 
103        meta.xxx = hdr.yyy;
104        switch (table1.apply().action_run) {
106            actionB: {
107                table2.apply();
108             }
109         }
110        table3.apply();
111     }
112 }
```

now the generated json properly points to table1 as the next stage.  

```
        {
          "name" : "tbl_aaa103",
          "source_info" : {
            "filename" : "aaa.p4",
            "line" : 103,
            "column" : 10,
            "source_fragment" : "= hdr.yyy; ..."
          },
          ... 
          "base_default_next" : "table1",
          "next_tables" : {
            "aaa103" : "table1"
          },
```

I am invoking p4c from the p4lang/p4c:latest docker image.

**Comment by jafingerhut** [comment]
@mukeshmv wrote a relatively small test program that he says also exhibits this issue, here: https://github.com/mukeshmv/p4_test/blob/master/test_pipeline.p4

I have compiled that program with these commands and a recent version of open source p4c (less than a month old), and it appears to me that at least the P4_16 intermediate output from the last mid-end pass looks correct to me.  I have not verified yet whether the BMv2 JSON file looks correct or wrong yet, but if the BMv2 JSON is wrong, then this sounds like it might be a bug in the p4c BMv2 back end code, not the front- or mid-end p4c code.

**Comment by jafingerhut** [comment]
I have examined the BMv2 JSON output file for the file `test_pipeline.p4` linked in my previous comment, and it does appear to contain a description of table `pre_tbl1`, but that table is not the "next_table" of any other table, so it appears like BMv2 would never execute it.  One of the possible actions of `pre_tbl1` is to modify a field called `meta.dropped`, but other actions of `pre_tbl1` do not do so, and the field `meta.dropped` is used in an `if` condition late in the ingress code, conditionally calling the `mark_to_drop(stdmeta)` extern function, or not, which cannot be correctly optimized away without changing the behavior of the program.  It does appear there is a bug here somewhere in the compiler.  Again, given that the P4_16 output from the last mid-end stage appears to be equivalent in behavior to the original program, I would strongly suspect that the bug is somewhere in the BMv2 back-end code of p4c.

**Comment by mbudiu-vmw** [comment]
This is the (relevant fragment of) output of the compiler for the program in the above comment:
```
        {
          "name" : "test_ingress.pre_tbl1",
          "id" : 1,
          "source_info" : {
            "filename" : "issue3488-bmv2.p4",
            "line" : 112,
            "column" : 10,
            "source_fragment" : "pre_tbl1"
          },
          "key" : [
            {
              "match_type" : "exact",
              "name" : "hdr.ipv4.dst_addr",
              "target" : ["ipv4", "dst_addr"],
              "mask" : null
            }
          ],
          "match_type" : "exact",
          "type" : "simple",
          "max_size" : 1024,
          "with_counters" : false,
          "support_timeout" : false,
          "direct_meters" : null,
          "action_ids" : [6, 5, 4, 0],
          "actions" : ["test_ingress.action1", "test_ingress.action2", "test_ingress.action3", "NoAction"],
          "base_default_next" : "test_ingress.post_tbl3",
          "next_tables" : {
            "test_ingress.action1" : "test_ingress.in_tbl2",
            "test_ingress.action2" : "test_ingress.in_tbl2",
            "test_ingress.action3" : "test_ingress.post_tbl3",
            "NoAction" : "test_ingress.post_tbl3"
          },
          "default_entry" : {
            "action_id" : 0,
            "action_const" : false,
            "action_data" : [],
            "action_entry_const" : false
          }
```

This looks correct to me.

**Comment by jafingerhut** [comment]
@mbudiu-vmw But did you see any other tables that had "test_ingress.pre_tbl1" as the value of its next_table key?  If not, and if "test_ingress.pre_tbl1" is not the initial table (which it isn't), then it will never be executed by BMv2, as far as I know.

**Comment by jafingerhut** [comment]
If we can create a small variant of this program that has a side effect in the execution of "test_ingress.pre_tbl1" that can be seen in the output packets of an STF test, that would be an even more sure way to confirm that there is a bug here.  If I find some time, I can try creating such a test program and STF test, but also happy if someone beats me to it.

**Comment by mukeshmv** [comment]
> This looks correct to me.

@mbudiu-vmw like what @jafingerhut said, the issue is in this part which belongs to line 155 (first line of apply block) from where the next_tables points to the post_tbl3 directly skipping the pre_tbl1 and in_tbl2.

```      
"tables" : [
        {
          "name" : "tbl_test_pipeline155",
          "id" : 0,
          "source_info" : {
            "filename" : "bmv2/test/test_pipeline.p4",
            "line" : 155,
            "column" : 38,
            "source_fragment" : "="
          },
          "key" : [],
          "match_type" : "exact",
          "type" : "simple",
          "max_size" : 1024,
          "with_counters" : false,
          "support_timeout" : false,
          "direct_meters" : null,
          "action_ids" : [9],
          "actions" : ["test_pipeline155"],
          "base_default_next" : "test_ingress.post_tbl3",
          "next_tables" : {
            "test_pipeline155" : "test_ingress.post_tbl3"
          },
          "default_entry" : {
            "action_id" : 9,
            "action_const" : true,
            "action_data" : [],
            "action_entry_const" : true
          }
        },
```

whereas if I remove the fall-through action1 then next_tables correctly points to pre_tbl1

```
      "tables" : [
        {
          "name" : "tbl_test_pipeline155",
          "id" : 0,
          "source_info" : {
            "filename" : "bmv2/test/test_pipeline.p4",
            "line" : 155,
            "column" : 38,
            "source_fragment" : "="
          },
          "key" : [],
          "match_type" : "exact",
          "type" : "simple",
          "max_size" : 1024,
          "with_counters" : false,
          "support_timeout" : false,
          "direct_meters" : null,
          "action_ids" : [9],
          "actions" : ["test_pipeline155"],
          "base_default_next" : "test_ingress.pre_tbl1",
          "next_tables" : {
            "test_pipeline155" : "test_ingress.pre_tbl1"
          },
          "default_entry" : {
            "action_id" : 9,
            "action_const" : true,
            "action_data" : [],
            "action_entry_const" : true
          }
        },
 ```

**Comment by jafingerhut** [comment]
I am having strange difficulties creating a PR for this repo from my branch, but this branch contains a slightly modified P4 program, plus an STF test, which demonstrates that pre_tbl1 is not being applied at all by BMv2, because its default action is definitely not being executed, and it has no entries installed.  If pre_tbl1 were being applied by BMv2, it would be sending all packets out port 2, but no packets are going to port 2.  https://github.com/jafingerhut/p4c/tree/add-issue3488-stf-test

All of the new files added in that branch contain 'issue3488' as part of their file names, and they are in the testdata directory.

**Comment by mbudiu-vmw** [comment]
Instead of pointing to the full repo fork perhaps you can attach here just the relevant files?
I may have fixed the bug, I'd like a check.
Surprising how this could live for so long.

**Comment by jafingerhut** [comment]
Attaching a zip file containing a P4 program and corresponding STF file that should pass, but fail, due to bug.
[issue3488.zip](https://github.com/p4lang/p4c/files/9374582/issue3488.zip)
