### ISSUE TITLE
Unexpected key field for BMV2 example

### ISSUE THREAD

**Issue by VolodymyrPeschanenkoIntel** [p4lang/p4c#3514]
The [match-on-exprs2-bmv2.p4](https://github.com/p4lang/p4c/blob/main/testdata/p4_16_samples/match-on-exprs2-bmv2.p4) finished with the messages for attached stf:
```
OrderedDict([('hdr.ethernet.srcAddr[22:18]', 'exact'), ('hdr.ethernet.dstAddr & 0x10101010101', 'exact'), ('etherType_less_10', 'exact')])
Exception  Unexpected key field hdr.ethernet.dstAddr
```
[match-on-exprs2-bmv2.stf.txt](https://github.com/p4lang/p4c/files/9489967/match-on-exprs2-bmv2.stf.txt)
[match-on-exprs2-bmv2-BMV2SimpleSwitchMidEnd_43_MidEndLast.p4.txt](https://github.com/p4lang/p4c/files/9489968/match-on-exprs2-bmv2-BMV2.SimpleSwitchMidEnd_43_MidEndLast.p4.txt)
[match-on-exprs2-bmv2.json.txt](https://github.com/p4lang/p4c/files/9489969/match-on-exprs2-bmv2.json.txt)

It looks like `p4c-bmv2-ss` generated invalid json file for `behavioral-model`.

**Comment by fruffy** [comment]
It looks like the correct behavior according to https://github.com/p4lang/p4c/blob/main/frontends/p4/tableKeyNames.cpp#L110 but the STF runner can not parse these types of names.

**Comment by mbudiu-vmw** [comment]
Can this be solved by adding some `@name` annotations on the key fields?

**Comment by mbudiu-vmw** [comment]
We actually have 2 STF parsers, one is in bmv2stf.py and the other one is in tools. We have never managed to replace the one in bmv2stf with the other one. Each of them has their own limitations.

**Comment by apinski-cavium** [comment]
> 

But the spec says something different.  See https://p4.org/p4-spec/docs/P4-16-working-spec.html#sec-computing-control-names

Which does not list & expressions in the table for keys and generated names.
Should this table be updated with what the reference compiler actually does and allows or is this an extension on top of the specifications. The spec seems to implies that the compiler should reject it if the @name is not supplied in this case even:
"All other kinds of expressions must be annotated with a @name annotation"

**Comment by mbudiu-vmw** [comment]
That is correct, the compiler indeed allows this while the spec does not.
I will file a bug with the spec.
