### ISSUE TITLE
Printing out a P4 file from midend/backend

### ISSUE THREAD

**Issue by ruijiefang** [p4lang/p4c#3526]
Hi, as part of a larger project, I would like to modify p4c such that I could read in a p4 program, perform some transformations on it in the midend, and then print out the IR to another syntactically valid p4 program. I took a quick look at the available printers in p4c, and I'm not sure if there is one that prints the intermediate representation back to a P4 program. Wondering if this functionality is implemented in p4c, and if so, where to look.

Many thanks in advance!

**Comment by jnfoster** [comment]
Look at the `toP4` inspector: https://github.com/p4lang/p4c/blob/main/frontends/p4/toP4/toP4.h

This can also be invoked from the command-line with the `--top4 <PassNamePattern>` option.

**Comment by jnfoster** [comment]
Closing as I think this resolves the question?

**Comment by ruijiefang** [comment]
@jnfoster oh nice! thanks for answering my question so quickly.

**Comment by jnfoster** [comment]
Actually, try running `p4c` with `--top4 ""` and you'll get a dump of the IR (as legal P4) after every front-end and mid-end pass.
