### ISSUE TITLE
Any blackbox in bmv2 ?

### ISSUE THREAD

**Issue by Johnny-dai-git** [p4lang/p4c#3529]
HI,

I am trying to convert some Tofino code into BMV2 architecture.

However, I can not find any comparative information in BMV2 as “blackbox” in Tofino.

Do I miss anything ?

Best Regards,

**Comment by mbudiu-vmw** [comment]
Tofino is a proprietary product, so I think you should address this question to the vendor.
This is the repository of the open-source p4c compiler, which does not directly support Tofino (it may be used by the Tofino compiler, but we have no way of knowing this). There is no Tofino-specific code in this repository.
I am also not sure what "blackbox" means in your question.
