### ISSUE TITLE
Question about recently added static_assert() externs

### ISSUE THREAD

**Issue by mvido** [p4lang/p4c#3531]
StaticAssert pass in frontend evaluates static_assert invocations. After this pass, the nodes representing the invocations of static_assert remain in the IR tree and possibly can cause problems for midends or backends. Does it make sense to eliminate these invocation nodes after they are evaluated in frontend or is there any use case why they could be needed after they are evaluated (and thus the midends/backends should deal with them)?

**Comment by mbudiu-vmw** [comment]
We should in fact constant-fold it, since it should always evaluate to 'true'.
