### ISSUE TITLE
On C++ standard version and possibility of upgrade to C++17 [discussion]

### ISSUE THREAD

**Issue by vlstill** [p4lang/p4c#3536]
This question is prompted by Intel's P4 compiler, which is now in the final steps of switching to use the C++17 standard.* So my question is if there is an interest in the wider P4 community in switching to a new C++ version.

### Advantages

I see the following main nice features of newer C++ standards (in context of our compiler, the list is very incomplete):

C++14
- `auto`-lambda can simplify and shorten code with lambdas, especially if the argument type is long but hiding it does not decrease readability 
- binary literals and digit separators (`1'024`, `0b1111'0000`)
- literal suffixes can make code simpler (e.g. there could be literal suffix for turning string literals into `cstring`)

C++17
- structured bindings (for tuples, etc.): `auto [it, inserted] = set.insert(x)`; or `for (auto [k, v] : someMap)` instead of decomposing the tuples manually or with `std::tie`
- `std::optional`, `std::variant` can replace the boost versions and does not have some downsides (e.g. spurious warnings)
- initializers in if: `if (auto [it, ins] = set.insert(x); ins) { ... }` simplifies code & limits scope
- class template deduction makes code simpler: `return std::pair(a, b)`, not need many `make_*` helpers
- simplified template programming (`if constexpr`, fold expressions)

C++20 could bring another set of nice features, but I don't thing it is sufficiently mature at this point. Basically for reasonable work it needs very new compiler (something like GCC 11).

A non-technical advantage is that newer C++ standards are often more attractive to C++ programmers (especially those coming out of universities freshly or actively following C++ development). As many universities already teach modern standards beyond C++11, students like to be able to use these standards in their work. Oftentimes, C++11 is already "too old" as it requires several (often detious) work-arounds if one is used to newer standards. That at least is my observation from also teaching C++ on university and speaking with my fellow C++ programmers. Therefore this switch could make the compiler more attractive to open-source contributors.

### Disadvantages

- we would remove support for some older compilers/platforms (or require compiler update on the platforms)
- all downstream projects using p4c would be affected and wound need to agree on this

---

If we wanted to use C++17, GCC 9 is a good target compiler as it has support for basically all of C++17 and this support should be stable. Also, p4c already uses GCC 9 for the CI. Also, GCC 9 and newer are here for some time already, so they are available on many platforms. Of course, we should also define which other compilers (such as `clang`) are supported.

---

*We can do the switch without any changes in p4c, so we are not dependent on p4c switching to C++17. In vast majority of cases C++11 code compiles as C++17 without any problems.

**Comment by davidbolvansky** [comment]
Maybe you could send a PR?

> Ubuntu 20.04 is the officially supported platform for p4c. There's also unofficial support for macOS 10.12. Other platforms are untested; you can try to use them, but YMMV.

So possibly not a big deal to switch to C++17?

TODO: use [[fallthrough]] in https://github.com/p4lang/p4c/blob/main/lib/hash.cpp#L62
