### ISSUE TITLE
Does P4-14 support circular shift as a primitive action?

### ISSUE THREAD

**Issue by XiangyuG** [p4lang/p4c#3545]
I have one question about the circular shift operation in P4-14 language. Specifically, circular shift means we want to reorder the bit order. Circular shift by 5 of a 32-bit integer means we put the highest 5 bits to lowest 5 bit and the lowest 27 bit to the highest. 

circular shift (x) = (x << n) | (x >> (32 - n)).

**However, is there any primitive action in Tofino's P4-14 that can support the circular shift directly**? Otherwise, based on the reference to (Page 32 of https://p4.org/p4-spec/p4-14/v1.0.4/tex/p4.pdf), we need to split such action into two stages:

stage 1: do left shift and right shift;
stage 2: do bitwise or;

Any feedback would be quite helpful. Thanks a lot in advance.

Best,

Xiangyu

**Comment by jnfoster** [comment]
Since this is a question about Tofino, you should ask Intel -- e.g., the ICRP program if you are a university, or through a customer support contact if you are in industry.
