### ISSUE TITLE
Range "set" not supported in parser transitions by bmv2 backend

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#357]
For example:
```
parser p(packet_in b, out Headers h,
         inout Meta m, inout standard_metadata_t sm) {
    state start {
        b.extract(h.hs.next);
        m.offset = m.offset + h.hs.last.f2;
        transition select(h.hs.last.f1) {
            0..4 : start;
            _: accept;
        }
    }
}
```
Attached program can be used to reproduce.
[range_set.p4.txt](https://github.com/p4lang/p4c/files/834809/range_set.p4.txt)

**Comment by mbudiu-vmw** [comment]
Does BMv2 support this or do I have to synthesize a list of explicit labels?

**Comment by antoninbas** [comment]
You would need to synthesize the list. I don't think it's worth changing the JSON format to support this. If there is a need to optimize the bmv2 parser implementation using set lookups in the future, then we can consider changing the JSON.

**Comment by mbudiu-vmw** [comment]
Here is a discussion of how this should be done: https://github.com/jafingerhut/p4-guide/tree/master/match-range-using-tcam

**Comment by jafingerhut** [comment]
This enhancement has been added with this PR: https://github.com/p4lang/p4c/pull/2125
