### ISSUE TITLE
The method call of read and write on a Register is currently not supported in p4c.  Please use RegisterAction to describe any register programming

### ISSUE THREAD

**Issue by QingQingR** [p4lang/p4c#3575]
I use v1model(v1model.p4) to build the program. I declare the register, and use read/write function, then the error appears.
"The method call of read and write on a Register is currently not supported in p4c.  Please use RegisterAction to describe any register programming"
Does he method call of read and write on a Register is not supported any longer? or what can I do to support the method?

**Comment by vgurevich** [comment]
@QingQingR -- you are probably asking a question related to Intel Tofino compiler and an old version of it for that matter. 

If you have a question about Intel products, please use the proper support forums:
* [Intel Premier Support](https://premiersuport.intel.com) if you are a commercial customer
* [ICRP Forum](https://community.intel.com/t5/Intel-Connectivity-Research/bd-p/connectivity-research-programforum-board) if you are an academic customer
