### ISSUE TITLE
STF files without a corresponding P4 file in testdata/p4_16_samples directory

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#3594]
@osinstom These two files are there:
testdata/p4_16_samples/default_action_ubpf.p4
testdata/p4_16_samples/default_action-ubpf.stf
It appears the `-` in the STF file name should be `_` instead, to match with the p4 source file?  I believe that without exactly matching prefixes for the names, the test scripts will not recognize that the STF file goes with this P4 source file, and will thus ignore the STF file.

@VolodymyrPeschanenkoIntel It appears that the STF file below has an undesired `_0` near the end of its name, that I suspect will prevent it from being used when testing what appears to be the intended corresponding p4 program:
testdata/p4_16_samples/issue1062-1-bmv2_0.stf
testdata/p4_16_samples/issue1062-1-bmv2.p4

**Comment by fruffy** [comment]
`gauntlet_action_mux` I believe the file may have been renamed, so this STF test can be removed.

`gauntlet_ctrl_plane_hdr` does not compile for BMv2 because it uses a header structure as control plane input. The STF test can be removed.

**Comment by mbudiu-vmw** [comment]
Can this be closed?

**Comment by jafingerhut** [comment]
Please do not close it yet.  There are still two more stf files without corresponding p4 files, as mentioned in the original issue.  I edited the original issue to leave the outstanding ones that have not been fixed at the top, only mentioning the ones with PRs at the bottom.  I will update the original issue again to reflect the latest commit today.
