### ISSUE TITLE
Missing include for core.p4 does not give a decent error message with a switch inside a control

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4c#3613]
Take where I had missed the include for core.p4:
```
control c(in bit<4> a)
{
  apply {
    switch (a) {
      4w0: {}
    }
  }
}
control ct(in bit<4> a);
package pt(ct t);
pt(c()) main;
```
The error message gives:
```
[--Werror=not-found] error: exact: declaration not found
```
Maybe add a note saying did you forgot to include core.p4?
I didn't realize what the error message was saying because exact was not quoted and there was no hint of what was going on.

**Comment by jafingerhut** [comment]
Interesting find.  Yeah, I'd bet $1 that this is due to the way that switch statements on expressions that are not of the form `table_name.apply().action_run` are implemented, which involves synthesizing a P4 table with one exact match field.

**Comment by apinski-cavium** [comment]
> Interesting find. Yeah, I'd bet $1 that this is due to the way that switch statements on expressions that are not of the form `table_name.apply().action_run` are implemented, which involves synthesizing a P4 table with one exact match field.

Yes that is what I expecting really. I have seen other similar error messages dealing with parsers and match_kind but I can't remember the testcase right now.

**Comment by mbudiu-vmw** [comment]
It is true, there are other cases where the compiler silently assumes that core.p4 has been included, but does not give a good error message otherwise. I haven't hunted for these, I will file a new issue.
