### ISSUE TITLE
Many dpdk tests are failing on Ubuntu 18.04 but not 20.04 or 22.04

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#3639]
It appears that the .spec files are expecting hex constants like 0xffffffff in the current repo, but the latest p4c-dpdk is producing capital letters like 0xFFFFFFFF.  That might be the only reason many dpdk tests are failing, but I haven't checked thoroughly yet.

@usha1830 I saw a comment from you recently that you were not sure why this happened.  @fruffy @mbudiu-vmw Could the recent libgmp changes have anything to do with this?  Or anything else you can guess might cause such a change?

**Comment by jafingerhut** [comment]
I guess other questions I'm curious are: are dpdk back end tests running in Github CI?  If not, why not?  If yes, why are they passing when the same tests fail on my freshly installed Ubuntu 18.04 system using my install scripts?  Perhaps I have a later version of some dependency than the p4c CI systems have?

**Comment by jnfoster** [comment]
We did make some changes to CI after merging the GMP PR. It’s possible this
is the culprit. What do you think @fruffy?

-N

**Comment by usha1830** [comment]
I tried reverting the GMP related committing and it seemed to fix this issue.

The prints are using "value" field from IR::Constant Node which is big_int.
I also tried using std::nouppercase but it still prints in capital. Seems like some issue in printing big_int.

Also came across this issue which dates back to 2019 and seems to be fixed in Boost 1.72.0,, https://github.com/boostorg/multiprecision/issues/149

**Comment by fruffy** [comment]
I believe different versions of boost produce different capitalization by default. We have been using [std::uppercase](https://github.com/p4lang/p4c/blob/main/backends/p4tools/common/lib/format_int.cpp#L101) to enforce consistent casing. I believe std::nouppercase has no effect if the output is already upper case. Is it possible to switch to upper case here?

**Comment by jafingerhut** [comment]
It is definitely possible to switch to upper case, but if dpdk tests are being run in Github CI right now, and diff'ing against the lowercase output, and passing, then changing the expected output files to upper-case with no other changes seems likely to cause them to fail, yes?  Do some library versions need to change in Github CI for the upper-case expected output files to pass?

**Comment by fruffy** [comment]
We would also need to change code that produces the output string to use std::uppercase, but then capitalization should be consistent for all supported distributions.

**Comment by jafingerhut** [comment]
Another data point -- the same install script and version of p4c that I used for Ubuntu 18.04 where several dpdk tests fail due to lower-case/upper-case difference, those tests pass on Ubuntu 20.04 and 22.04.  The install script I was using was this one, if it matters: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-v6.sh.  Not much new information there, other than if we change the expected output files to upper case, we definitely need to change something else in order to make them pass consistently on the 3 Ubuntu LTS versions still supported today (18.04, 20.04, 22.04)

**Comment by fruffy** [comment]
There are [a few places](https://github.com/p4lang/p4c/search?q=std%3A%3Ahex) in the source code that use `std::hex`. Adding `std::uppercase` to them should resolve the issue.
