### ISSUE TITLE
Instantiating a direct_counter outside of a table causes a bug in bmv2 backend

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#364]
[p4_16_direct_counter.p4.txt](https://github.com/p4lang/p4c/files/846138/p4_16_direct_counter.p4.txt)
See attached program.

The problem is with the instantiation of `c` in the following snippet:
```
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    direct_counter(CounterType.packets) c;
    action my_action(bit<32> a) { sm.egress_spec = a; }
    table t() {
        actions = { my_action; }
        const default_action = my_action(0);
        counters = c;
    }
    apply { t.apply(); }
}
```

Since direct objects cannot be shared across tables, there is no real need to support this but it would be nice to avoid this bug.
BTW, it seems that even direct meters support this type of instantiation (https://github.com/p4lang/p4c/blob/master/backends/bmv2/jsonconverter.cpp#L1808).

**Comment by mbudiu-vmw** [comment]
Would you suggest just giving an error message for this case directing people to invoke the constructor directly in the table?

**Comment by antoninbas** [comment]
An error message would work. But why not keep it consistent with direct meters?

**Comment by mbudiu-vmw** [comment]
I believe that this issue has been solved.
