### ISSUE TITLE
Incorrect @name annotation for key

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#366]
See test p4_14_samples/simple_nat.p4 - the name generated for keys containing isValid() looks suspicious:

hdr.ipv4.isValid(): exact @name("hdr.ipv4.isValid()")

**Comment by mbudiu-vmw** [comment]
@sethfowler : there are several issues related to naming things in the control-plane, including this one, #582, #595, #486. Maybe we can try to coordinate and find a solution to all of them?

**Comment by sethfowler** [comment]
Yeah, I agree. I have a couple of other tasks I need to complete first, but this is something we need to address soon if possible.

We put some of this stuff off while we discussed language changes that unfortunately didn't end up materializing.

**Comment by mbudiu-vmw** [comment]
I am assuming that this issue can now be closed.
