### ISSUE TITLE
Building p4c

### ISSUE THREAD

**Issue by srihari39** [p4lang/p4c#3696]
I've been trying to update the p4c binary. 
I made some changes in the backends and frontends of the p4c according to my use case. 

In the ```behavioural-model``` folder, I ran ```Makefile``` and ran ```./configure``` in the same folder.
However, the changes are not reflected, and the functionality is not observed in the programs.

Please guide me through this.
Thanks.

**Comment by jafingerhut** [comment]
This is almost certainly not the quickest-in-time way to rebuild the compiler from source code after making changes to it, but it is a reliable way.

Execute these commands, starting from the `p4c` directory of your cloned copy:
```
/bin/rm -fr build
mkdir build
cd build
# Use whatever configure options you want for cmake.  These are what I personally use.
cmake .. -DCMAKE_BUILD_TYPE=DEBUG
# You can also add a `-j<# of parallel jobs>` option, e.g. -j4, to `make` if you have enough RAM, about 1 to 1.5GB per parallel task
make
```

**Comment by srihari39** [comment]
@jafingerhut, unfortunately, it's not yet reflected after doing [https://github.com/p4lang/p4c/issues/3696#issuecomment-1313726683](url).

**Comment by jfingerh** [comment]
Are you making changes to p4c, behavioral-model, or both projects?

**Comment by srihari39** [comment]
@jafingerhut both.

**Comment by jfingerh** [comment]
The instructions I gave earlier would ONLY recompile p4c, not behavioral-model.  They are separate programs with separate build systems.

Here are instructions I have used successfully to build behavioral-model from scratch, which is definitely time-consuming, but should be sure to include any changes you make, I believe.  If you want a way to rebuild "partially", I don't have any suggestions other than to ask antoninbas.

Starting from the directory behavioral-model that is the root directory of your clone of that repo:
```
make clean
./autogen.sh
./configure --with-pi --with-thrift 'CXXFLAGS=-O0 -g'
make
sudo make install-strip
sudo ldconfig
```

**Comment by srihari39** [comment]
@jafingerhut , One more doubt, Are ```p4c``` and ```p4c-bm2-ss``` different. If yes, can you please post the commands required for updating ```p4c-bm2-ss``` binary.

Thanks.

**Comment by jafingerhut** [comment]
The commands I gave above for building p4c should build _all_ back ends for p4c, including `p4c-bm2-ss`.

**Comment by srihari39** [comment]
![image](https://user-images.githubusercontent.com/74501555/202204592-ef36cc3f-4521-4084-a1e9-559fe74fa56f.png)

@jafingerhut , please find the photo attached.
None of the binaries were being updated in the binary directory even after running the commands.

**Comment by srihari39** [comment]
@jafingerhut At the end of each command in their respective directories right? Just for the confirmation.

**Comment by jafingerhut** [comment]
`sudo make install` in p4c will only install the binaries built in `p4c/build`.  It has no idea whether there is a behavioral-model repo on your file system or not.  How could it?  They are two repos with two separate build systems that do not interact with each other.

So yes, `sudo make install` in your `behavioral-model` directory is required if you want to install updated binaries for simple_switch or simple_switch_grpc after building them.

**Comment by jfingerh** [comment]
@srihari39 Everything working for you now?  If so, feel free to close this issue.

**Comment by srihari39** [comment]
@jfingerh , unfortunately not yet.
I'll close this as and when I'm done, thanks.

**Comment by srihari39** [comment]
@jafingerhut , Well, I'll clearly explain my scenario.
I need to implement a custom hash function as for my use case. Instead of going for an extern function, I chose to go as the traditional hash algorithms were implemented. So, I modified ```calculations.cpp``` in ```behavioral-model```. Relevant changes are made to the frontends and backends of the p4c. 
Now when I'm updating the binaries and running the same program, it is still showing up the same error,
```unexpected algorithm.```

I can provide you all the information you want, please help me get out of this.

**Comment by jfingerh** [comment]
I am not necessarily the best person to debug your code changes, but if you are willing to publish a link to your code changes, e.g. publish them on a branch of a fork of these repos, or as a diff/patch to a particular version of the code that you started from, someone might take the time to look.  I personally do not have a lot of experience with the internals of these code bases, although I use them frequently.

This PR to behavioral-model is an example of adding a custom extern to behavioral-model.  Have you examined it?  https://github.com/p4lang/behavioral-model/pull/1140

**Comment by srihari39** [comment]
@jafingerhut, I'll look into that. Thanks

**Comment by srihari39** [comment]
@jafingerhut , I just want to check out one of the old p4c patches. I applied the patch and want to update the binaries. But I'm getting a strange error.

![image](https://user-images.githubusercontent.com/74501555/203489282-0c9c4042-a35a-4e39-a9da-23cb17c17f60.png)

Can you please tell what might be the problem.

**Comment by hesingh** [comment]
Even I had to use `sudo` for past few months after downloading any recent p4c to build on a Ubuntu 18.04 machine.

**Comment by jfingerh** [comment]
I test my install-p4dev-v4.sh and install-p4dev-v6.sh bash scripts on an Ubuntu 18.04 VM every month (and 20.04, and 22.04 for the v6 script).  They worked late last month, and every month before that.  I will test them again late in November to ensure they are still working.  They do not use `sudo` when building p4c, and they produce a p4c executable that passes quite a few tests.

https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

They use `sudo` when installing the executables into system-wide directories like /usr/local/bin, yes, but not for creating the executables.

**Comment by srihari39** [comment]
@jfingerh , I tried with both with sudo and without sudo. It's throwing error "permission denied" when sudo is not used. So we need to use sudo.

**Comment by jafingerhut** [comment]
You may need to use sudo.  I do not :-).  To each their own, if it is working for you with sudo.

**Comment by jafingerhut** [comment]
I can only tell you what works for me.  `cd p4c; rm -fr build; mkdir build; cd build` and then build it from scratch.

If that does not work for you, I'd recommend creating a new fresh clone of p4c, copying any changes over to it if you want changes, and build it from scratch.

**Comment by mbudiu-vmw** [comment]
Once you have built using sudo there are all sorts of files that only sudo users can access. So all subsequent builds also need sudo.
If this issue is active we should reopen it.

**Comment by jafingerhut** [comment]
Yes, I typically NEVER do builds of p4c using `sudo`, so that all files created will NOT be owned by the superuser, and I can modify them with my normal non-superuser non-root account.

Once you create files owned by the superuser, often they can only be removed or modified by the superuser account.  So I would recommend not doing that.
