### ISSUE TITLE
cpplint list of files is not configurable

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#3704]
Currently run-cpplint.sh does not follow symlinks, so it does not check extensions.
This can be solved by adding the -L flag to the find command.
However, a more important problem is that the list of exclusions is global in this file, so people who add a new extension cannot add exclusions. This makes it impossible to run cpplint using this tool.
The previous way of doing it using CMakeList was more modular.

**Comment by fruffy** [comment]
In cpplint exclusions can be added by placing a `CPPLINT.cfg` file with the `exclude_files` property set. Let me think how to make the overall process more user-friendly.
