### ISSUE TITLE
clang-format is not listed as a dependency

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#3705]
So far clang was one of the possible supported compilers, but was not required.
When the clang format check fails there are no indications given to the user how to remedy the problem.

**Comment by mbudiu-vmw** [comment]
clang-format has the same problem as cpplint: it does not run on the extension directories and has no configurable exclusions list.

**Comment by mbudiu-vmw** [comment]
On my ubuntu installation apt-get installs clang-format 6.0. This program gives the following errors when invoked:
```
clang-format: Unknown command line argument '--Werror'.  Try: 'clang-format -help'
clang-format: Did you mean '-cursor'?
clang-format: Unknown command line argument '--dry-run'.  Try: 'clang-format -help'
clang-format: Did you mean '-icp-lto'?
```

**Comment by mbudiu-vmw** [comment]
Ideally clang-format should be run as a pre-commit hook so that files that will be rejected cannot even be pushed. Otherwise we'll generate lots of failed jobs needlessly.

**Comment by fruffy** [comment]
clang-format can be installed using `pip3 install --user --upgrade clang-format`. This should install the right and latest version. 

Regarding the commit hook, unfortunately these have to be installed manually by each person. You can use the `tools/install_git_hooks.sh`. I will update the README instructions.

**Comment by mbudiu-vmw** [comment]
```
$ pip3 install "clang-format>=15.0.4"
Collecting clang-format>=15.0.4
  Downloading https://files.pythonhosted.org/packages/31/3d/83a35768932c398476595509812aae58b352a7052909dab1e2a941fb89f2/clang-format-15.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-y7wag41v/clang-format/setup.py", line 3, in <module>
        from skbuild import setup
    ModuleNotFoundError: No module named 'skbuild'
```

clang-format is written in Python?

**Comment by fruffy** [comment]
The pip wheel version should be a wrapper around a precompiled clang-format binary, which is periodically updated. It is more convenient than having to rely on a specific Ubuntu package. 

I am not quite sure why this installation does not work in your case. I guess `pip3 install --upgrade pip` can help?

**Comment by usha1830** [comment]
> ```
> $ pip3 install "clang-format>=15.0.4"
> Collecting clang-format>=15.0.4
>   Downloading https://files.pythonhosted.org/packages/31/3d/83a35768932c398476595509812aae58b352a7052909dab1e2a941fb89f2/clang-format-15.0.4.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-y7wag41v/clang-format/setup.py", line 3, in <module>
>         from skbuild import setup
>     ModuleNotFoundError: No module named 'skbuild'
> ```
> 
> clang-format is written in Python?

I got this same error on ubuntu 20.04
"apt-get install" installed **clang-format version 6.0.0-1ubuntu2**  which seems to be formatting the code differently and my [PR](https://github.com/p4lang/p4c/pull/3711) checks are failing. Will try rebasing again as some of the related PRs are merged.
