### ISSUE TITLE
Compiler Bug: nested action list?

### ISSUE THREAD

**Issue by smolkaj** [p4lang/p4c#3719]
After upgrading from p4c as of Nov 1
```
4a74084c675a3e8bdf7a318e468cbd5bb27c6914 Do not constant fold mux before it has been typechecked (... by Mihai Budiu <[mbudiu@vmware.com](mailto:mbudiu@vmware.com)>
```
to p4c as of Nov 22
```
- aa0a24caece8a3c30ac69076e08f74ec35d81007 P4Tools: Unify packet sizing options. (#3695) by fruffy <[5960321+fruffy@users.noreply.github.com](mailto:5960321+fruffy@users.noreply.github.com)>
```
I'm seeing the following regression in one of our programs:
```
In file: third_party/p4lang_p4c/frontends/p4/typeChecking/typeChecker.cpp:3902
Compiler Bug: { @proto_id acl_copy();
  @proto_id acl_trap();
  @proto_id acl_forward();
  @proto_id acl_mirror();
  @proto_id acl_drop(standard_metadata);
  @proto_id acl_experimental_trap();
  @defaultonly NoAction(); }: nested action list?
```

**Comment by mbudiu-vmw** [comment]
How can we reproduce this?

**Comment by smolkaj** [comment]
My hypothesis (to be confirmed) is that p4c no longer likes `acl_trap();` etc (note the empty parentheses).

**Comment by mbudiu-vmw** [comment]
Let's add a bit more logging to this place:
`BUG_CHECK(currentActionList == nullptr, "%1%: nested action list while in %2%?", al, currentActionList);`

**Comment by smolkaj** [comment]
With that suggestion, I am now getting a segmentation fault. Will retry with asan/msan.

**Comment by smolkaj** [comment]
> My hypothesis (to be confirmed) is that p4c no longer likes acl_trap(); etc (note the empty parentheses).

I no longer believe that this is the problem.

**Comment by mbudiu-vmw** [comment]
you're getting too fancy, this must be something simple

**Comment by mbudiu-vmw** [comment]
currentActionList should be cleared when finishing the visit of a table and set when entering a new ActionList.
for some reason it isn't cleared.
It's a simple state machine.
You can log the three places where it is read and written.

**Comment by smolkaj** [comment]
Ah, that makes sense.

Let me see if I can share a simple example to reproduce.

**Comment by smolkaj** [comment]
>  With that suggestion, I am now getting a segmentation fault. Will retry with asan/msan.
>  you're getting too fancy, this must be something simple

Just to make explicit the obvious: 
```
BUG_CHECK(currentActionList == nullptr, "%1%: nested action list while in %2%?", al, currentActionList);
```
of course gave a segmentation fault because it dereferences `currentActionList` when it is null.

**Comment by smolkaj** [comment]
I can reproduce the issue by compiling the following open-source file with the BMv2 backend:
- repository: https://github.com/sonic-net/sonic-pins
- path: sai_p4/instantiations/google/middleblock.p4

I needed an `-I.` where `.` is the root of the repository to make things compile.

**Comment by fruffy** [comment]
We have a version of middleblock.p4 here: 
https://github.com/p4lang/p4c/blob/main/testdata/p4_16_samples/pins/pins_middleblock.p4

I wonder why it does not break.

**Comment by smolkaj** [comment]
Oh, nice!

The upstream file could updated recently (20 days ago), so the p4c version might just be too stale?

**Comment by jafingerhut** [comment]
Perhaps there are differences in OS/dependencies/C++ compiler/glibc/toolchain involved here?  No idea what, just throwing out the most obvious possible culprits.

**Comment by mbudiu-vmw** [comment]
my version of the p4test compiler has no problems with middleblock.p4
What's your command-line?

**Comment by mbudiu-vmw** [comment]
@jafingerhut this would be very surprising. We try to make the code deterministic. But this should be a simple problem.

**Comment by smolkaj** [comment]
Could this be an issue with the bazel build only?

I used the following command:
```
blaze run //third_party/p4lang_p4c:p4c_bmv2 -- -I$(pwd) -I$(pwd)/third_party/p4lang_p4c/p4include $(pwd)/sonic-pins/sai_p4/instantiations/google/middleblock.p4
```
where `blaze` is our internal version of `bazel`. (Not very helpful, I know :/)

Will try reproducing with a cmake build.

**Comment by mbudiu-vmw** [comment]
it really should not depend on how you build it

**Comment by mbudiu-vmw** [comment]
what is the final command-line that this runs?

**Comment by mbudiu-vmw** [comment]
cmake does not have a target named p4c_bmv2, but I tried p4c-bm2-ss with no issues

**Comment by smolkaj** [comment]
`p4c_bmv2` is defined here: https://github.com/p4lang/p4c/blob/main/BUILD.bazel#L263-L276
It is essentially `backends/bmv2/simple_switch/main.cpp`.

**Comment by mbudiu-vmw** [comment]
Can I run this with regular bazel?

**Comment by smolkaj** [comment]
Yes!

**Comment by smolkaj** [comment]
(I haven't tried myself yet, will also give that a shot.)

**Comment by mbudiu-vmw** [comment]
Command-line?
I checked out sai in a parallel directory to p4c

**Comment by mbudiu-vmw** [comment]
This command-line works for me with a few warnings but no errors or crashes:
`~/git/sonic-pins/sai_p4/instantiations/google$ ~/git/p4c/build/p4c-bm2-ss -I. ./middleblock.p4`

**Comment by mbudiu-vmw** [comment]
Since you're here maybe you can also suggest how to upgrade the bazel build files to accept c++ 17

**Comment by mbudiu-vmw** [comment]
This command does reproduce the bug

**Comment by mbudiu-vmw** [comment]
This file has no debugging symbols...
Is there another one?

**Comment by smolkaj** [comment]
> Since you're here maybe you can also suggest how to upgrade the bazel build files to accept c++ 17.

By adding a `.bazelrc` to the root of the directory with the following contents:
```
build --cxxopt='-std=c++17'
build --host_cxxopt='-std=c++17'
run --cxxopt='-std=c++17'
run --host_cxxopt='-std=c++17'
```

>  This command does reproduce the bug

+1, I was also able to reproduce with bazel.

> This file has no debugging symbols... Is there another one?

Try with `-c dbg`:
```
bazel run -c dbg :p4c_bmv2 -- -I$(pwd)/p4include $(pwd)/../sonic-pins/sai_p4/instantiations/google/middleblock.p4
```

**Comment by mbudiu-vmw** [comment]
It looks like an uninitialized variable. There is another path through which the value is not initialized to nullptr.
