### ISSUE TITLE
Question regarding an issue in typeChecker code reported by static analysis tool

### ISSUE THREAD

**Issue by mvido** [p4lang/p4c#3724]
Static analysis reports following issue:
`Iterator 'paramIt' is dereferenced at line 946 when it can be equal to value returned by call to [r]end().`
for following code:
https://github.com/p4lang/p4c/blob/37a242cc53b4ef11595e51545e2ebffd2ba95b58/frontends/p4/typeChecking/typeChecker.cpp#L935-L966
introduced in this PR: https://github.com/p4lang/p4c/pull/3686
Is it guaranteed that the size of `functionType->parameters` is equal to the size of `arguments` and this is not a problem?

**Comment by mbudiu-vmw** [comment]
I have filed a PR just in case

**Comment by mvido** [comment]
> I have filed a PR just in case

Thanks
