### ISSUE TITLE
Implementing user-defined conversion functions for IR class objects.

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#3743]
I would like to implement a user-defined conversion method for an IR class object in a `.def` file. 

For example, the method defined here: 
https://github.com/p4lang/p4c/blob/main/backends/p4tools/common/lib/formulae.h#L23

However, the current parser/lexer does not seem to support this. 
Something like this in the `.def` file
```    operator Member const* () { return member; }```
will throw the error:
```
syntax error, unexpected IDENTIFIER "Member"                                                                              
    operator Member        
```
I tried playing around with the `ir-generator.ypp` file to get this to work, but have not find a setting that works. Is there a way to implement this?

**Comment by mbudiu-vmw** [comment]
The IR generator supports a small "subset" of C++ only.
I think the problem is "operator", not "Member".
Playing with that is fraught with danger, the grammar is also written using Bison, so it's very easy to introduce conflicts.
@ChrisDodd wrote almost the entire IR generator code.

**Comment by fruffy** [comment]
Is there any way to just insert straight C++ code for a segment of the class?

**Comment by mbudiu-vmw** [comment]
Use `#emit`. There are examples.

**Comment by mbudiu-vmw** [comment]
This is somewhat documented in the compiler-design.pptx presentation.

**Comment by fruffy** [comment]
Ah, I was looking at the `ir.def` documentation but I somehow missed that. That basically solves my problem. Thanks!
