### ISSUE TITLE
 Modifying a ParserState Node

### ISSUE THREAD

**Issue by Mohxen** [p4lang/p4c#3755]
Hi all,

I want to modify a ParserState node in a new pass in the frontend. I used preorder in IR::ParserState by using Transform. For example, for one node I have
state parse_udp { packet.extract<udp_t>(hdr.udp); accept;}
and I want to change it to
state parse_tcp {packet.extract<tcp_t>(hdr.tcp); accept;}
so I checked ParserState class, we have node->name which is parse_udp in my example and I try to change it to parse_tcp by
node->name = new IR::ParserValueSet::ID (“parse_tcp”); or
node->name = new IR::ID(“parse_tcp”);
But I have some errors. Could you give me some hints?
Also, in ParserState class I could not find any methods or variables related to packet.extract<udp_t>(hdr.udp). please let me know how I can access that.

**Comment by mbudiu-vmw** [comment]
Did you look at compiler-design.pptx in docs?

**Comment by Mohxen** [comment]
Hi Mihai,
Yes, Also, I watched your videos in P4 meeting. My first question is that name in ParserState node is which type of IR::ID because there are a lot of types for IR::ID. 

My second question is that we have name, selectExpression, annotations, components and srcInfo in parserState node. but there is a part of parserState node that is not in them. for example, we could not access to 
packet.extract<udp_t>(hdr.udp); 
in this node
state parse_udp { packet.extract<udp_t>(hdr.udp); accept;}

**Comment by mbudiu-vmw** [comment]
Extract is a MethodCallExpression. Use the --toP4 and -v flags to see the program ir.

**Comment by Mohxen** [comment]
thank you, Mihai. It helped me so much.

**Comment by mbudiu-vmw** [comment]
I will close this issue, since it looks like discussion has moved to #3757
