### ISSUE TITLE
Inserting a new ParserState node

### ISSUE THREAD

**Issue by Mohxen** [p4lang/p4c#3757]
Hi all,

I reviewed the documents and videos about inserting a new node. I can make the below code without error But I don't have JSON or p4i outputs (with --top4 --toJson --dump). Please let me know the reason I do not have output with one or two push_back.

```
const IR::Node* preorder( IR::ParserState* node) override {
auto result = new IR::Vector<IR::ParserState>(); 
result->push_back(node);
result->push_back(node);
return result;}
```

**Comment by mbudiu-vmw** [comment]
If you look at the parent node of a ParserState, which is a P4Parser, you will notice that it contains an IndexedVector of states.
So you have to return an IndexedVector, not just a Vector.

**Comment by Mohxen** [comment]
Thank you Mihai, But I don't have the output yet with one push_back by this code.

`const IR::Node* preorder( IR::ParserState* node) override {
auto result = new IR::IndexedVector<IR::ParserState>(); 
result->push_back(node);
return result;}`

**Comment by mbudiu-vmw** [comment]
the code you have written here inserts in the IR the original node, so the IR is really unchanged.

**Comment by Mohxen** [comment]
Yes, you are right but when I use two push_back to insert a new node, I have an error about duplicate declaration because of inserting an existing node. would it be possible to change the attributes of the new node to not have duplicated node? For example, we have the name attributes for IR::ParserState but for auto result = new IR::IndexedVector<IR::ParserState>(); I cannot access to name attribute with result->name. Please let me know if I can access the name attributes of result.

**Comment by Mohxen** [comment]
Yes, I want to do it. I know how to change the attributes of IR::ParserState But I don't know how to change the attributes of `IR::Indexed<VectorIR::ParserState()>`

**Comment by mbudiu-vmw** [comment]
The vector does not have any attributes

**Comment by Mohxen** [comment]
Thank you, I changed the name but I think it is not enough because there is no declaration for this inserting (There is an if for checking this in indexed_vector.h:65)
`In file: /home/projects/p4c/ir/indexed_vector.h:65
Compiler Bug: udp.p4: state parse_tcp{ 
packet.extract<udp_t>(hdr.udp); 
accept; } does not exist`
This is my code.
`const IR::Node* preorder( IR::ParserState* node) override {
auto result = new IR::IndexedVector<IR::ParserState>(); 
if (node->name = "parse_udp"){
result->push_back(node);
node->name = IR::id("parse_tcp");
result->push_back(node);}
return result;}`

**Comment by Mohxen** [comment]
Thank you, I make a clone node and change it. But when I run a p4 code, I have this error and IR:P4Parser is empty.
`Udp.p4(61): [--Werror=not-found] error: parser MyParser: parser does not have a `start' state
parser MyParser(packet_in packet,
       ^^^^^^^^`
I mentioned my code and also I controled if for running one time`
int runnin_if_for_one_time = 0;
const IR::Node* preorder( IR::ParserState* node ) override {
    auto results =  new IR::IndexedVector<IR::ParserState>();
    if (node->name == "parse_udp" and runnin_if_for_one_time == 0){
        runnin_if_for_one_time = 1;
        results->push_back(node);
        auto tcp_node = node->clone();
        tcp_node->name = IR::ID("parse_tcp");
        tcp_node->components = IR::IndexedVector<IR::StatOrDecl>();
        results->push_back(tcp_node);}
    return results;}`

**Comment by mbudiu-vmw** [comment]
Because you are deleting the contents of all other states by returning an empty indexedvector.
We can answer questions about the compiler architecture, but we cannot really debug your code on this forum.

**Comment by Mohxen** [comment]
Thank you so much, it works. you saved me :)
