### ISSUE TITLE
[p4testgen] Use consistent header import paths

### ISSUE THREAD

**Issue by kheradmandG** [p4lang/p4c#3768]
We use a different build system to build p4testgen (bazel). The inconsistent pattern of imports in `backends/p4tools` is causing problems for us. 

Particularly, we have problems with the following patterns:

1. E.g.  in `backends/p4tools/common/lib/taint.cpp` there is 

```
#include "backends/p4tools/common/lib/symbolic_env.h"
...
#include "p4tools/common/lib/model.h"
```

This pattern is repeated in many files in `backends/p4tools`. Would be great if we could replace all "#include "p4tools/..." with "#include "backends/p4toos/...".

2. in `backends/p4tools/modules/testgen/targets/bmv2/bmv2.cpp` there is `#include "bmv2/common/annotations.h`. Similarly, would be nice to replace it with `#include "backends/bmv2/common/annotations.h`. Fortunately, only this file has this problem.

@fruffy for visibility.

**Comment by fruffy** [comment]
IWYU seems to be adding these because CMake allows for it. I removed backends from the include path.
