### ISSUE TITLE
Preorder a new P4Pogram node

### ISSUE THREAD

**Issue by Mohxen** [p4lang/p4c#3773]
I could compile a p4 code and at the same time in a pass in the frontend I made a new P4Program with some subnodes. When I call preorder or postorder functions, they work just for the current P4Program. Please let me know if I can preorder or postorder the new P4Program node like the current P4Program node.
I used visit and apply_visitor but after running them for the new P4Program, the rest of the program in the new pass cannot continue without any error.

**Comment by fruffy** [comment]
Could you provide a program snippet of the problem you are dealing with? It makes it easier to help.

**Comment by mbudiu-vmw** [comment]
There isn't enough information in this question to enable us to provide a reply. I will close it, but if you can provide more details feel free to reopen it
