### ISSUE TITLE
test-linux-clang-sanitizers check randomly fails

### ISSUE THREAD

**Issue by usha1830** [p4lang/p4c#3781]
test-linux-clang-sanitizers randomly fails with timeout error for this test, passes on retriggering the test.
```
The following tests FAILED:
	2030 - p14_to_16/testdata/p4_14_samples/switch_20160512/switch.p4 (Timeout
	
```
Anyone else observed this issue?

**Comment by jafingerhut** [comment]
I have seen it on my local system.  It says "Timeout".  There is a maximum time limit the test infrastructure allows a test to run before it declares it a timeout for taking too long.  This is the biggest single P4 program and it nondeterministically takes sometimes longer than that Timeout value.  If the Timeout were increased by 60 seconds or so, I bet it would either never fail, or at least fail much less often.

**Comment by fruffy** [comment]
@davidbolvansky

**Comment by davidbolvansky** [comment]
We should set a bigger timeout for this test.

I am on PTO so it may take a bit more time to  fix it - or if you want to fix it urgently, you can prepare a patch - I will review it.

**Comment by davidbolvansky** [comment]
Will be fixed in https://github.com/p4lang/p4c/pull/3786/files

**Comment by usha1830** [comment]
Thanks for fixing this!
