### ISSUE TITLE
semantics of packets_and_bytes meter type in v1model.p4?

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#379]
When instantiating a `meter`, a `CounterType` argument has to be provided (https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4#L64). `CounterType` is an enum that includes `packets_and_bytes`. While the meaning of `packets_and_bytes` is pretty obvious to me for counters, what does it mean for meters?

Note that `packets_and_bytes` meters are accepted by the frontend and the bmv2 backend, but the produced JSON is invalid and is rejected by simple_switch:
```
simple_switch: P4Objects.cpp:954: void bm::P4Objects::init_meter_arrays(const Json::Value&, bm::P4Objects::InitState*): Assertion `0 && "invalid meter type"' failed.
```

I suggest doing one of the following:
- if `packets_and_bytes` is useful for meters then define the semantics somewhere and reject it (at least for now) in the bmv2 backend.
- otherwise, define a `MeterType` enum which does not include `packets_and_bytes` in v1model.p4

**Comment by mbudiu-vmw** [comment]
The right solution is to define a new enum type.

**Comment by mbudiu-vmw** [comment]
This has been solved by introducing a new enum MeterType in v1model.p4.
An important question to consider is whether freezing the P4-16 spec also entails freezing v1model.p4. 
In principle the two should be decoupled, but it would be nice to provide a stable model that people can rely on.

**Comment by sethfowler** [comment]
It looks to me like the P4Runtime code needs to be updated to account for this. I'll take care of that today if I get a chance.
