### ISSUE TITLE
The functionality of v1parser

### ISSUE THREAD

**Issue by Mohxen** [p4lang/p4c#3798]
Hi all,

Please let me know the functionality of v1parser.ypp (I cannot find any documents about it). Also, I like to know about the functionality differences between v1parser and p4parser. 

Especially, I like to know the functionality of control_function_declaration.
https://github.com/p4lang/p4c/blob/bc37a35b5be915d831ce6ca2b5da1ba9a6dcc961/frontends/parsers/v1/v1parser.ypp#L818-L858

**Comment by mbudiu-vmw** [comment]
v1parser parses the P4_14 version of the programming language
