### ISSUE TITLE
Generating digest does not work (P4_16, p4c, bmv2) 

### ISSUE THREAD

**Issue by kucejan** [p4lang/p4c#380]
Hi,

I am trying to generate digest using P4_16, p4c, bmv2 and this simple code:

    #include <core.p4>
    #include <v1model.p4>

    header ethernet_t {
        bit<48> dstAddr;
        bit<48> srcAddr;
        bit<16> etherType;
    }

    struct headers {
        ethernet_t ethernet;
    }

    struct intrinsic_metadata_t {
        bit<48> ingress_global_timestamp;
        bit<8> lf_field_list;
        bit<16> mcast_grp;
        bit<16> egress_rid;
        bit<8> resubmit_flag;
        bit<8> recirculate_flag;
    }

    struct metadata {
        intrinsic_metadata_t intrinsic_metadata;
    }

    struct digest_t {
        bit<48> item;
    }

    control debug(inout headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {

        action send() {
            digest<digest_t>(123, { meta.intrinsic_metadata.ingress_global_timestamp });
            //meta.intrinsic_metadata.lf_field_list = 1;
        }

        table tab() {
            actions = { send; }
            default_action = send();
        }

        apply {
            tab.apply();
        }
    }

    parser ParserImpl(packet_in packet, out headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
        state start {
            packet.extract<ethernet_t>(hdr.ethernet);
            transition accept;
        }
    }

    control verifyChecksum(in headers hdr, inout metadata meta) {
        apply {
        }
    }

    control ingress(inout headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
        debug() debug_0;

        apply {
            debug_0.apply(hdr, meta, standard_metadata);
        }
    }

    control egress(inout headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
        apply {
        }
    }

    control computeChecksum(inout headers hdr, inout metadata meta) {
        apply {   
        }
    }

    control DeparserImpl(packet_out packet, in headers hdr) {
        apply {
            packet.emit<ethernet_t>(hdr.ethernet);
        }
    }

    V1Switch<headers, metadata>(ParserImpl(), verifyChecksum(), ingress(), egress(), computeChecksum(), DeparserImpl()) main;

The program should for each incoming packet generate a digest with its ingress timestamp, but it does not work. In my opinion the problem is caused by the fact, that bmv2 is using *lf_field_list* field to store the learn id and the way, how the compiler processes input arguments of a control block. According the analysis of the generated JSON the compiler generates auxiliary variable (local copy) for each input (inout) parameter. This variable is set up at the beginning of the control block based on the passed arguments and the value is than copied back at the end of the block. During digest() call the global *lf_field_list* is set properly, however this value is again replaced with the local unmodified copy at the end of the control block.

If I uncomment the line `meta.intrinsic_metadata.lf_field_list = 1` or if I change *meta* parameter from *inout* to *in* only, it starts to work because I set the local variable properly or in the second case the compiler does not generate code to copy local value back.

I am not sure if this is a bug, but it is really confusing behaviour, which should be resolved.

Thanks,

Jan

**Comment by mbudiu-vmw** [comment]
I am not sure I understand what the problem is.
The problem may have disappeared after the latest PR merged.
However, if that is true, it is an accident. My guess is that the control-plane API generator actually uses the names of the *arguments* of the digest call, and if the compiler renames variables the control-plane no longer works properly. If this is the case, this is a big problem, because digest is not just a function call, it carries additional information. @sethfowler: this is something we should take a look at. There is no clear spec for how digest is supposed to work.

**Comment by kucejan** [comment]
Hi, the problem has really disappeared after the latest PR merge. Thanks.
