### ISSUE TITLE
Compiler should not expand stack assignments in parsers

### ISSUE THREAD

**Issue by mihaibudiu** [p4lang/p4c#3836]
Copying elements does not copy the .next index.

**Comment by fruffy** [comment]
This is fixed now after disabling the expansion?

**Comment by mbudiu-vmw** [comment]
It will be once we merge the corresponding PR.

**Comment by kfcripps** [comment]
Looks like this has been fixed by #3803.
https://github.com/p4lang/p4c/pull/3803#issuecomment-1487499977.
