### ISSUE TITLE
Drop 0x1 value

### ISSUE THREAD

**Issue by guy-davidi** [p4lang/p4c#3861]
Hi,
I wrote a P4 program that do simple exact match by Ipv4 table.
I see that the default value of the drop action in by the compiler is 0x1.
I see that this value isn't changed and cause to drop in out port.
```
rx m.psa_ingress_input_metadata_ingress_port
	mov m.psa_ingress_output_metadata_drop 0x1
	extract h.ethernet
	jmpeq INGRESS_PARSER_PARSE_VLAN_TAG h.ethernet.ether_type 0x8100
	jmpeq INGRESS_PARSER_PARSE_IPV4 h.ethernet.ether_type 0x800
	jmp INGRESS_PARSER_ACCEPT
	INGRESS_PARSER_PARSE_VLAN_TAG :	extract h.vlan_tag
	jmpeq INGRESS_PARSER_PARSE_IPV4 h.vlan_tag.ether_type 0x800
	jmp INGRESS_PARSER_ACCEPT
	INGRESS_PARSER_PARSE_IPV4 :	extract h.ipv4
	INGRESS_PARSER_ACCEPT :	table ipv4_host
	jmpneq LABEL_DROP m.psa_ingress_output_metadata_drop 0x0
	emit h.ethernet
	emit h.vlan_tag
	emit h.ipv4
	tx m.psa_ingress_output_metadata_egress_port
	LABEL_DROP :	drop
```
the bug is:
here we init the drop value
```
mov m.psa_ingress_output_metadata_drop 0x1
```

here we allways jump to "drop action"
```
jmpneq LABEL_DROP m.psa_ingress_output_metadata_drop 0x0
	emit h.ethernet
	emit h.vlan_tag
	emit h.ipv4
	tx m.psa_ingress_output_metadata_egress_port
	LABEL_DROP :	drop
```

**Comment by fruffy** [comment]
For which target architecture or compiler back end is this? DPDK?

**Comment by guy-davidi** [comment]
hi,
yes, DPDK.

**Comment by fruffy** [comment]
I believe @usha1830 is best qualified to help with this.

**Comment by jafingerhut** [comment]
If you use the PSA architecture, i.e. your P4 program has `#include <psa.p4>` near the beginning, the PSA architecture defines the behavior this way.  If you want to NOT have a packet be dropped at the end of ingress, you must execute some action that causes the `drop` metadata field to change to `false`.

One way to do that is to call the action `send_to_port` defined in that include file, as shown here: https://github.com/p4lang/p4c/blob/main/p4include/dpdk/psa.p4#L419-L420

Another is to do an assignment statement to the `drop` field in your own code, assigning it the value `false`.  Note: If you do that, but you do NOT also assign a unicast output port, or a multicast group, then the destination of the packet will be undefined/uninitialized, and implementation-specific whether it goes somewhere predictable or not.

**Comment by guy-davidi** [comment]
great thanks!
