### ISSUE TITLE
Comparing two nodes

### ISSUE THREAD

**Issue by Mohxen** [p4lang/p4c#3865]
Hi all,

I know that compiler has an equiv function for comparing two nodes but please let me know if there is another way for comparing in the compiler, especially if it does not consider the name of two nodes for comparison.

Thanks

**Comment by mbudiu-vmw** [comment]
In general you can define multiple equivalence relations on a set.
You have to define what it means to be equivalent, and then we can tell you whether something similar exists.
For example, for types there's a typeMap method which checks equivalence.
In a compiler it is very subtle what equivalence means.
For example, take two IR nodes of type PathExpression, both with a path of "x".
Are they equivalent? It really depends on the context (the part of the IR tree where they belong).
You can have to variables named "x" in a program, so whether the two expressions refer to the same variable depends on where they appear in the IR tree.
Even for seemingly trivial nodes like "2" the answer is not clear cut.
Consider the two expressions 8w2 + 2 and 8w16 + 2. We have two Constant nodes with value 2, but one will be transformed later in an 8-bit 2, and the other into a 16-bit 2. So they should not be considered equivalent with this interpretation in mind.

**Comment by apinski-cavium** [comment]
A technique inside the compiler to figure out if two things are equivalance is to do value numbering, see https://en.wikipedia.org/wiki/Value_numbering for more information.

**Comment by mbudiu-vmw** [comment]
We don't have a value numbering pass.

**Comment by Mohxen** [comment]
Thank you very much @mbudiu-vmw  @apinski-cavium 

I want to compare two header nodes and two parser nodes, without the name of the nodes and the positions in IR. I think the best option is changing equiv function to do it. I would appreciate it if I can have your feedback.

Thanks

**Comment by mbudiu-vmw** [comment]
You can create a new function, but you cannot change the existing one.
You still didn't tell us how you want to compare -- what is the definition of equality, so I cannot give you any more suggestions.

**Comment by Mohxen** [comment]
Thank you very much @mbudiu-vmw 
If I want to compare the nodes of two P4 codes (for example comparing the headers of two P4 codes and then understand that there are not some header nodes of the second p4 code in the first p4 code), please let me know if there is a function in the compiler that can help me with the assumption of accessing two graphs of two p4 codes.

**Comment by mbudiu-vmw** [comment]
you will have to write your own
