### ISSUE TITLE
What is limit N on how many of the first N characters of P4 program identifiers must be unique to be treated as different identifiers?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#3866]
I have a vague memory that someone asked this in an issue or comment somewhere in the last several months, but cannot find it.

I believe it was said in that discussion that if identifiers are identical in the first 64 characters, they are treated as the same identifier, even if they differ after the first 64 characters.

It was also mentioned that increasing this value to some larger value, e.g. 256 characters, might be a small change to p4c.  Of course there might be similar but different limits in BMv2 or other back ends, or the P4Runtime API implementation, but I wanted to start with the limit that p4c uses.

**Comment by mbudiu-vmw** [comment]
I don't recall coding any such limit in the compiler, and I frankly see no reason why we should.

**Comment by apinski-cavium** [comment]
The P4 language spec also does not have any such limit; though it might make sense to make a mention of minimal limit of needing to supported.
As far as I can tell the P4 runtime spec does not mention any limit either.

**Comment by jafingerhut** [comment]
Thanks for the quick response.  I did a quick test with action names and metadata field names that were the same in the first 128 characters, and differed only after that, and they were treated as different identifiers, so if there is some implementation limit, it is longer than that.  As Mihai mentioned above, he does not know of such a small finite limit (other than available memory, I assume :-)

**Comment by mbudiu-vmw** [comment]
I think we can close this issue.
