### ISSUE TITLE
How to use the hash function in bmv2? Are there some docs?

### ISSUE THREAD

**Issue by YichuanSun** [p4lang/p4c#3876]
I find a hash function use case.
`hash(meta.output_hash_one, HashAlgorithm.crc16, (bit<16>)0, {hdr.ipv4.srcAddr,
                                                          hdr.ipv4.dstAddr,
                                                          hdr.tcp.srcPort,
                                                          hdr.tcp.dstPort,
                                                          hdr.ipv4.protocol},
                                                          (bit<32>)BLOOM_FILTER_ENTRIES);`
So what is the meaning of the third parameter `(bit<16>)0` ? I don't find any docs abount the five parameters.

**Comment by jafingerhut** [comment]
Documentation about many things in the v1model architecture can be found in these two places:
+ The v1model.p4 header file has many comments, including a paragraph describing the behavior of the hash function: https://github.com/p4lang/p4c/blob/main/p4include/v1model.p4
+ This document on the simple_switch target in the behavioral-model repo: https://github.com/p4lang/behavioral-model/blob/main/docs/simple_switch.md

The first link is more useful for your particular question about the behavior of the hash function, but I would recommend saving links to both of these things in case you have additional questions about other features of the v1model architecture in the future.

**Comment by mbudiu-vmw** [comment]
I will close this issue, since it's not really about the compiler.
