### ISSUE TITLE
Inserting a new Type_Header node

### ISSUE THREAD

**Issue by Mohxen** [p4lang/p4c#3881]
Hi all,

I want to insert a new Type_Header node and I received this error. Actually, I could insert other types of nodes without errors but I do not know why I have this error for Type_Header. Also, you mentioned an explanation for this error in the compiler code but I don't understand why I need to do it just for Type_Header. 

**Error:** 
`/p4c/ir/vector.h:157:10: error: ‘bool IR::Vector<T>::operator==(const IR::Vector<T>&) const [with T = IR::Type_Header]’ marked ‘override’, but does not override
  157 |     bool operator==(const Vector &a) const override { return vec == a.vec; }
      |          ^~~~
In file included from /p4c/ir/ir.h:40,
                 from /p4c/frontends/p4/dontcareArgs.h:20,
                 from /p4c/frontends/p4/dontcareArgs.cpp:17,
                 from /p4c/build/frontends/unified_frontend_sources_3.cpp:2:
/p4c/ir/indexed_vector.h: In instantiation of ‘class IR::IndexedVector<IR::Type_Header>’:
/p4c/frontends/p4/newpass.h:144:76:   required from here
/p4c/ir/indexed_vector.h:155:10: error: ‘bool IR::IndexedVector<T>::operator==(const IR::Vector<T>&) const [with T = IR::Type_Header]’ marked ‘override’, but does not override
  155 |     bool operator==(const Vector<T> &a) const override { return a == *this; }
      |          ^~~~
/p4c/ir/indexed_vector.h:156:10: error: ‘bool IR::IndexedVector<T>::operator==(const IR::IndexedVector<T>&) const [with T = IR::Type_Header]’ marked ‘override’, but does not override
  156 |     bool operator==(const IndexedVector &a) const override {
      |          ^~~~
make[2]: * [frontends/CMakeFiles/frontend.dir/build.make:188: frontends/CMakeFiles/frontend.dir/unified_frontend_sources_3.cpp.o] Error 1
make[1]: * [CMakeFiles/Makefile2:1597: frontends/CMakeFiles/frontend.dir/all] Error 2`

**your explanation:**
`    /* DANGER -- if you get an error on the above line
     *       operator== ... marked ‘override’, but does not override
     * that mean you're trying to create an instantiation of IR::Vector that
     * does not appear anywhere in any .def file, which won't work.
     * To make double-dispatch comparisons work, the IR generator must know
     * about ALL instantiations of IR class templates, which it does by scanning
     * all the .def files for instantiations.  This could in theory be fixed by
     * having the IR generator scan all C++ header and source files for
     * instantiations, but that is currently not done.
     *
     * To avoid this problem, you need to have your code ONLY use instantiations
     * of IR::Vector that appear somewhere in a .def file -- you can usually make
     * it work by using an instantiation with an (abstract) base class rather
     * than a concrete class, as most of those appear in .def files. */`

**Comment by mbudiu-vmw** [comment]
If you show us the code we may be able to give you some guidance.

**Comment by Mohxen** [comment]
```
const IR::Node* preorder( IR::Type_Header* node ) override{
                if (node->name == "tcp_t" && running_if_for_one_time_tcp_header == 0){
                    running_if_for_one_time_tcp_header = 1;
                    std::cout << "{ \n" << node << "}\n" << std::endl;
                    tcp_header = node->clone();
                    return node;
                    }
                else if (node->name == "ipv4_t" && running_if_for_one_time_udp_header == 0) {
                    running_if_for_one_time_udp_header = 1;
                    std::cout << "{ \n" << node << "}\n" << std::endl;
                    //return node;
                    auto results =  new IR::IndexedVector<IR::Type_Header>();
                    results->push_back(node);
                    results->push_back(tcp_header);
                    return results;
                }
                else{
                    return node;}
            }
```

**Comment by mbudiu-vmw** [comment]
The problem is here `new IR::IndexedVector<IR::Type_Header>`. 
Probably you want an IndexedVector<IR::StatOrDecl>. 
Since all types are toplevel, perhaps you don't want an IndexedVector at all, but a Vector<IR::Node>.
