### ISSUE TITLE
How to store the intermediate representations in an output file? 

### ISSUE THREAD

**Issue by drobinkent** [p4lang/p4c#3883]
According to the compiler architecture document, the P4C compiler frontend and the midend work on the same intermediate representation.  How to store the intermediate representation in an output file? 

Is the BMV2 JSON same as the intermediate representation of a P4 program?

**Comment by mbudiu-vmw** [comment]
You can use the `--toJson file` command-line flag to obtain a representation of the IR after the compiler mid-end.
See also my previous answer: https://github.com/p4lang/p4c/issues/1273#issuecomment-1424871922
These two are completely different data structures.

**Comment by fruffy** [comment]
You could also use the ToP4 visitor and produce a .p4 file. It is not the exact same as the IR but it will give you a good representation. It might be enough for your purposes. The nice part is that you can easily reparse that P4 file into IR again.
