### ISSUE TITLE
Could NOT find LibGc (missing: LIBGCCPP_LIBRARY LIBGC_LIBRARY   LIBGC_INCLUDE_DIR) (Required is at least version "7.4.2")

### ISSUE THREAD

**Issue by isaacncz** [p4lang/p4c#3891]
am trying to run bootstrap.sh and faced this. Any ideas what went wrong?

**Comment by fruffy** [comment]
The bootstrap script is very out of date, we should remove it or update it.

You are likely missing several dependencies, you can find the complete install instructions here:
https://github.com/p4lang/p4c#installing-p4c-from-source

The full list of dependencies can be found in this script:
https://github.com/p4lang/p4c/blob/main/tools/ci-build.sh#L50 

If you just need a p4c binary you can also add the binary repo:
https://github.com/p4lang/p4c#ubuntu

@rst0git It looks like this was last updated in September. Is there a way to automatically push updates?

**Comment by rst0git** [comment]
@fruffy Thank you for the heads-up! I will update the packages in the next few hours. I usually test all packages locally before pushing an update.

**Comment by davidbolvansky** [comment]
@rst0git  rst0gitThere are new breakages 

Failed to fetch https://provo-mirror.opensuse.org/repositories/home%3A/p4lang/xUbuntu_22.04/amd64/p4lang-bmv2_1.15.0-2_amd64.deb  File has unexpected size (9033134 != 9033182). Mirror sync in progress? [IP: 91.193.113.70 443]

**Comment by rst0git** [comment]
@davidbolvansky Thank you for pointing this out. I have opened a pull request to fix a problem in BMv2 (https://github.com/p4lang/behavioral-model/pull/1182) and I'm currently building the packages with this fix.

**Comment by fruffy** [comment]
> @fruffy Thank you for the heads-up! I will update the packages in the next few hours. I usually test all packages locally before pushing an update.

Thanks!

**Comment by isaacncz** [comment]
> The bootstrap script is very out of date, we should remove it or update it.
> 
> You are likely missing several dependencies, you can find the complete install instructions here: https://github.com/p4lang/p4c#installing-p4c-from-source
> 
> The full list of dependencies can be found in this script: https://github.com/p4lang/p4c/blob/main/tools/ci-build.sh#L50
> 
> If you just need a p4c binary you can also add the binary repo: https://github.com/p4lang/p4c#ubuntu
> 
> @rst0git It looks like this was last updated in September. Is there a way to automatically push updates?

I managed to run it. Yup, left out the dependencies.
