### ISSUE TITLE
Access to the Includes of architectures

### ISSUE THREAD

**Issue by Mohxen** [p4lang/p4c#3900]
Hi all,

Compiler keeps the includes of architectures until the end of frontend such as include <v1model.p4>. Please let me know whether we access to them inside of compiler by using IR classes.

Thank you.

**Comment by mbudiu-vmw** [comment]
It actually does not, it simply includes the files entirely.
Each IR node has a srcInfo field with information about the source file it comes from.

**Comment by mbudiu-vmw** [comment]
The file inclusion is performed by cpp before the p4 compiler even sees the input.

**Comment by Mohxen** [comment]
Thank you, I checked the output of FrontEndLast for two types of include (a regular p4 code and v1model.p4). compiler merges the regular p4 codes but keeps include <v1model.p4>, let me know if it isn't correct.

**Comment by mbudiu-vmw** [comment]
That is not correct. You can read the code in toP4.cpp which emits the output. 
It uses a heuristic to emit an `#include` directive if the IR nodes are from a specific set of known files.
In fact, this heuristic is wrong in general, and can produce uncompilable code: https://github.com/p4lang/p4c/issues/646
