### ISSUE TITLE
The connection between Keyset of SelectCase and protocol number

### ISSUE THREAD

**Issue by Mohxen** [p4lang/p4c#3915]
Hi all,

For example, we can have
```
 const bit<16> TYPE_IPV4 = 0x800;
```
in the variable and 
```
TYPE_IPV4: parse_ipv4;
```
in the Keyset of SelectCase of ParserState. Please let me know how can we access 0x800 from TYPE_IPV4 Keyset which is IR::Expression.

Thank you

**Comment by mbudiu-vmw** [comment]
The constant folding pass will replace TYPE_IPV4 with its value everywhere.
But only if it is a const.
