### ISSUE TITLE
The input of parser

### ISSUE THREAD

**Issue by Mohxen** [p4lang/p4c#3921]
Hi all,

We have header, metadata, and others as the input of the parser. They are in P4Parse->type->applyParams->parameters. Would it be possible to change them in one place and compiler could change them in all part of P4Parser?
For example, if we change ```parser MyParser(out headers hdr_one)``` to ```parser MyParser(out headers hdr_two)```  inside the compiler, and compiler could change hdr_one to hdr_two in all part of IR . For example, it can change 
```packet.extract(hdr_one.ethernet)```
 to 
```packet.extract(hdr_two.ethernet)```

Thank you very much

**Comment by mbudiu-vmw** [comment]
There are many passes doing such thing, look for renaming and flattening passes
