### ISSUE TITLE
Can we set different flow sampling rate for each flow respectively?

### ISSUE THREAD

**Issue by YichuanSun** [p4lang/p4c#3922]
As title

**Comment by mbudiu-vmw** [comment]
This is not the right place for this question, try the forum at p4.org https://forum.p4.org

**Comment by YichuanSun** [comment]
Sorry, but the forum have some trouble when I login.

When I input the username and passwd, then click the login button, the info below is shown, and login fails.

Internal Server Error
Login error: unmarshal auth pass response: 503 invalid character '<' looking for beginning of value "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n<hr>\n<address>Apache/2.4.29 (Ubuntu) Server at crowd.opennetworking.org Port 443</address>\n</body></html>\n"

**Comment by mbudiu-vmw** [comment]
I am afraid we still can't help, a different set of people are administering the forum than writing the compiler.
Perhaps there's some email contact on p4.org where you can complain about it?

**Comment by YichuanSun** [comment]
> I am afraid we still can't help, a different set of people are administering the forum than writing the compiler. Perhaps there's some email contact on p4.org where you can complain about it?

OK, thanks for your help:）

**Comment by fruffy** [comment]
I was able to login. Maybe your username has unusual characters or the issue was temporary?
