### ISSUE TITLE
p4c-dpdk gives CompilerBug while attempting to generate context.json for DASH PNA program

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#3928]
Steps to create the attached P4 program file called dash-pna.p4:

```bash
git clone https://github.com/sonic-net/DASH
cd DASH
git checkout 40b77975a68061f029ecdbdb7a65a8fa9e702593
cd dash-pipeline/bmv2
p4c-dpdk -DTARGET_DPDK_PNA -DPNA_CONNTRACK --pp dash-pna.p4 dash_pipeline.p4
```

Command that causes p4c-dpdk to Compiler Bug:

```
$ p4c-dpdk --arch pna --context context.json dash-pna.p4

[ ... several warning messages omitted, which I am not worried about ... ]

terminate called after throwing an instance of 'Util::CompilerBug'
  what():  In file: /home/andy/p4c/backends/dpdk/dpdkContext.cpp:221
Compiler Bug: unable to find id for dash_ingress.outbound_ConntrackOut_conntrackOut

Aborted (core dumped)
```

I was concerned that perhaps the existence of characters like ':' and
'|' in the strings of `@name` annotations might be related to this
issue, so I also created an edited version of the file named
dash-pna-edited.p4.  The same command gives a similar error for that
P4 program, too.

```
$ p4c-dpdk --arch pna --context context.json dash-pna-edited.p4

[ ... several warning messages omitted, which I am not worried about ... ]

terminate called after throwing an instance of 'Util::CompilerBug'
  what():  In file: /home/andy/p4c/backends/dpdk/dpdkContext.cpp:221
Compiler Bug: unable to find id for dash_ingress.outbound_ConntrackOut_conntrackOut

Aborted (core dumped)
```

[programs.zip](https://github.com/p4lang/p4c/files/10996520/programs.zip)

**Comment by jafingerhut** [comment]
@usha1830 This looks like a completely different issue than the other one I created recently.  Feel free to notify someone else who deals with the part of p4c-dpdk that handles the `--context` option, if it wasn't you.

**Comment by jafingerhut** [comment]
@chrispsommers FYI, Chris, I will double check, but it might be that generating the `context.json` file (the name typically given to the file created by `p4c-dpdk --context <output_fname.json>`) is required in order to create a binary file that can be loaded into the DPDK data plane.

If so, then this issue may be a blocker for running the DASH P4 code in DPDK.

**Comment by mbudiu-vmw** [comment]
By running with the -v flag you can see the passes as they are executed. This fails in the very last pass of the DPDK backend.
