### ISSUE TITLE
Object without constructors can be allocated.

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#394]
```
extern C {}

C c; // accepted
C() c; // rejected
```

**Comment by jafingerhut** [comment]
After this commit, this program gives no errors:

```
extern C { C(); bool get(); }

control X(out bool b) {
    C() c;
    apply { b = c.get(); }
}

control Z(out bool a);
package top(Z z);
top(X()) main;
```

If I delete the C(); constructor inside the 'extern C' definition, I get this error:

```
issue394-variant2.p4(4): error: c: type C has no constructor with 0 arguments
    C() c;
        ^
issue394-variant2.p4(1)
extern C { bool get(); }
       ^
```

Does that all look like it is working as desired?

**Comment by mbudiu-vmw** [comment]
This is the intended behavior.
Do you find this surprising?

**Comment by jafingerhut** [comment]
I don't have enough experience with P4_16 to find it surprising or unsurprising.  Just wanted to check whether an issue was warranted.  If compiler is correct here, then P4_16 spec should have Checksum16() constructor in very_simple_model.p4 arch model, yes?  If correct, I can file issue for spec.

**Comment by mbudiu-vmw** [comment]
Even better, perhaps you can file a PR to fix the issue in the spec?
Thank you.

**Comment by jafingerhut** [comment]
PR created on the spec.
