### ISSUE TITLE
Do not allow people to commit files that would not pass clang-format

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#3945]
We keep wasting a lot of time and CI cycles with this.

**Comment by fruffy** [comment]
We already have a script for that:
https://github.com/p4lang/p4c/blob/main/tools/install_git_hooks.sh

This script installs a git commit hook, which applies some checks before you commit. Not much more can be done on the client side.

**Comment by mbudiu-vmw** [comment]
Can you please make the script executable?

**Comment by fruffy** [comment]
#3947 should do this.
