### ISSUE TITLE
Problematic inline code ordering causes use before declaration error

### ISSUE THREAD

**Issue by qobilidop** [p4lang/p4c#3955]
Update: Turns out this has nothing to do with type checking, but an issue with inline code ordering.

## Test code to reproduce the issue

When passing an extern to an inner control block, and using it in a table action, the frontend type checking would fail.

I think this should work, because according to the language spec:
- > For anything other than an action, e.g. a **control**, parser, or function, a **directionless parameter** means that the value supplied as an argument in a call must be a compile-time known value (see Section 18.1).
- 18.1
  - > The following are compile-time known values:
    - > Instances constructed by instance declarations (Section 11.3) and constructor invocations.
- 11.3
  - > Instantiations are similar to variable declarations, but are reserved for the types with constructors (**extern objects**, control blocks, parsers, and packages)

Here's an example that fails to compile (`test.p4`):
```p4
#include <core.p4>

extern MyCounter<I> {
    MyCounter(bit<32> size);
    void count(in I index);
}

typedef bit<10> my_counter_index_t;
typedef MyCounter<my_counter_index_t> my_counter_t;

control Inner(my_counter_t counter_set) {
    action count(my_counter_index_t index) {
        counter_set.count(index);
    }

    table counter_table {
        actions = {
            count;
        }
    }

    apply {
        counter_table.apply();
    }
}

control Test() {
    my_counter_t(1024) counter_set;

    apply {
        Inner.apply(counter_set);
    }
}

control C();
package P(C _c);
P(Test()) main;
```

The error message is:
```
In file: /path/to/p4c/frontends/p4/typeChecking/typeChecker.cpp:186
Compiler Bug: test.p4(28): Could not find type of <Declaration_Instance>(35172) counter_set/39 @name("counter_set") my_counter_t counter_set(1024)
    my_counter_t(1024) counter_set;
                       ^^^^^^^^^^^
```

To explore the conditions when this error would occur, I have done some experiments.

## Experiment 1

When the extern instance declaration is in the same control block as its usage, there is no issue. For example, this compiles:
```p4
#include <core.p4>

extern MyCounter<I> {
    MyCounter(bit<32> size);
    void count(in I index);
}

typedef bit<10> my_counter_index_t;
typedef MyCounter<my_counter_index_t> my_counter_t;

control Test() {
    my_counter_t(1024) counter_set;

    action count(my_counter_index_t index) {
        counter_set.count(index);
    }

    table counter_table {
        actions = {
            count;
        }
    }

    apply {
        counter_table.apply();
    }
}

control C();
package P(C _c);
P(Test()) main;
```

## Experiment 2

When the extern usage is not in a table action, there is no issue. For example, this compiles:
```p4
#include <core.p4>

extern MyCounter<I> {
    MyCounter(bit<32> size);
    void count(in I index);
}

typedef bit<10> my_counter_index_t;
typedef MyCounter<my_counter_index_t> my_counter_t;

control Inner(my_counter_t counter_set) {
    apply {
        counter_set.count(42);
    }
}

control Test() {
    my_counter_t(1024) counter_set;

    apply {
        Inner.apply(counter_set);
    }
}

control C();
package P(C _c);
P(Test()) main;
```

I'll keep debugging and try to come up with a fix. But maybe someone can spot the real issue faster than me.

**Comment by mbudiu-vmw** [comment]
Probably a bug in the inlining code.
You can find out where the bug happens by running with the -v flag. It will display the passes that have completed. 
You can see the output of the compiler after any pass using `--top4 SubstringOfPassName`.

**Comment by mbudiu-vmw** [comment]
Indeed, this happens in the `Inline` pass. The output after inlining is this:
```
control Test() {
    @name("Inner.count") action Inner_count(@name("index") my_counter_index_t index_0) {
        counter_set_0.count(index_0);
    }
    @name("Inner.counter_table") table Inner_counter_table {
        actions = {
            Inner_count();
            @defaultonly NoAction();
        }
        default_action = NoAction();
    }
    @name("counter_set") my_counter_t(32w1024) counter_set_0;
    apply {
        {
            Inner_counter_table.apply();
        }
    }
}
```

Notice that the declaration of counter_set_0 comes after it's first use.

**Comment by qobilidop** [comment]
Thank you for helping with the debugging! I know this would be an easy fix for you. But if you don't mind, I'd like to work on a solution from here, as an exercise to familiarize myself with the codebase.

**Comment by mbudiu-vmw** [comment]
sure, go ahead. I hope it won't require a dependency analysis to figure out where to insert the inlined actions (which doesn't really exist). They seem to be prependend now. The code is in inlining.cpp.
You can turn on tracing with -Tinlining:3 (the file name is used after T; 3 is a high enough level), buy I am not sure how much it will help.

**Comment by mbudiu-vmw** [comment]
I generated that output with `./p4test -top4 48 x.p4`; 48 happens to be the pass number of the inlining pass for this input. The pass numbers change depending on the files being compiled, but the compiler is supposed to be fully deterministic for a given input file, so you should be able to rerun in the debugger any number of times.

**Comment by qobilidop** [comment]
It seems this issue could be fixed at the earlier pass 7 of InstantiateDirectCalls.

Before FrontEnd_7_InstantiateDirectCalls:
```p4
control Test() {
    my_counter_t(1024) counter_set;
    apply {
        Inner.apply(counter_set);
    }
}
```

After FrontEnd_7_InstantiateDirectCalls:
```p4
control Test() {
    @name("Inner") Inner() Inner_inst;
    my_counter_t(1024) counter_set;
    apply {
        Inner_inst.apply(counter_set);
    }
}
```

In this pass, the control block instantiation (`Inner_inst`) is added at the begging of the parent control block. This is not an issue at this point, but later the reference site of `counter_set` will change from `Inner_inst.apply(counter_set)` to `Inner() Inner_inst`, as shown in the [comment above](https://github.com/p4lang/p4c/issues/3955#issuecomment-1492695031), which leads to the use-before-declaration error.

I think a simple fix would be to insert the instantiation statement always right before the `apply{}` block. Is there any problem with this solution?

**Comment by mbudiu-vmw** [comment]
Unfortunately the inlining pass is one of the most complex in the whole compiler, because the notion of constructor parameters and apply parameters complicates the inlining process.

There are quite a few passes that have to deal with the insertion of new temporaries, and in general the strategy that works best is to insert them right before the place where they are needed, but as late as possible. They have to be inserted after all the definitions that they may depend on.
