### ISSUE TITLE
When to "officially" drop support for Ubuntu 18.04 building of p4c?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#3986]
https://ubuntu.com/about/release-cycle

As you can see at the link above, the period for "hardware and maintenance updates" ends 5 years after a LTS release, so for Ubuntu 18.04 that ends during April 2023.

As far as I know, the extra 5 years of Extended Security Maintenance requires paying Ubuntu/Canonical money.

For brevity, I will call an Ubuntu LTS release "expired" if it is over 5 years since its initial release date.  So Ubuntu 16.04 is expired now, and Ubuntu 18.04 is expired some time this month, but definitely by May 1, 2023.

It seems reasonable to me that for _building_ p4c from source code (and perhaps for any other open source p4lang project), it is reasonable to no longer go to significant extra work to support that for expired Ubuntu LTS releases.  By that time, there are always 2 additional LTS releases available to use.

Do we want to make this "official p4c developer/maintainer policy"?  That is, if p4c fails to compile from source on an expired Ubuntu release, it is less likely that anyone will devote any effort to fixing such isses?  And in fact we might update some build scripts to take advantage of later versions of the build tools available as the default installable packages on later Ubuntu releases, even if that is known to break the build for expired Ubuntu versions?

Fabian Ruffy and others are currently dealing with p4c build system issues that are known to cause the build to fail for Ubuntu 18.04.  If some kind of majority of p4c developers agree that it is OK for builds of p4c on expired Ubuntu releases to no longer work, his changes can be made easier.

**Comment by jafingerhut** [comment]
@mbudiu-vmw @jnfoster @fruffy @chrisdodd @hanw @usha1830 @vgurevich Just pinging what I hope is a representative set of people on the questions raised in this issue.  I am pretty sure that the p4c build no longer works on an Ubuntu 16.04 system today, but the question of exactly how long to support expired Ubuntu releases might be one we could agree upon.

**Comment by fruffy** [comment]
I am always happy to drop older Ubuntu versions. However, Ubuntu 18.04 is the only CI check for the docker image. We have one other CI check, but that only builds and does not run tests. Regardless of the decision here, I will try to fix the issue I am encountering in #3985.

One thing we could do is to tag the commit where we officially dropped support for a particular version. That way, we can still package P4C for a particular debian/Ubuntu distribution, if needed.

**Comment by mbudiu-vmw** [comment]
I personally don't understand this desire to always use the latest and greatest. We accumulate lots of dependencies which do little to improve the code quality, but make it impossible to build on old system. If I had a choice I would never deprecate anything unless there is no workaround possible (e.g., security vulnerabilities).

**Comment by fruffy** [comment]
> I personally don't understand this desire to always use the latest and greatest. We accumulate lots of dependencies which do little to improve the code quality, but make it impossible to build on old system. If I had a choice I would never deprecate anything unless there is no workaround possible (e.g., security vulnerabilities).

Actually, with newer versions of Ubuntu we were able to reduce the number of dependencies that need to be built from scratch (protobuf, boost, thrift, and grpc). These can be pulled from the Debian/Ubuntu repositories now. Ubuntu 18.04 is the only version that still requires [third-party](https://github.com/p4lang/third-party) since some dependencies need to be prebuilt.  We have some workarounds in the build script for that: https://github.com/p4lang/p4c/blob/main/tools/ci-build.sh#L95

We could go a different route and pin **all** the dependencies in the compiler, then require them to be built before the compiler is built the first time. This would make sure that we are less dependent on specific Ubuntu versions. Since we control all dependencies and not the package maintainer. But that also means either much longer CI compilation times (because we need to build everything from scratch) or a dependency on an external repository such as third-party (which would make changes to dependencies difficult).

**Comment by jafingerhut** [comment]
At a certain age of system, in practice nearly no one is using it.  Do you run Ubuntu 14.04 any more (assuming you ever did)?  I ran it a lot 5 years ago, but not any more.  Ubuntu is actually better in this regard than some other Linux distributions, in that you get 5 free years of security and maintenance updates.  For Fedora it is only 13 months.  That is a tougher treadmill to keep up with.

**Comment by davidbolvansky** [comment]
>> I am pretty sure that the p4c build no longer works on an Ubuntu 16.04 system today

bf-p4c release is still built on this Ubuntu afaik :)

**Comment by davidbolvansky** [comment]
> I personally don't understand this desire to always use the latest and greatest. We accumulate lots of dependencies which do little to improve the code quality, but make it impossible to build on old system. If I had a choice I would never deprecate anything unless there is no workaround possible (e.g., security vulnerabilities).

I agree, totally. Code quality improvements are welcome and should make our lifes easier, not harder (by breaking builds).

**Comment by jafingerhut** [comment]
Closing this, as there seems to be little interest in dropping support for end-of-life 5+ year old versions of Linux distributions.  Keep supporting them as long as you like, I guess.

**Comment by fruffy** [comment]
With #4072 merged we are hitting the limits of our CI. It might make sense to drop some runs---or at least downgrade them to daily/weekly runs.

**Comment by davidbolvansky** [comment]
Go ahead and remove 18.04 from CI please:)
