### ISSUE TITLE
how can i solve this problem

### ISSUE THREAD

**Issue by xiaobai0102** [p4lang/p4c#3988]
[ 93%] Building CXX object test/CMakeFiles/gtestp4c.dir/gtest/helpers.cpp.o
/home/liuwei/p4c/test/gtest/helpers.cpp:18:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
test/CMakeFiles/gtestp4c.dir/build.make:244: recipe for target 'test/CMakeFiles/gtestp4c.dir/gtest/helpers.cpp.o' failed
make[2]: *** [test/CMakeFiles/gtestp4c.dir/gtest/helpers.cpp.o] Error 1
CMakeFiles/Makefile2:2565: recipe for target 'test/CMakeFiles/gtestp4c.dir/all' failed
make[1]: *** [test/CMakeFiles/gtestp4c.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xiaobai0102** [comment]
When the script runs to make - j ${MAX-PARALLEL_JOBS} in the installation p4c, an error is reported. How can I solve it? Thank you!

**Comment by fruffy** [comment]
Which version of gcc (`gcc --version`) are you using? What is the full output when you run `cmake ..`?

Usually, this error happens when you compile with a gcc or clang version that is too old or does not have `-std=c++17` enabled.

**Comment by xiaobai0102** [comment]
gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by xiaobai0102** [comment]
> Which version of gcc () are you using? What is the full output when you run ?`gcc --version``cmake ..`
> 
> Usually, this error happens when you compile with a gcc or clang version that is too old or does not have enabled.`-std=c++17`

gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
This is my version of gcc, but I don't know which one is suitable.

**Comment by xiaobai0102** [comment]
cmake .. -DCMAKE_BUILD_TYPE=DEBUG
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Found BMV2: /usr/local/bin/simple_switch  
-- Found BMV2: /usr/local/bin/simple_switch_grpc  
-- Found BMV2: /usr/local/bin/psa_switch  
-- Using the GNU gold linker.
-- Available extensions 
-- Added 537 tests to 'bmv2' (15 xfails)
-- Added 13 tests to 'bmv2-parser-inline-opt-disabled' (0 xfails)
-- Added 13 tests to 'bmv2-parser-inline-opt-enabled' (0 xfails)
-- Added 1 tests to 'bmv2-ptf' (0 xfails)
-- Added 25 tests to 'bmv2' (1 xfails)
-- Added 239 tests to 'dpdk' (0 xfails)
-- Start configuring eBPF back end
-- Detected kernel version: 4.15.0-209-generic
-- Check LLVM version with 'llvm-config --version'
-- Found LLVM 6.0.0
CMake Warning at backends/ebpf/CMakeLists.txt:198 (message):
  Missing the libbpf dependency, disabling kernel tests.  You can install
  libbpf by running './build_libbpf' in the /home/liuwei/p4c/backends/ebpf
  folder.


-- Added 26 tests to 'ebpf-bcc' (1 xfails)
-- Added 26 tests to 'ebpf' (2 xfails)
-- Done with configuring BPF back end
-- Added 2 tests to 'graph' (0 xfails)
-- Added 5 tests to 'p4' (0 xfails)
-- Added 1177 tests to 'p4' (0 xfails)
-- Added 12 tests to 'p4unroll' (0 xfails)
-- Added 13 tests to 'p4' (0 xfails)
-- Added 5 tests to 'err' (0 xfails)
-- Added 304 tests to 'err' (0 xfails)
-- Added 194 tests to 'p14_to_16' (0 xfails)
-- Added 17 tests to 'ubpf' (0 xfails)
-- CTest parallel: -j 2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/liuwei/p4c/build
When I run cmake- DCMAKE_ BUILD_ TYPE=DEBUG Its results are as above, I am not sure which part is causing the problem.

**Comment by fruffy** [comment]
You will have an easier time building P4C on Ubuntu 20.04. The minimum recommended GCC version to build the compiler is GCC 9, which is not supplied by default on Ubuntu 18.04. 

However, you can install GCC9 using the steps described here:
https://github.com/p4lang/p4c/blob/main/tools/ci-build.sh#L96

**Comment by xiaobai0102** [comment]
I'm not sure which code to run. Can you teach me? Thank you

> You will have an easier time building P4C on Ubuntu 20.04. The minimum recommended GCC version to build the compiler is GCC 9, which is not supplied by default on Ubuntu 18.04.
> 
> However, you can install GCC 9 using the steps described here: https://github.com/p4lang/p4c/blob/main/tools/ci-build.sh#L96

I'm not sure which code to run. Can you teach me? Thank you

**Comment by xiaobai0102** [comment]
> I'm not sure which code to run. Can you teach me? Thank you
> 
> > You will have an easier time building P4C on Ubuntu 20.04. The minimum recommended GCC version to build the compiler is GCC 9, which is not supplied by default on Ubuntu 18.04.
> > However, you can install GCC 9 using the steps described here: https://github.com/p4lang/p4c/blob/main/tools/ci-build.sh#L96
> 
> I'm not sure which code to run. Can you teach me? Thank you

I ran some but the error is still there. It should be that I ran the wrong one

> I'm not sure which code to run. Can you teach me? Thank you
> 
> > You will have an easier time building P4C on Ubuntu 20.04. The minimum recommended GCC version to build the compiler is GCC 9, which is not supplied by default on Ubuntu 18.04.
> > However, you can install GCC 9 using the steps described here: https://github.com/p4lang/p4c/blob/main/tools/ci-build.sh#L96
> 
> I'm not sure which code to run. Can you teach me? Thank you

I ran some but the error is still there. It should be that I ran the wrong one

**Comment by xiaobai0102** [comment]
+ make -j1
[  1%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/Unity/unity_2_cxx.cxx.o
[  2%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/Unity/unity_1_cxx.cxx.o
[  4%] Building CXX object lib/CMakeFiles/p4ctoolkit.dir/Unity/unity_0_cxx.cxx.o
[  5%] Linking CXX static library libp4ctoolkit.a
[  5%] Built target p4ctoolkit
[  7%] Building CXX object tools/ir-generator/CMakeFiles/irgenerator.dir/Unity/unity_0_cxx.cxx.o
[  8%] Linking CXX executable irgenerator
[ 11%] Built target irgenerator
[ 13%] Generating IR class files
[ 13%] Built target genIR
[ 14%] Building CXX object ir/CMakeFiles/ir.dir/Unity/unity_1_cxx.cxx.o
In file included from /home/liuwei/p4c/ir/node.cpp:20:0,
                 from /home/liuwei/p4c/build/ir/CMakeFiles/ir.dir/Unity/unity_1_cxx.cxx:4:
/home/liuwei/p4c/ir/node.h:144:43: error: ISO C++11 requires at least one argument for the "..." in a variadic macro [-Werror]
     IRNODE_ALL_SUBCLASSES(DEFINE_OPEQ_FUNC)
                                           ^
/home/liuwei/p4c/ir/node.h:144:43: error: ISO C++11 requires at least one argument for the "..." in a variadic macro [-Werror]
In file included from /home/liuwei/p4c/ir/ir-inline.h:25:0,
                 from /home/liuwei/p4c/ir/ir.h:22,
                 from /home/liuwei/p4c/ir/node.cpp:28,
                 from /home/liuwei/p4c/build/ir/CMakeFiles/ir.dir/Unity/unity_1_cxx.cxx:4:
/home/liuwei/p4c/ir/visitor.h:129:50: error: ISO C++11 requires at least one argument for the "..." in a variadic macro [-Werror]
     IRNODE_ALL_SUBCLASSES(DECLARE_VISIT_FUNCTIONS)
                                                  ^
/home/liuwei/p4c/ir/visitor.h:129:50: error: ISO C++11 requires at least one argument for the "..." in a variadic macro [-Werror]
/home/liuwei/p4c/ir/visitor.h:372:50: error: ISO C++11 requires at least one argument for the "..." in a variadic macro [-Werror]
     IRNODE_ALL_SUBCLASSES(DECLARE_VISIT_FUNCTIONS)
                                                  ^
/home/liuwei/p4c/ir/visitor.h:372:50: error: ISO C++11 requires at least one argument for the "..." in a variadic macro [-Werror]
/home/liuwei/p4c/ir/visitor.h:398:50: error: ISO C++11 requires at least one argument for the "..." in a variadic macro [-Werror]
     IRNODE_ALL_SUBCLASSES(DECLARE_VISIT_FUNCTIONS)
                                                  ^
/home/liuwei/p4c/ir/visitor.h:398:50: error: ISO C++11 requires at least one argument for the "..." in a variadic macro [-Werror]
/home/liuwei/p4c/ir/visitor.h:425:50: error: ISO C++11 requires at least one argument for the "..." in a variadic macro [-Werror]
     IRNODE_ALL_SUBCLASSES(DECLARE_VISIT_FUNCTIONS)
                                                  ^
/home/liuwei/p4c/ir/visitor.h:425:50: error: ISO C++11 requires at least one argument for the "..." in a variadic macro [-Werror]
In file included from /home/liuwei/p4c/build/ir/CMakeFiles/ir.dir/Unity/unity_1_cxx.cxx:8:0:
/home/liuwei/p4c/ir/visitor.cpp:479:45: error: ISO C++11 requires at least one argument for the "..." in a variadic macro [-Werror]
 IRNODE_ALL_SUBCLASSES(DEFINE_VISIT_FUNCTIONS)
                                             ^
/home/liuwei/p4c/ir/visitor.cpp:479:45: error: ISO C++11 requires at least one argument for the "..." in a variadic macro [-Werror]
/home/liuwei/p4c/ir/visitor.cpp:610:45: error: ISO C++11 requires at least one argument for the "..." in a variadic macro [-Werror]
 IRNODE_ALL_SUBCLASSES(DEFINE_VISIT_FUNCTIONS)
                                             ^
/home/liuwei/p4c/ir/visitor.cpp:610:45: error: ISO C++11 requires at least one argument for the "..." in a variadic macro [-Werror]
cc1plus: all warnings being treated as errors
ir/CMakeFiles/ir.dir/build.make:62: recipe for target 'ir/CMakeFiles/ir.dir/Unity/unity_1_cxx.cxx.o' failed
make[2]: *** [ir/CMakeFiles/ir.dir/Unity/unity_1_cxx.cxx.o] Error 1
CMakeFiles/Makefile2:1824: recipe for target 'ir/CMakeFiles/ir.dir/all' failed
make[1]: *** [ir/CMakeFiles/ir.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
It seems like a new w has appeared

**Comment by fruffy** [comment]
So the steps for installing gcc should be something like 
```
  sudo apt-get update && sudo apt-get install -y software-properties-common
  sudo add-apt-repository -uy ppa:ubuntu-toolchain-r/test
  sudo apt-get install gcc-9 g++-9
  export CC=gcc-9
  export CXX=g++-9
```
Then wipe your build folder and rerun
```
cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/g++-9 -DCMAKE_C_COMPILER=/usr/bin/gcc-9
```
in it.

**Comment by xiaobai0102** [comment]
> 所以安装 gcc 的步骤应该是这样的
> 
> ```
>   sudo apt-get update && sudo apt-get install -y software-properties-common
>   sudo add-apt-repository -uy ppa:ubuntu-toolchain-r/test
>   sudo apt-get install gcc-9 g++-9
>   export CC=gcc-9
>   export CXX=g++-9
> ```
> 
> 然后擦除您的构建文件夹并重新运行
> 
> ```
> cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/g++-9 -DCMAKE_C_COMPILER=/usr/bin/gcc-9
> ```
> 
> 在其中。

Thank you for your answer.I plan to test this script on Ubuntu 20.04 now, but when the script is executed to cmake- DCMAKE_ BUILD_ The execution is slow when TYPE=DEBUG $*, I don't know why. But I haven't reported an error yet.

**Comment by xiaobai0102** [comment]
> > 所以安装 gcc 的步骤应该是这样的
> > ```
> >   sudo apt-get update && sudo apt-get install -y software-properties-common
> >   sudo add-apt-repository -uy ppa:ubuntu-toolchain-r/test
> >   sudo apt-get install gcc-9 g++-9
> >   export CC=gcc-9
> >   export CXX=g++-9
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后擦除您的构建文件夹并重新运行
> > ```
> > cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/g++-9 -DCMAKE_C_COMPILER=/usr/bin/gcc-9
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在其中。
> 
> 谢谢你的回答。我现在计划在 Ubuntu 20.04 上测试这个脚本，但是当脚本执行到 cmake- DCMAKE_ BUILD_ 当 TYPE=DEBUG $* 时执行很慢，我不知道为什么。但我还没有报告错误。

Actually, I don't know how to erase the built files either

**Comment by xiaobai0102** [comment]
> > 所以安装 gcc 的步骤应该是这样的
> > ```
> >   sudo apt-get update && sudo apt-get install -y software-properties-common
> >   sudo add-apt-repository -uy ppa:ubuntu-toolchain-r/test
> >   sudo apt-get install gcc-9 g++-9
> >   export CC=gcc-9
> >   export CXX=g++-9
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后擦除您的构建文件夹并重新运行
> > ```
> > cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/g++-9 -DCMAKE_C_COMPILER=/usr/bin/gcc-9
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在其中。
> 
> Thank you for your answer.I plan to test this script on Ubuntu 20.04 now, but when the script is executed to cmake- DCMAKE_ BUILD_ The execution is slow when TYPE=DEBUG $*, I don't know why. But I haven't reported an error yet.

Actually, I don't know how to erase the built files either

**Comment by xiaobai0102** [comment]
> On Ubuntu 20.04 you should not need all these workarounds, you should be able to install everything after you installed the dependencies listed here: https://github.com/p4lang/p4c#ubuntu-dependencies
> 
> You can wipe your build folder with
> 
> ```
> rm -rf build
> ```
> 
> wherever you have created the folder. This will reset your cmake and build state.
> 
> You can use `-DCMAKE_BUILD_TYPE=RelWithDebInfo` to build debug symbols with release mode, which is a bit faster.

I ran install-p4dev v6. sh directly using a script. I hope there won't be any issues

**Comment by fruffy** [comment]
Sounds good, let me know how it goes. 

@jafingerhut May be able to help if there are problems with the `install-p4dev-v6.sh` script.

**Comment by xiaobai0102** [comment]
> Sounds good, let me know how it goes.
> 
> @jafingerhut May be able to help if there are problems with the script.`install-p4dev-v6.sh`

Cloning https://github.com/p4lang/p4runtime-shell.git to /tmp/pip-req-build-7u9wjppm
  Running command git clone --filter=blob:none --quiet https://github.com/p4lang/p4runtime-shell.git /tmp/pip-req-build-7u9wjppm
  fatal: unable to access 'https://github.com/p4lang/p4runtime-shell.git/': GnuTLS recv error (-54): Error in the pull function.
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/p4lang/p4runtime-shell.git /tmp/pip-req-build-7u9wjppm did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/p4lang/p4runtime-shell.git /tmp/pip-req-build-7u9wjppm did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
^C

**Comment by jafingerhut** [comment]
I am no longer testing my install scripts in the p4-guide repository with Ubuntu 18.04, because it is no longer supported with free security updates by Canonical.  If they happen to be useful for someone, great, but I do not plan to make changes to them if they fail to work on Ubuntu 18.04.  I do regularly test with Ubuntu 20.04 and 22.04.

**Comment by xiaobai0102** [comment]
> I am no longer testing my install scripts in the p4-guide repository with Ubuntu 18.04, because it is no longer supported with free security updates by Canonical. If they happen to be useful for someone, great, but I do not plan to make changes to them if they fail to work on Ubuntu 18.04. I do regularly test with Ubuntu 20.04 and 22.04.

Finally, I downloaded P4 related content using your script on Ubuntu 20.04. Thank you very much. I will also try again on Ubuntu 18.04 in the future. Thank you

**Comment by xiaobai0102** [comment]
> Sounds good, let me know how it goes.
> 
> @jafingerhut May be able to help if there are problems with the `install-p4dev-v6.sh` script.



> Sounds good, let me know how it goes.
> 
> @jafingerhut May be able to help if there are problems with the `install-p4dev-v6.sh` script.

I have successfully installed the basic content. Thank you very much for your guidance

**Comment by fruffy** [comment]
Closing because this issue appears to be resolved.
