### ISSUE TITLE
p4tc pollutes IR-generated.h with generic #defines

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#4028]
@Sosutha 

https://github.com/p4lang/p4c/blob/main/backends/tc/tc_defines.h is included in the `.def` file and declares very generic `#defines`. These #defines can potentially clash with other back ends. Please make sure these #defines are constant expressions and wrap them in a namespace.

**Comment by Sosutha** [comment]
I will update accordingly

**Comment by fruffy** [comment]
Thanks, an example how this could look like is this file:
https://github.com/p4lang/p4c/blob/main/backends/p4tools/modules/testgen/targets/bmv2/constants.h#L10

**Comment by zxy909** [comment]
Hi,
p4c tc backend seems to be a problem with the command to create the table entry.

I have tried compiling the p4 file in p4tc-v2-examples (https://github.com/p4tc-dev/p4tc-v2-examples/blob/main/model2/1table/exact/redirect_l2_pna_1t_exact.p4) with p4tc backend, But the generated runtime file doesn't seem to match the current p4tc code.
The shell command to create a table table in the generated runtime file is as follows,
```
$TC p4template create table/redirect_l2_pna_1t_exact/ingress/nh_table \
tblid 1\
type EXACT_TYPE \
keysz 32 nummasks 8 tentries 262144 \
table_acts act name redirect_l2_pna_1t_exact/ingress/send_nh \
act name redirect_l2_pna_1t_exact/ingress/drop
```
The type type is EXACT_TYPE, but the type defined by p4tc is exact, so an error occurs.
In the backends/tc/tc.def file, should the strings `EXACT_TYPE`, `LPM_TYPE`, `TERNARY_TYPE` be `exact`, `lpm`, `ternary`?
```
        switch(matchType) {
                case EXACT_TYPE :
                    matchTypeString = "EXACT_TYPE";
                    break;
                case LPM_TYPE :
                    matchTypeString = "LPM_TYPE";
                    break;
                case TERNARY_TYPE :
                    matchTypeString = "TERNARY_TYPE";
                    break;
        }
```
