### ISSUE TITLE
The relation between parser state and header

### ISSUE THREAD

**Issue by Mohxen** [p4lang/p4c#4032]
Hi all,
For example, we have a header udp_t {} and state parse_udp {} and I think compiler can understand the relation between them. Please let me know how compiler can understand this.
Thank you.

**Comment by mihaibudiu** [comment]
I don't understand the relation between them. I doubt the compiler can do better.

**Comment by Mohxen** [comment]
Thank you, I thought there is a relation between parser state and its corresponding header, so there is not :). Please let me know whether compiler understand the relation between parser state (parse_udp) and deparser (packet.emit(hdr.udp)) with hdr.udp or not.
```
    state parse_udp {
       packet.extract(hdr.udp);
       transition accept;
    }
```
```
header udp_t {
    bit<16> srcPort;
    bit<16> dstPort;
    bit<16> length_;
    bit<16> checksum;
}
```
```
control MyDeparser(packet_out packet, in headers hdr) {
    apply {
        packet.emit(hdr.ethernet);
        packet.emit(hdr.ipv4);
        packet.emit(hdr.udp);
        }
}
```

**Comment by mihaibudiu** [comment]
There isn't any relationship between the parser and the deparser.
In P4-14 the deparser was inferred from the parser: it would emit all headers in the 'headers' structure.
For other targets than v1model this is not necessarily true.
If you say something like `packet.emit(hdr)` this will emit all valid headers in hdr.
But still, this only depends on the headers, and has no relationship to any parser at all. (Some architectures can have many parsers.)

**Comment by Mohxen** [comment]
Thank you, Please let me know for example for header ipv4_t, with which functions we can access hdr.ipv4.ttl as ttl element of the header of ipv4. Please let me know if there is a relation?
```
header ipv4_t {
    bit<4>    version;
    bit<4>    ihl;
    bit<8>    diffserv;
    bit<16>   totalLen;
    bit<16>   identification;
    bit<3>    flags;
    bit<13>   fragOffset;
    bit<8>    ttl;
    bit<8>    protocol;
    bit<16>   hdrChecksum;
    ip4Addr_t srcAddr;
    ip4Addr_t dstAddr;
}
```
```
struct headers {
    ethernet_t   ethernet;
    ipv4_t       ipv4;
    tcp_t        tcp;
    udp_t        udp;
}
```
```
control MyIngress(inout headers hdr,
                  inout metadata meta,
                  inout standard_metadata_t standard_metadata) {
    action drop() {
        mark_to_drop(standard_metadata);
    }
    
    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
        standard_metadata.egress_spec = port;
        hdr.ethernet.srcAddr = hdr.ethernet.dstAddr;
        hdr.ethernet.dstAddr = dstAddr;
        hdr.ipv4.ttl = hdr.ipv4.ttl - 1;
    }
```

**Comment by fruffy** [comment]
The compiler front end does not really try to match data structures based on their names written by the program. However, it does know the types of each variable reference. 

In this case `hdr.ipv4.ttl = hdr.ipv4.ttl - 1;` it knows that `hdr` is a `struct headers`, which has the member `ipv4`. That member `ipv4` is of type `header ipv4`, which has a member `ttl`.

**Comment by Mohxen** [comment]
Thank you so much @mihaibudiu and @fruffy
