### ISSUE TITLE
Issues with p4testgen back end

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#4033]
Sample command line here: 
is:
```
p4testgen –target [TARGET] –arch [ARCH] –max-tests 10 –out-dir [OUT] prog.p4
```
but current p4testgen as of 2023-Jun-16 gives error unless one also supplies `--test-backend ptf` or one of the other allowed test backends.

Is it expected that stf and metadata test-backends produce only 1 test case, even if the p4testgen output says it is generating more?

Very minor: Seems slightly weird that test cases are numbered [0, N-1] in protobuf back end, but [1,N] in PTF test Python program.  Given that numbers of test cases start with 0 in stdout output of p4testgen, seems better to number them starting from 0 in Python PTF code, too.

In the PTF back end, the Python program written by p4testgen has a `@bt.autocleanup` decorator on the `setUp` method of class `AbstractTest`.  It does _nothing_ there.  I believe it should instead be on the `runTestImpl` method, where I have found that it actually can remove table entries at the end of a test case execution.

**Comment by jafingerhut** [comment]
Another PTF test problem: When a test case has no output packets, its `verifyPackets` method contains only `pass`.

I believe it should instead verify that no packets came out using a call like: `ptfutils.verify_no_other_packets(self, timeout=2)`

**Comment by fruffy** [comment]
Thanks for looking into this. 

> but current p4testgen as of 2023-Jun-16 gives error unless one also supplies `--test-backend ptf` or one of the other allowed test backends.

The available test back ends depends on the target. Currently, this check is done quite late because the target has to be instantiated first. We could decide for a default back end for each target instead to make this a little easier.

> Is it expected that stf and metadata test-backends produce only 1 test case, even if the p4testgen output says it is generating more?

This may depend on the program. If the program only has one valid path we will only generate 1 tests. max-tests can be seen as an upper bound. 


> Very minor: Seems slightly weird that test cases are numbered [0, N-1] in protobuf back end, but [1,N] in PTF test Python program. Given that numbers of test cases start with 0 in stdout output of p4testgen, seems better to number them starting from 0 in Python PTF code, too.

This is an inconsistency I should fix. It came from disagreements whether to start numbering at 0 or 1 :-).

> In the PTF back end, the Python program written by p4testgen has a `@bt.autocleanup` decorator on the `setUp` method of class `AbstractTest`. It does _nothing_ there. I believe it should instead be on the `runTestImpl` method, where I have found that it actually can remove table entries at the end of a test case execution.

Thanks for pointing that out, I was not sure what the annotation was for. Will fix.

**Comment by jfingerh** [comment]
"Let me think about whether there are cases where this could break. I believe part of the reason this was done was to support cloning."

Understood there might be subtleties here.  In general, p4testgen should be able to create test cases where it knows exactly the expected set of output packets, whether that is the empty set, one, or N > 1 packets, and which output ports they will go out.  In  my opinion, the test cases should specify that exact set of packets, and fail if some other set of (output port, packet) pairs goes out of the device being tested.
