### ISSUE TITLE
Arbitrary key masks not supported in P4_16

### ISSUE THREAD

**Issue by ChrisDodd** [p4lang/p4c#404]
P4_14 allows a mask to be used in the reads expression for a table:
```
table test1 {
    reads {
        data.f1 mask 0xff00ff : exact;
    }
```

but there does not appear to be any equivalent functionality in P4_16 -- using `data.f1 &&& 0xff00ff` gives a "syntax error, unexpected MASK"

When using the P4_14 frontend, it gives weird errors from the typechecker after converting to (apparently invalid) P4_16 code.

**Comment by mbudiu-vmw** [comment]
The meaning of key masks is not defined anywhere in the P4-14 spec.
The same thing can be achieved using slices and concatenation in P4-16.
However, the implications on the control-plane are unclear.

**Comment by ChrisDodd** [comment]
The meaning in P4_14 is pretty clear -- only some of the bits of the field are used for the key.  The way the API currently works for it is to take a value for the field when constructing the action, but ignoring all bits of that value that are not set in the mask.

**Comment by mbudiu-vmw** [comment]
There are no "fields" in the API. The question is "how does the API populate tables entries for tables that have a key mask. How is the key specified for such an entry?" I expect that the whole key is not stored in the physical table - it would be a waste of precious table storage to store key bits that are never used. So somehow the control-plane has to know what bits to strip out when populating the table.

**Comment by mbudiu-vmw** [comment]
In other words, the mask is (probably) not useful for the data-plane, it is probably only useful for the control-plane. But it really depends on the target.

**Comment by mbudiu-vmw** [comment]
If that is true, one way to translate this is to keep the full key ignoring the mask and add an annotation @mask(0xff00ff) which is only used for the API generation.

**Comment by mbudiu-vmw** [comment]
The spec of P4-16 does not allow masks for keys.
We can take this to the design committee to see whether this should be added.
In the meantime the simplest way to do the translation is to carry a @mask annotation with the key field, and use it in the BMv2 back-end and in the API generation.

**Comment by ChrisDodd** [comment]
Actually, since P4_16 allow arbitrary expressions in keys, we don't really need masks as such -- just using a bitwise `&` with a constant has the same effect.

The only issue is with naming -- should be allow a key like:
```
data.f1 & 0xff00ff : exact
```
with no explicit name (`@name` or otherwise) and infer the name `data.f1` for it?

**Comment by mbudiu-vmw** [comment]
There is already an inspector called TableKeyNames which does exactly this. It won't work in this context as is, but since we are talking about P4-14 you only need a small subset of that visitor.

**Comment by mbudiu-vmw** [comment]
Actually you also need the control-plane to never insert non-zero bits for the masked bits for this to work.

**Comment by mbudiu-vmw** [comment]
This has been fixed, but the issue of how this impacts the control-plane is still open.

**Comment by mbudiu-vmw** [comment]
I will close this, since we now support masks on keys. If there are problems with the control-plane another issue should be opened.
