### ISSUE TITLE
Make it impossible to instantiate std::set and std::map with IR::INode subclass pointers

### ISSUE THREAD

**Issue by sethfowler** [p4lang/p4c#406]
We've run into a number of problems with using std::set and std::map with pointers to IR nodes. Because those data structures are sorted by their keys, storing pointers in them makes the iterator order essentially random, which introduces a lot of nondeterminism into the execution of the compiler. That makes debugging much harder.

One solution is just forbid this. Things like `std::set<IR::Node*>` or `std::map<const IR::Parameter*>` should just not compile.

If we want to, we can do this. Adding the following code to `ir/node.h` is sufficient:

```c++
namespace IR {
class INode;

void accept_node_ptr(const INode*);
template <typename T, typename = decltype(accept_node_ptr(std::declval<T>()))>
using enable_if_node_ptr = T;

}  // namespace IR

namespace std {

template<class T, class Compare>
class set<IR::enable_if_node_ptr<T>, Compare, allocator<T>> {
  set() = delete;  // Bad! Sets of pointers to IR nodes result in nondeterminism!
};

template<class Key, class T, class Compare>
class map<IR::enable_if_node_ptr<Key>, T, Compare, std::allocator<std::pair<const Key, T>>> {
  map() = delete;  // Bad! Maps of pointers to IR nodes result in nondeterminism!
};

}  // namespace std
```

Unfortunately, there are a lot of instances of this in our code already, so to land this change we'd need to fix those instances first.

I'm filing this as an issue rather than a PR is because I want to make sure this is something we actually want. How do folks feel about totally forbidding these instantiations?

**Comment by mbudiu-vmw** [comment]
Having sets is harmless. 
Iterating over the sets is harmful.
It would be nice if you could just disable the iterators.

**Comment by sethfowler** [comment]
That's true, but unfortunately, it's much, much harder.
