### ISSUE TITLE
Add tests for which member types are allowed within headers, structs, and tuples

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#407]
[member-types.p4.txt](https://github.com/p4lang/p4c/files/879681/member-types.p4.txt)

Mihai Budiu would like compiler tests for all possible allowed types of members for headers, structs, and tuples, and all disallowed types.  The attached file contains uncommented lines for all of the combinations that give no errors with p4test and p4c-bm2-ss as of 2017-Mar-28, and have commented-out lines for the combinations that give errors (many of which, such as the ones inside headers, we expect should give errors, but some combinations that give errors for structs look like bugs to Mihai).

I am guessing the desire would be to have one test case like the attached file with all of the supported combinations, and perhaps one smaller separate negative test case for each combination for which the compiler should give an error.

**Comment by mbudiu-vmw** [comment]
I have fixed several of these. There is one big issue remaining: the bmv2 back-end does not work when you have a control or parser argument whose type contains nested structs (or tuples). I am thinking to file a separate issue for just that case; it may be harder to fix than the ones I've done. I have to think about it some more.

An important question is whether the compiler is allowed to change the signature of a parser or control. We don't know whether this has any bearing on the control-plane.

**Comment by mbudiu-vmw** [comment]
I will close this issue, since it is very broad and we fixed many cases covered.
If there are other known cases please file more specific issues.
