### ISSUE TITLE
Possible type checking bug.

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#409]
Compiling this program with `p4c-bm2-ss`,
```
#include <v1model.p4>

header h_t {
  bit<8> f;
}

struct my_packet {
  h_t h;
}

struct my_metadata {
}

parser MyParser(packet_in b, out my_packet p, inout my_metadata m, inout standard_metadata_t s) {
  state start {
   transition accept;
  }
}

control MyVerifyChecksum(in my_packet hdr, inout my_metadata meta) {
  apply { }
}

control MyIngress(inout my_packet p, inout my_metadata m, inout standard_metadata_t s) {
  apply {
    random(p.h.f, 0, 1);
  }
}

control MyEgress(inout my_packet p, inout my_metadata m, inout standard_metadata_t s) {
  apply { }
}

control MyComputeChecksum(inout my_packet p, inout my_metadata m) {
  apply { }
}

control MyDeparser(packet_out b, in my_packet p) {
  apply { }
}

V1Switch(MyParser(), MyVerifyChecksum(), MyIngress(), MyEgress(), MyComputeChecksum(), MyDeparser()) main;
```
produces an error:
```
min.p4(27): error: random: Cannot unify bit<8> to bit<32>
    random(p.h.f, 0, 1);
    ^^^^^^^^^^^^^^^^^^^
```

Adding a cast,
```
control MyIngress(inout my_packet p, inout my_metadata m, inout standard_metadata_t s) {
  apply {
    random((bit<32>)p.h.f, 0, 1);
  }
}
```
doesn't help:
```
min.p4(26): error: : Read-only value used for out/inout parameter result
    random((bit<32>)p.h.f, 0, 1);
           ^^^^^^^^^^^^^^
/home/ubuntu/p4c/build/p4include/v1model.p4(85)
extern void random(out bit<32> result, in bit<32> lo, in bit<32> hi);
                               ^^^^^^
```

Instead, I have to introduce my own local variable:
```
control MyIngress(inout my_packet p, inout my_metadata m, inout standard_metadata_t s) {
  apply {
    bit<32> x;
    random(x, 0, 1);
    p.h.f = x;
  }
}
```

**Comment by jnfoster** [comment]
How should implicit cast insertion work for out parameters?

**Comment by mbudiu-vmw** [comment]
There is no implicit cast insertion for parameters, in or out.

**Comment by jnfoster** [comment]
By copy-in/copy-out semantics (just copy-out semantics in this instance), I'd expect things to work just like the version with a local variable x. But it doesn't...

**Comment by mbudiu-vmw** [comment]
At least that's what the spec says.
The spec says that only assignment may introduce an implicit cast (and operations with an int).
This is not strictly assignment.

**Comment by jnfoster** [comment]
Fair enough. I think we can agree it's not super programmer friendly?

**Comment by mbudiu-vmw** [comment]
I think that this is actually a good behavior, you don't want to lose these bits accidentally because the compiler inserts a cast for you.

**Comment by mbudiu-vmw** [comment]
The programmer has to think what happens to the extra bits.

**Comment by jnfoster** [comment]
Ahh, the classic "it's a feature not a bug" ;-)

**Comment by mbudiu-vmw** [comment]
Programmers may hate you in the short term, but will thank you in the long term.
Implicit casts are evil. They change your program in invisible ways.
This is an important principle in the design of P4 - no surprises.

**Comment by jnfoster** [comment]
Sure, I find that convincing, except we argue the opposite for binary operations where one argument is `int` and another is fixed-width:

> Most binary operations that take an int and a fixed-width operand will insert an implicit cast to convert the int operand to the type of the fixed-width operand. (Section 8.9.2)

**Comment by mbudiu-vmw** [comment]
We are not arguing the opposite, we claim that there is no surprise in this case. 
Initially I wanted users to specify the width of all constants, but there was a revolt, and I relented. I think that this is reasonable.

**Comment by jnfoster** [comment]
Not disagreeing, but as a programmer it'd be nice if `+` and an extern `add<T>(out T result, in T op1, in T op2` behaved the same with respect to implicit casts...
