### ISSUE TITLE
Add dynamic array to p4c

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#4095]
A P4 node terminating traffic reassembles traffic and needs packet buffering. Also a P4 node may buffer packets and add/delete packets in a list.

**Comment by vgurevich** [comment]
@hesingh -- as of today, it is a known fact that P4 has not been designed to work with packet payloads. The only thing it has so far, are a couple of externs, `packet_in` and `packet_out` that have fairly limited functionality.

Nevertheless, before we start adding new constructs, it would be helpful to describe in detail what you are trying to achieve. For example, as of today the packet buffering functionality is not expressable in P4 and therefore even very complex buffering engines are exposed as fixed-function components interfacing with the rest of the P4 program using intrinsic metadata. Only after you demonstrate that the current mechanisms (externs and intrinsic metadata) are not sufficient to express what you need, then we should start looking at new constructs. 

Also, this has nothing to do with the compiler and should better be discussed in p4-spec.

**Comment by hesingh** [comment]
Terminating nodes for P4 need buffering - its already described in this is issue  - these are nodes running at 800 Gbs. Also, see https://github.com/p4lang/p4-spec/issues/1264

**Comment by hesingh** [comment]
My ask has been discussed in p4-design in detail after this presentation: https://opennetworking.org/wp-content/uploads/2021/05/Gergely-Pongracz-Slides.pdf

See slide 4 and the service is on a terminating node. My company's p4c already supports a timer. All that is left to support in P4 in dynamic array of packets.

**Comment by hesingh** [comment]
QUIC uses buffers and timers too and send and receive nodes run QUIC.

**Comment by vgurevich** [comment]
I think that p4lang/p4-spec#1264 is a more appropriate place to discuss your request, so let's move there. There is nothing to add to the public compiler unless the feature is defined in a public spec. Note, that you are free to implement/prototype the feature in your own compiler.

All my comments still stand: it is not enough to simply request a feature -- there has to be a detailed justification that explains why it is needed in the first place (and can't be implemented using existing mechanisms) and a proposals that will show how do you want it to look like.

**Comment by hesingh** [comment]
I see that the p4-16 specification does discuss checksum for simple switch and this extern is defined in v1model.p4 and implement ed in the p4c bmv2 backend. So some p4 spec for terminating node could define the new extern and a terminating node p4c backend implements the extern, e.g., pna. I agree to discus first in p4-spec forum.

**Comment by jafingerhut** [comment]
@hesingh FYI, all of the externs defined in the P4_16 language specification that are _not_ defined in core.p4, are _examples_ of extern definitions.  Just because they appear in the language specification as examples, does not imply that they are standard in any P4 architecture.
