### ISSUE TITLE
bit<W> to int<W> cast on const value fails if MSB is set

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#412]
Example:

    const bit<16> c1 = 16w0xbeef;
    const int<16> c1s = (int<16>) c1;

    % p4test allowed-construct.p4
    allowed-construct.p4(48): warning: 48879: signed value does not fit in 16 bits
    const bit<16> c1 = 16w0xbeef;
                       ^^^^^^^^^

Section 8.9.1 "Explicit casts" of P4_16 draft spec says:

    bit<W> -> int<W>: preserves all bits unchanged; values with the MSB set are reinterpreted as negative values.

**Comment by mbudiu-vmw** [comment]
This is a warning.
Why do you say that this fails?

**Comment by jafingerhut** [comment]
Ugh.  Sorry for the noise.  Not reading messages carefully enough.  Closing.
