### ISSUE TITLE
Missing release docker images on Dockerhub

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#4123]
I just noticed that although we do release images on DockerHub, we do not provided docker images of tagged versions:
https://hub.docker.com/r/p4lang/p4c/tags

This is probably something we should consider. Is this complicated to set up? Do you know by any chance @rst0git or @antoninbas? I am not sure who currently maintains the Github action which pushes to Dockerhub.

**Comment by rst0git** [comment]
@fruffy The [container-image](https://github.com/p4lang/p4c/blob/main/.github/workflows/ci-container-image.yml) action currently updates the container image in DockerHub after every pull request merged in the main branch. This is similar to [BMv2](https://github.com/p4lang/behavioral-model/blob/main/.github/workflows/build.yml) and [PI](https://github.com/p4lang/PI/blob/main/.github/workflows/build.yml). To provide container images with tagged versions, we can update the [release](https://github.com/p4lang/p4c/blob/main/.github/workflows/ci-release.yml) action to build & push an image when a new p4c release is created.

**Comment by fruffy** [comment]
That sounds good, can we do it? Seems like a simple change. What do I need to change?

**Comment by rst0git** [comment]
Sure, I will test this change in my GitHub fork and open a pull request.

**Comment by fruffy** [comment]
https://hub.docker.com/r/p4lang/p4c/tags 
I checked the tags after the release build was merged but the latest one is not there. Is there something missing or do we have to wait for the next release?

**Comment by rst0git** [comment]
@fruffy A container image with `1.2.4.3` tag is now available in DockerHub.
```
$ podman run -it p4lang/p4c:1.2.4.3 p4c --version
p4c 1.2.4.3 (SHA:  BUILD: RELEASE)
```

**Comment by fruffy** [comment]
Wonderful, thank you!
