### ISSUE TITLE
Ubuntu 20.04 p4lang packages has issues with signatures?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#4127]
I tried the following sequence of commands on a freshly installed Ubuntu 20.04 system a few minutes ago:
```
echo "deb http://download.opensuse.org/repositories/home:/p4lang/xUbuntu_20.04/ /" | sudo tee /etc/apt/sources.list.d/home:p4lang.list
wget -qO - "http://download.opensuse.org/repositories/home:/p4lang/xUbuntu_20.04/Release.key" | apt-key add -
apt-get update -qq
```
The output from the last command was:
```
$ sudo apt-get update -qq
W: GPG error: http://download.opensuse.org/repositories/home:/p4lang/xUbuntu_20.04  InRelease: The following signatures were invalid: EXPKEYSIG A4666B6753C0F7D1 home:p4lang OBS Project <home:p4lang@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/home:/p4lang/xUbuntu_20.04  InRelease' is not signed.
```
This happened at least 3 times in the past hour.

@rst0git Do you know why this might be?  Or know who I should ask?

**Comment by fruffy** [comment]
The opensuse package repository frequently has issues like this. I am not sure what we can do about it.

**Comment by rst0git** [comment]
I triggered a rebuild for the packages in the Open Build Service and this seems to have fixed this problem.

**Comment by fruffy** [comment]
Thanks!
