### ISSUE TITLE
Compiler crash on a particular action call

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#413]
Attempting to compile the P4_16 program in the attached file causes a crash in the compiler, one that does not occur if the call to the action foo2() is commented out.  The action call looks like it should be legal to me -- is it?  Even if not, a compiler crash seems a bit severe.
[crash.p4.txt](https://github.com/p4lang/p4c/files/884556/crash.p4.txt)

**Comment by mbudiu-vmw** [comment]
This is an important question that the spec should settle: can we call actions from a parser directly?
It looks reasonable - especially since we don't have any other kinds of user-defined functions.
I will file a bug with the spec too.

**Comment by jafingerhut** [comment]
Link to issue on p4-spec repo: https://github.com/p4lang/p4-spec/issues/151

**Comment by jafingerhut** [comment]
I've verified that after the commits made to fix the crash, the compiler no longer crashes when compiling the sample test program I gave.  Closing this issue.
