### ISSUE TITLE
Unexpected type void in lookahead

### ISSUE THREAD

**Issue by jhavrane** [p4lang/p4c#4146]
### Issue
```
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  In file: ./p4c/midend/interpreter.cpp:52
Compiler Bug: void: unexpected type
```

### P4 program
```
#include <core.p4>

parser Parser(packet_in pkt);
package SimpleArch(Parser p);

parser MyParser(packet_in packet) {
   state start {
       packet.lookahead<void>();
       transition accept;
   }
}

SimpleArch(MyParser()) main;
```

**Comment by fruffy** [comment]
Out of curiosity: How are you finding all these issues? Is this a backlog or are you using some form of fuzzing technique?

**Comment by jhavrane** [comment]
4 bugs were found using a fuzzifier and are from a backlog. The rest was found manually during experiments today.

@mihaibudiu, sure, but it seems that I don't have a permission to assign myself yet. I'm also waiting for authorization to sign CLA.

**Comment by mihaibudiu** [comment]
You can just add a comment if you plan to fix them, so we don't duplicate work.
