### ISSUE TITLE
P4 program coding style

### ISSUE THREAD

**Issue by williamtu** [p4lang/p4c#415]
Hi,
Is there any file specifying the P4 program's coding style? I couldn't find anything in p4c/docs/
Thanks

**Comment by mbudiu-vmw** [comment]
There is an emacs p4-mode.el, but it has several bugs. Better than nothing, though.

**Comment by mbudiu-vmw** [comment]
@vgurevich : I have assigned this to you, maybe you want to fix the emacs file? I got the original one from you. Maybe you have by now also vi support?

The bugs that I am aware of are the following:
#include is not indented properly
if/else is not indented properly
