### ISSUE TITLE
Ignore unknown annotations/pragmas

### ISSUE THREAD

**Issue by cc10512** [p4lang/p4c#416]
Unknown @annotations should print a warning, but not give an error.

**Comment by mbudiu-vmw** [comment]
I think that today they are silently ignored.
Unfortunately I don't think that the front-end or mid-end can do anything about this: only the back-end knows what annotations it recognizes. We can however have a pass similar to ValidateTableProperties for annotations.

**Comment by mbudiu-vmw** [comment]
It would be easy to check that there are no unknown annotations.
What is much harder to check is whether the annotations are used where they are supposed to be. E.g., @name annotations only make sense on declarations. The rules for each annotation type can be very complicated. So I think it is safer to go the Java/C# route: do not mandate anything in the spec about unknown annotations, and do the same thing in the compiler front-end.

**Comment by cc10512** [comment]
@mbudiu-vmw they were not silently ignored. Agreed that we should not mandate anything in the spec other that they should not do anything. However, an implementation (like p4c) should decide how to handle them. I thought warnings are a fair game, especially if we add support for ignoring classes of warnings. Silently ignored is not always the best, as people may think their annotation does something.

**Comment by mbudiu-vmw** [comment]
@cc10512 : what are you proposing to do about this issue?

**Comment by cc10512** [comment]
Fixed by #419
