### ISSUE TITLE
Error reported when `--port-ranges` option is used in Testgen DPDK/PNA mode

### ISSUE THREAD

**Issue by Hoooao** [p4lang/p4c#4172]
For instance ```p4testgen --target dpdk --arch pna --test-backend PTF --packet-size-range 0:12000 --port-ranges 0:8  --print-traces --seed 1000 --max-tests 10   --out-dir /small_sample.out  /small_sample.p4``` will yield `[--Werror=invalid] error: <=: operands have different types: bit<9> and bit<32>
[--Werror=invalid] error: <=: operands have different types: bit<32> and bit<9>
Internal error: In file: /p4c/frontends/p4/optimizeExpressions.h:17
Compiler Bug: Encountered errors while trying to optimize expressions.`

**Comment by fruffy** [comment]
Fixed with #4177
