### ISSUE TITLE
crash when compiling program with return inside action

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#420]
Tested with 2017-Mar-30 version of p4test and p4c-bm2-ss, using attached program.  Crash with return statement in action, no crash when the return statement in action is removed.  P4_16 spec explicitly mentions allowing return statements in controls and actions.  I found several test cases in p4c/testdata/p4_16_samples with return statements in controls, but none with return statements in actions.
[crash-for-return-in-action.p4.txt](https://github.com/p4lang/p4c/files/888533/crash-for-return-in-action.p4.txt)

**Comment by mbudiu-vmw** [comment]
The comment in your code is worried also about a warning being issued.
I think that the warning is actually OK, since the assignment in the 'if' is actually dead code; in the end the parameter ends up being dead code too.

**Comment by jafingerhut** [comment]
With this commit: https://github.com/p4lang/p4c/commit/a9dfc16ca69cc053a7116b9ca3b1c0e00465ccea

I have tested that the crash is gone, and no warnings or other problems occur, neither with p4test nor with p4c-bm2-ss, on the test program.  Closing this issue.
