### ISSUE TITLE
[P4Testgen] How to capture traces in generated test cases?

### ISSUE THREAD

**Issue by qobilidop** [p4lang/p4c#4202]
I see there is `traces` field in the `TestCase` proto:

https://github.com/p4lang/p4c/blob/112b734b5b23500c53c199b30bb2d914c52c146c/backends/p4tools/modules/testgen/targets/bmv2/proto/p4testgen.proto#L24-L36

But when I use `p4testgen` with the `--print-traces` option (for a v1model/bmv2 P4 program), I only see traces printed out in terminal, but not recorded in the generated test cases.

I wonder if this is the expected behavior? And how can I capture traces in generated test cases?

**Comment by fruffy** [comment]
Traces have been disabled for proto text files because they may sometimes include characters that are illegal: 

https://github.com/p4lang/p4c/blob/main/backends/p4tools/modules/testgen/targets/bmv2/backend/protobuf/protobuf.cpp#L392

This is something we have not address yet.
