### ISSUE TITLE
const not allowed inside parser state definition

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#422]
The attached program demonstrates this with 2017-Mar-30 version of p4test and p4c-bm2-ss.

Both const and variable declarations are allowed in all of these places by current P4_16 compiler:
* top level
* inside parser directly (outside of parser state definition)
* inside control directly (outside of table or action definition)
* inside action
* inside control apply block
* inside inner blocks enclosed by braces in any of the above places that allow block statements (i.e., actions, control apply blocks)

The unusual one is that parser states allow variable declarations, but not const.  Not a hard restriction to live with, but seems fairly odd given the consistency in all of the other places above.
[const-error-in-state.p4.txt](https://github.com/p4lang/p4c/files/889042/const-error-in-state.p4.txt)

**Comment by mbudiu-vmw** [comment]
Actually variable declarations at the top-level should be illegal. If they are not, it's a bug.
At the toplevel you should only be allowed instances.

**Comment by mbudiu-vmw** [comment]
I could not reproduce the claim that variable declarations are allowed at the top-level. If you have a counter-example please share it.

Please note that we make a clear distinction between variables and instances. Variables live on the "stack", while instances are statically allocated. We allow instances at the top-level, but not variables.

**Comment by jafingerhut** [comment]
I was mistaken about variable declarations being allowed at the top-level.  Thanks for the correction.

**Comment by jafingerhut** [comment]
Github did not auto-close this on this commit: https://github.com/p4lang/p4c/commit/b85401c8d7d7dca447816e7633128efc2db949dc

I have tested with compiler and failing test case after that commit, and it is accepting const inside parser state definition now, so closing.
