### ISSUE TITLE
buffer usage measurement in PSA

### ISSUE THREAD

**Issue by subrnath** [p4lang/p4c#4242]
I am looking for buffer usage in PSA architecture. As per As per https://p4.org/p4-spec/docs/PSA.html,

A.2. Observation and control of congestion
The current PSA does not provide any mechanisms to observe if particular output ports or queues are leading to congestion in the packet buffer. Thus it is not possible without using mechanisms defined outside of PSA to implement a feature like Explicit Congestion Notification (ECN)[11](https://p4.org/p4-spec/docs/PSA.html#fn-ecn). One possibility here is to define a small field, perhaps only 1 bit, that is part of the metadata associated with each packet as it begins egress processing. This field would indicate “how much congestion” the packet experienced in the packet buffer.

Does it mean that there is no such equivalent queueing_metadata_t functionality as it's there in simple_switch?

**Comment by jafingerhut** [comment]
I would recommend asking such questions on the web forum at https://forum.p4.org, where others who know the answer may see, and answers will be searchable in the future for others looking for them.

**Comment by subrnath** [comment]
Thanks.
