### ISSUE TITLE
add unit test for p4runtime

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#426]
Once #425 is fixed, to avoid similar issues in the future.

**Comment by sethfowler** [comment]
Agreed, this would be a good idea. I recently added GTest in p4c and this was one of my primary use-cases for it.

**Comment by antoninbas** [comment]
Not sure what the best approach is for this, given that the serializer needs a refMap and a typeMap to run. What is the quickest way of generating these? Also, is it a robust testing solution, given that different backends may use different maps based on which passes they have run before running the serializer?

**Comment by sethfowler** [comment]
I think we can define the behavior of p4RuntimeSerializer without *too* much reliance on backend-specific code, though externs are a tricky case once we venture outside of v1model.

As far as generating a refMap and a typeMap goes, Han is experimenting with tests that only run a small subset of the passes in the GTests he's been writing today. Take a look at them and see if you can adapt his approach to fit your needs.

**Comment by sethfowler** [comment]
(This stuff is undergoing a lot of churn right now, so honestly you may be better off waiting until next week to do this.)

**Comment by antoninbas** [comment]
@sethfowler Is now a good time to start tacking this? I have been fixing some issues in p4RuntimeSerializer but now I am afraid of these issues (or new ones) creeping back in as I make more changes in the future?

**Comment by mbudiu-vmw** [comment]
I will mark this as fixed. We have some tests, I hope that they are good enough.
