### ISSUE TITLE
How to calculate memory consumption of an ipv4 entry in TCAM?

### ISSUE THREAD

**Issue by castilhorosa** [p4lang/p4c#4281]
Hi,

Firstly, I apologize if this is not the right place for this kind of question.

I've been struggling lately to understand how to calculate the memory consumption of TCAM entries in a programmable ASIC. For example, do I need to consider both mask bits and value bits to calculate the memory consumption of an ipv4 prefix using TCAM memory? In other words, if we simplify and consider an ipv4 prefix with its basic components (32 bits for the destination ip, 32 bits for the mask and 8 bits for the output port), is it correct to say that an ipv4 prefix like that requires 72 bits? If so, in a 50 MB TCAM, we can store approximately 5.5 million ipv4 prefixes (50 MB / 72 bits), right? I know there is some other information that needs to be included in the calculation such as the action data. But, in summary, I would like to know if the TCAM memory in a given ASIC (let's say a TCAM with size of 50 MB) includes the space necessary to store the masks, which, if I understand correctly, is an overhead.

Once again, I apologize if this is not the right place for this question.

Thanks.

**Comment by fruffy** [comment]
This seems like a question better suited for https://forum.p4.org/ or https://community.intel.com/t5/Intel-Connectivity-Research/cmp-p/grouphub:connectivity-research-program.

**Comment by castilhorosa** [comment]
Thanks @fruffy
