### ISSUE TITLE
p4c support installation on ubuntu arm64 or aarch64 ?

### ISSUE THREAD

**Issue by laofan13** [p4lang/p4c#4282]
source /etc/lsb-release
echo "deb http://download.opensuse.org/repositories/home:/p4lang/xUbuntu_${DISTRIB_RELEASE}/ /" | sudo tee /etc/apt/sources.list.d/home:p4lang.list
curl -fsSL https://download.opensuse.org/repositories/home:p4lang/xUbuntu_${DISTRIB_RELEASE}/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_p4lang.gpg > /dev/null
sudo apt-get update
sudo apt install p4lang-p4c

**Comment by fruffy** [comment]
I believe for these binaries we only support x86. @rst0git can you confirm?

**Comment by rst0git** [comment]
Yes, these packages currently support only x86.
@laofan13 If you are working with aarch64, you can try to install [P4Edge](https://github.com/P4EDGE/platform-wiki/wiki/) or [P4Pi](https://github.com/p4lang/p4pi).

**Comment by laofan13** [comment]
thanks
