### ISSUE TITLE
Errors in Fedora with install_fedora_deps.sh 

### ISSUE THREAD

**Issue by vamsiDT** [p4lang/p4c#4293]
Hi, I am trying to build from source on a Fedora system. I started with `./install_fedora_deps.sh` and encountered the following error. Any help would be much appreciated. Thanks!

```
In file included from cpp_out/p4/tmp/p4config.pb.cc:4:
cpp_out/p4/tmp/p4config.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
   12 | #error This file was generated by a newer version of protoc which is
      |  ^~~~~
In file included from cpp_out/google/rpc/code.pb.cc:4:
cpp_out/google/rpc/code.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
   12 | #error This file was generated by a newer version of protoc which is
      |  ^~~~~
cpp_out/p4/tmp/p4config.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
   13 | #error incompatible with your Protocol Buffer headers. Please update
      |  ^~~~~
cpp_out/p4/tmp/p4config.pb.h:14:2: error: #error your headers.
   14 | #error your headers.
      |  ^~~~~
cpp_out/google/rpc/code.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
   13 | #error incompatible with your Protocol Buffer headers. Please update
      |  ^~~~~
cpp_out/google/rpc/code.pb.h:14:2: error: #error your headers.
   14 | #error your headers.
```

**Comment by rst0git** [comment]
@vamsiDT What version of Fedora are you using and what is your version of `protoc`?

**Comment by vamsiDT** [comment]
Hi @rst0git, I am on Fedora 39 and `protoc --version` outputs `libprotoc 3.20.3`.

**Comment by rst0git** [comment]
The CI tests are also running on Fedora 39 but it is using protobuf v3.19 installed from a package (`protobuf-3.19.6-6.fc39.x86_64 `). If protobuf  v3.20 has been previously installed on your system from source, it might be the case that you now have two different versions of protobuf and this is causing the error. What is the output of `which protoc`?

**Comment by vamsiDT** [comment]
Thanks a lot. It works now. The issue was multiple installed versions of protoc.
