### ISSUE TITLE
[P4Testgen] Coverage ignores empty actions

### ISSUE THREAD

**Issue by vlstill** [p4lang/p4c#4305]
This is probably an unforeseen artifact of the way testgen counts coverage. If there is an empty action, there are no IR nodes it in and therefore (presumably) it does not add to coverage metric. This means that in certain invocations (e.g. `--path-selection GREEDY_STATEMENT_SEARCH --track-coverage STATEMENTS --track-coverage TABLE_ENTRIES --only-covering-tests --stop-metric MAX_NODE_COVERAGE`), the execution that leads to empty action is ignored.

For example, with this code snippet only `a0` and `a3` were hit using these options (and I suspect `a0` was only hit because it was first).
```p4
    action t0_a0() { NoAction(); }
    action t0_a1() { }
    action t0_a2() { ; }
    action t0_a3() { hdr.h0.v0 = 42; }

    table t0 {
        key = {
            hdr.h0.v0 : exact;
            hdr.h0.v1 : exact;
        }
        actions = {
            t0_a0;
            t0_a1;
            t0_a2;
            t0_a3;
        }
        default_action = t0_a0;
        size = 32;
    }

    apply{
        if (hdr.h0.isValid())
            t0.apply();
    }
```

What would be a good solution here? One thing I can think about is adding an empty statement to each empty action in the testgen's midend. Then the tracking could be left as is and the cost would be presumably negligible. I think this could be used in all cases (both for `STATEMENTS` and for `TABLE_ENTRIES` coverage). @fruffy, what do you think?

**Comment by fruffy** [comment]
This is working as intended as there are no new statements or table entries covered with these actions. I would augment `CoverableNodesScanner` and `CollectNodes` with coverage of P4 actions.

**Comment by fruffy** [comment]
We can rephrase `TABLE_ENTRIES` to `CONST_TABLE_ENTRIES` to make it less ambiguous.

**Comment by vlstill** [comment]
OK, I'll try to add a new `ACTIONS` coverage.

**Comment by jnfoster** [comment]
Thumbs up. An action-specific notion of coverage would be a great addition.
