### ISSUE TITLE
How to use p4lang to implement division operation in compile-time unknown value ？

### ISSUE THREAD

**Issue by laofan13** [p4lang/p4c#4311]
in [/P4-16-v1.2.4.](https://staging.p4.org/p4-spec/docs/P4-16-v1.2.4.html?_ga=2.139645619.1411786894.1703573820-1641011827.1703573819&_gl=1*158mjsc*_ga*MTY0MTAxMTgyNy4xNzAzNTczODE5*_ga_FW0Q4274RH*MTcwMzU3MzgxOS4xLjEuMTcwMzU3MzgyNS4wLjAuMA..*_ga_VXXZD2250K*MTcwMzU3MzgxOS4xLjEuMTcwMzU3MzgyNS4wLjAuMA..#sec-int-ops). 

The type int denotes arbitrary-precision integers. In P4, all expressions of type int must be compile-time known values. The type int supports the following operations:

Hi, can support compile-time unknown values ?

**Comment by jafingerhut** [comment]
Some particular P4 implementations might have externs that implement such operations.  To find out, you must consult the particular implementation's documentation, or ask the vendor, e.g. https://github.com/barefootnetworks/Open-Tofino/blob/master/share/p4c/p4include/tofino1_base.p4#L653-L673

There is nothing in the P4 language specification that mandates that an implementation must provide such operations, though, and some do not.

Reading this article, and/or looking for the book "Hacker's Delight" mentioned in the article and looking through its table of contents, may give you ideas for how to work around this limitation, using the operations provided to implement the operations that you want to use: https://github.com/jafingerhut/p4-guide/blob/master/docs/floating-point-operations.md

**Comment by laofan13** [comment]
thanks @jafingerhut
