### ISSUE TITLE
Protobuf build errors with v1.2.4.7

### ISSUE THREAD

**Issue by jkhsjdhjs** [p4lang/p4c#4316]
Hey,

v1.2.4.7 fails to build for me because of the changes to the Protobuf cmake file: https://github.com/p4lang/p4c/commit/aaa5c7d547e968f0bd90e96d7eac6304e1e348bf
The problem is that the variables `Protobuf_LIBRARY`, `Protobuf_PROTOC_EXECUTABLE`, `PROTOC_BINARY` and `Protobuf_INCLUDE_DIR` are not defined when linking against system protobuf. I was able to resolve this by applying the following patch:
```patch
diff --git a/cmake/Protobuf.cmake b/cmake/Protobuf.cmake
index f1feeb00e..f0891c50e 100644
--- a/cmake/Protobuf.cmake
+++ b/cmake/Protobuf.cmake
@@ -15,15 +15,13 @@ macro(p4c_obtain_protobuf)
     if(NOT Protobuf_FOUND)
       find_package(Protobuf REQUIRED)
     endif()
-    # Protobuf sets the protoc binary to a generator expression, which are problematic.
-    # They are problematic because they are only evaluated at build time.
-    # However, we may have scripts that depend on the actual build time during the configure phase.
-    # Hard code a custom binary instead.
-    find_program(PROTOC_BINARY protoc)
 
     if(ENABLE_PROTOBUF_STATIC)
       set(CMAKE_FIND_LIBRARY_SUFFIXES ${SAVED_CMAKE_FIND_LIBRARY_SUFFIXES})
     endif()
+    set(Protobuf_LIBRARY "protobuf::libprotobuf")
+    set(Protobuf_PROTOC_EXECUTABLE "protobuf::protoc")
+    set(PROTOC_BINARY "protobuf::protoc")
   else()
     # Google introduced another breaking change with protobuf 22.x by adding abseil as a new
     # dependency. https://protobuf.dev/news/2022-08-03/#abseil-dep We do not want abseil, so we stay
diff --git a/control-plane/CMakeLists.txt b/control-plane/CMakeLists.txt
index 1e59f9a56..4d1b504b9 100644
--- a/control-plane/CMakeLists.txt
+++ b/control-plane/CMakeLists.txt
@@ -52,7 +52,7 @@ add_custom_target (mkP4configdir
   ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/p4/config)
 add_custom_command(OUTPUT ${P4RUNTIME_GEN_SRCS} ${P4RUNTIME_GEN_HDRS}
   COMMAND ${Protobuf_PROTOC_EXECUTABLE}
-          -I${P4RUNTIME_STD_DIR} -I${CMAKE_CURRENT_SOURCE_DIR} -I${Protobuf_INCLUDE_DIR}
+          -I${P4RUNTIME_STD_DIR} -I${CMAKE_CURRENT_SOURCE_DIR}
           --cpp_out ${CMAKE_CURRENT_BINARY_DIR}
           --python_out ${CMAKE_CURRENT_BINARY_DIR}
           --experimental_allow_proto3_optional
```

**Comment by jkhsjdhjs** [comment]
Yep, this is on a fresh build. The variables are probably not set because CMake FindProtobuf isn't used here, since it isn't compatible with the latest protobuf releases. That's why this was changed to `find_package(Protobuf CONFIG)` in https://github.com/p4lang/p4c/pull/4104, which uses protobufs own cmake files.

Anyway, I found an issue for our problem: https://github.com/protocolbuffers/protobuf/issues/4806 
Protobufs own CMake files don't seem to define these variables by default as they are legacy. They offer a legacy mode via `set(protobuf_MODULE_COMPATIBLE TRUE)` prior to calling `find_package()`. I tested it and it indeed defines some of these variables. However, `Protobuf_INCLUDE_DIR` remains undefined, changing it to `Protobuf_INCLUDE_DIRS` (plural) makes it work: https://github.com/p4lang/p4c/blob/8cc98afc5116730f8b8c90e6ed4a482874c6efee/control-plane/CMakeLists.txt#L55
However, I guess this can be problematic if `Protobuf_INCLUDE_DIRS` contains multiple directories, because there's only a single `-I` option?

Furthermore, `Protobuf_LIBRARY` is just to `/usr/lib/libprotobuf.so.25.1.0`, which causes errors because it only links against protobuf, not abseil.
So in either case, `Protobuf_LIBRARY` must be manually set to `protobuf::libprotobuf`, or `protobuf::libprotobuf` should be used instead of `Protobuf_LIBRARY` in the first place.

**Comment by jkhsjdhjs** [comment]
> Isn't `FindProtobuf` equivalent to `find_package` here?

I don't think so. `FindProtobuf` is CMakes internal function for finding protobuf and setting all the variables. When `CONFIG` is used, the internal function is skipped and the external protobuf cmake files are used for the configuration. That's how I currently understand it.

> Is the patch you linked still up-to-date?

It is, but we may also use `protobuf_MODULE_COMPATIBLE` instead to set fewer variables manually.

> For the control-plane CMake, the include is required.

It doesn't seem to be, it built fine without it.

**Comment by fruffy** [comment]
> It is, but we may also use `protobuf_MODULE_COMPATIBLE` instead to set fewer variables manually.

Seems like a good idea, could you make a PR for this? 

> > For the control-plane CMake, the include is required.
> 
> It doesn't seem to be, it built fine without it.

This might just work because protoc uses the system paths by defaullt, but if we do not use system Protobuf these includes are missing. We can try it in a PR.
