### ISSUE TITLE
Check the required version of bmv2

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#438]
configure should somehow check that a recent enough version of BMv2 is installed; otherwise tests that depend on recent features can fail.

**Comment by mbudiu-vmw** [comment]
I believe this is now done using the version field in the json output by the compiler.

**Comment by antoninbas** [comment]
A quick note: the check is done when the JSON file is loaded by bmv2, so it is a runtime check, it's not done by configure. That being said, if someone knows where to look, the logs should show an informational error message in case of version mismatch.

**Comment by mbudiu-vmw** [comment]
Even a runtime check is better than no check; if bmv2 fails on a version mismatch we can catch this quickly. If it doesn't perhaps we can add a flag so it does.

**Comment by antoninbas** [comment]
Yes it will fail if the advertised version in the JSON (added by p4c) is greater than the maximum known version. All changes to the JSON have been backwards-compatible so far, so there is no error when the advertised version is smaller than the maximum known version.
