### ISSUE TITLE
`P4TEST_REPLACE` does not replace expected contents of `p4tc` test outputs

### ISSUE THREAD

**Issue by kfcripps** [p4lang/p4c#4384]
For example, running `P4TEST_REPLACE=1 make check` doesn't replace the expected `p4tc` outputs with the actual outputs for failing `p4tc` tests, like it does for all of the other tests. It looks like some logic might be missing in [run-tc-test.py](https://github.com/p4lang/p4c/blob/main/backends/tc/run-tc-test.py) to support this.

**Comment by fruffy** [comment]
@komaljai @Sosutha

**Comment by kfcripps** [comment]
@usha1830 Let me know if you plan to fix this soon. I will either wait for this to be fixed, or manually fix the `p4tc` tests that are failing in https://github.com/p4lang/p4c/pull/4354, depending on how soon the fix for this will be available.

**Comment by usha1830** [comment]
> @usha1830 Let me know if you plan to fix this soon. I will either wait for this to be fixed, or manually fix the `p4tc` tests that are failing in #4354, depending on how soon the fix for this will be available.

@kfcripps I see that this is fixed in a commit in an existing PR #4327 which is under review.

**Comment by kfcripps** [comment]
Fixed by https://github.com/p4lang/p4c/pull/4395
