### ISSUE TITLE
Update the hash functions used in `hash.cpp` and `cstring.cpp`

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#4392]
`lib/hash.cpp` has been contributed several years back to support string hashes in the compiler's `cstring` implementation. However, the hash function has flaws. We should consider replacing it with more robust hashes such as `xxhash3` if we decide to making hash functions part of the public compiler library. 

Context from https://github.com/p4lang/p4c/pull/4377#discussion_r1477781295

>  `lib/hash.cpp` implements fnv1a and (old) murmur2. murmur2 is used in `cstring` (for unification, as string hash) and fnv1 is used to hash cstring' contents insider parser unroll. Both cases do not make much sense to me:
> 
> 1. murmur2 is old, slow and known to have flaws
> 2. fnv1a is quite slow, has mediocre quality. And actually its usage in parser unroll is questionable: since cstrings are guaranteed unique, then the address of string is enough as 64-bit hash
> 
> In my opinion:
>  - murmur2 should be replaced with something a bit more modern and performant. I'd stick with xxhash3.
>  - fnv1a usage from parser unroll should be removed
> 
> The only reason why fnv1a was chosen here is that it's small enough to be evaluated in constexpr context without slowing down compilation time. And for this its quality is good enough here: note that we are hashing few dozen of strings that are known during compile time, so our collision requirements are much lower than generic purpose string hash.
> 
> PS: Certainly, hash refactoring is a separate task :)
> PPS: Frankly speaking, just the address of string buffer is quite poor `hash<cstring>` for hash map implementation collision-wise. However, I believe we can easily make it much stronger just passing it through xxh3.

**Comment by vlstill** [comment]
@asl, could you please expand on the following?

> PPS: Frankly speaking, just the address of string buffer is quite poor hash<cstring> for hash map implementation collision-wise. However, I believe we can easily make it much stronger just passing it through xxh3.

**Comment by asl** [comment]
> @asl, could you please expand on the following?
> 
> > PPS: Frankly speaking, just the address of string buffer is quite poor hash for hash map implementation collision-wise. However, I believe we can easily make it much stronger just passing it through xxh3.

Oh, yes, sure. The sole reason is that the pointers themselves have quite poor entropy:
 - Low 3 bits are always zero, so the schemes like `bucket_id = std::hash<Object>(obj) % bucket_count` suffer especially in common case when # of buckets is power of two (and therefore `%` is just and with mask)
 - Upper ~16 bits are zero as well in many cases
 - Objects are usually derived from common "pool", therefore the entropy of other bits also tends to be low

Depending on the particular hash table implementation and use it may or may not matter much (iirc libstdc++ uses prime numbers as bucket counts), and lookup might suffer more than insert (as we'll end just random access of list of value pairs). Non hash-table usages that rely on the hash quality more (think about e.g. a bloom filter) might be impacted much more (certainly I'm speaking in general, not a particular bloom filer of `cstring`) :)

**Comment by asl** [comment]
I can take this task for myself, if noone would object :)

**Comment by fruffy** [comment]
> I can take this task for myself, if noone would object :)

Gladly!
