### ISSUE TITLE
Check unsupported versions of compilers

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#441]
Some code idioms in the p4c compiler trigger bugs in gcc or other tools.
`./configure` should check for these unsupported versions.

**Comment by sethfowler** [comment]
Fair enough. =)

**Comment by jafingerhut** [comment]
So after this commit, is Ubuntu 14.04 still supported?  At least the default g++ package version on Ubuntu 14.04 is 4.8, and with this change it fails saying it requires 4.9.  Is clang recommended for Ubuntu 14.04?  Or is it recommended to move to Ubuntu 16.04?  Something else?

**Comment by jafingerhut** [comment]
I was able to install the default version of clang available for Ubuntu 14.04, which is clang 3.4, and compiled p4c successfully after that.  If this is the plan, it might be good to update the README for p4c to mention installing the clang package before building.  I can open a PR for that if desired.

**Comment by ChrisDodd** [comment]
It requires either gcc 4.9 or clang 3.3 as the configure check says.  Either can be installed on Ubuntu 14.04 through the normal channels though neither is installed by default.

**Comment by sethfowler** [comment]
Yep. We are only running tests on Ubuntu 16.04 at this point, so that’s the officially supported OS, in that you cannot check in code that breaks with that configuration. However, unofficially, Ubuntu 14.04 will likely continue to work (with an updated compiler) for the foreseeable future.
