### ISSUE TITLE
Get rid of `dynamic_cast` in filtering enumerator

### ISSUE THREAD

**Issue by asl** [p4lang/p4c#4478]
Or one could provide different implementation in p4testgen. Here is the relevant profile:

<img width="1038" alt="Screenshot 2024-02-27 at 13 47 54" src="https://github.com/p4lang/p4c/assets/67392/22eb4a24-b64c-49f2-aae6-6c3e8e246d24">

~20% total is just `dynamic_cast`:

<img width="1037" alt="Screenshot 2024-02-27 at 13 49 29" src="https://github.com/p4lang/p4c/assets/67392/5eec9172-9af4-4113-8995-3ce7c5f011d8">

Tagging @fruffy

**Comment by asl** [comment]
@fruffy I do not see visitors in the profile frankly speaking :) But maybe they are just hidden behind or we already handled them

**Comment by fruffy** [comment]
Interesting, thanks for profiling. I am surprised the visitors do not show up. We use a `Transform` visitor to convert symbolic variables to constants on every generated test and we use Inspectors for traversal. I guess there are other parts that are still much slower. 

That piece you singled out might be difficult to completely remove but we should not spend this much time looking up types that never change either.

**Comment by asl** [comment]
> That piece you singled out might be difficult to completely remove but we should not spend this much time looking up types that never change either.

Well, the problem here is:
```c++
Util::Enumerator<const IDeclaration *> *P4Program::getDeclarations() const {
    return objects.getEnumerator()->as<const IDeclaration *>()->where(
        [](const IDeclaration *d) { return d != nullptr; });
}
```

Here there are all kinds of issues. Including `where`, `as`, and lots of allocations.

**Comment by asl** [comment]
So, removing `dynamic_cast` overhead here drops the runtime from 31 seconds down to 25 seconds

**Comment by asl** [comment]
@fruffy Lots of malloc traffic is due to `P4Testgen:ExecutionState` copy / clones.

**Comment by fruffy** [comment]
> So, removing `dynamic_cast` overhead here drops the runtime from 31 seconds down to 25 seconds

Great! 

>@fruffy Lots of malloc traffic is due to P4Testgen:ExecutionState copy / clones.

Yeah... hermetic execution state is a necessity for the test-case generator to work correctly, but there are many places where cloning is unnecessary. This problem is exacerbated by the fact that there are a lot of members in that class. There also more parts of the interpreter which are inefficient, e.g., the stack frame execution in the symbolic executor, which is barely used at all. 

Performance has not been the highest priority for that tool but it is definitely important to keep track of.

**Comment by asl** [comment]
> Performance has not been the highest priority for that tool but it is definitely important to keep track of.

Well, yes, certainly 100% correctness is required. But the coverage depends on # of random tests generated. So, performance is important. After all the more tests one could generate in, say, 1 day, the better :)

**Comment by fruffy** [comment]
> Well, yes, certainly 100% correctness is required. But the coverage depends on # of random tests generated. So, performance is important. After all the more tests one could generate in, say, 1 day, the better :)

Agree, we really need traversal performance for our heuristics which generate very specific tests. It can take a long time to find test pairs that fit user-specified criteria.

**Comment by asl** [comment]
`dynamic_cast` part (plus other overheads) are fixed in https://github.com/p4lang/p4c/pull/4513

**Comment by asl** [comment]
Note that `FilterEnumerator` above is misleading. It wrapped `AsEnumerator` that did `dynamic_cast`.

**Comment by fruffy** [comment]
I believe this is now fixed, right?

**Comment by asl** [comment]
Yea, fixed by https://github.com/p4lang/p4c/pull/4513
