### ISSUE TITLE
Query: How to get started with Contributions

### ISSUE THREAD

**Issue by Thrillseekr** [p4lang/p4c#4479]
Hello, 
@fruffy @vlstill @asl @qobilidop 
I'm Darshan Jain.

**I know, this is not the right place to ask questions but couldn't found any other way to get introduced to community and getting help to find a way to start contibuting.**

I've read the Readme.md file of P4 compiler and found this project interesting to be work on a compiler. Also my skills are aligned with the techstack of this project.

My skills includes:
C/C++, Object Oriented Programming Techniques(OOPs), Data Structures and Algorithms, Standard Template Library, HTML, CSS, Docker, Git, GitLab, GitHub.

I also have a little Open Source Experience. So considering me as a fresher could you please help me in directing and letting me know what's the first step and where should I contribute.
Also, it would be great if I get a chance to work on **P4 formatter**.

Thanks
Darshan Jain

**Comment by qobilidop** [comment]
Hi @Thrillseekr,

We are working on setting up a GSoC specific repo under https://github.com/p4lang. When that becomes public, all the GSoC specific discussions can happen there. It's preferable that we leave p4c's issues section with actual p4c issues and questions.

In the meantime, you are encouraged to post general P4 related questions in the [P4 forum](https://forum.p4.org/).

To directly answer your original question, we think the best way to get started is to go over our Contributor Guidance through our [GSoC org profile](https://summerofcode.withgoogle.com/programs/2024/organizations/the-p4-language-consortium), and start drafting your project proposal. When running into more specific questions, you are encouraged to reach out to the various community communication channels also covered in the Contributor Guidance.

Hope these helps!

**Comment by Thrillseekr** [comment]
Sure sir,
I Appologise

I'll close the issue.
Thanks

**Comment by qobilidop** [comment]
No need to apologize. This is a public discussion space anyway. It's normal to try things out. We'll guide you along the way.
