### ISSUE TITLE
Protobuf & Abseil compilation pollutes build with a lot of warnings

### ISSUE THREAD

**Issue by vlstill** [p4lang/p4c#4523]
Compiling with `FetchContent` Abseil and Protobuf, there is *a lot* of warnings. In parallel build they are also interleaved with proper p4c/extensions build which makes readability even worse.

* We should supress warnings in the builds of dependencies, they are not relevant.
* We should make sure the abseil/protobuf include search paths are included as `-isystem` -- some of the warnings are coming from abseil headers included into our code.

**Comment by fruffy** [comment]
I have been trying to make Abseil a system include here: https://github.com/p4lang/p4c/pull/4511

The problem is the overly opinionated Bazel version. We may have to patch the Abseil Bazel dependency to get things to work.
