### ISSUE TITLE
The formatters P4C CI uses are out of sync with the descriptions in the README.

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#4537]
Make sure that the installation instructions we list in the README match to what we actually use in our CI.

**Comment by b-harsh** [comment]
I am working on this issue

**Comment by b-harsh** [comment]
@fruffy I have a question where should I make the version changes in the requirements.txt file or README

**Comment by fruffy** [comment]
README, the problem is that the README is often slightly mismatched or out of date.

**Comment by b-harsh** [comment]
https://github.com/p4lang/p4c/pull/4538

@fruffy here is my PR
