### ISSUE TITLE
Choosing a consistent commenting style for core parts of the compiler.

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#4563]
This is a question that came up in #4554. 

We do not have a consistent comment style for P4C, at least for the core parts of the compiler. This makes it difficult for someone like @thrilseekr to actually add comments to the code and use doxygen.

I personally suggest using triple slashes for functions/classes and double slashes for comments within code.

Any other suggestions or objections? Back ends may do as they please, of course. 

@vlstill @ChrisDodd @asl @jnfoster @qobilidop @Dscano

**Comment by thrilseekr** [comment]
Hey, thanks for raising this issue.
I've a suggestion.

You can make a decision by going through the official doc of Doxygen
https://www.doxygen.nl/manual/docblocks.html

**Comment by vlstill** [comment]
> I personally suggest using triple slashes for functions/classes and double slashes for comments within code.

I am OK with that. I could imagine some cases when the comment on a function/class does not belong to Doxygen (e.g. commenting on why some template is spelled exactly the given way), but I guess if that arises we could always move the non-doxygen comment to the first line of the function body.

So would this mean basically removing / forbidding `/* ... */` style comments? There are some rare occasions when these are the only way around, e.g. when you want to add a comment into a multi-line macro, it has to be `/* ... */`. So I don't think these should be prohibited absolutely.

**Comment by fruffy** [comment]
>So would this mean basically removing / forbidding /* ... */ style comments? 

No, we do not have to be that rigid. I can imagine this being useful for very long comments, too. This is more to agree on common style at least.

**Comment by fruffy** [comment]
This is now fixed and implemented in https://github.com/p4lang/p4c/tree/main/docs#documentation-comments-style-guide. 
Thanks @sumit and @AdarshRawat1.
