### ISSUE TITLE
Acronym capitalization: P4C vs p4c

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#4585]
This is a pedantic question but since we are updating our documentation I figured it could be good to finally make a decision here. Should the canonical acronym for the P4 compiler be `P4C` or `p4c`?

I have been consistently using P4C, similar to the Gnu Compiler Collection (GCC). But in some of our docs and the main README we are using p4c (like icc). Anyone has some opinions on this?

**Comment by AdarshRawat1** [comment]
> Desclaimer : I don't know if I'm eligible to comment on this 😅
 
According to me `P4C` looks more consistent & suitable for a compiler name.

**Comment by fruffy** [comment]
> > Desclaimer : I don't know if I'm eligible to comment on this 😅
> 
> According to me `P4C` looks more consistent & suitable for a compiler name.

I will let this simmer until Friday, if there is no object we can go with P4C.

**Comment by kfcripps** [comment]
Not a strong preference but I like `p4c` because it requires 40% fewer keystrokes.

**Comment by qobilidop** [comment]
I don't have a strong preference, but agree having consistency in this naming could be beneficial! The GCC comparison makes sense to me, so now I'm slightly leaning towards that option.

**Comment by fruffy** [comment]
Okay, let's go with P4C then. At least for documents. The lowercase binary will stay the same.

**Comment by AdarshRawat1** [comment]
> Okay, let's go with P4C then. At least for documents. 

I'll submit a PR addressing this soon. 🚀
