### ISSUE TITLE
issues while trying to install nikss-cli for the psa-ebpf backend

### ISSUE THREAD

**Issue by Arishbiswas** [p4lang/p4c#4631]
hello, i am facing issues while trying to install nikss from source , i tried in both ubuntu 20.0 as well as ubuntu 22.0 , in the former one couldnot run the build.sh script it throws error but in ubuntu 22.0 i could run the build.sh but while i try to run the make file it generates lots of errors, as i am new , it would be a great help if anyone would let me know how to solve this issue.

This is the error messages that i got while trying to run the "make -j4" :
arishmita@arishmita-VirtualBox:~/nikss/build$ make -j4

make[1]: Entering directory '/home/arishmita/nikss/build'

make[2]: Entering directory '/home/arishmita/nikss/build'

make[2]: Leaving directory '/home/arishmita/nikss/build'

make[2]: Entering directory '/home/arishmita/nikss/build'

[ 3%] Building C object CMakeFiles/nikss-ctl.dir/lib/btf.c.o

[ 7%] Building C object CMakeFiles/nikss-ctl.dir/lib/nikss_pre.c.o

[ 10%] Building C object CMakeFiles/nikss-ctl.dir/lib/common.c.o

[ 14%] Building C object CMakeFiles/nikss-ctl.dir/lib/nikss_digest.c.o

In file included from /home/arishmita/nikss/install/usr/include/bpf/bpf.h:26,

             from /home/arishmita/nikss/lib/nikss_pre.c:18:
/home/arishmita/nikss/install/usr/include/linux/bpf.h:1281:17: error: unknown type name ‘__aligned_u64’

1281 | __aligned_u64 key;

  |                 ^~~~~~~~~~~~~
/home/arishmita/nikss/install/usr/include/linux/bpf.h:1283:25: error: unknown type name ‘__aligned_u64’

1283 | __aligned_u64 value;

  |                         ^~~~~~~~~~~~~
/home/arishmita/nikss/install/usr/include/linux/bpf.h:1284:25: error: unknown type name ‘__aligned_u64’

1284 | __aligned_u64 next_key;

  |                         ^~~~~~~~~~~~~
/home/arishmita/nikss/install/usr/include/linux/bpf.h:1290:17: error: unknown type name ‘__aligned_u64’

1290 | __aligned_u64 in_batch; /* start batch,

  |                 ^~~~~~~~~~~~~
/home/arishmita/nikss/install/usr/include/linux/bpf.h:1293:17: error: unknown type name ‘__aligned_u64’

1293 | __aligned_u64 out_batch; /* output: next start batch */

  |                 ^~~~~~~~~~~~~
/home/arishmita/nikss/install/usr/include/linux/bpf.h:1294:17: error: unknown type name ‘__aligned_u64’

1294 | __aligned_u64 keys;

  |                 ^~~~~~~~~~~~~
In file included from /home/arishmita/nikss/install/usr/include/bpf/bpf.h:26,

             from /home/arishmita/nikss/lib/nikss_digest.c:18:
/home/arishmita/nikss/install/usr/include/linux/bpf.h:1281:17: error: unknown type name ‘__aligned_u64’

1281 | __aligned_u64 key;

  |                 ^~~~~~~~~~~~~
/home/arishmita/nikss/install/usr/include/linux/bpf.h:1295:17: error: unknown type name ‘__aligned_u64’

1295 | __aligned_u64 values;

  |                 ^~~~~~~~~~~~~
/home/arishmita/nikss/install/usr/include/linux/bpf.h:1283:25: error: unknown type name ‘__aligned_u64’

1283 | __aligned_u64 value;

  |                         ^~~~~~~~~~~~~

  |         ^~~~~~~~~~~~~
/home/arishmita/nikss/install/usr/include/linux/bpf.h:5411:25: error: unknown type name ‘__be32’

*thanks in advance *

**Comment by jafingerhut** [comment]
It looks like you might have already filed an issue here for this: https://github.com/NIKSS-vSwitch/nikss/issues/109

I do not see any errors above that look like they are because of problems with p4c, so I'm not sure the readers of this issue are likely to be able to help you.

**Comment by fruffy** [comment]
@tatry @osinstom

**Comment by fruffy** [comment]
Closing in favor of https://github.com/NIKSS-vSwitch/nikss/issues/109.
