### ISSUE TITLE
include of file mm_malloc.h breaks build for Ubuntu aarch64 systems

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#4639]
This commit on 2024-Apr-18: https://github.com/p4lang/p4c/commit/c7d688a4ab857c684c06c5b6f6aaa5c698765360

added these lines to file `lib/gc.cpp`:

```
// Some systems (e.g. those with GNU libc) declare posix_memalign with an
// exception specifier. Compilers (clang including) might have special handling
// of this to allow posix_memalign redeclaration with / without exception
// specifier. As we define posix_memalign below in this file we really need to
// ensure the proper include order to workaround this weirdness.
#include <mm_malloc.h>  // NOLINT(build/include_order)
```

This file exists in Ubuntu package libgcc-11-dev on Ubuntu 22.04 for amd64 arch processors, but there is no such file for aarch64 processors on Ubuntu 22.04.

It would be nice if p4c could compile on recent Ubuntu versions for aarch64 processor architecture, too.  It was building a month ago, before the commit linked above, but I haven't done exhaustive testing on every commit to see if there are any blocking issues to achieve that other than the commit above.

**Comment by fruffy** [comment]
Our testing matrix is slowly growing. Maybe we can add an aarch64 nightly test, too.

**Comment by fruffy** [comment]
Looks like arm64/aarch64 is not supported yet: https://github.com/actions/runner-images/issues/5631.

**Comment by jafingerhut** [comment]
I have tested that with the changes made with this PR: https://github.com/p4lang/p4c/pull/4647

now merged, that building p4c with GCC on aarch64 Ubuntu 20.04 works again.  Thanks!

**Comment by jafingerhut** [comment]
Closing this issue since it has been fixed now.
