### ISSUE TITLE
Question about Static Analyzer

### ISSUE THREAD

**Issue by Mohxen** [p4lang/p4c#4666]
Hello all,

Please let me know which passes work as static analyzer (or control flow graph analyzer) in P4C.

Thank you in advance.

**Comment by ChrisDodd** [comment]
Not clear what you mean.  Any pass in p4c that inherits from `Inspector` is an analysis pass -- it traverses the IR and analyzes it without modifying anything (other than whatever internal data it collects)

**Comment by ChrisDodd** [comment]
`ControlFlowVisitor` itself is a "mixin" base class (inherited as an additional base class in addition to Insoector/Modifier/Transform) that has helper functions to support visitors that want to do control flow analysis -- Things are set up such that when you run a ControlFlowVisitor subclass over the IR (which is in AST form, not CFG form), things are visited in control-flow order and `flow_clone`/`flow_merge` are called at each control flow splitting/joiing point.  The idea being that visitor can compute any useful semilattice type over the control flow graph this way (using the semilattice meet/join operation in flow_merge)
