### ISSUE TITLE
Fix invalid format strings

### ISSUE THREAD

**Issue by asl** [p4lang/p4c#4689]
I am currently playing with using `absl::StrFormat` for various format strings interpolation inside p4c (this is mostly around `SourceCodeBuilder` and not related to diagnostics). One of the notable good things is that it does compile-time checks of format strings.

It turns out there are quite a decent amount of legitimate cases and errors mostly around bpf / ebpf backend. E.g.:
```c++
    builder->appendFormat("if (%s->drop) ", istd->name.name, istd->name.name);
```

We need certainly fix this.

**Comment by fruffy** [comment]
I have ran into this before when playing around with [fmt](https://github.com/fmtlib/fmt). Fixing this is definitely an improvement.
