### ISSUE TITLE
Add support for simple arithmetic expressions in bitfield size

### ISSUE THREAD

**Issue by thantry** [p4lang/p4c#47]
P4 grammar today cannot parse initializations of the form:

bit<8+8> p;
or
bit<16*8> p;
These would be useful for declaring identifiers that are multiples of bytes or half-words (for instance).

**Comment by mbudiu-vmw** [comment]
We actually had a prototype for this at some point.
One important issue is the following: if we allow a full expression language for expressing widths, then the greater-than sign will make the grammar ambiguous: you don't know whether > is greater-than or the closing of the "template": `bit<a > b ? c : d>`. So the grammar for expressions will have to require parentheses: `bit<(8+8)>`. This is a usability concern. The alternative to restrict the expression language disallowing comparisons sounds like a bad idea.

**Comment by jafingerhut** [comment]
Requiring parentheses in that context sounds reasonable to avoid the grammar ambiguity.

I would expect the common case for this would be having #define symbols that are sums of other #define symbols, and it is common practice to put parens around such expression anyway, to avoid syntax problems with the context of the C preprocessor textual substitution.

I haven't checked, but is it a workaround to this limitation in P4-16 to have one const be initialized via an arithmetic expression of other values defined as const, and use the const name as the width?

**Comment by ChrisDodd** [comment]
We only need to require the parentheses for expressions involving a `>` token, though doing so does involve some (minor) rule duplication in the grammar.

**Comment by sethfowler** [comment]
I'm curious how C++ deals with that ambiguity. This program actually compiles and runs fine:

```c++
template <bool V> struct foo { int value = V ? 10 : 20; };

int main() { return foo<1 < 2>().value; }
```

**Comment by ChrisDodd** [comment]
That example is easy -- the tough case is `>`.

Generally, this is handled in a parser by some sort of backtracking scheme
-- either GLR, or PEG trial parsing.

**Comment by ChrisDodd** [comment]
You want a tricky case, consider:

    template <int V> struct foo {
        int value = V ? 10 : 20;
        foo(int a) : value(a) {}
        operator int() { return value; }
    };

    int main() {
        return foo<1>(2) > (3);
    }

**Comment by sethfowler** [comment]
Ah yes, that's a good point. C++'s grammar interprets `>` in that case as closing the template argument list. That's considerably less impressive.

(FWIW, I'm familiar with how to handle this technically; I was more curious about what behavior they specified, but wasn't able to quickly find the appropriate section in the C++ standard.)

**Comment by mbudiu-vmw** [comment]
I think that this issue can now be closed permanently.
