### ISSUE TITLE
Invalid include in p4fmt.cpp

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#4715]
`p4fmt.cpp` should not have a dependency on google test, as it is not test code

`p4fmt.cpp` includes `test/gtest/helpers.h`:
https://github.com/p4lang/p4c/blob/63595490f488963ce4c8074828c8314d5e03643c/backends/p4fmt/p4fmt.cpp#L12C11-L12C31

`test/gtest/helpers.h` includes `gtest/gtest.h`:
https://github.com/p4lang/p4c/blob/63595490f488963ce4c8074828c8314d5e03643c/test/gtest/helpers.h#L20C11-L20C24

This means that trying to build p4c with `-DENABLE_GTESTS=OFF` is currently not working:
```
#16 ERROR: process "/bin/sh -c cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_CXX_FLAGS:STRING=-O3 -DENABLE_GTESTS=OFF -DENABLE_EBPF=OFF -DENABLE_P4C_GRAPHS=OFF -DENABLE_UBPF=OFF -DENABLE_DPDK=OFF -DENABLE_TEST_TOOLS=OFF .. &&     make &&     make DESTDIR=/output install" did not complete successfully: exit code: 2
------
 > [p4c-build 11/12] RUN cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_CXX_FLAGS:STRING=-O3 -DENABLE_GTESTS=OFF -DENABLE_EBPF=OFF -DENABLE_P4C_GRAPHS=OFF -DENABLE_UBPF=OFF -DENABLE_DPDK=OFF -DENABLE_TEST_TOOLS=OFF .. &&     make &&     make DESTDIR=/output install:
3879.6 [100%] Built target p4test
3879.6 [100%] Building CXX object backends/p4fmt/CMakeFiles/p4fmt.dir/p4fmt.cpp.o
3880.2 In file included from /p4c/backends/p4fmt/p4fmt.cpp:12:
3880.2 /p4c/test/gtest/helpers.h:20:10: fatal error: gtest/gtest.h: No such file or directory
3880.2    20 | #include <gtest/gtest.h>
3880.2       |          ^~~~~~~~~~~~~~~
3880.2 compilation terminated.
3880.2 make[2]: *** [backends/p4fmt/CMakeFiles/p4fmt.dir/build.make:76: backends/p4fmt/CMakeFiles/p4fmt.dir/p4fmt.cpp.o] Error 1
3880.2 make[1]: *** [CMakeFiles/Makefile2:7500: backends/p4fmt/CMakeFiles/p4fmt.dir/all] Error 2
3880.2 make: *** [Makefile:166: all] Error 2
```

**Comment by fruffy** [comment]
@snapdgn Could you take a look at this?

**Comment by qobilidop** [comment]
Is building with `-DENABLE_GTESTS=OFF` considered in any current CI test? If not, should we consider adding it?

**Comment by fruffy** [comment]
> Is building with `-DENABLE_GTESTS=OFF` considered in any current CI test? If not, should we consider adding it?

We could add it to one of the builds that does not run tests.

**Comment by qobilidop** [comment]
It seems `ci-static-build-test.yml` might be a good place to add the variation: https://github.com/p4lang/p4c/blob/7124b4ee2e046dea1fa0513aed0d6d8923fafd6a/.github/workflows/ci-static-build-test.yml#L25-L36

I'll take a further look into this.

**Comment by fruffy** [comment]
> It seems `ci-static-build-test.yml` might be a good place to add the variation:
> 
> https://github.com/p4lang/p4c/blob/7124b4ee2e046dea1fa0513aed0d6d8923fafd6a/.github/workflows/ci-static-build-test.yml#L25-L36
> 
> I'll take a further look into this.

I would suggest the Ubuntu 20.04 non-unity build. It also does not run tests but runs on every build.
