### ISSUE TITLE
Front-end doesn't enforce constraint that `extract` only be used with header types

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#477]
The following program is accepted by `p4test` but fails with any non-trivial backend.
```
#include <v1model.p4>

header h_t {
  bit<8> f;
}

struct my_packet {
  h_t[10] h;
}

struct my_metadata {
}

parser MyParser(packet_in b, out my_packet p, inout my_metadata m, inout standard_metadata_t s) {
  state start {
   transition dead;
  }
  state dead {
    b.extract(p.h);
    transition accept;
  }

}

control MyVerifyChecksum(in my_packet hdr, inout my_metadata meta) {
  apply { }
}

control MyIngress(inout my_packet p, inout my_metadata m, inout standard_metadata_t s) {
  apply { }
}

control MyEgress(inout my_packet p, inout my_metadata m, inout standard_metadata_t s) {
  apply { }
}

control MyComputeChecksum(inout my_packet p, inout my_metadata m) {
  apply { }
}

control MyDeparser(packet_out b, in my_packet p) {
  apply { }
}

V1Switch(MyParser(), MyVerifyChecksum(), MyIngress(), MyEgress(), MyComputeChecksum(), MyDeparser()) main;
```
The issue is that `extract` is used with a header stack rather than a header. 

Worse, if the start state merely transitions to `accept`, making `dead` a dead state, then some backends do not have an error, which is surprising for programmers.

I believe this should really be enforced during typechecking. However, the typechecker assumes that `extract` has an (overly) polymorphic type:
>  // T must be a fixed-size header type
>  void extract<T>(out T hdr);

**Comment by mbudiu-vmw** [comment]
If we had type constraints it would be indeed checked during typechecking.
For now I will write a separate little pass - the typechecking pass is complicated enough.

**Comment by mbudiu-vmw** [comment]
Adding a check for these problems causes several P4-14 programs with varbit fields to fail, because the translation to P4-16 is incorrect. The fundamental problem is that the translation of the varbit field length to p4-16 is incorrect.

This won't be very easy to fix. I may have to convert these to XFAIL and file a new issue.

I don't think we have any STF tests for varbit fields either; we probably would have caught these sooner.

**Comment by mbudiu-vmw** [comment]
@hanw: Fixing this also causes several gtestp4c tests to fail.
