### ISSUE TITLE
"Compiler Bug: out_1.p4(118): year;: expected a method call"

### ISSUE THREAD

**Issue by zzmic** [p4lang/p4c#4796]
Hi, 

I've encountered the following issue/bug when executing `p4test out_1.p4` at least after the latest commit `f24aacc` (I'm not claiming that the commit is directly affiliated with this bug).

```
Compiler Bug: out_1.p4(118): year;: expected a method call
    action revie(out priceX year, bit<128> orde, bit<128> priv) {
                            ^^^^
```
It seems to indicate a syntax issue where the `year` identifier is not recognized as a valid method call, which indeed may not be a method. Accordingly, the `priceX year` parameter is incorrectly parsed. 

I've renamed the file `out_1.p4` to `erroneous_year_as_method.p4.txt` for better naming illustration and attached it to this GitHub issue.

Thanks!

[erroneous_year_as_method.p4.txt](https://github.com/user-attachments/files/16189639/erroneous_year_as_method.p4.txt)

_Edit:_ 
I've attempted to reduce `erroneous_year_as_method.p4.txt` to the bare minimum state (w/ fewer lines of code) such that `p4test minimal_erroneous_year_as_method.p4` will replicate the same compiler bug. 

[minimal_erroneous_year_as_method.p4.txt](https://github.com/user-attachments/files/16197163/minimal_erroneous_year_as_method.p4.txt)

```
Compiler Bug: minimal_erroneous_year_as_method.p4(33): year;: expected a method call
    action revie(out priceX year, bit<128> orde, bit<128> priv) {
                            ^^^^
```

**Comment by asl** [comment]
I though that this is another `ResolutionContext` issue, but apparently I was wrong. After `RemoveActionParameters` we are having:

```p4
control MainControlImpl(inout Headers hdr, inout main_metadata_t user_meta, in pna_main_input_metadata_t istd, inout pna_main_output_metadata_t ostd) {
    @name("tmp_0") bool tmp_3;
    @name("tmp_1") bit<16> tmp_4;
    @noWarn("unused") @name(".NoAction") action NoAction_0() {
    }
    @name("year") priceX year;
    @name("revie") action revie_0(@name("orde") bit<128> orde, @name("priv") bit<128> priv) {
        hdr.heal[max((bit<3>)shouldr(), 3w3)] = year;
    }
    @name("greatY") table greatY {
        actions = {
            revie_0();
            @defaultonly NoAction_0();
        }
        default_action = NoAction_0();
    }
    apply {
        tmp_3 = greatY.apply().hit;
        if (tmp_3) {
            tmp_4 = 16w48951;
        } else {
            tmp_4 = 16w0;
        }
        hdr.eth_hdr.eth_type = tmp_4;
    }
}
```

Note that `revie_0` action. Now, `FunctionInliner` wants to inline `max` here. However, for `AssignmentStatement` it only knows how to handle rhs, it expects things of form `... = foo()` to inline `foo` here.

**Comment by asl** [comment]
Ok, I'm having a temporary fix that would not allow inlining in unsupported case. Will submit shortly.

**Comment by asl** [comment]
Temporary fix submitted in https://github.com/p4lang/p4c/pull/4800

**Comment by asl** [comment]
> so it may happen that wrong `call` will be passed to `inlineBefore` if we'd try to inline `bar()`

Answering to myself: this is certainly not an issue as we will see separate statements on RHS. The only problem is calls on LHS as there is only a single statement – the assignment itself.
