### ISSUE TITLE
Is it intentional that two of the three figures on P4 docs home page link to the same place?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#4802]
I am referring to the three figures at the bottom of the main pane here: https://p4lang.github.io/p4c/ as of 2024-Jul-13 when I examined it.

The bottom left figure is labeled "P4 Compiler Onboarding" and the middle one is labeled "Getting Started".  They currently both link to here: https://p4lang.github.io/p4c/md__2home_2runner_2work_2p4c_2p4c_2_r_e_a_d_m_e.html#autotoc_md51

If that is intentional, why not combine the two figures into one?

If it is unintentional, which one should be changed, and to what new link?

**Comment by AdarshRawat1** [comment]
Fixed in #4793, but the PR is a work in progress, so it is not merged yet.

**Comment by jafingerhut** [comment]
Closing this issue, as the links are correct after this PR was merged in: https://github.com/p4lang/p4c/pull/4793
