### ISSUE TITLE
Broken links in the generated P4 docs

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#4803]
I am referring to links appearing on this page as of 2024-Jul-13: https://p4lang.github.io/p4c/md__2home_2runner_2work_2p4c_2p4c_2docs_2_r_e_a_d_m_e.html

These links give a 404 in my browser:

+ "migration guide" link https://p4lang.github.io/p4c/migration-guide.pptx
+ "compiler design" link https://p4lang.github.io/p4c/compiler-design.pptx
+ "guidelines" link https://p4lang.github.io/p4c/CodingStandardPhilosophy.md#Git-commits-and-pull-requests
+ "guidelines" link https://p4lang.github.io/p4c/CodingStandardPhilosophy.md#Handling-errors

**Comment by AdarshRawat1** [comment]
Related discussion -  #4753

**Comment by AdarshRawat1** [comment]
> As of commit 6 of #4753, I have confirmed that the first 2 broken links are fixed, but the last 2 are still broken.

- commit 6 of PR #4793

**Comment by AdarshRawat1** [comment]
# Fixed Links  

| Section | Updated Links |
|--------|--------|
| migration guide | https://github.com/p4lang/p4c/blob/main/docs/migration-guide.pptx |
| compiler design | https://github.com/p4lang/p4c/blob/main/docs/compiler-design.pptx |
| guidelines | https://p4lang.github.io/p4c/md__2home_2runner_2work_2p4c_2p4c_2docs_2_coding_standard_philosophy.html#git-commits-and-pull-requests |
| guidelines | https://p4lang.github.io/p4c/md__2home_2runner_2work_2p4c_2p4c_2docs_2_coding_standard_philosophy.html#handling-errors |

**Comment by jafingerhut** [comment]
All of the links reported in my original issue are working reasonably now in the version generated and published here https://p4lang.github.io/p4c/index.html after this PR was merged in: https://github.com/p4lang/p4c/pull/4793

Thus, closing this issue.
