### ISSUE TITLE
Broken links in the P4C generated docs #2

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#4804]
I found these broken links in this page on 2024-Jul-13: https://p4lang.github.io/p4c/md__2home_2runner_2work_2p4c_2p4c_2_r_e_a_d_m_e.html

+ "CI installation script" link https://p4lang.github.io/p4c/tools/ci-build.sh
+ "dependencies installation script" link https://p4lang.github.io/p4c/tools/install_fedora_deps.sh
+ "rule" link https://p4lang.github.io/p4c/bazel/p4_library.bzl
+ "bazel/example" link https://p4lang.github.io/p4c/bazel/example
+ "unsupported P4_16 language features" link https://p4lang.github.io/p4c/backends/bmv2/README.md#unsupported-p4_16-language-features

**Comment by jafingerhut** [comment]
As of commit 6 of #4753, I have confirmed that all broken links mentioned in this issue _except_ the last one have been fixed.

**Comment by AdarshRawat1** [comment]
> As of commit 6 of #4753, I have confirmed that all broken links mentioned in this issue _except_ the last one have been fixed.

 I think you meant 
- commit 6 of PR #4793 

instead of
- issue #4753.

**Comment by AdarshRawat1** [comment]
# Fixed links 

| Sections | Updated links |
|--------|--------|
| CI installation script (GitHub Repo) | https://github.com/p4lang/p4c/blob/main/tools/ci-build.sh |
| dependencies installation script (GitHub Repo) | https://github.com/p4lang/p4c/blob/main/tools/install_fedora_deps.sh |
| "rule" link  (GitHub Repo) | https://github.com/p4lang/p4c/blob/main/bazel/p4_library.bzl|
| bazel/example (GitHub Repo) | https://github.com/p4lang/p4c/tree/main/bazel/example |
| unsupported P4_16 language features |  https://p4lang.github.io/p4c/md__2home_2runner_2work_2p4c_2p4c_2backends_2bmv2_2_r_e_a_d_m_e.html#unsupported-p4_16-language-features |

**Comment by jafingerhut** [comment]
All of the links reported in my original issue are working reasonably now in the version generated and published here https://p4lang.github.io/p4c/index.html after this PR was merged in: https://github.com/p4lang/p4c/pull/4793

Thus, closing this issue.
