### ISSUE TITLE
Broken links on P4C docs page on P4Smith

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#4823]
This is on the generated P4C docs page at https://p4lang.github.io/p4c/md__2home_2runner_2work_2p4c_2p4c_2backends_2p4tools_2modules_2smith_2_r_e_a_d_m_e.html

In particular, the links with the link text listed below:

+ targets/generic
+ targets/bmv2
+ targets/pna
+ targets/ebpf

These broken links exist even after this PR was merged: https://github.com/p4lang/p4c/pull/4793

**Comment by iamAyushChamoli** [comment]
Pardon me, the tests weren't passing, despite the links were fixed. Had to close the branch to reset.

**Comment by AdarshRawat1** [comment]
@jafingerhut Thanks for the hunt.

**Comment by AdarshRawat1** [comment]
> Pardon me, the tests weren't passing, despite the links were fixed. Had to close the branch to reset.

You can refer to our [DCO Guidelines](https://github.com/p4lang/governance/wiki/P4-DCO-Guidelines) for details on how to sign your commits.

**Comment by jafingerhut** [comment]
Corrected by a recently merged PR, so closing this issue: https://github.com/p4lang/p4c/pull/4828
