### ISSUE TITLE
Can't find `gc_mark.h` during build

### ISSUE THREAD

**Issue by jkhsjdhjs** [p4lang/p4c#4857]
When using `P4C_USE_PREINSTALLED_BDWGC=ON`, the compiler cannot find `gc_mark.h`, because it is installed to `/usr/include/gc/gc_mark.h` instead of `/usr/include/gc_mark.h`:

https://github.com/p4lang/p4c/blob/c3388512c56255c89daabf9e1e0a2308f72bfed5/lib/gc.cpp#L34

Changing this line to
```cpp
#include <gc/gc_mark.h>
```
makes it work.

I checked with the bdwgc makefile, installing `gc_mark.h` only to the `gc` subdirectory seems to be intended:

https://github.com/ivmai/bdwgc/blob/7f1503dbfe254e77678666a0e09b735add064b57/Makefile.direct#L132-L140

So if it doesn't cause any issues when not building against the system bdwgc, I recommend changing this include.

**Comment by asl** [comment]
I might be wrong, but I do not see why we need to include this header at all.

**Comment by ChrisDodd** [comment]
> I might be wrong, but I do not see why we need to include this header at all.

It's for the declaration of `GC_set_start_callback`  that is needed/used to enable gc logging

**Comment by asl** [comment]
> Why this one function is in gc_mark.h instead of in gc.h with all the others, I don't know.

Yeah, right. Seems to be a bit strange place...

**Comment by fruffy** [comment]
> So if it doesn't cause any issues when not building against the system bdwgc, I recommend changing this include.

We probably have to special-case the include when `P4C_USE_PREINSTALLED_BDWGC` is on.
