### ISSUE TITLE
Who can tell me the differences between p4c, p4c-bm and p4c-hlir ?

### ISSUE THREAD

**Issue by dingrui37** [p4lang/p4c#487]
Who can tell me the differences between p4c, p4c-bm and p4c-hlir ? thanks

**Comment by jafingerhut** [comment]
I have at least partial answers in a README here:
https://github.com/jafingerhut/p4-guide#p4-hlir

For folks more knowledgeable of the P4 tools than me, I would appreciate a
critical reading of those few paragraphs to see if I have misrepresented
anything.

Andy

**Comment by antoninbas** [comment]
The description is accurate IMO

**Comment by jafingerhut** [comment]
OK to close this now, then?
