### ISSUE TITLE
P4_14 parser exceptions are not recognized by bison parser

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#489]
parser exceptions have never been used much in P4_14 AFAIK, however people are complaining that p4c is rejecting valid (according to the current spec) P4_14 programs that use parser exceptions

**Comment by mbudiu-vmw** [comment]
I have assigned @ChrisDodd; but he can probably only help with the grammar; we should discuss about how to represents exceptions in P4-16. It would be nice to have at least one test example with exceptions.
I never understood clearly their semantics personally.

**Comment by ChrisDodd** [comment]
The P4_14 frontend has support for parser exceptions, so any legal program that uses them should be accepted.  They're just dropped before conversion to P4_16, however, so they won't be visible in the midend or backend, which might result in problems there.

**Comment by mbudiu-vmw** [comment]
I have pushed a "fix" for this issue which only consists in emitting a warning when a parser exception is encountered. I suggest to close this issue - which seems to be about parsing programs with parser exceptions. If we want to implement properly a translation to P4-16 we should probably file a different issue. If someone can explain exactly how a parser exception is triggered then we can attempt to implement the translation.
