### ISSUE TITLE
recomputing / verifying the TCP checksum in P4_16?

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#490]
I've been looking for an example, but I couldn't find any? How can I express that the checksum computation needs to include the whole TCP payload?
Incremental checksum computation would work for recomputing the checksum, but not for checksum verification.
Finally the `Checksum16` extern in v1model.p4 does not match the one described in Appendix C of the P4_16 spec, and does not support incremental update. As a result I don't see how it can even be used to recompute the checksum when a TCP field is modified.

**Comment by mbudiu-vmw** [comment]
- Indeed, v1model.p4 does not support payload checksums
- The spec checksum is just an example; each architecture will have a different checksum unit
- We should probably add a new method to the v1model.p4 checksum, something like "addPayload()'. We then will have to properly translate p4-14 to that, and also to generate the right json out of it. Hopefully it will provide the intended semantics.
- I think that P4-14 does not support a 'remove' method, and neither does BMv2, so that's why it is not in v1model.p4

Handling checksums is the biggest mismatch between P4-14 and P4-16. The compiler code is rather brittle in that respect. It would probably be simplest to solve this issue satisfactorily if BMv2 supported an extern that did the checksums, with the API in v1model.p4, instead of having it is a built-in construction.

**Comment by jafingerhut** [comment]
@antoninbas I am confused by the part of your question about calculating the checksum over the whole payload, where the question referes to the IPv4 checksum.

There is an IPv4 header checksum that includes the IPv4 header (including IPv4 options, if any).  

There is a TCP checksum that includes the whole payload, and an optional UDP checksum that includes the whole payload, but those are not IPv4-specific.  Do you want to perform a TCP or UDP checksum in P4?

**Comment by antoninbas** [comment]
My bad @jafingerhut, I meant the TCP checksum. Do you think I should fix my question?

**Comment by jafingerhut** [comment]
I didn't think the standard architecture or P4_14 had any operations that worked on the entire packet payload, but I could have missed it.

**Comment by antoninbas** [comment]
The tutorial repo has an example of how the TCP checksum can be recomputed in P4_14 if one TCP field is modified: https://github.com/p4lang/tutorials/blob/master/examples/simple_nat/p4src/simple_nat.p4#L160
This feature is needed for a P4 NAT implementation.

**Comment by jafingerhut** [comment]
Got it.  And now I have verified that the v1.0.3 spec has the payload keyword in it, too, for exactly this purpose.  The latest draft of Calin's P4_16 psa.p4 doesn't have that keyword, nor mention 'payload' anywhere in it, but that could just be an oversight while other higher priority items are being worked on.

**Comment by antoninbas** [comment]
updated my question to refer to the TCP checksum instead of the IPv4 checksum, which was a typo on my part

**Comment by mbudiu-vmw** [comment]
I am upgrading this to a bug: v1model.p4 does not support computing udp/tcp checksums, and thus it cannot support legacy P4-14 programs that need them.

**Comment by qin-nz** [comment]
@mbudiu-vmw 
```
extern void verify_checksum_with_payload<T, O>(in bool condition, in T data, inout O checksum, HashAlgorithm algo);
extern void update_checksum_with_payload<T, O>(in bool condition, in T data, inout O checksum, HashAlgorithm algo);
```
I think above two method should fix the problem in normal situation. (e.g. We often calculate payload after `in T data`)
By the way, you should padding in payload if needed.

**Comment by mbudiu-vmw** [comment]
The compiler will not generate code for these methods, it will just invoke the bmv2 corresponding methods. I assume that BMv2 does padding.

**Comment by kairotavares** [comment]
Any updates on this bug?

**Comment by mbudiu-vmw** [comment]
I was assuming that @qin-nz was assigning himself to implement the solution he proposed. That should work. This will require 3 changes:
- adding these methods to v1model
- changing the p4-14 parser to generate calls to these methods
- handling these methods in the bmv2 back-end to generate proper bmv2 calls

This should not be too hard to do. Does anyone volunteer to do this work?

**Comment by mbudiu-vmw** [comment]
OK, I assigned it to myself.

**Comment by mbudiu-vmw** [comment]
We don't have any end-to-end tests for this feature. I would appreciate if someone could contribute one.
The generated code looks fine.

**Comment by mbudiu-vmw** [comment]
I will assume that the provided fix is satisfactory and that we can close this issue.
We still don't have an STF test, though.
Maybe we can file a separate issue for that.
