### ISSUE TITLE
Using enum as a type generates syntax error.

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#492]
```
 enum HashAlgo {
    CRC32
}
extern Hash<Algo, O> {
    Hash();
    O getHash<T, D, M>(in T base, in D data, in M max);
}
control ingress<H, M> (inout H hdr, inout M meta);
package PSA<H, M> (ingress<H,M> ig);
// user program
struct ParsedHeaders {
    bit<32> hdr;
}
struct Metadata {
    bit<32> md;
}
control MyIngress (inout ParsedHeaders p, inout Metadata m) (Hash<HashAlgo.CRC32, bit<32>> h) {
    action compute_hash() {
        bit<32> b = p.hdr;
        tuple<bit<32>, bit<32>> d = {p.hdr, m.md};
        bit<32> max = m.md;
        bit<32> hash;
        hash = h.getHash(b, d, max);
    }
    apply{
        compute_hash();
    }
}
Hash<HashAlgo.CRC32, bit<32>> hash;
MyIngress(hash) ig;
PSA(ig) main;
```

Issue:
action_selector does not accept an enum as the type for instantiation.

Error message:
```
../test/gtest/arch_test.cpp(559):syntax error, unexpected '.', expecting ',' or '>'
        control MyIngress (inout ParsedHeaders p, inout Metadata m) (Hash<HashAlgo.
```

**Comment by mbudiu-vmw** [comment]
You see what a terrible error message this is from gtest, it does not really tell you where the error is.

I cannot reproduce this error, I am getting the following:
```
issue492.p4(30): warning: Table test1 does not have an `default_action' property
    table test1 {
          ^^^^^
issue492.p4(35): warning: selector shadows selector
        selector = action_selector(HashAlgorithm.crc16, 32w1024, 32w10);
        ^^^^^^^^
issue492.p4(12)
    selector
    ^^^^^^^^
```

**Comment by sethfowler** [comment]
What do you mean "from GTest"? That's just p4c's normal error reporting. The line that's being reported is correct.

**Comment by mbudiu-vmw** [comment]
```
../test/gtest/arch_test.cpp(559):syntax error, unexpected '.', expecting ',' or '>'
```

**Comment by sethfowler** [comment]
Yes, that is correct. That error message points to the line where the error is in the P4 program, which is also a line in a `.cpp` file since the P4 program is defined inline in the test.

**Comment by mbudiu-vmw** [comment]
Yes, but I don't have that C++ program, since the code is not checked-in.
How about the error message I posted which happens if you don't use gtest?

**Comment by jnfoster** [comment]
Mihai, I am on 482a3bdee10716281cc544f7ebbe7330355b0019. 

I see this error message for Han's original code snippet, which is like yours but also dumps core:
```
han.p4(30): warning: Table test1 does not have an `default_action' property
    table test1 {
          ^^^^^
han.p4(35): warning: selector shadows selector
        selector = action_selector(HashAlgorithm.crc16, 32w1024, 32w10);
        ^^^^^^^^
han.p4(12)
    selector
    ^^^^^^^^
han.p4(42): error: PackageBlock: Expected 6 arguments for main package
PSA(ig) main;
        ^^^^
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  COMPILER BUG: ../ir/ir.cpp:172
No parameter named eg

Aborted (core dumped)
```

With the newer code since he updated the issue, I see the kind of error he first reported:
```
han.p4(17):syntax error, unexpected '.', expecting ',' or '>'
control MyIngress (inout ParsedHeaders p, inout Metadata m) (Hash<HashAlgo.
                                                                          ^
error: 1 errors encountered, aborting compilation
```

**Comment by mbudiu-vmw** [comment]
I don't understand where this error is coming from. Look at the code, there is no line like the one quoted in the sources. There is no identifier `HashAlgo`.

**Comment by jnfoster** [comment]
He updated the code to 

```
 enum HashAlgo {
    CRC32
}
extern Hash<Algo, O> {
    Hash();
    O getHash<T, D, M>(in T base, in D data, in M max);
}
control ingress<H, M> (inout H hdr, inout M meta);
package PSA<H, M> (ingress<H,M> ig);
// user program
struct ParsedHeaders {
    bit<32> hdr;
}
struct Metadata {
    bit<32> md;
}
control MyIngress (inout ParsedHeaders p, inout Metadata m) (Hash<HashAlgo.CRC32, bit<32>> h) {
    action compute_hash() {
        bit<32> b = p.hdr;
        tuple<bit<32>, bit<32>> d = {p.hdr, m.md};
        bit<32> max = m.md;
        bit<32> hash;
        hash = h.getHash(b, d, max);
    }
    apply{
        compute_hash();
    }
}
Hash<HashAlgo.CRC32, bit<32>> hash;
MyIngress(hash) ig;
PSA(ig) main;
```

**Comment by mbudiu-vmw** [comment]
@jnfoster: the compiler is dumping core because you can't compile this with p4c-bm2-ss; this is not a program for v1model.
I will file a separate bug for that.

**Comment by hanw** [comment]
I pasted the wrong test case in the original email. Thanks Nate for pointing that out.

**Comment by mbudiu-vmw** [comment]
This example is not syntactically correct; you can only use types as type arguments when specializing a type. However, HashAlgo.CRC32 is not a type, it is a constant.

**Comment by cc10512** [comment]
However, @hanw's example is using HashAlgo as the the type, and HashAlgo.CRC32 as a constant parameter. That doesn't work either.

**Comment by mbudiu-vmw** [comment]
The example posted won't work in Java or C# either; the generics in P4 are modeled after those languages.
A constant can be used perhaps as a constructor parameter, but not as a template parameter.
Maybe there is another example I have not seen?

**Comment by cc10512** [comment]
Here is the source for all the examples that @hanw is trying to get through the compiler: https://github.com/cc10512/p4c/blob/cc/psa/p4include/psa.p4

**Comment by mbudiu-vmw** [comment]
There are generic externs in v1model.p4. In particular, register is a working example.
If you want a constant value, pass it as a constructor parameter.
In our language both templates and constructor arguments are evaluated at compile-time, so the expressivity is the same.

**Comment by jnfoster** [comment]
Can we safely close this?

**Comment by hanw** [comment]
Closed by passing constant value as a constructor parameter.
