### ISSUE TITLE
Cannot dump a p4 program with IR as comments

### ISSUE THREAD

**Issue by fengkeyleaf** [p4lang/p4c#4923]
Hi there,

I was trying to dump a p4 program with IR as comments, which is mentioned in this [pdf](https://github.com/p4lang/p4c/blob/main/docs/compiler-design.pdf) on page 39.

> Front-end and mid end passes can all dump IR back as P4 source with IR as comments; use --top4 pass and -v compiler arguments

However, I couldn't get such a p4 file after trying the command line with [the example](https://github.com/p4lang/tutorials/tree/master/exercises/basic/solution) in the tutorials.  I only got some printed outputs on the console ( Shown in the following picture ), not the format mentioned in the pdf.

![Ym9cdW8SaD](https://github.com/user-attachments/assets/f25844ef-cb11-4003-a14f-3726ed309cca)

Is there something that I missed or incorrect?

regards,

**Comment by fruffy** [comment]
Are you using the --dump [folder] command to write the passes to a file?

**Comment by ChrisDodd** [comment]
You should see a whole bunch of files of the form 'basic-NNNN-ParentPass-X-PassName.p4' created in the current directory (or in the directory you specify with the --dump option) containing the code after each pass.

**Comment by fengkeyleaf** [comment]
> Are you using the --dump [folder] command to write the passes to a file?

There are still no p4 files dumped after adding --dump:

![image](https://github.com/user-attachments/assets/9ca76406-940c-4c71-a4b7-2dd033ca719a)

![image](https://github.com/user-attachments/assets/36831134-7c07-4ffc-8284-f6dbd71d6c53)

by the way, I'm using the VM ( Date published: 2024-Aug-01 ) from [this p4-guide repository](https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md). Is it possible that the compiler isn't configured or installed correctly?

**Comment by ChrisDodd** [comment]
> There are still no p4 files dumped after adding --dump:
> 

You still seems to be dumping only passes names `pass` -- try `--top4 _`

**Comment by fruffy** [comment]
> > There are still no p4 files dumped after adding --dump:
> 
> You still seems to be dumping only passes named `pass` -- try `--top4 _`

The regex might be case-sensitive, something we could fix, too.

**Comment by fengkeyleaf** [comment]
> > There are still no p4 files dumped after adding --dump:
> 
> You still seems to be dumping only passes named `pass` -- try `--top4 _`

Oh, it worked by using --top4 _, instead of --top pass, thanks for the help!

![image](https://github.com/user-attachments/assets/b47e26b5-bf5b-4f3b-b724-3850e0fc4316)

regards
