### ISSUE TITLE
Syntax error with generic counter extern.

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#495]
This is a snippet from the upcoming portable switch architecture psa.p4. 

We are trying to create a generic counter extern and run into a syntax error with the frontend.

```
enum CounterType_t {
    packets,
    bytes,
    packets_and_bytes
}

extern Counter<W> {
    Counter<W> (int number, W size_in_bits, CounterType_t type);
    void count<W>(in W index, in W increment);
}
```

Error message:
```
issue494.p4(23):syntax error, unexpected '('
    Counter<W> (
               ^
error: 1 errors encountered, aborting compilation
```

The code snippet is pushed to https://github.com/hanw/p4c/commit/2a2827e8e46bad410c7f9c32d2ca6b18f04b6e49

**Comment by mbudiu-vmw** [comment]
The syntax is like Java; you cannot have generic constructors; all generic arguments are on the type itself.
So just delete the `<W>` from the constructor.

**Comment by mbudiu-vmw** [comment]
Also, probably you don't want a `<W>` on the count method; it uses the `<W>` from the extern.

**Comment by hanw** [comment]
```
enum CounterType_t {
    packets,
    bytes,
    packets_and_bytes
}

extern Counter<W> {
    Counter (int number, W size_in_bits, CounterType_t type);
    void count (in W index, in W increment);
}
```
With the above example, frontend reports a different error.

```
issue494.p4(23):syntax error, unexpected IDENTIFIER, expecting '<'
    Counter (int number
                      ^
error: 1 errors encountered, aborting compilation
```

**Comment by mbudiu-vmw** [comment]
Yes, `int` is not a type you can write down in P4. It is only used internally by the compiler.
You have to choose a width; so use `int<32>`, or probably `bit<32>`.
One can argue that this is a bug in the design, but the implementation follows the design.

**Comment by hanw** [comment]
Thanks, it makes sense now.

**Comment by hanw** [comment]
@cc10512 It is probably easier for you to update the psa.p4 on your branch instead of me.

**Comment by hanw** [comment]
@mbudiu-vmw I think it would be helpful to adjust the '^' position to point to space after `int` instead of the end of `number`. Should I file another issue for the improvement?

**Comment by hanw** [comment]
alternatively, the error message could say `unexpected IDENTIFIER "number"`.

**Comment by mbudiu-vmw** [comment]
These error messages suck, but they come from bison.
I don't know how to improve on them.

**Comment by jnfoster** [comment]
@hanw can we close this?

**Comment by hanw** [comment]
yes.
