### ISSUE TITLE
Missing declaration for constructor argument

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#496]
Compiling the following program,
```
#include <v1model.p4>

header h_t {
  bit<8> f;
}

struct my_packet {
  h_t h;
}

struct my_metadata { }

parser MyParser(packet_in b, out my_packet p, inout my_metadata m, inout standard_metadata_t s) {
  state start {
   transition accept;
  }
}

control MyVerifyChecksum(in my_packet hdr, inout my_metadata meta) {
  apply { }
}

control D() {
  apply { }
}

control C()(D d) {
  apply {
    d.apply();
  }
}

control MyIngress(inout my_packet p, inout my_metadata m, inout standard_metadata_t s) {
  D() d;
  C(d) c;
  apply { c.apply(); }
}

control MyEgress(inout my_packet p, inout my_metadata m, inout standard_metadata_t s) {
  apply { }
}

control MyComputeChecksum(inout my_packet p, inout my_metadata m) {
  apply { }
}

control MyDeparser(packet_out b, in my_packet p) {
  apply { }
}

V1Switch(MyParser(), MyVerifyChecksum(), MyIngress(), MyEgress(), MyComputeChecksum(), MyDeparser()) main;
```
produces an error:
```
/home/ubuntu/min.p4(35): error: Could not find declaration for d
  C(d) c;
    ^
```
However, if I replace that `d` with `D()`, then it successfully compiles.

**Comment by mbudiu-vmw** [comment]
This is a weird one. I haven't thought that you could pass controls as arguments to other controls (using constructor arguments) - but it looks like you can. Is this something we want to allow in the spec?

**Comment by jnfoster** [comment]
Morally, it's no different than defining C in the scope of an instance d. So we should only rule it out if what I described is also illegal.

-N

**Comment by jafingerhut** [comment]
The compiler does not allow defining a control within the lexical scope of an outer control, if that is what you mean.

**Comment by mbudiu-vmw** [comment]
This looks a lot like a function reference. It can be resolved statically, but the thinking was that we don't have function references - any identifier which names a function can be resolved statically.

This case is strange because the identifier can be resolved statically - after some substitutions are performed.
But inside C you don't know what instance of D you are calling.

**Comment by jnfoster** [comment]
```
control D(...)() { ... }
D() d;
control C(...)() { 
  // I believe you can refer to d here.
}
```

**Comment by mbudiu-vmw** [comment]
The last question is related to global instances; it's slightly different.
There are no global instances in this issue example.

**Comment by mbudiu-vmw** [comment]
Then we should also allow this:

```
control Proto();
control C()(Proto p) {
    apply { p.apply(); }
}
```

**Comment by mbudiu-vmw** [comment]
It would be simplest if we disallowed passing controls, parsers and packages as constructor arguments.
I am trying to make this work, but I would rather keep the language simpler for now.

**Comment by mbudiu-vmw** [comment]
Note that we can allow them later if we change our mind.

**Comment by jnfoster** [comment]
My original response was that if we do that, then we should also disallow global instances because they achieve the same effect.

**Comment by mbudiu-vmw** [comment]
It is not the same effect; in C you can resolve d immediately.
You don't need to see the instantiation of C to resolve it.
