### ISSUE TITLE
Annotations incur huge overhead

### ISSUE THREAD

**Issue by asl** [p4lang/p4c#4974]
It seems that `Annotations` / `Annotation` incur lots of overheads due to cloning during visiting:
<img width="886" alt="Screenshot 2024-10-22 at 12 12 06" src="https://github.com/user-attachments/assets/94db981b-905b-463d-9dea-d4d606adc789">

As one can see, the `Annotations` is behind the largest amount of memory allocations (and total size). `Annotation` itself is also results in large memory overhead.

There are multiple things that contribute to this:
  - `Annotation` itself is large. It is supposed to be a union of different things (vector of tokens, vector of expressions or indexed vector), but instead it just hold all of them. As a result, `Annotation` itself is 576 bytes and this is quite large node.
  - `Annotations` is also large: ~200 bytes, but more importantly it is cloned every time `IAnnotated` node is visited in the `Transform`. The reason is simple: while it is optional, it is always initialized to `Annotations::empty` resulting to explicit copies during visiting.

**Comment by jafingerhut** [comment]
@asl Can this issue be closed now that #4992 is merged?
