### ISSUE TITLE
Currently `cmake` requires `-DCMAKE_BUILD_TYPE=Release` or similar option to build without error

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#4991]
I believe this is a very minor issue, but wanted to see if others felt it was worth changing something.

If I attempt to build p4c without explicitly specifying `-DCMAKE_BUILD_TYPE=Release` (with that particular capitalization), then Z3 fails to build from source, because I believe the Z3 cmake "inherits" the value of CMAKE_BUILD_TYPE from p4c's cmake invocation, and Z3 gives an error if the value is `RELEASE` (all caps).

There are probably other ways to improve on this, but possibilities include:

+ Make the default value of CMAKE_BUILD_TYPE for p4c, if not specified on the cmake command line, `Release` instead of `RELEASE`.
+ Change how Z3 is bulit so that its cmake invocation always uses `-DCMAKE_BUILD_TYPE=Release`, regardless of what is specified for p4c's cmake invocation.

**Comment by fruffy** [comment]
Z3 only enforces what is implicit in CMake: https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#case-sensitivity

Is the default build type set somewhere still? We definitely should make it Release.

Alternatively we can remove the Z3 check if it is too strict.

**Comment by jafingerhut** [comment]
> Is the default build type set somewhere still? We definitely should make it Release.

Here, I believe: https://github.com/p4lang/p4c/blob/main/CMakeLists.txt#L80-L82
