### ISSUE TITLE
The Tofino back end is currently broken

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#5008]
Caused by #4992.

**Comment by hanw** [comment]
Add @psivanup

**Comment by asl** [comment]
I am working on first series to fix annotations usage in the backend.

**Comment by fruffy** [comment]
I have also started some work on this on the side but unlikely I will finish it soon: 
https://github.com/p4lang/p4c/commit/02861b90739750d3677a775bac9e035495c3d3c1

Feel free to cherry pick some of the changes here.
