### ISSUE TITLE
std::get is not guarded in the IR::Annotation getters

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#5050]
The getters defined [here](https://github.com/p4lang/p4c/blob/main/ir/base.def#L335) are not guarded. They just throw 
```
Internal compiler error: std::get: wrong index for variant                  
```
which is confusing to users. Ideally they should report a proper error message.

**Comment by asl** [comment]
This is expected actually. It is an ICE to use wrong getter (e.g. treat unparsed annotation as parsed), this is not a user error, but rather a compiler author error.

**Comment by fruffy** [comment]
> This is expected actually. It is an ICE to use wrong getter (e.g. treat unparsed annotation as parsed), this is not a user error, but rather a compiler author error.

Yes, but the problem is that the throw doesn't provide a message but instead just defaults to the unhelpful boost exception message. Ideally, users should see "Compiler Bug" or "Unimplemented".

**Comment by asl** [comment]
> message. Ideally, users should see "Compiler Bug" or "Unimplemented".

I am confused. Why "Unimplemented"? It shows "internal compiler error" that indicates the problem with the compiler itself. And if one launch the app in the debugger, then there is a clear stack trace where the exception is thrown. Overall, this is clean indication that there is some logic error somewhere, e.g. that the backend does not parse annotations properly, etc. 

PS: This is not a boost exception, it just comes from the C++ standard library.

**Comment by fruffy** [comment]
> > message. Ideally, users should see "Compiler Bug" or "Unimplemented".
> 
> I am confused. Why "Unimplemented"? It shows "internal compiler error" that indicates the problem with the compiler itself. And if one launch the app in the debugger, then there is a clear stack trace where the exception is thrown. Overall, this is clean indication that there is some logic error somewhere, e.g. that the backend does not parse annotations properly, etc.
> 
> PS: This is not a boost exception, it just comes from the C++ standard library.

Unimplemented was just an example. E.g., if a user runs into this issue it is better to throw an Internal error or a more helpful error message instead of just deferring to the generic exception. It makes it easier to spot the context in bug reports and is also more helpful to the user. Same reason we have CHECK_NULL instead of just asserting. 

>PS: This is not a boost exception, it just comes from the C++ standard library.

Yeah still used to calling this boost::variant..

**Comment by fruffy** [comment]
A good example is the bug check a couple lines further down: https://github.com/p4lang/p4c/blob/main/ir/base.def#L341
We could also just let it throw `std::out_of_range` here.
