### ISSUE TITLE
Including 'error' as a struct member crashes the compiler

### ISSUE THREAD

**Issue by cc10512** [p4lang/p4c#510]
As reported by @vgurevich, the following snippet:
```
struct my_metadata_t {
    error parser_error;
}
```
crashes the compiler
```
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  COMPILER BUG: ../backends/bmv2/jsonconverter.cpp:2487
/home/vgurevich/hh/p4c/build/p4include/core.p4(22): error { NoError, PacketTooShort, NoMatch, StackOutOfBounds, OverwritingHeader, HeaderTooShort, ParserTimeout }: Unhandled type for error { NoError, PacketTooShort, NoMatch, StackOutOfBounds, OverwritingHeader, HeaderTooShort, ParserTimeout } parser_error
error {
^
/tmp/error_in_struct.p4(29)
    error parser_error;
          ^^^^^^^^^^^^

Aborted (core dumped)
```

Full program attached: [error_in_struct.p4.txt](https://github.com/p4lang/p4c/files/949895/error_in_struct.p4.txt)

**Comment by mbudiu-vmw** [comment]
error is a funny one; as far as I can tell, BMv2 does not really expose the parser error at all - you cannot read the error generated by the parser, and it is not exposed as part of the architecture metadata.

But this does not preclude the user from using error as an enum.
So in the BMv2 back-end we can just treat it like a special enum.
