### ISSUE TITLE
p4test and p4c-bm2-ss give errors for conditional method call inside action

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#513]
I understand if some targets have complexity restrictions that prevent one from using if statements inside of actions, but it seems that at least p4test, and preferably also p4c-bm2-ss, should allow this, since P4_16 the language spec seems to allow it.

The attached program causes both p4test and p4c-bm2-ss to give an error on the mark_to_drop() call inside action 'foo':

    error: MethodCallStatement: Predication cannot be applied

If this is easy to correct for p4test, but requires changes to bmv2 for enhancing it in p4c-bm2-ss, I'm happy to file separate issues for p4c-bm2-ss and bmv2 from this one.
[if-restrictions-inside-action.p4.txt](https://github.com/p4lang/p4c/files/950094/if-restrictions-inside-action.p4.txt)

**Comment by mbudiu-vmw** [comment]
p4test is a compiler for an "arbitrary" architecture, which is mostly used to test the passes; whether it should accept or not conditionals in actions is debatable. But if it did we could not test the predication pass...

p4c-bm2-ss does not accept conditionals in actions.

We should give a better error message, so this issue is a bug. 

What happens is the following: the compiler accepts conditionals (and short-circuit evaluation) in actions at the front-end; it converts short-circuit evaluation into conditionals, and then the predication pass attempts to convert conditionals into ?: operators; this can be done for all operations except method calls that return void. So if you program has a conditional method call it cannot be executed on p4c-bm2-ss.

**Comment by jafingerhut** [comment]
p4c-bm2-ss _does_ accept some conditionals in actions without errors, but not always.  See https://github.com/p4lang/p4c/issues/512 for an attached program, where if you comment out one of several marked lines in an action that has an if statement, it compiles without error, and I believe even produces a correct bmv2 JSON file.

**Comment by mbudiu-vmw** [comment]
Whether conditionals are supported or not in actions depends on the target. The language allows conditionals.

The BMv2 back-end attempts to translate "if" statements into "?:" expressions; it if succeeds, then the program will compile. But this cannot always be done. (The conversion is not very efficient.)

**Comment by jafingerhut** [comment]
Is there some existing program other than p4test and p4c-bm2-ss that is intended to accept everything legal in P4, regardless of the capabilities of a particular back end?

**Comment by jnfoster** [comment]
I'm not sure how to interpret "arbitrary architecture" but I think that could be p4test...

**Comment by jafingerhut** [comment]
@jnfoster: From Mihai's earlier comments, it sounds like right now if p4test allowed if statements with method calls like mark_to_drop() executed conditionally within them, then at least in whatever 'mode' p4test was running in that accepted that, could not be used to test one or more of the compiler passes.  I understand the desire to have automated tests, for sure.  But it does seem that this goal may be slightly at odds with having a compiler front end that accepts everything that is legal in the P4-16 spec.

**Comment by jnfoster** [comment]
I think having a dummy front-end that accepts all syntactically / semantically valid programs will be valuable for the entire P4 community.

Having a dummy front-end that can be used for testing is useful, but mostly of interest to p4c developers.

If people agree with these statements, we could work to build such a front-end. However, likely not before the P4 Workshop...

**Comment by jafingerhut** [comment]
I will open a separate enhancement proposing that, marked suitably low priority, and close this issue, since at least for near-term purposes it is fixed.

**Comment by jafingerhut** [comment]
Opened a separate issue for the desire to have a dummy front-end compiler that can take everything P4-16 allows: https://github.com/p4lang/p4c/issues/530
