### ISSUE TITLE
Give error for assignment from bit<N> to bit<M> with N != M, and also for int<>

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#516]
This is to conform with the change to the P4-16 spec proposed here: https://github.com/p4lang/p4-spec/pull/173

there is a prototype patch attached as a file named p4c-diff-error-on-implicit-cast.txt on this issue: https://github.com/p4lang/p4-spec/issues/163#issuecomment-294698363
but that is not necessarily the best way to implement this change.  It is mentioned here only for reference.

**Comment by mbudiu-vmw** [comment]
There are lots of p4-14 programs which fail this test.
There are no casts in p4-14, so we'll have to insert them in the conversion process.

**Comment by jafingerhut** [comment]
Perhaps the default could be to insert implicit casts for P4-14 source code, but error for P4-16 source code?

**Comment by jafingerhut** [comment]
I have confirmed that the commit with PR #522 gives errors in P4-16 programs where LHS and RHS are `bit<W>` with different bit widths.  Closing this issue.
