### ISSUE TITLE
Enhancement: program that accepts all legal P4_16 programs

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#530]
p4test is pretty close to this already, but for various reasons it does not accept some syntactically and semantically legal P4_16 programs as of 2017-Apr-26, e.g. see https://github.com/p4lang/p4c/issues/513

Given how close p4test is to this, one possible implementation might be to add a new p4test command line option that changes its behavior somewhat, enabling it to accept all legal P4_16 programs, e.g. --validate

**Comment by mbudiu-vmw** [comment]
The only thing needed is to stop compilation after the front-end is finished.

**Comment by jafingerhut** [comment]
Sorry for my ignorance in asking, but is there already a p4test command line option that achieves this, and if so, what is it?

**Comment by mbudiu-vmw** [comment]
No. But that would be the fix.

**Comment by jafingerhut** [comment]
Tested with new --validate option on the same program on issue #513 that causes p4test to issue an error, and it gives no error.  Thanks!
