### ISSUE TITLE
Conclusive proof that P4 is ahead of its time

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#537]
https://github.com/p4lang/p4c/blob/0f2b63ecdea93bcb0c7b2b8ced57bae62fc8b404/testdata/p4_16_samples/x-bmv2.p4#L2
https://github.com/p4lang/p4c/blob/0f2b63ecdea93bcb0c7b2b8ced57bae62fc8b404/testdata/p4_16_samples/def-use.p4#L2

:-)

**Comment by jnfoster** [comment]
Or maybe Mihai is just really pessimistic about the P4-16 release date.
