### ISSUE TITLE
Question: Is match_kind 'selector' long term plan for P4-16 action profiles?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#543]
A colleague and I noticed the 'selector' match_kind in v1model.p4, and I did a little digging and found that it is indeed related to the implementation of action profiles with v1model.p4, according to these comments: https://github.com/p4lang/p4c/blob/master/control-plane/p4RuntimeSerializer.cpp#L1314-L1320

Is the selector match_kind the long term plan for indicating that a table uses action profiles, or a temporary stop-gap unti the PSA architecture is defined?

**Comment by mbudiu-vmw** [comment]
V1model is a model of the p4-14 architecture. This models dynamic action selection from the p4-14 spec.

**Comment by cc10512** [comment]
```selector``` match_kind is in for a long term. The PSA will include it too to facilitate dynamic action selection. We are defining two externs, ActionProfile and ActionSelector for handling this functionality. See https://github.com/cc10512/p4c/blob/cc/psa/p4include/psa.p4#L469-L524.

**Comment by jafingerhut** [comment]
So, is it semi-hackish to have a field with a match_kind of 'selector' in a search key, in that there is no intent that the hardware actually includes that field as any part of a search key in the target?  That is, the presence or absence of a field with match_kind 'selector' is effectively a global property of the table that could have bee implemented with a table annotation, but you don't want to require using an annotation for a core architecture feature like this?

If all of that is true, would another way to achieve this be to have no 'selector' match_kind, but instead have a new 'key = value' pair for the table, with a key name like 'action_profile'?

**Comment by mbudiu-vmw** [comment]
There are many ways one could represent similar functionality in P4-16. We should start by documenting clearly what this keyword means; hopefully the PSA spec will do that; then we can figure out whether this is the best way to achieve this effect. For v1model I think this is the most economical way to express the functionality of dynamic action selection, where some parts of the key select the table entry, and for each entry you have multiple possible actions, one of which is selected by the key parts labeled with "selector".

This question really belongs to the PSA specification, and no to the compiler, but I don't know where the question should be filed.

**Comment by mbudiu-vmw** [comment]
This is not a compiler, issue, so we are closing it.
