### ISSUE TITLE
remove `OverwritingHeader`

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#578]
Per 4/24 LDWG discussion.

**Comment by mbudiu-vmw** [comment]
This is more subtle:
- if P4-14 requires this error we have to insert a check in the compiler when compiling extracts
- if BMv2 triggers this error automatically, we have to invalidate headers prior to extraction
@antoninbas : what is the right way to handle this to remain compatible with P4-14 and to provide the right semantics for P4-16?

**Comment by antoninbas** [comment]
I don't think there is anything in the p4_14 spec that says you cannot extract to the same header twice, so I think you are fine on that side.
I have a pull request opened to stop triggering this error in bmv2 (https://github.com/p4lang/behavioral-model/pull/358). I think I should be good to merge it even before you make the compiler change, but just in case I'll wait until you have a PR ready.

**Comment by mbudiu-vmw** [comment]
@antoninbas : does bmv2 still trigger this error?

**Comment by antoninbas** [comment]
Not if I merge this: https://github.com/p4lang/behavioral-model/pull/358

**Comment by antoninbas** [comment]
So @mbudiu-vmw can I merge the bmv2 pull request to stop triggering the error?

**Comment by mbudiu-vmw** [comment]
I think that it is safe to do so.
