### ISSUE TITLE
p4c should use `@globalname` annotations

### ISSUE THREAD

**Issue by cole-barefoot** [p4lang/p4c#582]
See Section 16.3.2 of the most recent P4_16 spec:
https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/P4-16-draft-spec.mdk#L4151

This has two parts:

1. The compiler, when introducing new global names (eg. for P4_14 conversion) should use `@globalname("foo")` instead of `@name(".foo")`.

1. The control plane name generation should be extended to interpret `@globalname("foo")` as it used to interpret `@name(".foo")`.  The `@name` annotation should be treated as always introducing a local name.

**Comment by mbudiu-vmw** [comment]
@sethfowler : AFAICT any name annotation that starts with a dot will be converted to a globalname annotation. So maybe you can just accept both cases in the API generation, and when you do I will change the compiler to generate globalname.

**Comment by mbudiu-vmw** [comment]
I would propose to declare this wontfix, and to change the spec.
It looks to me like using name annotations starting with a dot works just fine.
