### ISSUE TITLE
Directly applying the same type in the same scope creates two instances with the same control API name

### ISSUE THREAD

**Issue by cole-barefoot** [p4lang/p4c#590]
For example:

```p4
control callee(...) { }
control caller(...) {
    apply { callee.apply(...); callee.apply(...); }
}
```

Will be translated to something like:

```p4
control callee(...) { }
control caller(...) {
    @name("callee") callee() tmp_1;
    @name("callee") callee() tmp_2;
    apply { tmp_1.apply(...); tmp_2.apply(...); }
}
```

Either duplicate applications of the same type in the same scope should be rejected, or they should refer to the same local instance (and the spec should be updated to reflect this).

**Comment by mbudiu-vmw** [comment]
I actually think this is a legal program.
If there is a table in callee, then the code which generates a control-plane API should complain.

**Comment by cole-barefoot** [comment]
@mbudiu-vmw: I see your point.  I'm going to close this issue and open a new one about rejecting programs that have the same control API names for different controllable entities.
