### ISSUE TITLE
Reject programs with conflicting control plane names

### ISSUE THREAD

**Issue by cole-barefoot** [p4lang/p4c#595]
It is illegal for a P4 program to have two controllable entities with the same control plane name.  The compiler should reject these programs with an appropriate error message.

For example, tables "t1" and "t2" have the same control plane name in the following code snippet:
```p4
control ingress(
    inout packet_t hdrs,
    inout user_metadata_t m,
    inout standard_metadata_t meta)
{
    action set_port(bit<9> port) { meta.egress_spec = port; }
    @name("t") table t1 {
        key = { hdrs.data.f : exact; }
        actions = { set_port; }
        default_action = set_port(1); }
    @name("t") table t2 {
        key = { hdrs.data.f : exact; }
        actions = { set_port; }
        default_action = set_port(1); }
    apply { t1.apply(); t2.apply(); }
}
```

Note that there are two compiler passes that introduce new control plane name annotations:
 - `TableKeyNames`
 - `InstantiateDirectCalls`

These passes derive `@name` annotations from the syntax of the P4 program.  If these names conflict with other control plane names, the program should be rejected.

**Comment by mbudiu-vmw** [comment]
I think that the P4Runtime code generation should handle this problem.

**Comment by jafingerhut** [comment]
This comment doesn't attempt to specify what the open source p4c _should do_ given such a program, it only explains what the latest versions now published actually do.

With latest p4c as of 2018-Apr-19, all of these commands give no errors nor warnings with a program containing the code in the original issue description:
```
% p4test myprog.p4
% p4test --p4runtime-format json --p4runtime-file myprog-p4info.json myprog.p4
% p4c-bm2-ss -o myprog.json myprog.p4
```
The resulting BMv2 JSON file myprog.json, and P4Info JSON file myprog-p4info.json, are both wrong, in that they contain two separate table instances with the same name "ingress.t".  The latest behavioral-model simple_switch code does correctly give an error if you attempt to give it the BMv2 JSON file myprog.json produced:
```
% simple_switch myprog.json
Thrift port was not specified, will use 9090
Calling target program-options parser
Duplicate objects of type 'control node' with name 'ingress.t'
```

**Comment by antoninbas** [comment]
@mbudiu-vmw Looks to me that such a program should be rejected early in the compilation process. I think we can safely say that under no circumstances should 2 objects have the same control-plane name. If we add the check to the p4RuntimeSerializer, we will probably need to add the check to several backends as well (at least bmv2), given that running the p4RuntimeSerializer is optional and depends on the presence of the `--p4runtime-file` flag. Any issue with enforcing the check in the frontend?

**Comment by mbudiu-vmw** [comment]
The front-end does not do any analysis across different blocks. It may not understand when some control blocks are dead code, for example, and thus their global names may be unused. I will have to think more about it.

**Comment by cc10512** [comment]
There can be no "dead code" for control-plane exposed entities, can it? I mean, sure, we might remove the data-plane resources, but we still should be generating APIs, and if the names collide, that's an invalid program. I think @antoninbas is right, we should reject the program in the front end. Please do consider this carefully, and please also consider what we need to do to implement a context sensitive analysis. We've seen several instances where we emit warnings or even errors for entities that _could_ have the same name. We cleaned up some in https://github.com/p4lang/p4c/pull/798, but I think we still have some ways to go!
