### ISSUE TITLE
p4c build error

### ISSUE THREAD

**Issue by ngsrinivas** [p4lang/p4c#597]
Hi, I'm unsure if this is the right place to ask, but I'm having trouble building p4c on ubuntu 16.04. Could you kindly help or let me know if there's a more appropriate place to post?

I've installed all the dependencies following the instructions from https://github.com/p4lang/p4c#ubuntu-dependencies, and the configuration through bootstrap.sh finishes without errors. However, the make fails with the following error:

../ir/expression.def: In constructor ‘IR::Constant::Constant(intmax_t, unsigned int)’:
../ir/expression.def:137:60: error: call of overloaded ‘__gmp_expr(intmax_t&)’ is ambiguous
             Literal(new Type_InfInt()), value(v), base(base) {}
                                                            ^
I've attached the full output from the compilation. Please lemme know if I can provide more info to clarify the problem. I'm running ubuntu 16.04 with kernel version 4.4.0-75. Thanks a bunch for your help!

[p4c-full-compile-message.txt](https://github.com/p4lang/p4c/files/988461/p4c-full-compile-message.txt)

**Comment by ngsrinivas** [comment]
I'll also add that I apt-get purged and reinstalled libgmp-dev which seems to be related to the error. Build continues to fail with this error.

**Comment by sethfowler** [comment]
Which compiler are you using?

It might also help to run `make V=1` and post the output, so we can see the full command line that's being used to compile.

**Comment by ngsrinivas** [comment]
g++ --version returns "g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609". I've attached the full compiler output with make V=1.

[p4c-compile-message-v-1.txt](https://github.com/p4lang/p4c/files/988659/p4c-compile-message-v-1.txt)

**Comment by mbudiu-vmw** [comment]
This is strange, it looks like the compiler has multiple possible conversions from intmax_t to an integer type.
I would imagine that intmax_t is one of these integer types.

**Comment by cc10512** [comment]
We're using the same version of the compiler and it works fine. I'm inclined to think that your environment has an obsolete gmpxx.h stashed somewhere.  Can you run g++ with -v and check for gmpxx.h in the list of directories that the compiler is searching? Something like this:
```
g++ -v -DHAVE_CONFIG_H -I. -I.. -I../frontends -I../backends -I../extensions -Wall -Wextra -Wno-overloaded-virtual -Wno-deprecated -g -O0 -std=c++11 -MT ir/ir-generated.lo -MD -MP -MF ir/.deps/ir-generated.Tpo -c ir/ir-generated.cpp  -fPIC -DPIC -o ir/.libs/ir-generated.o
```
and look for:
```
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/5"
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/5/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 .
 ..
 ../frontends
 ../backends
 ../extensions
 /usr/include/c++/5
 /usr/include/x86_64-linux-gnu/c++/5
 /usr/include/c++/5/backward
 /usr/lib/gcc/x86_64-linux-gnu/5/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
GNU C++11 (Ubuntu 5.4.0-6ubuntu1~16.04.4) version 5.4.0 20160609 (x86_64-linux-gnu)
	compiled by GNU C version 5.4.0 20160609, GMP version 6.1.0, MPFR version 3.1.4, MPC version 1.0.3
```

**Comment by ngsrinivas** [comment]
Hi, thanks a bunch for your responses. I see the same GMP version as yours (6.1.0) in my corresponding output (attached). Also, I found gmpxx.h only in /usr/include after searching in all the listed directories.

GNU C++11 (Ubuntu 5.4.0-6ubuntu1~16.04.4) version 5.4.0 20160609 (i686-linux-gnu)
	compiled by GNU C version 5.4.0 20160609, GMP version 6.1.0, MPFR version 3.1.4, MPC version 1.0.3

I've also attached the output of `dpkg -l "*gmp*"` to show all gmp related installed packages. All of the packages match the version shown above.

[gmp-detailed-compiler-msg.txt](https://github.com/p4lang/p4c/files/990840/gmp-detailed-compiler-msg.txt)
[gmp-libraries-installed.txt](https://github.com/p4lang/p4c/files/990841/gmp-libraries-installed.txt)

**Comment by mbudiu-vmw** [comment]
We could just cast the argument to a long before calling the constructor.
Does the standard guarantee no loss of information when casting from intmax_t to long?

**Comment by jnfoster** [comment]
Isn't it better to get to the bottom of Srinivas's build issues rather than torque the code?

**Comment by jnfoster** [comment]
(It builds fine for me on OS X and Linux, although I have a newer version of g++)

**Comment by mbudiu-vmw** [comment]
Even if we get to the bottom, if other people will have the same problem we should prevent it if we can. We have already many workarounds for various known compiler and tool bugs and limitations. This is no different.

**Comment by jnfoster** [comment]
@ngsrinivas MIT can't afford 64-bit VMs? (h/t @cc10512 for noticing that ;-))

**Comment by cc10512** [comment]
I think the difference is that you're using a 32-bit system. While I don't think we explicitly say this in our docs, we do test mainly on 64-bit systems. In this case, I believe that the cast that @mbudiu-vmw will make sense.

**Comment by mbudiu-vmw** [comment]
@ngsrinivas : can you please check that this change is sufficient?

```
@@ -134,7 +134,7 @@ class Constant : Literal {
     /// if noWarning is true, no warning is emitted
     void handleOverflow(bool noWarning);
     Constant(intmax_t v, unsigned base = 10) :
-            Literal(new Type_InfInt()), value(v), base(base) {}
+            Literal(new Type_InfInt()), value((long)v), base(base) {}
```

**Comment by ngsrinivas** [comment]
Thanks @mbudiu-vmw and @cc10512! The patch solved the problem. :-) 

I still find it mysterious that g++ ended up targeting a 32-bit system (I'm using an ubuntu 64-bit VM VirtualBox). Any thoughts?
