### ISSUE TITLE
u.isValid()

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#598]
The spec now mandates an `isValid()` method for header unions. This needs implemented.

**Comment by mbudiu-vmw** [comment]
This is subsumed by #561.

**Comment by mbudiu-vmw** [comment]
What is the value of isValid() on an empty union?
I really think we should forbid empty unions, they are a nasty corner case with no practical value.

**Comment by jnfoster** [comment]
I'm fine deleting this issue; I was only adding it because someone (you) said it should be done at the LDWG ;-)

If u is an empty union, then `u.isValid()` is false. It's not an empty corner case. Following the definition given in the spec, it would be an empty disjunction, which is false (e.g., see https://en.wikipedia.org/wiki/Logical_disjunction).

-N
