### ISSUE TITLE
Handling of tables with multiple "lpm" match type fields

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4c#60]
Following up on a posting in p4-dev...

The current code accepts such tables and generates a JSON file. Here is an example program:

```
header_type ethernet_t {
    fields {
        dstAddr : 48;
        srcAddr : 48;
        ethertype : 16;
    }
}

header ethernet_t ethernet;

parser start {
    extract(ethernet);
    return ingress;
}

action set_egress_port(port) {
    modify_field(standard_metadata.egress_spec, port);
}

table t1 {
    reads {
         ethernet.dstAddr : lpm;
         ethernet.srcAddr : lpm;
    }
    actions {
         set_egress_port;
    }
}

control ingress {
    apply(t1);
}

control egress {
}
```

However, when this JSON file is used with simple_switch BMv2 executable, it rejects it with the following message:

```
Table t1 features 2 LPM match fields
```

The current "official" compiler (p4c-bm) rejects such tables. The spec is not very explicit about whether this construct is allowed. If it is, then there needs to be a clear standard on how to handle entry priorities in this case and this will result in different PD API implementation in the first place.

**Comment by mbudiu-vmw** [comment]
I think that this issue has been solved by the recent PR #397
