### ISSUE TITLE
Compiler generates questionable code for P4_14-style checksum verification

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4c#609]
The file `p4_14_samples/basic_routing.p4` contains the code to verify IPv4 header checksum that the compiler translates into P4_16 as follows (formatting cleaned up):

```
control verifyChecksum(in headers hdr, inout metadata meta) {
    Checksum16() ipv4_checksum;
    apply {
        if (hdr.ipv4.hdrChecksum == ipv4_checksum.get({
            hdr.ipv4.version, 
            hdr.ipv4.ihl, 
            hdr.ipv4.diffserv, 
            hdr.ipv4.totalLen, 
            hdr.ipv4.identification, 
            hdr.ipv4.flags, 
            hdr.ipv4.fragOffset,
            hdr.ipv4.ttl,
            hdr.ipv4.protocol, 
            hdr.ipv4.srcAddr, 
            hdr.ipv4.dstAddr })) {
                mark_to_drop();
        }
    }
}
```

The biggest problem (in my opinion) is that the code does not check for the validity of hdr.ipv4, which can lead to a number of unpredictable behaviors. The right thing to do would be to check the validity of any header, involved in the checksum verification before we attempt to do it.

The other problem is the use of mark_to_drop(). it contradicts the spec, because the spec says that a parser exception should be generated. I understand that this is quite problematic in P4_16. 

In addition to that, the functionality of mark_to_drop() in control verifyChecksum() as opposed to control Ingress() is not very clear. For example, does it mean that the packet will not get into the control Ingress() at all or does it mean it will get into control Ingress() and then dropped at the end... How would control Ingress() then check for a packet with bad checksum?

In any case, as of today the code does nothing, because BMv2 never calls this control in the first place.

**Comment by mbudiu-vmw** [comment]
Today the compiler cheats and only looks at the updateChecksum. If you use that it will generate code for the verify too. Bmv2 does checksums in a very different way.

There was never support for parser exceptions because we had no examples using them.

**Comment by vgurevich** [comment]
I feel it would be less misleading if we left those controls blank. I did spend some time today trying to discover the truth.

In any case, I think we should treat this issue as a request to add proper handling of checksum verification. We specifically need to add it to either v1model or PSA, i.e. the final architecture we will be compiling P4_14 into, otherwise it will be difficult to claim compatibility.

**Comment by cc10512** [comment]
@vgurevich agreed we need to support checksums properly. I will open a separate issue for parser exceptions.

**Comment by mbudiu-vmw** [comment]
This issue has been filed under various names; everything was much simpler if there was a BMv2 extern for checksums. We have a lot of code to handle checksums - incorrectly - which would go away. Se also #490, #445, #255, #134.

**Comment by mbudiu-vmw** [comment]
The new APIs should have solved this issue.
