### ISSUE TITLE
make check: XFAIL: p4/testdata/p4_16_samples/cast-call.p4.test

### ISSUE THREAD

**Issue by technobilly** [p4lang/p4c#616]
make check -j4 results:
```
============================================================================
Testsuite summary for p4c 16
============================================================================
# TOTAL: 760
# PASS:  759
# SKIP:  0
# XFAIL: 1
# FAIL:  0
# XPASS: 0
# ERROR: 0
```
The one failure message is:
XFAIL: p4/testdata/p4_16_samples/cast-call.p4.test

**Comment by jnfoster** [comment]
XFAIL means "expected fail"

**Comment by mbudiu-vmw** [comment]
Yes, this is expected.
The XFAIL denotes a well-known bug which we don't know how to fix, so for now we accept it.

**Comment by technobilly** [comment]
Thanks for explanation. I'll close it.
