### ISSUE TITLE
emit() does not support structs

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4c#630]
According to p4_16 specification:

> For derived type, emit recursively proceeds on fields:
> . . .
> If the argument is a struct containing multiple fields, the emit is recursively applied to each component of the struct in the order of their declaration in the struct.

However, the attempt to pass a struct to emit results in the following message:
```
struct my_headers_t {
    ethernet_t     ethernet;
    vlan_tag_t [2] vlan_tag;
    mpls_t [5]     mpls;
    arp_t          arp;
    arp_ipv4_t     arp_ipv4;
    ipv4_t         ipv4;
    icmp_t         icmp;
}

. . . 

control MyDeparser(
    packet_out      packet,
    in my_headers_t hdr)
{
    apply {
        packet.emit(hdr);
   }
}
```

results in the following message:
```
l3_switch.p4(413): error: hdr: emit only supports header and stack arguments, not struct my_headers_t
        packet.emit(hdr);
                    ^^^
l3_switch.p4(110)
struct my_headers_t {
       ^^^^^^^^^^^^
```

**Comment by mbudiu-vmw** [comment]
There is a PR queued with this feature.

**Comment by mbudiu-vmw** [comment]
I lied, the PR is not yet submitted, it is only a commit in my repo, until I figure out some issues with BMv2.
I may split it into two PRs if a solution for this is needed soon.

**Comment by vgurevich** [comment]
It is definitely an extremely useful feature that can relieve a lot of people from the necessity of spending time writing trivial deparsers. Once we allow header_unions in  structs it will be doubly-useful and will also make code a lot safer.

 I wanted to demonstrate it in the training slides, but... So far, I decided to keep the slide, but put a "Not Implemented yet" note :(
