### ISSUE TITLE
Generalize the P4Runtime serializer to support arbitrary backends

### ISSUE THREAD

**Issue by sethfowler** [p4lang/p4c#658]
We'd like to generate a P4Runtime API for arbitrary backends, including ones added by extensions. This is currently *close* to working, but there are some BMV2-specific things in the existing code. We should remove them.

**Comment by mbudiu-vmw** [comment]
I don't think this can be done in general.
You can start by trying to adapt it to the ebpf back-end to see if it works.

**Comment by sethfowler** [comment]
The main difficulty I see is that there needs to be a way to describe to the P4Runtime serializer how to deal with backend-specific externs. It's unclear to me to what extent PSA will help with this in the long term. In the short term we'll have to deal with that problem in a somewhat ad hoc manner.

**Comment by mbudiu-vmw** [comment]
The bottom interface is the one I am wondering about, not the top one.
How do you actually perform the operations that the API describes?

**Comment by sethfowler** [comment]
All the P4Runtime serializer does is generate a data structure that describes the structure of the program (which tables exist, which externs are instantiated, etc). That information is consumed by target-specific code that performs communication between the data plane and the control plane. When someone wants to provide P4Runtime support for a target, they need to write that code manually. All of that code lives outside of the compiler, though; in this issue I'm just concerned with generating that data structure, which is the part that the compiler needs to do.

**Comment by mbudiu-vmw** [comment]
Is there a documentation about how to write such a target-specific code?

**Comment by sethfowler** [comment]
That's a good question. @antoninbas, does such documentation exist yet?

**Comment by antoninbas** [comment]
That's a very good question. As Seth writes, I believe the P4Runtime serializer output (which is actually called P4Info) should be completely backend-independent. It is still my belief that we should be able to run it after the frontend, before any midend or backend passes.
P4Info itself should only include interface-level information: table name, table id, action list, action parameters,... This information is valuable when writing a control-plane and it should actually be the only information needed to build and send P4Runtime messages. As you both correctly point out, acting upon these messages (P4Runtime implementation) requires some additional mapping information (e.g. logical to physical table mapping). This information should be produced by the compiler and is target-dependent. Each backend can use its own format for representing this information. If you look at the P4Runtime message to push a new P4 configuration to a P4-programmable device (https://github.com/p4lang/PI/blob/master/proto/p4/p4runtime.proto#L373), you will notice both P4Info and a binary string (`bytes` type) called `p4_device_config`. This binary data is meant to include any configuration needed by the device to configure its pipeline as well as the mapping information needed by the runtime implementation for this device. I want to emphasize again that both are target-dependent and both are produced by the compiler backend.

**Comment by mbudiu-vmw** [comment]
It looks to me like this issue is solved at this point.

**Comment by antoninbas** [comment]
Yes
