### ISSUE TITLE
Branches for which a PR is open need to be updated very time master is updated

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#660]
Otherwise merge is disabled. This means the Travis regression has to be run again. We can have many competing pull requests and sometimes it is quite hard to get your change merged if you "miss your turn". A discussion was started here: https://github.com/p4lang/p4c/issues/619

**Comment by antoninbas** [comment]
I am in favor of unchecking "Require branches to be up to date before merging" for this repo for a trial period and see if it leads to master getting broken, before trying out more involved solutions. Does anyone have a strong objection?

**Comment by sethfowler** [comment]
I don't think it's the best approach, but it does have the advantage of being very easy to set up. =)

**Comment by cc10512** [comment]
Let's give it a try for a week and if we hit issues, we can revert back to enforcing the requirement.

**Comment by antoninbas** [comment]
I have removed the requirement. I'm counting on people to refresh their branch before merging if it is too stale.
Let's roll it back if we start hitting issues.

**Comment by mbudiu-vmw** [comment]
When does the Travis job for master run?
The build is marked as passing on github, but for my copy of master (which is in sync with upstream) it is failing.

**Comment by antoninbas** [comment]
BTW, the build should run every time master is modified

**Comment by jnfoster** [comment]
Builds fine for me (and tests pass) on
49a4aac86d62d2cc528a626666a5ce8ed42a9b57

**Comment by sethfowler** [comment]
The build (and the tests) *are* run every time master is modified, just in case that's not clear.

**Comment by mbudiu-vmw** [comment]
Maybe we should close this one, seems to me that our current process works fine.

**Comment by antoninbas** [comment]
agreed we haven't had a single problem AFAIK
