### ISSUE TITLE
Error when same local variable name used in 2 parser states

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#665]
The attached program gives the following error during compilation, because a local variable with the same name `my_local` is used in 2 different parser states.  I would have expected that this would be OK, given they are defined in different lexical scopes.
[parser-local-var-names-collide.p4.txt](https://github.com/p4lang/p4c/files/1028254/parser-local-var-names-collide.p4.txt)
```
% p4test parser-local-var-names-collide.p4
parser-local-var-names-collide.p4(74): error: Duplicate declaration of my_local; previous at 
        bit<16> my_local = 2;
                ^^^^^^^^
parser-local-var-names-collide.p4(66)
        bit<8> my_local = 1;
               ^^^^^^^^
error: 1 errors encountered, aborting compilation
```

**Comment by jnfoster** [comment]
@jafingerhut: around-the-clock 30-minute response times... aren't you glad you bought that platinum-level service plan?

Diagnosis: the P4 parser was not correctly managing its symbol table. You can see that nothing changes when it processes a new state: 

https://github.com/p4lang/p4c/blob/master/frontends/parsers/p4/p4parser.ypp#L410

It should push a new namespace. Hence, currently, all P4 parser states are parsed as if they were in the same scope.

**Comment by jnfoster** [comment]
Now why are we managing a symbol table in the parser at all? I think the number GitHub assigned to my PR gives you the answer to that question...

**Comment by jafingerhut** [comment]
@jnfoster The service is great, I agree.  I still can't figure out how to get @mbudiu-vmw to pick an at-most-$50 favorite beverage for me to buy him.  I may have to buy him a gift certificate from BevMo.
