### ISSUE TITLE
p4c bmv2-v1model compiler bug when using typedef for standard_metadata_t

### ISSUE THREAD

**Issue by tomrodeheffer** [p4lang/p4c#677]
I got tired of writing standard_metadata_t on the parameter lists of the various v1model controls that need it.  So I abbreviated by saying

    typedef standard_metadata_t SM;

I expected this would be just fine, since section 7.3 in the 2017-05-22 P4_16 spec says "The two types are treated as synonyms, and all operations that can be executed using the original type can be also executed using the newly created type."

Here is my test file: [smeta.p4.txt](https://github.com/p4lang/p4c/files/1033818/smeta.p4.txt)
p4c says:

    In file: ../backends/bmv2/expression.cpp:239
    Compiler Bug: ../backends/bmv2/expression.cpp:239: Null name

**Comment by hanw** [comment]
This is a regression caused by recent refactoring. Will fix.

**Comment by mbudiu-vmw** [comment]
I think that this has been fixed.
