### ISSUE TITLE
p4c-bm2-ss fails to diagnose all cases of different selector inputs to the same action selector

### ISSUE THREAD

**Issue by tomrodeheffer** [p4lang/p4c#679]
The P4_16 file [keys.p4.txt](https://github.com/p4lang/p4c/files/1033899/keys.p4.txt)  contains two tables that share an action selector.  However, the selector inputs for these two tables are not the same:

    table tbl1 {
        key = {
            meta.a: selector;
            meta.b: selector;
        }
        implementation = as;
        ...
    }

    table tbl2 {
        key = {  // Note: order reversed from tbl1
            meta.b: selector;
            meta.a: selector;
        }
        implementation = as;
        ....
    }

But p4c-bm2-ss is perfectly happy with this invalid situation, producing only spurious warnings about a missing default_action property which is not supported on these tables anyway.

This same lack of diagnosis happens if you REMOVE some of the selector keys from the FIRST table.

Looking at p4c/backends/bmv2/sharedActionSelectorCheck.cpp lines 66 through 75 will show the problem.  The code there is completely incapable of determining whether or not the selector inputs consist of the same key expressions in the same order.  Surely the code ought to read something like:

        uint n = i1.size();
        if (n != i2.size()) return false;
        for (uint k = 0;  k < n;  k++) {
            if (!checkSameKeyExpr(i1[k], i2[k]))  return false;
        }
        return true;

**Comment by antoninbas** [comment]
I agree. Somehow when I wrote this I was under the impression that the field order did not matter, but then it seems that even with this assumption the code is not correct
