### ISSUE TITLE
Register cannot be declared at the top-level

### ISSUE THREAD

**Issue by qizhe** [p4lang/p4c#696]
I use v1model (v1model.p4) to build the program. When I tried to instantiate extern registers at the top-level of my program and read register values at one of actions, I got error:

P4 switch s1 did not start correctly.Check the switch log file.

S1 log:
terminate called after throwing an instance of 'std::out_of_range'
what(): _Map_base::at
Calling target program-options parser

After I changed to declare registers in the ingress control block, I can run my program.
I don't find in P4_16 spec that forbids us to declare extern objects in the top-level.

Sample code from issue242.p4 (only changes the place of declaring registers):

[issue242_revise.txt](https://github.com/p4lang/p4c/files/1050844/issue242_revise.txt)

**Comment by jafingerhut** [comment]
A tiny bit of analysis on the cause of the crash.  If it is true that it should be allowed to declare a regsister at the top level of a P4-16 program, then it appears that p4c is generating and incorrect bmv2 JSON configuration file for the P4 progarm issue242_revise.txt attached above.

I have used versions of p4lang/p4c and p4lang/behavioral-model dated 2017-Jun-03 in my testing.

I used p4c to compile the program issue242_revise.txt.  It generates a bmv2 JSON configuration file that has an empty list for the value of its "register_arrays" key, yet it also generates actions with "register_write" and "register_read" primitives referring to register_array's named "debug" and "reg", as they are named in the P4 program.  This causes behavioral-model's simple_switch program to crash when trying to look up a non-existent register_array with those names.

**Comment by hanw** [comment]
BMV2 backend does not support global register extern right now. A register extern instance must be local to a control block. The compiler should have returned an error in this case. However, we could add support to global extern instance since the spec does not explicitly disallow it.

**Comment by mbudiu-vmw** [comment]
I think that we should write a midend pass which pushes global instantiations into controls/parsers if they are used only within a single control or parser. Then we only need to handle this case in the back end. The p4-14 front-end does something similar for tables.

**Comment by cc10512** [comment]
Not sure I understand your comment. You need to handle the global instance if it is used in multiple controls regardless.

**Comment by mbudiu-vmw** [comment]
Many architectures will not support registers shared between different control/parser blocks.
Whether BMv2/PSA do or not it is a matter of choice.

**Comment by mbudiu-vmw** [comment]
This seems to be closeable.
