### ISSUE TITLE
Q: How could I define my own match kind?

### ISSUE THREAD

**Issue by Wasdns** [p4lang/p4c#697]
Hello.

Thank you for your great works on the p416 specification and p4c compiler. I have a little question about the specification: How could I define my own match kind and compile it? I overviewed the specification and found:

> Architectures may support additional match_kinds. The declaration of new match_kinds can only occur within model description files; P4 programmers cannot declare new match kinds.

But what puzzled me is that in the dir ` p4c/p4include`, the `p4d2model.p4` shows a new match kind named `range`. I think there may be a way to add my own definition of match kind into my model description file(is it a p4 file?). 

Could you help me with it? If so, thank you very much!

**Comment by mbudiu-vmw** [comment]
Mechanically it is very simple to declare a new match_kind, it looks much like an enum.
It does not make sense for users to declare new match_kinds, such declarations should be part of a target architecture description. Architecture declarations come together with custom compiler back-ends; if an architecture file contains a new match_kind, then the back-end is supposed to support it. In fact v1model.p4 comes with 2 new match kinds: selector and range.

To answer your question: you can add a new match kind only if you are prepared to create/modify a back-end to support it.

**Comment by cc10512** [comment]
In order to support different match kinds you need to:
1. Define a new architecture that introduces the match kind
2. Implement support for the match kind in bmv2 (or whatever target you are planning to run on). If you chose bmv2, then you need to define the json information required for the new match kind.
2. Implement support in the compiler backend to generate the corresponding json information (if bmv2) or machine code if a different target.

**Comment by Wasdns** [comment]
@mbudiu-vmw @cc10512 
Thank you very much! The information is very helpful with my work.
BTW, is there an example that illustrates the two new match kinds? I could understand the meanings but still not very familiar with them. How to write the corresponding runtime commands to populate the table which used the two match kinds?

**Comment by mbudiu-vmw** [comment]
The "range" match_kind is the equivalent to the P4-14 range match_kind; the control-plane can specify an interval of integer values through two endpoints. When you initialize such a table in P4 you use the 10..12 syntax to specify a range.

The "selector" match_kind is used to implement dynamic action selection, another P4-14 feature, described in Section 10 of the P4-14 specification. This document https://github.com/p4lang/p4-spec/blob/master/p4-16/discussions/migration-guide.pptx shows a translation from P4-14 to P4-16 using this match_kind (on slide 39).

Remember, v1model is there solely to provide compatibility to P4-14, so everything in v1model is there to model some feature of P4-14.

**Comment by mbudiu-vmw** [comment]
BTW: I don't think you can populate a table with "selector" match kinds in P4. In fact, tables with action selectors have really special implementations (with or without a "selector" match_kind), so it is not obvious that the initializers even make sense for them. @cc10512 : this is probably something we should have a test for.

**Comment by Wasdns** [comment]
@mbudiu-vmw Thank you very much! 👍
