### ISSUE TITLE
p4c-bm2-ss compiler bug: could not convert Checksum16 to Json

### ISSUE THREAD

**Issue by tomrodeheffer** [p4lang/p4c#741]
I wrote the following program to try out the Checksum16 extern: [checksum.p4.txt](https://github.com/p4lang/p4c/files/1104224/checksum.p4.txt)
But p4c-bm2-ss says:

```
In file: ../backends/bmv2/expression.cpp:82
Compiler Bug: checksum.p4(38): ck_1/ck;: could not convert to Json
    hdr.h.cksm = ck.get(hdr.h);
                 ^^
```

Is Checksum16 supported in p4c-bm2-ss?  If not, I would expect to see some remark about that in the documentation and a better error message from the compiler.

**Comment by mbudiu-vmw** [comment]
The documentation is really lacking, indeed.
Checksums can be only instantiated in the verifyChecksum and updateChecksum controls.
The error message is bad, so we'll keep this as a bug.

**Comment by jafingerhut** [comment]
I was running a test case yesterday with someone using v1model.p4 using the 2017-Jun-19 latest versions of p4c-bm2-ss and p4lang/behavioral-model's simple_switch, and it seems that nothing in the verifyCheckum and updateChecksum controls is executed in simple_switch.  Not 100% sure, but we had some evidence pointing that way.

**Comment by mbudiu-vmw** [comment]
BMv2 ignores checksum verify statements, even in P4-14.
If the update does not work then you can't really modify IPv4 headers.
We have issue #655, which still seems to be open. @hanw assigned himself for this one.

**Comment by antoninbas** [comment]
Actually bmv2 now logs an error message if a packet has an invalid checksum, but does not drop the packet. This was implemented a couple months ago.

**Comment by mbudiu-vmw** [comment]
I hope that the new checksum APIs in v1model make this a non-issue,
