### ISSUE TITLE
Type Checking for Constant Arguments

### ISSUE THREAD

**Issue by orenbenkiki** [p4lang/p4c#754]
**Issue:**

Currently, there is no type checking when passing a constant value to a control. For example:

```
control ctl(bit<3> v) { ... }
...
ctl(12345);
...
```
 
Will not be flagged as an error by `p4test`. However, using a named constant:

```
const bit<3> V = 12345;
```

Is correctly flagged as an error.

**Proposal:**

Perform for arguments the same verification for constant that is done today when defining constants.

**Comment by mbudiu-vmw** [comment]
This is a warning, not an error.
However, this is indeed a bug, the typechecker does not seem to look at constructor arguments until very late. In consequence, the following program crashes the compiler:

```
control c(out bit<3> x)(bit<3> v) { apply { x = v; } }

control ctrl(out bit<3> _x);
package top(ctrl c);

top(c(12345)) main;
```

**Comment by mbudiu-vmw** [comment]
@orenbenkiki : I will close this issue; please re-open if you think the fix is not good.
