### ISSUE TITLE
Name mangling in P4_14 to P4_16 converter

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#756]
The attached file, which is legal P4_14, fails when converted to P4_16 using `p4c`. 
```
% p4c-bm2-ss --p4-14 clone.p4 
clone.p4(1): error: header clone: Duplicates declaration clone
header_type clone {
^
v1model.p4(138)
extern void clone(in CloneType type, in bit<32> session);
            ^^^^^
error: 1 errors encountered, aborting compilation
```
@ChrisDodd says that the mangler should take care of the name clash, but it is not currently doing so.

[clone.txt](https://github.com/p4lang/p4c/files/1118420/clone.txt)

**Comment by jafingerhut** [comment]
Perhaps related to this issue?  https://github.com/p4lang/p4c/issues/486

**Comment by mbudiu-vmw** [comment]
This is superseded by #780. Let's close this one.
