### ISSUE TITLE
crash using tuple argument type.

### ISSUE THREAD

**Issue by ChrisDodd** [p4lang/p4c#759]
A slight variation of the tuple1.p4 test program crashes in typechecking:
```
extern void f(in tuple<bit<32>, bool> data);

control proto();
package top(proto _p);

control c() {
    tuple<bit<32>, bool> x = { 10, false };
    apply {
        f(x);
    }
}

top(c()) main;
```
running with p4test gives:
```
$ ./p4test tuple0.p4
Error compiling
In file: ../../p4c/frontends/p4/typeChecking/typeChecker.h:101
Compiler Bug: Could not find type of struct tuple_0 {
  bit<32> field;
  bool field_0; }
```

**Comment by mbudiu-vmw** [comment]
My guess is that the pass that converts tuples to structs inserts the struct after the first use.

**Comment by ChrisDodd** [comment]
The crash happens in TypeInference::postorder(IR::Type_Name* typeName)
It seems to be finding the declaration ok (gets it from the refmap) -- the problem is when it tries to get the Type_Type of the declaration from the typeMap; the decl is not in the typeMap so gives that BUG

**Comment by mbudiu-vmw** [comment]
@ChrisDodd : I will close this, please re-open if not satisfied.
