### ISSUE TITLE
Future extension: Convenient initialization of header/structs

### ISSUE THREAD

**Issue by orenbenkiki** [p4lang/p4c#762]
Implement https://github.com/p4lang/p4-spec/issues/341 - at least as an option - to promote its acceptance into the spec. That is, allow:

```
header_or_struct = {};
```

To initialize all the leaf fields to 0 (or `false` for a Boolean, or zero length for `varbit`).

**Comment by marko-stanoj** [comment]
Is there any particular reason why structs and headers, that are declared and initialized at the same time, are not processed by StructInitializer pass in frontend?

For example:
Bool_int_hdr hdr = { false, 0 };
this kind of initialization would not be processed by StructInitializer pass,

Bool_int_hdr hdr;
hdr = { false, 0 };
but this kind of initialization would.

Wouldn't it be better to visit those assignments after MoveInitializers pass, so they get the same treatment?

Second question is, is it even possible to set dynamic length of varbit in compile time and initialize it to zero length? I'm on the right track to solve this issue and answers on this question would help me a lot.

**Comment by mbudiu-vmw** [comment]
Please do not ask two different questions in a single issue.
We need to run StructInitializer as early as possible. MoveInitializers has a few other dependencies.
You are welcome to try to reorganize them.
If StructInitializer does not process declaration intializers this should be a bug which you can probably highlight using a specific test case.

There is no operation to set the length of a varbit field.

**Comment by mbudiu-vmw** [comment]
BTW: we should first settle on the syntax for doing initialization. I would prefer something like `{ ... }`.

**Comment by Jovana-Syrmia** [comment]
I'm currently working on adjusting  PR #2368 (referencing this issue) to work with the current main.
Is default initialization addition still needed?

**Comment by mbudiu-vmw** [comment]
Yes, it is still needed. Thank you.
