### ISSUE TITLE
P4_14 to P4_16 conversion: exact

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#767]
The identifier `exact` is not a keyword or reserved, according to the P4_14 specification. And indeed the following program compiles fine with the Python compiler:
```
parser start {
    return ingress;
}

action nop() { }
    
table exact {
    reads { standard_metadata.egress_port: exact; }
    actions { nop; }
}

control ingress {
  apply(exact);
}
```

However, when compiled with the C++ compiler, I get an error:
```
/Users/nate/exact.p4(7): warning: .exact shadows exact
table exact {
^
/Users/nate/./shared/bf-p4c-compilers/build/p4c/p4include/core.p4(75)
    exact,
    ^^^^^
error: Cannot extract field apply from exact which has type match_kind
/Users/nate/exact.p4(13): error: Could not find type of exact.apply
  apply(exact);
```
There are several issues, corresponding to each error message.

1. It's not clear that a table name should every be considered to shadow a match_kind since these are really different kinds (in the type theoretic sense).

2. I have no idea what the "Cannot extract..." error means. My program contains no field projections other than `standard_metadata.egress_port`.

3. If the table `exact` does shadow the match kind of the same name, per the first error, then why can't the compiler find the definition when it is used in the `ingress` control? It seems like the internal data structures which hold identifiers and types are not keeping track of scope consistently -- i.e., there's a deeper issue here that this test is exposing.

**Comment by mbudiu-vmw** [comment]
I think that this is just another instance of #780, with a different error message.

**Comment by jnfoster** [comment]
Correct. I might keep this one open though because the error messages are different which suggests a possibly different symptom.

**Comment by jafingerhut** [comment]
@jnfoster The P4_16 spec says this about match_kind names: https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/P4-16-spec.mdk#L1754-L1755

"All identifiers are inserted into the top-level namespace."

That seems to suggest to me that in a P4_16 translation of your example, the table name 'exact' would _should_ sadow the match_kind name 'exact' (shadow because P4_16 tables cannot be declared at the top level, only within control blocks, so it is "nested" inside the top level and names there can shadow top level names).

**Comment by jnfoster** [comment]
Right, but the error message 
> warning: .exact shadows exact
goes the other way around, doesn't it?

I guess it depends what ".exact" refers to. I thought that was the notation for the top-level declaration (i.e., the match-kind).

**Comment by mbudiu-vmw** [comment]
When converting from p4-14 to p4-16 we can change the names of the objects (while adding proper name annotations). Then this problem should not occur. I am working on a patch based on @cc10512 's PR.

**Comment by jnfoster** [comment]
Right. We were wondering if there's another bug -- if something is backwards it might be an indication that there's an issue we'll no longer see if we fix the name mangling.

**Comment by mbudiu-vmw** [comment]
I will close this issue; please re-open if you think it is not satisfactorily solved.
