### ISSUE TITLE
Compiler crashes when operations are applied to variable-length fields

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#776]
Compiling this program,
```
header_type h_t {
  fields {
    f : 8;
    g : *;
  }
  length : f;
  max_length : 32;
}

header h_t h;

parser start {
  extract(h);
  return ingress;
}

action a() {
  add_to_field(h.g, 1);
}    
    
table t {
  actions { a; }
  default_action: a;
}        

control ingress {
  apply(t);
}    
```
crashes pretty hard:
```
% ./p4c/build/p4c-bm2-ss --p4-14 variable.p4
libc++abi.dylib: terminating with uncaught exception of type Util::CompilerBug: In file: ../ir/expression.cpp:51
Compiler Bug: 1: Unexpected type for constant varbit<0>

Abort trap: 6
```

**Comment by mbudiu-vmw** [comment]
This is subsumed by #781.
I will close this one.

**Comment by jnfoster** [comment]
Actually, I think this may be a different bug. #781 is about incorrect instructions in the Bmv2 configuration generated by the compiler. This bug is about what happens when using a variable-length field in a control. And the symptoms are different -- here the compiler crashes. Note that the `add_to_field` is problematic because one of the operands has a type that is only known dynamically. Probably this should just be considered illegal -- that's what the Python compiler now does.
