### ISSUE TITLE
p4c-bm2-ss compile simple_router.p4 error

### ISSUE THREAD

**Issue by dingrui37** [p4lang/p4c#778]
```
hll@hll:/home/opendaylight/p4lang/behavioral-model/mininet$ p4c-bm2-ss simple_router.p4 --p4runtime-file simple_router.proto.txt --p4runtime-format text
simple_router.p4(16):syntax error, unexpected IDENTIFIER "header_type"
header_type
^^^^^^^^^^^
error: 1 errors encountered, aborting compilation
hll@hll:/home/opendaylight/p4lang/behavioral-model/mininet$ p4c-bm2-ss simple_router.p4 --toJSON simple_router.json
simple_router.p4(16):syntax error, unexpected IDENTIFIER "header_type"
header_type
^^^^^^^^^^^
error: 1 errors encountered, aborting compilation
hll@hll:/home/opendaylight/p4lang/behavioral-model/mininet$ 
hll@hll:/home/opendaylight/p4lang/behavioral-model/mininet$ p4c
p4c         p4c-bm2-ss  p4c-bmv2    p4c-ebpf    
hll@hll:/home/opendaylight/p4lang/behavioral-model/mininet$ p4c-bmv2 simple_router.p4 --json simple_router.json
parsing successful
semantic checking successful
Header type standard_metadata_t not byte-aligned, adding padding
WARNING:p4c_bm.gen_json:The P4 program defines a checksum verification on field 'ipv4.hdrChecksum'; as of now bmv2 ignores all checksum verifications; checksum updates are processed correctly.
Generating json output to /home/opendaylight/p4lang/behavioral-model/mininet/simple_router.json
```

**Comment by jafingerhut** [comment]
Without extra command line options, p4c-bm2-ss expects the P4 programs
given to it to be P4_16 syntax, not P4_14 syntax.  I am guessing your
program simple_router.p4 uses P4_14 syntax because the error message
complains about the presence of "header_type", which is a keyword in P4_14,
but not in P4_16.

Try a command like this instead, where the option "--p4v 14" specifies that
the P4 program uses P4_14 syntax.

    p4c-bm2-ss --p4v 14 simple_router.p4

Andy

**Comment by dingrui37** [comment]
Thank you for taking the time to help @jafingerhut . According to your advice, it works. But there is a warning, I wonder if it is a problem?
```
hll@hll:/home/opendaylight/p4lang/behavioral-model/mininet/tt$ p4c-bm2-ss --p4v 14 --p4runtime-file tt.proto.txt --p4runtime-format text --toJSON s.json simple_router.p4 
simple_router.p4(107): warning: -1: negative value with unsigned type
    add_to_field(ipv4.ttl, -1);
                            ^

```

**Comment by jafingerhut** [comment]
@dingrui37 I have seen this kind of warning involving adding negative values.  I haven't encountered a situation where that warning causes incorrect behavior before.  If you change 'add_to_field(ipv4.ttl, -1);' to 'subtract_from_field(ipv4.ttl, 1);' the warning should go away.  In one small P4_14 program where I made this change, the resulting bmv2 JSON configuration file produced by the compiler was identical for two programs that were the same except for that one change, so I suspect the warning is harmless here.

**Comment by dingrui37** [comment]
@jafingerhut  Are the p4runtime files generated by the two programs identical ?

**Comment by jafingerhut** [comment]
I did not check, and I would prefer not to take the time right now to
figure out how to generate the p4runtime files and verify.  The
add_to_field -> subtract_from_field changes in the P4_14 program are pretty
easy for you to make and do a 'diff' on the resulting p4runtime files
before and after, I hope?

**Comment by jafingerhut** [comment]
Plus, I would hope that the p4runtime file contents are only affected by
the search keys of the tables, and the action names, and the action
parameter names and bit widths, not the primitive actions invoked inside of
the actions.  The primitive actions used _should_ have no affect on the
control plane API of a P4 program.

**Comment by dingrui37** [comment]
I really appreciate your help.
