### ISSUE TITLE
p4c-bm2-ss generates wrong code for header validity

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#783]
This is from an email exchange on the p4-dev mailing list.
It looks like the bug is in the parser.cpp file, in convertParserStatement, the handling of the BuiltInMethod, where the "set" json operation is used to modify the validity instead of add_header or remove_header.

**Comment by antoninbas** [comment]
See http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2017-July/001212.html for the details

**Comment by mbudiu-vmw** [comment]
I tried to fix this, but bmv2 seems to reject add_header in a parser.
Is there any workaround?

**Comment by antoninbas** [comment]
Did you try the same json as what in the email? Because editing the json manually with that works for both Regis and I. Any primitive action can be invoked from the parser, unless you have a fairly old bmv2 version.

**Comment by cc10512** [comment]
Fixed by #787
