### ISSUE TITLE
p4test generates invalid "source_fragment" value in JSON file

### ISSUE THREAD

**Issue by brmarci** [p4lang/p4c#785]
I tried to generate JSON output using p4test from various P4 sources, but there are some `"source_fragment"` fields that are set to `"""` resulting in an invalid JSON file.

When running
`./p4test -I p4include/ ../testdata/p4_16_samples/vss-example.p4 --p4v 16 --toJSON temp.json`
the result file contains the following (from line 7067 to 7080):
```
                {
                  "Node_ID" : 90149,
                  "Node_Type" : "StringLiteral",
                  "type" : {
                    "Node_ID" : 3906
                  },
                  "value" : "NoAction",
                  "Source_Info" : {
                    "filename" : "/home/brmarci/work/p4/p4c/build/p4include/core.p4",
                    "line" : 67,
                    "column" : 15,
                    "source_fragment" : """
                  }
                }
```

Also when generating JSON from a P4_14 source file, there are similar problems referencing p4include/v1model.p4.

**Comment by cc10512** [comment]
Fixed by #786
