### ISSUE TITLE
ir-generator bison grammar has conflicts

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#791]
I noticed this while building the compiler:
```
[ 10%] [BISON][IRgenParser] Building parser with bison 3.0.4
ir-generator.ypp: warning: 4 shift/reduce conflicts [-Wconflicts-sr]
```

**Comment by mbudiu-vmw** [comment]
@ChrisDodd : the IR generator grammar has conflicts, maybe you would like to take a look.

**Comment by ChrisDodd** [comment]
Its on my list of things to look at when I get a spare moment -- preliminary looks like its just an ambiguity in the grammar used and the default resolution (shift) works out, but, like compiler warnings, this is something I would like to clean up.

**Comment by sskausik08** [comment]
This issue should be fixed. @mbudiu-vmw can you check this and close?

**Comment by mbudiu-vmw** [comment]
I trust @ChrisDodd's review , so I will close this.
