### ISSUE TITLE
p4test gives error when calling method on extern instance that was passed as argument

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#794]
When attempting to compile the attached program extern-ref.p4 (plus the file psa-local-copy.p4 that it #include's, also attached) using the latest version of p4test as of 2017-Jul-19, I get this error:
```
extern-ref.p4(70): error: Could not find declaration for rand
        my_headers.ethernet.srcAddr[47:38] = ~rand.read();
                                              ^^^^
```
It appears that this should be a legal P4_16 program, for which the compiler should not give any errors.  Some further discussion on this p4-spec issue: https://github.com/p4lang/p4-spec/issues/361

[extern-ref.p4.txt](https://github.com/p4lang/p4c/files/1181595/extern-ref.p4.txt)
[psa-local-copy.p4.txt](https://github.com/p4lang/p4c/files/1181597/psa-local-copy.p4.txt)

**Comment by mbudiu-vmw** [comment]
This is a bug in the inliner.

**Comment by mbudiu-vmw** [comment]
I will assume that we can close this one.

**Comment by jafingerhut** [comment]
Confirmed that my example test program that gave the error with the older version of p4test, now compiles with no errors using the latest version of p4test as of 2017-Oct-23.  Thanks for the fix.
