### ISSUE TITLE
Using digest on bmv2-ss-p4org creates learn_id = 0 

### ISSUE THREAD

**Issue by ygottlieb-vencorelabs-com** [p4lang/p4c#801]
In order to better understand the P4 language and the behavioral model, I've tried to translate the l2_switch.p4 into P4-16 and execute that in the simple_switch model.  The program is attached at [l2_switch.txt](https://github.com/p4lang/p4c/files/1182973/l2_switch.txt).

I'm using the latest P4c (master from Wednesday 2017-07-26) and compiling with:

p4c -v -b bmv2-ss-p4org l2_switch.p4

I've noticed an oddity that if I have the call to the extern digest() only once, the simple switch does not send it to the learning client, but will if I have it twice.  I suspect that the reason is that the JSON file has the parameters to digest as:

        {
          "op" : "generate_digest",
          "parameters" : [
            {
              "type" : "hexstr",
              "value" : "0x00000001"
            },
            {
              "type" : "hexstr",
              "value" : "0x0"
            }
          ]
        },

specifically that the second parameter is 0 and that the second parameter is taken as the learn_id in primitives.cpp:165.  In simple_switch.cpp:377, learn_id == 0 is taken to mean no learning.  This may be similar to issue #380, but still exists in the latest master of both p4c and behavioral-model.

**Comment by mbudiu-vmw** [comment]
If you manually replace the 0x0 with 0x1 the program works correctly?

**Comment by mbudiu-vmw** [comment]
@ygottlieb-vencorelabs-com : Can you please see if the PR #824 fixes this issue?

**Comment by ygottlieb-vencorelabs-com** [comment]
@mbudiu-vmw 
PR #824 fixes the problem in my setup.  Thank you very much!

**Comment by mbudiu-vmw** [comment]
If this is fixed perhaps we can close this issue.

**Comment by ygottlieb-vencorelabs-com** [comment]
Agreed.
