### ISSUE TITLE
how to set table entries for tables in multiple p4 files?

### ISSUE THREAD

**Issue by qizhe** [p4lang/p4c#805]
I have two P4 files: simple_router.p4 and execution.p4; execution.p4 contains one control block: control block "execution". In simple router.p4, my ingress control block calls execution.apply().

But I cannot add table entries for tables in "execution" control block in command.txt.  I got the error:
RuntimeCmd: Error: Invalid table name (linear_count_exact)

How can I do that????

[test.zip](https://github.com/p4lang/p4c/files/1185220/test.zip)

**Comment by qizhe** [comment]
Solved. It turns out I have to add the instance name before the table name.
Example:
table_set_default e.linear_count_exact NoAction

e is my instance name.

**Comment by jnfoster** [comment]
Okay, closing this.
