### ISSUE TITLE
Add parser_error field to v1model standard metadata

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#808]
This is a proposal to extend v1model's standard metadata with a `bit<X> parser_error` field. The v1model architecture would assign integral values in the appropriate range to each parser error and set this metadata field to the appropriate value so it can be consumed by the ingress control.

I know that such a feature will be available in PSA, but it will take some time to bring PSA software to the level where it can fully replace v1model / bmv2 simple_switch. This enhancement will enable P4 programmers to use parser errors today, with minimal changes in the existing software.

**Comment by mbudiu-vmw** [comment]
This has been merged: the v1model standard_metadata_t now has such a field, so I will close this.

**Comment by antoninbas** [comment]
I'm reopening this.
I see a `checksum_error` 1-bit field now, but that's not the same as a general error field to which one can write any possible parser error code.
