### ISSUE TITLE
Compiler Bug: expected method call

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#816]
Compiling this program 
```
#include <core.p4>

// Architecture    
control C();
package S(C c);
extern BoolRegister {
  BoolRegister();
  bool get();
  void flip();
}

// User Program
BoolRegister() r;
    
action a(in C c1, in C c2) {
  r.flip();
  if(r.get()) {
    c1.apply();
  } else {
    c2.apply();
  }
}

control MyC1() {
  apply {
  }
}
control MyC2() {
  apply {    
  }
}
control MyC3() {
  apply {
    a(MyC1(), MyC2());
  }
}

S(MyC3()) main;
```
crashes with a compiler bug:
```
In file: p4c/frontends/p4/simplifyDefUse.cpp:526
Compiler Bug: cyclic.p4(34): MyC1();: expected method call
    a(MyC1(), MyC2());
      ^^^^^^
```

**Comment by jnfoster** [comment]
Probably related... also compiling the following program
```
#include <core.p4>

// Architecture    
control C();
package S(C c);

// User Program
package P(C c1, C c2);

control Dummy() {
  apply { }
}    
    
control MyC1()(P p) {
  apply {
  }
}
control MyC2()(P p) {
  apply {
  }
}        
control MyC3() {
  Dummy() d;
  P(d,d) p;
  C c1 = MyC1(p);
  C c2 = MyC2(p);
  apply {
    c1.apply();
  }
}

S(MyC3()) main;
```
crashes with a compiler bug:
```
In file: p4c/frontends/p4/simplifyDefUse.cpp:526
Compiler Bug: cyclic.p4(25): MyC1(p_0/p);: expected method call
  C c1 = MyC1(p);
         ^^^^^^^
```

**Comment by jafingerhut** [comment]
Question: Is there any _use_ in having a package as a constructor parameter of a control or parser?

Suppose it were legal P4_16.  A control can call apply on a control given to it as a constructor parameter, or do method calls on an extern instance passed to it as a constructor parameter.  Similarly a parser can do that for other parser instances or extern instances.

But what can a control _do_ with a package instance passed to it?  I can't think of anything.

**Comment by jnfoster** [comment]
I don't think so. 

I was just poking around comprehensively through all of our various type constructs, @jafingerhut style, to see what the current compiler does. ;-)

**Comment by jafingerhut** [comment]
Thanks for your diligence and experimentation.  I'm making notes for PSA limitation ideas, at least, if not for P4_16 in general.

**Comment by mbudiu-vmw** [comment]
This will be fixed by 
- forbidding packages as parameters to anything which is not a package
- forbidding controls/externs/parsers as parameters with direction
A PR is upcoming.

**Comment by cc10512** [comment]
@mbudiu-vmw: I think it would be worthwhile to stop and think a bit about this, so we can come up with a specified set of rules of what goes where. I understand your urge to cleanup the current fixes, but as we've seen, adding more examples will add more issues. Should we just sit together and workout what is the behavior we want for each of these entities? Write it down and then implement it?

**Comment by mbudiu-vmw** [comment]
There is a general rule: compile-time objects are not designed to be passed as arguments or returned as results; they are not first-class objects. The rule is not enforced by the type-checker; there will be several small fixes. All of these fixes are necessary; none of them is ad-hoc.

**Comment by jafingerhut** [comment]
@mbudiu-vmw To clarify slightly, by "not designed to be passed as arguments" you mean "not designed to be passed as _run time_ arguments", yes?

They are designed to be passed as compile-time arguments in many cases (e.g. a control being passed to a control as a compile-time parameter).

**Comment by mbudiu-vmw** [comment]
None of the practical use cases that I know of requires one to pass controls or parsers as arguments, not even as constructor arguments, except as arguments to packages. So my preference would be to forbid this, and relax the rule later if a practical use-case arises.

**Comment by sethfowler** [comment]
I disagree. It'll restrict the opportunities for modularity and composability a lot if we can't pass controls and parsers as constructor arguments.

**Comment by cc10512** [comment]
There is an absolutely clear case for enabling this: modularity. We can not expect that all P4 programs will be written from scratch, and to enable extensibility, we will have to be able to pass controls and parsers.

**Comment by mbudiu-vmw** [comment]
I would first like to see at least one example program where one needs to pass a control as an argument.
We have discussed modularity briefly, and we have agreed that the language does not have enough mechanisms for writing modular programs. I am not convinced that allowing such arguments will actually provide any real software-engineering benefits.

**Comment by mbudiu-vmw** [comment]
Even so, please note that none of the fixes submitted recently prohibits passing controls or parsers as directionless arguments. There is absolutely no reason to pass a package as an argument anywhere except to a package. So currently I haven't introduced any new restrictions compared to the spirit of the spec.
