### ISSUE TITLE
Type checking for headers initialized by tuples/lists broken.

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#841]
The P4_16 spec states:

> A header object can be initialized with a list expression, similar to a struct—the list fields are assigned to the header fields in the order they appear. In this case the header automatically becomes valid:
```
header H { bit<32> x; bit<32> y; }
H h;
h = { 10, 12 };  // This also makes the header h valid
```
However, the p4c compiler rejects the following program:
```
#include <core.p4>
#include <v1model.p4>

header h_t {
  bit<32> src;
  bit<32> dst;
  bit<16> csum;
}

struct metadata {
}
struct headers {
  h_t h;
}

parser MyParser(packet_in packet, out headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
    state start {
        packet.extract(hdr.h);
        transition accept;
    }
}
control MyVerifyChecksum(in headers hdr, inout metadata meta) {
    apply {
    }
}
control MyIngress(inout headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
    apply {
    }
}
control MyEgress(inout headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
    apply {
    }
}
control MyDeparser(packet_out packet, in headers hdr) {
    apply {
    }
}
control MyComputeChecksum(inout headers hdr, inout metadata meta) {
    Checksum16() checksum;
    h_t h = { hdr.h.src, hdr.h.dst, 16w0 };
    apply {
	hdr.h.csum = checksum.get(h);
   }    
}
V1Switch(MyParser(), MyVerifyChecksum(), MyIngress(), MyEgress(), MyComputeChecksum(), MyDeparser()) main;
```
with this error:
```
foo.p4(40): error: AssignmentStatement: Number of fields 3 in initializer different than number of fields in structure 4: Tuple(3) to header h_t
    h_t h = { hdr.h.src, hdr.h.dst, 0 };
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
foo.p4(40)
    h_t h = { hdr.h.src, hdr.h.dst, 0 };
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
foo.p4(4)
header h_t {
       ^^^
```
(The compiler also rejects the example given in the spec with a similar error message.)

**Comment by sethfowler** [comment]
Is this specific to the BMV2 backend? I wonder if this problem is introduced when we add an explicit valid bit to the struct type. That's something that happens in the BMV2 mid end, but we don't do it for the other backends.

**Comment by jnfoster** [comment]
Yes, that seems likely! The program is accepted by p4test but triggers the
error with p4c-bm2-ss.

Good catch!

-N

**Comment by jnfoster** [comment]
It's also worth noting that this is truly a compiler bug and not, say a type error. The program does typechecking initially, but the transformations done by the compiler produce an ill-typed program. If we're going to run the typechecker multiple times, we should be sure that the later passes indicate that the error is a compiler bug and not an error in the program.

For reference, the check that fails is here:
https://github.com/p4lang/p4c/blob/12b6db763181fa45cb490d63ded66e0fabcfe7cf/frontends/p4/typeChecking/typeUnification.cpp#L255

**Comment by mbudiu-vmw** [comment]
The back-end should not be allowed to run the type-checker after the structure of the headers has been changed - the program IR is no longer a correct representation of the program. This should be one of the last things done before JSON generation. I will assign this to @sethfowler , since I believe that he wrote the code that added explicitly the valid fields.

**Comment by sethfowler** [comment]
We will find it difficult to guarantee that the type checker never gets rerun after this transformation, I think.

Why aren't we just lowering this kind of assignment into a sequence of assignments to individual fields and a call to `setValid()`?

**Comment by mbudiu-vmw** [comment]
Yes, we could lower the assignment; there is some code doing something similar for eliminating nested structs. But I am worried that there are other cases to worry about. The IR is indeed "invalid" at this point, so the rest of the back-end becomes brittle after this transformation. We should document this as well in the code.

**Comment by sethfowler** [comment]
Yeah, it makes me a bit nervous too. I can implement a short term fix here, but longer term I suspect we'd be better off with another approach to desugaring `isValid()`; I'll come back to this later and try to put together a better design.

**Comment by mbudiu-vmw** [comment]
This issue is hopefully fixed.
