### ISSUE TITLE
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):

### ISSUE THREAD

**Issue by guyuehu7** [p4lang/p4c#842]
Hello,
 I am new to p4.
 I tried to run ./bootstrap.sh  and i got below error.

CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Protobuf (missing: PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR)
  (Required is at least version "3.0.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindProtobuf.cmake:308 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:39 (find_package)

**Comment by cc10512** [comment]
You need to install protobuf 3.0 as explained in the README.md file: 

An exception is Google Protocol Buffers; p4c depends on version 3.0, which is not available until Ubuntu 16.10. For earlier releases of Ubuntu, you'll need to install from source. You can find instructions here. Check out the newest tag in the 3.0 series (v3.0.2 as of this writing) before you build.

git checkout v3.0.2

Please note that while newer versions should work for p4c itself, you may run into trouble with some extensions unless you install version 3.0, so you may want to install from source even on newer releases of Ubuntu.
