### ISSUE TITLE
Use of unexported GC library variables in lib/gc.cpp

### ISSUE THREAD

**Issue by DGeorgeNetro** [p4lang/p4c#844]
Both GC_start_call_back and GC_print_stats are not declared as part of the GC library API, ie marked with GC_API and should not be used. There are coincidentally available on Linux libraries and are not available on Windows (either native or MSYS2). This issue was encountered when attempting to compile on a Windows system.

Since GC 7.2 there is an API for setting the start callback, GC_set_start_callback(). I see no solution for the GC_print_stats issue other than to ifdef macros to prevent error in the cases where it definitely can't by used ie on windows.

**Comment by DGeorgeNetro** [comment]
PR #845 created to fix this issue

**Comment by DGeorgeNetro** [comment]
the above pull request was incomplete, I will resubmit a complete one.

**Comment by DGeorgeNetro** [comment]
Second attempt at a fix PR #849

**Comment by mbudiu-vmw** [comment]
Can we close this issue?
