### ISSUE TITLE
p4_14 to p4_16 conversion of boolean expressions

### ISSUE THREAD

**Issue by cc10512** [p4lang/p4c#846]
Conversion of P4_14 boolean expressions of the form `pkt.valid == 1` give an error: `error: ==: not defined on bool and int`. To address this issue, we propose that the converter turns these expressions into the simple test of the boolean expression.

**Comment by jnfoster** [comment]
In revision 1.0.4, we added `hdr.valid` as a pseudo-field that can be matched in the table. The primary motivation, if I recall correctly, was to allow matching on validity bits using tables with match kinds other than exact (e.g., ternary). I don't believe we added `hdr.valid` as a general expression although (i) I might be wrong and (ii) it might have been sensible to do so. 

To play devil's advocate: would it be simpler just to tighten up P4_14 front-ends to reject `hdr.valid` an expression and force programmers to use `valid(hdr)` instead?

**Comment by cc10512** [comment]
I have considered that, as well as relaxing the check in typeChecker to allow for comparisons to 1 or 0. However, there is a whole set of legacy code in P4_14 that will need to change since the compiler suddenly rejects it.  I don't think that's a workable path, especially whne adjusting the converter is such a trivial change.
