### ISSUE TITLE
variable used before declaration

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#862]
The current implementation in p4c infers use-before-declare from the line number (which is a monotonically increasing counter) when 'include' the source p4 program. This becomes a problem when I try to translate a program from v1model to PSA model. During the translation, the compiler reads the psa.p4 and prepended the declarations in the psa.p4 to the translated user program. However, all type declarations in psa.p4 actually happen after the use in the program because the psa.p4 file is read after the original program p4 file. Type inference fails when the isV1 flag is set to true, which disallow use-before-declare.

I can work around the issue by setting the isV1 flag to false, but it does not seem to be a proper solution to the issue.

**Comment by mbudiu-vmw** [comment]
You should make sure that the translated program includes psa.p4 before using it.
How are you translating from v1model to PSA?

**Comment by hanw** [comment]
It goes through a few steps:
1. read in v1model.p4, save all type names in an auxiliary data structure.
2. read in the program that uses v1model.p4, filter out the type declaration from v1model.p4 based on the auxiliary data structure.
3. a number of passes to translate the usage of v1model extern to the corresponding psa externs.
4. read in the psa.p4, prepend all declarations to the declaration from step 3.
5. create a new P4Program IR node using the output from step 4.

**Comment by mbudiu-vmw** [comment]
So you have a special compiler.
Why not just dump the programs as P4-16 and then manually edit them once and for all?

Anyway, perhaps you want to topologically sort the type dependences and dump them in order in the output.

**Comment by mbudiu-vmw** [comment]
I would not say that this is an issue with the compiler really.
