### ISSUE TITLE
Stale v1model.p4

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#864]
The build system does not notice when model files are updated and tests can run with out-of-date models.

**Comment by ChrisDodd** [comment]
There's a general "issue" with the cmake-generated makefiles that "make check" and "make recheck" don't actually rebuild anything before running tests, so you generally need to run "make && make check", or you might be running tests with out-of-date programs and files.

**Comment by mbudiu-vmw** [comment]
Even if I do make, it won't install new models. 
Can we have check depend on one of the main targets?

**Comment by ChrisDodd** [comment]
There's also an issue that if you've ever run "make install" it will prefer the installed header files over any updated header files that may be present in the build tree; this seems like a bug in the p4c driver program to me.

**Comment by mbudiu-vmw** [comment]
This should be fixed by #866.
