### ISSUE TITLE
Adding P4 Slice to EBPF backend causes extra text in Slice statement line 

### ISSUE THREAD

**Issue by familysingh** [p4lang/p4c#870]
I am using a modified EBPF backend to shoehorn P4 Slice code into this backend.  I have modified this file: “p4c/testdata/p4_16_samples/switch_ebpf.p4” as follows:

Added new struct below.

struct Token
{
    bit<64>    data;
};

Added the new struct as member of Headers_t

struct Headers_t
{
    Ethernet_h ethernet;
    IPv4_h     ipv4;
    Token      token;
}

Added one line to the control below for use of token.data.

control pipe(inout Headers_t headers, out bool pass)
{
    action Reject(IPv4Address add)
    {
        pass = false;
        headers.ipv4.srcAddr = add;
        headers.token.data[63:32] = add;  // <==== this is the line added
    }
…

I have modified p4c/backends/ebpf/codeGen.h and .cpp.  The .cpp has added this function and thus the modification to the .h file is obvious.

bool CodeGenInspector::preorder(const IR::Slice* expression) {
    int h = expression->getH();
    int l = expression->getL();
  
    std::cout << expression->toString() << h << " " << l  << "\n";    
    builder->append(expression->toString());
    return true;
}

When I use p4c-ebpf on switch_ebpf.p4, I see the printed output from code in the preorder Slice and the preorder AssigmentStatement functions showing correct text for this line of P4 code:

headers.token.data[63:32] = add;

However, the output file from p4c-ebpf adds extra text after the sliced data.  The text is shown in highlight below.

headers.token.data[63:32]headers.token.data6332 = value->u.Reject.add;     

Please test this issue and see where the problem is.

**Comment by mbudiu-vmw** [comment]
I hope that we can close this one.

**Comment by familysingh** [comment]
Sure, please go ahead and close this issue - thanks.
