### ISSUE TITLE
bmv2 backend: cycle containing

### ISSUE THREAD

**Issue by qin-nz** [p4lang/p4c#878]
I have following P4 code.
```
control ctl(){
table t1{
...
}
apply {
if (a==1){t1.apply(); return;}
if (a==2){t1.apply();}
}
}
```
When I compile using bmv2, it will say requires a cycle containing ctl.t1.
`Program cannot be implemented since it requires a cycle containing ctl.t1`

It's by design?  
Please note that I have `return` after `t1.apply()`, so it should't by a cycle.

Farther more, if `t1.apply()` doesn't change the variable `a`, `return` is not needed.

**Comment by jafingerhut** [comment]
The error message may be a bit misleading, in that the "cycle" referred to
doesn't mean that there is a loop in your code.

You will see this error message with p4c-bm2-ss any time you attempt to
call t1.apply() for the same table t1 more than one time in your code.
This is a limitation of the current way that the JSON file used by bmv2
represents the contents of a P4 program.

There is a Github issue for the p4c repository that requests enhancing p4c
and bmv2 to allow the same table to be applied more than once in your code
[1], but it is not a small change to p4c & bmv2 to enable this, so seems
unlikely to be implemented soon (unless someone with the requisite time and
knowledge gets interested in doing it).

Andy

[1] https://github.com/p4lang/p4c/issues/457

**Comment by jafingerhut** [comment]
I should also mention that in many cases, there are ways to restructure
your P4 program so that a single t1.apply() call per table is enough.

Andy

**Comment by qin-nz** [comment]
Thanks @jafingerhut .

**Comment by mbudiu-vmw** [comment]
The fundamental problem is not with the JSON representation, but with the way BMv2 internally represents the program; the JSON is just a serialization of that representation.

No significant change is required in p4c; today we just reject programs that do not satisfy the restrictions. 

In the above program perhaps adding an else in front of the second if may make it work.

That being said, perhaps we should have a better error message.
