### ISSUE TITLE
Make -j4 check fail, at 23, 127 cases

### ISSUE THREAD

**Issue by MaoJianwei** [p4lang/p4c#886]
99% tests passed, 2 tests failed out of 863

Label Time Summary:
XFAIL        =   1.80 sec (4 tests)
bmv2         = 956.34 sec (242 tests)
ebpf         =   5.41 sec (9 tests)
gtest        =   0.50 sec (1 test)
p14_to_16    = 679.55 sec (167 tests)
p4           = 341.74 sec (443 tests)

Total Test time (real) = 367.60 sec

The following tests FAILED:
	 23 - bmv2/testdata/p4_16_samples/mux-bmv2.p4 (Failed)
	127 - bmv2/testdata/p4_14_samples/issue780-8.p4 (Failed)
Errors while running CTest
CMakeFiles/check-all.dir/build.make:57: recipe for target 'CMakeFiles/check-all' failed
make[3]: *** [CMakeFiles/check-all] Error 8
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/check-all.dir/all' failed
make[2]: *** [CMakeFiles/check-all.dir/all] Error 2
CMakeFiles/Makefile2:234: recipe for target 'CMakeFiles/check.dir/rule' failed
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
Makefile:238: recipe for target 'check' failed
make: *** [check] Error 2

**Comment by MaoJianwei** [comment]
git clone AND git submodule, today

**Comment by sethfowler** [comment]
Thanks for reporting this issue! Unfortunately, just the summary doesn't give us enough information to troubleshoot the problem. Please attach the full test log, which you can find in your build directory under `Testing/Temporary/LastTest.log`.

**Comment by MaoJianwei** [comment]
Here you are, and, 
Could you please help me and take a look? at https://github.com/p4lang/p4c/issues/887

I success to compile my p4 program and run p4 switch last night, but I hit this problem today while I try to re-compile my program again. It doubt me!

Thank you!

[LastTest.log.zip](https://github.com/p4lang/p4c/files/1286673/LastTest.log.zip)

**Comment by sethfowler** [comment]
These are the errors you're seeing:

```
127/863 Testing: bmv2/testdata/p4_14_samples/issue780-8.p4
127/863 Test: bmv2/testdata/p4_14_samples/issue780-8.p4
Command: "/home/mao/maoP4/p4c/build/bmv2/testdata/p4_14_samples/issue780-8.p4.test"
Directory: /home/mao/maoP4/p4c/build
"bmv2/testdata/p4_14_samples/issue780-8.p4" start time: Sep 08 11:08 CST
Output:
----------------------------------------------------------
Thrift: Fri Sep  8 11:08:22 2017 TServerSocket::listen() BIND 10022
Calling target program-options parser
Thrift server was started
Thrift returned an exception when trying to bind to port 10022
The exception is: Could not bind: Transport endpoint is not connected
You may have another process already using this port, maybe another instance of bmv2.
pure virtual method called
terminate called without an active exception
Obtaining JSON from switch...
Done
Control utility for runtime P4 table manipulation
RuntimeCmd: 
Check for  /home/mao/maoP4/p4c/testdata/p4_14_samples/issue780-8.stf
*** simple_switch died with return code -6
*** Test failed
<end of output>
Test time =   2.87 sec
----------------------------------------------------------
Test Failed.
```

@antoninbas, any ideas here? Is it possible there's a race happening?

**Comment by antoninbas** [comment]
based on this output, if there was a race wouldn't it be in the test script where available port numbers are selected? Or there was an instance of bmv2 running before the tests started...

**Comment by MaoJianwei** [comment]
thank you! I don't imagine that Ctrl+C will not kill the progress 👍

**Comment by MaoJianwei** [comment]
All test cases pass!

**Comment by mbudiu-vmw** [comment]
The test script uses filesystem operations to atomically allocate random ports for thrift, to run multiple checks concurrently, but maybe that does not always work. Also, if some old simulator processes do not die, their ports remain occupied.

This being said, bmv2 does not have a way to shut down. Our timeouts used to kill it take most of the testing time. We can probably speed-up tests significantly if we add a way for the control-plane to shut down the simulator synchronously.

**Comment by mbudiu-vmw** [comment]
I assume we can close this one.
