### ISSUE TITLE
[Question] How to make conversion between P4 14 and P4 16?

### ISSUE THREAD

**Issue by Wasdns** [p4lang/p4c#893]
Hi, all.

In current p4 development environment, is there a way to make conversion between P4 14 and P4 16? For example, it is very difficult and time-consuming to convert a huge P4-14 program such as switch.p4 to P4-16 program without automated 14-to-16/16-to-14 tools. 

Thank you very much!

**Comment by mbudiu-vmw** [comment]
Use the flags --p4-14 --pp out.p4. This reads a p4 14 program and writes a p4 16 program. Any of the compilers would work.

**Comment by jafingerhut** [comment]
Yes, try this command after following the build instructions for the p4lang/p4c repository.  The executables for p4c-bm2-ss, p4test, and a few others are built in the p4c/build directory:

    p4test --p4v 14 --pp foo-translated-to-p4-16.p4 foo-in-p4-14.p4

**Comment by Wasdns** [comment]
@mbudiu-vmw @jafingerhut 
Thank you for your help! But one error occurs when I try to convert heavy_hitter.p4 in the solution of [tutorials/SIGCOMM_2016/heavy_hitter](https://github.com/p4lang/tutorials/tree/master/SIGCOMM_2016/heavy_hitter). I open another issue for it. Thank you!

**Comment by cristina-dominicini** [comment]
Hi,
Is it possible to go the other way around and convert a P4_16 program to P4_14?
Thank you,
Cristina

**Comment by mbudiu-vmw** [comment]
I am not aware of any tool that can do that automatically.

In general this is impossible; if you are talking about P4-16 programs written for v1model, it should be possible to some degree to perform such a translation automatically.
The P4-16 compiler does much of the work by eliminating many high-level constructs that do not exist in P4-14, e.g., functions, tuples, etc.
P4-16 has constructs that have no equivalent in P4-14, e.g., deparsers. P4-14 infers the deparser order automatically from the parser; if the order is not the one you want there is no way to express it.
There are other similar mismatches between the two languages.
