### ISSUE TITLE
Fix CMakeList.txt for EBPF backend for gdb

### ISSUE THREAD

**Issue by familysingh** [p4lang/p4c#896]
I am using Ubuntu 16.04. First, the instructions in the README.md file in the p4c directory do not suffice to build p4c-ebpf with a -ggdb flag.   By adding to the top p4c  directory CMakeList.txt, p4c-ebpf is built with gdb symbols.

add_cxx_compiler_option ("-ggdb")

However, the other .cpp files in the EBPF backend are still not built with -ggdb flag.  The p4c compiler should ship with at least one backend ,such as EBPF, and its CMakeList.txt file to build a RELEASE or DEBUG image.  Invoking cmake in the p4c/backends/ebpf causes an error shown below.

hemant@thinkpad:~/Downloads/p4c/backends/ebpf$ cmake -DCMAKE_BUILD_TYPE=DEBUG
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:49 (add_cpplint_files):
   Unknown CMake command "add_cpplint_files".

CMake Warning (dev) in CMakeLists.txt:
   No cmake_minimum_required command is present.  A line of code such as

     cmake_minimum_required(VERSION 3.5)

   should be added at the top of the file.  The version specified may be lower
   if you wish to support older CMake versions for this project.  For more
   information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also  
"/home/hemant/Downloads/p4c/backends/ebpf/CMakeFiles/CMakeOutput.log".
hemant@thinkpad:~/Downloads/p4c/backends/ebpf$

**Comment by cc10512** [comment]
The cmake system is setup to be configured only from the top directory. Please run cmake at the p4c level. If you want to build just the ebpf backend, run `make p4c-ebpf` after configuring globally.
