### ISSUE TITLE
Question: Allow STF files to perform all bmv2 control plane operations?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#899]
If I understand the bmv2stf.py code correctly here: https://github.com/p4lang/p4c/blob/master/backends/bmv2/bmv2stf.py#L379-L405

The only operations that can be performed in an STF file are:

+ "packet" to send a packet to the system being tested
+ "expect" to expect a packet coming out of the system being tested
+ "add" to do the same things that a simple_switch_CLI "table_add" command can do (but no more than table_add can do): https://github.com/p4lang/p4c/blob/master/backends/bmv2/bmv2stf.py#L456
+ "setdefault" to do the same things that a simple_switch_CLI "table_set_default" command can do (but no more than table_set_default can do): https://github.com/p4lang/p4c/blob/master/backends/bmv2/bmv2stf.py#L417

There appears to be no current way to use an STF file to test action profiles, and a host of other features of the P4 language.

Is there is some other commonly used method, other than STF files, to write more general tests?  Something that allows everything that simple_switch_CLI can do, perhaps?

**Comment by mbudiu-vmw** [comment]
You can use ptf tests. We don't use these in our testing. However, switch.p4 compiled with p4c-bm2-ss was passing all the ptf tests even 18 months ago.

**Comment by antoninbas** [comment]
I can say that internally we started using PTF tests with the Python APIs generated from P4Runtime. I don't believe there is an example of this on p4lang though.

**Comment by jafingerhut** [comment]
A Cisco summer intern and I did some small modifications to runtime_CLI.py that is used in the implementation of simpe_switch_CLI, to enable it to be used from a Python program instead of interactively, and have written a few automated tests using Scapy for packet send/receive.  I wouldn't call it polished, but it can invoke any command that simple_switch_CLI can.

https://github.com/jafingerhut/VPP_P4

**Comment by jafingerhut** [comment]
Closing this old issue.  I think the right answer for fancier tests is enabling PTF tests, written in Python, which enable full P4Runtime API control operations, and very strong control over their relative order, and the order of when those are done relative to sending in packets and expecting output packets, with the full power of a general purpose programming language behind them.  STF is fine for simple-enough tests, but would take a lot of work to make as powerful as PTF, and PTF already exists, so why bother?
