### ISSUE TITLE
Compiler Bug: Unexpected type for constant varbit<0>

### ISSUE THREAD

**Issue by ebiken** [p4lang/p4c#905]
Below error will be reported while compiling p4-14 code using variable fields.
File "p4var-error.p4.txt" which can be used to reproduce the issue is attached.

```
$ p4c -x p4-14 p4var-error.p4
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  In file: ../ir/expression.cpp:51
Compiler Bug: 1: Unexpected type for constant varbit<0>
[p4var-error.p4.txt](https://github.com/p4lang/p4c/files/1303200/p4var-error.p4.txt)


```
I have simplified from original source code trying to isolate the cause and found it happens when performing arithmetic operations to a value of a variable field.
For example, doing -1 / +1 / *2 to can_data.value will cause the compiler error.
(Tried with commenting in/out below lines in the action)

```
action value_add() {
    //modify_field(can_data.value, can_data.value); // no-error
    //modify_field(can_data.value, can_data.value - 1); // error
    //modify_field(can_data.value, can_data.value + 1); // error
    modify_field(can_data.value, can_data.value * 2); // error
}
```

**Comment by ebiken** [comment]
[p4var-error.p4.txt](https://github.com/p4lang/p4c/files/1303204/p4var-error.p4.txt)

**Comment by mbudiu-vmw** [comment]
Thank you for the bug report.
There are no arithmetic operations on varbit values. In fact, the only operation on varbit values is copying them to other varbit values. But the compiler should not crash.

**Comment by mbudiu-vmw** [comment]
I assume we can close this one.
