### ISSUE TITLE
The T of register<T>, Can not support Struct or header, but just bit<>? (simple_switch)

### ISSUE THREAD

**Issue by MaoJianwei** [p4lang/p4c#907]
Migrated compiler bug, from https://github.com/p4lang/behavioral-model/issues/440

When I declare neighber as a Struct or a header, it will fail while running simple_switch, as follow:

```
mao@mao-vm:~/maoP4/testbmv2/techTest$ sudo simple_switch -L 'trace' --log-file ~/maoP4/mao.log --log-flush -i 0@ens192 -i 1@ens224 ~/maoP4/testbmv2/techTest/output.file
Thrift port was not specified, will use 9090
Calling target program-options parser
Adding interface ens192 as port 0
Adding interface ens224 as port 1
Thrift server was started
simple_switch: ../../include/bm/bm_sim/actions.h:327: T bm::ActionParam::to(bm::ActionEngineState*) const [with T = bm::Field&]: Assertion `tag == ActionParam::FIELD' failed.
Aborted (core dumped)
mao@mao-vm:~/maoP4/testbmv2/techTest$ 
```

Declare is:

```
struct neighbor {
	bit<20> label;
}

OR

header neighbor {
	bit<20> label;
}

register<neighbor>(10) maoReg;
```

Read and write register in Ingress control, by:

```

// simplified code, P4-16

apply {
    neighbor regVal;
    maoReg.read(regVal, 1);
    regVal.label = regVal.label + 1;
    maoReg.write(1, regVal);
}
```

**If I declare _register<bit<20>>(10) maoReg;_, and modify Read and Write call respectively, it will work well.**

The architecture model, <v1model.p4> has:

```
extern register<T> {
    register(bit<32> size);
    void read(out T result, in bit<32> index);
    void write(in bit<32> index, in T value);
}
```

In my understanding, T can be anything including typical data-type, structure, header, etc.
Is that right?

**Comment by jafingerhut** [comment]
Related issues on p4lang/p4-spec repository, that includes the functionality requested above, and perhaps more:
+ https://github.com/p4lang/p4-spec/issues/383
+ https://github.com/p4lang/p4-spec/issues/342

**Comment by MaoJianwei** [comment]
thank you, but I don't think it is related to this problem.

Conclude this problem is :

These fail:
```
struct neighbor {
	bit<20> label;
}

OR

header neighbor {
	bit<20> label;
}

register<neighbor>(10) maoReg;
```

But this successes:

`register<bit<6>>(10) maoReg;`

**Comment by jafingerhut** [comment]
The reason I think it is related is that you have a place where a bit
vector bit<6> works as expected, i.e. as the type stored in a register, and
you wish that you could replace it with a struct of bit vectors, e.g.
'struct neighbor' in your example, but the tools fail to compile it.  So,
you want a 'bit-vector struct' to work in a place where a bit vector works
today.

There are other places in the P4 language where I think this generalization
would be useful, hence the related issues on the P4_16 spec.

Andy

**Comment by mbudiu-vmw** [comment]
The language puts no constraints on T, but a specific back-end may. Anyway, bmv2 should not crash, so this is a bug.

**Comment by mbudiu-vmw** [comment]
I hope that this fix is satisfactory, so I am closing.
The fix is just a good error message.
