### ISSUE TITLE
header with typedef field has wrong width

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#909]
```
typedef bit<9> PortId_t ;
header metadata_t {
    PortId_t port;
    bit<7> _pad1;
}
```
Calling width_bits() on Type_Header for the above header returns 7, instead of 16.
The root cause is `PortId_t` is a `Type_Name` IR node, its width_bits() function returns 0.

**Comment by mbudiu-vmw** [comment]
Do not call width_bits except on canonical types, stored in the type map.

**Comment by hanw** [comment]
How do I to find out the total bit width of `metadata_t`?

Currently, we are doing something as follows:
```
bool preorder(const IR::Type_Header* header) {
   LOG1("header width" << header->width_bits());
   return false;
}
```

**Comment by hanw** [comment]
Is there a pass in frontend that substitute `Type_Name` with the original type `Type_Bits`? `substituteVisitor.h`?

**Comment by mbudiu-vmw** [comment]
Use typeMap->getTypeType(header) to get the canonical type. The canonical type has the typeName substituted.

**Comment by hanw** [comment]
Thanks!
