### ISSUE TITLE
gtestp4c looks for inexistant directory

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#924]
One of the gtestp4c tests fails as follows on my machine:

```
[ RUN      ] P4Runtime.P4_14_MatchFields
cpp: error: /usr/local/share/p4c/p4include/v1model.p4: No such file or directory
cpp: warning: ‘-x c’ after last input file has no effect
cpp: fatal error: no input files
compilation terminated.
error: Preprocessor returned exit code 256; aborting compilation
error: 1 errors encountered, aborting compilation
Couldn't parse test case source
/home/mbudiu/git/p4c/test/gtest/p4runtime.cpp:458: Failure
Value of: test
  Actual: false
Expected: true
[  FAILED  ] P4Runtime.P4_14_MatchFields (17 ms)
```

I have never run 'make install', so the p4c directory under share does not exist indeed.

**Comment by sethfowler** [comment]
Hmm, that scenario indeed has not been tested. I'll check it out. Thanks for letting me know, Mihai.

**Comment by mbudiu-vmw** [comment]
This issue has been solved by brute-force by commenting out a gtest that was failing.
I don't know if this warrants us to mark the issue closed, though. I would rather fix the broken gtest.
