### ISSUE TITLE
Add support for p4runtime code generation to the EBPF backend

### ISSUE THREAD

**Issue by familysingh** [p4lang/p4c#935]
Currently, only the p4c-bm2-ss backend supports p4runtime code generation.  It would be very helpful to add the same support to at least the EBPF backend - thanks.

**Comment by antoninbas** [comment]
I've added support in the p4test backend today (https://github.com/p4lang/p4c/pull/962)
However I'm not sure I see the point of adding support in the eBPF backend if no P4Runtime implementation exists for this target.

**Comment by familysingh** [comment]
Adding to p4test sounds good - thanks!  You can close this issue.
