### ISSUE TITLE
Support for cleanly deprecating features

### ISSUE THREAD

**Issue by ChrisDodd** [p4lang/p4c#940]
P4c should have support for cleanly deprecating features.  One useful idea would be to allow for `@deprecated` (or `@deprecated("message")`) annotations on standard library things.  Then a pass added to the frontend could check for uses of such things and issue warnings about them.

**Comment by mbudiu-vmw** [comment]
If we adopt this we may consider adding the annotation to the spec.
The implementation concatenates all arguments of @deprecated which are strings.

**Comment by mbudiu-vmw** [comment]
Can we close this issue?
