### ISSUE TITLE
Table apply eliminated with dead store

### ISSUE THREAD

**Issue by jamescoole-cisco** [p4lang/p4c#949]
Table applys whose return value is used as part of a dead store get removed along with the store. For the same table, a bare apply is preserved:

``` p4
someTable.apply();
```

While a call made as part of a dead store is eliminated:

``` p4
bool didHit = someTable.apply().hit;
```

The table apply that's being removed has effects through its actions, so it seems like it shouldn't be removed:

``` p4
action setDest() {
	hdr.ethernet.dstAddr = 48w0x_6A_F3_40_04_26_D3;
}
table someTable {
	key = {
		hdr.ethernet.srcAddr : exact;
	}
	actions = {
		setDest;
	}
}
```

I put a small program that shows this [here](https://gist.github.com/jamescoole-cisco/9af6287f9c9f126faa4daf215ba5f2da). Run `p4test --top4 MidEndLast main.p4` with `#define DCE_BUG=1` to see the table removed.

**Comment by mbudiu-vmw** [comment]
@ChrisDodd : this happens in the LocalCopyPropagation pass, so I have assigned it to you.

**Comment by ChrisDodd** [comment]
fix PR created

**Comment by ChrisDodd** [comment]
fix merged to master

**Comment by jamescoole-cisco** [comment]
thanks!
