### ISSUE TITLE
Compiler error attempting to use packet_out parameter in sub-deparser

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#978]
[sub-deparser-args-v1.p4.txt](https://github.com/p4lang/p4c/files/1395546/sub-deparser-args-v1.p4.txt)

Maybe what this program is trying to do is not legal P4_16 code, but if so, it isn't obvious to me why that would be.  The same program has a couple of 'sub-parsers' that pass a parameter of type `packet_in` from the top level parser to the sub-parsers, and that part of the program compiles fine, and even behaves as I would expect when running it with bmv2's simple_switch.

The attached program causes the latest version of p4test as of 2017-Oct-18 to give these error messages when attempting to call the emit method on the parameter named `packet`, with type `packet_out` in a 'sub-deparser' control block:

```
sub-deparser-args-v1.p4(188): error: Could not find declaration for packet
packet.emit(hdr.tcp);
^^^^^^
sub-deparser-args-v1.p4(189): error: Could not find declaration for packet
packet.emit(hdr.udp);
^^^^^^
```

Credit to @hanw for writing a program that had a similar error, leading to this report.

**Comment by mbudiu-vmw** [comment]
PR #974 fixes these. 
We are waiting for a review.

**Comment by jafingerhut** [comment]
Thanks, I had not realized the issues were related.  I will wait until that PR is merged in, test again with this example program, and close the issue if things look better then.

**Comment by mbudiu-vmw** [comment]
it's merged.

**Comment by jafingerhut** [comment]
Retested with latest p4c, and no compiler error any more.   Closing this issue.  Thanks.
