### ISSUE TITLE
make check fails when P4C_16_INCLUDE is set

### ISSUE THREAD

**Issue by rhalstea** [p4lang/p4c#979]
on my machine ~175 test cases fail when P4C_16_INCLUDE is set, and ~380 cases fail when P4C_16_INCLUDE points to /abs/path/build/p4cinclude

**Comment by hanw** [comment]
Are you using osx or ubuntu?

**Comment by rhalstea** [comment]
CentOS

I wrote the wrong environment variable. It should be P4C_16_INCLUDE_PATH
