### ISSUE TITLE
ebpf back-end does not support table initializers

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#991]

**Comment by Netroman** [comment]
Is there any update on this issue, or is there perhaps a guide somewhere on how to add rules during run time for p4c-xdp?

**Comment by mbudiu-vmw** [comment]
This should not be too difficult to implement, but it has had a relatively low priority. If you really need this feature let us know and we'll try to expedite the implementation.

When generating C for a program the compiler will also generate a header file which contains a function called `init_tables()` which contains example code to set the default actions for tables. The code to initialize table entries would have a similar structure.

Also, @fruffy has recently implemented a testing framework for ebpf/xdp programs which generates automatically code to initialize tables from STF files (the STF files describe the initial contents of tables in a user-friendly format). You can inspect the generated code for table intializers.

For example, you can run an ebpf test by hand, let's say:
```
ebpf-test/testdata/p4_16_samples/key_ebpf.p4.test -v -b
```

The -b flag tells the testing framework to keep the temporary files around. You will see that all the C code is generated in a temporary folder which is printed when you start the test. In that temporary folder you can find the `control.h` file which contains table initialization code.

**Comment by Netroman** [comment]
I'm doing a presentation on P4 on Monday and have a XDP section. I would really like to demo the attached program and show people where to find your compiler on github, but didn't realise there will be complications. You can use the attached file for tests as well if you want to.

Not sure if it is too soon to make changes and add it to the docker image as I use that to build?  

I probably have to change the 'written out' IP addresses to hex, but left it as is for now to make clear what I would like to show.

Line 170 causes a c error (not related to this thread, but might be worth mentioning). I can remove that if its not an easy fix.

[xdp_load_balancer_demo.p4.txt](https://github.com/p4lang/p4c/files/2290963/xdp_load_balancer_demo.p4.txt)

**Comment by mbudiu-vmw** [comment]
For the demo you should consider using an STF file to initialize the tables. From your example it looks like you don't want to hardwire these entries in the program, they are part of a runtime policy.

P4 has no notion of IP and does not understand IP addresses written as quads. You would have to write these as integers.

Tables do not have arguments, so there should be no parentheses after a table name. 

Please file a separate issue if you found a bug in the generated code. I could not figure out what the problem is on line 170.

The load_balance_entries table entries do not match the key.

**Comment by mbudiu-vmw** [comment]
Unfortunately the PR https://github.com/vmware/p4c-xdp/pull/74 that uses STF files for testing XDP is still pending, and that PR depends on another PR which has a few changes required #1431. One thing you can do is to apply these PRs and then look at the example STF files in the XDP repo.

Regarding the memcmp bug, I will send a PR right now to fix it.

**Comment by mbudiu-vmw** [comment]
The memcmp problem should be fixed by https://github.com/p4lang/p4c/pull/1444
In general, the ebpf back-end code hasn't been much tested or cared for in the last year. I have started a rewrite, bug I got sidetracked.
