### ISSUE TITLE
graphs backend: requires the boost graph headers, which could not be found

### ISSUE THREAD

**Issue by qin-nz** [p4lang/p4c#996]
I am using macOS to compile p4c.
I already install boost by brew.

I got following error when I run `cmake .. && make`.
I try to delete `build` folder and rerun, but still can't make. 

https://github.com/p4lang/p4c/blob/3882cd5720d474af5ec5c7e3841642c2b9062513/backends/graphs/controls.h#L22-L26

cmake(3.9.4) can recognise  boost
```
-- Found the following Boost libraries:
--   iostreams
--   regex
```

**Comment by cc10512** [comment]
There is not enough information to understand what is your issue. What version of mac OS, clang, boost library you have installed? What is the contents of your `build/config.h`?

**Comment by qin-nz** [comment]
@cc10512 
macOS 10.12.6
clang-900.0.38
boost 1.65.1

I try to remove build folder, so nothing in it.

**Comment by hanw** [comment]
@qin-nz Here is the contents in my `build/config.h`, do you have similar configuration?
```
/* Define to 1 if you have the boost iostreams library */
#define HAVE_LIBBOOST_IOSTREAMS 1

/* Define to 1 if you have the boost graph headers */
#define HAVE_LIBBOOST_GRAPH 1

/* Define to 1 if you have the execinfo.h header */
#define HAVE_EXECINFO_H 1

/* Define to 1 if you have the LIBGC library. */
#define HAVE_LIBGC 1

/* Define to 1 if you have the memchr function. */
#define HAVE_MEMCHR 1

/* Define to 1 if you have the pipe2 function. */
/* #undef HAVE_PIPE2 */

/* Define to 1 if you have the GC_print_stats function. */
#define HAVE_GC_PRINT_STATS 1

/* Define if you have simple switch installed */
#define HAVE_SIMPLE_SWITCH 1

/* Define to 1 if you have the ucontext.h header */
/* #undef HAVE_UCONTEXT_H */
```

**Comment by qin-nz** [comment]
I deleted untracked file of git.
The problem solved.
